In [1]:
import pandas as pd
import cv2
import itertools
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_ann = pd.read_json('dataset/annotation_image_info.json')
df_ann.head(5)

,imgH,source,bbox,source_id,imgW,id
0,640,instagram,"[[62, 266, 325, 639], [224, 219, 564, 636]]",527824347898327040,640,0
1,640,instagram,"[[32, 147, 227, 542], [187, 159, 548, 615]]",527868030970527744,640,1
2,640,instagram,"[[0, 157, 98, 431], [504, 183, 603, 537], [330...",528016560141901824,640,2
3,640,instagram,"[[9, 42, 217, 639], [316, 50, 527, 639], [175,...",528030746167226368,640,3
4,640,instagram,"[[200, 201, 295, 523], [136, 221, 214, 510]]",528034482796761088,640,4

In [3]:
df_rltn = pd.read_json('dataset/relationship.json', orient='index')
df_rltn = df_rltn.sort_index()
df_rltn['id'] = df_rltn.index
df_rltn.head(35)

,1 2,1 3,2 3,2 4,1 4,2 5,1 5,3 4,4 5,4 6,...,4 10,5 11,8 10,5 12,3 12,4 12,3 10,3 11,5 9,id
0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
5,5.0,5.0,5.0,NaN,NaN,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
6,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
7,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
8,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
10,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
11,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
12,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
13,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
15,4.0,4.0,4.0,4.0,4.0,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
16,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
17,1.0,1.0,1.0,1.0,1.0,6.0,6.0,1.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
18,4.0,4.0,4.0,4.0,4.0,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
19,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
20,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
21,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
22,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
23,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
24,4.0,4.0,4.0,4.0,4.0,4.0,NaN,4.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
25,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
27,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27
28,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28
29,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29
32,3.0,6.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32
33,6.0,6.0,3.0,6.0,4.0,NaN,NaN,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33
34,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34
35,6.0,6.0,1.0,NaN,6.0,6.0,6.0,NaN,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
36,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36

In [4]:
def image_resize(image, width = None, height = None, inter = cv2.INTER_AREA):
    # initialize the dimensions of the image to be resized and
    # grab the image size
    dim = None
    (h, w) = image.shape[:2]
    if(h==0):
        h=1

    # if both the width and height are None, then return the
    # original image
    if width is None and height is None:
        return image

    # check to see if the width is None
    if width is None:
        # calculate the ratio of the height and construct the
        # dimensions
        r = height / float(h)
        dim = (int(w * r), height)

    # otherwise, the height is None
    else:
        # calculate the ratio of the width and construct the
        # dimensions
        r = width / float(w)
        dim = (width, int(h * r))

    # resize the image
    resized = cv2.resize(image, dim, interpolation = inter)

    # return the resized image
    return resized

In [5]:
def nameIDfixer(id__, total_digits):
    len_id = len(id__)
    newId = ""
    for i in range(total_digits-len_id):
        newId+="0"
        
    return newId+id__

def pairMaker(numOfppl):
    test_list = []
    for i in range(1, numOfppl+1):
        test_list.append(i)
        
    res = [(a, b) for idx, a in enumerate(test_list) for b in test_list[idx + 1:]]
    return res
    
def imgprocessor(_id, numOfp, bbox, nextId, df_row_rltn):
    savePath = "dataset/an/"
    img = cv2.imread("dataset/image/"+nameIDfixer(_id, 5)+".jpg")
    immgs = []
    for index, boxCord in enumerate(bbox):
#         print(index+1, boxCord, savePath)
        crop_img = img[boxCord[1]:boxCord[3], boxCord[0]:boxCord[2]]
        immgs.append(crop_img)
        
    pairCode = pairMaker(numOfp)
    df_ne_an = pd.DataFrame() #dataframe new
    for pair in pairCode:
        img1_ = immgs[list(pair)[0]-1]
        img2_ = immgs[list(pair)[1]-1]
#         print(df_row_rltn[str(list(pair)[0])+" "+str(list(pair)[1])][0])
#         break
        if(pd.isnull(df_row_rltn[str(list(pair)[0])+" "+str(list(pair)[1])].values)):
            continue
#         print("In func: ", str(list(pair)[0])+" "+str(list(pair)[1]), pd.isnull(df_row_rltn[str(list(pair)[0])+" "+str(list(pair)[1])].values))
        rro = {'id_name': str(nextId), 'relation': df_row_rltn[str(list(pair)[0])+" "+str(list(pair)[1])].values[0]}
        df_ne_an = df_ne_an.append(rro, ignore_index=True)
        height1, width1 = img1_.shape[0],img1_.shape[1]
        height2, width2 = img2_.shape[0],img2_.shape[1]
        min_height = max(height1, height2)
#         min_width = min(width1, width2)
        img1_ = image_resize(img1_, height = min_height)
        img2_ = image_resize(img2_, height = min_height)
        im_v = cv2.hconcat([img1_, img2_])
#         print(nextId)
        cv2.imwrite(savePath+str(nextId)+".jpg", im_v)
        nextId+=1
    return nextId, df_ne_an
        
    
    
# imgprocessor("2", 3, [[0, 157, 98, 431], [504, 183, 603, 537], [330, 172, 435, 438]], 1)

In [6]:
indx = 1
df_ne_an = pd.DataFrame()
for index, row in df_ann.iterrows():
#     print("Chk:", row['id'], row['id'] in df_rltn['id'])
#     if(row['id']>10000):
#         break
    if(row['id'] in df_rltn['id']):
        indx, out_ = imgprocessor(str(row['id']), len(row['bbox']), row['bbox'], indx, df_rltn[df_rltn.id==row['id']])
        df_ne_an = pd.concat([df_ne_an,out_], axis=0)
        print("Chk", str(row['id']), row['bbox'])

df_ne_an

Chk 0 [[62, 266, 325, 639], [224, 219, 564, 636]]
Chk 1 [[32, 147, 227, 542], [187, 159, 548, 615]]
Chk 2 [[0, 157, 98, 431], [504, 183, 603, 537], [330, 172, 435, 438]]
Chk 3 [[9, 42, 217, 639], [316, 50, 527, 639], [175, 38, 352, 639]]
Chk 4 [[200, 201, 295, 523], [136, 221, 214, 510]]
Chk 5 [[226, 344, 369, 640], [348, 356, 456, 606], [550, 319, 633, 609], [9, 321, 87, 489], [225, 297, 299, 370], [352, 286, 449, 362]]
Chk 6 [[141, 212, 385, 620], [184, 221, 400, 586], [322, 214, 619, 640]]
Chk 7 [[370, 71, 640, 640], [125, 164, 403, 640], [144, 0, 215, 95]]
Chk 8 [[316, 41, 503, 264], [30, 31, 274, 239]]
Chk 9 [[0, 191, 300, 514], [290, 184, 538, 516]]
Chk 10 [[302, 167, 615, 640], [75, 176, 322, 533]]
Chk 11 [[42, 155, 225, 289], [307, 241, 478, 569], [75, 205, 342, 595]]
Chk 12 [[364, 208, 459, 499], [267, 287, 367, 468]]
Chk 13 [[87, 51, 523, 639], [309, 116, 575, 639]]
Chk 14 [[0, 172, 160, 522], [458, 292, 639, 550], [389, 162, 498, 272], [434, 277, 525, 511], [248, 223, 307, 308], [148, 179, 255, 327], [136, 237, 243, 382]]
Chk 15 [[319, 399, 380, 551], [211, 412, 249, 531], [123, 421, 154, 524], [77, 419, 107, 514]]
Chk 16 [[89, 72, 594, 594], [342, 245, 615, 562]]
Chk 17 [[0, 144, 176, 575], [162, 124, 308, 399], [472, 219, 640, 595], [464, 74, 640, 248], [55, 53, 145, 153]]
Chk 18 [[108, 274, 160, 332], [155, 287, 209, 442], [325, 289, 382, 453], [375, 282, 424, 440]]
Chk 19 [[177, 169, 376, 521], [426, 212, 556, 465]]
Chk 20 [[215, 44, 472, 519], [8, 33, 251, 613]]
Chk 21 [[222, 116, 354, 404], [155, 8, 436, 640]]
Chk 22 [[249, 194, 428, 626], [125, 2, 516, 595]]
Chk 23 [[527, 293, 612, 530], [490, 326, 528, 458], [66, 295, 110, 421], [128, 318, 187, 431], [202, 301, 262, 467], [256, 321, 319, 451], [359, 314, 405, 471]]
Chk 24 [[0, 328, 139, 640], [120, 286, 192, 426], [246, 280, 342, 462], [357, 275, 455, 448], [465, 273, 570, 489]]
Chk 25 [[323, 306, 590, 462], [489, 226, 613, 510]]
Chk 26 [[304, 112, 428, 325], [163, 38, 386, 369]]
Chk 27 [[15, 262, 305, 559], [297, 242, 443, 572], [548, 240, 636, 568]]
Chk 28 [[332, 118, 618, 639], [123, 253, 298, 639]]
Chk 29 [[226, 0, 387, 640], [48, 186, 268, 640]]
Chk 32 [[27, 125, 251, 439], [210, 56, 640, 581], [527, 151, 630, 311]]
Chk 33 [[249, 139, 387, 336], [445, 170, 551, 342], [554, 191, 633, 370], [54, 118, 251, 373]]
Chk 34 [[178, 107, 440, 537], [140, 245, 335, 568]]
Chk 35 [[319, 97, 574, 455], [107, 218, 190, 378], [50, 195, 138, 381], [225, 267, 286, 371], [1, 286, 46, 357]]
Chk 36 [[64, 1, 365, 304], [301, 0, 606, 384]]
Chk 37 [[61, 124, 307, 573], [265, 149, 474, 523], [417, 149, 587, 585]]
Chk 38 [[212, 238, 477, 638], [288, 34, 625, 629], [33, 25, 333, 634], [68, 119, 125, 183]]
Chk 39 [[216, 4, 493, 539], [184, 411, 293, 608]]
Chk 40 [[90, 359, 321, 631], [311, 330, 459, 611], [247, 363, 329, 594]]
Chk 41 [[60, 151, 589, 634], [7, 34, 323, 584]]
Chk 42 [[72, 36, 531, 657], [347, 58, 999, 665]]
Chk 43 [[0, 31, 355, 599], [363, 66, 799, 599]]
Chk 44 [[35, 28, 447, 360], [306, 64, 493, 359]]
Chk 45 [[262, 0, 476, 363], [165, 21, 316, 352], [5, 27, 202, 415]]
Chk 47 [[190, 0, 486, 316], [11, 0, 335, 334]]
Chk 49 [[518, 29, 999, 645], [140, 90, 460, 470], [437, 48, 693, 524]]
Chk 50 [[55, 32, 546, 663], [406, 54, 986, 653]]
Chk 52 [[0, 74, 119, 400], [50, 12, 300, 400]]
Chk 55 [[307, 412, 992, 1496], [81, 173, 686, 1497]]
Chk 56 [[227, 0, 492, 325], [0, 0, 382, 298]]
Chk 57 [[0, 25, 349, 428], [315, 0, 647, 431]]
Chk 59 [[0, 62, 332, 690], [226, 9, 533, 678]]
Chk 61 [[31, 46, 545, 691], [522, 0, 988, 692]]
Chk 63 [[0, 0, 158, 742], [655, 465, 972, 746]]
Chk 64 [[225, 48, 818, 688], [0, 4, 475, 718]]
Chk 65 [[555, 64, 997, 697], [38, 42, 855, 688]]
Chk 67 [[6, 11, 432, 650], [721, 128, 939, 600], [243, 209, 722, 650], [543, 122, 732, 650]]
Chk 72 [[0, 0, 278, 400], [200, 80, 466, 377]]
Chk 75 [[16, 37, 679, 674], [338, 30, 983, 667]]
Chk 76 [[7, 6, 181, 265], [97, 47, 269, 268]]
Chk 77 [[27, 30, 678, 622], [470, 99, 999, 628]]
Chk 80 [[108, 9, 691, 574], [381, 205, 948, 575]]
Chk 82 [[6, 0, 184, 179], [74, 0, 272, 168]]
Chk 83 [[31, 5, 326, 220], [0, 1, 142, 215]]
Chk 84 [[9, 18, 155, 304], [75, 21, 219, 329]]
Chk 85 [[0, 64, 190, 240], [154, 0, 335, 240]]
Chk 86 [[80, 66, 675, 563], [89, 51, 418, 402]]
Chk 87 [[39, 6, 326, 563], [224, 228, 629, 535]]
Chk 88 [[74, 43, 573, 665], [503, 36, 917, 662]]
Chk 89 [[3, 8, 198, 249], [128, 0, 352, 228]]
Chk 90 [[382, 120, 639, 359], [190, 91, 433, 349], [62, 31, 215, 359], [7, 34, 102, 337], [413, 0, 581, 220]]
Chk 91 [[61, 145, 997, 730], [0, 0, 544, 654]]
Chk 92 [[58, 16, 319, 414], [183, 117, 541, 413]]
Chk 93 [[441, 0, 999, 744], [30, 265, 770, 757]]
Chk 94 [[466, 30, 968, 665], [34, 321, 770, 655]]
Chk 96 [[19, 54, 248, 329], [227, 9, 468, 417]]
Chk 97 [[0, 14, 235, 337], [199, 39, 396, 341]]
Chk 98 [[393, 65, 813, 599], [85, 314, 426, 565]]
Chk 100 [[227, 4, 807, 548], [81, 41, 563, 489]]
Chk 101 [[189, 68, 357, 252], [175, 0, 285, 127], [133, 66, 229, 208], [0, 0, 152, 259]]
Chk 102 [[53, 5, 608, 299], [414, 67, 662, 299]]
Chk 105 [[266, 49, 498, 362], [211, 128, 296, 302], [0, 0, 260, 351]]
Chk 106 [[45, 7, 268, 266], [246, 30, 386, 224]]
Chk 107 [[189, 127, 635, 617], [657, 156, 999, 665]]
Chk 108 [[196, 12, 960, 499], [25, 0, 442, 480]]
Chk 109 [[187, 115, 571, 499], [544, 58, 883, 499]]
Chk 111 [[0, 0, 238, 361], [174, 8, 318, 258], [230, 0, 516, 386]]
Chk 112 [[301, 16, 793, 549], [0, 26, 476, 522]]
Chk 113 [[136, 121, 398, 363], [366, 37, 535, 333]]
Chk 114 [[213, 8, 988, 1218], [14, 400, 401, 1409]]
Chk 116 [[293, 331, 383, 492], [66, 324, 115, 485]]
Chk 117 [[170, 9, 315, 182], [322, 7, 467, 190], [13, 32, 126, 190], [329, 0, 402, 105], [430, 0, 485, 70], [432, 0, 462, 39]]
Chk 118 [[434, 121, 499, 314], [8, 114, 83, 317], [133, 140, 204, 304], [346, 104, 370, 175]]
Chk 119 [[0, 227, 317, 375], [0, 47, 500, 375]]
Chk 120 [[211, 2, 282, 231], [290, 179, 367, 263]]
Chk 121 [[0, 157, 96, 375], [33, 102, 201, 314], [304, 69, 475, 330]]
Chk 123 [[298, 103, 354, 291], [2, 145, 29, 201], [337, 165, 406, 339]]
Chk 124 [[62, 161, 178, 349], [142, 104, 355, 447]]
Chk 125 [[227, 160, 274, 227], [122, 164, 154, 209]]
Chk 126 [[369, 71, 470, 300], [50, 73, 202, 306], [323, 161, 345, 213]]
Chk 127 [[140, 7, 248, 327], [20, 39, 116, 342], [315, 94, 347, 139]]
Chk 128 [[138, 67, 200, 241], [315, 79, 420, 359], [48, 198, 151, 374]]
Chk 129 [[309, 6, 465, 332], [274, 32, 371, 185], [46, 45, 140, 332]]
Chk 130 [[371, 33, 449, 246], [34, 20, 129, 374], [139, 52, 239, 343], [191, 51, 234, 203], [337, 104, 385, 220], [1, 48, 33, 167]]
Chk 132 [[25, 213, 89, 315], [22, 81, 411, 375], [266, 30, 500, 375]]
Chk 133 [[104, 86, 191, 251], [375, 80, 449, 265]]
Chk 134 [[202, 14, 434, 363], [42, 157, 211, 343], [187, 146, 311, 360]]
Chk 135 [[0, 39, 233, 375], [128, 60, 284, 238], [238, 79, 383, 216], [420, 99, 500, 269]]
Chk 136 [[76, 113, 171, 270], [190, 115, 274, 327], [249, 95, 355, 324], [375, 98, 432, 297], [404, 79, 464, 315], [457, 108, 500, 287]]
Chk 137 [[99, 198, 159, 295], [322, 199, 388, 333], [443, 222, 492, 318]]
Chk 138 [[0, 13, 89, 334], [151, 72, 291, 334], [300, 67, 414, 334], [360, 15, 459, 310]]
Chk 139 [[190, 83, 330, 322], [389, 100, 491, 369], [57, 123, 181, 320]]
Chk 140 [[13, 180, 111, 339], [301, 163, 345, 274], [333, 163, 367, 278]]
Chk 141 [[166, 102, 497, 499], [4, 21, 185, 314]]
Chk 142 [[20, 124, 78, 194], [75, 132, 143, 217], [29, 185, 107, 323], [72, 186, 199, 424]]
Chk 143 [[0, 102, 73, 375], [84, 129, 182, 251], [164, 110, 323, 255], [310, 113, 435, 250]]
Chk 144 [[23, 193, 257, 368], [44, 77, 344, 361], [129, 10, 334, 247]]
Chk 145 [[141, 118, 407, 334], [3, 8, 364, 335]]
Chk 148 [[0, 90, 202, 329], [24, 8, 285, 265]]
Chk 149 [[210, 5, 475, 431], [155, 60, 296, 346]]
Chk 150 [[50, 120, 128, 312], [120, 149, 161, 296]]
Chk 151 [[8, 60, 165, 347], [160, 59, 245, 185], [135, 96, 315, 370], [298, 17, 368, 105], [304, 56, 385, 178], [328, 42, 465, 375]]
Chk 152 [[0, 99, 210, 332], [355, 94, 500, 332], [195, 44, 379, 231]]
Chk 153 [[338, 181, 500, 334], [159, 89, 312, 334], [218, 126, 288, 209]]
Chk 155 [[245, 114, 288, 161], [163, 160, 234, 271]]
Chk 157 [[326, 84, 454, 333], [25, 131, 155, 332], [15, 89, 42, 151]]
Chk 158 [[334, 90, 422, 306], [124, 79, 201, 304], [221, 74, 310, 242]]
Chk 159 [[98, 69, 291, 466], [229, 75, 452, 461]]
Chk 163 [[300, 94, 395, 331], [224, 101, 299, 316]]
Chk 164 [[95, 105, 206, 445], [180, 110, 268, 447]]
Chk 165 [[63, 79, 232, 334], [163, 132, 353, 334], [299, 24, 478, 255]]
Chk 166 [[0, 53, 243, 335], [136, 149, 231, 290], [247, 2, 500, 335]]
Chk 168 [[111, 37, 214, 332], [196, 62, 257, 264], [247, 70, 299, 217], [290, 66, 378, 268], [374, 88, 417, 214], [424, 55, 500, 334], [401, 70, 460, 281]]
Chk 169 [[211, 163, 257, 229], [172, 186, 220, 270]]

Chk 170 [[308, 24, 427, 293], [183, 22, 325, 281]]
Chk 171 [[184, 256, 298, 372], [78, 278, 148, 364]]
Chk 172 [[420, 0, 500, 121], [351, 0, 428, 95], [247, 20, 372, 171], [260, 112, 349, 251], [213, 112, 277, 211]]
Chk 173 [[152, 51, 298, 146], [252, 40, 395, 139]]
Chk 174 [[112, 50, 376, 372], [62, 94, 184, 362]]
Chk 175 [[236, 31, 470, 321], [7, 46, 201, 331]]
Chk 176 [[36, 134, 150, 313], [137, 126, 314, 342], [228, 93, 375, 287]]
Chk 177 [[107, 30, 214, 277], [231, 32, 362, 265]]
Chk 180 [[364, 163, 466, 318], [463, 55, 500, 193], [305, 78, 388, 333], [163, 109, 252, 333], [0, 43, 135, 333]]
Chk 181 [[455, 238, 499, 329], [95, 100, 273, 324], [241, 111, 413, 328]]
Chk 182 [[132, 111, 220, 304], [323, 109, 397, 255]]
Chk 183 [[42, 28, 147, 289], [151, 16, 344, 333]]
Chk 185 [[35, 91, 211, 292], [168, 21, 490, 338]]
Chk 188 [[305, 40, 446, 314], [44, 25, 238, 297]]
Chk 189 [[0, 61, 90, 294], [149, 94, 296, 290]]
Chk 190 [[328, 48, 469, 340], [31, 62, 235, 387]]
Chk 191 [[246, 174, 363, 329], [25, 156, 91, 308], [185, 192, 254, 331], [163, 188, 199, 297]]
Chk 192 [[81, 27, 212, 326], [372, 211, 485, 290], [231, 118, 321, 333]]
Chk 193 [[0, 168, 103, 332], [111, 28, 220, 278], [220, 57, 364, 332], [347, 70, 461, 332]]
Chk 194 [[267, 113, 427, 332], [95, 95, 254, 332]]
Chk 195 [[279, 57, 431, 280], [71, 11, 282, 280]]
Chk 196 [[37, 251, 102, 380], [98, 271, 146, 384], [108, 259, 195, 480], [179, 251, 241, 493], [245, 224, 326, 500]]
Chk 197 [[268, 39, 397, 225], [94, 6, 299, 261]]
Chk 198 [[418, 30, 499, 134], [275, 102, 365, 260]]
Chk 200 [[101, 65, 290, 295], [239, 47, 354, 270]]
Chk 202 [[128, 8, 279, 311], [23, 37, 157, 311]]
Chk 203 [[125, 145, 171, 215], [196, 63, 325, 269], [321, 23, 414, 258]]
Chk 204 [[419, 79, 483, 313], [370, 72, 440, 295], [299, 67, 408, 318], [250, 79, 336, 197], [169, 68, 230, 196], [145, 77, 230, 203]]
Chk 206 [[115, 112, 246, 332], [141, 126, 277, 246]]
Chk 207 [[25, 0, 240, 339], [264, 0, 478, 362]]
Chk 208 [[58, 189, 143, 278], [117, 126, 256, 270]]
Chk 209 [[0, 204, 71, 281], [0, 0, 20, 20], [166, 188, 210, 229], [277, 184, 319, 224], [197, 151, 268, 293], [283, 131, 500, 333]]
Chk 210 [[228, 146, 328, 289], [259, 83, 375, 500], [0, 80, 118, 500]]
Chk 211 [[273, 74, 500, 318], [0, 29, 275, 332]]
Chk 212 [[141, 69, 314, 331], [0, 3, 122, 328], [344, 117, 416, 330], [255, 89, 329, 331], [128, 94, 189, 327]]
Chk 213 [[41, 168, 70, 235], [171, 122, 216, 222], [215, 42, 286, 243], [112, 167, 145, 235], [272, 57, 320, 222], [149, 152, 175, 221]]
Chk 214 [[344, 74, 426, 246], [16, 77, 81, 301]]
Chk 215 [[302, 88, 500, 321], [34, 49, 292, 321]]
Chk 216 [[1, 36, 141, 281], [85, 38, 167, 147], [144, 31, 336, 281], [218, 32, 353, 281], [310, 42, 410, 240], [358, 41, 446, 210]]
Chk 217 [[0, 55, 180, 271], [0, 89, 192, 308], [246, 123, 344, 266], [221, 84, 461, 331], [427, 142, 500, 291]]
Chk 218 [[308, 86, 406, 246], [99, 94, 186, 295], [223, 176, 281, 238]]
Chk 219 [[138, 73, 219, 206], [223, 57, 314, 195], [16, 71, 182, 299]]
Chk 220 [[39, 159, 176, 482], [213, 181, 326, 456]]
Chk 221 [[37, 130, 167, 500], [132, 129, 279, 500]]
Chk 222 [[0, 107, 102, 266], [143, 111, 293, 365], [231, 117, 315, 224], [443, 114, 500, 279]]
Chk 224 [[13, 94, 220, 333], [195, 49, 406, 333]]
Chk 225 [[191, 27, 370, 429], [20, 179, 159, 311]]
Chk 226 [[0, 111, 151, 475], [214, 177, 314, 431]]
Chk 227 [[177, 33, 283, 232], [329, 104, 465, 375], [59, 133, 278, 380], [15, 79, 79, 189], [0, 84, 40, 143], [306, 70, 356, 161], [397, 71, 454, 122], [422, 76, 436, 99]]
Chk 228 [[214, 52, 398, 385], [117, 67, 247, 379]]
Chk 229 [[0, 13, 199, 498], [210, 12, 387, 496]]
Chk 230 [[409, 65, 500, 289], [292, 85, 381, 284], [156, 71, 251, 273], [138, 31, 205, 150]]
Chk 231 [[88, 36, 307, 499], [2, 161, 189, 486]]
Chk 232 [[110, 54, 199, 170], [326, 105, 424, 295], [157, 197, 275, 329]]
Chk 233 [[95, 150, 263, 298], [251, 66, 460, 333]]
Chk 234 [[187, 128, 260, 280], [337, 51, 397, 238], [246, 70, 333, 285]]
Chk 235 [[166, 74, 321, 332], [317, 68, 488, 332]]
Chk 236 [[148, 89, 232, 275], [45, 66, 124, 286]]
Chk 237 [[13, 8, 98, 187], [271, 0, 378, 244], [135, 28, 253, 231], [88, 22, 154, 178], [106, 34, 205, 195]]
Chk 238 [[0, 0, 210, 170], [130, 0, 403, 214], [266, 0, 500, 286]]
Chk 239 [[334, 133, 391, 189], [263, 126, 297, 170], [196, 118, 227, 166], [155, 114, 182, 160]]
Chk 240 [[308, 136, 347, 250], [134, 203, 177, 295], [282, 135, 309, 244], [359, 151, 400, 236], [41, 205, 117, 286]]
Chk 241 [[367, 22, 499, 330], [174, 23, 347, 324], [3, 53, 178, 329]]
Chk 242 [[218, 142, 330, 334], [436, 126, 499, 334]]
Chk 243 [[270, 9, 399, 190], [400, 4, 491, 267], [6, 29, 138, 223]]
Chk 244 [[47, 153, 304, 374], [308, 169, 490, 374], [0, 231, 50, 366]]
Chk 245 [[102, 112, 183, 345], [54, 123, 127, 370]]
Chk 246 [[328, 159, 418, 281], [167, 186, 219, 277], [114, 212, 147, 274], [79, 190, 118, 299], [40, 173, 90, 299], [0, 216, 20, 240]]
Chk 247 [[0, 46, 77, 197], [69, 76, 119, 192], [3, 177, 119, 421], [123, 15, 194, 186], [331, 73, 394, 200], [407, 17, 488, 199]]
Chk 248 [[140, 146, 200, 330], [242, 139, 295, 206]]
Chk 249 [[295, 49, 423, 291], [132, 35, 282, 304]]
Chk 250 [[125, 32, 258, 374], [7, 69, 95, 374], [262, 40, 398, 369], [191, 44, 235, 141], [66, 26, 196, 371], [243, 34, 282, 133]]
Chk 251 [[40, 329, 202, 430], [30, 327, 99, 450]]
Chk 252 [[0, 121, 252, 375], [235, 45, 500, 375], [223, 152, 343, 289]]
Chk 253 [[10, 92, 236, 355], [316, 67, 500, 325]]
Chk 258 [[75, 120, 237, 375], [200, 139, 312, 342], [229, 78, 411, 375]]
Chk 259 [[202, 46, 494, 374], [78, 15, 316, 258]]
Chk 260 [[142, 180, 228, 329], [314, 57, 392, 334], [279, 176, 375, 347]]
Chk 261 [[100, 108, 236, 318], [254, 89, 354, 329], [332, 141, 436, 328], [50, 117, 137, 343]]
Chk 262 [[0, 41, 139, 386], [116, 6, 163, 66], [127, 40, 250, 241], [215, 26, 326, 231]]
Chk 263 [[244, 15, 389, 314], [124, 137, 227, 317], [203, 28, 286, 242], [137, 58, 194, 144]]
Chk 264 [[8, 41, 297, 332], [115, 5, 500, 332]]
Chk 265 [[129, 22, 350, 465], [50, 42, 218, 440]]
Chk 267 [[67, 74, 142, 263], [208, 88, 284, 217], [195, 148, 325, 294], [215, 153, 345, 311]]
Chk 268 [[243, 204, 326, 314], [0, 130, 102, 374], [140, 211, 233, 299], [72, 172, 129, 262]]
Chk 269 [[23, 143, 116, 303], [0, 55, 97, 500]]
Chk 270 [[149, 238, 235, 391], [53, 194, 162, 318]]
Chk 271 [[35, 13, 370, 499], [105, 248, 374, 481]]
Chk 272 [[37, 152, 276, 333], [273, 132, 500, 333]]
Chk 273 [[138, 35, 268, 244], [315, 46, 457, 249], [7, 97, 157, 336]]
Chk 274 [[244, 165, 311, 333], [204, 120, 278, 287], [333, 30, 394, 113], [303, 2, 351, 55], [409, 34, 493, 81], [70, 27, 124, 121], [0, 57, 25, 158]]
Chk 275 [[76, 77, 248, 312], [410, 212, 490, 334]]
Chk 276 [[139, 2, 486, 360], [77, 147, 272, 369]]
Chk 277 [[47, 46, 186, 331], [312, 72, 452, 331]]
Chk 278 [[209, 176, 329, 325], [58, 185, 225, 348], [36, 154, 110, 248], [328, 143, 378, 220]]
Chk 279 [[110, 88, 213, 333], [193, 111, 259, 304], [263, 107, 326, 267], [350, 92, 442, 208], [67, 143, 99, 191], [241, 130, 273, 195], [298, 115, 345, 203]]
Chk 280 [[70, 121, 130, 215], [219, 19, 316, 161], [201, 72, 363, 333]]
Chk 281 [[0, 142, 141, 376], [196, 45, 363, 376]]
Chk 282 [[220, 41, 324, 342], [335, 46, 419, 347]]
Chk 283 [[165, 207, 217, 265], [308, 195, 362, 272], [338, 200, 436, 280]]
Chk 285 [[70, 61, 262, 497], [52, 89, 168, 354]]
Chk 287 [[299, 13, 409, 324], [164, 25, 265, 332], [456, 37, 497, 216], [146, 13, 169, 92], [187, 18, 214, 67], [406, 8, 455, 112], [59, 8, 86, 103], [239, 7, 261, 70]]
Chk 288 [[18, 10, 191, 356], [169, 178, 244, 356], [327, 69, 439, 356]]
Chk 289 [[211, 107, 500, 375], [243, 64, 432, 223], [79, 52, 208, 242], [110, 13, 176, 102], [0, 17, 55, 111], [22, 95, 161, 298], [8, 101, 196, 336]]
Chk 290 [[90, 113, 206, 352], [148, 89, 227, 205], [257, 12, 333, 178], [280, 112, 500, 373]]
Chk 291 [[26, 55, 287, 357], [256, 27, 474, 346], [448, 51, 500, 357]]
Chk 292 [[0, 87, 206, 375], [138, 65, 309, 273], [325, 71, 500, 375]]
Chk 293 [[67, 61, 135, 214], [288, 55, 355, 211], [153, 63, 214, 215], [382, 66, 434, 205]]
Chk 294 [[174, 10, 492, 328], [7, 24, 317, 330]]
Chk 295 [[34, 129, 91, 215], [92, 136, 142, 216], [146, 124, 194, 212], [213, 131, 264, 217]]
Chk 296 [[92, 146, 158, 272], [130, 144, 313, 341], [223, 105, 297, 281], [349, 183, 379, 265]]
Chk 297 [[33, 54, 111, 244], [183, 74, 292, 235], [430, 46, 497, 275], [117, 49, 194, 241]]
Chk 298 [[159, 169, 203, 345], [96, 187, 136, 344], [207, 142, 243, 274], [130, 222, 166, 341]]
Chk 299 [[87, 0, 146, 37], [85, 0, 136, 36], [54, 0, 147, 500], [54, 11, 196, 500]]
Chk 300 [[14, 44, 103, 239], [113, 33, 327, 332], [255, 60, 498, 295]]
Chk 301 [[147, 108, 288, 323], [232, 48, 434, 270]]
Chk 302 [[72, 13, 354, 339], [215, 85, 410, 320]]
Chk 303 [[8, 114, 208, 500], [177, 155, 338, 404]]
Chk 305 [[96, 4, 499, 331], [82, 97, 282, 319]]

Chk 306 [[34, 12, 228, 255], [216, 22, 349, 260], [359, 56, 477, 255]]
Chk 307 [[54, 94, 120, 220], [98, 125, 166, 239], [374, 73, 458, 225]]
Chk 308 [[291, 141, 360, 273], [177, 166, 280, 263]]
Chk 309 [[38, 103, 112, 277], [142, 16, 267, 354]]
Chk 310 [[86, 55, 221, 332], [241, 7, 410, 219]]
Chk 311 [[398, 168, 435, 250], [423, 170, 466, 256]]
Chk 312 [[173, 65, 282, 333], [256, 61, 354, 333], [347, 73, 443, 333], [71, 64, 168, 333], [10, 41, 102, 193]]
Chk 314 [[45, 71, 151, 296], [106, 152, 285, 424]]
Chk 317 [[46, 112, 80, 240], [98, 91, 153, 239], [3, 109, 30, 200], [277, 89, 304, 184], [246, 89, 271, 191]]
Chk 318 [[60, 42, 422, 328], [261, 27, 468, 331]]
Chk 320 [[53, 126, 113, 214], [119, 85, 177, 208], [149, 89, 192, 186], [183, 73, 239, 200], [286, 65, 349, 200], [355, 75, 416, 198], [443, 100, 487, 182]]
Chk 321 [[94, 71, 237, 406], [247, 5, 483, 385]]
Chk 322 [[111, 143, 294, 476], [24, 140, 178, 499]]
Chk 323 [[108, 100, 177, 216], [200, 168, 375, 375]]
Chk 324 [[64, 101, 136, 433], [1, 114, 32, 257], [254, 143, 322, 259]]
Chk 325 [[86, 169, 194, 266], [282, 159, 397, 254]]
Chk 326 [[0, 91, 193, 331], [157, 23, 381, 331], [260, 0, 500, 331]]
Chk 327 [[257, 67, 374, 287], [119, 115, 219, 209], [211, 130, 265, 196]]
Chk 328 [[24, 39, 298, 332], [267, 0, 499, 329]]
Chk 329 [[343, 53, 477, 331], [37, 41, 202, 325], [186, 86, 323, 331]]
Chk 330 [[92, 171, 139, 343], [216, 147, 287, 336], [142, 164, 222, 354], [125, 155, 188, 331]]
Chk 331 [[394, 184, 421, 226], [360, 180, 390, 221], [182, 141, 214, 181], [147, 124, 173, 169]]
Chk 332 [[401, 39, 482, 281], [129, 195, 209, 286], [65, 167, 126, 293], [209, 193, 294, 302]]
Chk 333 [[213, 114, 274, 273], [15, 86, 126, 330], [321, 120, 373, 258]]
Chk 334 [[11, 163, 62, 284], [203, 149, 259, 268], [348, 166, 448, 276]]
Chk 335 [[110, 256, 220, 397], [201, 84, 309, 355], [127, 100, 188, 185], [41, 109, 91, 170], [421, 136, 475, 201]]
Chk 336 [[51, 301, 120, 401], [264, 220, 295, 282], [451, 280, 490, 373], [173, 271, 294, 420]]
Chk 337 [[139, 128, 239, 427], [42, 152, 231, 361]]
Chk 338 [[107, 52, 313, 289], [121, 33, 500, 350]]
Chk 339 [[314, 79, 476, 347], [62, 68, 199, 352]]
Chk 340 [[97, 44, 292, 245], [246, 96, 409, 254]]
Chk 341 [[47, 39, 174, 366], [208, 41, 310, 366], [363, 66, 470, 337]]
Chk 342 [[150, 32, 327, 331], [256, 66, 408, 331]]
Chk 343 [[321, 94, 400, 318], [83, 38, 123, 201], [236, 52, 304, 261], [180, 41, 226, 192], [350, 44, 401, 136]]
Chk 344 [[36, 189, 131, 369], [145, 109, 244, 374], [392, 96, 484, 374], [314, 146, 378, 345]]
Chk 345 [[68, 158, 128, 251], [210, 109, 323, 320], [326, 161, 370, 234], [369, 134, 445, 261]]
Chk 346 [[137, 29, 487, 353], [0, 11, 158, 318]]
Chk 347 [[80, 39, 225, 332], [0, 118, 42, 257], [183, 34, 366, 125]]
Chk 348 [[92, 82, 251, 328], [186, 57, 393, 333]]
Chk 349 [[290, 78, 371, 235], [60, 109, 130, 246], [172, 193, 207, 282], [387, 127, 417, 170], [465, 171, 500, 294], [15, 201, 67, 266]]
Chk 352 [[44, 49, 258, 329], [337, 47, 412, 192], [0, 45, 106, 332], [0, 39, 29, 108]]
Chk 353 [[0, 55, 107, 331], [149, 55, 363, 331], [358, 0, 500, 331]]
Chk 354 [[150, 167, 209, 323], [209, 175, 247, 334], [342, 136, 396, 334]]
Chk 355 [[36, 48, 208, 333], [154, 69, 315, 380], [264, 48, 463, 383]]
Chk 356 [[224, 97, 310, 326], [127, 76, 224, 326], [467, 147, 499, 329]]
Chk 357 [[218, 48, 500, 333], [166, 80, 275, 333], [53, 10, 220, 333], [0, 226, 55, 309]]
Chk 358 [[58, 53, 430, 374], [240, 133, 481, 374]]
Chk 359 [[48, 4, 236, 365], [156, 7, 282, 354]]
Chk 363 [[0, 149, 29, 297], [25, 150, 76, 300], [57, 149, 98, 229], [80, 114, 191, 276], [238, 129, 346, 281]]
Chk 366 [[461, 121, 500, 241], [305, 45, 468, 365], [273, 113, 338, 169], [263, 129, 333, 293], [147, 19, 287, 375], [85, 113, 199, 375]]
Chk 367 [[2, 35, 161, 329], [192, 53, 327, 345], [312, 35, 491, 342], [264, 24, 426, 294], [298, 229, 360, 302]]
Chk 368 [[0, 0, 500, 375], [259, 36, 500, 249]]
Chk 372 [[29, 202, 86, 316], [105, 200, 149, 305], [197, 150, 324, 375], [315, 132, 426, 375], [6, 201, 41, 273]]
Chk 373 [[23, 60, 155, 441], [119, 201, 225, 394], [241, 157, 289, 267], [192, 200, 235, 246]]
Chk 374 [[353, 81, 499, 374], [69, 96, 217, 374]]
Chk 375 [[311, 56, 488, 366], [41, 100, 192, 321], [382, 6, 485, 199], [3, 64, 110, 211], [214, 9, 253, 44]]
Chk 376 [[140, 121, 292, 375], [355, 126, 492, 375]]
Chk 377 [[0, 84, 104, 375], [77, 95, 260, 375], [190, 63, 363, 355], [287, 35, 500, 375]]
Chk 378 [[20, 37, 150, 333], [103, 175, 143, 219], [87, 0, 293, 333], [395, 143, 481, 290], [337, 128, 500, 312]]
Chk 379 [[0, 159, 223, 500], [205, 163, 375, 500]]
Chk 380 [[143, 8, 329, 346], [123, 9, 196, 337]]
Chk 381 [[143, 87, 366, 499], [6, 59, 105, 499], [38, 18, 215, 499], [314, 108, 374, 278]]
Chk 382 [[170, 138, 285, 327], [149, 10, 265, 128], [153, 90, 182, 133], [69, 37, 216, 334]]
Chk 383 [[78, 61, 203, 333], [309, 105, 380, 273], [207, 87, 275, 267], [0, 148, 63, 331], [366, 138, 410, 200], [35, 166, 93, 238], [70, 168, 95, 212]]
Chk 384 [[4, 31, 124, 333], [137, 62, 236, 284], [291, 73, 393, 333], [377, 46, 476, 333]]
Chk 385 [[173, 151, 220, 241], [278, 156, 309, 234], [231, 154, 265, 237]]
Chk 386 [[315, 75, 467, 330], [170, 173, 311, 332], [21, 4, 171, 322]]
Chk 388 [[160, 114, 227, 306], [245, 177, 322, 278], [228, 105, 282, 214]]
Chk 389 [[145, 143, 427, 325], [76, 13, 358, 324], [1, 26, 113, 318]]
Chk 391 [[335, 139, 413, 270], [75, 79, 169, 300]]
Chk 392 [[236, 242, 290, 339], [39, 126, 122, 328]]
Chk 393 [[3, 86, 173, 443], [57, 271, 292, 497]]
Chk 394 [[130, 101, 285, 305], [247, 23, 407, 302]]
Chk 395 [[1, 54, 62, 110], [98, 77, 209, 451], [182, 78, 266, 418]]
Chk 396 [[260, 24, 480, 331], [170, 47, 288, 331], [48, 4, 193, 331]]
Chk 397 [[135, 111, 169, 224], [314, 122, 351, 232], [260, 139, 311, 218], [399, 147, 423, 182], [223, 103, 254, 207], [195, 110, 227, 234]]
Chk 398 [[81, 46, 313, 495], [157, 30, 301, 331]]
Chk 399 [[431, 88, 500, 334], [256, 70, 413, 334], [87, 77, 273, 334], [13, 73, 137, 334]]
Chk 400 [[171, 234, 328, 499], [60, 225, 158, 322]]
Chk 401 [[81, 92, 293, 373], [235, 128, 355, 368]]
Chk 403 [[166, 65, 318, 499], [23, 79, 198, 499]]
Chk 404 [[347, 71, 500, 375], [223, 118, 371, 375], [192, 118, 348, 375]]
Chk 405 [[390, 124, 437, 244], [287, 128, 367, 329], [196, 135, 265, 349], [87, 123, 190, 376]]
Chk 406 [[64, 127, 148, 314], [304, 15, 411, 305], [187, 33, 299, 294]]
Chk 407 [[100, 124, 319, 499], [10, 124, 215, 414]]
Chk 408 [[229, 134, 287, 273], [231, 30, 342, 181]]
Chk 409 [[75, 125, 136, 263], [303, 109, 367, 280], [402, 129, 441, 273]]
Chk 410 [[52, 92, 137, 195], [121, 115, 234, 238], [160, 175, 256, 293], [263, 139, 369, 288], [369, 107, 455, 290]]
Chk 411 [[75, 33, 208, 333], [246, 41, 443, 333], [365, 126, 464, 293], [451, 123, 500, 260]]
Chk 412 [[17, 73, 203, 374], [144, 0, 357, 369]]
Chk 413 [[15, 100, 154, 445], [140, 36, 337, 320]]
Chk 414 [[171, 87, 253, 409], [8, 86, 98, 432], [91, 81, 198, 431]]
Chk 415 [[38, 21, 372, 499], [33, 168, 269, 366]]
Chk 416 [[28, 208, 143, 459], [142, 172, 375, 500]]
Chk 417 [[126, 99, 226, 333], [197, 54, 306, 321], [299, 65, 394, 317]]
Chk 418 [[38, 5, 267, 352], [413, 24, 499, 354], [192, 56, 442, 356], [361, 80, 433, 197]]
Chk 419 [[62, 138, 149, 298], [128, 139, 208, 288]]
Chk 420 [[154, 0, 224, 250], [260, 124, 382, 270], [196, 106, 322, 265]]
Chk 421 [[106, 61, 180, 143], [0, 75, 238, 314], [349, 283, 454, 375], [368, 179, 481, 375]]
Chk 422 [[5, 61, 87, 178], [0, 114, 150, 303], [99, 34, 195, 342], [180, 71, 287, 320], [331, 82, 380, 178]]
Chk 423 [[34, 80, 214, 459], [110, 91, 194, 417]]
Chk 424 [[348, 52, 442, 331], [170, 124, 244, 300], [313, 190, 354, 299], [411, 184, 450, 287], [231, 135, 276, 228]]
Chk 425 [[336, 8, 477, 336], [296, 45, 378, 336], [165, 49, 268, 336], [0, 25, 111, 336]]
Chk 426 [[344, 86, 495, 326], [39, 53, 145, 213], [158, 122, 243, 241], [264, 116, 356, 307], [0, 106, 42, 194]]
Chk 427 [[170, 60, 275, 144], [233, 51, 336, 139]]
Chk 428 [[212, 65, 473, 332], [84, 70, 251, 332], [13, 217, 66, 332]]
Chk 429 [[0, 73, 237, 332], [284, 98, 382, 332], [363, 96, 446, 332]]
Chk 430 [[0, 37, 52, 142], [41, 0, 96, 140], [94, 64, 254, 319], [189, 58, 414, 375]]
Chk 431 [[52, 87, 262, 319], [213, 63, 437, 232], [0, 144, 83, 331]]
Chk 432 [[213, 177, 314, 415], [13, 169, 108, 396]]

Chk 433 [[64, 56, 197, 311], [204, 35, 380, 333], [379, 39, 491, 333], [337, 47, 408, 333]]
Chk 434 [[11, 22, 115, 391], [83, 49, 333, 500]]
Chk 435 [[109, 102, 190, 369], [5, 0, 289, 402]]
Chk 436 [[82, 163, 213, 495], [126, 170, 200, 283]]
Chk 437 [[169, 38, 318, 333], [18, 103, 124, 323], [317, 100, 458, 317]]
Chk 438 [[228, 74, 305, 273], [306, 31, 375, 332]]
Chk 439 [[92, 38, 186, 332], [236, 43, 345, 332]]
Chk 440 [[335, 48, 407, 315], [263, 61, 387, 333]]
Chk 442 [[95, 117, 288, 493], [5, 135, 124, 499], [27, 134, 129, 301]]
Chk 443 [[143, 73, 235, 211], [212, 83, 335, 229], [351, 78, 427, 229], [419, 88, 492, 235]]
Chk 444 [[13, 48, 315, 332], [173, 17, 469, 332]]
Chk 445 [[113, 152, 232, 329], [257, 46, 400, 332], [238, 128, 264, 210]]
Chk 446 [[123, 106, 256, 331], [202, 133, 263, 290]]
Chk 447 [[247, 58, 342, 332], [131, 42, 247, 332]]
Chk 448 [[51, 103, 220, 492], [195, 112, 333, 477]]
Chk 450 [[37, 32, 234, 268], [153, 47, 451, 316]]
Chk 451 [[98, 49, 256, 498], [255, 56, 441, 498]]
Chk 453 [[317, 60, 443, 331], [7, 17, 208, 331]]
Chk 455 [[13, 90, 177, 396], [181, 146, 248, 229]]
Chk 457 [[263, 185, 372, 332], [216, 191, 321, 297]]
Chk 458 [[22, 52, 180, 409], [358, 96, 473, 435], [257, 16, 359, 207]]
Chk 459 [[204, 63, 285, 320], [264, 34, 360, 318], [137, 46, 224, 327]]
Chk 461 [[80, 176, 167, 273], [298, 160, 419, 279]]
Chk 462 [[6, 231, 124, 481], [231, 249, 332, 491]]
Chk 464 [[33, 23, 223, 357], [362, 79, 489, 357]]
Chk 465 [[135, 44, 330, 499], [19, 22, 296, 365]]
Chk 467 [[294, 182, 453, 456], [140, 222, 265, 368]]
Chk 469 [[219, 104, 293, 183], [80, 79, 125, 151]]
Chk 470 [[3, 47, 78, 270], [403, 69, 482, 280], [60, 94, 214, 280]]
Chk 471 [[33, 110, 82, 300], [0, 103, 37, 305], [121, 87, 192, 325], [217, 44, 441, 333], [244, 45, 440, 333]]
Chk 472 [[0, 44, 220, 332], [193, 0, 480, 332]]
Chk 473 [[397, 18, 492, 311], [51, 53, 192, 326]]
Chk 474 [[88, 144, 332, 498], [0, 134, 209, 499]]
Chk 475 [[36, 250, 90, 383], [130, 261, 256, 404], [241, 250, 342, 406]]
Chk 476 [[103, 106, 273, 441], [317, 160, 408, 411], [402, 153, 487, 398]]
Chk 477 [[150, 61, 243, 164], [247, 57, 321, 157], [52, 52, 152, 267], [312, 65, 356, 133], [368, 65, 445, 163]]
Chk 478 [[8, 14, 291, 295], [192, 10, 406, 295]]
Chk 479 [[376, 150, 476, 280], [122, 77, 192, 246], [243, 60, 296, 267], [128, 166, 261, 278]]
Chk 480 [[2, 22, 157, 399], [330, 114, 454, 372], [183, 115, 356, 371]]
Chk 482 [[463, 115, 500, 300], [248, 73, 391, 302], [131, 39, 271, 327]]
Chk 483 [[15, 62, 139, 465], [174, 82, 332, 455]]
Chk 484 [[338, 73, 499, 314], [36, 65, 310, 324]]
Chk 485 [[49, 70, 178, 323], [284, 47, 420, 319]]
Chk 486 [[213, 99, 280, 322], [91, 154, 214, 306]]
Chk 488 [[106, 111, 227, 316], [249, 107, 404, 324]]
Chk 489 [[161, 60, 408, 333], [191, 50, 411, 333]]
Chk 490 [[39, 50, 141, 304], [134, 87, 274, 312], [460, 55, 500, 333]]
Chk 491 [[33, 179, 175, 484], [150, 107, 276, 466], [310, 233, 333, 321]]
Chk 492 [[237, 106, 300, 239], [81, 98, 148, 248]]
Chk 493 [[432, 128, 479, 224], [276, 175, 393, 331], [165, 174, 288, 287], [95, 95, 173, 275]]
Chk 494 [[118, 127, 297, 487], [157, 122, 327, 462]]
Chk 495 [[222, 201, 342, 402], [126, 113, 210, 317]]
Chk 496 [[193, 113, 269, 192], [269, 127, 329, 197], [117, 111, 203, 206]]
Chk 497 [[18, 17, 253, 326], [202, 55, 338, 326], [474, 194, 498, 245]]
Chk 498 [[134, 158, 182, 327], [267, 44, 333, 114], [163, 49, 271, 317]]
Chk 499 [[0, 44, 161, 330], [277, 73, 425, 330], [412, 258, 456, 325], [2, 249, 27, 312]]
Chk 500 [[0, 101, 54, 281], [0, 72, 92, 241], [70, 55, 134, 171], [170, 13, 288, 241], [281, 65, 453, 281], [360, 214, 450, 281], [402, 53, 448, 131]]
Chk 501 [[84, 209, 155, 347], [248, 91, 333, 302], [86, 136, 151, 269]]
Chk 502 [[247, 23, 364, 375], [121, 15, 284, 375], [90, 102, 167, 210], [91, 73, 192, 373], [152, 0, 223, 81], [377, 0, 443, 64], [455, 0, 498, 64], [339, 90, 413, 275]]
Chk 503 [[99, 39, 227, 314], [197, 65, 315, 304]]
Chk 504 [[32, 2, 205, 475], [207, 0, 401, 488]]
Chk 506 [[50, 62, 114, 226], [285, 88, 417, 269], [379, 95, 417, 162], [182, 97, 215, 148]]
Chk 507 [[106, 75, 230, 483], [23, 96, 144, 469], [1, 185, 24, 312]]
Chk 509 [[17, 35, 150, 331], [201, 56, 332, 331], [325, 76, 390, 331], [343, 52, 500, 331]]
Chk 510 [[48, 3, 87, 56], [33, 54, 195, 350], [186, 8, 355, 351]]
Chk 511 [[93, 138, 162, 217], [340, 135, 435, 211], [211, 140, 277, 213], [461, 133, 499, 206]]
Chk 512 [[239, 151, 340, 471], [75, 172, 211, 464]]
Chk 513 [[104, 37, 185, 297], [293, 6, 430, 295], [209, 24, 327, 321]]
Chk 516 [[397, 111, 444, 214], [445, 102, 491, 219], [194, 48, 318, 278], [113, 87, 192, 253], [331, 11, 349, 44]]
Chk 518 [[407, 108, 459, 333], [217, 107, 304, 333], [144, 131, 220, 333]]
Chk 519 [[25, 18, 188, 325], [303, 18, 472, 330], [177, 56, 326, 330]]
Chk 521 [[344, 108, 435, 334], [182, 101, 299, 330]]
Chk 522 [[170, 180, 245, 335], [52, 144, 123, 335], [21, 138, 62, 309]]
Chk 523 [[0, 84, 64, 334], [30, 30, 164, 334], [129, 67, 246, 334], [219, 105, 328, 334], [302, 50, 468, 334]]
Chk 525 [[235, 111, 415, 412], [33, 49, 267, 410]]
Chk 526 [[16, 94, 206, 333], [203, 92, 372, 333]]
Chk 528 [[0, 3, 182, 374], [136, 163, 309, 355], [260, 245, 304, 306]]
Chk 529 [[3, 186, 225, 484], [187, 183, 359, 436]]
Chk 530 [[2, 6, 279, 374], [208, 135, 338, 364], [297, 116, 484, 371], [456, 136, 497, 226]]
Chk 531 [[129, 80, 341, 362], [305, 53, 445, 298]]
Chk 532 [[23, 167, 157, 365], [309, 94, 500, 375], [156, 133, 302, 339]]
Chk 533 [[287, 221, 324, 345], [218, 247, 269, 359]]
Chk 535 [[177, 74, 389, 356], [288, 84, 396, 301]]
Chk 536 [[14, 68, 155, 343], [285, 83, 343, 280]]
Chk 538 [[11, 301, 77, 484], [87, 303, 162, 488], [150, 318, 232, 472], [231, 304, 294, 454]]
Chk 539 [[0, 53, 186, 375], [214, 80, 405, 375], [171, 55, 304, 375]]
Chk 540 [[232, 56, 403, 183], [36, 49, 340, 374]]
Chk 541 [[32, 20, 269, 361], [192, 45, 340, 336]]
Chk 542 [[130, 42, 272, 471], [84, 215, 169, 422]]
Chk 543 [[4, 130, 234, 403], [266, 0, 453, 308]]
Chk 544 [[21, 49, 205, 290], [238, 22, 339, 149], [315, 54, 457, 205]]
Chk 545 [[289, 30, 367, 283], [106, 135, 223, 298], [74, 119, 134, 284]]
Chk 547 [[0, 58, 89, 375], [229, 84, 366, 375], [144, 107, 175, 151]]
Chk 549 [[270, 99, 393, 328], [178, 96, 314, 332]]
Chk 550 [[0, 35, 94, 281], [78, 37, 187, 281], [228, 30, 332, 281], [346, 44, 431, 280]]
Chk 551 [[151, 88, 238, 238], [0, 72, 212, 333], [257, 31, 500, 333]]
Chk 552 [[75, 48, 228, 375], [355, 42, 495, 375]]
Chk 553 [[0, 112, 193, 307], [283, 76, 472, 289]]
Chk 555 [[1, 131, 256, 500], [216, 60, 500, 500]]
Chk 556 [[229, 0, 500, 375], [33, 27, 271, 375], [33, 54, 255, 375]]
Chk 557 [[165, 17, 239, 95], [236, 39, 343, 219], [433, 56, 500, 171], [75, 82, 415, 333]]
Chk 558 [[329, 73, 485, 374], [0, 0, 193, 374], [196, 78, 375, 374], [132, 47, 267, 366]]
Chk 559 [[16, 43, 271, 347], [202, 96, 442, 374]]
Chk 560 [[68, 65, 152, 331], [177, 121, 238, 330], [329, 69, 401, 293], [10, 107, 60, 244], [228, 65, 323, 332], [411, 94, 467, 214], [156, 120, 184, 217], [432, 188, 464, 244]]
Chk 564 [[223, 124, 306, 218], [338, 131, 420, 225]]
Chk 565 [[121, 67, 275, 375], [296, 91, 425, 298]]
Chk 566 [[27, 34, 205, 333], [252, 48, 446, 333], [9, 0, 94, 141], [281, 0, 372, 74]]
Chk 567 [[40, 120, 160, 338], [173, 151, 295, 300], [192, 145, 219, 190], [268, 131, 311, 194], [310, 140, 328, 209]]
Chk 569 [[144, 71, 243, 272], [377, 96, 466, 247]]
Chk 571 [[54, 157, 172, 332], [172, 141, 322, 332]]
Chk 572 [[42, 36, 198, 311], [233, 49, 401, 357]]
Chk 573 [[428, 183, 500, 357], [214, 47, 425, 357], [393, 121, 500, 274], [82, 71, 254, 357], [29, 246, 98, 357], [0, 279, 38, 357]]
Chk 574 [[181, 85, 291, 156], [7, 51, 208, 363], [335, 37, 496, 362]]
Chk 576 [[167, 89, 282, 267], [34, 71, 178, 335]]
Chk 577 [[19, 52, 97, 272], [65, 14, 192, 300], [301, 46, 410, 300], [407, 4, 500, 300], [364, 21, 415, 119], [179, 56, 252, 204], [2, 37, 52, 208]]
Chk 578 [[73, 110, 164, 242], [216, 29, 320, 252], [176, 65, 241, 230], [332, 49, 405, 177]]
Chk 579 [[0, 42, 314, 312], [190, 14, 467, 312]]
Chk 580 [[216, 69, 298, 297], [114, 50, 193, 259], [2, 84, 53, 230]]
Chk 581 [[109, 95, 180, 280], [224, 103, 297, 280]]
Chk 582 [[310, 85, 485, 496], [35, 74, 186, 499]]
Chk 583 [[148, 10, 263, 256], [265, 68, 462, 311], [58, 128, 232, 313]]
Chk 584 [[185, 61, 267, 309], [423, 75, 484, 248], [56, 73, 191, 318], [371, 45, 399, 112]]
Chk 585 [[218, 40, 417, 235], [56, 50, 265, 269]]
Chk 586 [[191, 37, 331, 332], [73, 55, 205, 332], [325, 43, 452, 332]]
Chk 587 [[83, 11, 198, 160], [217, 30, 305, 148], [393, 38, 500, 272]]
Chk 588 [[270, 118, 332, 277], [52, 120, 107, 297], [384, 136, 440, 280], [100, 175, 163, 286]]
Chk 589 [[185, 174, 244, 310], [256, 175, 306, 275], [378, 218, 417, 269]]
Chk 591 [[223, 27, 383, 220], [154, 142, 207, 189]]
Chk 592 [[39, 103, 120, 249], [159, 117, 333, 441], [283, 89, 333, 219]]
Chk 593 [[208, 29, 397, 334], [39, 51, 158, 318]]
Chk 594 [[330, 94, 410, 296], [94, 68, 206, 328], [261, 79, 316, 289], [194, 207, 259, 286]]
Chk 596 [[165, 114, 332, 429], [8, 50, 188, 498]]
Chk 597 [[11, 211, 213, 499], [242, 225, 325, 497]]

Chk 598 [[287, 23, 462, 303], [65, 46, 158, 312]]
Chk 599 [[89, 23, 261, 329], [243, 6, 399, 317]]
Chk 600 [[241, 126, 287, 235], [161, 143, 212, 238], [323, 132, 374, 230]]
Chk 601 [[34, 25, 270, 331], [161, 27, 478, 294]]
Chk 602 [[59, 0, 212, 332], [267, 120, 424, 328]]
Chk 603 [[241, 79, 355, 332], [141, 87, 233, 332], [0, 116, 178, 332]]
Chk 604 [[63, 66, 156, 334], [201, 61, 309, 310], [347, 51, 468, 322]]
Chk 605 [[0, 153, 148, 375], [129, 150, 335, 375], [299, 120, 375, 230], [418, 117, 487, 253]]
Chk 606 [[205, 44, 428, 333], [176, 42, 412, 333]]
Chk 607 [[72, 36, 302, 374], [293, 0, 462, 299]]
Chk 608 [[65, 142, 200, 485], [164, 28, 421, 485], [146, 211, 268, 483]]
Chk 609 [[376, 73, 463, 232], [244, 84, 335, 226], [119, 76, 184, 239], [4, 69, 71, 232]]
Chk 611 [[298, 77, 385, 334], [127, 65, 231, 320]]
Chk 612 [[0, 0, 217, 500], [102, 0, 332, 500]]
Chk 613 [[56, 169, 168, 483], [126, 239, 210, 472], [257, 233, 332, 458], [172, 141, 263, 493]]
Chk 614 [[233, 75, 398, 238], [54, 58, 207, 318], [162, 88, 278, 311]]
Chk 615 [[263, 25, 499, 456], [38, 112, 193, 462]]
Chk 616 [[58, 47, 162, 334], [143, 21, 282, 334], [273, 29, 395, 334], [422, 60, 500, 299]]
Chk 618 [[162, 56, 426, 441], [40, 25, 274, 441]]
Chk 620 [[53, 169, 107, 294], [48, 166, 104, 296]]
Chk 621 [[112, 125, 239, 417], [16, 97, 202, 364]]
Chk 622 [[322, 193, 415, 317], [107, 82, 287, 332]]
Chk 623 [[0, 111, 51, 238], [74, 118, 132, 231], [161, 118, 242, 233], [339, 146, 417, 249], [376, 126, 492, 281]]
Chk 624 [[92, 295, 200, 500], [126, 290, 318, 500]]
Chk 625 [[42, 101, 255, 290], [287, 48, 499, 316]]
Chk 626 [[83, 28, 210, 255], [193, 31, 287, 223], [257, 49, 393, 278]]
Chk 627 [[33, 159, 72, 230], [256, 147, 311, 261], [175, 141, 253, 281]]
Chk 628 [[328, 22, 485, 340], [151, 141, 308, 355], [5, 126, 147, 339]]
Chk 629 [[396, 118, 493, 268], [352, 122, 387, 173], [145, 114, 174, 225], [195, 123, 225, 177], [205, 123, 227, 153], [452, 135, 499, 261]]
Chk 630 [[46, 12, 136, 230], [308, 79, 493, 330], [165, 84, 328, 311], [291, 87, 382, 304]]
Chk 631 [[83, 48, 299, 365], [255, 84, 464, 336]]
Chk 632 [[210, 92, 365, 331], [366, 148, 484, 331], [49, 136, 80, 207], [125, 161, 173, 228], [74, 129, 97, 218], [182, 162, 211, 191]]
Chk 633 [[414, 28, 488, 163], [115, 31, 352, 255]]
Chk 634 [[255, 48, 398, 361], [58, 85, 150, 366]]
Chk 635 [[0, 106, 103, 375], [114, 125, 253, 375], [353, 76, 455, 375], [418, 73, 500, 375], [169, 0, 291, 162]]
Chk 636 [[46, 135, 205, 500], [161, 177, 227, 278], [19, 151, 109, 436]]
Chk 637 [[256, 27, 488, 323], [48, 32, 283, 326]]
Chk 638 [[13, 5, 139, 333], [119, 51, 220, 331], [203, 35, 316, 333], [286, 0, 445, 333]]
Chk 640 [[265, 2, 410, 326], [80, 52, 185, 323], [372, 5, 401, 119], [180, 26, 286, 323], [75, 46, 91, 85], [41, 43, 56, 81]]
Chk 641 [[75, 181, 120, 308], [244, 186, 295, 329], [187, 178, 236, 323], [224, 188, 253, 310]]
Chk 643 [[384, 123, 445, 290], [176, 139, 251, 265]]
Chk 644 [[253, 58, 420, 321], [37, 45, 177, 292]]
Chk 645 [[190, 107, 275, 320], [37, 79, 128, 332], [79, 96, 157, 318]]
Chk 646 [[0, 153, 216, 500], [192, 148, 333, 500], [20, 131, 223, 500]]
Chk 647 [[294, 12, 483, 421], [76, 32, 256, 438]]
Chk 648 [[153, 209, 241, 415], [22, 32, 170, 415], [208, 116, 263, 350], [252, 119, 309, 338], [345, 137, 430, 355], [408, 125, 486, 350]]
Chk 650 [[312, 10, 383, 160], [183, 92, 251, 270], [99, 159, 152, 246], [7, 283, 60, 327], [184, 167, 234, 261]]
Chk 651 [[374, 52, 491, 332], [277, 68, 381, 332], [41, 98, 150, 300], [167, 63, 235, 280], [0, 60, 57, 259]]
Chk 652 [[55, 10, 377, 500], [45, 6, 417, 500]]
Chk 653 [[0, 41, 263, 394], [266, 90, 438, 334]]
Chk 654 [[69, 149, 149, 263], [11, 161, 77, 266], [281, 140, 349, 299], [354, 146, 409, 278]]
Chk 655 [[251, 75, 344, 210], [141, 59, 229, 259], [339, 84, 460, 309]]
Chk 656 [[242, 60, 499, 332], [204, 75, 355, 332]]
Chk 657 [[238, 78, 339, 331], [120, 106, 233, 328], [0, 50, 142, 331], [328, 62, 499, 331]]
Chk 658 [[209, 4, 479, 173], [0, 10, 182, 286], [396, 0, 499, 316]]
Chk 659 [[203, 0, 474, 317], [42, 27, 221, 306]]
Chk 660 [[257, 51, 404, 332], [86, 53, 220, 332]]
Chk 661 [[0, 175, 196, 413], [142, 62, 285, 373], [76, 163, 333, 500]]
Chk 662 [[318, 107, 397, 312], [131, 109, 236, 296], [75, 113, 169, 289]]
Chk 663 [[9, 111, 112, 332], [153, 69, 357, 277], [402, 82, 499, 281]]
Chk 664 [[178, 184, 247, 254], [342, 188, 415, 272], [72, 164, 152, 258]]
Chk 665 [[26, 76, 186, 374], [291, 99, 419, 362], [154, 147, 223, 282]]
Chk 666 [[334, 139, 491, 374], [3, 166, 150, 371], [141, 163, 343, 374]]
Chk 667 [[256, 92, 301, 183], [117, 136, 189, 181], [393, 82, 447, 296]]
Chk 668 [[3, 60, 246, 300], [291, 57, 499, 367]]
Chk 671 [[60, 49, 255, 333], [216, 26, 397, 333], [63, 54, 253, 333]]
Chk 673 [[217, 112, 340, 264], [88, 128, 183, 258]]
Chk 674 [[71, 221, 255, 333], [239, 39, 374, 333], [236, 36, 395, 333]]
Chk 676 [[283, 107, 364, 213], [85, 96, 171, 223]]
Chk 677 [[0, 0, 239, 329], [128, 3, 354, 308]]
Chk 678 [[168, 150, 369, 333], [357, 156, 500, 333], [186, 102, 262, 226], [87, 14, 179, 255]]
Chk 680 [[334, 77, 499, 268], [75, 37, 249, 302]]
Chk 682 [[227, 133, 323, 317], [125, 68, 228, 351], [147, 44, 241, 176]]
Chk 683 [[127, 55, 199, 276], [207, 143, 302, 284]]
Chk 684 [[111, 110, 169, 256], [248, 12, 357, 262], [144, 32, 175, 108], [451, 3, 499, 182], [5, 51, 42, 130]]
Chk 685 [[42, 28, 262, 331], [170, 2, 479, 326]]
Chk 686 [[226, 0, 500, 375], [204, 55, 361, 270], [109, 34, 232, 290]]
Chk 687 [[0, 83, 189, 288], [73, 105, 150, 201], [210, 135, 391, 203]]
Chk 688 [[42, 34, 163, 323], [275, 24, 500, 375], [447, 80, 475, 108], [240, 54, 271, 69], [180, 42, 198, 70], [57, 45, 81, 77], [246, 43, 256, 60]]
Chk 690 [[385, 69, 457, 306], [29, 128, 126, 300]]
Chk 691 [[154, 78, 386, 332], [277, 125, 405, 332]]
Chk 692 [[343, 174, 499, 374], [186, 106, 391, 374], [52, 163, 278, 374]]
Chk 693 [[294, 77, 479, 374], [36, 99, 228, 367], [261, 305, 323, 362]]
Chk 694 [[15, 132, 352, 374], [197, 150, 392, 374]]
Chk 695 [[6, 59, 194, 500], [200, 57, 366, 500]]
Chk 696 [[63, 142, 293, 500], [42, 130, 327, 499]]
Chk 698 [[30, 110, 180, 494], [166, 83, 364, 500]]
Chk 699 [[72, 153, 125, 263], [108, 139, 163, 286], [177, 137, 220, 272], [222, 139, 267, 288], [322, 135, 388, 316], [388, 99, 489, 307]]
Chk 700 [[4, 67, 106, 309], [132, 134, 208, 210], [148, 234, 201, 339], [177, 143, 291, 329], [251, 192, 488, 337]]
Chk 701 [[0, 5, 349, 324], [222, 0, 499, 369]]
Chk 702 [[21, 47, 131, 500], [193, 47, 333, 500], [92, 110, 204, 500]]
Chk 703 [[0, 237, 109, 375], [0, 140, 105, 280], [238, 203, 412, 375], [140, 202, 279, 375], [211, 110, 312, 330]]
Chk 704 [[189, 68, 423, 325], [390, 0, 495, 195], [10, 62, 232, 332]]
Chk 705 [[49, 80, 205, 332], [175, 41, 370, 332]]
Chk 707 [[277, 57, 456, 336], [185, 66, 295, 336], [67, 61, 204, 336]]
Chk 708 [[136, 100, 310, 499], [2, 168, 203, 499]]
Chk 709 [[241, 86, 374, 366], [135, 136, 239, 371]]
Chk 710 [[160, 99, 248, 286], [17, 95, 117, 279], [253, 102, 369, 289]]
Chk 711 [[169, 251, 213, 375], [197, 186, 257, 375], [251, 194, 315, 375], [57, 212, 84, 264]]
Chk 712 [[114, 79, 365, 324], [44, 69, 230, 297]]
Chk 713 [[377, 81, 500, 292], [159, 78, 261, 202], [52, 79, 149, 257], [64, 135, 272, 375], [257, 105, 441, 375]]
Chk 714 [[5, 46, 324, 378], [273, 26, 472, 364]]
Chk 715 [[127, 36, 415, 296], [284, 48, 429, 320]]
Chk 716 [[21, 71, 202, 383], [107, 18, 301, 422]]
Chk 717 [[300, 124, 391, 333], [396, 89, 499, 333], [100, 95, 202, 333], [273, 138, 312, 256], [165, 95, 252, 329], [88, 141, 109, 209], [61, 135, 83, 179]]
Chk 718 [[254, 155, 301, 211], [333, 146, 379, 209]]
Chk 719 [[213, 81, 390, 327], [116, 188, 243, 327]]
Chk 720 [[91, 116, 156, 289], [195, 152, 246, 229], [280, 113, 346, 236], [8, 105, 104, 283], [27, 126, 76, 313]]
Chk 721 [[1, 116, 112, 421], [113, 61, 267, 468]]
Chk 722 [[307, 146, 391, 365], [106, 156, 194, 358], [12, 155, 82, 372], [219, 91, 289, 173]]
Chk 723 [[133, 54, 331, 318], [80, 97, 200, 328]]
Chk 724 [[285, 181, 326, 275], [236, 105, 336, 242], [225, 179, 266, 259], [199, 184, 246, 272]]
Chk 725 [[0, 96, 204, 333], [158, 36, 455, 333]]
Chk 726 [[117, 48, 332, 489], [0, 48, 189, 491]]
Chk 727 [[322, 116, 445, 297], [163, 113, 345, 303], [109, 115, 219, 288]]
Chk 728 [[257, 180, 353, 330], [106, 20, 213, 332]]
Chk 729 [[157, 27, 293, 333], [255, 79, 384, 318]]
Chk 730 [[287, 122, 499, 333], [137, 77, 329, 332]]
Chk 731 [[376, 173, 446, 329], [357, 229, 403, 319]]
Chk 732 [[131, 35, 286, 278], [170, 56, 390, 333]]
Chk 733 [[211, 92, 418, 321], [102, 137, 247, 290], [0, 18, 38, 318]]
Chk 734 [[31, 106, 205, 333], [167, 109, 242, 333], [239, 97, 317, 321]]
Chk 735 [[208, 4, 373, 356], [85, 18, 221, 356]]
Chk 737 [[43, 132, 375, 500], [111, 99, 222, 453], [198, 55, 309, 254]]
Chk 738 [[0, 78, 171, 334], [207, 144, 296, 237], [146, 42, 383, 334]]
Chk 739 [[120, 1, 227, 285], [240, 218, 443, 375], [92, 45, 415, 375]]
Chk 740 [[86, 107, 220, 272], [383, 152, 500, 375]]
Chk 741 [[106, 93, 319, 499], [0, 78, 181, 499]]
Chk 743 [[247, 74, 414, 322], [48, 51, 264, 296]]
Chk 744 [[351, 79, 488, 358], [151, 71, 286, 375]]
Chk 745 [[24, 8, 278, 375], [190, 130, 417, 375]]

Chk 746 [[109, 51, 253, 232], [212, 107, 322, 292], [381, 240, 484, 332]]
Chk 747 [[169, 110, 316, 413], [99, 131, 195, 406], [21, 271, 120, 400], [4, 205, 95, 337], [0, 273, 95, 401]]
Chk 748 [[0, 151, 87, 221], [193, 114, 349, 250], [183, 116, 323, 243], [295, 78, 343, 140]]
Chk 749 [[8, 13, 234, 324], [350, 26, 493, 326]]
Chk 751 [[131, 138, 232, 320], [304, 173, 368, 265], [135, 74, 196, 166], [293, 104, 343, 270]]
Chk 752 [[316, 48, 402, 272], [99, 116, 195, 301], [218, 100, 330, 303]]
Chk 753 [[3, 119, 85, 365], [113, 33, 316, 488], [13, 75, 233, 499]]
Chk 755 [[187, 103, 341, 285], [8, 149, 170, 371]]
Chk 756 [[51, 57, 165, 351], [193, 79, 311, 380]]
Chk 758 [[210, 66, 328, 332], [12, 56, 125, 332], [403, 84, 497, 332]]
Chk 759 [[0, 37, 115, 357], [112, 26, 287, 491], [247, 45, 334, 210], [277, 132, 400, 437]]
Chk 761 [[199, 91, 300, 369], [93, 118, 236, 289]]
Chk 762 [[130, 20, 299, 499], [96, 219, 200, 499]]
Chk 763 [[0, 58, 269, 333], [272, 45, 413, 287], [250, 42, 430, 324]]
Chk 764 [[23, 75, 109, 286], [135, 71, 220, 296]]
Chk 766 [[196, 95, 262, 291], [262, 90, 332, 290], [146, 102, 224, 408]]
Chk 767 [[28, 84, 200, 325], [2, 115, 51, 232], [283, 23, 458, 331], [195, 51, 325, 331]]
Chk 768 [[49, 34, 289, 333], [175, 89, 307, 333], [291, 14, 500, 333]]
Chk 769 [[19, 49, 332, 475], [37, 288, 256, 500]]
Chk 770 [[7, 118, 153, 468], [117, 45, 333, 500]]
Chk 771 [[274, 140, 342, 285], [23, 59, 139, 274], [369, 139, 496, 315], [168, 147, 265, 292]]
Chk 772 [[169, 68, 331, 491], [23, 6, 245, 443]]
Chk 774 [[72, 129, 329, 357], [283, 66, 469, 342]]
Chk 776 [[309, 23, 486, 248], [83, 97, 274, 294]]
Chk 777 [[116, 43, 277, 333], [289, 174, 420, 327]]
Chk 778 [[239, 149, 326, 296], [90, 148, 137, 330]]
Chk 781 [[23, 48, 165, 399], [343, 69, 489, 390]]
Chk 782 [[172, 97, 311, 484], [63, 79, 190, 347]]
Chk 783 [[211, 58, 391, 331], [366, 46, 498, 331], [68, 75, 241, 321]]
Chk 784 [[55, 65, 203, 297], [204, 42, 374, 357]]
Chk 785 [[8, 57, 146, 333], [242, 43, 381, 333]]
Chk 786 [[231, 100, 339, 259], [93, 70, 211, 496]]
Chk 787 [[7, 58, 211, 322], [311, 66, 485, 250]]
Chk 788 [[90, 73, 170, 202], [80, 210, 199, 486]]
Chk 789 [[70, 25, 204, 350], [220, 104, 341, 360]]
Chk 790 [[174, 39, 268, 293], [51, 84, 100, 223], [291, 120, 354, 195], [362, 9, 451, 324]]
Chk 791 [[16, 43, 157, 333], [139, 5, 303, 333], [369, 45, 437, 269], [402, 65, 453, 283]]
Chk 792 [[223, 47, 487, 332], [7, 48, 240, 332]]
Chk 794 [[359, 170, 428, 333], [264, 180, 340, 342]]
Chk 795 [[124, 167, 286, 330], [63, 143, 175, 330]]
Chk 796 [[15, 62, 159, 499], [172, 56, 322, 475]]
Chk 798 [[124, 118, 212, 325], [23, 82, 119, 302], [397, 108, 458, 266], [313, 113, 380, 312], [275, 83, 313, 245]]
Chk 799 [[155, 59, 220, 192], [230, 0, 351, 320], [436, 178, 455, 223]]
Chk 801 [[328, 60, 437, 277], [215, 50, 343, 310], [21, 61, 191, 317]]
Chk 802 [[212, 64, 393, 329], [37, 28, 246, 332]]
Chk 803 [[10, 120, 193, 331], [207, 24, 295, 175]]
Chk 804 [[71, 99, 221, 417], [160, 71, 332, 500]]
Chk 805 [[358, 82, 418, 266], [313, 85, 364, 263]]
Chk 806 [[83, 76, 196, 290], [182, 94, 404, 296]]
Chk 807 [[29, 36, 257, 332], [258, 153, 332, 250], [368, 264, 420, 332]]
Chk 808 [[207, 145, 255, 256], [258, 101, 366, 323]]
Chk 809 [[324, 34, 492, 330], [104, 0, 292, 330], [2, 30, 198, 328]]
Chk 810 [[129, 26, 240, 289], [348, 70, 435, 214]]
Chk 811 [[157, 153, 200, 248], [225, 151, 277, 252]]
Chk 812 [[401, 134, 451, 234], [348, 140, 384, 231], [159, 121, 215, 231], [98, 125, 137, 216]]
Chk 813 [[213, 118, 294, 259], [105, 147, 169, 247], [20, 126, 57, 206], [478, 157, 499, 216]]
Chk 814 [[13, 103, 199, 333], [190, 71, 341, 333], [327, 67, 500, 333]]
Chk 815 [[113, 103, 272, 324], [261, 62, 449, 330]]
Chk 816 [[91, 153, 420, 500], [111, 17, 300, 380], [29, 72, 147, 418]]
Chk 817 [[78, 285, 173, 402], [200, 293, 272, 400]]
Chk 818 [[265, 70, 495, 452], [14, 14, 298, 452]]
Chk 819 [[180, 7, 294, 220], [101, 125, 202, 330], [6, 17, 131, 321], [271, 14, 426, 301], [384, 0, 499, 268]]
Chk 820 [[134, 68, 298, 325], [343, 24, 423, 253]]
Chk 821 [[225, 102, 310, 332], [340, 48, 472, 332]]
Chk 822 [[120, 59, 198, 293], [217, 86, 278, 287]]
Chk 823 [[405, 148, 444, 241], [204, 159, 237, 204], [222, 147, 256, 209]]
Chk 825 [[142, 54, 470, 323], [17, 34, 184, 332]]
Chk 826 [[191, 91, 326, 361], [85, 136, 126, 231], [127, 144, 154, 222], [211, 91, 310, 231], [13, 145, 55, 221], [44, 138, 122, 330]]
Chk 828 [[33, 174, 122, 452], [92, 174, 250, 479]]
Chk 829 [[302, 28, 500, 323], [261, 14, 500, 322], [42, 59, 382, 331]]
Chk 830 [[0, 79, 65, 141], [4, 124, 156, 331], [84, 55, 260, 331], [242, 64, 409, 331]]
Chk 832 [[287, 60, 499, 332], [47, 25, 245, 332]]
Chk 833 [[42, 2, 249, 332], [281, 29, 490, 332], [3, 75, 32, 138]]
Chk 834 [[177, 52, 254, 159], [311, 78, 369, 167], [405, 72, 500, 281]]
Chk 835 [[0, 0, 149, 333], [159, 27, 350, 333], [396, 0, 500, 333]]
Chk 836 [[234, 144, 362, 331], [353, 132, 466, 331], [39, 173, 192, 329], [448, 160, 499, 325], [118, 93, 206, 152]]
Chk 837 [[237, 137, 307, 326], [298, 128, 352, 345], [379, 135, 468, 362], [2, 152, 48, 254], [58, 132, 142, 341], [384, 282, 483, 368], [451, 187, 493, 271]]
Chk 838 [[303, 22, 427, 284], [101, 43, 266, 319]]
Chk 839 [[102, 238, 153, 364], [178, 233, 216, 352], [3, 274, 25, 317]]
Chk 842 [[148, 174, 221, 282], [234, 103, 276, 231], [289, 106, 320, 216], [348, 97, 399, 245], [388, 97, 450, 222], [331, 82, 376, 230]]
Chk 844 [[143, 32, 363, 499], [51, 68, 175, 384]]
Chk 845 [[14, 68, 234, 334], [184, 0, 441, 295], [438, 32, 500, 257]]
Chk 846 [[148, 99, 294, 219], [263, 108, 420, 234], [335, 165, 446, 276], [291, 221, 488, 375]]
Chk 848 [[331, 51, 475, 278], [76, 61, 207, 328], [214, 63, 330, 275]]
Chk 849 [[53, 5, 118, 190], [157, 76, 250, 214], [240, 67, 310, 214], [288, 79, 343, 213]]
Chk 850 [[62, 37, 287, 427], [39, 65, 177, 389]]
Chk 851 [[0, 0, 134, 280], [48, 24, 207, 231], [314, 19, 500, 280]]
Chk 852 [[251, 179, 338, 273], [216, 103, 291, 231]]
Chk 853 [[53, 39, 374, 493], [8, 138, 171, 499]]
Chk 855 [[47, 89, 195, 375], [159, 56, 322, 218], [320, 86, 462, 371]]
Chk 858 [[0, 206, 71, 375], [28, 147, 254, 375], [150, 117, 291, 330], [257, 107, 427, 375]]
Chk 859 [[114, 68, 359, 491], [24, 158, 193, 499]]
Chk 860 [[119, 67, 271, 208], [352, 98, 499, 374], [1, 112, 153, 258]]
Chk 861 [[198, 61, 277, 266], [372, 77, 436, 278], [112, 35, 204, 332], [269, 57, 382, 332]]
Chk 863 [[0, 28, 153, 321], [251, 30, 474, 266], [143, 114, 312, 293]]
Chk 865 [[261, 24, 456, 375], [158, 113, 243, 375], [104, 183, 171, 359]]
Chk 866 [[336, 7, 499, 374], [141, 23, 403, 325]]
Chk 867 [[205, 172, 317, 488], [155, 260, 226, 484], [68, 99, 191, 495]]
Chk 868 [[343, 39, 492, 332], [60, 41, 267, 332]]
Chk 870 [[154, 113, 285, 407], [22, 127, 177, 441]]
Chk 871 [[81, 140, 180, 299], [242, 28, 414, 375]]
Chk 872 [[31, 16, 413, 375], [160, 173, 362, 370], [227, 49, 500, 375]]
Chk 873 [[16, 117, 288, 375], [179, 0, 500, 367]]
Chk 874 [[232, 76, 290, 176], [378, 51, 499, 332], [147, 84, 202, 181], [0, 29, 157, 329], [103, 64, 158, 200], [2, 63, 54, 130]]
Chk 875 [[376, 61, 495, 369], [134, 82, 210, 174], [221, 77, 289, 226], [298, 72, 362, 282]]
Chk 877 [[74, 91, 225, 480], [166, 112, 355, 479]]
Chk 878 [[315, 23, 436, 321], [464, 101, 500, 220], [31, 131, 91, 227], [14, 34, 233, 288], [7, 117, 31, 154], [160, 145, 189, 187]]
Chk 879 [[185, 114, 373, 375], [250, 142, 331, 276], [408, 0, 500, 314]]
Chk 880 [[101, 114, 264, 266], [137, 94, 203, 187], [192, 88, 258, 160], [259, 89, 301, 157], [308, 90, 384, 230]]
Chk 881 [[316, 127, 438, 374], [51, 99, 217, 343]]
Chk 882 [[35, 172, 119, 424], [278, 190, 332, 429], [118, 138, 217, 377], [92, 223, 170, 455]]
Chk 883 [[134, 133, 183, 275], [193, 101, 227, 195]]
Chk 884 [[28, 209, 277, 500], [229, 93, 466, 500], [26, 133, 293, 494]]
Chk 885 [[264, 14, 451, 339], [231, 30, 315, 282]]
Chk 886 [[57, 127, 126, 300], [118, 42, 155, 175], [389, 27, 435, 92], [242, 3, 307, 164], [156, 119, 189, 161], [424, 90, 466, 259], [11, 137, 37, 197]]
Chk 888 [[10, 85, 233, 325], [288, 100, 412, 364], [431, 125, 500, 237], [372, 107, 441, 238], [1, 115, 34, 164]]
Chk 889 [[52, 54, 185, 406], [243, 62, 394, 213]]
Chk 890 [[213, 113, 307, 331], [83, 137, 157, 331], [370, 110, 463, 331], [453, 145, 499, 314]]
Chk 891 [[30, 103, 131, 349], [170, 114, 268, 340], [275, 145, 328, 278], [312, 128, 372, 286], [383, 175, 429, 306], [405, 162, 446, 303]]
Chk 892 [[108, 51, 254, 334], [136, 71, 289, 334]]
Chk 893 [[278, 101, 413, 279], [164, 119, 250, 255], [11, 176, 309, 316]]

Chk 895 [[256, 140, 381, 371], [57, 135, 385, 374], [415, 75, 493, 352]]
Chk 896 [[234, 114, 320, 337], [121, 129, 205, 344], [393, 167, 437, 276], [431, 180, 458, 266]]
Chk 897 [[19, 225, 284, 500], [120, 24, 333, 500]]
Chk 898 [[37, 267, 156, 385], [43, 141, 106, 282], [130, 208, 189, 263], [232, 168, 277, 248]]
Chk 899 [[227, 62, 400, 332], [128, 117, 277, 316]]
Chk 900 [[405, 122, 499, 374], [250, 139, 309, 358], [7, 99, 90, 300], [376, 133, 458, 254]]
Chk 903 [[263, 150, 477, 392], [182, 74, 343, 373]]
Chk 904 [[79, 133, 192, 332], [355, 113, 477, 253]]
Chk 906 [[233, 208, 278, 339], [290, 204, 349, 365], [174, 222, 217, 349]]
Chk 908 [[270, 8, 447, 332], [167, 56, 318, 332], [0, 78, 170, 332], [418, 101, 457, 166]]
Chk 910 [[5, 69, 216, 489], [153, 34, 332, 499]]
Chk 912 [[224, 70, 467, 331], [1, 34, 193, 331]]
Chk 914 [[241, 133, 373, 332], [14, 121, 161, 332], [327, 104, 492, 320]]
Chk 916 [[11, 0, 207, 459], [72, 100, 333, 496]]
Chk 917 [[13, 117, 84, 322], [271, 158, 320, 221], [352, 196, 435, 293], [415, 162, 489, 268], [333, 152, 372, 192]]
Chk 918 [[71, 245, 230, 494], [129, 11, 255, 267]]
Chk 919 [[8, 65, 143, 334], [139, 65, 354, 334], [360, 75, 479, 326]]
Chk 920 [[269, 108, 318, 278], [170, 106, 251, 330], [86, 109, 151, 322], [9, 203, 40, 274], [218, 97, 265, 278]]
Chk 921 [[229, 168, 482, 374], [77, 172, 288, 374]]
Chk 922 [[108, 128, 187, 297], [198, 122, 281, 300], [0, 195, 18, 259]]
Chk 923 [[120, 108, 204, 296], [191, 13, 314, 314]]
Chk 926 [[0, 121, 290, 500], [252, 120, 448, 500]]
Chk 927 [[224, 23, 270, 200], [443, 60, 496, 302], [382, 30, 465, 309]]
Chk 928 [[6, 101, 166, 320], [260, 167, 458, 317], [198, 164, 264, 250], [374, 173, 438, 267], [414, 158, 500, 255]]
Chk 930 [[172, 80, 260, 332], [52, 152, 117, 212], [264, 89, 327, 316]]
Chk 931 [[297, 86, 426, 329], [96, 85, 271, 333]]
Chk 932 [[230, 63, 333, 333], [404, 21, 500, 333]]
Chk 933 [[272, 66, 407, 360], [347, 64, 499, 367], [110, 54, 236, 224]]
Chk 934 [[33, 7, 237, 331], [229, 32, 469, 331], [412, 74, 499, 328]]
Chk 935 [[73, 141, 289, 278], [122, 92, 401, 218]]
Chk 936 [[10, 65, 83, 175], [73, 0, 288, 334], [274, 6, 428, 325]]
Chk 937 [[163, 0, 285, 287], [339, 65, 445, 250], [328, 100, 365, 214], [313, 143, 335, 210]]
Chk 938 [[319, 64, 500, 333], [267, 23, 365, 333], [155, 131, 282, 333]]
Chk 939 [[261, 57, 362, 325], [33, 131, 135, 234], [158, 90, 244, 205], [382, 107, 446, 186], [436, 62, 496, 150]]
Chk 941 [[64, 55, 206, 422], [43, 116, 104, 310], [289, 95, 459, 422]]
Chk 942 [[110, 215, 243, 499], [167, 225, 239, 413]]
Chk 943 [[0, 47, 267, 334], [287, 0, 500, 334], [0, 0, 154, 214]]
Chk 945 [[128, 130, 241, 398], [238, 164, 302, 335], [31, 142, 134, 353]]
Chk 947 [[86, 110, 242, 319], [283, 106, 422, 321], [0, 133, 84, 330]]
Chk 949 [[0, 73, 182, 490], [120, 164, 336, 500]]
Chk 950 [[0, 68, 83, 333], [140, 99, 252, 333], [257, 106, 386, 333]]
Chk 952 [[273, 34, 390, 309], [82, 80, 211, 304], [341, 62, 499, 369]]
Chk 953 [[40, 87, 189, 333], [305, 136, 393, 304], [184, 72, 298, 333]]
Chk 955 [[144, 119, 335, 320], [293, 16, 487, 331]]
Chk 956 [[376, 104, 483, 338], [294, 99, 380, 332], [193, 104, 270, 283]]
Chk 958 [[177, 95, 397, 461], [58, 88, 227, 457]]
Chk 959 [[157, 0, 500, 375], [150, 52, 301, 337], [34, 48, 217, 375]]
Chk 960 [[17, 49, 422, 352], [227, 0, 497, 271]]
Chk 961 [[93, 23, 266, 306], [263, 69, 360, 201], [377, 39, 473, 133]]
Chk 963 [[273, 90, 345, 276], [171, 70, 238, 305]]
Chk 964 [[28, 13, 167, 436], [173, 179, 291, 425]]
Chk 965 [[64, 56, 238, 332], [229, 29, 423, 319], [435, 78, 499, 300]]
Chk 966 [[259, 73, 339, 296], [330, 98, 394, 249], [161, 136, 238, 263]]
Chk 967 [[0, 73, 30, 185], [35, 70, 111, 299], [204, 97, 277, 286], [391, 95, 435, 211], [369, 91, 417, 176]]
Chk 968 [[418, 39, 499, 313], [105, 90, 226, 282], [204, 58, 351, 287]]
Chk 969 [[3, 108, 244, 409], [47, 43, 328, 500], [64, 144, 103, 235], [93, 120, 137, 219], [0, 106, 37, 215]]
Chk 970 [[150, 269, 251, 499], [54, 254, 225, 499], [0, 423, 27, 498], [283, 437, 320, 482], [265, 435, 294, 490]]
Chk 971 [[267, 78, 462, 436], [25, 10, 366, 493]]
Chk 972 [[15, 0, 249, 333], [152, 49, 495, 333], [363, 0, 500, 252]]
Chk 973 [[387, 182, 424, 262], [170, 174, 204, 257]]
Chk 974 [[23, 68, 249, 367], [355, 46, 488, 287], [151, 45, 249, 305]]
Chk 975 [[162, 176, 333, 373], [0, 197, 153, 374], [309, 0, 470, 374]]
Chk 976 [[246, 88, 327, 252], [21, 45, 157, 325], [184, 92, 223, 206], [309, 57, 410, 261], [332, 74, 491, 330], [144, 122, 162, 172]]
Chk 977 [[327, 116, 352, 191], [255, 118, 280, 192], [213, 139, 239, 199]]
Chk 978 [[346, 33, 499, 327], [33, 7, 353, 323]]
Chk 980 [[20, 70, 222, 325], [341, 32, 462, 156], [103, 63, 261, 229]]
Chk 981 [[236, 130, 274, 168], [175, 135, 221, 173]]
Chk 982 [[266, 149, 352, 319], [121, 148, 196, 320]]
Chk 983 [[186, 110, 260, 313], [140, 131, 197, 328], [299, 218, 369, 357]]
Chk 984 [[293, 94, 405, 334], [139, 43, 290, 246]]
Chk 986 [[219, 11, 500, 369], [0, 96, 268, 369]]
Chk 988 [[54, 70, 136, 185], [240, 60, 443, 375], [75, 81, 420, 375]]
Chk 989 [[127, 56, 226, 208], [295, 84, 374, 190], [441, 93, 466, 131], [418, 94, 441, 125], [365, 90, 389, 132]]
Chk 990 [[317, 167, 372, 271], [176, 162, 226, 208], [264, 160, 296, 268], [238, 139, 273, 190]]
Chk 991 [[114, 156, 288, 262], [188, 100, 285, 230]]
Chk 992 [[39, 158, 181, 477], [121, 157, 213, 426]]
Chk 994 [[342, 128, 399, 264], [141, 172, 187, 272], [73, 167, 112, 252]]
Chk 995 [[44, 64, 267, 320], [454, 100, 497, 204], [233, 140, 459, 309]]
Chk 998 [[180, 50, 259, 172], [335, 104, 442, 262], [48, 35, 128, 268], [440, 74, 473, 154]]
Chk 1000 [[2, 0, 120, 211], [220, 21, 500, 404]]
Chk 1001 [[308, 215, 423, 374], [37, 177, 210, 369], [204, 159, 230, 206], [386, 187, 408, 218]]
Chk 1002 [[24, 199, 332, 499], [82, 15, 332, 404]]
Chk 1004 [[92, 117, 236, 365], [259, 254, 348, 365]]
Chk 1005 [[28, 82, 75, 162], [296, 87, 343, 217], [439, 98, 500, 219]]
Chk 1007 [[373, 119, 452, 324], [66, 69, 215, 301]]
Chk 1008 [[293, 8, 428, 320], [97, 127, 213, 329], [193, 129, 259, 231]]
Chk 1009 [[172, 46, 482, 318], [142, 53, 457, 317], [238, 19, 324, 107], [127, 2, 241, 102]]
Chk 1010 [[265, 55, 341, 222], [56, 157, 110, 273], [154, 126, 186, 230]]
Chk 1012 [[115, 150, 215, 426], [202, 159, 277, 411]]
Chk 1013 [[273, 101, 400, 346], [131, 106, 201, 294], [189, 163, 236, 301]]
Chk 1014 [[242, 35, 389, 224], [31, 0, 171, 373]]
Chk 1015 [[0, 31, 337, 500], [3, 63, 337, 500]]
Chk 1016 [[233, 59, 366, 235], [149, 78, 377, 332], [75, 38, 235, 269], [370, 82, 416, 136]]
Chk 1017 [[365, 156, 443, 313], [233, 115, 354, 309], [155, 140, 254, 355], [366, 265, 408, 306]]
Chk 1018 [[421, 29, 500, 306], [267, 103, 430, 268], [190, 84, 492, 332]]
Chk 1019 [[0, 199, 88, 375], [243, 6, 377, 182], [94, 143, 168, 362], [89, 301, 157, 375]]
Chk 1020 [[1, 10, 71, 207], [123, 34, 272, 293], [291, 141, 432, 329]]
Chk 1021 [[13, 131, 240, 363], [67, 141, 243, 260], [237, 135, 332, 243], [365, 134, 493, 313]]
Chk 1022 [[3, 16, 84, 141], [36, 31, 193, 234], [184, 10, 361, 394]]
Chk 1023 [[387, 257, 426, 338], [417, 248, 451, 331], [154, 239, 191, 318], [172, 219, 214, 293]]
Chk 1024 [[147, 133, 221, 224], [297, 120, 367, 212], [375, 111, 468, 211]]
Chk 1025 [[232, 74, 295, 262], [316, 87, 379, 234], [356, 49, 414, 247]]
Chk 1026 [[0, 116, 249, 499], [180, 0, 374, 499]]
Chk 1027 [[74, 22, 263, 369], [258, 1, 460, 374]]
Chk 1028 [[272, 95, 411, 308], [173, 117, 266, 290], [48, 87, 195, 323]]
Chk 1029 [[76, 52, 327, 271], [84, 151, 340, 429]]
Chk 1030 [[67, 125, 194, 273], [244, 172, 386, 316]]
Chk 1031 [[289, 39, 440, 236], [0, 40, 245, 331]]
Chk 1032 [[55, 125, 151, 374], [202, 177, 266, 307]]
Chk 1034 [[363, 108, 420, 280], [407, 86, 466, 280]]
Chk 1035 [[389, 29, 485, 161], [4, 94, 85, 239], [37, 72, 88, 149], [90, 101, 142, 170], [112, 93, 168, 161], [165, 103, 264, 250]]
Chk 1036 [[355, 75, 499, 374], [199, 98, 345, 372], [5, 91, 101, 374]]
Chk 1037 [[58, 70, 182, 279], [78, 191, 174, 333], [212, 209, 309, 333], [289, 2, 494, 333]]
Chk 1039 [[99, 50, 168, 214], [195, 39, 252, 209]]
Chk 1040 [[32, 33, 161, 232], [330, 35, 497, 330], [206, 107, 413, 332]]
Chk 1041 [[3, 161, 170, 329], [152, 69, 384, 279]]
Chk 1042 [[263, 139, 372, 334], [87, 148, 190, 326]]
Chk 1043 [[151, 92, 323, 499], [7, 40, 180, 499]]
Chk 1044 [[2, 151, 187, 476], [82, 183, 332, 500]]
Chk 1045 [[118, 248, 182, 380], [15, 236, 53, 365], [15, 319, 60, 363]]
Chk 1046 [[424, 92, 479, 228], [157, 123, 221, 196], [233, 120, 290, 212], [470, 147, 492, 198]]
Chk 1047 [[350, 91, 417, 230], [91, 123, 163, 312], [161, 115, 227, 318]]
Chk 1048 [[71, 136, 166, 293], [142, 135, 195, 256], [213, 133, 266, 283], [254, 124, 308, 275], [423, 153, 492, 278]]
Chk 1049 [[26, 44, 117, 293], [302, 45, 420, 325], [224, 37, 270, 150], [268, 38, 313, 139], [414, 29, 473, 215]]
Chk 1050 [[291, 60, 467, 320], [100, 80, 264, 305], [2, 96, 132, 266]]
Chk 1052 [[170, 41, 286, 160], [280, 43, 386, 156]]
Chk 1053 [[7, 6, 290, 314], [257, 121, 500, 332]]

Chk 1054 [[303, 30, 413, 322], [133, 146, 226, 324]]
Chk 1055 [[136, 52, 240, 214], [231, 48, 311, 194], [153, 72, 432, 331]]
Chk 1056 [[5, 133, 80, 332], [293, 53, 375, 277], [113, 151, 235, 331], [95, 155, 166, 303]]
Chk 1057 [[0, 47, 327, 333], [197, 64, 354, 247], [339, 21, 500, 195]]
Chk 1058 [[132, 103, 409, 326], [154, 103, 401, 316]]
Chk 1059 [[339, 63, 403, 205], [113, 49, 179, 209]]
Chk 1060 [[304, 179, 497, 374], [112, 78, 326, 374]]
Chk 1061 [[0, 0, 72, 297], [111, 106, 175, 333], [240, 62, 404, 333], [233, 31, 376, 333]]
Chk 1062 [[19, 135, 199, 462], [149, 152, 221, 245]]
Chk 1063 [[66, 17, 145, 167], [125, 16, 196, 195], [337, 25, 406, 166], [304, 40, 359, 149]]
Chk 1064 [[4, 196, 123, 451], [116, 198, 247, 493], [215, 203, 314, 463]]
Chk 1066 [[286, 107, 459, 310], [91, 78, 375, 330]]
Chk 1067 [[42, 101, 177, 253], [259, 112, 349, 229], [362, 101, 457, 238]]
Chk 1068 [[102, 61, 290, 332], [293, 114, 492, 332]]
Chk 1069 [[244, 64, 385, 333], [346, 72, 461, 333]]
Chk 1070 [[0, 58, 252, 309], [109, 27, 272, 270], [281, 61, 442, 263], [289, 210, 500, 333]]
Chk 1071 [[271, 131, 310, 215], [206, 115, 256, 217]]
Chk 1073 [[54, 17, 237, 333], [328, 57, 498, 324], [10, 21, 122, 329]]
Chk 1074 [[8, 9, 187, 251], [224, 40, 462, 234], [94, 59, 228, 230]]
Chk 1075 [[81, 22, 247, 313], [190, 0, 471, 318]]
Chk 1076 [[207, 201, 258, 250], [347, 171, 385, 255], [217, 165, 242, 199]]
Chk 1077 [[0, 97, 160, 332], [169, 61, 325, 325], [283, 106, 496, 333]]
Chk 1078 [[0, 0, 102, 176], [152, 10, 285, 321], [210, 22, 379, 391]]
Chk 1079 [[364, 84, 446, 254], [214, 104, 277, 262], [68, 75, 139, 267]]
Chk 1080 [[375, 55, 461, 331], [187, 75, 283, 332], [14, 90, 146, 374], [265, 84, 340, 315], [386, 47, 425, 95]]
Chk 1081 [[51, 171, 266, 423], [250, 132, 398, 335]]
Chk 1082 [[73, 151, 155, 371], [218, 171, 280, 350], [344, 144, 408, 347], [214, 127, 276, 232]]
Chk 1083 [[64, 64, 146, 297], [293, 61, 373, 319]]
Chk 1084 [[73, 46, 382, 324], [236, 69, 435, 327]]
Chk 1086 [[93, 140, 183, 473], [265, 157, 305, 276], [211, 166, 247, 279]]
Chk 1087 [[141, 62, 245, 341], [297, 15, 465, 374], [59, 27, 176, 374], [4, 0, 88, 374]]
Chk 1088 [[77, 50, 181, 363], [95, 41, 186, 335], [369, 76, 419, 188], [311, 101, 394, 145]]
Chk 1089 [[100, 98, 181, 333], [289, 26, 436, 333]]
Chk 1090 [[203, 154, 245, 229], [329, 115, 404, 211]]
Chk 1091 [[255, 82, 403, 379], [36, 109, 198, 480], [148, 174, 252, 388]]
Chk 1092 [[1, 40, 158, 500], [120, 53, 311, 500]]
Chk 1093 [[185, 18, 253, 195], [269, 51, 356, 165], [0, 67, 133, 345], [1, 86, 41, 159], [268, 10, 500, 362]]
Chk 1094 [[260, 182, 319, 374], [201, 190, 281, 374]]
Chk 1096 [[0, 128, 192, 435], [218, 120, 344, 350], [260, 49, 491, 435]]
Chk 1097 [[62, 23, 279, 364], [222, 71, 406, 263]]
Chk 1098 [[49, 16, 270, 458], [165, 14, 426, 463]]
Chk 1099 [[0, 23, 197, 283], [258, 45, 424, 283], [101, 59, 250, 283]]
Chk 1100 [[270, 82, 409, 332], [129, 105, 264, 319]]
Chk 1101 [[225, 117, 300, 265], [142, 126, 197, 189], [36, 127, 149, 288]]
Chk 1103 [[167, 107, 240, 247], [231, 113, 282, 253]]
Chk 1104 [[284, 58, 453, 283], [175, 66, 320, 234], [0, 201, 307, 333], [0, 70, 38, 161]]
Chk 1105 [[182, 47, 236, 94], [48, 88, 207, 333], [256, 49, 350, 328], [303, 40, 426, 333], [411, 129, 457, 250], [448, 183, 495, 240]]
Chk 1106 [[345, 11, 477, 332], [277, 115, 351, 326], [113, 24, 283, 328]]
Chk 1107 [[12, 105, 102, 259], [98, 11, 206, 129], [232, 21, 346, 142], [341, 125, 434, 260]]
Chk 1108 [[139, 130, 220, 280], [278, 134, 375, 283]]
Chk 1109 [[1, 81, 435, 331], [225, 115, 469, 333]]
Chk 1110 [[335, 99, 426, 330], [206, 147, 268, 261], [91, 140, 196, 293]]
Chk 1111 [[117, 362, 156, 435], [201, 350, 239, 432], [268, 347, 302, 440]]
Chk 1112 [[223, 173, 278, 261], [103, 241, 207, 461], [387, 239, 438, 364]]
Chk 1113 [[317, 121, 421, 498], [29, 41, 195, 499]]
Chk 1114 [[364, 154, 407, 261], [310, 136, 355, 256], [238, 112, 316, 305], [205, 131, 251, 199]]
Chk 1115 [[219, 81, 295, 293], [157, 84, 227, 280]]
Chk 1117 [[269, 67, 368, 438], [196, 133, 276, 391]]
Chk 1118 [[123, 74, 194, 159], [200, 48, 272, 120]]
Chk 1119 [[0, 50, 328, 333], [273, 93, 380, 269], [226, 7, 500, 333], [345, 143, 492, 333]]
Chk 1120 [[57, 77, 248, 328], [231, 95, 423, 329]]
Chk 1121 [[162, 81, 283, 375], [212, 107, 305, 375], [215, 162, 272, 265]]
Chk 1123 [[14, 46, 245, 277], [463, 58, 500, 214], [257, 31, 500, 279]]
Chk 1124 [[45, 118, 141, 324], [266, 91, 389, 195]]
Chk 1125 [[181, 125, 328, 274], [23, 134, 183, 262]]
Chk 1127 [[297, 184, 495, 374], [6, 174, 231, 369], [145, 137, 202, 236], [213, 130, 363, 341]]
Chk 1129 [[120, 27, 335, 331], [74, 39, 329, 333], [0, 24, 115, 255]]
Chk 1131 [[307, 64, 353, 221], [40, 48, 155, 416], [173, 79, 205, 152], [269, 56, 303, 223]]
Chk 1132 [[200, 189, 315, 489], [186, 164, 262, 423], [44, 183, 180, 412]]
Chk 1133 [[207, 89, 296, 331], [76, 87, 192, 329]]
Chk 1134 [[214, 33, 323, 242], [67, 4, 265, 264], [0, 8, 144, 329], [290, 26, 375, 188]]
Chk 1136 [[147, 60, 237, 300], [235, 57, 338, 299], [100, 59, 138, 194], [53, 74, 125, 183], [395, 72, 437, 183]]
Chk 1137 [[230, 64, 320, 324], [165, 60, 246, 302]]
Chk 1138 [[50, 80, 212, 324], [300, 39, 489, 332], [183, 63, 367, 332]]
Chk 1139 [[267, 70, 468, 374], [109, 53, 297, 374]]
Chk 1140 [[211, 56, 409, 335], [105, 22, 286, 335]]
Chk 1141 [[34, 127, 122, 225], [142, 124, 223, 214], [203, 69, 264, 174], [79, 52, 133, 170], [243, 100, 290, 165], [261, 79, 310, 134], [187, 30, 228, 95]]
Chk 1143 [[4, 61, 76, 253], [173, 160, 260, 357], [213, 437, 276, 496]]
Chk 1144 [[5, 16, 86, 231], [71, 7, 123, 185], [180, 22, 226, 174], [225, 32, 327, 222], [116, 151, 276, 402], [308, 142, 474, 297]]
Chk 1145 [[12, 0, 331, 370], [162, 15, 484, 373]]
Chk 1146 [[90, 127, 180, 375], [200, 138, 300, 375]]
Chk 1147 [[60, 75, 160, 225], [291, 144, 393, 255], [386, 155, 484, 270]]
Chk 1148 [[87, 149, 200, 339], [237, 102, 298, 302], [317, 59, 389, 331]]
Chk 1149 [[23, 0, 219, 319], [160, 35, 313, 261], [443, 158, 498, 331]]
Chk 1150 [[15, 41, 282, 355], [242, 138, 384, 374]]
Chk 1151 [[0, 3, 354, 365], [222, 107, 499, 365]]
Chk 1152 [[135, 111, 175, 276], [174, 66, 216, 226], [129, 49, 185, 136], [283, 81, 335, 262], [337, 60, 404, 309], [7, 147, 53, 294], [21, 10, 144, 333]]
Chk 1153 [[425, 47, 493, 195], [24, 81, 153, 328], [184, 113, 254, 203], [221, 17, 436, 299], [67, 137, 230, 326], [226, 88, 350, 227]]
Chk 1155 [[75, 42, 227, 375], [178, 43, 424, 375], [286, 0, 417, 106]]
Chk 1156 [[57, 147, 242, 499], [176, 55, 351, 491]]
Chk 1157 [[67, 117, 152, 333], [228, 75, 322, 242], [290, 14, 389, 203], [382, 36, 456, 206]]
Chk 1158 [[120, 41, 315, 332], [319, 31, 499, 332]]
Chk 1159 [[277, 184, 354, 358], [108, 166, 179, 349], [12, 205, 55, 325], [212, 179, 272, 331]]
Chk 1160 [[81, 143, 179, 371], [155, 162, 254, 374]]
Chk 1161 [[249, 116, 352, 263], [95, 122, 203, 266]]
Chk 1162 [[364, 145, 444, 354], [0, 144, 73, 343], [171, 138, 258, 338], [260, 72, 365, 169], [93, 169, 149, 346]]
Chk 1164 [[95, 161, 185, 468], [141, 183, 279, 493]]
Chk 1165 [[211, 41, 453, 298], [55, 41, 218, 332]]
Chk 1166 [[41, 57, 314, 374], [208, 96, 443, 374]]
Chk 1172 [[344, 47, 434, 332], [191, 112, 237, 301], [38, 142, 122, 270], [240, 171, 278, 250], [457, 187, 496, 229]]
Chk 1175 [[342, 135, 446, 281], [218, 139, 292, 280], [86, 147, 172, 278], [57, 160, 111, 250], [0, 234, 29, 299]]
Chk 1176 [[195, 90, 361, 333], [106, 80, 227, 191]]
Chk 1177 [[0, 0, 251, 362], [226, 81, 435, 309]]
Chk 1179 [[0, 109, 219, 332], [145, 119, 261, 236], [312, 121, 412, 236], [370, 140, 500, 332]]
Chk 1180 [[31, 35, 312, 326], [175, 1, 499, 332], [232, 59, 266, 131]]
Chk 1182 [[278, 70, 499, 330], [177, 62, 381, 302], [55, 32, 241, 267]]
Chk 1183 [[175, 54, 271, 156], [284, 61, 427, 168]]
Chk 1184 [[81, 114, 172, 381], [212, 141, 316, 416], [311, 121, 427, 444]]
Chk 1185 [[176, 118, 258, 336], [64, 153, 138, 357]]
Chk 1186 [[53, 54, 167, 345], [293, 50, 414, 376], [169, 66, 351, 392]]
Chk 1187 [[70, 117, 272, 375], [231, 113, 360, 340]]
Chk 1188 [[37, 243, 155, 499], [121, 261, 194, 457]]
Chk 1189 [[110, 150, 254, 354], [376, 136, 490, 241], [16, 153, 117, 364]]
Chk 1190 [[237, 86, 390, 225], [98, 46, 248, 235]]
Chk 1191 [[103, 115, 233, 436], [2, 259, 70, 360], [247, 49, 390, 500], [385, 304, 439, 421], [427, 304, 475, 413]]

Chk 1193 [[108, 62, 329, 245], [155, 19, 493, 439]]
Chk 1194 [[29, 146, 146, 276], [209, 136, 330, 258], [330, 131, 440, 281]]
Chk 1195 [[114, 136, 263, 331], [36, 120, 188, 331]]
Chk 1196 [[10, 63, 201, 307], [119, 63, 240, 211], [397, 66, 487, 236], [282, 55, 464, 375]]
Chk 1197 [[230, 29, 446, 367], [131, 40, 274, 275]]
Chk 1198 [[39, 220, 92, 409], [105, 288, 148, 404]]
Chk 1200 [[186, 65, 346, 331], [56, 110, 213, 399], [135, 122, 200, 335]]
Chk 1201 [[243, 48, 408, 308], [80, 32, 273, 314]]
Chk 1202 [[238, 87, 349, 332], [77, 26, 177, 302]]
Chk 1203 [[36, 46, 187, 276], [219, 48, 438, 276]]
Chk 1204 [[398, 226, 476, 378], [147, 48, 332, 497], [25, 144, 194, 477]]
Chk 1205 [[214, 38, 300, 181], [0, 56, 66, 186], [102, 41, 171, 192]]
Chk 1206 [[220, 69, 270, 187], [184, 65, 254, 323], [266, 74, 371, 311]]
Chk 1207 [[286, 39, 372, 267], [395, 17, 495, 305], [100, 83, 214, 221]]
Chk 1210 [[233, 109, 480, 492], [152, 47, 326, 494]]
Chk 1211 [[297, 131, 446, 500], [0, 142, 212, 500], [109, 9, 299, 500]]
Chk 1213 [[65, 58, 199, 333], [291, 35, 407, 269], [203, 45, 309, 318]]
Chk 1214 [[148, 150, 265, 481], [75, 126, 180, 462]]
Chk 1215 [[0, 0, 169, 333], [232, 45, 500, 333], [403, 19, 485, 135], [276, 43, 500, 333]]
Chk 1216 [[277, 119, 365, 332], [185, 160, 315, 332]]
Chk 1217 [[43, 74, 311, 269], [289, 0, 500, 306]]
Chk 1218 [[12, 32, 207, 367], [293, 41, 499, 373], [144, 90, 345, 374]]
Chk 1219 [[9, 83, 108, 333], [409, 87, 499, 330], [229, 145, 293, 221]]
Chk 1220 [[3, 67, 181, 374], [283, 16, 473, 303], [331, 138, 489, 374], [99, 39, 244, 328]]
Chk 1221 [[301, 59, 497, 325], [7, 35, 254, 332], [252, 108, 374, 317]]
Chk 1222 [[47, 162, 142, 251], [49, 102, 115, 195], [171, 88, 223, 192], [258, 85, 302, 192], [294, 104, 344, 199]]
Chk 1224 [[311, 148, 500, 421], [146, 110, 263, 393]]
Chk 1225 [[0, 42, 293, 318], [181, 9, 353, 265], [395, 101, 500, 248]]
Chk 1226 [[296, 90, 450, 331], [166, 83, 325, 301]]
Chk 1227 [[318, 190, 355, 281], [205, 193, 245, 265]]
Chk 1228 [[68, 138, 263, 472], [85, 0, 263, 226], [307, 228, 330, 310]]
Chk 1230 [[134, 93, 199, 259], [56, 76, 119, 266], [303, 79, 392, 349], [371, 77, 432, 294]]
Chk 1231 [[362, 118, 484, 500], [24, 130, 205, 500], [237, 127, 403, 500]]
Chk 1232 [[122, 71, 238, 303], [280, 26, 484, 331], [189, 53, 300, 327], [1, 27, 103, 314]]
Chk 1233 [[292, 102, 428, 329], [6, 10, 193, 329], [118, 160, 201, 315]]
Chk 1234 [[335, 138, 424, 370], [121, 127, 211, 374]]
Chk 1235 [[48, 51, 205, 333], [169, 30, 342, 333]]
Chk 1236 [[79, 92, 333, 500], [0, 89, 214, 500]]
Chk 1237 [[72, 120, 238, 311], [147, 111, 226, 258], [211, 108, 344, 267]]
Chk 1238 [[163, 45, 298, 395], [312, 58, 430, 429]]
Chk 1239 [[240, 42, 364, 317], [364, 71, 491, 297], [130, 44, 230, 276], [354, 83, 385, 143]]
Chk 1240 [[301, 71, 404, 286], [188, 82, 323, 295], [138, 24, 273, 264], [26, 32, 226, 289]]
Chk 1241 [[114, 96, 235, 304], [250, 105, 346, 304]]
Chk 1242 [[272, 5, 383, 211], [26, 120, 130, 223]]
Chk 1244 [[178, 40, 254, 259], [303, 38, 376, 276]]
Chk 1245 [[125, 96, 217, 190], [365, 178, 437, 263]]
Chk 1246 [[382, 199, 500, 374], [323, 114, 500, 315], [271, 85, 390, 247], [0, 0, 224, 374]]
Chk 1247 [[166, 0, 483, 330], [9, 73, 209, 331]]
Chk 1248 [[1, 25, 209, 487], [126, 219, 235, 446]]
Chk 1249 [[142, 10, 280, 233], [273, 32, 448, 372]]
Chk 1250 [[70, 117, 175, 389], [127, 136, 195, 379]]
Chk 1251 [[303, 0, 500, 375], [423, 82, 471, 120], [357, 9, 500, 375], [91, 61, 334, 313], [0, 36, 110, 375]]
Chk 1252 [[5, 8, 249, 499], [134, 141, 332, 479]]
Chk 1254 [[83, 60, 329, 367], [191, 32, 480, 356]]
Chk 1255 [[70, 5, 225, 266], [157, 0, 285, 169]]
Chk 1257 [[254, 54, 431, 285], [215, 62, 327, 258]]
Chk 1258 [[161, 45, 336, 499], [2, 40, 182, 497]]
Chk 1259 [[43, 148, 230, 278], [155, 139, 322, 333]]
Chk 1260 [[139, 57, 201, 245], [320, 67, 406, 256], [56, 85, 106, 176]]
Chk 1261 [[178, 74, 371, 374], [88, 90, 265, 374]]
Chk 1262 [[149, 97, 311, 332], [280, 78, 398, 329]]
Chk 1263 [[16, 89, 160, 353], [128, 167, 333, 399]]
Chk 1265 [[164, 81, 339, 313], [44, 88, 215, 302]]
Chk 1266 [[247, 219, 335, 476], [146, 246, 224, 454], [30, 193, 140, 489]]
Chk 1267 [[150, 49, 319, 484], [25, 137, 189, 489]]
Chk 1269 [[70, 51, 166, 201], [347, 38, 496, 348]]
Chk 1270 [[0, 103, 190, 374], [345, 70, 499, 374]]
Chk 1271 [[184, 149, 267, 276], [245, 177, 388, 317], [219, 159, 333, 289]]
Chk 1272 [[243, 73, 373, 374], [368, 97, 492, 365], [0, 116, 166, 371], [123, 84, 243, 285]]
Chk 1273 [[33, 72, 251, 374], [314, 53, 500, 309]]
Chk 1275 [[162, 70, 213, 144], [94, 34, 245, 216], [157, 62, 276, 235], [321, 135, 411, 280]]
Chk 1276 [[259, 82, 421, 365], [117, 65, 249, 323]]
Chk 1277 [[24, 25, 243, 378], [198, 217, 333, 471]]
Chk 1278 [[12, 137, 221, 343], [128, 128, 254, 291], [333, 118, 433, 324], [388, 123, 481, 249]]
Chk 1279 [[269, 85, 385, 374], [109, 35, 270, 374]]
Chk 1280 [[344, 39, 446, 287], [210, 39, 312, 279], [450, 101, 500, 219], [312, 76, 358, 179], [109, 24, 188, 273], [9, 76, 52, 191]]
Chk 1282 [[78, 119, 273, 321], [313, 136, 500, 333]]
Chk 1283 [[0, 0, 286, 333], [263, 0, 500, 333]]
Chk 1284 [[342, 67, 499, 373], [76, 137, 169, 356], [155, 126, 308, 367]]
Chk 1285 [[95, 129, 334, 500], [92, 149, 323, 500]]
Chk 1286 [[254, 25, 459, 368], [104, 26, 280, 280]]
Chk 1287 [[14, 202, 116, 349], [175, 157, 306, 341]]
Chk 1288 [[158, 0, 499, 374], [47, 20, 263, 368]]
Chk 1289 [[39, 15, 231, 280], [221, 41, 374, 254]]
Chk 1290 [[345, 53, 499, 374], [124, 85, 348, 373], [7, 61, 150, 352]]
Chk 1291 [[198, 0, 309, 267], [326, 29, 500, 332], [0, 0, 140, 332], [66, 13, 230, 295]]
Chk 1293 [[348, 119, 416, 375], [268, 135, 337, 359], [252, 142, 296, 258], [208, 197, 269, 301], [173, 209, 241, 351], [146, 194, 210, 276], [103, 192, 179, 371]]
Chk 1295 [[40, 344, 111, 499], [294, 318, 334, 362], [0, 333, 62, 491]]
Chk 1297 [[246, 37, 441, 331], [40, 51, 267, 316]]
Chk 1298 [[0, 50, 148, 357], [165, 68, 249, 243], [177, 42, 353, 362], [335, 40, 494, 362]]
Chk 1299 [[95, 65, 343, 331], [265, 31, 480, 331], [14, 65, 79, 174]]
Chk 1300 [[178, 128, 281, 332], [248, 115, 371, 332]]
Chk 1301 [[183, 100, 289, 374], [19, 54, 175, 375]]
Chk 1302 [[0, 0, 282, 364], [300, 94, 493, 365]]
Chk 1303 [[166, 60, 451, 284], [120, 87, 259, 314], [12, 112, 109, 243], [454, 177, 499, 316]]
Chk 1304 [[173, 53, 385, 333], [358, 78, 498, 333], [0, 25, 144, 333]]
Chk 1306 [[229, 10, 381, 399], [86, 157, 172, 350], [38, 5, 98, 138], [4, 63, 42, 149], [325, 77, 459, 391]]
Chk 1307 [[0, 0, 183, 361], [134, 31, 321, 361], [332, 21, 500, 361], [203, 2, 272, 102], [422, 0, 500, 113]]
Chk 1308 [[156, 58, 245, 332], [260, 53, 338, 315], [339, 82, 369, 162], [362, 79, 431, 233], [453, 84, 498, 203]]
Chk 1310 [[101, 216, 176, 352], [436, 74, 499, 328], [92, 97, 160, 292], [199, 129, 258, 292]]
Chk 1312 [[97, 45, 206, 324], [140, 65, 171, 105], [243, 60, 386, 376]]
Chk 1313 [[64, 74, 200, 341], [142, 87, 342, 376], [296, 127, 470, 376]]
Chk 1314 [[74, 202, 248, 457], [217, 213, 364, 463], [259, 43, 402, 285], [381, 47, 479, 264]]
Chk 1315 [[298, 171, 333, 254], [175, 164, 213, 255]]
Chk 1316 [[38, 65, 190, 249], [277, 58, 456, 246]]
Chk 1317 [[81, 15, 256, 499], [49, 0, 166, 465]]
Chk 1318 [[345, 103, 459, 332], [194, 25, 369, 332], [56, 52, 238, 332]]
Chk 1320 [[402, 111, 499, 324], [232, 148, 334, 324], [17, 171, 185, 310]]
Chk 1321 [[4, 85, 182, 333], [157, 99, 387, 333], [368, 67, 500, 333]]
Chk 1322 [[169, 168, 205, 289], [48, 159, 102, 321]]
Chk 1324 [[0, 0, 264, 332], [265, 70, 455, 264], [401, 1, 500, 212], [67, 0, 120, 74], [461, 117, 500, 206]]
Chk 1325 [[10, 41, 225, 332], [220, 3, 491, 332], [0, 62, 61, 332]]
Chk 1326 [[45, 54, 208, 312], [109, 41, 179, 158], [226, 55, 334, 248], [287, 86, 394, 240]]
Chk 1327 [[146, 115, 309, 288], [241, 138, 393, 275]]
Chk 1328 [[145, 64, 246, 248], [84, 78, 263, 316], [408, 50, 500, 295], [352, 68, 437, 274]]
Chk 1329 [[43, 154, 292, 338], [272, 100, 380, 241]]
Chk 1332 [[162, 96, 226, 246], [242, 80, 291, 234]]
Chk 1333 [[251, 124, 308, 286], [125, 101, 190, 286], [150, 169, 280, 324]]
Chk 1334 [[453, 33, 500, 199], [331, 33, 405, 220], [159, 82, 332, 228], [79, 129, 167, 217]]
Chk 1336 [[363, 182, 419, 367], [299, 176, 359, 346], [99, 168, 149, 241]]
Chk 1338 [[107, 212, 221, 457], [239, 84, 275, 170], [205, 80, 251, 159]]
Chk 1339 [[91, 47, 201, 333], [209, 55, 474, 333]]
Chk 1340 [[197, 206, 273, 308], [114, 223, 173, 315], [328, 187, 369, 266]]
Chk 1342 [[304, 93, 370, 251], [54, 75, 126, 260], [163, 112, 214, 222], [245, 94, 304, 249], [217, 98, 255, 230]]
Chk 1343 [[176, 122, 312, 331], [277, 43, 350, 211], [414, 173, 480, 245]]
Chk 1344 [[286, 55, 433, 333], [139, 103, 332, 329]]
Chk 1346 [[20, 66, 169, 500], [141, 87, 287, 500]]
Chk 1348 [[198, 99, 500, 333], [12, 89, 200, 333], [178, 83, 358, 290], [0, 41, 156, 333]]
Chk 1349 [[150, 195, 195, 347], [52, 231, 79, 273], [7, 224, 28, 267]]
Chk 1350 [[66, 64, 277, 375], [171, 29, 458, 375]]
Chk 1351 [[36, 120, 99, 333], [380, 115, 481, 333], [311, 117, 393, 333], [124, 152, 208, 270], [209, 142, 306, 333]]
Chk 1352 [[7, 0, 310, 334], [294, 166, 429, 334]]
Chk 1353 [[263, 135, 360, 332], [95, 162, 189, 332], [359, 177, 499, 332], [3, 159, 136, 332]]

Chk 1354 [[15, 146, 116, 292], [115, 171, 211, 333], [197, 127, 316, 291], [352, 135, 500, 333], [108, 142, 204, 229]]
Chk 1355 [[162, 91, 346, 284], [300, 99, 491, 341], [1, 114, 182, 315]]
Chk 1356 [[57, 159, 137, 305], [147, 178, 220, 324], [219, 174, 296, 329], [305, 174, 379, 346]]
Chk 1358 [[160, 195, 224, 340], [70, 164, 155, 347]]
Chk 1359 [[0, 173, 63, 291], [50, 10, 282, 333], [218, 73, 363, 333]]
Chk 1363 [[179, 60, 268, 229], [54, 54, 179, 260]]
Chk 1365 [[105, 121, 211, 325], [155, 186, 363, 368]]
Chk 1366 [[269, 160, 307, 307], [220, 150, 264, 310]]
Chk 1367 [[34, 13, 162, 156], [0, 125, 156, 290], [43, 91, 235, 392], [278, 0, 451, 355], [406, 241, 500, 397]]
Chk 1368 [[166, 224, 239, 499], [92, 216, 167, 493]]
Chk 1370 [[359, 185, 445, 265], [93, 67, 199, 335], [269, 100, 348, 253]]
Chk 1371 [[56, 99, 184, 332], [255, 38, 435, 332], [54, 263, 85, 317]]
Chk 1372 [[225, 295, 330, 469], [30, 191, 282, 384]]
Chk 1374 [[135, 152, 205, 341], [60, 140, 138, 340]]
Chk 1375 [[36, 77, 342, 331], [284, 68, 496, 331]]
Chk 1377 [[267, 14, 366, 319], [192, 32, 285, 319], [351, 26, 464, 319]]
Chk 1378 [[106, 126, 201, 287], [205, 100, 315, 301]]
Chk 1379 [[47, 58, 188, 333], [163, 79, 290, 331], [354, 44, 499, 333], [270, 62, 365, 333]]
Chk 1381 [[105, 107, 164, 191], [217, 109, 267, 214]]
Chk 1382 [[184, 109, 265, 228], [94, 111, 165, 248]]
Chk 1384 [[157, 172, 242, 418], [92, 167, 182, 395]]
Chk 1385 [[130, 118, 230, 239], [45, 169, 141, 235], [366, 136, 491, 249], [258, 160, 283, 195]]
Chk 1386 [[21, 77, 95, 324], [56, 100, 171, 306], [249, 79, 387, 295]]
Chk 1387 [[138, 128, 237, 332], [228, 63, 385, 328]]
Chk 1388 [[134, 72, 266, 326], [204, 60, 269, 243]]
Chk 1389 [[290, 92, 477, 401], [0, 62, 237, 472], [204, 39, 303, 405], [108, 25, 275, 410]]
Chk 1390 [[0, 147, 322, 372], [271, 89, 499, 372]]
Chk 1391 [[0, 184, 119, 357], [75, 198, 116, 245], [366, 103, 500, 357]]
Chk 1392 [[298, 165, 342, 266], [393, 163, 426, 270], [357, 162, 392, 250]]
Chk 1393 [[21, 56, 205, 254], [278, 54, 475, 250]]
Chk 1394 [[322, 23, 477, 263], [222, 39, 438, 272]]
Chk 1395 [[430, 21, 499, 255], [0, 39, 61, 332], [182, 21, 288, 295], [117, 40, 152, 110], [259, 44, 336, 249]]
Chk 1398 [[214, 54, 375, 330], [326, 18, 451, 297], [411, 0, 500, 181]]
Chk 1399 [[18, 194, 56, 313], [110, 203, 157, 307], [98, 202, 134, 288]]
Chk 1400 [[149, 73, 312, 369], [410, 35, 499, 283]]
Chk 1401 [[151, 73, 250, 332], [256, 78, 347, 324]]
Chk 1402 [[191, 73, 494, 332], [141, 114, 353, 332]]
Chk 1403 [[0, 26, 244, 333], [279, 61, 477, 333]]
Chk 1404 [[21, 47, 113, 198], [185, 58, 348, 333], [290, 47, 421, 333]]
Chk 1405 [[17, 74, 250, 370], [226, 95, 422, 382]]
Chk 1407 [[154, 205, 213, 311], [319, 173, 386, 371]]
Chk 1409 [[174, 55, 297, 335], [300, 34, 395, 267], [458, 41, 499, 120]]
Chk 1410 [[251, 196, 306, 346], [188, 190, 232, 339]]
Chk 1411 [[209, 106, 338, 330], [38, 34, 299, 333]]
Chk 1412 [[178, 8, 416, 348], [13, 63, 321, 375]]
Chk 1413 [[23, 120, 268, 500], [277, 206, 475, 500]]
Chk 1414 [[26, 73, 132, 281], [146, 55, 252, 302], [315, 59, 410, 283]]
Chk 1416 [[93, 97, 264, 278], [432, 153, 499, 263], [258, 159, 380, 272]]
Chk 1417 [[55, 21, 188, 301], [292, 48, 450, 307]]
Chk 1419 [[84, 113, 170, 365], [209, 144, 284, 374], [302, 98, 399, 355], [340, 75, 494, 373]]
Chk 1421 [[53, 2, 155, 228], [124, 102, 237, 276], [188, 119, 374, 295]]
Chk 1422 [[134, 109, 193, 247], [191, 105, 270, 270], [269, 110, 351, 276], [425, 118, 500, 277]]
Chk 1423 [[47, 146, 170, 290], [347, 149, 458, 281]]
Chk 1424 [[50, 65, 146, 282], [322, 39, 439, 309]]
Chk 1425 [[0, 0, 151, 225], [211, 8, 460, 332]]
Chk 1426 [[16, 29, 288, 330], [29, 33, 309, 330]]
Chk 1427 [[37, 83, 209, 333], [268, 78, 462, 333]]
Chk 1428 [[33, 67, 390, 464], [38, 134, 246, 389]]
Chk 1429 [[224, 115, 314, 332], [70, 155, 255, 493], [113, 217, 201, 379]]
Chk 1430 [[0, 5, 266, 364], [160, 132, 399, 371]]
Chk 1431 [[72, 11, 251, 342], [420, 126, 499, 374], [314, 119, 419, 355]]
Chk 1432 [[250, 62, 499, 374], [0, 250, 17, 301], [223, 150, 384, 374], [195, 254, 217, 287], [212, 260, 235, 290]]
Chk 1433 [[14, 0, 218, 289], [279, 27, 425, 279]]
Chk 1434 [[164, 77, 328, 480], [15, 66, 188, 489], [299, 113, 332, 214]]
Chk 1435 [[339, 103, 499, 374], [170, 99, 374, 374]]
Chk 1436 [[289, 58, 378, 310], [368, 18, 485, 368], [87, 171, 256, 301]]
Chk 1438 [[7, 127, 238, 316], [224, 136, 381, 291]]
Chk 1439 [[41, 89, 308, 354], [186, 9, 493, 354], [0, 40, 81, 354]]
Chk 1440 [[0, 12, 251, 372], [186, 64, 328, 318], [432, 0, 500, 194], [211, 0, 255, 90], [171, 22, 212, 82], [331, 21, 374, 78]]
Chk 1441 [[316, 0, 467, 189], [195, 155, 403, 345], [13, 2, 69, 67]]
Chk 1442 [[18, 12, 249, 414], [201, 16, 390, 420]]
Chk 1443 [[17, 209, 173, 499], [142, 0, 333, 499]]
Chk 1444 [[240, 25, 369, 334], [355, 10, 447, 283]]
Chk 1445 [[59, 28, 233, 309], [302, 0, 391, 276]]
Chk 1446 [[181, 242, 317, 445], [74, 239, 154, 438], [125, 254, 170, 300], [17, 241, 52, 285]]
Chk 1447 [[355, 125, 426, 301], [270, 136, 324, 278], [91, 112, 178, 295], [202, 121, 291, 308]]
Chk 1449 [[224, 58, 292, 278], [323, 69, 380, 280], [395, 106, 441, 204], [169, 87, 230, 251], [457, 108, 499, 225], [437, 109, 472, 225], [291, 91, 311, 162]]
Chk 1451 [[404, 3, 494, 132], [318, 3, 437, 132], [105, 0, 253, 144]]
Chk 1452 [[37, 86, 108, 344], [155, 220, 196, 268], [254, 105, 272, 173]]
Chk 1453 [[0, 115, 34, 365], [12, 207, 57, 353], [32, 109, 133, 402], [110, 129, 184, 390], [154, 18, 263, 426], [224, 160, 289, 382]]
Chk 1454 [[272, 40, 437, 361], [27, 90, 191, 359]]
Chk 1455 [[138, 139, 237, 360], [20, 124, 179, 352], [258, 25, 407, 370], [149, 29, 291, 364]]
Chk 1456 [[296, 47, 499, 326], [126, 101, 199, 309], [34, 144, 102, 274], [282, 129, 315, 196], [214, 140, 243, 175]]
Chk 1458 [[157, 27, 253, 183], [119, 31, 320, 357]]
Chk 1459 [[269, 231, 319, 405], [162, 252, 197, 363], [109, 255, 134, 340], [85, 257, 109, 327], [59, 263, 85, 320], [47, 266, 60, 312]]
Chk 1460 [[107, 64, 225, 300], [184, 205, 275, 455]]
Chk 1462 [[2, 81, 150, 239], [333, 115, 490, 355]]
Chk 1463 [[172, 229, 257, 380], [54, 128, 179, 387]]
Chk 1464 [[85, 161, 243, 375], [45, 140, 146, 346], [224, 86, 392, 228], [239, 90, 389, 241], [372, 130, 500, 375]]
Chk 1466 [[263, 153, 335, 334], [49, 165, 133, 334], [116, 152, 212, 334]]
Chk 1467 [[311, 147, 359, 283], [361, 149, 403, 272], [126, 115, 152, 180], [54, 112, 76, 184], [76, 111, 105, 184]]
Chk 1469 [[35, 84, 303, 367], [291, 91, 433, 254], [413, 105, 499, 310]]
Chk 1470 [[25, 5, 246, 377], [148, 39, 376, 377]]
Chk 1471 [[191, 60, 406, 302], [145, 50, 262, 327], [55, 64, 227, 328]]
Chk 1472 [[58, 69, 133, 281], [300, 0, 394, 325]]
Chk 1473 [[277, 81, 488, 375], [189, 114, 315, 375], [10, 171, 83, 374], [69, 163, 122, 299]]
Chk 1474 [[206, 20, 263, 201], [48, 23, 199, 297], [278, 48, 300, 90], [232, 51, 463, 330]]
Chk 1475 [[0, 139, 85, 333], [74, 171, 172, 333], [169, 142, 284, 333], [134, 148, 216, 332], [277, 127, 395, 333], [413, 112, 500, 333]]
Chk 1476 [[223, 125, 320, 332], [373, 137, 429, 288], [91, 137, 170, 316]]
Chk 1477 [[43, 167, 182, 500], [144, 124, 265, 487], [226, 210, 286, 290]]
Chk 1479 [[0, 69, 64, 183], [101, 70, 146, 139], [118, 90, 185, 179], [167, 82, 300, 237], [17, 89, 173, 249], [285, 71, 500, 333]]
Chk 1480 [[281, 80, 374, 332], [192, 96, 279, 332], [0, 21, 175, 328], [147, 219, 177, 268]]
Chk 1481 [[35, 36, 197, 333], [154, 47, 334, 333], [273, 64, 404, 333]]
Chk 1482 [[285, 86, 383, 327], [118, 41, 312, 336], [305, 120, 486, 333], [0, 157, 168, 341]]
Chk 1484 [[149, 50, 274, 237], [300, 84, 401, 220]]
Chk 1485 [[183, 40, 436, 256], [128, 1, 239, 211]]
Chk 1486 [[202, 113, 370, 332], [307, 86, 438, 328]]
Chk 1487 [[221, 114, 441, 372], [144, 70, 237, 312]]
Chk 1488 [[0, 165, 63, 326], [48, 27, 243, 227], [250, 67, 341, 259], [325, 116, 417, 239], [291, 92, 487, 331]]
Chk 1489 [[159, 153, 278, 374], [362, 81, 454, 357], [123, 57, 209, 188], [302, 58, 410, 374], [226, 179, 337, 374], [233, 63, 302, 168], [475, 81, 497, 147]]
Chk 1491 [[278, 81, 478, 257], [6, 60, 140, 284], [116, 82, 295, 283]]
Chk 1492 [[102, 138, 226, 320], [187, 122, 299, 272]]
Chk 1493 [[94, 31, 224, 409], [312, 62, 416, 297]]
Chk 1494 [[173, 30, 391, 329], [0, 0, 229, 332]]
Chk 1495 [[0, 214, 222, 500], [129, 165, 332, 500], [230, 120, 313, 266]]
Chk 1496 [[17, 76, 310, 333], [184, 32, 500, 333]]
Chk 1498 [[388, 39, 486, 243], [345, 59, 385, 102], [308, 61, 349, 104], [106, 84, 148, 193], [12, 109, 52, 169], [0, 125, 34, 168]]
Chk 1499 [[29, 46, 83, 117], [127, 19, 280, 320], [237, 5, 370, 325]]
Chk 1500 [[375, 54, 435, 225], [423, 67, 461, 210]]
Chk 1501 [[48, 14, 263, 330], [219, 44, 375, 292]]

Chk 1505 [[90, 83, 306, 492], [26, 143, 215, 499]]
Chk 1506 [[138, 90, 235, 390], [26, 77, 179, 399]]
Chk 1507 [[21, 46, 227, 309], [223, 44, 499, 315]]
Chk 1508 [[243, 36, 388, 370], [113, 59, 245, 365]]
Chk 1509 [[70, 88, 283, 372], [266, 95, 491, 371]]
Chk 1510 [[294, 131, 342, 202], [435, 124, 494, 360], [354, 85, 454, 371], [185, 88, 352, 374], [0, 119, 158, 374]]
Chk 1511 [[9, 118, 201, 492], [175, 45, 333, 497]]
Chk 1513 [[147, 136, 212, 213], [67, 118, 133, 227], [453, 173, 471, 209]]
Chk 1514 [[29, 32, 200, 333], [160, 174, 342, 333], [311, 155, 454, 333], [404, 149, 500, 327]]
Chk 1515 [[71, 60, 207, 375], [223, 61, 394, 375], [228, 62, 293, 375], [1, 104, 27, 171], [25, 98, 61, 184]]
Chk 1516 [[25, 11, 174, 268], [161, 25, 335, 296], [299, 70, 437, 266]]
Chk 1517 [[33, 196, 149, 499], [111, 0, 296, 485]]
Chk 1518 [[280, 63, 499, 361], [126, 128, 280, 262]]
Chk 1520 [[183, 32, 318, 452], [36, 72, 181, 442]]
Chk 1521 [[19, 189, 42, 247], [182, 176, 220, 285], [216, 173, 262, 289], [301, 187, 337, 279]]
Chk 1522 [[216, 136, 285, 277], [26, 125, 113, 281]]
Chk 1523 [[0, 14, 117, 332], [276, 91, 383, 319], [371, 103, 440, 332], [441, 50, 499, 320], [185, 98, 272, 227]]
Chk 1524 [[15, 216, 142, 462], [177, 134, 283, 449], [363, 237, 478, 326]]
Chk 1525 [[258, 28, 481, 278], [0, 14, 243, 280]]
Chk 1526 [[31, 77, 166, 451], [245, 100, 357, 396], [175, 229, 274, 323]]
Chk 1527 [[14, 128, 56, 243], [50, 127, 90, 249], [318, 111, 370, 240]]
Chk 1529 [[275, 207, 341, 336], [248, 204, 310, 326]]
Chk 1530 [[7, 17, 213, 491], [155, 234, 279, 490]]
Chk 1531 [[80, 77, 158, 256], [2, 194, 116, 345], [296, 161, 431, 345], [315, 94, 375, 180], [218, 140, 260, 238]]
Chk 1533 [[144, 17, 229, 315], [217, 109, 337, 308]]
Chk 1534 [[34, 74, 197, 326], [336, 58, 459, 332]]
Chk 1535 [[284, 68, 438, 320], [134, 88, 275, 316]]
Chk 1537 [[206, 66, 354, 321], [50, 54, 181, 330], [319, 34, 499, 330]]
Chk 1538 [[101, 50, 211, 207], [246, 159, 307, 298], [269, 166, 333, 294]]
Chk 1539 [[291, 138, 351, 282], [171, 113, 267, 269], [72, 112, 122, 244], [36, 129, 85, 274]]
Chk 1540 [[301, 110, 403, 258], [193, 97, 276, 247]]
Chk 1541 [[9, 109, 90, 283], [99, 117, 183, 278], [332, 102, 430, 278], [203, 105, 290, 298]]
Chk 1542 [[0, 63, 148, 427], [0, 41, 284, 500], [128, 18, 333, 467], [182, 202, 333, 409]]
Chk 1543 [[178, 43, 330, 175], [9, 76, 159, 254], [321, 78, 456, 212], [2, 173, 66, 332], [373, 230, 396, 267]]
Chk 1544 [[133, 210, 284, 406], [123, 38, 276, 303]]
Chk 1545 [[85, 47, 260, 334], [206, 4, 322, 334]]
Chk 1546 [[62, 56, 163, 281], [174, 54, 306, 281], [345, 47, 463, 281]]
Chk 1547 [[142, 6, 334, 500], [0, 73, 108, 500]]
Chk 1548 [[343, 178, 460, 276], [0, 41, 103, 280], [124, 114, 209, 240]]
Chk 1550 [[0, 13, 192, 375], [379, 34, 500, 375], [110, 30, 343, 370]]
Chk 1552 [[128, 100, 382, 332], [49, 115, 251, 331]]
Chk 1553 [[106, 122, 210, 333], [214, 127, 278, 333]]
Chk 1554 [[437, 111, 493, 241], [2, 87, 87, 250], [199, 138, 267, 273], [62, 187, 111, 245]]
Chk 1557 [[296, 1, 499, 367], [30, 25, 231, 275], [14, 54, 72, 138]]
Chk 1560 [[11, 100, 300, 500], [252, 177, 343, 416], [22, 67, 294, 480]]
Chk 1561 [[165, 114, 310, 332], [309, 66, 474, 328], [54, 49, 236, 323]]
Chk 1563 [[3, 49, 120, 319], [244, 66, 345, 317], [418, 94, 500, 202]]
Chk 1564 [[289, 28, 458, 183], [16, 119, 274, 334], [332, 125, 499, 325], [0, 31, 270, 192], [158, 45, 316, 175], [0, 0, 121, 90]]
Chk 1565 [[4, 116, 192, 374], [149, 10, 432, 357]]
Chk 1566 [[0, 0, 161, 309], [277, 127, 460, 323], [171, 31, 417, 342]]
Chk 1568 [[78, 149, 169, 445], [255, 158, 362, 404]]
Chk 1569 [[258, 76, 437, 332], [113, 90, 256, 240], [2, 0, 94, 200]]
Chk 1570 [[84, 88, 181, 235], [185, 151, 294, 244], [354, 151, 466, 242]]
Chk 1571 [[144, 137, 375, 500], [0, 46, 245, 500]]
Chk 1572 [[61, 59, 191, 257], [176, 65, 340, 230], [270, 45, 500, 358]]
Chk 1573 [[38, 100, 158, 375], [137, 134, 185, 241], [351, 82, 486, 375]]
Chk 1574 [[121, 56, 500, 333], [27, 82, 249, 333]]
Chk 1575 [[297, 8, 486, 253], [141, 36, 312, 253]]
Chk 1576 [[0, 54, 222, 332], [228, 68, 372, 331]]
Chk 1577 [[89, 107, 166, 258], [202, 160, 300, 315], [288, 75, 365, 182]]
Chk 1578 [[0, 114, 238, 375], [9, 66, 151, 215], [193, 83, 312, 288], [337, 95, 500, 375]]
Chk 1579 [[308, 124, 376, 287], [180, 130, 223, 291]]
Chk 1580 [[46, 69, 276, 332], [341, 206, 439, 332]]
Chk 1582 [[271, 181, 324, 375], [216, 192, 269, 377]]
Chk 1583 [[40, 0, 283, 333], [203, 113, 378, 333]]
Chk 1584 [[116, 108, 177, 297], [18, 104, 109, 320], [386, 86, 499, 332]]
Chk 1585 [[149, 107, 330, 372], [376, 159, 497, 374], [53, 116, 188, 368]]
Chk 1586 [[0, 4, 179, 485], [285, 26, 478, 384], [161, 0, 318, 355], [98, 0, 190, 156]]
Chk 1587 [[197, 18, 335, 226], [6, 56, 76, 211], [426, 3, 499, 291], [167, 90, 199, 150]]
Chk 1588 [[142, 113, 327, 485], [38, 123, 292, 500]]
Chk 1589 [[44, 46, 375, 365], [235, 84, 369, 347]]
Chk 1590 [[0, 0, 270, 325], [177, 16, 450, 292]]
Chk 1591 [[19, 32, 239, 355], [298, 37, 485, 238]]
Chk 1592 [[134, 36, 190, 144], [63, 33, 138, 151], [223, 32, 297, 179], [178, 34, 235, 142]]
Chk 1593 [[274, 140, 364, 250], [54, 92, 124, 181], [155, 43, 208, 128]]
Chk 1595 [[33, 53, 283, 258], [322, 51, 499, 231]]
Chk 1596 [[63, 97, 179, 335], [151, 101, 283, 335], [267, 41, 415, 335]]
Chk 1598 [[342, 89, 500, 330], [58, 104, 176, 330], [119, 80, 264, 330]]
Chk 1599 [[384, 177, 427, 327], [149, 150, 187, 295], [188, 169, 231, 284], [454, 214, 495, 316], [306, 168, 358, 341]]
Chk 1601 [[241, 49, 466, 332], [454, 196, 499, 328], [164, 105, 309, 332]]
Chk 1603 [[47, 3, 181, 375], [145, 102, 257, 372], [237, 166, 320, 348], [313, 170, 473, 375]]
Chk 1604 [[125, 52, 413, 356], [98, 46, 243, 356]]
Chk 1605 [[241, 105, 376, 467], [69, 162, 194, 491]]
Chk 1606 [[67, 46, 143, 150], [171, 91, 385, 301], [29, 46, 264, 339]]
Chk 1607 [[8, 75, 147, 330], [181, 43, 300, 333], [263, 94, 337, 177], [350, 59, 483, 333]]
Chk 1608 [[232, 7, 351, 370], [100, 25, 212, 366]]
Chk 1609 [[0, 140, 28, 277], [13, 116, 62, 303], [66, 130, 115, 331], [180, 130, 229, 315], [222, 123, 274, 247], [394, 120, 462, 333]]
Chk 1610 [[217, 68, 330, 295], [33, 102, 153, 320]]
Chk 1611 [[175, 112, 298, 287], [254, 56, 421, 332], [188, 101, 308, 235]]
Chk 1612 [[132, 66, 249, 438], [153, 29, 245, 211]]
Chk 1613 [[111, 35, 264, 375], [320, 4, 470, 357]]
Chk 1614 [[293, 175, 433, 375], [252, 230, 317, 310], [215, 205, 270, 292], [147, 163, 223, 287], [192, 122, 253, 217], [13, 172, 119, 299]]
Chk 1615 [[67, 127, 143, 216], [140, 121, 221, 213], [207, 118, 286, 223], [273, 106, 363, 215], [98, 76, 170, 149]]
Chk 1616 [[26, 39, 217, 311], [304, 68, 410, 312]]
Chk 1618 [[141, 125, 190, 216], [220, 71, 272, 174], [308, 135, 360, 210], [391, 39, 500, 198]]
Chk 1619 [[67, 131, 183, 280], [290, 81, 444, 320]]
Chk 1620 [[0, 0, 240, 332], [168, 150, 354, 331]]
Chk 1621 [[8, 58, 122, 331], [182, 77, 282, 331], [315, 25, 420, 331]]
Chk 1622 [[284, 174, 454, 429], [257, 146, 330, 391], [126, 166, 187, 299], [102, 132, 188, 429]]
Chk 1623 [[17, 93, 187, 500], [244, 136, 333, 484], [153, 117, 316, 500]]
Chk 1624 [[123, 184, 232, 346], [145, 174, 350, 337]]
Chk 1625 [[86, 52, 246, 285], [154, 47, 319, 287]]
Chk 1626 [[78, 51, 169, 296], [156, 76, 242, 285]]
Chk 1627 [[128, 31, 224, 375], [201, 47, 291, 360], [300, 33, 408, 334]]
Chk 1628 [[209, 20, 449, 334], [15, 109, 235, 334]]
Chk 1629 [[52, 33, 232, 325], [279, 62, 420, 325]]
Chk 1630 [[147, 100, 287, 326], [257, 74, 397, 326]]
Chk 1631 [[233, 96, 345, 333], [162, 1, 412, 291]]
Chk 1632 [[298, 43, 499, 351], [11, 13, 203, 351], [132, 40, 341, 351]]
Chk 1633 [[76, 63, 332, 341], [112, 232, 327, 390], [45, 300, 332, 500]]
Chk 1634 [[138, 92, 198, 244], [263, 62, 364, 265], [267, 58, 368, 261]]
Chk 1635 [[105, 63, 250, 333], [328, 0, 448, 333]]
Chk 1636 [[206, 224, 320, 405], [90, 130, 227, 473]]
Chk 1637 [[8, 78, 322, 352], [198, 105, 415, 345]]
Chk 1638 [[288, 60, 468, 333], [61, 48, 299, 333], [75, 39, 167, 212]]
Chk 1640 [[120, 90, 319, 324], [355, 104, 499, 318]]
Chk 1641 [[31, 120, 187, 323], [204, 115, 244, 250], [158, 109, 198, 218]]
Chk 1642 [[25, 65, 133, 333], [113, 79, 270, 333], [313, 71, 452, 333]]
Chk 1643 [[44, 126, 176, 286], [333, 106, 491, 303]]
Chk 1644 [[312, 128, 375, 288], [367, 119, 420, 280], [56, 118, 133, 284]]
Chk 1645 [[369, 13, 428, 115], [265, 78, 355, 158]]
Chk 1646 [[206, 68, 308, 373], [0, 44, 54, 382], [43, 88, 166, 490]]
Chk 1647 [[288, 82, 487, 319], [9, 35, 158, 374]]
Chk 1648 [[11, 28, 125, 332], [334, 102, 455, 237]]
Chk 1649 [[81, 85, 156, 314], [145, 154, 257, 314]]
Chk 1651 [[0, 0, 283, 333], [207, 107, 465, 333]]
Chk 1652 [[133, 96, 285, 332], [222, 46, 406, 331]]

Chk 1653 [[177, 72, 241, 269], [26, 70, 108, 253], [297, 94, 330, 193], [105, 97, 128, 146], [351, 87, 385, 190], [380, 91, 405, 191]]
Chk 1655 [[292, 33, 438, 329], [124, 19, 304, 320], [239, 72, 333, 282]]
Chk 1656 [[58, 63, 276, 332], [204, 14, 491, 332], [259, 142, 333, 248]]
Chk 1657 [[0, 116, 181, 499], [314, 163, 479, 496]]
Chk 1658 [[129, 221, 198, 466], [191, 214, 270, 471]]
Chk 1659 [[244, 173, 354, 305], [342, 128, 383, 166], [194, 117, 251, 317]]
Chk 1661 [[267, 18, 398, 287], [67, 7, 188, 248]]
Chk 1663 [[32, 123, 111, 277], [346, 121, 417, 298]]
Chk 1665 [[253, 170, 330, 283], [2, 144, 44, 282], [184, 150, 230, 246], [39, 149, 82, 271]]
Chk 1667 [[235, 132, 299, 314], [325, 130, 418, 330]]
Chk 1668 [[284, 39, 384, 346], [128, 18, 231, 347], [213, 43, 303, 331]]
Chk 1669 [[2, 45, 233, 385], [198, 151, 297, 389], [257, 68, 481, 393]]
Chk 1670 [[143, 89, 220, 194], [224, 117, 340, 266], [237, 133, 357, 274], [240, 142, 368, 280]]
Chk 1672 [[223, 27, 299, 190], [295, 42, 405, 222], [411, 24, 500, 244]]
Chk 1673 [[26, 108, 118, 316], [126, 109, 206, 329]]
Chk 1674 [[32, 37, 260, 331], [201, 47, 355, 333]]
Chk 1675 [[0, 313, 57, 446], [76, 124, 159, 448], [162, 160, 265, 442], [139, 277, 185, 419]]
Chk 1676 [[92, 123, 132, 212], [136, 123, 161, 215]]
Chk 1677 [[48, 183, 130, 431], [176, 165, 263, 452], [199, 120, 228, 161]]
Chk 1678 [[195, 119, 295, 374], [286, 145, 446, 374]]
Chk 1679 [[1, 46, 157, 333], [138, 84, 285, 333], [383, 36, 500, 333]]
Chk 1681 [[187, 24, 472, 332], [0, 94, 150, 332]]
Chk 1682 [[145, 64, 274, 473], [252, 50, 391, 489], [72, 181, 88, 225], [64, 181, 77, 223], [110, 185, 139, 244]]
Chk 1685 [[360, 57, 495, 329], [0, 0, 186, 332], [137, 44, 369, 332], [352, 179, 393, 244]]
Chk 1686 [[147, 15, 262, 171], [98, 141, 266, 372], [254, 125, 368, 263]]
Chk 1688 [[0, 7, 62, 108], [48, 4, 119, 113], [131, 39, 226, 217], [253, 6, 446, 283]]
Chk 1690 [[278, 51, 363, 321], [157, 15, 275, 277]]
Chk 1691 [[117, 169, 171, 332], [281, 90, 350, 290]]
Chk 1692 [[0, 5, 197, 367], [300, 141, 488, 374]]
Chk 1694 [[51, 99, 264, 409], [162, 0, 375, 500]]
Chk 1695 [[163, 232, 234, 332], [215, 235, 271, 312], [266, 225, 325, 303], [148, 182, 214, 256], [234, 191, 282, 260]]
Chk 1696 [[122, 55, 333, 499], [29, 72, 194, 499]]
Chk 1698 [[216, 66, 333, 390], [0, 170, 158, 378]]
Chk 1700 [[356, 153, 408, 317], [419, 165, 473, 323], [235, 87, 309, 194], [303, 96, 355, 148]]
Chk 1701 [[0, 47, 124, 475], [122, 104, 309, 465], [244, 51, 302, 177], [118, 44, 155, 97]]
Chk 1702 [[67, 119, 231, 333], [172, 95, 267, 274], [258, 79, 449, 333]]
Chk 1703 [[71, 83, 294, 359], [210, 48, 353, 279]]
Chk 1704 [[234, 109, 350, 481], [75, 100, 213, 476]]
Chk 1705 [[96, 116, 165, 222], [105, 125, 270, 375], [250, 135, 386, 328]]
Chk 1707 [[0, 50, 196, 214], [137, 22, 246, 213]]
Chk 1708 [[208, 120, 292, 333], [213, 88, 300, 154], [282, 87, 346, 189], [423, 162, 467, 270], [450, 180, 492, 242], [436, 100, 486, 192], [464, 142, 500, 284]]
Chk 1709 [[11, 26, 192, 371], [270, 75, 497, 371], [197, 115, 247, 226], [269, 29, 292, 80], [277, 78, 399, 293]]
Chk 1710 [[237, 91, 284, 184], [156, 27, 227, 203], [0, 58, 16, 105], [190, 34, 239, 183]]
Chk 1711 [[0, 35, 95, 215], [333, 18, 486, 280], [253, 81, 341, 252], [109, 5, 283, 271], [57, 0, 155, 233], [261, 0, 367, 101]]
Chk 1712 [[37, 53, 389, 366], [169, 139, 473, 371]]
Chk 1713 [[11, 72, 128, 307], [136, 92, 214, 312], [258, 71, 359, 322], [364, 93, 473, 315]]
Chk 1714 [[216, 48, 350, 251], [345, 138, 469, 326], [120, 69, 197, 242], [0, 130, 83, 229], [428, 123, 496, 289], [17, 120, 192, 315]]
Chk 1715 [[1, 139, 174, 394], [83, 209, 281, 359], [151, 36, 335, 295]]
Chk 1716 [[88, 90, 327, 484], [21, 45, 170, 476]]
Chk 1717 [[108, 57, 189, 280], [19, 29, 142, 280], [329, 50, 446, 275]]
Chk 1718 [[140, 136, 356, 375], [295, 140, 470, 375]]
Chk 1719 [[76, 46, 227, 203], [65, 145, 310, 332], [301, 175, 396, 298]]
Chk 1720 [[147, 14, 364, 374], [316, 38, 469, 374]]
Chk 1721 [[249, 0, 375, 500], [32, 27, 252, 500]]
Chk 1722 [[9, 62, 95, 287], [367, 56, 486, 296], [153, 67, 256, 305]]
Chk 1723 [[133, 31, 242, 333], [227, 93, 306, 294], [274, 0, 430, 333], [367, 69, 447, 293]]
Chk 1725 [[160, 65, 349, 374], [276, 23, 490, 374], [46, 309, 148, 374], [8, 88, 51, 176]]
Chk 1726 [[114, 22, 235, 334], [182, 0, 351, 334], [336, 33, 498, 334]]
Chk 1727 [[101, 37, 220, 313], [356, 61, 484, 281], [80, 157, 99, 211], [0, 163, 15, 202], [250, 164, 268, 204], [39, 158, 53, 199], [187, 137, 215, 229]]
Chk 1728 [[259, 151, 340, 364], [89, 131, 180, 366]]
Chk 1729 [[4, 55, 172, 375], [189, 55, 305, 245], [351, 0, 489, 229], [299, 113, 352, 244]]
Chk 1730 [[386, 50, 500, 333], [0, 74, 149, 333]]
Chk 1732 [[114, 106, 297, 332], [277, 92, 499, 332], [8, 124, 169, 329], [89, 107, 184, 232]]
Chk 1733 [[0, 48, 55, 226], [285, 30, 352, 212], [212, 129, 270, 295]]
Chk 1734 [[110, 92, 272, 270], [242, 96, 361, 267]]
Chk 1735 [[263, 84, 435, 330], [66, 31, 262, 331]]
Chk 1736 [[429, 106, 499, 351], [4, 163, 150, 372], [0, 106, 81, 343]]
Chk 1737 [[40, 100, 223, 500], [151, 40, 333, 500]]
Chk 1738 [[266, 144, 320, 210], [207, 124, 267, 182], [95, 64, 190, 331]]
Chk 1739 [[101, 204, 153, 318], [76, 145, 194, 302], [181, 139, 256, 331]]
Chk 1740 [[157, 216, 332, 499], [0, 126, 160, 499]]
Chk 1742 [[306, 54, 427, 362], [221, 169, 293, 348]]
Chk 1745 [[0, 237, 63, 333], [38, 79, 179, 333], [210, 160, 334, 333], [302, 52, 481, 333]]
Chk 1746 [[49, 114, 167, 313], [308, 68, 436, 369], [466, 92, 499, 207]]
Chk 1747 [[177, 47, 232, 224], [129, 16, 185, 134], [337, 115, 479, 270], [296, 92, 396, 253], [299, 26, 362, 140]]
Chk 1750 [[327, 99, 500, 353], [99, 103, 344, 298]]
Chk 1751 [[175, 58, 287, 332], [336, 34, 444, 332], [433, 75, 499, 332], [102, 54, 192, 323]]
Chk 1752 [[178, 63, 341, 275], [156, 60, 465, 328]]
Chk 1753 [[64, 66, 225, 332], [213, 32, 402, 275], [371, 0, 486, 250]]
Chk 1754 [[1, 3, 133, 317], [415, 122, 491, 276], [139, 84, 278, 309]]
Chk 1755 [[90, 77, 330, 342], [211, 140, 408, 352], [145, 39, 167, 72]]
Chk 1757 [[222, 66, 263, 104], [309, 167, 367, 234], [233, 187, 290, 236], [295, 61, 323, 98]]
Chk 1758 [[0, 10, 196, 374], [309, 92, 483, 267], [212, 96, 290, 156], [415, 85, 499, 274]]
Chk 1759 [[82, 42, 216, 469], [196, 31, 340, 476]]
Chk 1760 [[0, 16, 227, 450], [143, 61, 384, 454]]
Chk 1761 [[99, 145, 246, 396], [0, 106, 138, 395]]
Chk 1762 [[100, 87, 253, 264], [265, 40, 428, 258]]
Chk 1763 [[103, 132, 160, 296], [159, 132, 218, 299], [247, 149, 288, 225], [312, 149, 355, 232]]
Chk 1764 [[291, 11, 396, 228], [63, 41, 198, 329], [406, 4, 447, 108]]
Chk 1765 [[33, 37, 216, 273], [249, 62, 439, 277]]
Chk 1766 [[83, 80, 223, 467], [227, 89, 364, 467]]
Chk 1767 [[0, 10, 251, 331], [270, 10, 499, 331]]
Chk 1768 [[224, 93, 409, 325], [28, 81, 308, 332]]
Chk 1769 [[230, 82, 407, 267], [84, 100, 223, 269]]
Chk 1770 [[19, 86, 168, 333], [146, 90, 327, 333], [279, 46, 481, 333]]
Chk 1771 [[98, 48, 279, 333], [192, 56, 369, 364]]
Chk 1774 [[130, 112, 221, 395], [267, 123, 340, 374], [67, 149, 124, 229], [182, 109, 253, 270]]
Chk 1775 [[62, 67, 288, 328], [254, 15, 494, 328]]
Chk 1778 [[325, 96, 430, 332], [183, 114, 340, 315]]
Chk 1779 [[45, 92, 192, 333], [129, 91, 232, 285], [270, 91, 341, 298], [326, 95, 414, 294]]
Chk 1780 [[406, 124, 484, 204], [315, 136, 398, 211], [15, 128, 89, 207], [121, 125, 205, 214], [236, 142, 300, 208]]
Chk 1781 [[70, 37, 210, 416], [7, 180, 85, 371], [280, 291, 305, 332]]
Chk 1782 [[68, 0, 274, 500], [181, 94, 387, 500]]
Chk 1787 [[52, 223, 164, 485], [194, 193, 314, 499]]
Chk 1788 [[214, 59, 346, 333], [271, 47, 500, 333]]
Chk 1789 [[25, 113, 174, 344], [291, 99, 410, 302]]
Chk 1790 [[109, 130, 238, 374], [196, 62, 436, 374]]
Chk 1791 [[37, 107, 85, 267], [62, 120, 134, 296], [358, 119, 438, 290]]
Chk 1793 [[0, 43, 163, 194], [175, 42, 273, 209], [255, 35, 345, 214], [277, 0, 500, 301]]
Chk 1794 [[70, 131, 175, 445], [200, 167, 277, 448], [127, 161, 234, 446]]
Chk 1795 [[276, 56, 358, 298], [384, 158, 451, 290]]
Chk 1796 [[77, 136, 210, 361], [203, 96, 313, 389], [299, 142, 380, 367]]
Chk 1797 [[134, 42, 310, 333], [343, 19, 500, 309]]
Chk 1798 [[205, 44, 425, 330], [3, 27, 306, 326]]
Chk 1800 [[61, 86, 273, 333], [223, 268, 295, 333], [243, 44, 383, 287], [249, 55, 395, 316], [350, 181, 408, 333]]
Chk 1801 [[225, 164, 265, 256], [275, 169, 309, 255]]
Chk 1802 [[139, 29, 274, 331], [293, 60, 432, 331], [0, 61, 133, 331]]
Chk 1803 [[0, 0, 264, 332], [238, 124, 500, 332]]
Chk 1804 [[152, 187, 287, 478], [9, 58, 185, 367]]
Chk 1805 [[196, 0, 421, 375], [101, 105, 256, 375]]
Chk 1806 [[222, 79, 324, 282], [270, 56, 417, 323]]
Chk 1807 [[21, 42, 179, 280], [283, 25, 399, 280]]
Chk 1808 [[170, 148, 200, 258], [181, 160, 235, 290], [145, 208, 183, 291]]
Chk 1809 [[205, 40, 288, 278], [68, 63, 202, 277], [401, 57, 476, 261]]
Chk 1810 [[100, 126, 223, 357], [223, 122, 364, 357], [418, 52, 483, 192]]
Chk 1811 [[97, 123, 220, 236], [246, 151, 300, 228]]
Chk 1813 [[312, 52, 440, 334], [194, 27, 350, 366]]

Chk 1814 [[249, 143, 325, 247], [332, 157, 432, 355], [117, 138, 162, 220], [63, 132, 79, 170], [50, 127, 71, 170]]
Chk 1815 [[177, 88, 366, 350], [338, 91, 499, 371], [51, 102, 193, 314]]
Chk 1816 [[0, 28, 120, 364], [106, 111, 254, 263], [248, 94, 333, 379]]
Chk 1817 [[298, 81, 445, 261], [105, 106, 281, 271], [40, 120, 139, 263]]
Chk 1818 [[0, 61, 199, 375], [361, 39, 500, 375], [199, 128, 285, 323]]
Chk 1819 [[248, 73, 424, 374], [23, 67, 188, 369]]
Chk 1820 [[155, 273, 275, 500], [38, 84, 204, 500], [212, 115, 270, 259], [262, 159, 316, 263], [187, 142, 229, 267], [293, 125, 332, 210], [259, 125, 300, 176]]
Chk 1821 [[211, 21, 383, 171], [342, 14, 451, 171]]
Chk 1822 [[85, 77, 333, 451], [0, 0, 255, 477]]
Chk 1823 [[17, 337, 156, 432], [56, 347, 238, 485]]
Chk 1824 [[327, 30, 452, 320], [241, 26, 373, 332]]
Chk 1825 [[151, 13, 382, 375], [174, 22, 400, 375]]
Chk 1826 [[51, 73, 214, 317], [189, 31, 334, 331], [278, 40, 463, 327]]
Chk 1828 [[0, 22, 236, 333], [220, 93, 439, 333]]
Chk 1829 [[30, 71, 279, 375], [247, 130, 500, 281]]
Chk 1830 [[199, 96, 240, 202], [283, 87, 323, 194]]
Chk 1831 [[0, 58, 36, 290], [36, 109, 182, 301], [191, 138, 334, 311], [340, 97, 500, 375]]
Chk 1832 [[280, 27, 500, 333], [0, 18, 305, 333]]
Chk 1833 [[136, 145, 188, 304], [71, 173, 120, 332]]
Chk 1834 [[305, 36, 499, 332], [0, 16, 216, 327], [172, 0, 319, 315]]
Chk 1835 [[13, 20, 183, 375], [173, 66, 323, 326], [260, 38, 347, 141], [192, 58, 487, 375]]
Chk 1836 [[169, 145, 303, 311], [351, 199, 500, 326]]
Chk 1837 [[370, 136, 403, 274], [331, 156, 379, 265], [323, 204, 358, 272]]
Chk 1838 [[86, 91, 250, 322], [254, 21, 448, 325]]
Chk 1839 [[124, 59, 427, 328], [263, 6, 491, 332]]
Chk 1841 [[237, 80, 391, 325], [68, 79, 235, 349]]
Chk 1842 [[13, 119, 119, 301], [135, 120, 215, 270], [333, 119, 462, 268], [402, 132, 500, 286]]
Chk 1843 [[157, 100, 271, 258], [220, 136, 296, 252]]
Chk 1845 [[11, 74, 164, 500], [165, 263, 339, 500]]
Chk 1847 [[0, 20, 342, 332], [325, 33, 499, 332]]
Chk 1848 [[145, 48, 348, 499], [9, 88, 166, 499], [321, 387, 341, 423]]
Chk 1850 [[91, 51, 307, 333], [187, 54, 353, 289]]
Chk 1851 [[186, 78, 277, 374], [330, 149, 378, 285]]
Chk 1852 [[41, 116, 120, 327], [193, 150, 254, 254], [239, 155, 315, 257], [16, 97, 86, 313]]
Chk 1853 [[286, 112, 361, 181], [154, 103, 306, 395], [108, 93, 223, 353], [44, 208, 112, 395], [0, 100, 72, 388], [53, 101, 98, 193], [82, 93, 135, 185]]
Chk 1854 [[70, 0, 336, 365], [239, 54, 482, 362]]
Chk 1856 [[171, 55, 391, 405], [49, 34, 236, 437]]
Chk 1857 [[313, 145, 402, 334], [382, 145, 489, 334], [238, 160, 259, 204], [211, 165, 227, 211]]
Chk 1858 [[1, 0, 116, 342], [97, 0, 211, 456], [210, 0, 354, 445]]
Chk 1860 [[161, 142, 228, 202], [155, 206, 242, 382]]
Chk 1861 [[171, 130, 300, 332], [6, 137, 123, 331], [257, 137, 460, 329]]
Chk 1862 [[173, 139, 224, 281], [457, 113, 496, 293], [400, 131, 451, 287], [57, 141, 106, 293], [236, 130, 300, 269], [138, 131, 163, 209], [98, 140, 119, 203]]
Chk 1863 [[0, 124, 118, 500], [151, 141, 258, 496], [206, 107, 318, 456], [102, 189, 175, 492]]
Chk 1865 [[54, 28, 363, 318], [261, 0, 500, 333], [22, 55, 116, 270], [9, 30, 113, 321]]
Chk 1866 [[215, 201, 278, 300], [244, 206, 322, 313]]
Chk 1867 [[178, 42, 273, 290], [93, 57, 193, 278], [325, 41, 397, 279], [430, 65, 472, 161]]
Chk 1868 [[264, 43, 331, 253], [407, 43, 492, 252], [116, 17, 243, 320], [318, 47, 406, 273]]
Chk 1869 [[413, 106, 499, 332], [32, 32, 311, 332], [0, 55, 108, 332], [300, 45, 476, 332], [235, 62, 364, 326]]
Chk 1870 [[127, 56, 247, 172], [285, 64, 408, 176]]
Chk 1871 [[165, 131, 346, 414], [12, 28, 315, 469]]
Chk 1872 [[0, 36, 194, 333], [185, 38, 374, 333], [341, 73, 500, 333]]
Chk 1873 [[134, 149, 194, 226], [246, 148, 308, 218]]
Chk 1874 [[38, 50, 124, 307], [147, 71, 270, 484], [153, 154, 229, 220], [32, 36, 187, 465]]
Chk 1875 [[45, 0, 164, 259], [140, 36, 279, 314], [254, 57, 391, 333], [299, 0, 342, 61], [260, 13, 307, 69]]
Chk 1876 [[36, 33, 163, 332], [314, 54, 407, 315], [259, 39, 361, 315], [1, 29, 70, 332]]
Chk 1877 [[79, 133, 332, 499], [4, 41, 226, 488]]
Chk 1878 [[28, 80, 113, 242], [43, 106, 83, 148], [87, 72, 185, 240]]
Chk 1879 [[37, 10, 249, 350], [251, 15, 454, 350]]
Chk 1880 [[209, 95, 276, 337], [97, 97, 176, 320]]
Chk 1881 [[367, 187, 499, 328], [175, 16, 344, 288]]
Chk 1882 [[134, 70, 292, 422], [334, 181, 412, 396], [68, 20, 105, 103]]
Chk 1883 [[42, 95, 253, 278], [205, 80, 464, 239]]
Chk 1884 [[235, 44, 361, 159], [132, 100, 227, 187], [190, 115, 223, 171]]
Chk 1886 [[23, 141, 156, 307], [282, 118, 426, 332], [247, 54, 500, 374]]
Chk 1887 [[307, 150, 417, 331], [205, 51, 338, 331], [102, 109, 247, 331]]
Chk 1888 [[196, 191, 275, 432], [243, 213, 311, 420]]
Chk 1889 [[134, 56, 223, 205], [180, 21, 240, 109], [232, 51, 313, 231], [318, 15, 396, 156], [435, 37, 500, 375]]
Chk 1892 [[120, 39, 265, 331], [244, 51, 353, 331], [338, 77, 375, 258]]
Chk 1893 [[196, 135, 310, 332], [3, 28, 204, 331], [315, 146, 427, 309]]
Chk 1894 [[194, 75, 225, 178], [117, 82, 157, 160], [81, 75, 129, 150], [157, 79, 183, 170]]
Chk 1895 [[0, 1, 206, 333], [207, 16, 416, 333], [314, 6, 500, 333]]
Chk 1896 [[0, 147, 50, 286], [133, 144, 179, 253], [191, 149, 261, 240], [252, 160, 305, 245], [311, 141, 380, 248]]
Chk 1897 [[116, 61, 189, 149], [282, 76, 329, 143], [326, 86, 387, 153], [383, 81, 437, 147]]
Chk 1898 [[332, 145, 416, 332], [432, 151, 499, 331], [156, 71, 291, 236]]
Chk 1900 [[300, 29, 433, 381], [151, 157, 353, 426], [27, 28, 177, 377]]
Chk 1902 [[59, 36, 265, 312], [169, 34, 388, 288]]
Chk 1903 [[260, 135, 339, 332], [70, 125, 194, 332], [0, 128, 75, 332]]
Chk 1904 [[0, 55, 224, 332], [255, 34, 493, 332]]
Chk 1905 [[134, 38, 193, 188], [251, 13, 331, 234], [255, 24, 285, 129]]
Chk 1907 [[33, 45, 202, 462], [126, 47, 354, 469]]
Chk 1908 [[110, 93, 286, 269], [16, 165, 148, 282]]
Chk 1910 [[225, 109, 297, 179], [326, 104, 412, 185]]
Chk 1911 [[394, 96, 455, 239], [105, 56, 169, 220]]
Chk 1912 [[0, 22, 204, 362], [313, 142, 399, 255], [395, 128, 500, 281]]
Chk 1913 [[0, 18, 180, 388], [146, 16, 337, 388], [342, 21, 500, 388]]
Chk 1914 [[107, 64, 243, 333], [200, 58, 327, 333], [330, 51, 466, 333]]
Chk 1915 [[237, 156, 293, 419], [111, 191, 194, 411]]
Chk 1916 [[102, 48, 299, 333], [342, 123, 491, 333]]
Chk 1917 [[159, 62, 298, 299], [97, 127, 252, 297]]
Chk 1918 [[303, 88, 398, 277], [141, 65, 208, 183]]
Chk 1920 [[59, 129, 197, 303], [153, 120, 306, 270]]
Chk 1921 [[148, 92, 210, 246], [1, 92, 42, 270], [180, 97, 273, 264]]
Chk 1922 [[206, 141, 329, 297], [302, 142, 388, 312], [267, 95, 311, 183], [0, 289, 41, 331]]
Chk 1925 [[135, 78, 267, 333], [206, 101, 373, 333]]
Chk 1926 [[7, 77, 101, 486], [239, 129, 324, 287]]
Chk 1927 [[213, 147, 369, 363], [98, 136, 225, 358]]
Chk 1928 [[0, 15, 102, 333], [121, 126, 232, 320], [352, 37, 451, 311]]
Chk 1929 [[131, 113, 222, 326], [48, 105, 126, 318]]
Chk 1930 [[97, 102, 268, 318], [282, 119, 442, 331], [115, 0, 172, 112], [125, 1, 174, 43], [85, 0, 135, 85], [10, 0, 61, 106]]
Chk 1931 [[32, 61, 282, 333], [224, 40, 500, 333]]
Chk 1932 [[110, 275, 164, 424], [156, 289, 198, 390], [186, 275, 236, 380], [235, 274, 277, 375]]
Chk 1933 [[59, 72, 245, 373], [196, 49, 429, 313], [371, 76, 400, 123], [452, 70, 476, 164], [307, 67, 334, 119]]
Chk 1934 [[194, 0, 385, 374], [27, 132, 214, 374]]
Chk 1935 [[76, 27, 284, 445], [193, 8, 444, 434]]
Chk 1937 [[121, 105, 318, 373], [277, 95, 463, 366]]
Chk 1938 [[250, 90, 350, 309], [287, 69, 409, 311]]
Chk 1939 [[25, 163, 97, 232], [227, 157, 304, 267], [335, 110, 368, 139], [373, 109, 397, 137]]
Chk 1940 [[18, 66, 247, 332], [196, 41, 451, 330]]
Chk 1941 [[270, 150, 341, 244], [67, 79, 115, 166]]
Chk 1942 [[41, 65, 108, 255], [139, 29, 216, 337], [332, 75, 441, 248]]
Chk 1943 [[50, 111, 239, 333], [165, 115, 362, 333], [377, 123, 500, 333]]
Chk 1946 [[83, 106, 452, 326], [263, 53, 306, 151], [276, 101, 458, 290], [33, 5, 258, 324]]
Chk 1947 [[122, 61, 257, 332], [50, 30, 152, 332]]
Chk 1949 [[144, 120, 233, 424], [47, 95, 116, 271], [7, 128, 61, 227]]
Chk 1952 [[12, 90, 211, 333], [315, 97, 455, 333], [233, 87, 357, 333]]
Chk 1953 [[273, 195, 416, 372], [113, 93, 360, 370]]
Chk 1954 [[0, 135, 161, 359], [54, 325, 235, 424], [175, 58, 332, 411]]
Chk 1955 [[0, 51, 84, 266], [110, 30, 264, 352], [400, 17, 500, 375], [340, 110, 431, 248]]
Chk 1956 [[260, 39, 428, 371], [35, 52, 227, 374]]
Chk 1957 [[57, 254, 162, 500], [95, 235, 223, 500], [278, 255, 344, 405], [210, 266, 264, 402], [183, 248, 229, 335], [0, 338, 71, 424]]

Chk 1958 [[29, 135, 111, 267], [111, 131, 210, 314], [238, 85, 313, 273], [375, 50, 500, 375]]
Chk 1959 [[260, 95, 336, 297], [119, 93, 237, 469], [29, 91, 135, 490], [315, 87, 374, 297], [219, 122, 265, 304], [10, 121, 45, 179]]
Chk 1961 [[43, 108, 236, 324], [196, 108, 302, 247], [229, 108, 393, 333], [373, 86, 460, 196], [249, 76, 290, 115]]
Chk 1962 [[352, 63, 412, 170], [24, 29, 128, 304], [316, 64, 349, 176]]
Chk 1963 [[0, 130, 129, 480], [99, 194, 300, 407], [22, 95, 126, 303], [114, 6, 228, 216]]
Chk 1964 [[0, 0, 155, 375], [232, 55, 406, 375]]
Chk 1965 [[130, 211, 375, 481], [0, 45, 337, 500]]
Chk 1966 [[133, 23, 403, 375], [84, 162, 233, 375]]
Chk 1967 [[99, 286, 182, 492], [192, 280, 270, 496]]
Chk 1969 [[33, 27, 104, 238], [92, 26, 169, 252], [210, 147, 338, 313]]
Chk 1970 [[0, 35, 193, 199], [180, 0, 290, 115], [268, 12, 438, 164]]
Chk 1971 [[18, 78, 311, 497], [0, 5, 203, 311]]
Chk 1972 [[100, 118, 199, 341], [226, 130, 317, 339]]
Chk 1973 [[26, 0, 288, 318], [283, 35, 500, 333]]
Chk 1974 [[3, 41, 151, 499], [200, 176, 374, 499], [172, 184, 267, 487]]
Chk 1975 [[140, 99, 233, 329], [0, 80, 101, 328], [395, 109, 468, 236], [279, 142, 326, 240], [300, 154, 423, 265]]
Chk 1976 [[357, 74, 403, 204], [200, 131, 298, 306], [230, 118, 381, 310], [110, 79, 137, 134], [63, 122, 203, 310], [305, 90, 327, 128]]
Chk 1978 [[159, 154, 221, 209], [50, 167, 99, 210], [227, 160, 268, 209]]
Chk 1979 [[235, 59, 480, 333], [4, 40, 235, 333]]
Chk 1980 [[0, 31, 184, 303], [252, 17, 439, 273], [400, 126, 500, 375]]
Chk 1982 [[0, 64, 172, 333], [146, 54, 361, 333], [459, 257, 500, 333]]
Chk 1983 [[84, 113, 186, 481], [192, 18, 347, 482], [32, 126, 54, 194], [6, 114, 31, 184]]
Chk 1984 [[185, 146, 323, 416], [94, 114, 220, 247], [19, 101, 127, 242], [0, 102, 48, 258]]
Chk 1985 [[140, 61, 279, 365], [374, 99, 479, 375], [275, 56, 334, 141], [86, 57, 161, 314]]
Chk 1986 [[5, 154, 63, 239], [160, 22, 309, 416], [81, 131, 179, 319]]
Chk 1989 [[295, 5, 413, 288], [49, 4, 179, 313]]
Chk 1990 [[0, 43, 256, 328], [218, 30, 500, 333]]
Chk 1991 [[267, 120, 366, 293], [84, 14, 187, 319]]
Chk 1992 [[238, 124, 478, 344], [63, 120, 339, 326]]
Chk 1993 [[75, 166, 136, 320], [201, 150, 296, 328], [367, 104, 439, 324]]
Chk 1994 [[23, 14, 208, 356], [197, 50, 314, 356], [364, 160, 390, 216], [391, 110, 436, 216]]
Chk 1995 [[314, 116, 500, 333], [36, 89, 191, 306], [285, 72, 355, 167], [340, 75, 409, 178], [124, 59, 199, 158]]
Chk 1996 [[155, 50, 275, 310], [357, 115, 420, 243], [83, 212, 152, 311], [50, 207, 101, 259]]
Chk 1997 [[74, 250, 135, 343], [110, 235, 161, 323]]
Chk 1998 [[28, 72, 135, 401], [216, 29, 417, 400]]
Chk 1999 [[0, 48, 202, 309], [157, 72, 305, 308], [273, 8, 441, 302], [421, 0, 500, 219], [356, 0, 458, 149]]
Chk 2000 [[172, 58, 219, 207], [200, 92, 292, 210]]
Chk 2003 [[23, 144, 121, 312], [123, 141, 183, 284]]
Chk 2005 [[318, 173, 481, 370], [4, 186, 234, 374]]
Chk 2006 [[138, 32, 242, 164], [167, 115, 222, 247], [113, 135, 179, 247]]
Chk 2007 [[373, 29, 494, 288], [43, 121, 175, 332], [197, 73, 296, 296]]
Chk 2008 [[5, 61, 171, 332], [275, 55, 487, 332]]
Chk 2010 [[176, 126, 317, 484], [51, 148, 209, 469], [15, 160, 92, 479]]
Chk 2012 [[285, 83, 432, 374], [278, 64, 365, 250], [189, 84, 271, 231]]
Chk 2013 [[67, 175, 177, 328], [200, 209, 277, 297], [172, 197, 467, 487]]
Chk 2014 [[326, 4, 499, 312], [190, 73, 416, 252], [106, 129, 221, 229]]
Chk 2015 [[95, 66, 357, 477], [21, 147, 172, 415], [326, 135, 439, 248]]
Chk 2016 [[41, 39, 245, 434], [208, 81, 330, 434], [316, 111, 456, 432]]
Chk 2017 [[238, 202, 482, 428], [82, 202, 226, 426]]
Chk 2018 [[237, 96, 307, 267], [303, 100, 384, 280]]
Chk 2020 [[394, 55, 491, 351], [38, 63, 111, 301], [116, 60, 206, 300]]
Chk 2021 [[336, 109, 403, 244], [263, 103, 332, 247], [8, 101, 78, 288], [172, 72, 233, 291], [452, 45, 472, 95], [229, 71, 266, 193], [395, 24, 425, 112]]
Chk 2022 [[388, 86, 465, 271], [194, 89, 323, 279]]
Chk 2024 [[80, 219, 297, 500], [210, 213, 357, 500]]
Chk 2026 [[111, 128, 179, 268], [151, 119, 198, 219], [304, 117, 381, 344]]
Chk 2027 [[266, 179, 389, 373], [194, 171, 288, 368]]
Chk 2029 [[43, 117, 153, 349], [199, 91, 308, 349], [386, 73, 500, 349], [282, 118, 349, 349]]
Chk 2031 [[401, 60, 489, 237], [60, 105, 180, 326], [230, 104, 379, 337], [104, 25, 283, 379]]
Chk 2032 [[139, 107, 238, 333], [264, 72, 460, 333]]
Chk 2033 [[62, 133, 241, 357], [97, 143, 346, 441]]
Chk 2035 [[278, 17, 500, 379], [228, 223, 392, 379], [154, 111, 312, 379], [32, 125, 205, 379]]
Chk 2036 [[366, 75, 446, 290], [93, 37, 304, 330]]
Chk 2039 [[307, 105, 435, 256], [80, 115, 247, 266]]
Chk 2040 [[52, 131, 203, 286], [235, 126, 389, 329]]
Chk 2041 [[50, 151, 190, 296], [129, 148, 256, 294], [262, 135, 382, 286], [374, 141, 454, 280]]
Chk 2042 [[8, 117, 109, 217], [125, 123, 199, 219], [221, 115, 290, 212], [303, 132, 377, 323], [386, 107, 471, 215]]
Chk 2043 [[239, 125, 310, 229], [104, 91, 194, 337], [182, 118, 235, 247]]
Chk 2044 [[41, 152, 203, 333], [196, 170, 337, 332], [74, 53, 183, 209], [220, 49, 300, 193], [283, 0, 389, 298], [365, 29, 469, 333]]
Chk 2045 [[291, 123, 329, 168], [211, 119, 254, 170]]
Chk 2046 [[206, 40, 371, 333], [190, 52, 365, 333]]
Chk 2047 [[0, 12, 249, 331], [335, 44, 500, 331]]
Chk 2048 [[190, 10, 240, 134], [105, 14, 169, 152], [89, 10, 129, 136], [0, 10, 44, 199]]
Chk 2049 [[32, 21, 166, 319], [240, 73, 421, 333], [406, 20, 500, 318]]
Chk 2050 [[156, 74, 321, 332], [50, 115, 178, 332], [19, 245, 64, 332], [0, 230, 37, 287]]
Chk 2051 [[112, 102, 253, 297], [234, 93, 404, 318]]
Chk 2052 [[0, 48, 126, 315], [186, 73, 267, 305], [314, 74, 405, 311], [397, 149, 439, 225], [370, 156, 402, 224]]
Chk 2053 [[100, 23, 193, 226], [177, 106, 227, 213], [288, 98, 341, 203], [415, 106, 480, 209], [423, 104, 490, 212]]
Chk 2054 [[308, 48, 426, 332], [252, 87, 297, 204]]
Chk 2055 [[296, 111, 431, 357], [201, 132, 283, 370], [32, 167, 114, 362]]
Chk 2056 [[182, 72, 297, 278], [38, 69, 139, 268], [339, 100, 458, 313]]
Chk 2057 [[13, 80, 253, 375], [211, 74, 318, 213], [299, 96, 483, 375], [469, 0, 500, 148], [351, 0, 441, 134]]
Chk 2058 [[262, 49, 320, 131], [95, 52, 227, 323], [176, 98, 311, 322]]
Chk 2059 [[49, 38, 147, 264], [272, 32, 393, 264], [378, 130, 411, 197]]
Chk 2060 [[186, 85, 321, 333], [0, 71, 259, 333]]
Chk 2061 [[124, 64, 201, 284], [170, 108, 341, 287]]
Chk 2062 [[6, 52, 191, 500], [306, 130, 466, 500]]
Chk 2063 [[300, 49, 412, 333], [186, 38, 351, 333]]
Chk 2064 [[0, 181, 58, 287], [38, 169, 123, 291], [100, 173, 195, 301], [158, 151, 297, 293], [297, 119, 465, 302]]
Chk 2066 [[289, 135, 359, 324], [226, 115, 295, 312], [359, 139, 420, 331]]
Chk 2067 [[66, 29, 329, 332], [284, 76, 475, 281], [26, 98, 136, 221]]
Chk 2069 [[90, 0, 296, 315], [294, 0, 500, 375]]
Chk 2071 [[21, 0, 125, 309], [191, 111, 316, 302]]
Chk 2072 [[70, 130, 133, 309], [210, 162, 283, 307], [310, 169, 386, 314], [288, 156, 335, 237]]
Chk 2074 [[77, 0, 322, 375], [209, 108, 341, 303]]
Chk 2075 [[277, 77, 428, 258], [87, 79, 212, 375]]
Chk 2076 [[28, 185, 133, 372], [127, 267, 189, 368]]
Chk 2078 [[306, 0, 425, 271], [87, 0, 256, 374], [53, 43, 105, 185], [386, 0, 500, 360]]
Chk 2079 [[127, 33, 233, 354], [147, 49, 243, 351], [258, 63, 344, 289]]
Chk 2080 [[163, 299, 245, 374], [52, 322, 109, 374]]
Chk 2081 [[301, 71, 441, 351], [164, 137, 232, 366], [68, 80, 143, 345], [139, 63, 160, 93], [171, 66, 187, 98], [195, 58, 218, 147]]
Chk 2082 [[9, 19, 274, 323], [210, 24, 399, 323]]
Chk 2083 [[256, 181, 314, 299], [430, 192, 477, 279], [52, 184, 121, 329], [139, 176, 186, 237], [170, 167, 213, 239], [105, 210, 147, 263], [14, 212, 55, 266], [217, 214, 257, 261]]
Chk 2085 [[153, 118, 440, 364], [202, 33, 271, 111]]
Chk 2086 [[210, 0, 375, 500], [9, 192, 210, 475], [172, 194, 242, 368]]
Chk 2087 [[175, 50, 294, 333], [269, 4, 439, 333]]
Chk 2088 [[0, 22, 194, 374], [254, 40, 386, 260], [349, 68, 499, 287]]
Chk 2089 [[1, 90, 153, 316], [217, 119, 343, 261], [383, 87, 499, 321]]
Chk 2090 [[8, 49, 274, 376], [289, 121, 470, 376]]
Chk 2091 [[302, 49, 363, 235], [92, 60, 213, 315]]
Chk 2092 [[232, 92, 351, 383], [0, 8, 139, 485], [148, 55, 174, 92], [4, 43, 29, 113]]
Chk 2094 [[22, 154, 84, 354], [76, 137, 131, 256]]
Chk 2095 [[17, 39, 266, 306], [302, 65, 416, 280], [28, 50, 277, 290]]
Chk 2097 [[23, 125, 236, 500], [0, 164, 115, 476], [199, 177, 318, 458]]
Chk 2098 [[134, 109, 249, 464], [335, 193, 435, 348], [63, 161, 119, 336]]
Chk 2099 [[355, 89, 429, 301], [205, 64, 293, 333], [285, 145, 341, 247], [95, 89, 150, 314], [141, 131, 165, 271]]
Chk 2100 [[179, 147, 263, 362], [198, 139, 359, 376]]
Chk 2101 [[55, 76, 184, 332], [190, 53, 327, 332], [344, 227, 403, 321]]
Chk 2102 [[114, 95, 273, 314], [280, 123, 396, 309]]
Chk 2103 [[69, 107, 119, 232], [330, 110, 378, 264], [151, 120, 193, 232]]
Chk 2104 [[222, 73, 323, 293], [352, 64, 499, 332]]
Chk 2105 [[12, 2, 185, 218], [210, 21, 333, 188], [162, 31, 446, 334], [428, 51, 500, 215]]
Chk 2106 [[206, 134, 456, 499], [39, 137, 189, 488]]
Chk 2107 [[40, 185, 207, 500], [203, 206, 338, 500], [311, 262, 338, 351]]

Chk 2108 [[28, 117, 152, 474], [132, 126, 242, 500], [232, 295, 281, 357]]
Chk 2109 [[215, 119, 329, 240], [57, 129, 165, 238], [393, 133, 486, 246]]
Chk 2110 [[345, 92, 447, 370], [101, 128, 203, 309], [197, 136, 328, 367]]
Chk 2111 [[198, 155, 407, 377], [114, 82, 331, 377]]
Chk 2112 [[0, 43, 96, 336], [50, 54, 216, 336], [380, 52, 500, 336]]
Chk 2113 [[40, 56, 248, 500], [176, 83, 333, 500]]
Chk 2114 [[142, 91, 237, 332], [270, 63, 421, 332]]
Chk 2115 [[208, 27, 464, 335], [27, 65, 233, 335]]
Chk 2116 [[140, 171, 266, 285], [237, 199, 310, 340]]
Chk 2117 [[0, 11, 193, 351], [246, 19, 483, 349]]
Chk 2118 [[325, 97, 421, 222], [188, 80, 233, 179]]
Chk 2119 [[134, 37, 241, 490], [25, 40, 155, 477]]
Chk 2120 [[3, 0, 130, 135], [0, 0, 227, 363], [123, 82, 376, 380], [400, 71, 500, 270]]
Chk 2121 [[109, 36, 153, 172], [6, 52, 48, 165], [216, 88, 422, 258], [306, 22, 402, 252], [53, 43, 105, 173]]
Chk 2122 [[0, 19, 154, 296], [235, 47, 497, 297], [191, 92, 247, 159], [246, 105, 281, 158], [256, 97, 327, 212]]
Chk 2124 [[12, 94, 146, 366], [164, 66, 303, 309], [238, 80, 484, 361]]
Chk 2125 [[235, 167, 459, 333], [71, 71, 199, 333], [183, 96, 299, 333]]
Chk 2126 [[276, 154, 343, 207], [65, 157, 150, 227]]
Chk 2127 [[104, 14, 291, 289], [73, 68, 499, 326]]
Chk 2128 [[180, 197, 299, 374], [0, 159, 75, 374], [85, 183, 126, 275], [67, 265, 150, 365]]
Chk 2129 [[210, 104, 243, 184], [314, 82, 371, 247], [379, 87, 432, 256], [460, 152, 480, 218]]
Chk 2130 [[0, 162, 171, 385], [129, 42, 333, 500], [251, 167, 333, 368]]
Chk 2131 [[72, 24, 219, 333], [213, 38, 340, 333], [332, 60, 462, 333]]
Chk 2132 [[217, 86, 493, 340], [11, 41, 184, 309], [392, 57, 494, 316]]
Chk 2133 [[1, 49, 138, 398], [63, 12, 332, 333]]
Chk 2134 [[2, 0, 218, 361], [238, 155, 418, 352]]
Chk 2135 [[264, 6, 474, 333], [21, 28, 255, 333]]
Chk 2136 [[0, 9, 182, 330], [160, 0, 307, 330], [255, 0, 500, 330]]
Chk 2137 [[244, 79, 446, 374], [18, 23, 167, 374]]
Chk 2139 [[176, 75, 457, 329], [27, 131, 159, 253], [150, 84, 300, 239]]
Chk 2140 [[87, 44, 236, 273], [0, 177, 317, 500]]
Chk 2141 [[0, 112, 66, 359], [46, 54, 338, 493], [269, 87, 310, 141], [191, 101, 387, 500]]
Chk 2144 [[34, 130, 117, 297], [83, 28, 231, 307], [296, 23, 406, 304]]
Chk 2145 [[247, 72, 328, 252], [134, 67, 213, 255]]
Chk 2146 [[203, 102, 366, 325], [319, 112, 491, 324]]
Chk 2148 [[131, 78, 301, 369], [124, 90, 298, 375]]
Chk 2149 [[137, 76, 213, 192], [56, 59, 98, 117]]
Chk 2150 [[126, 49, 338, 375], [286, 25, 491, 375]]
Chk 2151 [[93, 77, 141, 168], [128, 74, 192, 184], [339, 71, 400, 150], [0, 1, 135, 333], [181, 9, 364, 250], [321, 33, 500, 333]]
Chk 2152 [[38, 83, 106, 301], [218, 69, 296, 302], [398, 45, 473, 296], [305, 150, 351, 247], [281, 177, 315, 246], [355, 153, 379, 221]]
Chk 2153 [[111, 98, 283, 239], [311, 108, 461, 242], [0, 100, 47, 238]]
Chk 2155 [[224, 44, 322, 163], [42, 124, 229, 280]]
Chk 2156 [[370, 90, 499, 348], [57, 153, 209, 296]]
Chk 2159 [[197, 42, 433, 419], [45, 22, 214, 430]]
Chk 2160 [[47, 54, 139, 331], [119, 105, 186, 331], [249, 105, 321, 331], [310, 101, 401, 331], [395, 44, 500, 331]]
Chk 2161 [[0, 5, 298, 333], [194, 57, 500, 333]]
Chk 2162 [[388, 103, 436, 244], [452, 103, 499, 284], [39, 40, 115, 191], [167, 78, 233, 191]]
Chk 2163 [[185, 91, 321, 462], [20, 17, 230, 411]]
Chk 2164 [[264, 31, 485, 429], [38, 11, 245, 455]]
Chk 2165 [[44, 70, 179, 332], [295, 70, 459, 332], [136, 87, 316, 332]]
Chk 2168 [[40, 232, 130, 499], [123, 161, 172, 213]]
Chk 2170 [[4, 22, 271, 343], [344, 56, 494, 365]]
Chk 2171 [[244, 238, 299, 363], [316, 224, 356, 361]]
Chk 2172 [[127, 135, 243, 330], [225, 134, 269, 230]]
Chk 2174 [[160, 129, 233, 279], [40, 53, 80, 146], [252, 104, 304, 203], [332, 36, 370, 135]]
Chk 2175 [[0, 29, 214, 334], [201, 52, 392, 323], [343, 21, 500, 334]]
Chk 2176 [[243, 111, 392, 332], [195, 126, 252, 171]]
Chk 2178 [[277, 41, 378, 282], [360, 29, 488, 328], [145, 79, 230, 259], [212, 87, 297, 300], [53, 82, 157, 246]]
Chk 2179 [[300, 31, 499, 306], [15, 59, 264, 312]]
Chk 2180 [[53, 196, 148, 332], [119, 191, 158, 242]]
Chk 2181 [[114, 127, 232, 290], [0, 142, 83, 262], [254, 110, 352, 285], [442, 174, 485, 243]]
Chk 2182 [[196, 104, 259, 229], [238, 118, 301, 239], [331, 116, 435, 332]]
Chk 2183 [[316, 11, 499, 360], [94, 79, 277, 346]]
Chk 2184 [[116, 41, 197, 325], [424, 92, 468, 203], [342, 80, 387, 204], [242, 44, 348, 314]]
Chk 2185 [[103, 117, 138, 163], [133, 81, 245, 311], [244, 69, 316, 266]]
Chk 2186 [[121, 110, 163, 188], [261, 152, 318, 248]]
Chk 2188 [[199, 23, 299, 320], [127, 25, 205, 261]]
Chk 2189 [[102, 80, 226, 330], [296, 56, 472, 332]]
Chk 2191 [[260, 78, 488, 330], [115, 18, 307, 320], [44, 164, 129, 311]]
Chk 2192 [[0, 35, 231, 375], [356, 77, 500, 375]]
Chk 2193 [[106, 34, 290, 354], [299, 163, 499, 374]]
Chk 2194 [[244, 178, 298, 263], [0, 0, 278, 319], [454, 137, 500, 233], [314, 24, 500, 265]]
Chk 2195 [[0, 0, 165, 486], [118, 117, 369, 383], [304, 73, 478, 393]]
Chk 2196 [[154, 74, 220, 194], [213, 77, 274, 192]]
Chk 2197 [[0, 119, 56, 240], [13, 51, 75, 175], [100, 82, 148, 174], [109, 68, 160, 150], [164, 61, 221, 169], [194, 151, 273, 240], [81, 181, 201, 240], [274, 58, 354, 240]]
Chk 2198 [[56, 72, 262, 388], [63, 178, 252, 444]]
Chk 2199 [[140, 87, 310, 258], [229, 0, 345, 230], [320, 18, 381, 199], [370, 68, 439, 177]]
Chk 2200 [[102, 37, 201, 342], [228, 35, 368, 348]]
Chk 2201 [[121, 101, 164, 191], [145, 100, 187, 195], [187, 72, 250, 276], [250, 87, 306, 281]]
Chk 2202 [[88, 37, 263, 375], [230, 53, 357, 375]]
Chk 2203 [[359, 112, 430, 305], [331, 152, 387, 258], [135, 108, 202, 281], [17, 105, 74, 235]]
Chk 2204 [[20, 75, 93, 294], [57, 66, 146, 332], [152, 109, 233, 334], [247, 111, 332, 334], [375, 83, 500, 330]]
Chk 2205 [[279, 131, 456, 375], [217, 140, 305, 361], [76, 136, 254, 375], [62, 99, 135, 259]]
Chk 2206 [[98, 117, 242, 329], [259, 0, 432, 304], [171, 113, 244, 262]]
Chk 2207 [[9, 48, 338, 343], [235, 35, 483, 343]]
Chk 2209 [[269, 1, 433, 356], [138, 236, 276, 356], [39, 37, 165, 356]]
Chk 2210 [[66, 53, 292, 358], [207, 35, 477, 359]]
Chk 2211 [[208, 29, 479, 358], [41, 69, 294, 374]]
Chk 2213 [[260, 61, 328, 259], [167, 52, 248, 290], [222, 43, 266, 167]]
Chk 2214 [[100, 152, 138, 235], [216, 149, 242, 190], [289, 117, 315, 174]]
Chk 2215 [[252, 73, 362, 320], [140, 91, 240, 311]]
Chk 2216 [[0, 43, 334, 500], [0, 129, 275, 500]]
Chk 2218 [[139, 45, 286, 289], [35, 37, 270, 333]]
Chk 2219 [[152, 13, 492, 374], [4, 33, 168, 362]]
Chk 2220 [[0, 42, 221, 335], [274, 135, 436, 330], [430, 0, 499, 256]]
Chk 2221 [[15, 52, 304, 374], [150, 30, 300, 241], [359, 75, 499, 305]]
Chk 2223 [[0, 16, 336, 370], [273, 168, 457, 369]]
Chk 2224 [[76, 19, 184, 348], [184, 144, 449, 313]]
Chk 2225 [[325, 95, 433, 334], [81, 73, 178, 306], [230, 116, 271, 194]]
Chk 2226 [[90, 112, 215, 463], [204, 150, 326, 499]]
Chk 2228 [[6, 20, 199, 331], [295, 11, 497, 330]]
Chk 2229 [[253, 6, 488, 323], [81, 0, 402, 375]]
Chk 2230 [[157, 41, 251, 258], [288, 63, 372, 328]]
Chk 2231 [[32, 68, 130, 268], [73, 61, 168, 233], [203, 65, 311, 275], [337, 11, 484, 335]]
Chk 2232 [[21, 1, 232, 333], [220, 121, 435, 333]]
Chk 2233 [[86, 22, 347, 321], [205, 24, 488, 330]]
Chk 2234 [[265, 80, 441, 374], [164, 61, 357, 374]]
Chk 2235 [[187, 28, 286, 317], [63, 88, 197, 282], [398, 29, 499, 332], [325, 76, 425, 310]]
Chk 2236 [[51, 77, 119, 239], [218, 101, 272, 265], [313, 90, 371, 283], [167, 94, 196, 129], [160, 96, 184, 125]]
Chk 2237 [[105, 53, 288, 333], [215, 27, 342, 333]]
Chk 2238 [[86, 70, 193, 331], [343, 78, 452, 330], [190, 118, 295, 331], [306, 93, 360, 224]]
Chk 2239 [[71, 278, 141, 429], [205, 327, 319, 496], [201, 275, 248, 355], [211, 254, 244, 294]]
Chk 2240 [[10, 107, 140, 284], [191, 55, 344, 330], [223, 29, 481, 322]]
Chk 2241 [[29, 15, 225, 371], [242, 73, 484, 371], [231, 86, 317, 371]]
Chk 2242 [[111, 5, 285, 466], [274, 93, 377, 345]]
Chk 2243 [[54, 155, 145, 375], [0, 251, 35, 356], [152, 358, 201, 429], [226, 79, 353, 465], [340, 266, 409, 398]]
Chk 2244 [[129, 128, 249, 375], [222, 168, 298, 375], [262, 132, 412, 375]]
Chk 2245 [[73, 156, 198, 331], [197, 156, 352, 331]]
Chk 2247 [[78, 72, 199, 475], [215, 101, 325, 399], [159, 95, 217, 297]]
Chk 2248 [[315, 57, 438, 298], [145, 55, 295, 305], [156, 230, 194, 281]]
Chk 2249 [[224, 36, 428, 349], [32, 12, 269, 327]]
Chk 2250 [[67, 23, 263, 334], [190, 28, 399, 334]]

Chk 2251 [[132, 10, 243, 194], [271, 37, 485, 246]]
Chk 2252 [[52, 67, 277, 290], [241, 142, 385, 267]]
Chk 2253 [[192, 136, 358, 392], [0, 107, 138, 400]]
Chk 2254 [[3, 137, 126, 350], [274, 141, 457, 312], [107, 142, 207, 361], [195, 117, 315, 329]]
Chk 2255 [[114, 117, 164, 254], [283, 103, 343, 233], [376, 123, 429, 240]]
Chk 2256 [[81, 59, 198, 352], [142, 58, 253, 356], [258, 49, 357, 371], [394, 27, 498, 372]]
Chk 2257 [[255, 11, 467, 322], [70, 14, 222, 324], [380, 24, 498, 319], [4, 29, 65, 332]]
Chk 2258 [[229, 100, 373, 496], [107, 107, 264, 499]]
Chk 2259 [[89, 4, 178, 108], [228, 0, 303, 83], [148, 96, 227, 280], [283, 68, 358, 265]]
Chk 2260 [[268, 117, 340, 283], [410, 109, 457, 255]]
Chk 2261 [[300, 91, 373, 239], [252, 145, 284, 225]]
Chk 2262 [[86, 188, 159, 266], [157, 117, 263, 263]]
Chk 2263 [[262, 84, 365, 231], [268, 185, 373, 299], [276, 251, 448, 371], [26, 282, 193, 375], [113, 83, 205, 273], [6, 106, 79, 218], [4, 142, 63, 257]]
Chk 2265 [[29, 32, 240, 333], [240, 42, 429, 333]]
Chk 2266 [[250, 0, 360, 349], [100, 30, 242, 335]]
Chk 2267 [[128, 361, 198, 500], [191, 343, 259, 500], [0, 206, 187, 283]]
Chk 2268 [[173, 100, 228, 271], [4, 14, 111, 274], [20, 5, 76, 139]]
Chk 2270 [[81, 33, 280, 399], [314, 92, 490, 399]]
Chk 2271 [[25, 130, 119, 391], [187, 142, 288, 386]]
Chk 2272 [[131, 80, 234, 257], [213, 11, 305, 136], [227, 115, 387, 284], [0, 88, 103, 249]]
Chk 2273 [[219, 30, 290, 230], [135, 23, 213, 227]]
Chk 2274 [[2, 60, 147, 475], [148, 39, 395, 478]]
Chk 2275 [[31, 113, 190, 333], [157, 101, 333, 383], [58, 0, 333, 303]]
Chk 2277 [[87, 40, 188, 429], [167, 1, 292, 441]]
Chk 2278 [[197, 63, 319, 331], [95, 54, 210, 331], [19, 54, 98, 328]]
Chk 2280 [[35, 41, 153, 264], [360, 1, 431, 308], [373, 2, 454, 315]]
Chk 2281 [[195, 109, 294, 333], [276, 131, 419, 333], [427, 145, 500, 327]]
Chk 2284 [[24, 7, 113, 375], [160, 57, 229, 374], [306, 10, 497, 375]]
Chk 2285 [[113, 9, 156, 85], [152, 3, 227, 87], [43, 72, 162, 411], [156, 83, 245, 389]]
Chk 2286 [[128, 113, 260, 401], [389, 65, 456, 377], [298, 65, 377, 400], [253, 142, 319, 401], [65, 59, 147, 201], [124, 48, 186, 178]]
Chk 2287 [[88, 135, 203, 379], [302, 123, 423, 377], [328, 65, 362, 137]]
Chk 2289 [[35, 37, 188, 332], [353, 71, 484, 333]]
Chk 2290 [[352, 131, 494, 352], [92, 140, 208, 334], [6, 156, 45, 285], [238, 135, 340, 301]]
Chk 2291 [[67, 74, 181, 249], [308, 68, 401, 280], [165, 71, 279, 262]]
Chk 2292 [[261, 174, 386, 373], [318, 181, 428, 365]]
Chk 2293 [[117, 114, 310, 492], [72, 144, 178, 446]]
Chk 2294 [[26, 87, 94, 274], [95, 85, 156, 268]]
Chk 2295 [[124, 53, 212, 206], [304, 35, 407, 222]]
Chk 2296 [[4, 0, 241, 332], [155, 96, 317, 332], [232, 26, 390, 332]]
Chk 2297 [[248, 148, 317, 253], [170, 185, 244, 272], [68, 174, 138, 289]]
Chk 2298 [[328, 87, 479, 273], [6, 37, 204, 354], [125, 83, 248, 300], [215, 142, 301, 254]]
Chk 2299 [[5, 34, 226, 480], [120, 75, 332, 483]]
Chk 2301 [[169, 25, 424, 332], [69, 55, 242, 332]]
Chk 2302 [[89, 107, 289, 333], [307, 73, 411, 314]]
Chk 2303 [[0, 34, 209, 338], [230, 70, 359, 338]]
Chk 2304 [[130, 54, 323, 332], [14, 98, 144, 332], [228, 0, 449, 332]]
Chk 2306 [[0, 61, 195, 244], [254, 54, 475, 224]]
Chk 2307 [[0, 105, 152, 355], [287, 84, 495, 369], [146, 102, 205, 171]]
Chk 2308 [[0, 36, 189, 408], [139, 22, 429, 410], [236, 157, 415, 406]]
Chk 2309 [[64, 173, 186, 445], [146, 166, 233, 413]]
Chk 2310 [[79, 78, 361, 374], [309, 65, 499, 374]]
Chk 2311 [[191, 55, 365, 375], [107, 92, 206, 352], [351, 106, 461, 364], [68, 13, 93, 55]]
Chk 2312 [[337, 146, 399, 282], [189, 154, 266, 301]]
Chk 2313 [[170, 112, 266, 293], [289, 118, 389, 294]]
Chk 2314 [[308, 69, 381, 177], [138, 56, 228, 214], [22, 49, 128, 250]]
Chk 2315 [[342, 37, 412, 252], [85, 17, 150, 251], [57, 126, 109, 260], [242, 135, 290, 234]]
Chk 2316 [[9, 29, 375, 330], [196, 65, 439, 329]]
Chk 2317 [[71, 213, 147, 418], [148, 204, 221, 425]]
Chk 2318 [[0, 71, 45, 332], [22, 76, 84, 321], [59, 61, 181, 333], [277, 62, 367, 333], [295, 0, 500, 333]]
Chk 2320 [[188, 128, 238, 246], [121, 100, 179, 196], [55, 121, 98, 256]]
Chk 2321 [[364, 84, 456, 320], [65, 124, 141, 261]]
Chk 2322 [[62, 216, 108, 385], [90, 127, 213, 391], [205, 205, 305, 475], [249, 176, 358, 467], [344, 153, 394, 322], [362, 108, 477, 481]]
Chk 2323 [[206, 4, 372, 373], [68, 21, 228, 367], [44, 59, 70, 116], [0, 64, 29, 185], [193, 51, 225, 134]]
Chk 2324 [[381, 57, 474, 253], [1, 80, 130, 333], [204, 107, 326, 275]]
Chk 2326 [[248, 80, 447, 374], [81, 115, 220, 374], [359, 97, 492, 374], [0, 49, 119, 374]]
Chk 2327 [[35, 16, 147, 355], [114, 0, 210, 276], [266, 141, 347, 247], [301, 104, 449, 276], [298, 190, 451, 375], [184, 38, 221, 143], [218, 14, 255, 129]]
Chk 2328 [[222, 116, 372, 273], [90, 114, 188, 264]]
Chk 2329 [[6, 48, 102, 307], [175, 48, 257, 299], [274, 49, 366, 317], [394, 27, 500, 319]]
Chk 2330 [[223, 188, 269, 333], [280, 174, 321, 330]]
Chk 2331 [[22, 141, 77, 270], [187, 105, 240, 278], [226, 126, 288, 251]]
Chk 2332 [[114, 159, 169, 299], [213, 146, 251, 254], [164, 145, 194, 258]]
Chk 2333 [[0, 21, 154, 333], [167, 86, 480, 333], [373, 115, 500, 315]]
Chk 2334 [[93, 74, 171, 346], [162, 114, 215, 313], [209, 86, 385, 363], [370, 138, 436, 315]]
Chk 2335 [[275, 148, 356, 295], [195, 160, 257, 229], [79, 148, 155, 218]]
Chk 2337 [[186, 133, 253, 233], [105, 147, 188, 254]]
Chk 2339 [[109, 111, 331, 499], [36, 44, 238, 424]]
Chk 2340 [[0, 200, 117, 422], [149, 184, 296, 356], [77, 168, 219, 301]]
Chk 2341 [[79, 26, 227, 468], [203, 29, 377, 411]]
Chk 2343 [[23, 52, 153, 367], [374, 84, 458, 290], [176, 109, 305, 290]]
Chk 2344 [[84, 8, 293, 454], [369, 243, 488, 436]]
Chk 2345 [[0, 73, 224, 333], [193, 35, 500, 333], [196, 123, 215, 162], [222, 126, 239, 165], [248, 125, 274, 167], [283, 123, 304, 165], [172, 124, 193, 162]]
Chk 2346 [[31, 142, 281, 469], [155, 284, 291, 468]]
Chk 2347 [[86, 54, 328, 360], [9, 120, 259, 499]]
Chk 2348 [[109, 134, 188, 281], [195, 147, 280, 319]]
Chk 2349 [[243, 41, 481, 331], [110, 109, 247, 284]]
Chk 2350 [[189, 65, 460, 332], [28, 94, 244, 332]]
Chk 2351 [[376, 83, 500, 303], [296, 48, 403, 321], [217, 44, 337, 352], [29, 92, 167, 334], [11, 80, 66, 254], [7, 79, 61, 257]]
Chk 2352 [[257, 30, 487, 320], [0, 18, 251, 323]]
Chk 2353 [[173, 18, 339, 332], [35, 41, 161, 332], [380, 36, 467, 332]]
Chk 2356 [[63, 116, 232, 350], [321, 103, 479, 399], [261, 121, 368, 245], [175, 115, 249, 230]]
Chk 2357 [[44, 86, 207, 326], [168, 63, 255, 173], [272, 95, 367, 218], [404, 76, 493, 292], [265, 193, 489, 333]]
Chk 2358 [[37, 68, 168, 296], [178, 60, 380, 319]]
Chk 2360 [[340, 70, 491, 499], [217, 124, 358, 478], [32, 86, 169, 490]]
Chk 2362 [[46, 33, 191, 464], [142, 93, 340, 500]]
Chk 2363 [[109, 122, 160, 284], [284, 143, 351, 260]]
Chk 2364 [[78, 79, 291, 317], [279, 111, 430, 352]]
Chk 2365 [[246, 217, 354, 401], [195, 208, 297, 392]]
Chk 2366 [[227, 101, 478, 433], [3, 0, 263, 444]]
Chk 2367 [[35, 48, 174, 206], [268, 68, 455, 287]]
Chk 2368 [[123, 66, 261, 328], [185, 66, 366, 333]]
Chk 2369 [[277, 90, 332, 325], [317, 92, 374, 273], [354, 82, 423, 328]]
Chk 2370 [[175, 133, 424, 399], [34, 16, 283, 399]]
Chk 2373 [[85, 83, 146, 199], [14, 76, 88, 247]]
Chk 2374 [[67, 28, 295, 350], [294, 59, 486, 356]]
Chk 2375 [[181, 1, 231, 128], [56, 58, 108, 198]]
Chk 2376 [[324, 108, 404, 326], [63, 119, 135, 243], [236, 134, 327, 355], [204, 116, 267, 297]]
Chk 2377 [[71, 22, 327, 333], [276, 100, 313, 144], [283, 56, 442, 301]]
Chk 2378 [[283, 7, 486, 333], [50, 6, 307, 333]]
Chk 2379 [[0, 132, 114, 322], [121, 33, 251, 338], [38, 204, 218, 375], [351, 118, 485, 317], [249, 65, 499, 375]]
Chk 2380 [[102, 90, 188, 285], [197, 42, 275, 286]]
Chk 2381 [[0, 9, 70, 196], [72, 33, 258, 333], [240, 23, 348, 333], [252, 74, 467, 333]]
Chk 2382 [[69, 9, 407, 496], [304, 38, 499, 499]]
Chk 2383 [[61, 194, 174, 347], [325, 16, 474, 350]]
Chk 2384 [[450, 135, 500, 238], [337, 110, 436, 237], [222, 94, 314, 232], [103, 102, 222, 233], [0, 117, 105, 278]]
Chk 2385 [[355, 92, 451, 300], [272, 59, 316, 183]]
Chk 2387 [[196, 19, 482, 332], [27, 80, 250, 332]]
Chk 2388 [[289, 100, 411, 331], [97, 110, 243, 331]]
Chk 2389 [[36, 81, 194, 370], [295, 21, 497, 374]]
Chk 2390 [[26, 152, 87, 331], [90, 147, 170, 334], [194, 144, 277, 332], [320, 145, 390, 335], [403, 147, 482, 332]]
Chk 2391 [[46, 0, 173, 367], [153, 2, 339, 367], [272, 93, 425, 273]]
Chk 2393 [[337, 42, 499, 333], [217, 128, 298, 333], [126, 121, 225, 332], [1, 76, 183, 333]]
Chk 2394 [[8, 55, 283, 332], [242, 74, 475, 332]]

Chk 2396 [[167, 150, 259, 375], [271, 94, 372, 375]]
Chk 2398 [[188, 73, 497, 356], [43, 84, 262, 369]]
Chk 2399 [[151, 23, 490, 371], [17, 0, 218, 250]]
Chk 2400 [[291, 72, 428, 332], [280, 78, 336, 176], [236, 47, 312, 154], [81, 64, 172, 190], [0, 78, 150, 332]]
Chk 2401 [[72, 27, 216, 331], [180, 25, 309, 332]]
Chk 2402 [[227, 46, 314, 300], [290, 30, 375, 294]]
Chk 2403 [[155, 0, 427, 332], [174, 48, 409, 332]]
Chk 2405 [[369, 23, 500, 375], [238, 54, 377, 375], [0, 212, 146, 375], [0, 38, 108, 238]]
Chk 2406 [[27, 78, 184, 374], [337, 92, 412, 215], [279, 41, 337, 167]]
Chk 2407 [[38, 53, 306, 500], [260, 159, 375, 500]]
Chk 2408 [[234, 107, 486, 330], [0, 102, 87, 308], [49, 92, 316, 331]]
Chk 2409 [[49, 62, 264, 499], [285, 84, 423, 499], [0, 0, 92, 214]]
Chk 2410 [[20, 34, 261, 494], [123, 131, 332, 499]]
Chk 2412 [[353, 3, 480, 374], [249, 37, 347, 337], [8, 5, 264, 366], [155, 9, 273, 247]]
Chk 2413 [[19, 107, 305, 411], [152, 124, 332, 499]]
Chk 2414 [[2, 65, 259, 375], [231, 86, 456, 375]]
Chk 2415 [[109, 70, 298, 333], [254, 0, 500, 333]]
Chk 2416 [[178, 151, 243, 280], [264, 44, 378, 280]]
Chk 2417 [[93, 104, 239, 332], [258, 113, 410, 332]]
Chk 2418 [[28, 80, 121, 275], [126, 142, 250, 325], [195, 136, 354, 375], [307, 130, 500, 375]]
Chk 2419 [[281, 149, 393, 332], [20, 114, 127, 330]]
Chk 2420 [[281, 107, 381, 275], [182, 73, 299, 253], [81, 107, 210, 283], [17, 91, 98, 289], [15, 82, 107, 302]]
Chk 2421 [[191, 67, 328, 475], [7, 2, 104, 305]]
Chk 2422 [[0, 132, 104, 332], [284, 112, 392, 306], [276, 10, 378, 191]]
Chk 2423 [[19, 4, 218, 332], [263, 99, 483, 332]]
Chk 2424 [[53, 0, 196, 125], [0, 0, 79, 264], [71, 176, 201, 489]]
Chk 2425 [[28, 61, 195, 455], [317, 183, 381, 339], [109, 34, 313, 499]]
Chk 2426 [[197, 0, 483, 334], [90, 179, 287, 334]]
Chk 2428 [[76, 172, 151, 273], [140, 60, 288, 334], [272, 74, 432, 334], [431, 221, 500, 334]]
Chk 2429 [[161, 67, 274, 312], [354, 65, 427, 272]]
Chk 2430 [[33, 157, 140, 268], [286, 156, 396, 286]]
Chk 2431 [[210, 139, 276, 367], [29, 204, 211, 320]]
Chk 2432 [[223, 60, 294, 269], [120, 48, 217, 319], [434, 77, 494, 262], [311, 60, 376, 291], [0, 217, 21, 301]]
Chk 2433 [[119, 154, 238, 375], [111, 51, 218, 199], [203, 63, 302, 340], [263, 55, 443, 375], [116, 4, 166, 119]]
Chk 2434 [[190, 156, 275, 271], [363, 94, 499, 352], [0, 39, 216, 372], [317, 158, 402, 330]]
Chk 2435 [[179, 54, 287, 408], [91, 82, 185, 405], [55, 100, 96, 216], [3, 89, 52, 199]]
Chk 2436 [[298, 64, 379, 266], [52, 49, 132, 235], [24, 50, 49, 104]]
Chk 2437 [[340, 73, 461, 241], [244, 83, 369, 217], [43, 81, 164, 242], [130, 79, 220, 206]]
Chk 2440 [[37, 70, 197, 351], [134, 47, 364, 480]]
Chk 2441 [[16, 29, 105, 186], [24, 10, 187, 469], [104, 21, 333, 500]]
Chk 2442 [[230, 126, 339, 374], [150, 88, 256, 374]]
Chk 2443 [[21, 199, 85, 323], [365, 208, 403, 313], [401, 194, 457, 312], [297, 206, 337, 324]]
Chk 2444 [[178, 119, 359, 490], [6, 77, 274, 499]]
Chk 2445 [[234, 78, 371, 313], [35, 121, 164, 272], [102, 109, 178, 227]]
Chk 2447 [[266, 122, 441, 413], [192, 147, 254, 331]]
Chk 2448 [[19, 20, 204, 332], [154, 36, 398, 310]]
Chk 2449 [[136, 129, 263, 374], [260, 199, 430, 374], [71, 183, 147, 369]]
Chk 2450 [[108, 253, 259, 375], [142, 52, 495, 375], [202, 61, 500, 371]]
Chk 2451 [[106, 26, 370, 331], [222, 98, 440, 342]]
Chk 2452 [[63, 32, 315, 398], [192, 226, 294, 493]]
Chk 2454 [[114, 92, 192, 289], [79, 84, 146, 285], [337, 96, 402, 284]]
Chk 2456 [[263, 4, 499, 348], [23, 68, 328, 364]]
Chk 2457 [[75, 65, 162, 251], [200, 96, 302, 278], [336, 87, 437, 269]]
Chk 2458 [[0, 34, 355, 387], [228, 149, 437, 387]]
Chk 2459 [[297, 64, 427, 331], [178, 77, 284, 331], [39, 32, 164, 331]]
Chk 2460 [[275, 0, 500, 375], [271, 119, 414, 277], [132, 153, 252, 267]]
Chk 2461 [[111, 65, 359, 461], [11, 144, 256, 472], [17, 163, 157, 390]]
Chk 2462 [[272, 81, 354, 271], [166, 96, 255, 263]]
Chk 2463 [[18, 60, 430, 375], [217, 95, 360, 375]]
Chk 2468 [[284, 196, 335, 361], [202, 190, 267, 352], [101, 192, 158, 357], [135, 162, 189, 345]]
Chk 2470 [[14, 15, 251, 333], [130, 0, 222, 91], [163, 0, 285, 164], [240, 7, 500, 333]]
Chk 2472 [[20, 198, 170, 411], [251, 173, 326, 393]]
Chk 2473 [[58, 49, 139, 270], [161, 50, 227, 223], [2, 71, 25, 163]]
Chk 2474 [[339, 13, 499, 352], [6, 30, 217, 360]]
Chk 2475 [[323, 62, 499, 334], [105, 63, 318, 328], [30, 60, 186, 329]]
Chk 2476 [[247, 112, 373, 386], [8, 152, 190, 477]]
Chk 2477 [[118, 65, 330, 461], [31, 87, 194, 445], [145, 18, 311, 220]]
Chk 2479 [[59, 88, 136, 251], [185, 58, 282, 266], [342, 47, 438, 284]]
Chk 2480 [[27, 36, 206, 279], [251, 23, 480, 281], [195, 116, 264, 230]]
Chk 2482 [[88, 63, 312, 333], [226, 58, 399, 333]]
Chk 2484 [[60, 11, 238, 296], [304, 51, 479, 322]]
Chk 2485 [[189, 145, 253, 232], [113, 12, 164, 201]]
Chk 2486 [[381, 31, 439, 237], [150, 85, 260, 310], [307, 43, 388, 243], [234, 79, 336, 264]]
Chk 2487 [[185, 107, 385, 335], [243, 63, 313, 203]]
Chk 2488 [[42, 199, 145, 331], [147, 185, 276, 331], [317, 54, 390, 301], [412, 49, 472, 255], [459, 81, 500, 209]]
Chk 2489 [[257, 170, 359, 411], [2, 204, 114, 277], [121, 184, 193, 322], [174, 167, 237, 354]]
Chk 2491 [[11, 0, 372, 500], [234, 130, 500, 500]]
Chk 2493 [[35, 109, 213, 258], [125, 90, 238, 215], [281, 93, 353, 189], [342, 94, 407, 202], [448, 84, 500, 182], [301, 93, 479, 334]]
Chk 2494 [[210, 76, 294, 276], [318, 65, 431, 285], [69, 71, 137, 289]]
Chk 2495 [[80, 247, 154, 372], [118, 264, 166, 339], [147, 254, 247, 422]]
Chk 2498 [[164, 344, 237, 500], [207, 334, 291, 500]]
Chk 2499 [[254, 97, 388, 333], [335, 103, 494, 333]]
Chk 2500 [[183, 160, 316, 333], [253, 122, 347, 333]]
Chk 2503 [[26, 34, 151, 312], [158, 22, 462, 375]]
Chk 2506 [[164, 204, 228, 375], [99, 230, 166, 371], [38, 6, 79, 95]]
Chk 2507 [[197, 97, 286, 317], [275, 111, 352, 319]]
Chk 2508 [[285, 121, 356, 332], [349, 98, 445, 332], [41, 108, 143, 332], [125, 100, 219, 332]]
Chk 2509 [[12, 16, 188, 328], [198, 79, 468, 322]]
Chk 2511 [[79, 102, 156, 255], [0, 75, 34, 182], [36, 87, 74, 175], [273, 119, 341, 264]]
Chk 2512 [[131, 59, 266, 281], [276, 43, 403, 281], [397, 67, 497, 274], [5, 22, 151, 280]]
Chk 2513 [[144, 23, 293, 478], [97, 33, 185, 405]]
Chk 2514 [[0, 38, 88, 375], [141, 133, 238, 375], [295, 114, 422, 375], [256, 128, 332, 359]]
Chk 2515 [[0, 75, 75, 357], [42, 6, 277, 357], [266, 72, 481, 357], [408, 101, 500, 357]]
Chk 2516 [[0, 63, 65, 333], [108, 34, 234, 333], [200, 230, 287, 333]]
Chk 2517 [[81, 77, 275, 452], [218, 66, 333, 386]]
Chk 2518 [[349, 108, 411, 210], [413, 109, 482, 221], [218, 82, 274, 205]]
Chk 2520 [[0, 22, 130, 302], [279, 181, 435, 332], [121, 160, 272, 332], [235, 129, 285, 292], [402, 179, 499, 314]]
Chk 2521 [[17, 132, 274, 500], [8, 92, 291, 500]]
Chk 2522 [[108, 121, 172, 226], [196, 121, 283, 210], [201, 46, 491, 310]]
Chk 2523 [[175, 86, 296, 317], [113, 81, 202, 275]]
Chk 2524 [[19, 94, 289, 474], [95, 107, 272, 311]]
Chk 2525 [[383, 39, 479, 365], [40, 49, 167, 355], [236, 75, 401, 369], [204, 72, 332, 276]]
Chk 2526 [[355, 16, 479, 294], [167, 27, 210, 180], [209, 29, 251, 173], [473, 22, 499, 155], [341, 31, 372, 88]]
Chk 2530 [[139, 2, 345, 333], [16, 133, 160, 328], [325, 130, 442, 333]]
Chk 2531 [[131, 41, 250, 333], [238, 103, 323, 261], [299, 102, 393, 250]]
Chk 2532 [[193, 41, 278, 347], [70, 63, 169, 352]]
Chk 2533 [[41, 183, 157, 453], [126, 189, 199, 375], [221, 187, 271, 284]]
Chk 2535 [[0, 56, 201, 334], [158, 68, 265, 334]]
Chk 2537 [[180, 110, 266, 332], [371, 106, 426, 204], [282, 114, 348, 266]]
Chk 2538 [[0, 152, 180, 333], [4, 157, 168, 333], [157, 113, 307, 299], [343, 102, 428, 333], [383, 92, 500, 333]]
Chk 2539 [[160, 102, 253, 238], [58, 74, 269, 375]]
Chk 2540 [[31, 92, 206, 332], [252, 117, 437, 332]]
Chk 2541 [[64, 115, 186, 358], [222, 135, 420, 374]]
Chk 2542 [[106, 20, 160, 144], [172, 6, 236, 167], [206, 46, 254, 161], [230, 17, 292, 170], [268, 104, 313, 180]]
Chk 2543 [[81, 164, 125, 325], [123, 212, 156, 322]]
Chk 2544 [[202, 86, 259, 191], [50, 92, 243, 375], [137, 195, 417, 375], [350, 57, 500, 359]]
Chk 2546 [[265, 41, 385, 323], [0, 43, 119, 313], [164, 83, 253, 268]]
Chk 2547 [[213, 166, 249, 255], [175, 158, 204, 251]]
Chk 2548 [[240, 129, 427, 373], [376, 239, 477, 372], [0, 120, 47, 371]]
Chk 2549 [[40, 58, 140, 325], [290, 58, 417, 294]]
Chk 2550 [[102, 125, 199, 317], [296, 125, 337, 267], [252, 136, 297, 263]]
Chk 2552 [[204, 67, 499, 331], [33, 24, 255, 206]]
Chk 2553 [[344, 70, 466, 331], [188, 77, 331, 331], [29, 151, 175, 331]]

Chk 2554 [[25, 0, 375, 467], [53, 10, 203, 311]]
Chk 2555 [[198, 51, 280, 266], [326, 85, 391, 202], [44, 120, 115, 193]]
Chk 2556 [[309, 209, 407, 378], [103, 292, 220, 459], [8, 169, 50, 221], [373, 169, 406, 225], [340, 161, 376, 231], [403, 175, 424, 220]]
Chk 2557 [[276, 79, 421, 274], [40, 101, 209, 267], [191, 49, 260, 271], [231, 16, 321, 270]]
Chk 2558 [[138, 0, 480, 372], [24, 100, 281, 367]]
Chk 2559 [[172, 85, 292, 408], [230, 89, 338, 392], [59, 61, 188, 410]]
Chk 2561 [[0, 98, 174, 293], [428, 51, 499, 231], [143, 73, 305, 274], [308, 82, 473, 244]]
Chk 2562 [[98, 14, 208, 231], [339, 1, 440, 162], [218, 77, 353, 259]]
Chk 2564 [[0, 90, 73, 299], [0, 75, 39, 196], [44, 31, 230, 333], [180, 59, 315, 180], [212, 80, 321, 333], [207, 14, 461, 333]]
Chk 2566 [[92, 94, 179, 209], [253, 93, 301, 205], [304, 99, 346, 204]]
Chk 2567 [[164, 160, 269, 442], [71, 144, 185, 455]]
Chk 2568 [[148, 22, 227, 238], [69, 35, 140, 277], [280, 11, 388, 216], [208, 13, 287, 235]]
Chk 2569 [[52, 11, 273, 318], [338, 9, 467, 339], [201, 4, 399, 331]]
Chk 2570 [[2, 31, 322, 391], [289, 17, 499, 395]]
Chk 2571 [[63, 126, 170, 447], [159, 158, 213, 313]]
Chk 2572 [[72, 99, 263, 341], [257, 130, 373, 304]]
Chk 2573 [[9, 28, 214, 325], [294, 44, 493, 325], [208, 33, 394, 325], [80, 119, 214, 292]]
Chk 2574 [[192, 40, 481, 332], [33, 20, 354, 327]]
Chk 2575 [[26, 148, 369, 353], [217, 33, 340, 220], [427, 124, 495, 238]]
Chk 2576 [[339, 85, 432, 196], [277, 76, 351, 157], [67, 87, 195, 300], [129, 22, 219, 139]]
Chk 2577 [[213, 226, 372, 500], [0, 202, 134, 500]]
Chk 2578 [[280, 27, 383, 282], [374, 41, 454, 275]]
Chk 2580 [[158, 80, 364, 332], [283, 8, 500, 332], [2, 89, 198, 332]]
Chk 2581 [[272, 149, 314, 267], [335, 67, 390, 266]]
Chk 2582 [[45, 4, 242, 332], [217, 67, 365, 332], [424, 132, 500, 332]]
Chk 2583 [[212, 60, 308, 238], [14, 14, 126, 205], [100, 115, 186, 264]]
Chk 2584 [[0, 87, 262, 375], [91, 133, 201, 284], [224, 105, 353, 353], [339, 88, 473, 321]]
Chk 2585 [[94, 138, 234, 312], [274, 136, 340, 207], [338, 147, 460, 319], [13, 124, 119, 281]]
Chk 2586 [[76, 137, 201, 332], [330, 8, 436, 321]]
Chk 2587 [[15, 133, 114, 225], [105, 127, 170, 209], [200, 51, 280, 217]]
Chk 2588 [[136, 89, 378, 450], [70, 103, 197, 442]]
Chk 2589 [[135, 141, 330, 415], [153, 203, 219, 300], [0, 136, 161, 392]]
Chk 2590 [[211, 100, 368, 307], [313, 84, 394, 288], [44, 75, 159, 290]]
Chk 2592 [[157, 55, 470, 317], [73, 154, 274, 308]]
Chk 2594 [[266, 101, 466, 370], [178, 150, 279, 370], [148, 173, 213, 370]]
Chk 2595 [[163, 52, 315, 205], [287, 54, 437, 206]]
Chk 2596 [[272, 50, 443, 292], [37, 8, 199, 333]]
Chk 2598 [[176, 18, 415, 290], [97, 22, 294, 297]]
Chk 2599 [[225, 106, 324, 325], [329, 106, 447, 332], [0, 64, 185, 324]]
Chk 2601 [[46, 95, 146, 275], [362, 75, 493, 318], [190, 77, 309, 278]]
Chk 2603 [[303, 150, 357, 274], [99, 181, 146, 303], [202, 244, 350, 347]]
Chk 2604 [[86, 13, 127, 86], [30, 79, 213, 375], [257, 48, 365, 262]]
Chk 2605 [[119, 126, 226, 361], [252, 54, 365, 379], [348, 77, 431, 382]]
Chk 2607 [[96, 49, 333, 500], [152, 279, 304, 500]]
Chk 2608 [[77, 136, 229, 333], [136, 280, 162, 331], [185, 79, 414, 333], [193, 85, 410, 333], [432, 207, 500, 333]]
Chk 2609 [[223, 140, 325, 382], [74, 261, 137, 374]]
Chk 2610 [[89, 171, 135, 302], [187, 208, 227, 281], [440, 214, 486, 262], [218, 169, 255, 281]]
Chk 2611 [[74, 53, 147, 278], [175, 51, 235, 267], [231, 105, 318, 266]]
Chk 2612 [[240, 65, 326, 355], [58, 9, 269, 375]]
Chk 2613 [[72, 96, 193, 248], [195, 100, 310, 457]]
Chk 2614 [[38, 63, 208, 333], [323, 7, 453, 274]]
Chk 2615 [[8, 48, 306, 429], [255, 57, 455, 429]]
Chk 2616 [[195, 76, 274, 334], [132, 111, 223, 359]]
Chk 2617 [[241, 127, 345, 312], [129, 20, 236, 292]]
Chk 2618 [[21, 7, 241, 377], [235, 115, 421, 377], [354, 206, 500, 377]]
Chk 2619 [[236, 12, 500, 426], [274, 166, 318, 231], [315, 192, 356, 234], [119, 153, 299, 372], [0, 286, 132, 397], [21, 249, 62, 294], [90, 247, 132, 298]]
Chk 2620 [[130, 59, 258, 353], [127, 71, 263, 353], [308, 6, 500, 353]]
Chk 2622 [[86, 42, 182, 321], [135, 71, 221, 327]]
Chk 2623 [[360, 48, 496, 375], [235, 235, 337, 368], [80, 12, 293, 375], [53, 22, 295, 375]]
Chk 2625 [[136, 0, 330, 240], [34, 63, 187, 327], [278, 1, 355, 105]]
Chk 2628 [[136, 26, 445, 352], [38, 130, 223, 365]]
Chk 2629 [[24, 122, 163, 330], [167, 165, 238, 332], [303, 110, 383, 332]]
Chk 2630 [[312, 56, 458, 330], [12, 53, 140, 325], [435, 84, 499, 330], [283, 94, 353, 325], [108, 71, 187, 330]]
Chk 2631 [[268, 53, 434, 335], [222, 136, 288, 254]]
Chk 2632 [[351, 6, 500, 389], [238, 98, 349, 296], [144, 201, 225, 328], [100, 235, 156, 312], [27, 194, 69, 275], [0, 183, 38, 260]]
Chk 2634 [[102, 202, 178, 315], [348, 174, 419, 328], [239, 187, 317, 303], [448, 189, 474, 250]]
Chk 2635 [[0, 70, 229, 277], [130, 71, 291, 277]]
Chk 2636 [[129, 176, 243, 478], [222, 157, 313, 453]]
Chk 2637 [[35, 78, 123, 315], [341, 98, 442, 289], [207, 65, 307, 254]]
Chk 2639 [[289, 58, 396, 318], [97, 58, 277, 335]]
Chk 2641 [[271, 51, 436, 331], [289, 41, 402, 190], [13, 18, 159, 252]]
Chk 2642 [[55, 150, 154, 331], [397, 126, 446, 300], [176, 132, 214, 229], [0, 130, 28, 218], [16, 134, 45, 207], [35, 132, 56, 196]]
Chk 2643 [[167, 82, 247, 288], [55, 32, 144, 317], [278, 16, 360, 317], [360, 52, 445, 313]]
Chk 2644 [[30, 120, 133, 434], [144, 187, 264, 462], [274, 92, 374, 489], [144, 157, 204, 343]]
Chk 2645 [[62, 122, 105, 172], [95, 120, 147, 197], [124, 100, 417, 318], [284, 59, 359, 243], [196, 125, 241, 182]]
Chk 2646 [[124, 234, 224, 454], [17, 251, 155, 447]]
Chk 2648 [[148, 141, 260, 358], [64, 103, 191, 310]]
Chk 2649 [[211, 127, 282, 254], [283, 149, 387, 270], [176, 252, 350, 334]]
Chk 2650 [[328, 117, 376, 189], [252, 102, 307, 271], [287, 119, 330, 194], [220, 126, 266, 208], [128, 190, 183, 318]]
Chk 2651 [[100, 84, 181, 270], [269, 76, 390, 256]]
Chk 2652 [[298, 9, 456, 310], [19, 45, 285, 352], [64, 0, 91, 45]]
Chk 2653 [[279, 35, 483, 374], [3, 3, 243, 341]]
Chk 2654 [[8, 157, 81, 271], [243, 84, 355, 333], [314, 16, 439, 333]]
Chk 2655 [[357, 68, 499, 328], [97, 65, 257, 332]]
Chk 2656 [[3, 59, 102, 165], [174, 48, 322, 185], [354, 63, 500, 258]]
Chk 2657 [[395, 101, 472, 243], [256, 104, 392, 396], [217, 75, 347, 380]]
Chk 2658 [[0, 55, 63, 299], [85, 58, 200, 312], [310, 49, 386, 244], [324, 46, 398, 246], [396, 59, 500, 230], [22, 41, 86, 97], [458, 45, 500, 126]]
Chk 2659 [[31, 145, 210, 383], [100, 19, 309, 409]]
Chk 2660 [[142, 105, 230, 262], [9, 66, 84, 266], [431, 118, 483, 265], [367, 131, 420, 275]]
Chk 2661 [[0, 114, 100, 333], [61, 120, 232, 333], [232, 116, 361, 249]]
Chk 2663 [[4, 134, 118, 285], [216, 151, 380, 332], [361, 175, 484, 332], [334, 65, 407, 163], [404, 107, 476, 198]]
Chk 2664 [[21, 27, 110, 309], [274, 130, 405, 333], [399, 136, 500, 309]]
Chk 2666 [[2, 152, 76, 331], [215, 160, 262, 329], [82, 162, 154, 331], [451, 146, 499, 331], [343, 195, 366, 227]]
Chk 2667 [[66, 72, 181, 383], [191, 89, 304, 401], [15, 186, 45, 246]]
Chk 2668 [[236, 148, 295, 312], [185, 101, 289, 317]]
Chk 2669 [[217, 135, 295, 280], [259, 100, 324, 225], [296, 94, 346, 162]]
Chk 2671 [[270, 122, 388, 203], [142, 121, 230, 332]]
Chk 2672 [[91, 47, 295, 281], [206, 30, 453, 281]]
Chk 2673 [[264, 28, 309, 97], [355, 32, 431, 116], [405, 212, 479, 317], [116, 174, 201, 278], [105, 145, 148, 206]]
Chk 2675 [[51, 37, 206, 333], [177, 74, 377, 333]]
Chk 2676 [[74, 69, 124, 192], [191, 116, 248, 192], [441, 153, 499, 262]]
Chk 2678 [[64, 65, 240, 327], [226, 92, 452, 331], [437, 233, 499, 331]]
Chk 2680 [[300, 103, 361, 280], [233, 99, 304, 282], [72, 118, 155, 310], [139, 171, 203, 294], [137, 119, 186, 191]]
Chk 2681 [[124, 177, 202, 442], [25, 144, 119, 460]]
Chk 2682 [[129, 77, 209, 206], [358, 74, 457, 341], [335, 86, 409, 282]]
Chk 2683 [[141, 27, 190, 120], [168, 207, 229, 315]]
Chk 2684 [[77, 191, 222, 356], [171, 197, 262, 347]]
Chk 2685 [[34, 27, 260, 362], [203, 12, 499, 362]]
Chk 2686 [[25, 25, 258, 323], [243, 51, 482, 316]]
Chk 2687 [[107, 54, 171, 153], [25, 64, 97, 157], [333, 21, 395, 197], [153, 90, 234, 156], [396, 84, 489, 153], [298, 24, 346, 176]]
Chk 2688 [[420, 32, 496, 240], [197, 22, 350, 330], [66, 42, 226, 330], [336, 5, 461, 268]]
Chk 2689 [[262, 45, 335, 215], [95, 34, 169, 245], [350, 131, 455, 226]]
Chk 2690 [[30, 358, 93, 479], [93, 350, 144, 493], [187, 339, 241, 481]]
Chk 2691 [[195, 11, 338, 165], [194, 103, 319, 320]]
Chk 2694 [[318, 54, 495, 217], [150, 68, 305, 326]]
Chk 2695 [[48, 61, 229, 329], [196, 60, 298, 327]]
Chk 2696 [[109, 73, 213, 308], [221, 83, 325, 333]]
Chk 2697 [[171, 96, 290, 216], [277, 207, 444, 355], [0, 157, 117, 359], [112, 160, 242, 374], [288, 102, 403, 222], [392, 127, 479, 286]]
Chk 2698 [[91, 190, 201, 495], [147, 202, 224, 474], [64, 238, 94, 335], [3, 239, 52, 324]]
Chk 2700 [[45, 9, 254, 470], [114, 208, 354, 500]]
Chk 2701 [[75, 65, 194, 322], [366, 47, 493, 331]]
Chk 2702 [[0, 70, 375, 500], [0, 38, 245, 451]]
Chk 2703 [[339, 26, 454, 192], [219, 32, 327, 187]]

Chk 2704 [[0, 125, 251, 418], [8, 132, 241, 410], [0, 131, 269, 451]]
Chk 2706 [[84, 196, 173, 405], [155, 139, 253, 343]]
Chk 2707 [[105, 73, 229, 332], [221, 187, 305, 332], [287, 58, 356, 245], [310, 40, 422, 332]]
Chk 2708 [[175, 94, 281, 200], [286, 87, 386, 201]]
Chk 2710 [[140, 31, 307, 474], [290, 13, 485, 463]]
Chk 2712 [[282, 7, 447, 288], [50, 44, 208, 300], [34, 76, 62, 140]]
Chk 2713 [[357, 62, 453, 321], [100, 80, 184, 332], [162, 56, 246, 292]]
Chk 2714 [[348, 101, 430, 325], [183, 113, 243, 331], [245, 107, 323, 308], [46, 137, 86, 210]]
Chk 2715 [[185, 210, 290, 445], [91, 220, 170, 426], [0, 412, 58, 499]]
Chk 2716 [[18, 55, 339, 329], [299, 113, 482, 313]]
Chk 2717 [[6, 0, 333, 497], [13, 73, 333, 500]]
Chk 2718 [[192, 119, 384, 259], [42, 120, 154, 280]]
Chk 2719 [[180, 15, 494, 334], [85, 62, 326, 334]]
Chk 2720 [[329, 47, 499, 356], [84, 37, 270, 281], [1, 75, 156, 320]]
Chk 2721 [[160, 66, 237, 308], [275, 84, 345, 213]]
Chk 2723 [[216, 32, 332, 188], [0, 17, 166, 293], [359, 12, 496, 320], [434, 0, 495, 63]]
Chk 2724 [[165, 86, 244, 208], [431, 149, 484, 220], [366, 145, 417, 223], [329, 132, 385, 206]]
Chk 2726 [[104, 92, 279, 333], [354, 180, 463, 333], [401, 101, 500, 319], [254, 146, 364, 333]]
Chk 2727 [[162, 100, 350, 480], [47, 109, 216, 499]]
Chk 2728 [[22, 46, 257, 370], [307, 79, 436, 338], [11, 123, 79, 294]]
Chk 2729 [[303, 68, 480, 247], [27, 27, 238, 218]]
Chk 2730 [[142, 57, 490, 331], [0, 68, 225, 331]]
Chk 2731 [[57, 188, 119, 362], [232, 186, 294, 329], [335, 168, 388, 348]]
Chk 2733 [[213, 199, 273, 361], [112, 167, 205, 447], [296, 237, 323, 318]]
Chk 2734 [[145, 122, 250, 358], [57, 44, 130, 192], [20, 101, 91, 200], [308, 37, 351, 79], [233, 64, 432, 375], [282, 43, 500, 375]]
Chk 2736 [[181, 156, 274, 455], [47, 46, 177, 459]]
Chk 2737 [[0, 252, 65, 333], [212, 135, 292, 273], [309, 195, 414, 333], [393, 188, 500, 333]]
Chk 2738 [[233, 110, 300, 283], [190, 117, 237, 283], [370, 147, 451, 331]]
Chk 2740 [[0, 113, 101, 330], [77, 73, 335, 375], [221, 101, 362, 375]]
Chk 2741 [[63, 158, 194, 492], [149, 48, 290, 442]]
Chk 2743 [[227, 73, 305, 355], [325, 50, 437, 358], [35, 38, 135, 361]]
Chk 2744 [[0, 129, 69, 333], [29, 43, 191, 333], [160, 81, 242, 332], [236, 85, 297, 320], [279, 74, 349, 294], [287, 115, 419, 333], [395, 95, 500, 333]]
Chk 2745 [[102, 87, 146, 233], [164, 140, 208, 262], [182, 26, 270, 261], [190, 158, 267, 264]]
Chk 2746 [[155, 153, 227, 356], [261, 103, 330, 220], [286, 95, 430, 269]]
Chk 2747 [[309, 43, 470, 374], [7, 47, 116, 206], [443, 16, 477, 72], [272, 43, 294, 84], [175, 60, 222, 121], [213, 40, 252, 129], [103, 51, 131, 107]]
Chk 2748 [[94, 102, 229, 301], [347, 84, 500, 346]]
Chk 2749 [[98, 30, 186, 299], [159, 0, 340, 375], [136, 121, 199, 365]]
Chk 2750 [[195, 73, 311, 374], [141, 90, 215, 374], [292, 84, 384, 306], [409, 100, 477, 261]]
Chk 2752 [[0, 13, 182, 333], [171, 128, 275, 242], [220, 120, 357, 278]]
Chk 2753 [[391, 90, 500, 234], [286, 97, 399, 240], [157, 104, 303, 245], [1, 78, 159, 301]]
Chk 2754 [[262, 116, 338, 273], [106, 3, 161, 144], [445, 99, 491, 185], [19, 53, 158, 334]]
Chk 2755 [[1, 0, 153, 387], [182, 126, 267, 417], [236, 1, 313, 247], [80, 37, 139, 141], [183, 12, 243, 213]]
Chk 2756 [[325, 150, 444, 280], [203, 171, 316, 325], [65, 114, 217, 344]]
Chk 2758 [[245, 56, 452, 295], [64, 69, 248, 271]]
Chk 2759 [[172, 96, 212, 182], [399, 78, 488, 290], [343, 48, 419, 266], [224, 90, 260, 161]]
Chk 2760 [[127, 5, 309, 311], [241, 15, 407, 335]]
Chk 2762 [[132, 108, 178, 262], [2, 84, 58, 210], [251, 67, 297, 270], [229, 132, 263, 255]]
Chk 2763 [[29, 207, 162, 499], [127, 35, 260, 309], [8, 9, 139, 451]]
Chk 2764 [[206, 76, 257, 219], [129, 85, 176, 247], [397, 68, 459, 203]]
Chk 2766 [[79, 80, 164, 273], [349, 15, 427, 238]]
Chk 2767 [[149, 157, 212, 285], [48, 86, 76, 160], [95, 95, 118, 143], [226, 175, 309, 305], [138, 97, 158, 128], [146, 102, 169, 129]]
Chk 2768 [[62, 16, 162, 490], [172, 51, 305, 468]]
Chk 2769 [[224, 271, 289, 361], [348, 233, 429, 356], [310, 260, 345, 324]]
Chk 2770 [[43, 97, 151, 327], [254, 24, 477, 326], [148, 97, 201, 283], [0, 89, 72, 332], [195, 108, 351, 332]]
Chk 2771 [[143, 163, 235, 321], [211, 156, 292, 313]]
Chk 2772 [[87, 61, 279, 300], [240, 63, 279, 160], [18, 64, 164, 300]]
Chk 2774 [[63, 88, 209, 333], [250, 65, 400, 333]]
Chk 2776 [[241, 138, 370, 374], [67, 4, 261, 263]]
Chk 2777 [[34, 103, 246, 279], [75, 92, 329, 203], [196, 91, 294, 253], [323, 90, 458, 261]]
Chk 2779 [[4, 60, 169, 231], [326, 122, 494, 356], [153, 84, 387, 313]]
Chk 2780 [[336, 65, 407, 237], [5, 74, 62, 253], [266, 46, 351, 309], [423, 65, 491, 265], [326, 25, 346, 71]]
Chk 2781 [[0, 172, 44, 282], [146, 140, 208, 333], [222, 148, 308, 331]]
Chk 2783 [[38, 77, 164, 366], [141, 96, 259, 375], [227, 51, 310, 310], [360, 113, 500, 375], [305, 55, 446, 339], [285, 45, 367, 255]]
Chk 2785 [[463, 120, 500, 301], [410, 115, 479, 305], [351, 108, 422, 312], [276, 105, 363, 315], [101, 106, 168, 323], [53, 127, 129, 330], [0, 143, 59, 324]]
Chk 2786 [[175, 33, 485, 323], [115, 76, 325, 332]]
Chk 2787 [[78, 73, 334, 407], [7, 20, 202, 418]]
Chk 2788 [[38, 25, 280, 333], [280, 58, 437, 284]]
Chk 2789 [[359, 141, 422, 190], [266, 131, 318, 186], [190, 125, 240, 184], [240, 98, 274, 134], [93, 161, 128, 201], [72, 137, 116, 210]]
Chk 2791 [[263, 0, 499, 280], [0, 16, 262, 280]]
Chk 2792 [[247, 43, 441, 499], [160, 24, 305, 499]]
Chk 2793 [[0, 307, 107, 451], [113, 153, 247, 492], [336, 63, 475, 477], [303, 133, 381, 447]]
Chk 2794 [[120, 101, 237, 218], [201, 32, 293, 162], [188, 74, 351, 247], [212, 117, 436, 320]]
Chk 2795 [[277, 53, 392, 290], [241, 70, 281, 223], [104, 65, 226, 249], [21, 113, 65, 161]]
Chk 2797 [[233, 58, 297, 248], [174, 42, 254, 298], [101, 72, 179, 226]]
Chk 2798 [[316, 31, 458, 331], [165, 66, 298, 319]]
Chk 2799 [[294, 115, 375, 245], [99, 101, 214, 259]]
Chk 2800 [[122, 389, 154, 429], [258, 404, 294, 449], [142, 317, 165, 371]]
Chk 2801 [[93, 68, 373, 328], [347, 18, 499, 331], [0, 41, 100, 323]]
Chk 2802 [[92, 12, 158, 115], [205, 16, 267, 103], [170, 68, 302, 241], [305, 73, 367, 129], [322, 56, 438, 211], [402, 60, 491, 178], [223, 183, 373, 375], [66, 178, 237, 375]]
Chk 2804 [[261, 151, 300, 285], [86, 140, 143, 275], [47, 151, 73, 240], [11, 136, 42, 238], [158, 135, 186, 218], [296, 104, 338, 147]]
Chk 2805 [[190, 118, 249, 289], [243, 129, 292, 286]]
Chk 2806 [[207, 144, 253, 226], [264, 136, 309, 198]]
Chk 2807 [[224, 109, 310, 267], [152, 117, 239, 265]]
Chk 2808 [[215, 132, 281, 245], [130, 112, 186, 208], [275, 115, 335, 218]]
Chk 2809 [[360, 82, 488, 224], [180, 101, 347, 231]]
Chk 2810 [[204, 126, 314, 426], [55, 118, 196, 389], [126, 196, 167, 337]]
Chk 2811 [[179, 85, 250, 203], [90, 90, 134, 219], [361, 73, 379, 127]]
Chk 2812 [[50, 228, 161, 362], [124, 232, 236, 388]]
Chk 2813 [[1, 47, 105, 294], [158, 76, 212, 237], [255, 94, 295, 151], [330, 25, 451, 311]]
Chk 2814 [[43, 312, 87, 435], [193, 285, 268, 476], [112, 336, 218, 467]]
Chk 2815 [[137, 65, 251, 278], [345, 83, 461, 251], [250, 109, 326, 224], [57, 70, 128, 270]]
Chk 2817 [[243, 41, 342, 333], [307, 38, 429, 334]]
Chk 2818 [[0, 84, 305, 437], [42, 114, 298, 463]]
Chk 2819 [[3, 69, 118, 408], [156, 122, 270, 484]]
Chk 2820 [[251, 109, 352, 289], [338, 132, 395, 277]]
Chk 2821 [[64, 45, 245, 333], [189, 103, 346, 333], [280, 169, 345, 254], [234, 292, 335, 333]]
Chk 2822 [[67, 78, 251, 322], [202, 37, 360, 295], [347, 25, 471, 264]]
Chk 2824 [[236, 1, 442, 500], [75, 342, 228, 500]]
Chk 2825 [[203, 93, 288, 276], [239, 87, 342, 265]]
Chk 2826 [[10, 218, 177, 391], [157, 196, 312, 400], [273, 244, 325, 351]]
Chk 2827 [[240, 29, 463, 279], [200, 28, 345, 268]]
Chk 2828 [[194, 37, 393, 313], [74, 33, 184, 185]]
Chk 2829 [[287, 42, 406, 260], [388, 55, 496, 356], [109, 19, 224, 270], [21, 41, 198, 358], [211, 0, 321, 229]]
Chk 2830 [[82, 167, 212, 313], [199, 165, 306, 313], [292, 156, 441, 313]]
Chk 2831 [[27, 76, 286, 333], [298, 26, 499, 316]]
Chk 2832 [[1, 34, 258, 296], [0, 4, 500, 375]]
Chk 2833 [[95, 91, 232, 497], [16, 131, 120, 485], [226, 164, 312, 313], [212, 121, 261, 188], [242, 116, 277, 178]]
Chk 2834 [[126, 123, 216, 413], [200, 128, 312, 453], [73, 68, 134, 164]]
Chk 2838 [[56, 149, 225, 325], [0, 52, 172, 332]]
Chk 2839 [[7, 56, 133, 471], [180, 50, 295, 463]]
Chk 2840 [[155, 121, 199, 257], [219, 105, 281, 283], [328, 86, 377, 294], [366, 143, 425, 251]]
Chk 2841 [[0, 76, 112, 196], [141, 55, 310, 300], [0, 155, 88, 345], [291, 96, 361, 203], [318, 60, 493, 310], [442, 154, 500, 346]]

Chk 2842 [[309, 134, 488, 332], [8, 139, 167, 332], [167, 129, 350, 318]]
Chk 2843 [[26, 99, 144, 361], [157, 20, 349, 361], [395, 87, 500, 361]]
Chk 2845 [[117, 181, 224, 331], [318, 202, 365, 327]]
Chk 2846 [[1, 101, 71, 395], [99, 98, 238, 429], [218, 29, 323, 477]]
Chk 2847 [[235, 87, 466, 356], [0, 93, 282, 348]]
Chk 2848 [[189, 39, 329, 499], [38, 59, 205, 499]]
Chk 2850 [[107, 173, 190, 278], [213, 139, 297, 465]]
Chk 2851 [[197, 129, 309, 374], [84, 137, 203, 373], [322, 168, 442, 374]]
Chk 2852 [[143, 35, 213, 243], [194, 42, 272, 234], [149, 57, 200, 147]]
Chk 2853 [[65, 67, 151, 204], [0, 56, 135, 375], [418, 110, 500, 375], [286, 89, 372, 366]]
Chk 2854 [[47, 0, 418, 367], [312, 170, 499, 374]]
Chk 2855 [[0, 15, 140, 315], [126, 0, 324, 315], [322, 2, 500, 315]]
Chk 2856 [[277, 38, 348, 252], [159, 20, 255, 285]]
Chk 2857 [[36, 135, 126, 272], [50, 219, 214, 332], [194, 145, 354, 332]]
Chk 2858 [[195, 53, 406, 409], [210, 0, 255, 58], [158, 57, 334, 282]]
Chk 2859 [[236, 115, 289, 201], [0, 109, 39, 186], [0, 69, 81, 333], [79, 69, 191, 333], [236, 18, 366, 333]]
Chk 2860 [[94, 170, 136, 242], [128, 161, 156, 241], [224, 159, 259, 241], [343, 182, 394, 271]]
Chk 2861 [[104, 15, 266, 335], [229, 13, 391, 335]]
Chk 2862 [[35, 122, 93, 256], [116, 101, 215, 321], [174, 121, 249, 255], [395, 115, 430, 183], [326, 113, 441, 320]]
Chk 2863 [[21, 24, 275, 375], [188, 30, 472, 340]]
Chk 2864 [[257, 59, 377, 461], [82, 184, 254, 471], [121, 180, 242, 354]]
Chk 2865 [[333, 67, 410, 242], [37, 142, 120, 304]]
Chk 2866 [[219, 222, 271, 368], [264, 230, 302, 370]]
Chk 2867 [[191, 17, 385, 356], [134, 95, 213, 305]]
Chk 2868 [[72, 19, 353, 390], [5, 161, 154, 485], [33, 100, 135, 246]]
Chk 2869 [[138, 56, 224, 328], [217, 64, 328, 332]]
Chk 2870 [[0, 56, 207, 375], [197, 38, 407, 309]]
Chk 2871 [[0, 81, 361, 332], [216, 115, 377, 279], [198, 107, 465, 332], [215, 101, 473, 330]]
Chk 2872 [[420, 89, 497, 331], [241, 138, 270, 208], [345, 131, 403, 214], [269, 145, 335, 256], [316, 146, 353, 223], [467, 105, 499, 180]]
Chk 2873 [[0, 71, 213, 375], [225, 116, 498, 375]]
Chk 2874 [[238, 107, 346, 374], [91, 132, 174, 329]]
Chk 2875 [[304, 97, 421, 284], [191, 123, 296, 297], [124, 133, 203, 287]]
Chk 2877 [[19, 35, 157, 321], [322, 37, 458, 211], [182, 49, 292, 203], [0, 22, 59, 176]]
Chk 2878 [[343, 14, 498, 334], [0, 16, 186, 302], [206, 57, 242, 139], [119, 42, 220, 135], [60, 34, 242, 233], [0, 21, 37, 240], [0, 20, 25, 88]]
Chk 2880 [[102, 142, 367, 499], [331, 123, 489, 499]]
Chk 2881 [[0, 3, 192, 333], [328, 68, 492, 330]]
Chk 2882 [[50, 61, 132, 132], [180, 49, 254, 167]]
Chk 2883 [[235, 27, 403, 375], [375, 106, 500, 375]]
Chk 2886 [[71, 103, 338, 487], [127, 133, 291, 362]]
Chk 2887 [[179, 115, 426, 325], [192, 128, 307, 292]]
Chk 2888 [[78, 156, 152, 330], [178, 180, 289, 333]]
Chk 2889 [[91, 133, 132, 241], [293, 63, 397, 289]]
Chk 2891 [[64, 61, 249, 334], [148, 67, 420, 334], [21, 104, 42, 152]]
Chk 2892 [[222, 139, 345, 449], [144, 300, 248, 397], [0, 143, 127, 438], [89, 113, 160, 370]]
Chk 2893 [[270, 75, 416, 476], [43, 43, 216, 482], [0, 249, 51, 409]]
Chk 2894 [[40, 75, 127, 281], [271, 70, 366, 245], [380, 60, 437, 245], [406, 57, 481, 255], [358, 89, 415, 232]]
Chk 2895 [[0, 118, 132, 332], [0, 92, 135, 312], [104, 75, 253, 331], [222, 32, 441, 332]]
Chk 2896 [[302, 33, 477, 303], [25, 41, 172, 316]]
Chk 2897 [[188, 39, 358, 500], [0, 51, 179, 500], [0, 43, 185, 410]]
Chk 2898 [[298, 133, 448, 317], [72, 47, 228, 291], [217, 91, 315, 286]]
Chk 2899 [[43, 97, 156, 333], [130, 116, 217, 333], [206, 125, 311, 333], [290, 124, 405, 333]]
Chk 2900 [[329, 130, 408, 262], [175, 112, 267, 214], [5, 102, 137, 281]]
Chk 2902 [[105, 70, 278, 331], [254, 26, 386, 325], [1, 72, 50, 318]]
Chk 2903 [[90, 39, 184, 287], [205, 18, 319, 318]]
Chk 2904 [[204, 98, 367, 375], [241, 72, 500, 353]]
Chk 2906 [[0, 58, 68, 265], [60, 36, 266, 313], [310, 48, 500, 276], [255, 0, 347, 167], [402, 0, 500, 163]]
Chk 2908 [[356, 264, 429, 458], [302, 252, 350, 428]]
Chk 2909 [[74, 41, 249, 375], [228, 41, 407, 375]]
Chk 2911 [[40, 184, 150, 289], [174, 96, 279, 219], [283, 63, 445, 332]]
Chk 2912 [[257, 271, 321, 474], [201, 286, 253, 465]]
Chk 2913 [[264, 92, 324, 300], [54, 47, 192, 365], [469, 121, 499, 276], [345, 77, 448, 365], [196, 42, 290, 260]]
Chk 2914 [[195, 101, 356, 323], [24, 123, 142, 304], [336, 58, 495, 362]]
Chk 2916 [[164, 59, 298, 259], [63, 96, 140, 270], [284, 99, 370, 269], [333, 86, 412, 280]]
Chk 2917 [[147, 137, 191, 317], [163, 209, 240, 483], [169, 161, 257, 477], [64, 85, 163, 488]]
Chk 2918 [[30, 71, 144, 310], [242, 39, 386, 310]]
Chk 2919 [[237, 225, 285, 346], [128, 221, 166, 347]]
Chk 2920 [[132, 80, 250, 191], [0, 10, 136, 332], [262, 84, 342, 208], [294, 97, 438, 211], [0, 0, 51, 70]]
Chk 2921 [[139, 137, 311, 484], [28, 133, 206, 479]]
Chk 2922 [[21, 0, 311, 372], [237, 39, 423, 374]]
Chk 2923 [[44, 101, 242, 499], [151, 96, 320, 483]]
Chk 2924 [[138, 43, 229, 339], [326, 67, 448, 338]]
Chk 2925 [[54, 10, 332, 500], [27, 5, 303, 500]]
Chk 2926 [[21, 75, 82, 183], [174, 65, 212, 173], [308, 130, 375, 223], [283, 132, 329, 209]]
Chk 2928 [[149, 20, 371, 346], [25, 101, 205, 356]]
Chk 2929 [[7, 27, 157, 319], [126, 43, 208, 319], [272, 62, 342, 310]]
Chk 2930 [[7, 0, 329, 375], [187, 99, 484, 375], [330, 90, 500, 308]]
Chk 2931 [[190, 11, 441, 302], [150, 129, 264, 259], [82, 82, 377, 375]]
Chk 2932 [[39, 45, 188, 276], [273, 44, 403, 227]]
Chk 2934 [[69, 48, 245, 225], [283, 52, 457, 333]]
Chk 2935 [[211, 21, 487, 357], [13, 46, 265, 360]]
Chk 2936 [[0, 42, 179, 260], [116, 84, 207, 228], [157, 49, 277, 220], [220, 8, 298, 169]]
Chk 2940 [[50, 80, 177, 483], [281, 54, 444, 487], [200, 68, 364, 444]]
Chk 2941 [[28, 104, 89, 228], [256, 89, 323, 200], [74, 92, 122, 242], [194, 109, 215, 146], [124, 90, 163, 244]]
Chk 2942 [[12, 166, 253, 500], [127, 49, 349, 500]]
Chk 2943 [[320, 94, 419, 373], [268, 143, 307, 262], [335, 195, 499, 373]]
Chk 2946 [[8, 284, 158, 433], [100, 234, 177, 342], [190, 263, 322, 435], [237, 222, 326, 342]]
Chk 2947 [[77, 85, 166, 263], [33, 87, 104, 269], [325, 96, 390, 249]]
Chk 2948 [[40, 108, 95, 216], [189, 138, 265, 331], [281, 107, 360, 256], [143, 121, 193, 260]]
Chk 2949 [[0, 103, 167, 415], [143, 357, 338, 450], [66, 431, 144, 500], [131, 430, 288, 500], [101, 120, 306, 406]]
Chk 2950 [[4, 0, 213, 495], [343, 145, 485, 329], [202, 108, 335, 314]]
Chk 2951 [[20, 133, 152, 331], [373, 124, 493, 246]]
Chk 2952 [[151, 146, 331, 498], [85, 70, 204, 373]]
Chk 2953 [[0, 117, 135, 331], [213, 103, 283, 279]]
Chk 2954 [[296, 46, 391, 275], [288, 42, 396, 274], [153, 59, 212, 247], [121, 71, 183, 242]]
Chk 2955 [[105, 118, 187, 238], [276, 109, 385, 211], [224, 119, 302, 206]]
Chk 2956 [[24, 110, 300, 400], [197, 128, 300, 277], [339, 127, 451, 378]]
Chk 2958 [[109, 46, 150, 118], [129, 51, 180, 151], [215, 47, 258, 143], [423, 52, 474, 156]]
Chk 2960 [[216, 60, 367, 357], [122, 19, 295, 349], [4, 6, 204, 357]]
Chk 2963 [[184, 130, 242, 195], [261, 130, 320, 182], [321, 142, 376, 190], [386, 127, 440, 194]]
Chk 2964 [[239, 84, 405, 332], [57, 21, 323, 332]]
Chk 2965 [[212, 97, 314, 332], [66, 63, 195, 332], [306, 113, 442, 332]]
Chk 2966 [[91, 91, 185, 404], [149, 98, 288, 397]]
Chk 2967 [[47, 63, 210, 262], [297, 66, 467, 265]]
Chk 2969 [[260, 62, 448, 302], [133, 74, 311, 281], [81, 90, 217, 270], [11, 86, 141, 265], [51, 90, 105, 179], [20, 90, 78, 191]]
Chk 2970 [[290, 46, 481, 333], [19, 30, 198, 333]]
Chk 2971 [[94, 129, 297, 380], [126, 112, 318, 377], [144, 132, 339, 374]]
Chk 2974 [[103, 91, 144, 226], [212, 143, 287, 224], [147, 148, 200, 202]]
Chk 2975 [[303, 216, 344, 324], [205, 176, 264, 264], [371, 213, 423, 307], [278, 181, 302, 237]]
Chk 2976 [[98, 97, 174, 338], [287, 132, 334, 318]]
Chk 2977 [[92, 28, 228, 375], [181, 32, 396, 375]]
Chk 2978 [[13, 33, 194, 304], [359, 59, 460, 284]]
Chk 2979 [[30, 78, 116, 305], [164, 96, 233, 308]]
Chk 2980 [[58, 18, 182, 376], [211, 135, 316, 376], [219, 77, 335, 374]]
Chk 2982 [[176, 77, 386, 333], [62, 86, 228, 333]]
Chk 2983 [[58, 153, 159, 351], [7, 88, 101, 251], [155, 129, 226, 287], [313, 148, 381, 500], [280, 153, 343, 268], [222, 149, 285, 282], [318, 128, 354, 156]]
Chk 2984 [[4, 120, 204, 283], [179, 97, 365, 299]]
Chk 2985 [[0, 20, 188, 369], [276, 118, 419, 374], [465, 198, 497, 276], [159, 46, 268, 363]]
Chk 2986 [[0, 45, 344, 456], [227, 71, 349, 432]]
Chk 2987 [[122, 147, 313, 279], [236, 158, 470, 363]]

Chk 2988 [[330, 103, 410, 340], [300, 124, 345, 278], [265, 111, 310, 192], [153, 118, 212, 267], [97, 108, 167, 365], [66, 99, 120, 330]]
Chk 2989 [[127, 57, 195, 332], [279, 60, 354, 286], [470, 66, 499, 256]]
Chk 2990 [[183, 74, 264, 333], [111, 97, 174, 298], [375, 169, 455, 283]]
Chk 2991 [[182, 146, 223, 321], [271, 120, 319, 310]]
Chk 2992 [[23, 162, 152, 455], [123, 62, 290, 392]]
Chk 2993 [[50, 173, 85, 275], [83, 167, 133, 280], [168, 169, 217, 315], [137, 181, 175, 271]]
Chk 2994 [[13, 115, 236, 375], [128, 99, 408, 375]]
Chk 2995 [[8, 111, 163, 333], [140, 98, 313, 333], [311, 118, 472, 333]]
Chk 2996 [[140, 144, 212, 220], [210, 148, 256, 217]]
Chk 2997 [[76, 60, 170, 322], [159, 47, 235, 326]]
Chk 2999 [[324, 27, 452, 236], [84, 64, 212, 230]]
Chk 3000 [[183, 7, 423, 328], [404, 6, 499, 332], [59, 22, 281, 332]]
Chk 3001 [[151, 53, 225, 264], [87, 59, 167, 271]]
Chk 3003 [[381, 79, 483, 328], [42, 187, 147, 309], [182, 104, 276, 275]]
Chk 3004 [[183, 82, 311, 333], [303, 144, 403, 333], [368, 105, 500, 333]]
Chk 3007 [[132, 44, 311, 499], [38, 118, 158, 475], [160, 412, 312, 494]]
Chk 3008 [[106, 63, 245, 333], [209, 72, 342, 333], [249, 62, 361, 328]]
Chk 3010 [[145, 136, 374, 489], [32, 178, 217, 485]]
Chk 3011 [[193, 163, 231, 256], [155, 155, 194, 265]]
Chk 3012 [[0, 198, 54, 373], [165, 171, 239, 366], [257, 168, 313, 369]]
Chk 3014 [[340, 142, 398, 327], [387, 177, 452, 320]]
Chk 3015 [[91, 160, 277, 454], [20, 172, 104, 300]]
Chk 3017 [[340, 148, 499, 374], [171, 99, 435, 371], [6, 25, 261, 374]]
Chk 3018 [[230, 51, 387, 323], [41, 85, 237, 323]]
Chk 3019 [[197, 60, 276, 270], [155, 118, 216, 279], [240, 89, 350, 282]]
Chk 3020 [[207, 64, 311, 308], [142, 50, 229, 274]]
Chk 3021 [[86, 13, 233, 375], [236, 0, 367, 375], [363, 0, 481, 375]]
Chk 3022 [[67, 133, 151, 427], [66, 87, 170, 365], [201, 62, 296, 439]]
Chk 3023 [[14, 79, 109, 323], [63, 161, 148, 337], [186, 94, 291, 346], [195, 87, 291, 342], [453, 91, 500, 344]]
Chk 3024 [[250, 125, 464, 366], [64, 136, 171, 374], [161, 149, 287, 373], [33, 128, 65, 170]]
Chk 3025 [[52, 166, 197, 343], [186, 7, 425, 361]]
Chk 3026 [[37, 30, 240, 331], [251, 34, 434, 331]]
Chk 3027 [[196, 148, 252, 279], [158, 139, 218, 275]]
Chk 3028 [[0, 41, 139, 276], [52, 121, 220, 290], [222, 121, 352, 279]]
Chk 3029 [[134, 20, 192, 74], [2, 14, 294, 402], [217, 106, 403, 397]]
Chk 3030 [[297, 82, 394, 361], [70, 170, 144, 299]]
Chk 3031 [[65, 105, 221, 366], [158, 77, 263, 274]]
Chk 3032 [[150, 3, 274, 333], [243, 15, 469, 333], [278, 40, 359, 295]]
Chk 3033 [[136, 148, 256, 495], [45, 152, 161, 500]]
Chk 3034 [[22, 106, 234, 257], [206, 106, 330, 273], [46, 75, 500, 324]]
Chk 3035 [[337, 75, 433, 290], [396, 32, 471, 283]]
Chk 3036 [[19, 23, 188, 331], [179, 84, 307, 323], [254, 34, 407, 331]]
Chk 3037 [[25, 66, 188, 325], [257, 1, 380, 363], [363, 78, 497, 317]]
Chk 3038 [[8, 168, 202, 345], [43, 111, 143, 225], [154, 106, 286, 252], [285, 21, 403, 256], [377, 211, 500, 345]]
Chk 3039 [[273, 129, 337, 287], [331, 109, 402, 305]]
Chk 3040 [[212, 245, 254, 300], [252, 237, 296, 303], [86, 242, 145, 404], [16, 234, 89, 423]]
Chk 3041 [[66, 77, 280, 282], [272, 52, 411, 238]]
Chk 3042 [[174, 167, 300, 306], [0, 106, 192, 374], [350, 137, 484, 282]]
Chk 3044 [[93, 27, 207, 326], [279, 33, 429, 330], [416, 0, 494, 206]]
Chk 3045 [[0, 61, 256, 486], [207, 156, 332, 499]]
Chk 3046 [[70, 222, 123, 375], [103, 238, 165, 375], [397, 215, 466, 370]]
Chk 3047 [[235, 226, 369, 467], [71, 203, 239, 469]]
Chk 3048 [[98, 81, 141, 181], [144, 80, 188, 148], [175, 24, 258, 357], [214, 44, 344, 422]]
Chk 3049 [[296, 24, 492, 327], [120, 9, 312, 248], [21, 1, 172, 241]]
Chk 3050 [[111, 143, 222, 372], [328, 0, 499, 364]]
Chk 3051 [[44, 29, 276, 331], [157, 23, 499, 333]]
Chk 3052 [[52, 26, 227, 375], [254, 11, 428, 340]]
Chk 3053 [[0, 0, 259, 500], [201, 220, 358, 500]]
Chk 3055 [[151, 72, 215, 315], [256, 188, 313, 297]]
Chk 3056 [[130, 37, 216, 256], [295, 40, 404, 324]]
Chk 3057 [[311, 175, 409, 293], [64, 171, 150, 261], [180, 151, 286, 294], [137, 164, 215, 257]]
Chk 3058 [[159, 83, 330, 323], [388, 118, 500, 298]]
Chk 3059 [[158, 121, 275, 454], [60, 147, 182, 494], [94, 17, 259, 240]]
Chk 3060 [[102, 116, 193, 334], [232, 98, 325, 326]]
Chk 3062 [[72, 28, 181, 295], [162, 90, 257, 210], [261, 107, 416, 332]]
Chk 3063 [[280, 10, 424, 336], [111, 126, 270, 368], [1, 42, 30, 97]]
Chk 3064 [[93, 192, 230, 255], [277, 138, 423, 238], [64, 103, 237, 329]]
Chk 3065 [[221, 9, 341, 287], [4, 87, 194, 366], [292, 72, 491, 371], [408, 74, 451, 130]]
Chk 3066 [[79, 240, 178, 454], [178, 207, 250, 358]]
Chk 3067 [[11, 39, 177, 335], [202, 45, 378, 335], [318, 42, 420, 335]]
Chk 3068 [[193, 130, 352, 274], [94, 157, 228, 287], [327, 141, 486, 330], [313, 130, 415, 280]]
Chk 3070 [[260, 34, 449, 374], [408, 218, 499, 374], [49, 166, 228, 374]]
Chk 3071 [[414, 44, 500, 214], [282, 55, 402, 202], [132, 68, 285, 193]]
Chk 3072 [[16, 93, 329, 331], [179, 108, 394, 331]]
Chk 3073 [[15, 55, 79, 218], [128, 12, 171, 153], [167, 9, 234, 159], [318, 59, 370, 151], [401, 66, 482, 221], [390, 14, 430, 93]]
Chk 3074 [[385, 64, 443, 333], [324, 54, 402, 322]]
Chk 3075 [[94, 103, 221, 334], [219, 94, 312, 334]]
Chk 3077 [[266, 45, 404, 279], [83, 51, 164, 252]]
Chk 3078 [[64, 212, 121, 321], [275, 143, 396, 334], [153, 151, 301, 334]]
Chk 3079 [[193, 170, 333, 406], [25, 87, 233, 500]]
Chk 3081 [[25, 142, 73, 262], [91, 151, 172, 375], [290, 139, 385, 360], [415, 101, 500, 243], [192, 60, 301, 161]]
Chk 3083 [[67, 85, 214, 319], [219, 67, 388, 263], [219, 58, 401, 247]]
Chk 3084 [[19, 55, 222, 476], [204, 144, 331, 494]]
Chk 3085 [[318, 54, 452, 332], [74, 21, 181, 322], [199, 123, 289, 284]]
Chk 3086 [[309, 16, 499, 332], [158, 73, 296, 304]]
Chk 3087 [[304, 81, 499, 373], [17, 46, 238, 374]]
Chk 3088 [[121, 146, 221, 333], [177, 118, 264, 333]]
Chk 3090 [[75, 285, 127, 452], [30, 257, 95, 470], [156, 231, 198, 320]]
Chk 3091 [[32, 50, 333, 448], [272, 102, 428, 457]]
Chk 3092 [[55, 62, 203, 332], [153, 77, 230, 332], [290, 108, 430, 332], [387, 51, 500, 332]]
Chk 3093 [[320, 29, 449, 327], [17, 43, 150, 294], [272, 51, 297, 141], [195, 52, 279, 181]]
Chk 3094 [[92, 107, 229, 220], [202, 105, 389, 213]]
Chk 3095 [[170, 124, 242, 255], [248, 95, 380, 235], [118, 78, 244, 240]]
Chk 3097 [[126, 151, 329, 461], [26, 163, 228, 473]]
Chk 3098 [[11, 42, 54, 193], [62, 23, 156, 199], [272, 31, 373, 238]]
Chk 3099 [[274, 145, 343, 304], [92, 142, 155, 303], [205, 149, 249, 306]]
Chk 3100 [[132, 98, 214, 325], [305, 100, 378, 336], [212, 98, 255, 293], [353, 73, 435, 355]]
Chk 3102 [[0, 35, 271, 332], [211, 36, 500, 332]]
Chk 3103 [[66, 88, 202, 331], [287, 80, 411, 331], [193, 135, 244, 280], [243, 141, 288, 267]]
Chk 3104 [[69, 78, 218, 375], [233, 32, 407, 375]]
Chk 3105 [[76, 100, 366, 387], [0, 0, 270, 397]]
Chk 3106 [[269, 73, 467, 250], [39, 88, 159, 256]]
Chk 3107 [[121, 87, 294, 500], [45, 98, 169, 500]]
Chk 3108 [[269, 134, 361, 266], [121, 164, 217, 295], [247, 23, 369, 282]]
Chk 3109 [[68, 31, 294, 359], [281, 47, 493, 359]]
Chk 3111 [[353, 17, 499, 299], [242, 84, 396, 285], [106, 123, 241, 272]]
Chk 3112 [[72, 97, 229, 333], [140, 78, 444, 333]]
Chk 3113 [[254, 39, 432, 280], [51, 61, 184, 280], [162, 58, 261, 280]]
Chk 3114 [[192, 171, 227, 254], [111, 180, 168, 322], [316, 172, 383, 321], [281, 171, 319, 270], [134, 199, 180, 303]]
Chk 3115 [[342, 87, 392, 164], [290, 96, 339, 210]]
Chk 3117 [[178, 142, 295, 377], [142, 42, 226, 375], [8, 105, 167, 422], [0, 44, 130, 190]]
Chk 3118 [[238, 64, 387, 371], [96, 44, 266, 369]]
Chk 3120 [[112, 61, 313, 334], [246, 77, 462, 334]]
Chk 3121 [[212, 46, 473, 332], [33, 43, 345, 332]]
Chk 3122 [[173, 154, 235, 263], [247, 137, 308, 275], [306, 132, 355, 271]]
Chk 3123 [[254, 29, 386, 270], [134, 52, 313, 316]]
Chk 3124 [[0, 52, 188, 369], [228, 48, 436, 317]]
Chk 3125 [[340, 95, 496, 329], [318, 43, 398, 209], [207, 57, 320, 213], [0, 53, 89, 189], [7, 70, 226, 316]]
Chk 3126 [[0, 71, 261, 493], [115, 85, 364, 495]]
Chk 3127 [[118, 64, 195, 287], [295, 56, 384, 277]]
Chk 3128 [[0, 17, 105, 345], [97, 103, 249, 355], [314, 119, 433, 314]]
Chk 3130 [[98, 85, 217, 298], [240, 71, 346, 270]]
Chk 3132 [[88, 172, 183, 500], [147, 116, 234, 500], [290, 172, 332, 395]]
Chk 3133 [[119, 100, 377, 332], [64, 131, 239, 330]]
Chk 3134 [[255, 188, 409, 439], [0, 172, 219, 415]]
Chk 3135 [[31, 57, 229, 332], [206, 30, 380, 323]]
Chk 3136 [[142, 144, 274, 333], [115, 3, 397, 310]]
Chk 3137 [[237, 48, 494, 329], [0, 0, 203, 332]]
Chk 3139 [[138, 40, 246, 249], [307, 68, 450, 372], [418, 28, 478, 247]]
Chk 3140 [[98, 22, 276, 328], [326, 12, 414, 299], [363, 21, 500, 328]]
Chk 3141 [[293, 56, 449, 332], [36, 108, 164, 332]]
Chk 3142 [[8, 24, 279, 400], [397, 209, 500, 365], [221, 137, 492, 400]]
Chk 3143 [[63, 38, 205, 371], [101, 114, 200, 254]]
Chk 3144 [[249, 165, 292, 302], [406, 152, 459, 309], [452, 147, 499, 322]]

Chk 3146 [[283, 25, 499, 332], [105, 5, 326, 329], [0, 141, 91, 289], [44, 194, 107, 270]]
Chk 3147 [[35, 32, 221, 365], [151, 67, 288, 360], [73, 16, 221, 361], [0, 60, 37, 355]]
Chk 3148 [[298, 55, 412, 262], [94, 69, 226, 310]]
Chk 3150 [[31, 19, 269, 480], [123, 11, 291, 478]]
Chk 3152 [[13, 72, 188, 336], [62, 10, 174, 249]]
Chk 3153 [[0, 45, 139, 217], [80, 45, 193, 217], [248, 79, 329, 217], [363, 19, 483, 217]]
Chk 3154 [[77, 70, 209, 372], [275, 32, 443, 378]]
Chk 3155 [[25, 226, 74, 304], [101, 112, 224, 302], [180, 120, 328, 265]]
Chk 3156 [[14, 110, 174, 397], [249, 61, 459, 391], [443, 314, 491, 368]]
Chk 3157 [[36, 98, 66, 158], [54, 88, 126, 269], [125, 85, 187, 258], [206, 64, 265, 269], [239, 103, 421, 375]]
Chk 3158 [[228, 40, 435, 256], [0, 46, 136, 332]]
Chk 3160 [[47, 79, 161, 320], [139, 50, 253, 332], [236, 43, 328, 332], [352, 59, 404, 163], [382, 62, 430, 157], [411, 56, 454, 155]]
Chk 3161 [[15, 138, 89, 302], [74, 107, 187, 333], [215, 129, 326, 333], [371, 138, 424, 312], [413, 128, 480, 295], [476, 152, 500, 234]]
Chk 3162 [[253, 157, 314, 256], [326, 133, 373, 263], [378, 123, 408, 183], [204, 93, 233, 159], [232, 84, 264, 166], [353, 120, 378, 187]]
Chk 3164 [[19, 59, 135, 319], [171, 45, 283, 425]]
Chk 3165 [[0, 96, 123, 333], [217, 112, 276, 176], [342, 70, 411, 182], [398, 56, 490, 181]]
Chk 3166 [[175, 51, 260, 375], [242, 72, 326, 367]]
Chk 3168 [[0, 154, 286, 492], [164, 0, 374, 499]]
Chk 3169 [[0, 97, 189, 332], [274, 154, 474, 332], [146, 46, 336, 312]]
Chk 3170 [[241, 95, 356, 286], [318, 112, 436, 310]]
Chk 3172 [[420, 122, 500, 239], [134, 76, 332, 400], [22, 80, 158, 400]]
Chk 3173 [[293, 160, 336, 283], [76, 210, 173, 331], [109, 214, 248, 332], [251, 172, 292, 258]]
Chk 3174 [[241, 123, 499, 374], [54, 81, 279, 366]]
Chk 3176 [[378, 119, 500, 362], [120, 125, 222, 371], [0, 154, 89, 375], [4, 149, 95, 375]]
Chk 3177 [[8, 176, 179, 327], [428, 265, 494, 332], [167, 129, 295, 332], [303, 275, 363, 324], [383, 271, 436, 332]]
Chk 3178 [[69, 111, 213, 314], [181, 94, 333, 460]]
Chk 3179 [[99, 86, 172, 374], [266, 75, 338, 347], [196, 64, 269, 327]]
Chk 3181 [[88, 45, 191, 293], [183, 160, 279, 277]]
Chk 3182 [[32, 184, 107, 266], [152, 178, 232, 276]]
Chk 3183 [[165, 148, 232, 225], [253, 129, 315, 225], [298, 229, 334, 307]]
Chk 3184 [[3, 115, 212, 375], [96, 117, 283, 375], [169, 98, 375, 375], [417, 97, 500, 375]]
Chk 3186 [[222, 114, 330, 457], [93, 136, 253, 470]]
Chk 3188 [[94, 243, 185, 499], [208, 271, 275, 499]]
Chk 3189 [[348, 81, 416, 298], [71, 93, 142, 322], [123, 65, 180, 309]]
Chk 3190 [[161, 57, 332, 499], [30, 142, 192, 499]]
Chk 3192 [[314, 60, 499, 332], [247, 115, 282, 207], [128, 100, 292, 309], [24, 44, 193, 321], [1, 213, 29, 302], [0, 108, 19, 212]]
Chk 3193 [[39, 63, 346, 295], [121, 59, 349, 272]]
Chk 3194 [[278, 69, 420, 217], [69, 0, 170, 143], [387, 49, 499, 296]]
Chk 3195 [[95, 244, 173, 394], [144, 255, 248, 436]]
Chk 3196 [[215, 120, 300, 402], [152, 128, 242, 428]]
Chk 3197 [[244, 21, 499, 323], [12, 94, 218, 320], [156, 91, 328, 312]]
Chk 3198 [[391, 38, 475, 272], [228, 120, 433, 336], [137, 113, 237, 275], [78, 95, 166, 219], [17, 93, 96, 201], [0, 91, 28, 188]]
Chk 3199 [[182, 222, 214, 317], [114, 221, 146, 332], [38, 234, 86, 324]]
Chk 3201 [[0, 97, 220, 333], [124, 32, 289, 301], [373, 142, 477, 271], [428, 191, 500, 309]]
Chk 3202 [[192, 134, 311, 330], [31, 116, 194, 330]]
Chk 3203 [[40, 188, 309, 474], [114, 79, 234, 231]]
Chk 3204 [[324, 85, 393, 201], [98, 66, 240, 208]]
Chk 3205 [[37, 167, 137, 306], [95, 163, 210, 296], [323, 23, 382, 233], [356, 44, 426, 237], [407, 29, 477, 222]]
Chk 3206 [[253, 101, 374, 216], [4, 139, 135, 368], [385, 112, 489, 337], [83, 112, 204, 336], [450, 39, 499, 136]]
Chk 3207 [[0, 70, 172, 270], [286, 35, 500, 268]]
Chk 3208 [[301, 50, 492, 320], [21, 107, 262, 354]]
Chk 3209 [[158, 146, 334, 312], [343, 126, 489, 282], [444, 95, 495, 252]]
Chk 3211 [[115, 77, 330, 333], [137, 79, 337, 327]]
Chk 3212 [[111, 42, 168, 199], [175, 36, 273, 194], [193, 100, 314, 310]]
Chk 3214 [[62, 92, 162, 269], [122, 133, 216, 261]]
Chk 3215 [[0, 0, 294, 375], [150, 0, 280, 212], [310, 12, 492, 329]]
Chk 3216 [[263, 44, 404, 374], [114, 63, 306, 374]]
Chk 3218 [[205, 4, 459, 330], [92, 66, 294, 332]]
Chk 3219 [[121, 96, 200, 281], [254, 115, 327, 291], [303, 108, 373, 290]]
Chk 3220 [[327, 0, 499, 320], [107, 38, 391, 332]]
Chk 3223 [[370, 174, 427, 335], [133, 172, 214, 331], [295, 171, 367, 333]]
Chk 3224 [[238, 6, 484, 333], [16, 220, 327, 332]]
Chk 3225 [[64, 27, 234, 335], [305, 93, 388, 320]]
Chk 3226 [[109, 156, 249, 318], [456, 16, 498, 148], [259, 58, 335, 177]]
Chk 3227 [[47, 77, 108, 297], [126, 40, 206, 269]]
Chk 3228 [[321, 6, 371, 138], [13, 27, 144, 298], [153, 37, 276, 271], [0, 28, 26, 169]]
Chk 3229 [[229, 110, 285, 236], [305, 91, 364, 222]]
Chk 3230 [[188, 136, 220, 172], [245, 145, 301, 203]]
Chk 3231 [[46, 91, 181, 499], [190, 222, 266, 436], [103, 308, 176, 488]]
Chk 3232 [[117, 96, 219, 359], [208, 80, 261, 292], [238, 74, 346, 432], [280, 177, 382, 454]]
Chk 3235 [[235, 304, 330, 492], [112, 221, 208, 478], [176, 246, 260, 398], [139, 209, 190, 316]]
Chk 3236 [[77, 159, 108, 250], [141, 152, 174, 254]]
Chk 3237 [[62, 219, 122, 374], [129, 218, 172, 374], [0, 224, 38, 374]]
Chk 3238 [[38, 35, 236, 371], [118, 65, 425, 375]]
Chk 3239 [[5, 59, 219, 336], [221, 20, 469, 335]]
Chk 3240 [[318, 153, 396, 331], [0, 161, 121, 375], [80, 222, 190, 375]]
Chk 3241 [[261, 154, 344, 270], [134, 102, 215, 299], [204, 156, 257, 273]]
Chk 3243 [[177, 36, 322, 202], [371, 50, 447, 217]]
Chk 3244 [[42, 45, 159, 256], [162, 91, 235, 256], [257, 163, 325, 247], [365, 71, 477, 265], [467, 153, 500, 263]]
Chk 3245 [[17, 9, 238, 458], [152, 129, 309, 485]]
Chk 3246 [[58, 232, 150, 495], [284, 230, 332, 332], [133, 215, 217, 485]]
Chk 3247 [[0, 183, 137, 375], [0, 129, 109, 254], [112, 125, 227, 239], [190, 45, 321, 214], [220, 133, 365, 351]]
Chk 3249 [[110, 58, 443, 374], [63, 152, 250, 354]]
Chk 3250 [[211, 106, 363, 375], [163, 179, 298, 375]]
Chk 3251 [[193, 124, 275, 270], [216, 114, 334, 261], [389, 101, 405, 131]]
Chk 3252 [[277, 118, 429, 331], [396, 149, 491, 302]]
Chk 3253 [[134, 293, 191, 470], [22, 261, 68, 408], [179, 241, 270, 479]]
Chk 3254 [[39, 69, 201, 451], [179, 104, 290, 452]]
Chk 3255 [[60, 33, 208, 432], [205, 42, 318, 495]]
Chk 3257 [[97, 7, 369, 375], [0, 121, 113, 499]]
Chk 3258 [[3, 28, 244, 328], [361, 20, 499, 324], [340, 77, 360, 146], [359, 59, 389, 154], [111, 90, 147, 148]]
Chk 3259 [[7, 62, 297, 500], [245, 32, 375, 500]]
Chk 3261 [[13, 43, 176, 333], [365, 46, 455, 319]]
Chk 3262 [[0, 102, 183, 339], [304, 16, 500, 375]]
Chk 3263 [[91, 4, 333, 492], [14, 72, 206, 499]]
Chk 3264 [[190, 246, 236, 360], [147, 245, 185, 357], [315, 253, 351, 336], [278, 253, 310, 353]]
Chk 3265 [[86, 27, 216, 333], [237, 53, 413, 333]]
Chk 3266 [[306, 283, 375, 360], [65, 291, 234, 383]]
Chk 3267 [[0, 52, 179, 333], [226, 115, 347, 333], [320, 0, 498, 333]]
Chk 3268 [[0, 45, 206, 375], [400, 17, 500, 226], [209, 5, 399, 371]]
Chk 3269 [[15, 52, 222, 456], [234, 0, 488, 456]]
Chk 3270 [[138, 41, 409, 448], [0, 35, 227, 409], [181, 0, 330, 167]]
Chk 3271 [[257, 66, 315, 219], [127, 43, 200, 252], [331, 67, 383, 220], [105, 50, 153, 230]]
Chk 3272 [[259, 27, 367, 414], [209, 43, 299, 182], [70, 32, 243, 326]]
Chk 3273 [[296, 64, 500, 273], [4, 48, 218, 286], [209, 0, 314, 240], [95, 16, 128, 62], [79, 27, 102, 57], [38, 21, 62, 54], [48, 30, 90, 79], [0, 22, 37, 103]]
Chk 3274 [[132, 42, 221, 342], [256, 69, 329, 336]]
Chk 3275 [[50, 118, 160, 321], [260, 121, 375, 319]]
Chk 3276 [[239, 186, 275, 280], [180, 199, 210, 272]]
Chk 3277 [[376, 229, 497, 332], [334, 94, 498, 294], [208, 116, 334, 250], [95, 86, 224, 246]]
Chk 3278 [[105, 137, 329, 375], [331, 4, 484, 375], [0, 127, 153, 375], [297, 115, 379, 244], [215, 103, 293, 199]]
Chk 3279 [[338, 137, 397, 335], [368, 119, 498, 335]]
Chk 3280 [[17, 142, 183, 500], [107, 124, 333, 500]]
Chk 3281 [[84, 56, 309, 290], [323, 94, 500, 375]]
Chk 3283 [[128, 151, 260, 360], [195, 52, 421, 360]]
Chk 3284 [[73, 139, 170, 482], [171, 141, 272, 466], [242, 123, 332, 493]]
Chk 3285 [[121, 132, 307, 499], [25, 42, 263, 435]]
Chk 3286 [[395, 142, 500, 357], [172, 31, 369, 357], [0, 43, 164, 357]]
Chk 3287 [[82, 96, 483, 333], [111, 89, 494, 333]]
Chk 3288 [[102, 71, 199, 347], [200, 72, 295, 374], [305, 17, 411, 374]]
Chk 3289 [[101, 31, 265, 287], [244, 32, 420, 288], [84, 86, 121, 213], [338, 64, 433, 278], [93, 81, 131, 144]]
Chk 3290 [[284, 121, 324, 261], [299, 98, 388, 329], [13, 53, 146, 323]]
Chk 3291 [[252, 68, 439, 367], [65, 77, 178, 374]]

Chk 3292 [[42, 200, 198, 375], [188, 143, 399, 375], [350, 189, 460, 344]]
Chk 3293 [[195, 25, 331, 466], [19, 129, 144, 331]]
Chk 3294 [[45, 149, 169, 393], [18, 55, 126, 327], [110, 65, 198, 268]]
Chk 3296 [[146, 101, 287, 333], [12, 58, 117, 333], [272, 124, 359, 328], [351, 134, 482, 325]]
Chk 3297 [[28, 19, 276, 326], [308, 28, 500, 326]]
Chk 3298 [[305, 93, 469, 375], [102, 152, 230, 366], [0, 158, 123, 375], [0, 153, 28, 252]]
Chk 3299 [[32, 32, 117, 280], [0, 48, 43, 196], [148, 39, 240, 272], [326, 82, 383, 174], [338, 22, 430, 280]]
Chk 3300 [[264, 81, 496, 266], [73, 56, 238, 271]]
Chk 3301 [[143, 170, 186, 289], [297, 91, 362, 298], [174, 88, 247, 288]]
Chk 3303 [[85, 66, 314, 460], [46, 203, 249, 492]]
Chk 3304 [[52, 35, 141, 244], [124, 37, 227, 236]]
Chk 3305 [[196, 49, 499, 405], [1, 6, 295, 405]]
Chk 3306 [[2, 193, 35, 239], [24, 183, 56, 251], [277, 149, 364, 395], [416, 132, 474, 371], [373, 146, 442, 367]]
Chk 3308 [[308, 50, 492, 332], [53, 77, 275, 319]]
Chk 3309 [[0, 95, 201, 332], [94, 22, 467, 332]]
Chk 3310 [[180, 141, 272, 332], [94, 122, 189, 332], [356, 107, 442, 332], [293, 133, 393, 332]]
Chk 3311 [[308, 79, 408, 292], [406, 86, 479, 299], [245, 74, 308, 307], [95, 103, 128, 183], [10, 80, 56, 198]]
Chk 3312 [[259, 3, 395, 372], [134, 0, 299, 357], [58, 41, 99, 154], [30, 42, 77, 153], [0, 35, 47, 157]]
Chk 3313 [[186, 90, 330, 222], [61, 100, 147, 207]]
Chk 3314 [[338, 60, 499, 332], [156, 25, 343, 332], [6, 57, 167, 309]]
Chk 3315 [[268, 16, 404, 191], [214, 162, 242, 196], [208, 141, 228, 174]]
Chk 3318 [[95, 122, 190, 374], [298, 85, 412, 374], [193, 109, 304, 371], [220, 103, 261, 148]]
Chk 3320 [[0, 79, 279, 368], [184, 139, 453, 374], [395, 110, 499, 367]]
Chk 3321 [[51, 91, 208, 428], [201, 36, 392, 500], [191, 94, 267, 282]]
Chk 3322 [[153, 103, 210, 236], [105, 110, 167, 248], [231, 264, 304, 425], [116, 252, 224, 434], [125, 257, 225, 435]]
Chk 3323 [[165, 7, 375, 467], [248, 117, 353, 263], [166, 103, 261, 243], [0, 100, 277, 500]]
Chk 3324 [[79, 0, 216, 469], [163, 86, 326, 482], [295, 80, 358, 414]]
Chk 3328 [[220, 86, 343, 232], [87, 131, 241, 332]]
Chk 3330 [[14, 56, 308, 492], [21, 51, 276, 485]]
Chk 3333 [[4, 73, 81, 317], [124, 77, 212, 332], [350, 42, 437, 330], [280, 89, 317, 168], [223, 108, 257, 185], [315, 107, 364, 193]]
Chk 3334 [[63, 128, 152, 432], [190, 78, 330, 321], [28, 132, 54, 176], [129, 129, 324, 434]]
Chk 3335 [[54, 79, 349, 500], [0, 171, 178, 500]]
Chk 3336 [[350, 181, 372, 217], [70, 165, 160, 414], [128, 58, 292, 472]]
Chk 3337 [[53, 31, 302, 332], [194, 14, 432, 332]]
Chk 3338 [[223, 0, 479, 331], [18, 29, 308, 328]]
Chk 3339 [[248, 128, 376, 374], [25, 133, 185, 370]]
Chk 3340 [[107, 188, 161, 269], [183, 178, 287, 331], [329, 188, 374, 256], [474, 198, 498, 260]]
Chk 3341 [[63, 163, 271, 499], [196, 66, 419, 499]]
Chk 3342 [[297, 115, 479, 333], [175, 93, 345, 265], [101, 90, 282, 333]]
Chk 3343 [[188, 139, 265, 303], [124, 107, 187, 199]]
Chk 3346 [[186, 141, 288, 259], [286, 75, 386, 286], [136, 79, 214, 247], [43, 138, 141, 270], [342, 132, 445, 329]]
Chk 3347 [[66, 77, 214, 330], [247, 95, 334, 211]]
Chk 3348 [[165, 10, 286, 335], [305, 124, 394, 304]]
Chk 3352 [[195, 147, 268, 267], [373, 137, 442, 316], [54, 131, 103, 289], [307, 124, 362, 267]]
Chk 3353 [[224, 43, 499, 332], [44, 27, 356, 332]]
Chk 3354 [[70, 95, 354, 314], [338, 46, 449, 288]]
Chk 3355 [[53, 44, 245, 302], [290, 71, 447, 303], [266, 106, 381, 247]]
Chk 3356 [[64, 95, 231, 400], [163, 126, 319, 400]]
Chk 3357 [[44, 35, 150, 309], [224, 36, 321, 195]]
Chk 3359 [[294, 124, 384, 330], [1, 104, 121, 257], [164, 138, 275, 313]]
Chk 3360 [[0, 20, 120, 328], [139, 44, 237, 328], [198, 32, 331, 328], [326, 13, 500, 328]]
Chk 3361 [[71, 50, 148, 257], [159, 71, 309, 349]]
Chk 3362 [[165, 214, 280, 366], [0, 210, 140, 352], [346, 101, 442, 364], [282, 202, 428, 370]]
Chk 3365 [[183, 41, 318, 500], [17, 174, 192, 500]]
Chk 3366 [[130, 37, 496, 333], [117, 34, 459, 333]]
Chk 3367 [[2, 17, 138, 433], [128, 32, 387, 414]]
Chk 3368 [[298, 41, 491, 358], [22, 15, 165, 361], [143, 25, 200, 125], [320, 16, 422, 202]]
Chk 3369 [[152, 41, 298, 263], [62, 45, 189, 226]]
Chk 3370 [[141, 120, 164, 149], [243, 118, 266, 154], [212, 122, 234, 165]]
Chk 3371 [[72, 86, 138, 276], [351, 94, 404, 233]]
Chk 3372 [[0, 38, 169, 500], [136, 69, 379, 412]]
Chk 3373 [[63, 78, 191, 441], [133, 53, 241, 434]]
Chk 3374 [[331, 101, 405, 354], [83, 79, 210, 414]]
Chk 3375 [[282, 90, 394, 316], [189, 95, 273, 266]]
Chk 3376 [[11, 100, 160, 245], [259, 68, 294, 123], [415, 82, 499, 221], [299, 70, 367, 160], [383, 66, 425, 131], [151, 67, 246, 217], [100, 73, 155, 145]]
Chk 3377 [[12, 26, 235, 330], [239, 85, 410, 332], [325, 77, 474, 310]]
Chk 3378 [[0, 101, 97, 306], [148, 114, 219, 216], [375, 76, 452, 321], [208, 130, 299, 206], [330, 84, 401, 256], [471, 88, 500, 184]]
Chk 3380 [[323, 117, 477, 374], [21, 112, 172, 365]]
Chk 3381 [[0, 30, 142, 333], [46, 100, 354, 333]]
Chk 3382 [[288, 148, 439, 499], [216, 92, 343, 461], [57, 416, 199, 494]]
Chk 3384 [[0, 2, 164, 196], [192, 12, 373, 258]]
Chk 3385 [[92, 95, 264, 333], [222, 83, 379, 333], [410, 83, 500, 333], [9, 96, 80, 289], [62, 107, 104, 229]]
Chk 3386 [[142, 44, 242, 270], [12, 32, 127, 303], [344, 1, 382, 50], [181, 1, 216, 45], [90, 6, 124, 40], [252, 10, 290, 57]]
Chk 3387 [[183, 34, 462, 261], [334, 33, 459, 209]]
Chk 3388 [[158, 47, 243, 307], [215, 77, 294, 312]]
Chk 3389 [[281, 113, 398, 375], [212, 143, 298, 375], [114, 134, 211, 375]]
Chk 3390 [[0, 110, 161, 404], [134, 29, 342, 393]]
Chk 3392 [[84, 0, 209, 332], [199, 0, 309, 332], [314, 111, 385, 192]]
Chk 3394 [[44, 286, 194, 500], [178, 57, 392, 500], [372, 330, 399, 454]]
Chk 3395 [[40, 10, 208, 259], [307, 0, 500, 334]]
Chk 3396 [[63, 48, 178, 374], [181, 77, 302, 308], [237, 85, 345, 297]]
Chk 3397 [[197, 36, 498, 374], [0, 56, 267, 374]]
Chk 3398 [[313, 145, 400, 364], [18, 128, 103, 373]]
Chk 3399 [[12, 148, 476, 324], [42, 50, 251, 307]]
Chk 3401 [[357, 31, 452, 262], [23, 29, 142, 287]]
Chk 3402 [[228, 119, 315, 424], [5, 127, 74, 411], [17, 121, 93, 410]]
Chk 3403 [[9, 70, 145, 432], [116, 73, 232, 426]]
Chk 3404 [[188, 21, 474, 499], [3, 5, 259, 485]]
Chk 3407 [[127, 10, 257, 418], [55, 25, 175, 417]]
Chk 3408 [[66, 79, 228, 333], [321, 33, 500, 252], [129, 130, 243, 294]]
Chk 3409 [[94, 109, 247, 372], [278, 104, 486, 373]]
Chk 3410 [[97, 38, 220, 333], [158, 103, 336, 333]]
Chk 3413 [[292, 193, 337, 332], [93, 214, 129, 332], [186, 212, 252, 332], [352, 226, 395, 276], [56, 225, 78, 281], [148, 81, 170, 126], [1, 231, 21, 275]]
Chk 3414 [[20, 77, 100, 241], [406, 75, 471, 285], [136, 102, 207, 276], [246, 88, 329, 291]]
Chk 3415 [[15, 15, 115, 374], [219, 62, 330, 370]]
Chk 3416 [[226, 38, 500, 375], [0, 38, 270, 375]]
Chk 3417 [[240, 34, 422, 333], [75, 31, 249, 333], [0, 67, 103, 333], [53, 68, 131, 333]]
Chk 3418 [[64, 56, 340, 374], [191, 97, 488, 358]]
Chk 3419 [[85, 76, 313, 362], [227, 140, 403, 329]]
Chk 3420 [[6, 200, 108, 323], [292, 156, 360, 294], [393, 171, 484, 334]]
Chk 3421 [[9, 12, 126, 322], [67, 0, 218, 333], [286, 10, 439, 333], [207, 34, 330, 333], [209, 17, 336, 302]]
Chk 3422 [[13, 130, 188, 329], [216, 101, 337, 331], [268, 130, 490, 330]]
Chk 3424 [[158, 63, 272, 257], [51, 139, 168, 265]]
Chk 3425 [[154, 100, 333, 500], [56, 259, 245, 477]]
Chk 3426 [[105, 114, 240, 278], [231, 130, 333, 342], [313, 133, 421, 328]]
Chk 3428 [[253, 184, 310, 368], [150, 187, 198, 359]]
Chk 3430 [[238, 94, 464, 373], [5, 115, 279, 374], [193, 159, 235, 215]]
Chk 3432 [[370, 99, 452, 329], [172, 105, 255, 331], [238, 226, 299, 324]]
Chk 3433 [[170, 113, 337, 332], [16, 79, 170, 332]]
Chk 3434 [[111, 42, 362, 494], [24, 34, 215, 490]]
Chk 3435 [[303, 97, 499, 373], [25, 65, 232, 374]]
Chk 3436 [[0, 102, 173, 340], [118, 125, 249, 267], [125, 129, 253, 274], [239, 68, 423, 340]]
Chk 3437 [[94, 77, 250, 333], [203, 61, 317, 261], [257, 55, 465, 333]]
Chk 3438 [[4, 168, 243, 499], [90, 16, 265, 449], [0, 69, 39, 239], [292, 108, 332, 226]]
Chk 3439 [[145, 142, 200, 229], [339, 101, 411, 268]]
Chk 3440 [[197, 112, 302, 239], [290, 120, 383, 218]]
Chk 3441 [[30, 17, 269, 372], [256, 142, 386, 375], [420, 83, 500, 375]]
Chk 3442 [[22, 62, 239, 352], [187, 103, 480, 352]]
Chk 3443 [[296, 125, 375, 397], [104, 131, 186, 406], [164, 68, 290, 500], [0, 32, 132, 500]]
Chk 3444 [[167, 74, 330, 289], [226, 64, 474, 318]]
Chk 3445 [[298, 75, 392, 233], [189, 75, 267, 235]]
Chk 3446 [[180, 135, 299, 290], [257, 125, 421, 348]]
Chk 3447 [[191, 142, 357, 500], [319, 176, 357, 237], [129, 109, 276, 500], [0, 105, 161, 500]]
Chk 3450 [[307, 26, 461, 319], [84, 77, 201, 243], [185, 204, 256, 299]]
Chk 3451 [[301, 4, 499, 286], [0, 69, 133, 280], [189, 159, 280, 268], [174, 36, 317, 266]]
Chk 3453 [[318, 68, 432, 199], [0, 28, 201, 346], [175, 73, 275, 257], [406, 29, 499, 280], [105, 67, 221, 271]]

Chk 3454 [[0, 146, 129, 300], [167, 125, 298, 334], [273, 104, 500, 334]]
Chk 3455 [[290, 177, 370, 473], [343, 159, 453, 500]]
Chk 3456 [[193, 239, 285, 479], [38, 162, 177, 494]]
Chk 3457 [[308, 8, 386, 324], [151, 18, 287, 324], [103, 3, 173, 317], [289, 67, 327, 152]]
Chk 3458 [[68, 13, 223, 331], [296, 73, 410, 322]]
Chk 3460 [[453, 122, 499, 296], [291, 125, 454, 375], [228, 127, 279, 189], [178, 91, 254, 190], [135, 92, 259, 265], [52, 135, 106, 270]]
Chk 3461 [[289, 72, 389, 298], [188, 65, 263, 291], [13, 140, 50, 195], [31, 80, 81, 252]]
Chk 3463 [[145, 41, 400, 369], [82, 34, 205, 351]]
Chk 3464 [[164, 72, 499, 372], [1, 114, 176, 324]]
Chk 3465 [[5, 73, 156, 332], [372, 75, 499, 332], [203, 100, 429, 332]]
Chk 3466 [[86, 119, 168, 327], [319, 114, 409, 246], [15, 145, 55, 277], [265, 142, 309, 216], [58, 130, 87, 205], [235, 146, 260, 194]]
Chk 3467 [[288, 127, 343, 269], [69, 88, 148, 331], [388, 78, 441, 232]]
Chk 3468 [[0, 79, 194, 366], [108, 58, 299, 309], [366, 66, 500, 269], [327, 0, 410, 180]]
Chk 3469 [[174, 32, 302, 302], [299, 84, 374, 210]]
Chk 3470 [[350, 35, 464, 197], [237, 32, 339, 202], [107, 36, 246, 301], [7, 39, 161, 324]]
Chk 3471 [[8, 166, 199, 388], [73, 53, 280, 406]]
Chk 3472 [[207, 83, 366, 229], [346, 77, 498, 242], [57, 76, 204, 209]]
Chk 3473 [[51, 147, 189, 360], [182, 196, 264, 370], [211, 339, 332, 500]]
Chk 3475 [[25, 75, 186, 304], [295, 89, 420, 201], [467, 180, 500, 268], [30, 212, 48, 261]]
Chk 3477 [[0, 21, 136, 334], [190, 13, 277, 214], [142, 36, 183, 108], [362, 18, 483, 326]]
Chk 3478 [[34, 21, 220, 348], [298, 46, 481, 348]]
Chk 3479 [[251, 112, 318, 294], [121, 94, 191, 242], [115, 94, 151, 220]]
Chk 3480 [[5, 97, 66, 271], [370, 42, 467, 321]]
Chk 3481 [[210, 68, 296, 352], [22, 61, 132, 344], [394, 109, 466, 196], [290, 62, 374, 171], [1, 65, 73, 321]]
Chk 3483 [[208, 172, 259, 277], [304, 152, 364, 288], [418, 115, 452, 197], [449, 139, 472, 196]]
Chk 3484 [[280, 27, 499, 324], [18, 14, 271, 314]]
Chk 3485 [[83, 33, 207, 314], [241, 34, 401, 318], [0, 44, 46, 313], [51, 72, 85, 218], [179, 84, 234, 284], [386, 93, 415, 188]]
Chk 3486 [[119, 119, 311, 302], [280, 92, 489, 319]]
Chk 3487 [[49, 123, 204, 374], [250, 113, 308, 291], [322, 124, 405, 315]]
Chk 3490 [[21, 59, 126, 332], [211, 32, 320, 332], [381, 63, 484, 332], [431, 23, 500, 266], [0, 91, 39, 270]]
Chk 3491 [[246, 49, 493, 374], [0, 0, 257, 357]]
Chk 3493 [[279, 3, 443, 282], [106, 29, 234, 278]]
Chk 3494 [[303, 47, 439, 253], [180, 31, 317, 255]]
Chk 3495 [[276, 40, 440, 236], [15, 29, 233, 332]]
Chk 3496 [[240, 25, 304, 155], [293, 48, 337, 129], [212, 60, 464, 316], [132, 49, 232, 173]]
Chk 3497 [[319, 40, 444, 332], [166, 16, 344, 332]]
Chk 3498 [[254, 66, 391, 215], [60, 59, 227, 249]]
Chk 3499 [[227, 13, 362, 373], [9, 52, 138, 372], [159, 94, 240, 181]]
Chk 3500 [[403, 158, 477, 326], [215, 131, 296, 295], [137, 149, 205, 283]]
Chk 3501 [[9, 77, 160, 333], [311, 181, 463, 314]]
Chk 3502 [[239, 156, 383, 335], [243, 112, 385, 297], [168, 60, 254, 361]]
Chk 3503 [[3, 42, 70, 243], [366, 50, 449, 251], [137, 57, 257, 239], [199, 51, 250, 222]]
Chk 3505 [[214, 40, 333, 255], [131, 41, 260, 269], [432, 0, 499, 230], [18, 50, 143, 285], [333, 34, 426, 328]]
Chk 3506 [[148, 105, 186, 219], [105, 277, 285, 447], [53, 263, 141, 346], [43, 141, 102, 282], [23, 156, 65, 290]]
Chk 3508 [[6, 180, 91, 289], [149, 190, 220, 271], [238, 183, 347, 265], [228, 164, 305, 235], [397, 177, 479, 261]]
Chk 3509 [[250, 56, 314, 140], [355, 73, 435, 134]]
Chk 3510 [[386, 142, 484, 304], [42, 68, 207, 295]]
Chk 3511 [[272, 23, 384, 330], [168, 93, 241, 272], [56, 132, 101, 228]]
Chk 3512 [[114, 44, 404, 319], [305, 88, 499, 332], [0, 56, 147, 328]]
Chk 3513 [[166, 27, 458, 333], [0, 3, 289, 333]]
Chk 3514 [[106, 118, 304, 333], [208, 129, 437, 333], [409, 123, 500, 333], [372, 113, 429, 179]]
Chk 3515 [[376, 74, 485, 328], [46, 55, 244, 325], [299, 0, 416, 254]]
Chk 3516 [[246, 16, 483, 306], [30, 63, 201, 313]]
Chk 3517 [[202, 106, 310, 224], [284, 114, 331, 220]]
Chk 3518 [[8, 95, 212, 499], [114, 249, 279, 499], [21, 75, 147, 322]]
Chk 3519 [[42, 64, 207, 261], [305, 70, 480, 288]]
Chk 3520 [[144, 59, 214, 266], [73, 85, 116, 231]]
Chk 3521 [[6, 76, 73, 250], [94, 61, 153, 254], [140, 84, 204, 273], [302, 82, 362, 222], [371, 91, 451, 269]]
Chk 3522 [[225, 199, 302, 440], [165, 252, 204, 418], [72, 226, 131, 421], [117, 231, 146, 359]]
Chk 3523 [[256, 117, 365, 332], [40, 96, 208, 332], [0, 108, 38, 332], [440, 114, 500, 321]]
Chk 3524 [[31, 96, 198, 482], [186, 53, 312, 496]]
Chk 3525 [[5, 98, 104, 320], [131, 15, 387, 333], [244, 26, 500, 333]]
Chk 3527 [[70, 121, 147, 302], [177, 53, 276, 295]]
Chk 3528 [[0, 24, 205, 375], [125, 81, 303, 355], [214, 141, 361, 307], [262, 72, 500, 375]]
Chk 3529 [[2, 121, 138, 324], [121, 96, 246, 246], [280, 113, 489, 316], [257, 115, 381, 243]]
Chk 3531 [[46, 53, 273, 329], [271, 60, 432, 329]]
Chk 3532 [[0, 56, 179, 332], [249, 74, 500, 332], [129, 82, 274, 332], [227, 125, 248, 172], [248, 134, 261, 175]]
Chk 3534 [[69, 82, 196, 477], [142, 81, 311, 479]]
Chk 3535 [[178, 8, 493, 500], [28, 108, 262, 500]]
Chk 3536 [[10, 24, 124, 432], [72, 147, 178, 437], [155, 190, 258, 296], [172, 0, 272, 301], [0, 60, 31, 327], [264, 0, 334, 443], [286, 178, 328, 400], [71, 34, 169, 165]]
Chk 3537 [[110, 21, 240, 356], [329, 0, 476, 345], [13, 0, 58, 40], [303, 9, 364, 174], [357, 0, 388, 71], [266, 4, 292, 27]]
Chk 3538 [[149, 53, 330, 281], [116, 0, 475, 375]]
Chk 3539 [[13, 48, 88, 482], [80, 97, 203, 477], [228, 84, 386, 485], [381, 115, 463, 373]]
Chk 3540 [[37, 105, 183, 354], [333, 144, 437, 305]]
Chk 3541 [[53, 11, 186, 214], [163, 14, 274, 167], [269, 42, 500, 333]]
Chk 3542 [[124, 32, 500, 334], [67, 63, 294, 309]]
Chk 3543 [[190, 102, 284, 325], [351, 134, 404, 231], [7, 80, 129, 320]]
Chk 3544 [[87, 137, 241, 342], [156, 3, 311, 295], [333, 52, 375, 270]]
Chk 3545 [[74, 50, 159, 256], [206, 93, 283, 260]]
Chk 3546 [[64, 78, 275, 394], [25, 91, 171, 478]]
Chk 3547 [[20, 67, 253, 333], [57, 155, 200, 333], [228, 88, 383, 302], [274, 24, 500, 333]]
Chk 3549 [[305, 56, 364, 287], [124, 128, 209, 237]]
Chk 3550 [[247, 98, 312, 242], [86, 173, 210, 438], [74, 165, 202, 429]]
Chk 3551 [[112, 132, 215, 294], [251, 116, 369, 269], [236, 48, 322, 260]]
Chk 3552 [[327, 91, 449, 334], [176, 76, 354, 334], [487, 255, 500, 310], [447, 246, 482, 333]]
Chk 3553 [[17, 37, 161, 331], [10, 24, 146, 331], [111, 44, 235, 331], [239, 70, 500, 331]]
Chk 3554 [[0, 0, 180, 401], [203, 0, 339, 362], [280, 0, 457, 401]]
Chk 3555 [[158, 146, 246, 296], [279, 139, 364, 278]]
Chk 3557 [[27, 162, 180, 375], [182, 78, 317, 368], [295, 89, 391, 341], [385, 148, 483, 344]]
Chk 3558 [[274, 149, 322, 313], [91, 175, 132, 255], [203, 161, 237, 287]]
Chk 3559 [[230, 100, 369, 374], [34, 65, 246, 374]]
Chk 3560 [[41, 86, 148, 325], [124, 43, 256, 413], [183, 56, 333, 499]]
Chk 3561 [[57, 62, 316, 352], [205, 17, 336, 231]]
Chk 3563 [[105, 154, 353, 499], [96, 39, 229, 426]]
Chk 3565 [[217, 71, 343, 365], [12, 86, 150, 370], [447, 146, 499, 316], [330, 117, 440, 310]]
Chk 3566 [[105, 370, 143, 436], [138, 371, 191, 433]]
Chk 3567 [[215, 124, 294, 332], [311, 149, 377, 332]]
Chk 3568 [[415, 79, 499, 374], [4, 100, 139, 372], [176, 108, 282, 262]]
Chk 3569 [[141, 78, 297, 368], [0, 58, 146, 367], [286, 125, 391, 374], [399, 131, 499, 374]]
Chk 3570 [[227, 30, 306, 314], [140, 64, 231, 313]]
Chk 3571 [[3, 129, 171, 445], [282, 70, 333, 419], [147, 44, 276, 347], [134, 53, 175, 140], [234, 43, 285, 113], [269, 42, 308, 160]]
Chk 3572 [[1, 105, 125, 325], [200, 73, 413, 328], [427, 179, 485, 227]]
Chk 3575 [[363, 77, 428, 265], [5, 130, 176, 322]]
Chk 3576 [[289, 25, 476, 274], [21, 25, 164, 271]]
Chk 3577 [[82, 102, 137, 294], [162, 102, 224, 261], [288, 87, 367, 281], [381, 124, 419, 266]]
Chk 3579 [[256, 38, 489, 350], [0, 41, 226, 370], [190, 31, 289, 171]]
Chk 3580 [[16, 40, 223, 375], [188, 48, 492, 375]]
Chk 3581 [[10, 56, 186, 314], [211, 27, 362, 311]]
Chk 3582 [[187, 35, 255, 220], [77, 65, 164, 277], [257, 128, 337, 306], [278, 70, 352, 229]]
Chk 3583 [[317, 90, 454, 251], [209, 81, 344, 203], [73, 121, 258, 333], [16, 90, 99, 292], [432, 0, 453, 52], [399, 0, 432, 54], [371, 0, 401, 59]]
Chk 3584 [[27, 34, 293, 333], [244, 39, 453, 333]]
Chk 3585 [[301, 4, 499, 359], [0, 27, 140, 374]]
Chk 3586 [[178, 174, 258, 478], [0, 177, 193, 500]]
Chk 3587 [[28, 10, 164, 445], [113, 204, 224, 484], [175, 37, 333, 498]]
Chk 3588 [[28, 80, 204, 314], [332, 133, 402, 235], [278, 83, 412, 256]]
Chk 3589 [[306, 87, 500, 333], [342, 55, 473, 196], [188, 11, 392, 255], [61, 79, 348, 333]]
Chk 3590 [[43, 107, 282, 310], [259, 150, 346, 301], [367, 151, 479, 334]]
Chk 3591 [[316, 107, 468, 275], [168, 60, 278, 257], [39, 82, 161, 225]]
Chk 3594 [[203, 98, 355, 298], [17, 130, 42, 177], [330, 131, 493, 357], [202, 112, 258, 248]]
Chk 3595 [[72, 75, 213, 256], [401, 115, 500, 312]]
Chk 3596 [[176, 139, 258, 390], [0, 158, 103, 500]]
Chk 3597 [[290, 12, 492, 365], [13, 32, 208, 236]]

Chk 3600 [[19, 0, 83, 129], [43, 27, 175, 349], [149, 37, 276, 349], [273, 45, 359, 319], [347, 27, 448, 345]]
Chk 3601 [[21, 113, 235, 370], [307, 124, 487, 332]]
Chk 3603 [[293, 71, 499, 364], [0, 160, 197, 364], [169, 11, 186, 56], [369, 11, 389, 71]]
Chk 3604 [[162, 0, 334, 320], [68, 60, 266, 332]]
Chk 3605 [[318, 57, 390, 262], [352, 64, 441, 268]]
Chk 3607 [[14, 218, 190, 500], [168, 244, 283, 500], [264, 339, 375, 500]]
Chk 3608 [[293, 104, 451, 333], [295, 89, 469, 333]]
Chk 3609 [[70, 120, 247, 368], [441, 159, 499, 282], [277, 151, 330, 239]]
Chk 3610 [[15, 0, 428, 333], [146, 124, 305, 292]]
Chk 3611 [[444, 88, 489, 215], [291, 39, 367, 181], [175, 107, 215, 196], [363, 75, 403, 206]]
Chk 3613 [[57, 55, 253, 218], [262, 72, 499, 272]]
Chk 3614 [[33, 52, 191, 314], [287, 78, 496, 335], [230, 116, 300, 197]]
Chk 3615 [[87, 202, 211, 455], [158, 307, 242, 425], [37, 118, 84, 207], [0, 117, 47, 201]]
Chk 3617 [[107, 89, 173, 282], [181, 60, 246, 274], [291, 94, 331, 189], [475, 70, 500, 258]]
Chk 3620 [[23, 62, 132, 333], [311, 51, 432, 335]]
Chk 3621 [[17, 51, 194, 479], [222, 38, 439, 488]]
Chk 3623 [[0, 49, 121, 285], [169, 128, 289, 264], [362, 34, 450, 242]]
Chk 3625 [[163, 260, 337, 432], [164, 171, 374, 500]]
Chk 3626 [[265, 157, 336, 263], [8, 157, 38, 234], [354, 160, 425, 260], [55, 147, 87, 234]]
Chk 3627 [[31, 113, 145, 491], [176, 84, 290, 485]]
Chk 3628 [[64, 147, 138, 332], [132, 144, 201, 332]]
Chk 3629 [[156, 84, 285, 330], [46, 140, 245, 331]]
Chk 3630 [[169, 89, 217, 223], [75, 84, 117, 152], [101, 132, 145, 181], [0, 86, 72, 175], [0, 0, 147, 104], [301, 96, 376, 251], [397, 108, 468, 295]]
Chk 3631 [[230, 131, 267, 252], [437, 134, 493, 280], [74, 92, 119, 202], [112, 76, 142, 186]]
Chk 3632 [[239, 170, 336, 306], [332, 35, 419, 226], [19, 0, 91, 149], [63, 150, 176, 265]]
Chk 3633 [[319, 26, 488, 374], [143, 76, 346, 346]]
Chk 3634 [[115, 121, 272, 332], [345, 159, 404, 310], [330, 132, 500, 332]]
Chk 3636 [[439, 15, 499, 234], [118, 16, 169, 163], [162, 23, 210, 167], [259, 10, 366, 281]]
Chk 3637 [[162, 40, 311, 234], [193, 49, 500, 364]]
Chk 3638 [[252, 9, 381, 218], [1, 2, 235, 310]]
Chk 3639 [[118, 61, 234, 436], [30, 27, 148, 470]]
Chk 3640 [[46, 21, 312, 333], [294, 20, 477, 333]]
Chk 3641 [[132, 179, 189, 316], [228, 216, 317, 359], [232, 320, 403, 475]]
Chk 3642 [[30, 103, 129, 241], [325, 85, 441, 259], [245, 105, 320, 227], [152, 108, 221, 235]]
Chk 3643 [[79, 79, 208, 441], [198, 194, 267, 314]]
Chk 3644 [[101, 173, 134, 273], [383, 165, 419, 290], [236, 216, 288, 297], [314, 166, 352, 278], [283, 214, 332, 302]]
Chk 3646 [[26, 141, 198, 358], [208, 142, 407, 374]]
Chk 3647 [[1, 86, 208, 274], [191, 86, 298, 181], [203, 125, 266, 202]]
Chk 3649 [[7, 8, 270, 309], [193, 0, 497, 309]]
Chk 3650 [[109, 9, 247, 289], [308, 2, 461, 287]]
Chk 3651 [[105, 86, 250, 331], [222, 11, 312, 279], [288, 135, 421, 331]]
Chk 3653 [[250, 131, 293, 270], [206, 125, 266, 273]]
Chk 3654 [[107, 154, 151, 222], [154, 91, 260, 335], [318, 140, 433, 335]]
Chk 3655 [[205, 196, 256, 361], [113, 172, 158, 353]]
Chk 3657 [[33, 26, 225, 335], [158, 82, 243, 281], [244, 59, 448, 335], [0, 73, 44, 325]]
Chk 3659 [[214, 165, 269, 308], [133, 151, 217, 334]]
Chk 3660 [[322, 63, 444, 374], [262, 114, 334, 197], [112, 107, 170, 224], [163, 99, 234, 201]]
Chk 3661 [[120, 95, 321, 499], [79, 199, 148, 422]]
Chk 3662 [[37, 58, 268, 342], [175, 16, 445, 339]]
Chk 3663 [[229, 81, 383, 333], [135, 96, 288, 332]]
Chk 3664 [[0, 2, 152, 332], [250, 46, 458, 332]]
Chk 3665 [[323, 103, 378, 195], [155, 122, 222, 249], [285, 97, 321, 174], [449, 63, 499, 316]]
Chk 3666 [[9, 4, 132, 457], [162, 100, 320, 468]]
Chk 3667 [[408, 110, 475, 321], [346, 94, 425, 335], [289, 177, 348, 264], [268, 197, 389, 342]]
Chk 3668 [[16, 39, 315, 331], [320, 29, 499, 323]]
Chk 3669 [[239, 17, 460, 334], [32, 61, 251, 334]]
Chk 3671 [[96, 38, 187, 326], [198, 54, 269, 331]]
Chk 3673 [[101, 16, 320, 320], [337, 6, 490, 315], [2, 36, 119, 297]]
Chk 3675 [[148, 89, 294, 406], [180, 76, 304, 437]]
Chk 3676 [[163, 183, 422, 332], [171, 90, 366, 274], [164, 61, 291, 178], [0, 119, 130, 297], [76, 94, 170, 180], [353, 95, 395, 165]]
Chk 3677 [[163, 91, 288, 293], [131, 84, 201, 221], [8, 104, 156, 333]]
Chk 3678 [[31, 4, 476, 332], [3, 115, 212, 331]]
Chk 3679 [[143, 17, 323, 500], [0, 46, 192, 445]]
Chk 3680 [[265, 67, 329, 263], [208, 59, 273, 150], [206, 113, 273, 284], [187, 161, 231, 266]]
Chk 3681 [[236, 95, 487, 374], [0, 77, 120, 345], [123, 50, 335, 371], [406, 126, 499, 374]]
Chk 3682 [[294, 108, 500, 375], [315, 66, 418, 214], [93, 89, 233, 219], [0, 52, 84, 149], [0, 99, 272, 375], [253, 49, 342, 143], [457, 70, 500, 178]]
Chk 3683 [[51, 21, 245, 333], [194, 95, 330, 333]]
Chk 3684 [[0, 133, 167, 288], [137, 35, 298, 201], [299, 30, 374, 154]]
Chk 3685 [[371, 209, 488, 335], [280, 197, 365, 335], [140, 72, 298, 317]]
Chk 3686 [[227, 223, 265, 280], [302, 224, 347, 283], [433, 204, 475, 375], [459, 196, 500, 375], [2, 225, 37, 276]]
Chk 3687 [[2, 45, 153, 280], [325, 53, 481, 229], [138, 77, 251, 229], [114, 99, 161, 155]]
Chk 3688 [[73, 178, 196, 313], [283, 179, 373, 301]]
Chk 3689 [[96, 86, 301, 374], [203, 0, 442, 367]]
Chk 3690 [[6, 320, 230, 499], [266, 139, 499, 499], [104, 15, 354, 499], [359, 0, 499, 161], [464, 172, 499, 265]]
Chk 3691 [[106, 104, 250, 331], [273, 106, 459, 324], [36, 133, 82, 180]]
Chk 3693 [[8, 56, 61, 231], [129, 74, 199, 268], [242, 87, 300, 224], [357, 65, 405, 194], [37, 67, 94, 187]]
Chk 3694 [[1, 41, 255, 375], [159, 82, 409, 375]]
Chk 3695 [[40, 4, 284, 334], [247, 51, 485, 334], [262, 147, 310, 194], [27, 117, 139, 285], [386, 133, 440, 194], [471, 181, 500, 329]]
Chk 3696 [[0, 72, 126, 332], [174, 48, 324, 332], [155, 76, 223, 280]]
Chk 3697 [[76, 178, 104, 272], [358, 118, 399, 208], [115, 159, 144, 276]]
Chk 3698 [[44, 61, 311, 499], [207, 62, 342, 397]]
Chk 3699 [[17, 92, 139, 357], [412, 75, 499, 357], [260, 75, 371, 357], [134, 88, 235, 357]]
Chk 3700 [[226, 168, 292, 249], [78, 121, 136, 225], [0, 179, 60, 370], [0, 136, 66, 212], [114, 148, 223, 375]]
Chk 3701 [[84, 175, 135, 312], [15, 199, 57, 309]]
Chk 3702 [[6, 118, 186, 432], [195, 10, 391, 423], [159, 236, 233, 383]]
Chk 3704 [[239, 67, 344, 360], [130, 60, 218, 167]]
Chk 3705 [[305, 81, 491, 375], [217, 84, 340, 321], [59, 53, 101, 171], [23, 52, 76, 185], [0, 49, 33, 194]]
Chk 3706 [[55, 220, 132, 352], [146, 209, 228, 306], [261, 221, 343, 366], [353, 211, 412, 287]]
Chk 3707 [[46, 16, 240, 475], [250, 91, 396, 392]]
Chk 3708 [[0, 55, 140, 374], [351, 70, 499, 367], [111, 119, 279, 374]]
Chk 3709 [[56, 26, 272, 333], [284, 15, 500, 333], [247, 45, 345, 333]]
Chk 3710 [[278, 17, 365, 159], [184, 35, 258, 140]]
Chk 3711 [[215, 288, 264, 395], [91, 305, 149, 419], [145, 246, 179, 316]]
Chk 3712 [[310, 174, 383, 289], [134, 171, 225, 277]]
Chk 3713 [[0, 1, 221, 334], [206, 49, 476, 334]]
Chk 3714 [[22, 169, 332, 491], [0, 131, 118, 489], [86, 186, 102, 230]]
Chk 3715 [[8, 65, 211, 279], [228, 95, 444, 343]]
Chk 3716 [[0, 119, 55, 285], [75, 136, 225, 392], [250, 0, 374, 491]]
Chk 3717 [[130, 45, 175, 135], [179, 49, 216, 128], [219, 31, 292, 126]]
Chk 3718 [[195, 51, 332, 500], [64, 87, 204, 495]]
Chk 3720 [[75, 62, 329, 332], [226, 52, 470, 331]]
Chk 3721 [[52, 33, 232, 249], [273, 49, 436, 249], [444, 56, 499, 241], [450, 140, 499, 210]]
Chk 3722 [[93, 61, 194, 242], [181, 66, 286, 237], [425, 262, 500, 333]]
Chk 3723 [[312, 79, 464, 242], [93, 0, 248, 256], [2, 1, 54, 126]]
Chk 3724 [[82, 155, 224, 499], [99, 63, 225, 214]]
Chk 3725 [[344, 129, 429, 229], [272, 151, 363, 256], [206, 172, 289, 267], [153, 182, 227, 301]]
Chk 3727 [[119, 136, 256, 371], [10, 71, 124, 374], [387, 126, 488, 374], [265, 3, 291, 38]]
Chk 3728 [[291, 177, 369, 305], [146, 119, 396, 292]]
Chk 3729 [[235, 31, 436, 334], [72, 37, 203, 334]]
Chk 3730 [[332, 28, 500, 348], [196, 25, 338, 183]]
Chk 3731 [[0, 19, 39, 113], [32, 16, 76, 164], [81, 4, 157, 110], [217, 25, 262, 125], [252, 10, 297, 114], [298, 13, 340, 77], [373, 63, 500, 280], [70, 92, 260, 373]]
Chk 3732 [[326, 52, 395, 353], [268, 45, 364, 365], [209, 65, 316, 358], [140, 29, 238, 202], [0, 41, 103, 375]]
Chk 3734 [[46, 103, 194, 374], [306, 25, 467, 360], [314, 100, 369, 206]]
Chk 3735 [[332, 110, 425, 347], [66, 87, 167, 347], [165, 186, 236, 338]]
Chk 3736 [[135, 7, 299, 295], [279, 79, 450, 248]]
Chk 3737 [[231, 134, 279, 263], [91, 160, 153, 264]]
Chk 3738 [[32, 86, 115, 264], [406, 29, 498, 200], [308, 35, 400, 215], [119, 28, 212, 274]]

Chk 3739 [[53, 46, 163, 333], [160, 63, 265, 333], [259, 58, 375, 333]]
Chk 3740 [[0, 3, 443, 333], [252, 113, 421, 333]]
Chk 3742 [[174, 99, 286, 410], [139, 116, 221, 420]]
Chk 3743 [[102, 78, 191, 332], [262, 66, 359, 229], [209, 68, 279, 183], [435, 286, 495, 332]]
Chk 3744 [[0, 36, 195, 333], [166, 44, 388, 333]]
Chk 3745 [[213, 127, 268, 270], [173, 124, 220, 287]]
Chk 3746 [[74, 15, 253, 364], [188, 133, 333, 396], [0, 152, 130, 455], [1, 1, 31, 100]]
Chk 3748 [[118, 80, 215, 348], [211, 44, 319, 322], [389, 93, 413, 142], [354, 90, 371, 134]]
Chk 3749 [[53, 95, 245, 295], [206, 78, 468, 303]]
Chk 3753 [[200, 51, 261, 232], [120, 39, 176, 201]]
Chk 3756 [[36, 38, 139, 333], [304, 2, 465, 333], [384, 199, 428, 333], [417, 37, 492, 312]]
Chk 3758 [[299, 9, 497, 265], [7, 9, 307, 278]]
Chk 3760 [[148, 146, 424, 333], [179, 137, 423, 333], [228, 154, 299, 227], [328, 61, 447, 190], [273, 52, 357, 161], [320, 52, 386, 128], [81, 0, 133, 104]]
Chk 3762 [[228, 123, 321, 284], [328, 124, 386, 281], [389, 107, 462, 283]]
Chk 3763 [[41, 0, 200, 153], [237, 44, 443, 289], [151, 137, 349, 328]]
Chk 3764 [[353, 104, 449, 332], [54, 95, 155, 332], [158, 119, 253, 332]]
Chk 3765 [[118, 16, 232, 333], [211, 86, 406, 333], [417, 53, 500, 333]]
Chk 3766 [[136, 91, 227, 332], [36, 102, 116, 332], [451, 117, 491, 230], [381, 113, 459, 225], [284, 105, 372, 194]]
Chk 3767 [[29, 113, 109, 315], [200, 131, 262, 298], [254, 125, 316, 311], [380, 115, 443, 305], [427, 212, 474, 299]]
Chk 3768 [[81, 270, 122, 412], [155, 200, 306, 478]]
Chk 3769 [[228, 26, 454, 332], [104, 56, 242, 332]]
Chk 3770 [[73, 58, 196, 337], [238, 90, 434, 313], [307, 72, 495, 374]]
Chk 3771 [[168, 168, 287, 373], [93, 181, 157, 312]]
Chk 3772 [[266, 55, 355, 305], [133, 41, 238, 315]]
Chk 3774 [[139, 92, 316, 330], [0, 8, 147, 330], [379, 52, 498, 330]]
Chk 3776 [[117, 93, 227, 298], [60, 157, 111, 231], [206, 68, 321, 287], [401, 167, 431, 214]]
Chk 3778 [[0, 6, 181, 332], [166, 84, 361, 332], [296, 35, 499, 332]]
Chk 3779 [[348, 75, 462, 273], [198, 111, 261, 223]]
Chk 3780 [[0, 39, 258, 353], [335, 80, 439, 272], [342, 71, 440, 266]]
Chk 3781 [[24, 50, 133, 244], [321, 73, 448, 184]]
Chk 3782 [[266, 33, 481, 276], [12, 31, 282, 323]]
Chk 3783 [[104, 83, 159, 211], [375, 138, 437, 248], [231, 171, 320, 328], [426, 99, 495, 216], [10, 112, 60, 172], [208, 76, 253, 126]]
Chk 3785 [[201, 90, 311, 424], [159, 282, 305, 468], [91, 296, 229, 498], [0, 308, 160, 500]]
Chk 3786 [[178, 89, 232, 224], [223, 142, 279, 221], [292, 100, 335, 216], [326, 88, 373, 195]]
Chk 3788 [[167, 80, 268, 335], [270, 87, 368, 335], [322, 76, 411, 335]]
Chk 3790 [[215, 57, 321, 284], [34, 56, 106, 250], [0, 4, 28, 31]]
Chk 3791 [[385, 67, 463, 326], [51, 51, 128, 242], [148, 27, 228, 285]]
Chk 3792 [[219, 44, 384, 323], [97, 23, 224, 323]]
Chk 3793 [[240, 20, 384, 286], [64, 126, 234, 256]]
Chk 3794 [[181, 13, 337, 297], [67, 110, 179, 312], [12, 68, 69, 198]]
Chk 3795 [[104, 63, 224, 301], [184, 61, 265, 248]]
Chk 3796 [[96, 62, 217, 334], [243, 80, 317, 262], [348, 0, 500, 334], [0, 2, 76, 333]]
Chk 3797 [[59, 85, 126, 237], [167, 93, 258, 260], [383, 115, 474, 265]]
Chk 3798 [[274, 111, 446, 315], [98, 140, 212, 311]]
Chk 3799 [[267, 79, 364, 297], [350, 82, 404, 293]]
Chk 3800 [[274, 142, 323, 224], [165, 173, 202, 219]]
Chk 3801 [[54, 31, 203, 323], [243, 41, 353, 299]]
Chk 3803 [[120, 138, 181, 269], [169, 108, 224, 270], [318, 97, 364, 243], [343, 81, 398, 271]]
Chk 3804 [[189, 71, 328, 417], [72, 88, 214, 421], [59, 144, 117, 391]]
Chk 3806 [[0, 1, 324, 500], [149, 200, 323, 485]]
Chk 3808 [[327, 286, 431, 500], [176, 237, 280, 412], [258, 141, 369, 486]]
Chk 3809 [[281, 21, 468, 311], [67, 59, 283, 325], [204, 19, 323, 269], [177, 52, 203, 91]]
Chk 3810 [[213, 167, 336, 349], [315, 118, 453, 277], [177, 119, 262, 209]]
Chk 3811 [[40, 101, 231, 334], [250, 79, 371, 196]]
Chk 3813 [[180, 127, 281, 462], [79, 149, 197, 450]]
Chk 3814 [[25, 41, 144, 479], [109, 54, 223, 500], [198, 34, 333, 500]]
Chk 3815 [[103, 42, 290, 294], [217, 105, 320, 295], [0, 46, 44, 209], [440, 32, 500, 228], [314, 86, 358, 184]]
Chk 3816 [[105, 47, 250, 330], [341, 40, 483, 324], [460, 0, 493, 47]]
Chk 3817 [[5, 95, 55, 309], [30, 75, 84, 293], [100, 134, 147, 275], [131, 146, 189, 296], [195, 103, 270, 307], [148, 73, 221, 271]]
Chk 3819 [[98, 97, 211, 247], [438, 35, 494, 116], [10, 76, 97, 230], [197, 80, 330, 250]]
Chk 3822 [[157, 85, 266, 375], [252, 154, 361, 345]]
Chk 3823 [[186, 47, 267, 133], [286, 47, 362, 117]]
Chk 3824 [[298, 29, 494, 311], [3, 47, 301, 317], [131, 58, 278, 241]]
Chk 3825 [[0, 122, 199, 351], [213, 138, 331, 324]]
Chk 3827 [[40, 83, 99, 367], [85, 99, 171, 375], [83, 74, 132, 152], [141, 79, 220, 330], [210, 86, 291, 303], [258, 80, 325, 155]]
Chk 3828 [[163, 157, 204, 302], [406, 205, 466, 386]]
Chk 3829 [[152, 77, 245, 211], [234, 71, 309, 205]]
Chk 3830 [[36, 247, 220, 500], [105, 48, 189, 256]]
Chk 3831 [[409, 91, 494, 333], [345, 116, 415, 324]]
Chk 3832 [[27, 115, 278, 374], [185, 117, 317, 357], [268, 128, 465, 357]]
Chk 3833 [[0, 151, 83, 499], [82, 161, 178, 486], [201, 187, 226, 249], [200, 245, 246, 334], [156, 256, 189, 306], [239, 283, 270, 328], [246, 262, 279, 310]]
Chk 3834 [[128, 44, 216, 311], [36, 54, 122, 318]]
Chk 3835 [[35, 46, 196, 319], [344, 66, 449, 329]]
Chk 3836 [[238, 106, 318, 294], [79, 74, 263, 325]]
Chk 3837 [[270, 62, 362, 330], [179, 41, 337, 329]]
Chk 3838 [[223, 75, 322, 437], [39, 74, 160, 321]]
Chk 3839 [[143, 204, 209, 362], [114, 262, 165, 372], [21, 195, 76, 363], [60, 218, 112, 325], [129, 178, 171, 254], [188, 170, 238, 260]]
Chk 3840 [[346, 108, 479, 346], [196, 253, 317, 323], [31, 224, 253, 342]]
Chk 3841 [[31, 150, 195, 375], [188, 0, 500, 375]]
Chk 3843 [[306, 250, 500, 332], [0, 0, 275, 332], [231, 13, 408, 332]]
Chk 3844 [[208, 156, 342, 486], [40, 141, 191, 498]]
Chk 3845 [[134, 65, 369, 367], [0, 87, 74, 369], [12, 100, 189, 374]]
Chk 3848 [[207, 52, 263, 201], [367, 102, 430, 271], [276, 146, 339, 337], [127, 100, 188, 273]]
Chk 3849 [[412, 30, 457, 93], [248, 16, 443, 320], [147, 17, 316, 334], [381, 0, 431, 50], [455, 21, 500, 88]]
Chk 3850 [[199, 38, 314, 333], [273, 4, 349, 289], [329, 27, 447, 301]]
Chk 3852 [[298, 196, 387, 322], [388, 199, 435, 315]]
Chk 3853 [[0, 50, 180, 281], [112, 24, 278, 224], [234, 41, 370, 175], [365, 0, 496, 121]]
Chk 3854 [[26, 140, 106, 301], [335, 152, 395, 291], [187, 205, 230, 301]]
Chk 3856 [[320, 194, 365, 329], [351, 195, 400, 331]]
Chk 3857 [[199, 101, 285, 306], [428, 30, 496, 234], [26, 148, 109, 315], [327, 45, 440, 313], [378, 39, 437, 235]]
Chk 3858 [[51, 157, 128, 299], [0, 190, 142, 375], [122, 158, 190, 292], [186, 190, 304, 375], [245, 165, 291, 217], [284, 176, 339, 251], [404, 142, 500, 366]]
Chk 3859 [[120, 19, 218, 175], [173, 30, 223, 99], [389, 109, 500, 375]]
Chk 3860 [[169, 242, 240, 450], [49, 235, 110, 435]]
Chk 3862 [[64, 116, 177, 227], [194, 110, 306, 220], [327, 135, 440, 240], [89, 199, 287, 333], [326, 230, 487, 333]]
Chk 3863 [[154, 20, 465, 326], [22, 0, 254, 297]]
Chk 3864 [[372, 34, 458, 230], [2, 139, 98, 396], [207, 114, 313, 254]]
Chk 3865 [[51, 169, 310, 500], [10, 189, 131, 481], [245, 225, 336, 499]]
Chk 3866 [[25, 0, 233, 333], [345, 21, 500, 333]]
Chk 3867 [[186, 31, 304, 243], [256, 92, 421, 316]]
Chk 3868 [[200, 91, 297, 439], [28, 78, 201, 493]]
Chk 3869 [[155, 92, 363, 357], [0, 139, 154, 374], [270, 29, 479, 361]]
Chk 3870 [[306, 58, 470, 329], [40, 57, 241, 319], [227, 40, 345, 233]]
Chk 3871 [[116, 133, 189, 287], [200, 140, 279, 302]]
Chk 3872 [[243, 21, 375, 406], [0, 59, 109, 351], [114, 104, 149, 202], [41, 101, 113, 245]]
Chk 3873 [[34, 166, 183, 375], [98, 111, 307, 375]]
Chk 3874 [[307, 64, 498, 364], [135, 34, 322, 356], [15, 0, 144, 288], [147, 204, 275, 333]]
Chk 3875 [[188, 139, 250, 334], [88, 104, 164, 375], [127, 127, 187, 345], [62, 133, 106, 333], [0, 103, 51, 375]]
Chk 3876 [[24, 9, 244, 331], [230, 2, 438, 331], [421, 218, 500, 331]]
Chk 3877 [[14, 32, 309, 331], [157, 56, 419, 331]]
Chk 3878 [[48, 134, 169, 366], [25, 61, 217, 460], [97, 114, 333, 467]]
Chk 3879 [[136, 104, 234, 319], [219, 58, 324, 241], [275, 34, 359, 266], [345, 117, 430, 337]]
Chk 3880 [[305, 258, 365, 372], [127, 240, 233, 457]]
Chk 3881 [[54, 26, 156, 350], [272, 210, 358, 275]]
Chk 3882 [[79, 46, 163, 290], [273, 95, 393, 236]]
Chk 3883 [[100, 41, 235, 331], [207, 100, 322, 331], [11, 78, 33, 127], [49, 87, 75, 160], [291, 87, 319, 160]]
Chk 3884 [[181, 84, 314, 305], [397, 119, 490, 313]]
Chk 3885 [[205, 174, 279, 397], [93, 171, 165, 414]]
Chk 3886 [[160, 33, 266, 318], [227, 47, 305, 302], [0, 24, 31, 165]]
Chk 3887 [[353, 40, 464, 229], [276, 29, 394, 281], [68, 29, 241, 281], [0, 10, 112, 281]]
Chk 3889 [[219, 71, 419, 328], [63, 95, 207, 322]]
Chk 3891 [[239, 49, 379, 345], [170, 35, 300, 319]]

Chk 3894 [[0, 13, 153, 491], [129, 43, 284, 487]]
Chk 3895 [[149, 92, 245, 260], [359, 98, 451, 275]]
Chk 3896 [[163, 155, 237, 344], [74, 237, 128, 370], [17, 149, 83, 347]]
Chk 3898 [[346, 72, 432, 267], [42, 59, 128, 210]]
Chk 3899 [[219, 158, 318, 298], [357, 153, 432, 296]]
Chk 3900 [[96, 111, 216, 333], [141, 99, 204, 162], [203, 97, 269, 289], [258, 85, 344, 298], [463, 111, 500, 333]]
Chk 3901 [[65, 131, 142, 257], [138, 144, 222, 263], [205, 136, 280, 273], [265, 141, 341, 288], [352, 117, 457, 326]]
Chk 3902 [[76, 36, 329, 483], [7, 117, 216, 482]]
Chk 3903 [[21, 18, 301, 356], [294, 24, 479, 356], [1, 145, 68, 356]]
Chk 3904 [[84, 211, 319, 483], [14, 42, 226, 475]]
Chk 3905 [[31, 27, 292, 370], [154, 157, 305, 368]]
Chk 3906 [[72, 111, 221, 274], [285, 106, 435, 361], [180, 208, 374, 400]]
Chk 3907 [[177, 65, 291, 271], [357, 65, 474, 287], [294, 53, 386, 257]]
Chk 3908 [[204, 115, 408, 319], [153, 54, 195, 157], [11, 22, 44, 182]]
Chk 3910 [[146, 114, 316, 332], [314, 0, 499, 332]]
Chk 3911 [[104, 93, 156, 239], [182, 94, 237, 234]]
Chk 3912 [[421, 52, 498, 188], [162, 46, 252, 154]]
Chk 3913 [[179, 23, 279, 256], [323, 0, 467, 184]]
Chk 3914 [[0, 0, 108, 333], [50, 136, 121, 179], [117, 15, 209, 173], [281, 29, 369, 185], [203, 86, 256, 151], [367, 55, 412, 162], [386, 14, 486, 183]]
Chk 3917 [[325, 16, 464, 306], [24, 42, 154, 227], [217, 20, 321, 210]]
Chk 3918 [[99, 130, 332, 487], [3, 202, 202, 499]]
Chk 3920 [[209, 173, 257, 301], [350, 154, 407, 318], [287, 192, 329, 296], [261, 161, 304, 307]]
Chk 3921 [[84, 64, 226, 261], [269, 28, 420, 328]]
Chk 3923 [[208, 84, 277, 273], [409, 93, 482, 254]]
Chk 3924 [[0, 33, 106, 380], [56, 161, 371, 500]]
Chk 3925 [[6, 47, 234, 333], [283, 29, 500, 333]]
Chk 3926 [[135, 106, 200, 255], [210, 98, 256, 268], [264, 105, 315, 309]]
Chk 3928 [[106, 153, 200, 383], [236, 69, 339, 447], [13, 156, 114, 418]]
Chk 3930 [[134, 96, 231, 334], [217, 109, 271, 332], [260, 107, 376, 334], [378, 168, 431, 224], [413, 144, 475, 298], [462, 206, 500, 278]]
Chk 3932 [[0, 35, 223, 375], [193, 81, 317, 286], [297, 13, 481, 375]]
Chk 3933 [[42, 49, 204, 267], [185, 18, 399, 291]]
Chk 3934 [[419, 93, 483, 227], [191, 64, 283, 291]]
Chk 3935 [[1, 78, 88, 317], [230, 76, 349, 265], [341, 70, 498, 264], [74, 97, 196, 317]]
Chk 3936 [[6, 85, 191, 374], [299, 53, 492, 368]]
Chk 3937 [[292, 236, 414, 328], [228, 1, 385, 204], [16, 22, 209, 177]]
Chk 3938 [[0, 94, 192, 358], [22, 1, 162, 157], [163, 44, 273, 182], [262, 108, 494, 358], [395, 59, 500, 310]]
Chk 3940 [[56, 29, 171, 355], [239, 126, 286, 236], [249, 21, 484, 355]]
Chk 3941 [[126, 125, 241, 388], [258, 134, 334, 390], [58, 132, 145, 382]]
Chk 3942 [[14, 5, 328, 332], [209, 28, 466, 332]]
Chk 3943 [[22, 105, 150, 270], [227, 76, 393, 255], [355, 60, 500, 375]]
Chk 3945 [[8, 165, 200, 500], [166, 145, 272, 500], [244, 114, 458, 500], [26, 182, 64, 254]]
Chk 3946 [[156, 130, 239, 431], [100, 137, 176, 446]]
Chk 3947 [[0, 51, 274, 500], [114, 72, 460, 500], [339, 106, 460, 199], [354, 148, 460, 342]]
Chk 3948 [[74, 47, 239, 332], [254, 91, 456, 325]]
Chk 3949 [[176, 165, 211, 265], [218, 176, 256, 293], [3, 154, 36, 252]]
Chk 3950 [[398, 3, 461, 172], [340, 123, 393, 306], [98, 122, 185, 325], [241, 121, 301, 267], [292, 150, 353, 260], [262, 122, 321, 243]]
Chk 3951 [[9, 40, 182, 469], [106, 186, 206, 435]]
Chk 3952 [[359, 140, 381, 202], [476, 146, 493, 209], [461, 144, 479, 207], [82, 43, 440, 375], [80, 64, 397, 375]]
Chk 3953 [[62, 49, 224, 375], [250, 65, 354, 375], [381, 101, 489, 375]]
Chk 3954 [[59, 151, 149, 332], [145, 5, 312, 332], [253, 28, 464, 332]]
Chk 3955 [[178, 107, 317, 484], [60, 100, 175, 472]]
Chk 3957 [[226, 39, 294, 127], [303, 89, 329, 118], [334, 86, 365, 121], [360, 92, 393, 128], [382, 92, 420, 163], [401, 96, 444, 161]]
Chk 3958 [[27, 0, 218, 401], [248, 9, 334, 364]]
Chk 3959 [[184, 161, 268, 315], [297, 161, 374, 287]]
Chk 3960 [[251, 203, 303, 346], [288, 194, 339, 329]]
Chk 3961 [[29, 78, 173, 358], [226, 76, 349, 368], [346, 135, 462, 358]]
Chk 3962 [[0, 91, 136, 295], [85, 115, 186, 300], [58, 42, 313, 375]]
Chk 3963 [[317, 128, 379, 219], [443, 141, 486, 224], [216, 124, 274, 230], [114, 118, 159, 216], [26, 130, 84, 216]]
Chk 3964 [[6, 39, 170, 280], [157, 16, 318, 277], [311, 56, 489, 233]]
Chk 3965 [[178, 76, 260, 276], [239, 167, 301, 281]]
Chk 3966 [[107, 59, 193, 288], [167, 134, 228, 310], [62, 69, 105, 141]]
Chk 3967 [[268, 114, 491, 496], [0, 4, 220, 386]]
Chk 3968 [[333, 17, 500, 333], [295, 86, 387, 333], [220, 109, 302, 333], [97, 140, 152, 332], [71, 162, 114, 333]]
Chk 3969 [[321, 6, 420, 278], [116, 49, 227, 316]]
Chk 3971 [[327, 67, 422, 294], [46, 28, 140, 279]]
Chk 3974 [[40, 15, 154, 392], [103, 79, 265, 392]]
Chk 3975 [[311, 140, 402, 343], [282, 151, 339, 306]]
Chk 3976 [[60, 93, 219, 375], [345, 124, 448, 375], [385, 203, 500, 375]]
Chk 3977 [[143, 75, 237, 254], [237, 64, 324, 279]]
Chk 3978 [[0, 2, 194, 332], [359, 0, 497, 146]]
Chk 3980 [[111, 129, 155, 214], [144, 89, 261, 489], [234, 97, 311, 461], [267, 89, 423, 500]]
Chk 3981 [[28, 86, 94, 283], [389, 99, 447, 228]]
Chk 3982 [[287, 15, 500, 375], [0, 128, 198, 375], [36, 4, 195, 228]]
Chk 3984 [[0, 0, 140, 260], [91, 0, 369, 410], [273, 0, 500, 410]]
Chk 3985 [[26, 290, 109, 485], [148, 278, 237, 485]]
Chk 3986 [[125, 21, 283, 489], [267, 232, 356, 473]]
Chk 3987 [[313, 101, 371, 171], [327, 118, 406, 291], [392, 120, 490, 283], [243, 103, 322, 314], [93, 79, 174, 171]]
Chk 3988 [[265, 0, 441, 333], [241, 34, 422, 333]]
Chk 3989 [[0, 131, 207, 387], [234, 35, 375, 365], [223, 53, 300, 283]]
Chk 3991 [[9, 7, 306, 336], [191, 38, 477, 335]]
Chk 3992 [[428, 48, 500, 294], [317, 93, 440, 247], [237, 84, 342, 236], [0, 32, 221, 333], [78, 74, 221, 243]]
Chk 3995 [[149, 78, 263, 302], [118, 79, 200, 255]]
Chk 3996 [[263, 20, 431, 365], [0, 77, 215, 356], [380, 6, 429, 139]]
Chk 3997 [[81, 35, 212, 332], [4, 49, 101, 324], [314, 48, 437, 329]]
Chk 3998 [[293, 132, 375, 275], [169, 125, 291, 264]]
Chk 3999 [[104, 89, 209, 361], [246, 99, 313, 319], [419, 82, 495, 342], [212, 219, 269, 324]]
Chk 4002 [[160, 23, 293, 361], [279, 58, 389, 333]]
Chk 4004 [[66, 63, 263, 323], [288, 38, 444, 331]]
Chk 4006 [[46, 78, 198, 473], [228, 67, 366, 429], [183, 90, 225, 242]]
Chk 4007 [[292, 93, 426, 242], [436, 71, 493, 270], [1, 129, 142, 312], [145, 89, 248, 253]]
Chk 4008 [[102, 147, 341, 454], [0, 0, 232, 500]]
Chk 4009 [[243, 137, 386, 329], [12, 75, 229, 327]]
Chk 4010 [[455, 35, 499, 171], [180, 79, 251, 223], [305, 48, 390, 201], [380, 51, 417, 138]]
Chk 4011 [[228, 155, 282, 211], [221, 131, 322, 235], [168, 125, 267, 232]]
Chk 4012 [[166, 79, 363, 312], [302, 28, 494, 311], [0, 5, 136, 248]]
Chk 4014 [[194, 139, 291, 374], [333, 82, 499, 374]]
Chk 4015 [[0, 37, 122, 302], [149, 64, 274, 333], [265, 78, 378, 303], [352, 55, 438, 275], [394, 0, 500, 321]]
Chk 4016 [[151, 132, 224, 328], [173, 129, 276, 373], [10, 82, 101, 373], [21, 75, 203, 373]]
Chk 4017 [[180, 154, 266, 398], [73, 95, 194, 402]]
Chk 4018 [[105, 107, 217, 287], [294, 93, 396, 212], [7, 93, 151, 291]]
Chk 4021 [[308, 118, 339, 189], [255, 139, 290, 184], [207, 129, 231, 204], [140, 132, 163, 190]]
Chk 4022 [[189, 35, 332, 385], [25, 54, 148, 357]]
Chk 4023 [[213, 109, 322, 333], [307, 165, 414, 333]]
Chk 4024 [[184, 185, 244, 370], [133, 193, 228, 383]]
Chk 4025 [[78, 119, 213, 292], [290, 125, 371, 300]]
Chk 4026 [[119, 109, 280, 332], [289, 141, 480, 332]]
Chk 4029 [[276, 75, 405, 333], [145, 34, 246, 333], [84, 44, 186, 333], [0, 61, 43, 192]]
Chk 4032 [[316, 62, 381, 203], [409, 76, 462, 191], [161, 70, 224, 183], [38, 61, 79, 192], [238, 79, 280, 126]]
Chk 4033 [[73, 47, 226, 333], [289, 50, 394, 333]]
Chk 4034 [[138, 170, 218, 308], [42, 289, 251, 333], [212, 116, 319, 322]]
Chk 4035 [[113, 54, 201, 319], [210, 84, 279, 300]]
Chk 4036 [[38, 45, 164, 385], [44, 63, 308, 453]]
Chk 4037 [[317, 124, 464, 331], [124, 71, 214, 331], [252, 68, 371, 306], [40, 156, 221, 325]]
Chk 4038 [[71, 78, 211, 333], [204, 52, 319, 333], [335, 44, 460, 333]]
Chk 4039 [[0, 189, 40, 341], [27, 196, 82, 370], [157, 161, 227, 360], [138, 275, 182, 365], [121, 246, 147, 302], [142, 238, 161, 280]]
Chk 4040 [[284, 22, 452, 332], [71, 105, 220, 332]]
Chk 4041 [[366, 107, 419, 261], [288, 114, 353, 254], [241, 98, 302, 223], [332, 160, 379, 250], [216, 154, 265, 219], [283, 70, 324, 114]]

Chk 4042 [[12, 58, 223, 333], [244, 25, 459, 333]]
Chk 4043 [[239, 52, 384, 316], [50, 80, 156, 314]]
Chk 4044 [[3, 114, 212, 430], [197, 91, 420, 430]]
Chk 4045 [[160, 116, 312, 326], [348, 43, 420, 112], [399, 7, 429, 55]]
Chk 4047 [[164, 43, 295, 183], [259, 18, 434, 201]]
Chk 4049 [[201, 59, 266, 241], [245, 32, 326, 375], [100, 22, 222, 382]]
Chk 4050 [[0, 102, 124, 333], [125, 77, 309, 333], [282, 113, 432, 326]]
Chk 4051 [[98, 67, 211, 374], [227, 27, 399, 370]]
Chk 4052 [[183, 44, 335, 333], [289, 83, 399, 333]]
Chk 4053 [[409, 116, 495, 327], [353, 124, 421, 290], [132, 80, 269, 333], [55, 76, 131, 250], [217, 92, 331, 313], [295, 112, 342, 165]]
Chk 4054 [[44, 149, 196, 499], [179, 184, 277, 499]]
Chk 4055 [[0, 73, 331, 374], [239, 108, 499, 373]]
Chk 4056 [[0, 0, 64, 141], [73, 125, 302, 238]]
Chk 4057 [[349, 150, 436, 374], [122, 131, 220, 371]]
Chk 4058 [[80, 91, 260, 338], [249, 51, 449, 338]]
Chk 4059 [[38, 36, 322, 334], [195, 73, 437, 334], [473, 152, 496, 187]]
Chk 4060 [[234, 52, 452, 390], [19, 39, 277, 361], [0, 96, 50, 258]]
Chk 4061 [[86, 277, 128, 346], [231, 266, 260, 341], [201, 257, 239, 339]]
Chk 4062 [[123, 70, 257, 500], [57, 9, 176, 500]]
Chk 4064 [[0, 138, 198, 482], [71, 0, 333, 493]]
Chk 4065 [[69, 38, 247, 500], [174, 0, 355, 491]]
Chk 4066 [[220, 41, 488, 377], [14, 6, 184, 359]]
Chk 4067 [[40, 5, 284, 253], [283, 41, 453, 253]]
Chk 4068 [[357, 125, 455, 364], [18, 85, 106, 336], [193, 116, 272, 318], [266, 82, 299, 195], [303, 79, 340, 214]]
Chk 4069 [[126, 58, 266, 305], [21, 133, 182, 477]]
Chk 4070 [[31, 116, 139, 388], [124, 161, 209, 402], [211, 215, 258, 381], [299, 161, 364, 394], [259, 197, 317, 375], [0, 230, 34, 330]]
Chk 4071 [[11, 19, 214, 307], [374, 109, 462, 254], [230, 31, 417, 332], [169, 72, 269, 326]]
Chk 4072 [[190, 28, 492, 329], [2, 42, 251, 328]]
Chk 4076 [[144, 178, 197, 266], [103, 172, 153, 261]]
Chk 4077 [[201, 141, 452, 301], [221, 81, 333, 250], [51, 14, 239, 245]]
Chk 4078 [[297, 173, 341, 312], [83, 106, 179, 332], [376, 169, 418, 298], [188, 165, 224, 321]]
Chk 4079 [[0, 211, 58, 285], [106, 56, 191, 303], [280, 26, 394, 315], [399, 197, 500, 334], [163, 150, 216, 247]]
Chk 4080 [[217, 40, 290, 139], [168, 98, 384, 440]]
Chk 4081 [[48, 133, 119, 317], [204, 61, 297, 276], [285, 64, 346, 287], [101, 98, 159, 207]]
Chk 4082 [[162, 103, 255, 324], [221, 25, 372, 331]]
Chk 4083 [[9, 54, 249, 351], [281, 58, 499, 369]]
Chk 4084 [[176, 60, 319, 272], [188, 166, 356, 301]]
Chk 4085 [[229, 170, 314, 320], [155, 130, 229, 311], [314, 132, 339, 196], [171, 124, 201, 187]]
Chk 4088 [[0, 1, 125, 226], [104, 48, 253, 226], [197, 47, 336, 226]]
Chk 4089 [[124, 59, 243, 308], [213, 109, 312, 292], [247, 87, 300, 201]]
Chk 4090 [[258, 37, 438, 287], [133, 29, 262, 280]]
Chk 4091 [[281, 70, 423, 234], [119, 99, 227, 270], [135, 83, 157, 125], [100, 81, 134, 151]]
Chk 4092 [[108, 22, 297, 320], [275, 56, 433, 299], [0, 62, 197, 324], [399, 128, 488, 237]]
Chk 4093 [[86, 256, 154, 450], [251, 325, 352, 478], [367, 167, 448, 301], [215, 233, 272, 367], [308, 247, 355, 378], [286, 216, 335, 293], [129, 251, 189, 332]]
Chk 4094 [[60, 169, 262, 333], [3, 74, 116, 310], [221, 65, 326, 333], [426, 106, 500, 262], [324, 76, 459, 333], [326, 73, 457, 333]]
Chk 4095 [[13, 46, 197, 492], [187, 113, 320, 459]]
Chk 4096 [[10, 53, 173, 377], [286, 26, 473, 377]]
Chk 4097 [[334, 5, 391, 170], [0, 149, 178, 374], [92, 79, 233, 250], [369, 113, 499, 370], [80, 0, 193, 214]]
Chk 4098 [[146, 0, 500, 332], [0, 1, 192, 332]]
Chk 4099 [[184, 134, 256, 318], [118, 135, 188, 326]]
Chk 4100 [[0, 174, 68, 308], [171, 129, 314, 366], [342, 130, 435, 339]]
Chk 4101 [[309, 75, 459, 319], [108, 88, 288, 242], [19, 88, 172, 331]]
Chk 4102 [[111, 142, 142, 207], [133, 136, 170, 216], [178, 162, 223, 272], [324, 82, 417, 343]]
Chk 4103 [[0, 82, 63, 266], [70, 130, 162, 335], [149, 92, 342, 286], [199, 46, 264, 208]]
Chk 4105 [[196, 177, 282, 296], [140, 185, 193, 288], [75, 208, 117, 277], [4, 128, 82, 433]]
Chk 4106 [[320, 92, 415, 321], [210, 80, 296, 312], [78, 113, 113, 197]]
Chk 4107 [[133, 76, 295, 279], [35, 66, 151, 257], [224, 52, 441, 301]]
Chk 4108 [[333, 116, 452, 330], [119, 74, 302, 331]]
Chk 4109 [[360, 60, 490, 332], [66, 45, 213, 268], [199, 36, 322, 330]]
Chk 4112 [[326, 54, 500, 241], [203, 56, 373, 227], [94, 43, 240, 209]]
Chk 4113 [[17, 184, 151, 482], [97, 191, 311, 492]]
Chk 4114 [[72, 119, 238, 334], [185, 133, 264, 285], [236, 127, 293, 239], [243, 151, 402, 334], [168, 33, 305, 173]]
Chk 4115 [[185, 38, 482, 332], [62, 34, 323, 320]]
Chk 4116 [[0, 5, 156, 311], [223, 176, 331, 378], [166, 154, 255, 346]]
Chk 4118 [[257, 105, 326, 239], [174, 102, 258, 234]]
Chk 4119 [[262, 53, 358, 224], [124, 62, 210, 203], [0, 76, 57, 177]]
Chk 4120 [[201, 169, 290, 247], [416, 161, 483, 373], [263, 102, 389, 374]]
Chk 4122 [[0, 139, 100, 479], [219, 135, 351, 499], [55, 101, 256, 499], [331, 163, 369, 359]]
Chk 4124 [[37, 158, 231, 495], [110, 56, 333, 500]]
Chk 4125 [[25, 34, 249, 332], [138, 46, 374, 332]]
Chk 4126 [[251, 84, 391, 332], [356, 80, 444, 321], [409, 75, 478, 304]]
Chk 4127 [[62, 49, 301, 412], [221, 26, 493, 406]]
Chk 4128 [[34, 54, 256, 334], [142, 40, 476, 334]]
Chk 4129 [[107, 19, 273, 338], [346, 37, 466, 314], [70, 90, 126, 160]]
Chk 4130 [[333, 12, 460, 276], [21, 13, 164, 235], [148, 104, 322, 315]]
Chk 4131 [[52, 49, 182, 333], [165, 85, 291, 333]]
Chk 4132 [[12, 131, 172, 373], [210, 71, 261, 178], [185, 218, 296, 368]]
Chk 4133 [[255, 26, 442, 333], [17, 28, 257, 333], [0, 71, 74, 333]]
Chk 4134 [[25, 122, 174, 499], [118, 124, 276, 497]]
Chk 4135 [[292, 63, 359, 233], [222, 108, 284, 229]]
Chk 4136 [[65, 100, 229, 364], [307, 12, 439, 268]]
Chk 4137 [[41, 43, 220, 331], [292, 152, 404, 331]]
Chk 4141 [[307, 173, 404, 333], [222, 176, 332, 332]]
Chk 4142 [[296, 128, 383, 333], [171, 81, 313, 333], [0, 92, 217, 333]]
Chk 4143 [[80, 21, 166, 287], [204, 71, 315, 332], [322, 62, 406, 327]]
Chk 4144 [[258, 118, 307, 261], [190, 141, 263, 277], [336, 134, 411, 264], [481, 143, 499, 238]]
Chk 4145 [[358, 43, 500, 375], [96, 38, 208, 375], [0, 5, 136, 375]]
Chk 4146 [[244, 135, 324, 233], [349, 137, 423, 246]]
Chk 4148 [[61, 110, 333, 352], [6, 15, 173, 347]]
Chk 4149 [[0, 86, 95, 231], [183, 63, 372, 231]]
Chk 4151 [[285, 60, 499, 365], [134, 50, 299, 250], [22, 39, 161, 299]]
Chk 4152 [[93, 87, 208, 256], [158, 106, 396, 330], [346, 76, 482, 262], [2, 67, 128, 315]]
Chk 4154 [[212, 46, 458, 331], [121, 69, 218, 332]]
Chk 4155 [[4, 94, 171, 372], [369, 94, 490, 286]]
Chk 4157 [[33, 85, 136, 436], [165, 91, 285, 389]]
Chk 4159 [[247, 26, 363, 268], [93, 71, 182, 256]]
Chk 4160 [[28, 109, 129, 319], [170, 49, 365, 313], [475, 163, 499, 224], [0, 134, 18, 177]]
Chk 4161 [[0, 122, 268, 427], [280, 1, 448, 427]]
Chk 4162 [[0, 67, 79, 332], [92, 70, 184, 332], [194, 73, 289, 302], [298, 83, 412, 332], [370, 49, 493, 332]]
Chk 4164 [[349, 136, 468, 360], [42, 57, 211, 294], [205, 165, 264, 250]]
Chk 4165 [[0, 12, 207, 333], [164, 91, 268, 333], [247, 63, 425, 333], [327, 59, 428, 217]]
Chk 4166 [[106, 88, 215, 253], [222, 136, 336, 249], [348, 47, 496, 323], [314, 126, 334, 159]]
Chk 4168 [[259, 25, 394, 155], [32, 21, 202, 167]]
Chk 4169 [[358, 104, 423, 275], [254, 122, 285, 224]]
Chk 4170 [[409, 151, 446, 259], [37, 113, 89, 282], [345, 128, 412, 282], [188, 181, 229, 261]]
Chk 4171 [[51, 111, 99, 271], [104, 115, 126, 161], [303, 96, 353, 227], [140, 103, 178, 169]]
Chk 4172 [[305, 58, 405, 356], [189, 20, 327, 356]]
Chk 4173 [[111, 128, 178, 166], [374, 104, 447, 253], [210, 113, 244, 158], [53, 128, 92, 168], [289, 109, 342, 151]]
Chk 4174 [[398, 116, 500, 324], [143, 147, 239, 279], [143, 53, 312, 252]]
Chk 4175 [[185, 101, 283, 391], [324, 144, 413, 344], [0, 177, 89, 362]]
Chk 4176 [[38, 160, 112, 333], [21, 167, 68, 283], [33, 213, 56, 235], [179, 159, 268, 314], [288, 245, 347, 281], [403, 129, 427, 150], [220, 183, 249, 215], [343, 124, 448, 306]]
Chk 4177 [[282, 203, 338, 341], [172, 204, 224, 354], [223, 200, 266, 341], [125, 219, 152, 265], [374, 232, 393, 273]]
Chk 4178 [[48, 75, 227, 332], [256, 81, 433, 323]]
Chk 4179 [[95, 126, 186, 296], [166, 154, 231, 258], [226, 142, 284, 257], [282, 139, 374, 283], [158, 127, 187, 192], [303, 152, 340, 207]]
Chk 4180 [[323, 32, 493, 333], [125, 62, 323, 333], [0, 18, 155, 333]]
Chk 4182 [[75, 111, 265, 327], [239, 105, 469, 180]]
Chk 4183 [[61, 20, 286, 331], [166, 32, 413, 330], [394, 124, 453, 289], [459, 148, 499, 253]]
Chk 4184 [[230, 142, 292, 274], [77, 53, 131, 199], [152, 38, 236, 118]]
Chk 4185 [[172, 0, 322, 499], [296, 220, 437, 471]]
Chk 4186 [[148, 99, 291, 332], [245, 96, 331, 332], [417, 162, 500, 292]]

Chk 4188 [[4, 100, 353, 481], [201, 67, 400, 485]]
Chk 4190 [[69, 52, 192, 269], [197, 26, 274, 260]]
Chk 4192 [[218, 124, 447, 374], [153, 60, 267, 374]]
Chk 4193 [[0, 0, 244, 333], [249, 132, 489, 333], [238, 91, 442, 222]]
Chk 4195 [[209, 82, 347, 258], [352, 107, 421, 253]]
Chk 4196 [[228, 161, 322, 307], [146, 156, 237, 303]]
Chk 4197 [[0, 114, 63, 301], [45, 137, 141, 346], [96, 124, 186, 315], [213, 116, 287, 293], [291, 78, 375, 359], [354, 165, 408, 293], [438, 188, 500, 331]]
Chk 4198 [[168, 70, 312, 375], [254, 29, 406, 375], [88, 57, 214, 343]]
Chk 4199 [[176, 190, 277, 408], [6, 170, 204, 440], [209, 190, 274, 405], [92, 163, 175, 314]]
Chk 4201 [[247, 61, 311, 332], [283, 102, 368, 332]]
Chk 4202 [[295, 79, 363, 319], [215, 61, 303, 328], [2, 122, 32, 177], [84, 116, 118, 243]]
Chk 4203 [[0, 93, 100, 394], [77, 128, 298, 389], [190, 31, 465, 393]]
Chk 4204 [[215, 53, 358, 306], [138, 35, 240, 258]]
Chk 4205 [[45, 129, 91, 227], [134, 173, 217, 291], [200, 147, 242, 278], [227, 137, 273, 299], [258, 148, 303, 315], [347, 188, 375, 408], [345, 136, 375, 202]]
Chk 4207 [[305, 191, 342, 271], [267, 190, 299, 279]]
Chk 4208 [[115, 115, 178, 215], [332, 114, 417, 231]]
Chk 4209 [[176, 24, 485, 332], [73, 55, 336, 332], [4, 3, 142, 140]]
Chk 4210 [[313, 48, 387, 208], [251, 58, 324, 178]]
Chk 4211 [[327, 74, 428, 268], [88, 55, 236, 304], [0, 117, 151, 420]]
Chk 4212 [[19, 23, 204, 372], [313, 109, 461, 359]]
Chk 4213 [[307, 152, 359, 267], [225, 10, 306, 302]]
Chk 4214 [[125, 40, 461, 366], [40, 55, 297, 366]]
Chk 4216 [[10, 68, 222, 331], [169, 83, 425, 331]]
Chk 4217 [[70, 38, 200, 215], [185, 19, 369, 357]]
Chk 4218 [[41, 71, 266, 332], [273, 36, 383, 332], [459, 154, 500, 281]]
Chk 4219 [[59, 72, 195, 311], [116, 136, 215, 315], [251, 101, 396, 316]]
Chk 4220 [[83, 125, 153, 281], [39, 126, 107, 280]]
Chk 4221 [[146, 82, 372, 333], [3, 12, 253, 333]]
Chk 4222 [[0, 0, 268, 500], [72, 0, 276, 383]]
Chk 4223 [[51, 59, 200, 331], [184, 26, 322, 331]]
Chk 4226 [[1, 80, 259, 375], [254, 67, 445, 375]]
Chk 4227 [[153, 141, 292, 331], [343, 132, 440, 332]]
Chk 4228 [[152, 44, 209, 231], [203, 76, 264, 281], [288, 53, 334, 262], [312, 51, 360, 218]]
Chk 4229 [[261, 55, 499, 331], [96, 0, 265, 326], [0, 61, 181, 331]]
Chk 4230 [[178, 69, 263, 251], [304, 154, 414, 336]]
Chk 4232 [[0, 95, 46, 195], [23, 92, 119, 224], [110, 100, 152, 201], [137, 88, 185, 180], [161, 71, 233, 248], [316, 51, 405, 327]]
Chk 4233 [[100, 19, 294, 310], [397, 24, 500, 276]]
Chk 4234 [[35, 110, 199, 333], [184, 71, 373, 332], [413, 127, 450, 233]]
Chk 4235 [[17, 63, 276, 350], [160, 83, 411, 375], [169, 90, 437, 375]]
Chk 4236 [[75, 84, 403, 225], [13, 57, 187, 214], [248, 0, 337, 66]]
Chk 4237 [[49, 112, 148, 376], [103, 267, 252, 428], [184, 211, 257, 365]]
Chk 4238 [[0, 49, 237, 500], [249, 71, 332, 292], [38, 252, 209, 500]]
Chk 4239 [[94, 41, 174, 236], [390, 62, 462, 229], [433, 37, 499, 218], [39, 62, 114, 235]]
Chk 4240 [[178, 134, 329, 490], [15, 115, 185, 417], [282, 103, 332, 335], [96, 336, 175, 414]]
Chk 4241 [[388, 39, 468, 332], [458, 95, 500, 221], [184, 65, 271, 264], [0, 118, 74, 332], [142, 84, 212, 242]]
Chk 4242 [[242, 31, 287, 158], [278, 79, 308, 183]]
Chk 4244 [[267, 108, 391, 374], [78, 47, 220, 348]]
Chk 4246 [[20, 84, 132, 199], [200, 78, 490, 336], [192, 73, 425, 204]]
Chk 4247 [[307, 96, 500, 333], [239, 100, 423, 333]]
Chk 4248 [[148, 39, 430, 361], [100, 179, 261, 336], [66, 4, 152, 125]]
Chk 4249 [[0, 45, 146, 288], [333, 62, 499, 288]]
Chk 4250 [[215, 32, 392, 264], [13, 59, 200, 353]]
Chk 4251 [[54, 126, 135, 317], [310, 124, 395, 293], [392, 146, 455, 243]]
Chk 4252 [[0, 38, 318, 297], [0, 80, 254, 332]]
Chk 4253 [[25, 58, 140, 173], [116, 5, 294, 260], [294, 33, 485, 375]]
Chk 4254 [[231, 177, 319, 454], [324, 235, 346, 298], [167, 150, 254, 439], [335, 238, 353, 290]]
Chk 4256 [[35, 46, 247, 374], [172, 79, 420, 374]]
Chk 4257 [[219, 34, 457, 309], [39, 7, 280, 284]]
Chk 4258 [[68, 63, 102, 101], [111, 64, 153, 96]]
Chk 4259 [[39, 67, 164, 209], [159, 18, 309, 333], [322, 61, 442, 329], [415, 126, 497, 333]]
Chk 4260 [[29, 155, 99, 222], [161, 133, 236, 257], [258, 131, 329, 283], [303, 138, 382, 296], [461, 148, 500, 242]]
Chk 4261 [[317, 32, 415, 325], [122, 42, 235, 308]]
Chk 4262 [[34, 56, 209, 333], [188, 122, 288, 333], [293, 126, 400, 333], [450, 199, 500, 333]]
Chk 4263 [[0, 39, 147, 333], [109, 73, 203, 333], [340, 63, 433, 279], [350, 17, 500, 333]]
Chk 4264 [[144, 122, 202, 334], [198, 144, 230, 187]]
Chk 4265 [[209, 86, 344, 221], [19, 98, 163, 374], [344, 85, 446, 202]]
Chk 4266 [[304, 141, 341, 257], [83, 139, 106, 192], [113, 139, 137, 193], [142, 142, 166, 187], [225, 134, 254, 174]]
Chk 4268 [[128, 59, 330, 332], [314, 56, 481, 332], [86, 144, 128, 257], [46, 143, 85, 254]]
Chk 4269 [[215, 92, 279, 212], [280, 118, 316, 179], [309, 97, 366, 182]]
Chk 4270 [[53, 0, 290, 375], [258, 6, 433, 375]]
Chk 4271 [[109, 22, 290, 500], [103, 41, 291, 500]]
Chk 4272 [[29, 196, 147, 472], [167, 166, 296, 454], [297, 199, 452, 465], [126, 176, 200, 297]]
Chk 4273 [[14, 125, 144, 331], [248, 148, 393, 331], [265, 94, 372, 203], [387, 165, 489, 331]]
Chk 4274 [[62, 12, 233, 145], [302, 21, 482, 212], [0, 93, 82, 280], [218, 20, 340, 160]]
Chk 4275 [[95, 116, 253, 375], [243, 124, 408, 375]]
Chk 4276 [[254, 129, 363, 352], [325, 118, 403, 347], [7, 169, 154, 397], [450, 16, 493, 56]]
Chk 4277 [[257, 153, 334, 329], [189, 131, 260, 326]]
Chk 4278 [[20, 58, 74, 145], [38, 50, 156, 334], [131, 11, 249, 332], [257, 4, 463, 334]]
Chk 4279 [[289, 195, 360, 289], [358, 164, 467, 305], [63, 124, 181, 303], [71, 10, 165, 174], [29, 25, 108, 170]]
Chk 4280 [[53, 72, 156, 324], [206, 54, 325, 324]]
Chk 4281 [[65, 121, 219, 420], [197, 207, 317, 500]]
Chk 4282 [[137, 79, 239, 341], [291, 93, 343, 254], [80, 102, 143, 286]]
Chk 4283 [[273, 141, 350, 327], [227, 146, 260, 242]]
Chk 4284 [[66, 130, 127, 314], [6, 121, 96, 325]]
Chk 4286 [[223, 41, 454, 301], [51, 35, 287, 317]]
Chk 4287 [[6, 132, 167, 286], [128, 123, 212, 265], [266, 89, 348, 195], [335, 124, 454, 278], [332, 114, 433, 249], [261, 84, 344, 193]]
Chk 4288 [[0, 101, 112, 364], [98, 51, 247, 442]]
Chk 4289 [[0, 101, 500, 353], [98, 93, 282, 284]]
Chk 4291 [[339, 61, 406, 170], [416, 2, 476, 115], [355, 109, 463, 226]]
Chk 4292 [[34, 176, 122, 333], [86, 112, 206, 333], [299, 104, 461, 333]]
Chk 4293 [[34, 44, 141, 375], [93, 66, 139, 145], [172, 42, 244, 226], [339, 43, 417, 259]]
Chk 4295 [[82, 89, 139, 269], [28, 90, 108, 264]]
Chk 4296 [[159, 62, 479, 333], [309, 0, 444, 205]]
Chk 4297 [[79, 106, 172, 306], [212, 92, 282, 310], [265, 135, 343, 269], [375, 82, 457, 308]]
Chk 4298 [[138, 159, 282, 367], [174, 23, 292, 262], [9, 264, 109, 373], [253, 254, 367, 484]]
Chk 4299 [[58, 230, 184, 500], [163, 111, 249, 345]]
Chk 4300 [[96, 186, 210, 440], [189, 190, 279, 419]]
Chk 4301 [[21, 127, 118, 374], [345, 137, 415, 261], [228, 133, 299, 272]]
Chk 4302 [[66, 91, 227, 356], [76, 81, 396, 328]]
Chk 4303 [[53, 57, 235, 331], [305, 35, 486, 331], [270, 215, 353, 329]]
Chk 4304 [[81, 54, 312, 332], [196, 42, 362, 314]]
Chk 4307 [[0, 120, 190, 500], [152, 210, 321, 500]]
Chk 4308 [[61, 145, 230, 500], [206, 209, 373, 500]]
Chk 4310 [[163, 64, 240, 271], [261, 46, 347, 261]]
Chk 4311 [[285, 99, 363, 313], [65, 47, 148, 315]]
Chk 4314 [[258, 120, 351, 230], [330, 53, 443, 313]]
Chk 4315 [[132, 46, 381, 418], [1, 55, 184, 415]]
Chk 4316 [[151, 0, 332, 496], [8, 35, 196, 499]]
Chk 4317 [[74, 203, 162, 439], [179, 204, 284, 438]]
Chk 4319 [[166, 138, 219, 230], [238, 239, 325, 332]]
Chk 4320 [[247, 113, 447, 325], [384, 94, 487, 303], [60, 42, 241, 318]]
Chk 4321 [[316, 56, 415, 351], [38, 49, 190, 356], [223, 60, 322, 357], [36, 45, 101, 324]]
Chk 4322 [[421, 170, 471, 298], [123, 164, 162, 262], [145, 163, 186, 269]]
Chk 4324 [[2, 75, 68, 148], [35, 29, 166, 334], [285, 70, 349, 333]]
Chk 4325 [[344, 139, 423, 278], [188, 131, 252, 270], [39, 154, 97, 278]]
Chk 4326 [[27, 55, 192, 334], [87, 87, 275, 334], [341, 69, 500, 334]]
Chk 4327 [[42, 11, 142, 275], [344, 82, 399, 236], [138, 31, 211, 282], [320, 113, 348, 231], [400, 102, 429, 193]]
Chk 4328 [[298, 85, 446, 326], [190, 55, 319, 331]]
Chk 4329 [[306, 179, 352, 333], [180, 12, 307, 330], [415, 111, 500, 333]]
Chk 4330 [[12, 62, 288, 370], [263, 53, 489, 270]]
Chk 4331 [[11, 98, 95, 318], [154, 79, 227, 337]]
Chk 4332 [[37, 83, 156, 402], [104, 94, 332, 466]]
Chk 4333 [[24, 0, 178, 170], [126, 27, 196, 109], [132, 24, 384, 332], [305, 42, 396, 139], [330, 4, 383, 77], [369, 11, 441, 117], [421, 0, 497, 79], [448, 14, 500, 131]]
Chk 4336 [[25, 149, 328, 375], [259, 70, 500, 375]]
Chk 4337 [[58, 33, 173, 440], [171, 36, 292, 486]]
Chk 4338 [[52, 23, 378, 271], [139, 18, 257, 230]]
Chk 4339 [[147, 100, 331, 498], [5, 84, 191, 459]]
Chk 4341 [[266, 95, 469, 331], [73, 98, 329, 309]]
Chk 4343 [[132, 216, 221, 330], [265, 179, 409, 293]]
Chk 4344 [[348, 41, 457, 290], [215, 30, 315, 265]]

Chk 4345 [[0, 23, 145, 375], [106, 148, 226, 260], [136, 237, 260, 375], [167, 60, 280, 330]]
Chk 4346 [[0, 103, 275, 370], [279, 145, 499, 372], [198, 243, 265, 329]]
Chk 4347 [[39, 102, 149, 291], [52, 115, 177, 287], [182, 117, 291, 257], [285, 92, 409, 357], [441, 102, 500, 357], [389, 167, 482, 310]]
Chk 4349 [[123, 130, 199, 270], [344, 142, 432, 281], [212, 147, 273, 252]]
Chk 4350 [[12, 52, 164, 499], [121, 165, 351, 490]]
Chk 4351 [[132, 151, 210, 373], [420, 152, 493, 352], [241, 146, 322, 343], [200, 157, 266, 358]]
Chk 4352 [[86, 58, 287, 450], [192, 89, 323, 427]]
Chk 4353 [[318, 25, 390, 109], [340, 91, 438, 313]]
Chk 4354 [[293, 181, 332, 316], [105, 175, 225, 325], [0, 203, 46, 301], [191, 194, 241, 301]]
Chk 4355 [[129, 38, 278, 425], [17, 61, 175, 425], [292, 166, 370, 271]]
Chk 4358 [[0, 58, 142, 500], [55, 154, 236, 500], [271, 175, 375, 500], [279, 98, 375, 330]]
Chk 4359 [[342, 136, 398, 219], [246, 150, 295, 233]]
Chk 4360 [[20, 32, 95, 130], [17, 21, 189, 216], [177, 40, 375, 318], [279, 14, 500, 333]]
Chk 4361 [[93, 90, 164, 212], [154, 47, 298, 222]]
Chk 4362 [[249, 183, 343, 373], [387, 201, 491, 356], [18, 185, 80, 284]]
Chk 4363 [[128, 81, 205, 184], [435, 89, 498, 204], [320, 183, 482, 286]]
Chk 4365 [[270, 90, 450, 303], [126, 18, 165, 152], [19, 64, 127, 245], [465, 11, 499, 70]]
Chk 4367 [[64, 154, 151, 500], [125, 164, 198, 477], [272, 199, 342, 414], [316, 186, 389, 398], [250, 188, 301, 311]]
Chk 4368 [[0, 159, 61, 248], [57, 141, 159, 217], [96, 117, 234, 293], [211, 118, 335, 279]]
Chk 4369 [[6, 70, 143, 333], [150, 86, 254, 333], [250, 78, 370, 333], [369, 84, 469, 333]]
Chk 4372 [[162, 126, 386, 327], [342, 138, 481, 332], [26, 258, 87, 331]]
Chk 4373 [[94, 174, 148, 259], [144, 161, 197, 261], [111, 275, 223, 494], [211, 281, 314, 479]]
Chk 4374 [[182, 41, 264, 333], [258, 30, 340, 326], [67, 53, 108, 170], [0, 63, 68, 166]]
Chk 4375 [[222, 164, 255, 237], [402, 156, 427, 233], [281, 153, 327, 238]]
Chk 4376 [[25, 64, 88, 306], [72, 37, 170, 308], [167, 109, 239, 304], [220, 28, 303, 309], [165, 84, 240, 308]]
Chk 4380 [[84, 56, 332, 500], [0, 174, 264, 500]]
Chk 4381 [[200, 68, 499, 374], [103, 126, 280, 374]]
Chk 4382 [[44, 100, 167, 346], [150, 122, 249, 346], [228, 83, 356, 346]]
Chk 4383 [[7, 62, 173, 312], [181, 73, 427, 275]]
Chk 4384 [[21, 1, 153, 202], [14, 158, 204, 332]]
Chk 4385 [[0, 55, 227, 421], [293, 59, 500, 349], [208, 123, 249, 245]]
Chk 4386 [[174, 88, 263, 286], [44, 80, 135, 244]]
Chk 4387 [[0, 79, 171, 375], [263, 87, 448, 375], [143, 212, 202, 343], [400, 225, 454, 375], [449, 220, 500, 375]]
Chk 4389 [[271, 137, 356, 303], [379, 125, 498, 306], [126, 117, 260, 326], [15, 117, 153, 315]]
Chk 4390 [[71, 4, 309, 335], [317, 1, 482, 335]]
Chk 4391 [[55, 47, 250, 367], [231, 54, 391, 287]]
Chk 4392 [[98, 39, 287, 275], [240, 32, 446, 354]]
Chk 4393 [[33, 69, 188, 333], [213, 73, 406, 333]]
Chk 4394 [[161, 24, 295, 269], [27, 118, 210, 332], [308, 155, 373, 246]]
Chk 4395 [[174, 20, 422, 335], [40, 0, 271, 335]]
Chk 4396 [[332, 58, 498, 252], [147, 53, 353, 243], [84, 47, 231, 196]]
Chk 4397 [[0, 30, 240, 332], [242, 25, 478, 329], [452, 184, 499, 328], [441, 129, 479, 230]]
Chk 4398 [[64, 81, 203, 359], [199, 95, 411, 338], [338, 173, 394, 261], [249, 120, 499, 376]]
Chk 4399 [[70, 115, 177, 333], [266, 29, 442, 306]]
Chk 4400 [[302, 78, 373, 206], [87, 41, 170, 269], [193, 96, 236, 204]]
Chk 4401 [[0, 10, 171, 379], [56, 17, 275, 375], [162, 0, 493, 392], [231, 0, 338, 116]]
Chk 4402 [[169, 83, 238, 274], [54, 76, 121, 278], [285, 135, 372, 270], [382, 65, 444, 260]]
Chk 4403 [[311, 69, 468, 374], [6, 132, 116, 374], [182, 153, 311, 374], [428, 115, 494, 374]]
Chk 4404 [[102, 49, 241, 300], [245, 59, 335, 314]]
Chk 4405 [[12, 2, 312, 332], [273, 121, 500, 332], [276, 143, 498, 332]]
Chk 4406 [[100, 41, 311, 360], [343, 252, 467, 369]]
Chk 4407 [[327, 52, 462, 307], [5, 40, 215, 320], [80, 27, 211, 215]]
Chk 4408 [[0, 19, 263, 374], [332, 174, 427, 269], [129, 121, 312, 373]]
Chk 4410 [[62, 10, 359, 373], [218, 45, 443, 374]]
Chk 4411 [[215, 166, 261, 290], [271, 163, 324, 290]]
Chk 4413 [[156, 59, 306, 341], [111, 80, 186, 277]]
Chk 4415 [[69, 86, 154, 242], [252, 109, 356, 389], [321, 114, 387, 389], [364, 128, 441, 389], [405, 115, 489, 378]]
Chk 4416 [[188, 132, 334, 448], [24, 83, 187, 425]]
Chk 4417 [[68, 54, 195, 412], [204, 17, 464, 366]]
Chk 4418 [[0, 29, 136, 286], [73, 33, 220, 234], [190, 44, 258, 160], [162, 61, 223, 173], [361, 27, 493, 286], [332, 32, 408, 189], [308, 44, 373, 153]]
Chk 4420 [[70, 191, 333, 500], [98, 315, 298, 500], [2, 335, 88, 500]]
Chk 4421 [[269, 11, 416, 253], [75, 10, 245, 282]]
Chk 4422 [[130, 154, 313, 227], [206, 105, 305, 218]]
Chk 4423 [[141, 86, 233, 265], [109, 110, 191, 327], [371, 76, 418, 212]]
Chk 4425 [[1, 139, 154, 373], [377, 114, 491, 373], [154, 151, 311, 373], [289, 55, 418, 373]]
Chk 4426 [[45, 110, 218, 476], [178, 94, 333, 388]]
Chk 4428 [[12, 144, 86, 255], [95, 146, 156, 306], [144, 129, 205, 302], [200, 132, 285, 221], [119, 108, 159, 166]]
Chk 4429 [[153, 124, 294, 390], [29, 127, 165, 423], [16, 267, 49, 318]]
Chk 4430 [[100, 131, 150, 230], [4, 189, 103, 331], [220, 207, 298, 294]]
Chk 4431 [[198, 53, 288, 313], [278, 84, 392, 313], [450, 85, 491, 171]]
Chk 4432 [[266, 78, 387, 216], [384, 74, 435, 156], [385, 51, 495, 316], [451, 56, 500, 148], [460, 143, 500, 319]]
Chk 4433 [[17, 45, 224, 333], [219, 47, 475, 333], [159, 97, 244, 208], [398, 89, 480, 283]]
Chk 4434 [[126, 71, 188, 362], [200, 74, 284, 375]]
Chk 4435 [[327, 133, 410, 369], [264, 189, 329, 362], [183, 78, 290, 342], [375, 116, 423, 210]]
Chk 4436 [[211, 68, 411, 365], [315, 24, 500, 367]]
Chk 4437 [[177, 179, 258, 311], [74, 177, 166, 304], [155, 151, 219, 296]]
Chk 4439 [[10, 30, 212, 374], [173, 95, 375, 374]]
Chk 4440 [[95, 57, 326, 500], [24, 5, 167, 500]]
Chk 4441 [[93, 294, 192, 465], [27, 281, 118, 488]]
Chk 4442 [[13, 60, 162, 276], [209, 69, 395, 334]]
Chk 4443 [[307, 79, 499, 325], [5, 69, 176, 265], [130, 67, 340, 315]]
Chk 4444 [[24, 42, 164, 333], [121, 67, 310, 333], [240, 0, 482, 333]]
Chk 4446 [[194, 124, 294, 416], [0, 174, 110, 300]]
Chk 4448 [[51, 19, 175, 333], [178, 101, 255, 295], [369, 110, 500, 283]]
Chk 4449 [[349, 156, 488, 314], [16, 128, 263, 328]]
Chk 4450 [[21, 167, 415, 300], [133, 24, 500, 333]]
Chk 4451 [[78, 70, 143, 205], [424, 69, 496, 202], [138, 69, 212, 202]]
Chk 4452 [[459, 174, 500, 337], [118, 121, 304, 375], [0, 0, 186, 375]]
Chk 4453 [[0, 126, 217, 377], [156, 58, 464, 377]]
Chk 4454 [[56, 19, 253, 273], [152, 126, 500, 279]]
Chk 4456 [[315, 77, 376, 295], [40, 147, 152, 322], [387, 107, 410, 154]]
Chk 4457 [[7, 73, 186, 366], [270, 86, 421, 374]]
Chk 4458 [[44, 59, 201, 475], [198, 56, 337, 439]]
Chk 4459 [[18, 66, 199, 324], [241, 118, 482, 324], [183, 56, 386, 324]]
Chk 4460 [[260, 32, 483, 332], [41, 53, 264, 301]]
Chk 4461 [[234, 0, 499, 374], [21, 123, 260, 374]]
Chk 4463 [[75, 35, 176, 332], [216, 43, 339, 372], [293, 0, 381, 213], [361, 0, 427, 177]]
Chk 4464 [[262, 389, 333, 500], [229, 406, 271, 497], [104, 299, 182, 400], [0, 269, 116, 432], [53, 260, 103, 285], [0, 250, 65, 336]]
Chk 4465 [[16, 109, 448, 500], [232, 31, 398, 354]]
Chk 4466 [[175, 64, 380, 332], [30, 48, 191, 332]]
Chk 4467 [[1, 4, 164, 252], [197, 45, 291, 286]]
Chk 4468 [[0, 15, 198, 324], [156, 1, 323, 333]]
Chk 4470 [[282, 93, 477, 374], [10, 124, 194, 374], [109, 136, 221, 374]]
Chk 4471 [[361, 229, 494, 374], [103, 233, 262, 369], [117, 175, 154, 270]]
Chk 4473 [[0, 70, 147, 433], [146, 88, 290, 390]]
Chk 4474 [[136, 128, 308, 445], [70, 28, 254, 348]]
Chk 4477 [[5, 113, 57, 256], [79, 97, 189, 422], [147, 80, 255, 397], [103, 25, 137, 109], [142, 20, 204, 121], [230, 149, 257, 214]]
Chk 4478 [[245, 21, 464, 385], [92, 10, 160, 234], [164, 58, 346, 397]]
Chk 4479 [[6, 15, 268, 332], [142, 8, 406, 332], [356, 4, 499, 313]]
Chk 4480 [[48, 20, 316, 281], [295, 0, 500, 281]]
Chk 4482 [[250, 60, 371, 333], [384, 59, 490, 333]]
Chk 4483 [[204, 87, 273, 287], [106, 80, 197, 287], [294, 73, 384, 282]]
Chk 4484 [[313, 21, 413, 268], [114, 142, 211, 291]]
Chk 4487 [[0, 43, 444, 531], [392, 3, 799, 533]]
Chk 4488 [[223, 41, 338, 229], [616, 90, 799, 541], [484, 37, 656, 472], [2, 59, 56, 352], [619, 139, 680, 323], [66, 115, 103, 208]]
Chk 4489 [[136, 226, 264, 417], [52, 262, 128, 360], [564, 183, 704, 442], [308, 265, 358, 362], [254, 265, 293, 342]]
Chk 4490 [[102, 143, 180, 363], [219, 227, 297, 319]]
Chk 4491 [[102, 80, 259, 332], [498, 53, 562, 174], [456, 276, 584, 479], [656, 414, 800, 566]]
Chk 4492 [[391, 403, 518, 639], [722, 399, 787, 582], [332, 433, 424, 639]]
Chk 4493 [[9, 143, 88, 390], [139, 157, 182, 339], [232, 159, 305, 338], [349, 166, 425, 255]]
Chk 4494 [[186, 247, 279, 448], [311, 268, 374, 376]]
Chk 4495 [[212, 49, 294, 293], [413, 184, 563, 298]]
Chk 4496 [[420, 101, 625, 531], [584, 190, 669, 467]]
Chk 4497 [[241, 12, 294, 101], [124, 109, 171, 201], [117, 217, 168, 317], [122, 358, 170, 454]]
Chk 4498 [[128, 330, 189, 421], [247, 302, 282, 426], [400, 345, 446, 459]]

Chk 4500 [[49, 23, 300, 595], [0, 21, 99, 569]]
Chk 4501 [[429, 208, 603, 543], [282, 54, 377, 431]]
Chk 4502 [[122, 10, 249, 323], [378, 159, 469, 376]]
Chk 4503 [[314, 1, 701, 384], [17, 54, 362, 485], [200, 96, 386, 394]]
Chk 4504 [[131, 16, 234, 313], [201, 254, 296, 443], [272, 266, 379, 452], [601, 0, 673, 134], [716, 1, 796, 140]]
Chk 4505 [[405, 47, 766, 531], [32, 37, 393, 511]]
Chk 4506 [[661, 178, 727, 301], [22, 219, 208, 404]]
Chk 4510 [[0, 56, 430, 599], [365, 43, 768, 599]]
Chk 4511 [[155, 473, 204, 687], [94, 398, 170, 662]]
Chk 4512 [[439, 0, 800, 600], [116, 201, 563, 600]]
Chk 4513 [[8, 214, 42, 292], [29, 200, 85, 369], [72, 194, 201, 375], [213, 133, 274, 302], [286, 116, 345, 308]]
Chk 4514 [[275, 306, 459, 599], [452, 11, 654, 597], [141, 223, 322, 599]]
Chk 4518 [[39, 148, 99, 219], [198, 216, 347, 333]]
Chk 4519 [[353, 242, 422, 430], [489, 268, 553, 466]]
Chk 4520 [[358, 286, 598, 627], [78, 175, 224, 678]]
Chk 4521 [[106, 274, 305, 582], [358, 253, 420, 401], [43, 296, 139, 481]]
Chk 4522 [[428, 223, 519, 464], [144, 239, 227, 445]]
Chk 4523 [[16, 14, 315, 574], [493, 5, 791, 599]]
Chk 4524 [[361, 264, 433, 444], [241, 280, 288, 444], [285, 271, 332, 436]]
Chk 4525 [[46, 87, 177, 414], [121, 118, 241, 369]]
Chk 4526 [[539, 36, 798, 532], [84, 67, 328, 531], [268, 52, 597, 532]]
Chk 4527 [[417, 58, 641, 509], [54, 58, 297, 485]]
Chk 4528 [[0, 23, 381, 800], [281, 262, 708, 800]]
Chk 4530 [[38, 192, 164, 437], [307, 179, 438, 436], [424, 154, 589, 450], [579, 204, 692, 442]]
Chk 4531 [[49, 20, 318, 600], [546, 110, 649, 541], [622, 77, 800, 600]]
Chk 4532 [[462, 35, 725, 604], [92, 58, 239, 572]]
Chk 4533 [[166, 82, 342, 439], [36, 50, 247, 448]]
Chk 4534 [[370, 211, 549, 757], [26, 295, 105, 470], [296, 303, 348, 459], [91, 283, 250, 710], [342, 311, 388, 446]]
Chk 4535 [[189, 154, 332, 508], [412, 200, 515, 502]]
Chk 4536 [[235, 134, 587, 587], [222, 96, 554, 583]]
Chk 4537 [[572, 102, 701, 530], [489, 44, 598, 525]]
Chk 4538 [[186, 223, 244, 437], [483, 265, 551, 419], [607, 271, 669, 418], [567, 294, 609, 370]]
Chk 4539 [[62, 157, 278, 514], [345, 248, 434, 450], [592, 167, 703, 377], [4, 172, 78, 293], [485, 158, 535, 290], [249, 166, 287, 221], [297, 167, 332, 234]]
Chk 4541 [[363, 193, 488, 430], [477, 207, 607, 435]]
Chk 4542 [[568, 76, 762, 532], [230, 141, 428, 405], [0, 280, 89, 450], [71, 302, 119, 395]]
Chk 4543 [[0, 0, 278, 383], [295, 14, 582, 336], [416, 0, 652, 224]]
Chk 4544 [[316, 455, 470, 632], [64, 42, 357, 632], [300, 61, 586, 623]]
Chk 4545 [[3, 32, 201, 500], [187, 1, 391, 500]]
Chk 4546 [[485, 332, 580, 512], [300, 326, 495, 578], [160, 294, 313, 585]]
Chk 4547 [[377, 35, 565, 537], [129, 95, 352, 472]]
Chk 4548 [[66, 150, 518, 798], [338, 119, 656, 793], [466, 7, 657, 436]]
Chk 4549 [[422, 91, 549, 510], [508, 89, 671, 533], [91, 148, 320, 533]]
Chk 4550 [[363, 210, 473, 455], [249, 216, 410, 437]]
Chk 4551 [[74, 289, 196, 496], [299, 165, 400, 393], [362, 320, 484, 742], [467, 321, 532, 609], [0, 351, 102, 685], [338, 110, 395, 172]]
Chk 4552 [[53, 185, 152, 478], [203, 163, 331, 521], [561, 165, 612, 268], [457, 145, 505, 255]]
Chk 4553 [[82, 55, 480, 529], [328, 8, 799, 531]]
Chk 4554 [[103, 190, 211, 408], [529, 314, 604, 425]]
Chk 4556 [[537, 240, 636, 352], [377, 260, 444, 391]]
Chk 4557 [[61, 141, 237, 637], [222, 138, 337, 517], [338, 167, 406, 409], [512, 362, 643, 629], [643, 140, 710, 431]]
Chk 4558 [[158, 231, 237, 462], [233, 215, 290, 459], [398, 289, 506, 490], [679, 212, 800, 494], [538, 184, 589, 360]]
Chk 4559 [[192, 282, 291, 431], [375, 273, 579, 589], [594, 274, 661, 373]]
Chk 4560 [[430, 169, 677, 508], [241, 160, 403, 429]]
Chk 4561 [[525, 210, 659, 446], [611, 173, 704, 254], [347, 185, 546, 449], [56, 0, 295, 327], [367, 0, 611, 106], [308, 36, 368, 128], [325, 0, 380, 38]]
Chk 4562 [[334, 137, 648, 558], [74, 122, 382, 548]]
Chk 4563 [[105, 43, 722, 500], [8, 0, 782, 531]]
Chk 4564 [[437, 105, 625, 501], [337, 173, 466, 326], [192, 198, 284, 337]]
Chk 4565 [[247, 144, 313, 315], [533, 138, 599, 338]]
Chk 4566 [[556, 195, 669, 370], [740, 186, 800, 326]]
Chk 4568 [[629, 167, 800, 433], [400, 148, 634, 351], [195, 146, 355, 318], [0, 161, 200, 517]]
Chk 4570 [[465, 69, 617, 407], [208, 64, 327, 401]]
Chk 4572 [[425, 45, 642, 573], [38, 191, 129, 376], [346, 89, 482, 571]]
Chk 4573 [[37, 71, 228, 450], [421, 53, 668, 293], [572, 77, 800, 450]]
Chk 4574 [[133, 323, 208, 456], [211, 123, 449, 466], [529, 24, 783, 476]]
Chk 4575 [[243, 188, 427, 535], [133, 189, 315, 450]]
Chk 4576 [[302, 311, 471, 534], [518, 239, 662, 493], [650, 258, 741, 479]]
Chk 4577 [[88, 267, 486, 613], [436, 63, 755, 610]]
Chk 4578 [[147, 313, 236, 492], [336, 56, 457, 229]]
Chk 4579 [[640, 254, 769, 467], [105, 137, 173, 353], [508, 29, 547, 126]]
Chk 4581 [[359, 121, 491, 271], [664, 132, 760, 263], [433, 51, 715, 435], [13, 98, 566, 600]]
Chk 4582 [[519, 177, 694, 391], [262, 295, 453, 534], [58, 145, 206, 379]]
Chk 4583 [[122, 208, 269, 533], [241, 163, 376, 518], [372, 164, 485, 512], [524, 210, 653, 533], [602, 140, 695, 498]]
Chk 4584 [[37, 108, 164, 528], [115, 84, 309, 528]]
Chk 4585 [[43, 4, 171, 314], [227, 153, 507, 439], [663, 222, 800, 450]]
Chk 4586 [[90, 33, 384, 520], [617, 51, 799, 515], [380, 89, 634, 520], [1, 64, 131, 283], [2, 337, 81, 493]]
Chk 4587 [[503, 208, 577, 532], [677, 286, 779, 419], [272, 193, 320, 264], [74, 198, 110, 279], [720, 192, 798, 355]]
Chk 4589 [[0, 234, 137, 529], [642, 226, 798, 529], [122, 199, 313, 529], [597, 232, 652, 408], [375, 227, 426, 344], [364, 232, 604, 527], [270, 224, 342, 414]]
Chk 4591 [[144, 209, 344, 566], [367, 44, 623, 600]]
Chk 4592 [[326, 243, 545, 528], [640, 244, 800, 528], [615, 205, 711, 449]]
Chk 4593 [[189, 42, 428, 333], [168, 53, 270, 188], [53, 60, 202, 219], [0, 13, 89, 231], [261, 17, 329, 161]]
Chk 4594 [[39, 174, 156, 557], [136, 200, 254, 579]]
Chk 4595 [[300, 193, 358, 442], [388, 177, 446, 297], [703, 252, 725, 314], [726, 281, 785, 355], [758, 276, 800, 378]]
Chk 4596 [[37, 77, 434, 601], [463, 81, 774, 601]]
Chk 4597 [[47, 145, 422, 532], [380, 189, 749, 532], [648, 294, 800, 532]]
Chk 4598 [[156, 383, 227, 554], [112, 386, 166, 554]]
Chk 4599 [[4, 146, 286, 592], [300, 163, 466, 327], [417, 156, 711, 396]]
Chk 4600 [[181, 28, 553, 525], [3, 259, 380, 445]]
Chk 4601 [[298, 210, 797, 674], [3, 135, 313, 559]]
Chk 4603 [[105, 47, 378, 520], [382, 94, 655, 510]]
Chk 4607 [[0, 341, 38, 516], [105, 372, 152, 536], [258, 426, 304, 473], [316, 363, 361, 488], [379, 372, 419, 505]]
Chk 4608 [[409, 29, 795, 527], [17, 0, 513, 513], [234, 4, 445, 473]]
Chk 4609 [[258, 44, 402, 497], [249, 216, 538, 496]]
Chk 4610 [[21, 18, 269, 365], [262, 96, 360, 318]]
Chk 4611 [[115, 31, 327, 410], [436, 47, 648, 325], [584, 3, 799, 522]]
Chk 4612 [[262, 110, 361, 267], [180, 32, 271, 273], [121, 82, 196, 262]]
Chk 4613 [[274, 62, 473, 404], [19, 39, 288, 460]]
Chk 4614 [[186, 60, 257, 246], [405, 57, 455, 137], [490, 56, 541, 146], [580, 46, 627, 168]]
Chk 4615 [[225, 111, 318, 349], [175, 137, 232, 240]]
Chk 4616 [[426, 292, 799, 590], [387, 54, 696, 358]]
Chk 4617 [[10, 138, 152, 492], [143, 300, 315, 467], [515, 133, 640, 471]]
Chk 4618 [[264, 215, 356, 389], [486, 259, 580, 471]]
Chk 4619 [[281, 132, 404, 380], [392, 91, 514, 348]]
Chk 4620 [[230, 259, 395, 453], [0, 0, 531, 764]]
Chk 4621 [[176, 217, 318, 401], [271, 203, 373, 368], [472, 118, 639, 416], [614, 27, 710, 402], [691, 67, 769, 361], [760, 49, 800, 376]]
Chk 4622 [[0, 51, 212, 427], [148, 95, 373, 427], [404, 115, 615, 427]]
Chk 4623 [[92, 242, 198, 589], [190, 366, 489, 708], [325, 335, 446, 458]]
Chk 4624 [[11, 429, 51, 488], [425, 407, 466, 462], [360, 508, 405, 738], [417, 482, 466, 606], [451, 502, 515, 755]]
Chk 4625 [[11, 135, 238, 483], [646, 120, 795, 473], [363, 88, 506, 426], [235, 19, 263, 78]]
Chk 4626 [[89, 154, 271, 599], [511, 102, 724, 425], [376, 111, 567, 367]]
Chk 4627 [[557, 2, 800, 600], [252, 58, 400, 249], [245, 66, 289, 125]]
Chk 4628 [[118, 50, 315, 634], [500, 60, 721, 555]]
Chk 4629 [[300, 84, 702, 600], [169, 202, 436, 600]]
Chk 4630 [[128, 15, 330, 455], [410, 168, 800, 600]]
Chk 4631 [[20, 14, 221, 372], [244, 24, 484, 373]]
Chk 4632 [[387, 174, 527, 468], [341, 114, 455, 465]]
Chk 4633 [[0, 23, 126, 230], [230, 32, 319, 223], [115, 10, 279, 190]]
Chk 4635 [[113, 294, 237, 706], [157, 84, 390, 756]]
Chk 4637 [[579, 140, 647, 251], [223, 200, 265, 304], [176, 193, 221, 269], [136, 187, 193, 484], [42, 149, 130, 465]]
Chk 4638 [[323, 145, 574, 500], [99, 107, 514, 516]]
Chk 4639 [[241, 140, 438, 531], [683, 341, 749, 502], [492, 131, 645, 448]]
Chk 4640 [[450, 227, 653, 533], [127, 153, 344, 533]]
Chk 4641 [[151, 116, 481, 487], [376, 201, 800, 531]]
Chk 4642 [[10, 190, 227, 426], [9, 47, 321, 471]]
Chk 4643 [[213, 36, 239, 99], [160, 43, 189, 94], [112, 33, 139, 94]]
Chk 4644 [[428, 221, 533, 379], [612, 75, 701, 406]]

Chk 4645 [[141, 29, 511, 340], [331, 310, 564, 533], [448, 54, 800, 533]]
Chk 4647 [[28, 74, 257, 368], [150, 77, 348, 232], [388, 73, 491, 266]]
Chk 4650 [[218, 194, 266, 270], [274, 182, 345, 276], [350, 152, 398, 278]]
Chk 4651 [[377, 67, 511, 174], [559, 62, 735, 199], [208, 65, 317, 182]]
Chk 4652 [[97, 87, 168, 225], [86, 24, 133, 121], [67, 255, 124, 499]]
Chk 4653 [[120, 91, 317, 599], [222, 393, 436, 599]]
Chk 4655 [[391, 122, 725, 370], [245, 212, 578, 571]]
Chk 4657 [[508, 151, 678, 561], [360, 84, 462, 448], [33, 99, 156, 539]]
Chk 4658 [[362, 165, 613, 599], [94, 93, 297, 547]]
Chk 4659 [[379, 168, 576, 501], [328, 191, 413, 432]]
Chk 4660 [[0, 0, 525, 529], [385, 227, 753, 529]]
Chk 4661 [[171, 39, 229, 211], [223, 26, 274, 222], [336, 118, 415, 224], [699, 235, 784, 449]]
Chk 4662 [[62, 403, 217, 533], [408, 224, 583, 451]]
Chk 4663 [[20, 172, 303, 455], [251, 333, 315, 399], [318, 283, 393, 407], [524, 321, 583, 402], [596, 250, 696, 449]]
Chk 4665 [[364, 440, 469, 786], [243, 440, 356, 753]]
Chk 4666 [[44, 27, 111, 189], [153, 42, 220, 150]]
Chk 4667 [[0, 162, 43, 246], [41, 143, 110, 230], [99, 129, 177, 239], [143, 115, 221, 193], [167, 136, 338, 498], [384, 57, 433, 100], [400, 66, 482, 173], [284, 61, 514, 516]]
Chk 4668 [[571, 239, 635, 459], [131, 270, 178, 356]]
Chk 4670 [[185, 49, 425, 789], [335, 153, 630, 705]]
Chk 4671 [[265, 130, 443, 558], [443, 156, 567, 528]]
Chk 4672 [[369, 92, 668, 635], [257, 86, 481, 635]]
Chk 4673 [[262, 22, 326, 220], [93, 0, 166, 217], [281, 6, 419, 375]]
Chk 4674 [[181, 69, 319, 260], [329, 138, 412, 204]]
Chk 4675 [[141, 6, 239, 144], [72, 12, 529, 530], [439, 40, 711, 530]]
Chk 4677 [[81, 12, 317, 356], [8, 107, 129, 332]]
Chk 4678 [[194, 103, 450, 529], [540, 156, 673, 389]]
Chk 4679 [[406, 139, 574, 371], [270, 164, 338, 262], [98, 126, 161, 308], [657, 198, 686, 248], [766, 148, 799, 221]]
Chk 4682 [[51, 165, 109, 252], [139, 146, 201, 211], [379, 148, 442, 223], [427, 128, 489, 217]]
Chk 4684 [[0, 161, 163, 409], [185, 84, 437, 531], [436, 131, 682, 531], [426, 178, 513, 526], [313, 182, 351, 312], [361, 212, 412, 350], [425, 203, 458, 264]]
Chk 4685 [[0, 193, 147, 336], [0, 61, 217, 316], [181, 29, 293, 166], [170, 136, 307, 336], [280, 0, 419, 336], [368, 0, 500, 336]]
Chk 4687 [[209, 89, 356, 800], [272, 100, 449, 800]]
Chk 4688 [[178, 114, 291, 282], [267, 91, 319, 265]]
Chk 4689 [[133, 261, 327, 530], [325, 270, 444, 508], [433, 266, 536, 529]]
Chk 4691 [[353, 154, 795, 588], [74, 53, 494, 590], [139, 87, 436, 385]]
Chk 4692 [[673, 225, 751, 550], [553, 254, 672, 600], [283, 242, 336, 363], [7, 338, 210, 587], [238, 348, 372, 522]]
Chk 4695 [[154, 205, 212, 350], [273, 172, 309, 254]]
Chk 4696 [[21, 21, 532, 736], [99, 336, 685, 738]]
Chk 4697 [[391, 175, 472, 284], [208, 205, 266, 262], [313, 204, 362, 280], [468, 165, 586, 318], [165, 212, 205, 267], [131, 222, 168, 272]]
Chk 4698 [[171, 290, 230, 444], [235, 320, 305, 472], [293, 84, 337, 211], [223, 56, 269, 203], [179, 84, 221, 212]]
Chk 4699 [[95, 168, 341, 437], [383, 209, 532, 479]]
Chk 4700 [[419, 207, 588, 533], [311, 162, 443, 438]]
Chk 4701 [[7, 84, 155, 271], [365, 46, 499, 265]]
Chk 4702 [[685, 37, 792, 257], [280, 111, 404, 332], [547, 0, 655, 313]]
Chk 4703 [[449, 93, 498, 185], [617, 121, 699, 210], [154, 395, 214, 448], [279, 375, 340, 438]]
Chk 4704 [[144, 19, 424, 798], [53, 45, 286, 777]]
Chk 4705 [[240, 200, 314, 311], [307, 144, 389, 290]]
Chk 4706 [[159, 46, 534, 702], [0, 528, 275, 800]]
Chk 4707 [[531, 213, 610, 349], [459, 198, 520, 335]]
Chk 4709 [[619, 90, 788, 393], [380, 142, 634, 420], [315, 98, 408, 416], [126, 281, 313, 524], [128, 228, 215, 386]]
Chk 4710 [[58, 4, 384, 515], [357, 116, 775, 534]]
Chk 4711 [[131, 107, 402, 377], [562, 136, 800, 402]]
Chk 4712 [[406, 215, 728, 599], [137, 129, 463, 596], [6, 227, 217, 591]]
Chk 4713 [[275, 225, 341, 375], [363, 164, 441, 449], [18, 216, 47, 287], [89, 212, 126, 331]]
Chk 4714 [[197, 121, 333, 600], [481, 145, 594, 600], [386, 227, 427, 351], [357, 230, 405, 351], [702, 240, 722, 291], [576, 209, 618, 388]]
Chk 4716 [[448, 85, 662, 528], [139, 63, 245, 268]]
Chk 4717 [[67, 171, 333, 531], [286, 3, 722, 531]]
Chk 4718 [[52, 111, 192, 422], [504, 93, 592, 420]]
Chk 4719 [[653, 114, 768, 358], [134, 115, 240, 415], [22, 102, 127, 401]]
Chk 4720 [[625, 197, 747, 475], [448, 241, 561, 380]]
Chk 4721 [[161, 0, 397, 600], [507, 0, 774, 600]]
Chk 4725 [[200, 9, 264, 134], [127, 226, 443, 775], [308, 205, 454, 761]]
Chk 4726 [[48, 72, 283, 738], [379, 41, 577, 741]]
Chk 4728 [[302, 87, 793, 494], [14, 40, 381, 548]]
Chk 4729 [[468, 36, 690, 507], [68, 87, 245, 562]]
Chk 4730 [[48, 152, 338, 627], [301, 329, 465, 800]]
Chk 4733 [[103, 462, 247, 657], [314, 463, 448, 663]]
Chk 4734 [[236, 81, 491, 493], [499, 88, 669, 546]]
Chk 4735 [[341, 229, 431, 479], [607, 226, 704, 466], [444, 247, 502, 404]]
Chk 4736 [[97, 145, 235, 378], [299, 141, 340, 177], [471, 132, 518, 234], [512, 112, 603, 257]]
Chk 4737 [[274, 94, 449, 535], [4, 0, 262, 539]]
Chk 4738 [[444, 232, 471, 312], [197, 212, 230, 312]]
Chk 4739 [[0, 224, 185, 800], [161, 463, 456, 800], [342, 212, 581, 800]]
Chk 4741 [[163, 95, 570, 513], [273, 216, 543, 467]]
Chk 4742 [[363, 325, 405, 404], [554, 316, 596, 406], [606, 334, 665, 387], [611, 290, 691, 347]]
Chk 4744 [[217, 178, 278, 422], [359, 174, 466, 429], [494, 201, 570, 408]]
Chk 4745 [[185, 170, 293, 454], [104, 193, 198, 423], [119, 189, 186, 308]]
Chk 4746 [[43, 312, 79, 370], [360, 302, 441, 485], [463, 288, 592, 511]]
Chk 4747 [[24, 9, 476, 615], [649, 440, 774, 710], [540, 499, 606, 603]]
Chk 4749 [[309, 105, 580, 449], [147, 155, 341, 444], [709, 266, 799, 441], [562, 97, 780, 447]]
Chk 4750 [[143, 128, 305, 624], [314, 105, 543, 800]]
Chk 4752 [[0, 0, 359, 531], [253, 46, 589, 531], [645, 18, 800, 531]]
Chk 4753 [[334, 306, 380, 500], [399, 314, 448, 498]]
Chk 4754 [[6, 49, 286, 599], [502, 26, 799, 599], [321, 52, 703, 571]]
Chk 4755 [[489, 9, 559, 231], [124, 13, 249, 302], [571, 45, 618, 196], [632, 51, 685, 167], [314, 141, 431, 352], [377, 53, 459, 179], [81, 117, 225, 394], [724, 78, 767, 211]]
Chk 4756 [[27, 578, 278, 745], [307, 386, 510, 773]]
Chk 4758 [[292, 18, 605, 529], [0, 27, 312, 384], [402, 4, 797, 529]]
Chk 4759 [[121, 13, 207, 308], [329, 43, 489, 366]]
Chk 4760 [[192, 270, 240, 418], [318, 254, 365, 400], [245, 267, 291, 390], [292, 253, 327, 396]]
Chk 4761 [[99, 170, 241, 517], [430, 127, 518, 224]]
Chk 4762 [[388, 61, 621, 534], [177, 131, 398, 534]]
Chk 4763 [[0, 329, 125, 500], [165, 336, 296, 500], [131, 134, 215, 457]]
Chk 4764 [[396, 64, 448, 144], [248, 76, 314, 148], [102, 68, 169, 167], [130, 96, 160, 171]]
Chk 4765 [[463, 146, 766, 627], [177, 133, 371, 626]]
Chk 4766 [[145, 365, 239, 592], [213, 333, 330, 592], [621, 352, 780, 581], [587, 372, 641, 429]]
Chk 4767 [[0, 0, 520, 533], [397, 0, 800, 533]]
Chk 4769 [[14, 49, 129, 333], [163, 74, 288, 333]]
Chk 4773 [[553, 84, 628, 219], [117, 3, 294, 255], [125, 67, 373, 510], [389, 108, 607, 453], [195, 95, 567, 513], [328, 60, 486, 317]]
Chk 4775 [[210, 126, 283, 282], [263, 141, 317, 292]]
Chk 4776 [[105, 44, 212, 366], [243, 50, 358, 370], [323, 61, 411, 365]]
Chk 4778 [[36, 232, 105, 492], [85, 252, 144, 495]]
Chk 4779 [[198, 127, 327, 363], [342, 94, 488, 373], [42, 30, 168, 363]]
Chk 4780 [[462, 8, 625, 532], [219, 192, 291, 398], [664, 41, 796, 521]]
Chk 4781 [[115, 156, 445, 561], [513, 92, 767, 599], [236, 123, 305, 193], [276, 195, 433, 506], [473, 107, 619, 509]]
Chk 4782 [[62, 178, 303, 522], [0, 145, 103, 523], [333, 144, 440, 331], [430, 111, 544, 299], [585, 176, 653, 270], [619, 140, 761, 317]]
Chk 4783 [[235, 84, 384, 494], [345, 103, 455, 277], [446, 74, 521, 364], [604, 51, 684, 388], [633, 88, 795, 425], [751, 47, 800, 366]]
Chk 4784 [[353, 260, 394, 371], [279, 277, 317, 373]]
Chk 4786 [[319, 0, 799, 449], [28, 37, 551, 449]]
Chk 4787 [[573, 109, 787, 533], [19, 1, 288, 423]]
Chk 4788 [[372, 247, 464, 574], [424, 276, 528, 592], [614, 282, 749, 589]]
Chk 4789 [[116, 165, 221, 277], [321, 15, 452, 152], [537, 53, 800, 600]]
Chk 4791 [[185, 236, 375, 468], [408, 273, 483, 358]]
Chk 4792 [[432, 52, 629, 535], [205, 100, 451, 490], [10, 37, 107, 179], [74, 24, 168, 229]]
Chk 4793 [[0, 127, 231, 534], [230, 27, 435, 534], [354, 206, 589, 534]]

Chk 4794 [[57, 35, 411, 534], [381, 4, 687, 534]]
Chk 4795 [[138, 203, 259, 526], [430, 220, 495, 374], [214, 215, 304, 322]]
Chk 4796 [[271, 102, 596, 517], [49, 93, 476, 483]]
Chk 4797 [[0, 0, 178, 326], [97, 1, 355, 375], [273, 44, 500, 375], [425, 6, 500, 182]]
Chk 4798 [[212, 373, 362, 581], [101, 350, 223, 609]]
Chk 4799 [[0, 63, 354, 532], [379, 87, 467, 253], [266, 267, 800, 532], [418, 2, 767, 387], [743, 0, 800, 113]]
Chk 4800 [[298, 211, 353, 473], [347, 172, 449, 428], [485, 144, 639, 461], [703, 65, 738, 170]]
Chk 4801 [[46, 28, 249, 494], [224, 91, 345, 499]]
Chk 4802 [[419, 141, 705, 533], [160, 174, 416, 533]]
Chk 4803 [[196, 328, 315, 582], [675, 52, 743, 172]]
Chk 4804 [[132, 108, 256, 492], [44, 111, 145, 498]]
Chk 4806 [[407, 243, 600, 788], [228, 236, 406, 765], [54, 164, 250, 766]]
Chk 4808 [[251, 308, 372, 599], [428, 232, 593, 579]]
Chk 4809 [[182, 13, 274, 281], [127, 18, 208, 227]]
Chk 4811 [[198, 166, 362, 485], [342, 177, 544, 483]]
Chk 4812 [[361, 389, 410, 528], [277, 381, 334, 519], [237, 378, 273, 499]]
Chk 4813 [[401, 104, 490, 434], [528, 250, 653, 448]]
Chk 4814 [[217, 32, 307, 169], [351, 6, 427, 165], [566, 28, 640, 285], [305, 29, 357, 144], [722, 48, 789, 150], [644, 40, 753, 305]]
Chk 4815 [[0, 20, 204, 375], [155, 53, 306, 375], [260, 62, 374, 375], [346, 71, 430, 375]]
Chk 4816 [[405, 343, 533, 617], [610, 303, 725, 561]]
Chk 4817 [[562, 190, 695, 508], [427, 175, 575, 511]]
Chk 4818 [[419, 214, 618, 420], [559, 160, 727, 598]]
Chk 4819 [[450, 288, 599, 794], [231, 90, 507, 686], [201, 118, 322, 558]]
Chk 4820 [[81, 249, 283, 582], [0, 317, 437, 736]]
Chk 4821 [[175, 190, 329, 532], [366, 141, 596, 530], [535, 133, 720, 532]]
Chk 4823 [[56, 147, 311, 535], [13, 201, 164, 400], [83, 0, 278, 229], [276, 220, 554, 535]]
Chk 4824 [[0, 87, 391, 532], [417, 78, 800, 532]]
Chk 4825 [[62, 53, 230, 534], [632, 45, 779, 555]]
Chk 4828 [[97, 106, 301, 509], [301, 178, 507, 565], [268, 140, 522, 368]]
Chk 4829 [[126, 85, 291, 596], [544, 27, 770, 552]]
Chk 4831 [[119, 57, 288, 363], [325, 20, 460, 330], [486, 116, 650, 316]]
Chk 4833 [[72, 42, 538, 441], [308, 325, 513, 614]]
Chk 4836 [[266, 194, 455, 463], [149, 261, 339, 483]]
Chk 4837 [[106, 82, 306, 716], [341, 65, 537, 736]]
Chk 4838 [[2, 68, 221, 638], [308, 8, 737, 639]]
Chk 4839 [[450, 134, 623, 525], [273, 110, 476, 476]]
Chk 4840 [[660, 17, 799, 461], [142, 38, 306, 284]]
Chk 4841 [[386, 174, 544, 654], [251, 212, 392, 663]]
Chk 4842 [[220, 17, 417, 613], [485, 116, 751, 502]]
Chk 4843 [[163, 161, 355, 538], [358, 154, 491, 524], [448, 156, 555, 470]]
Chk 4844 [[433, 85, 696, 532], [56, 60, 345, 519], [256, 116, 427, 513], [764, 123, 797, 180]]
Chk 4845 [[273, 191, 321, 362], [497, 208, 556, 334], [163, 144, 224, 370]]
Chk 4846 [[55, 202, 197, 614], [249, 270, 371, 710]]
Chk 4847 [[171, 372, 365, 603], [598, 443, 776, 595], [639, 341, 715, 537], [654, 294, 727, 369]]
Chk 4850 [[162, 438, 272, 725], [90, 453, 174, 710]]
Chk 4851 [[110, 60, 377, 535], [354, 9, 571, 529], [549, 30, 800, 535]]
Chk 4852 [[208, 159, 419, 404], [442, 99, 625, 522], [194, 209, 228, 258], [723, 172, 774, 288]]
Chk 4853 [[448, 140, 560, 518], [366, 181, 417, 449], [305, 165, 373, 454], [140, 175, 299, 602]]
Chk 4854 [[175, 176, 262, 473], [45, 150, 177, 492], [281, 202, 382, 492], [173, 314, 228, 469]]
Chk 4855 [[109, 95, 350, 455], [336, 122, 758, 533]]
Chk 4857 [[439, 127, 513, 346], [537, 146, 582, 335], [370, 155, 419, 223], [17, 160, 54, 223]]
Chk 4858 [[250, 90, 501, 411], [29, 120, 277, 415]]
Chk 4859 [[315, 204, 441, 497], [239, 220, 328, 313]]
Chk 4860 [[339, 64, 486, 362], [14, 37, 148, 353], [31, 79, 149, 209]]
Chk 4863 [[145, 207, 191, 301], [111, 234, 149, 323]]
Chk 4864 [[0, 272, 248, 498], [101, 104, 357, 394], [175, 43, 313, 267]]
Chk 4865 [[30, 231, 229, 532], [402, 215, 658, 532], [170, 190, 439, 503]]
Chk 4866 [[75, 36, 268, 400], [180, 223, 383, 395], [253, 319, 372, 415], [332, 55, 421, 355], [383, 217, 511, 419], [575, 230, 704, 411], [643, 57, 800, 401]]
Chk 4867 [[383, 41, 477, 259], [278, 66, 358, 273], [333, 103, 367, 152]]
Chk 4870 [[694, 278, 745, 427], [382, 228, 457, 438], [762, 312, 794, 431], [303, 256, 431, 453]]
Chk 4871 [[250, 183, 663, 599], [98, 130, 495, 587]]
Chk 4872 [[0, 80, 221, 375], [224, 74, 500, 375]]
Chk 4875 [[493, 222, 565, 338], [677, 228, 792, 538]]
Chk 4876 [[382, 243, 584, 588], [97, 273, 599, 585]]
Chk 4877 [[584, 297, 800, 534], [515, 232, 678, 416], [278, 237, 480, 493], [80, 116, 316, 522], [0, 159, 115, 465]]
Chk 4878 [[152, 33, 398, 799], [368, 58, 642, 799]]
Chk 4879 [[32, 115, 321, 533], [379, 111, 632, 531], [520, 305, 800, 533]]
Chk 4880 [[84, 177, 214, 531], [303, 233, 384, 398], [382, 180, 451, 416], [590, 192, 731, 518]]
Chk 4881 [[0, 282, 480, 790], [194, 119, 497, 560]]
Chk 4882 [[64, 157, 322, 534], [319, 49, 718, 534]]
Chk 4883 [[360, 390, 441, 575], [250, 379, 397, 615]]
Chk 4884 [[671, 40, 799, 445], [138, 191, 280, 461], [114, 37, 247, 417]]
Chk 4886 [[97, 47, 336, 533], [332, 68, 682, 533], [603, 250, 800, 533]]
Chk 4887 [[142, 151, 235, 402], [93, 154, 149, 370], [12, 170, 49, 228], [240, 167, 289, 223], [363, 147, 399, 222], [462, 151, 498, 272], [477, 152, 514, 272], [515, 148, 540, 239]]
Chk 4888 [[58, 137, 136, 333], [230, 30, 275, 117], [263, 8, 308, 95], [281, 1, 344, 82], [344, 120, 403, 208]]
Chk 4890 [[216, 175, 312, 337], [302, 106, 370, 306], [432, 186, 496, 330], [247, 96, 305, 276]]
Chk 4891 [[45, 188, 373, 559], [228, 236, 363, 532]]
Chk 4892 [[176, 124, 248, 277], [131, 117, 173, 260]]
Chk 4893 [[111, 195, 276, 663], [304, 190, 438, 640]]
Chk 4894 [[492, 323, 637, 558], [451, 241, 583, 479]]
Chk 4895 [[11, 5, 329, 536], [316, 0, 572, 545]]
Chk 4896 [[313, 10, 799, 632], [20, 51, 398, 632]]
Chk 4897 [[399, 99, 499, 331], [0, 153, 74, 331]]
Chk 4898 [[79, 78, 350, 757], [348, 0, 596, 754]]
Chk 4899 [[345, 441, 419, 638], [222, 385, 301, 688], [20, 251, 130, 736], [0, 121, 48, 665]]
Chk 4901 [[98, 66, 263, 688], [242, 89, 353, 570], [378, 46, 523, 689]]
Chk 4902 [[407, 135, 464, 334], [138, 136, 291, 531], [474, 132, 545, 314], [559, 128, 618, 335], [238, 105, 390, 513]]
Chk 4903 [[95, 115, 193, 368], [83, 115, 199, 451], [358, 104, 534, 528], [548, 29, 741, 432]]
Chk 4904 [[211, 273, 308, 400], [332, 282, 400, 522]]
Chk 4905 [[380, 366, 571, 535], [289, 345, 396, 535], [235, 325, 276, 391], [210, 272, 266, 381]]
Chk 4907 [[186, 63, 559, 786], [16, 52, 345, 799]]
Chk 4908 [[302, 124, 740, 602], [284, 110, 706, 602], [172, 47, 441, 488], [45, 13, 154, 249]]
Chk 4909 [[0, 0, 475, 406], [0, 188, 618, 600]]
Chk 4910 [[16, 30, 589, 581], [245, 178, 705, 595]]
Chk 4912 [[344, 292, 409, 385], [616, 314, 759, 440], [183, 297, 255, 378], [71, 318, 115, 369], [0, 301, 46, 374], [23, 415, 83, 564]]
Chk 4913 [[350, 42, 459, 156], [571, 18, 728, 235]]
Chk 4914 [[155, 148, 384, 459], [363, 239, 465, 575], [487, 7, 599, 141], [432, 216, 547, 541]]
Chk 4917 [[127, 284, 260, 506], [281, 86, 358, 274], [462, 75, 508, 272], [395, 28, 456, 250]]
Chk 4918 [[276, 15, 516, 568], [25, 45, 250, 575]]
Chk 4920 [[185, 270, 294, 509], [61, 251, 157, 509]]
Chk 4921 [[312, 54, 507, 330], [142, 103, 321, 372], [558, 134, 710, 360], [81, 97, 542, 310]]
Chk 4922 [[116, 211, 243, 587], [331, 225, 440, 590], [504, 223, 659, 597], [214, 174, 354, 596], [436, 202, 539, 599]]
Chk 4923 [[373, 29, 561, 508], [233, 178, 425, 469]]
Chk 4924 [[331, 220, 399, 432], [496, 237, 555, 402]]
Chk 4925 [[123, 104, 266, 416], [247, 100, 386, 441], [669, 112, 716, 212], [610, 114, 650, 203]]
Chk 4927 [[112, 110, 300, 434], [664, 103, 799, 434], [437, 120, 603, 434], [0, 100, 99, 434], [247, 116, 445, 434]]
Chk 4932 [[0, 261, 155, 540], [157, 121, 621, 526], [639, 184, 798, 548]]
Chk 4933 [[413, 123, 680, 599], [170, 60, 422, 599]]
Chk 4934 [[0, 314, 157, 706], [147, 204, 329, 540], [367, 165, 534, 686]]
Chk 4935 [[101, 10, 437, 533], [392, 21, 735, 533], [0, 113, 131, 533]]
Chk 4937 [[8, 72, 143, 266], [169, 4, 271, 341], [383, 17, 475, 198]]
Chk 4938 [[201, 55, 360, 470], [312, 88, 491, 499]]
Chk 4939 [[219, 0, 604, 389], [433, 146, 724, 389]]
Chk 4940 [[9, 11, 268, 366], [282, 34, 454, 293]]
Chk 4941 [[372, 39, 799, 530], [18, 59, 546, 530]]

Chk 4942 [[222, 293, 461, 732], [0, 18, 339, 670], [280, 55, 520, 478]]
Chk 4943 [[248, 274, 485, 578], [68, 228, 246, 570]]
Chk 4944 [[499, 133, 577, 274], [205, 133, 251, 241], [17, 126, 55, 226]]
Chk 4945 [[476, 54, 553, 268], [192, 7, 270, 328], [55, 163, 132, 260], [19, 164, 54, 237]]
Chk 4946 [[0, 550, 534, 783], [0, 0, 534, 614]]
Chk 4947 [[456, 356, 570, 649], [263, 201, 449, 750], [20, 262, 180, 589], [118, 156, 359, 677]]
Chk 4949 [[0, 103, 315, 580], [417, 13, 800, 580]]
Chk 4950 [[48, 162, 370, 756], [479, 221, 603, 325]]
Chk 4951 [[252, 57, 772, 527], [3, 70, 355, 528]]
Chk 4953 [[84, 90, 199, 479], [255, 62, 375, 459], [344, 90, 384, 153], [400, 64, 483, 396], [479, 85, 526, 293], [560, 52, 713, 514], [692, 50, 781, 381]]
Chk 4954 [[192, 288, 240, 366], [360, 306, 478, 452], [82, 283, 216, 533]]
Chk 4955 [[648, 140, 739, 436], [101, 103, 187, 250]]
Chk 4956 [[239, 37, 589, 492], [543, 0, 799, 515]]
Chk 4957 [[345, 41, 517, 424], [224, 107, 351, 484]]
Chk 4958 [[144, 70, 300, 492], [375, 310, 656, 611], [649, 163, 717, 359], [492, 195, 544, 348], [700, 159, 759, 357], [408, 181, 476, 349]]
Chk 4959 [[138, 194, 191, 353], [344, 155, 417, 336]]
Chk 4960 [[328, 300, 456, 665], [138, 316, 250, 652]]
Chk 4961 [[600, 226, 642, 396], [677, 209, 722, 391], [179, 314, 217, 428], [293, 191, 328, 307], [456, 41, 507, 149], [335, 73, 399, 174], [39, 403, 74, 471]]
Chk 4963 [[310, 205, 497, 600], [400, 4, 654, 600]]
Chk 4964 [[384, 16, 625, 687], [106, 28, 485, 696]]
Chk 4967 [[268, 157, 470, 510], [225, 106, 722, 579]]
Chk 4968 [[251, 194, 402, 533], [371, 208, 478, 533]]
Chk 4969 [[69, 0, 337, 742], [326, 50, 532, 693]]
Chk 4970 [[439, 183, 563, 599], [104, 295, 244, 510]]
Chk 4971 [[189, 212, 392, 470], [393, 192, 569, 481]]
Chk 4972 [[115, 18, 355, 799], [241, 43, 489, 774]]
Chk 4974 [[81, 68, 318, 799], [239, 102, 408, 753]]
Chk 4975 [[97, 65, 283, 559], [420, 98, 532, 492]]
Chk 4976 [[175, 27, 466, 399], [27, 99, 147, 350]]
Chk 4979 [[0, 132, 126, 600], [101, 168, 162, 599], [380, 179, 534, 600], [374, 195, 558, 600], [644, 316, 756, 455], [736, 167, 800, 449]]
Chk 4980 [[162, 212, 254, 386], [232, 192, 431, 439]]
Chk 4981 [[181, 348, 565, 507], [229, 90, 298, 198], [159, 52, 602, 421]]
Chk 4982 [[21, 64, 368, 532], [177, 93, 574, 532]]
Chk 4984 [[163, 327, 209, 442], [571, 359, 621, 444], [63, 344, 95, 406], [421, 212, 466, 280], [264, 322, 315, 445], [246, 249, 296, 328], [132, 340, 162, 421]]
Chk 4985 [[23, 0, 304, 799], [263, 88, 567, 784]]
Chk 4986 [[73, 95, 191, 395], [418, 131, 533, 413], [535, 141, 597, 265], [273, 140, 346, 388], [230, 148, 281, 286]]
Chk 4987 [[498, 208, 592, 403], [363, 207, 420, 319]]
Chk 4988 [[0, 257, 31, 349], [604, 209, 684, 322], [344, 212, 431, 338], [6, 215, 236, 593], [414, 279, 800, 600]]
Chk 4989 [[81, 226, 494, 799], [12, 77, 412, 535]]
Chk 4990 [[0, 98, 369, 632], [308, 217, 541, 619], [481, 15, 799, 612]]
Chk 4991 [[521, 63, 736, 529], [154, 54, 410, 533], [334, 217, 593, 533]]
Chk 4992 [[353, 91, 464, 373], [203, 53, 293, 374], [132, 65, 204, 370]]
Chk 4993 [[464, 43, 799, 501], [157, 20, 489, 522]]
Chk 4994 [[83, 118, 133, 277], [118, 125, 159, 171], [168, 141, 224, 217], [199, 64, 231, 171], [325, 97, 373, 202]]
Chk 4995 [[197, 176, 278, 451], [298, 208, 392, 477], [347, 311, 412, 654], [400, 199, 534, 466], [605, 216, 662, 502], [657, 266, 723, 564]]
Chk 4996 [[226, 16, 530, 587], [382, 225, 659, 598], [398, 237, 684, 598]]
Chk 4997 [[276, 360, 500, 773], [113, 287, 300, 665]]
Chk 4998 [[295, 262, 421, 474], [0, 350, 91, 765], [82, 209, 238, 787], [30, 302, 66, 408]]
Chk 4999 [[349, 112, 463, 334], [86, 121, 210, 320], [211, 126, 351, 324]]
Chk 5000 [[382, 68, 642, 532], [35, 54, 355, 532]]
Chk 5001 [[46, 178, 101, 337], [298, 176, 353, 316], [115, 150, 152, 246], [274, 120, 318, 198], [384, 132, 425, 208], [330, 172, 374, 274]]
Chk 5002 [[241, 116, 318, 302], [141, 146, 215, 295]]
Chk 5003 [[15, 137, 101, 347], [55, 47, 122, 322], [298, 114, 370, 399], [583, 180, 769, 511], [44, 333, 197, 530]]
Chk 5004 [[144, 165, 446, 590], [92, 197, 280, 594]]
Chk 5005 [[220, 116, 303, 426], [119, 129, 198, 428], [293, 114, 368, 418]]
Chk 5007 [[493, 139, 630, 518], [274, 139, 405, 533]]
Chk 5008 [[276, 42, 357, 213], [356, 24, 446, 197]]
Chk 5009 [[225, 392, 367, 545], [114, 388, 226, 538]]
Chk 5011 [[27, 64, 320, 522], [309, 93, 557, 522], [528, 107, 799, 522]]
Chk 5014 [[136, 60, 248, 334], [288, 92, 368, 279]]
Chk 5015 [[50, 17, 182, 329], [298, 103, 411, 252]]
Chk 5016 [[109, 214, 333, 590], [287, 52, 581, 666], [125, 25, 383, 313]]
Chk 5017 [[16, 115, 323, 583], [434, 14, 769, 340]]
Chk 5019 [[410, 37, 494, 326], [8, 52, 99, 329], [313, 67, 365, 142], [371, 44, 437, 312], [326, 77, 356, 127]]
Chk 5020 [[0, 293, 234, 600], [423, 244, 707, 600], [368, 68, 483, 311], [105, 118, 324, 399]]
Chk 5021 [[14, 173, 91, 347], [56, 214, 186, 322], [239, 207, 393, 423], [405, 208, 516, 411], [572, 201, 731, 415]]
Chk 5022 [[117, 122, 218, 396], [299, 129, 408, 344], [171, 259, 320, 404]]
Chk 5023 [[135, 209, 207, 393], [432, 187, 535, 302], [87, 177, 145, 359]]
Chk 5024 [[283, 29, 455, 254], [96, 14, 257, 292]]
Chk 5025 [[10, 82, 146, 317], [234, 105, 355, 300]]
Chk 5027 [[256, 253, 799, 644], [1, 22, 477, 640]]
Chk 5028 [[333, 10, 541, 372], [179, 73, 360, 416]]
Chk 5029 [[39, 81, 302, 783], [270, 80, 539, 797], [0, 283, 39, 384]]
Chk 5030 [[210, 90, 489, 706], [165, 233, 385, 636]]
Chk 5031 [[300, 35, 800, 534], [392, 44, 658, 534], [140, 48, 388, 534], [0, 3, 265, 534]]
Chk 5032 [[352, 224, 580, 449], [118, 162, 544, 449]]
Chk 5033 [[276, 0, 799, 523], [0, 222, 303, 518]]
Chk 5034 [[519, 113, 653, 433], [606, 199, 746, 441], [698, 177, 800, 453]]
Chk 5035 [[95, 260, 146, 379], [308, 258, 351, 453], [406, 258, 449, 386], [444, 258, 483, 391], [645, 241, 682, 339], [743, 266, 797, 376]]
Chk 5036 [[422, 522, 493, 683], [98, 515, 170, 655], [226, 520, 280, 665]]
Chk 5038 [[326, 263, 383, 404], [455, 179, 528, 367], [371, 439, 403, 494]]
Chk 5039 [[463, 234, 600, 399], [579, 266, 660, 358]]
Chk 5040 [[451, 52, 613, 339], [270, 48, 468, 339]]
Chk 5041 [[112, 31, 260, 246], [89, 197, 214, 474]]
Chk 5043 [[64, 0, 313, 332], [236, 80, 435, 332]]
Chk 5044 [[509, 209, 641, 366], [165, 244, 232, 391], [254, 240, 348, 453]]
Chk 5045 [[0, 0, 263, 533], [88, 21, 466, 461], [514, 55, 800, 511]]
Chk 5046 [[104, 122, 285, 559], [320, 80, 564, 525]]
Chk 5047 [[375, 149, 491, 490], [164, 158, 290, 496], [282, 160, 380, 459], [156, 171, 188, 241]]
Chk 5048 [[2, 132, 254, 800], [122, 262, 531, 727], [0, 41, 51, 232], [59, 26, 114, 233], [70, 51, 127, 227]]
Chk 5049 [[420, 133, 577, 426], [146, 109, 217, 280]]
Chk 5050 [[384, 100, 695, 480], [8, 0, 393, 576]]
Chk 5051 [[126, 74, 347, 560], [397, 132, 583, 599]]
Chk 5052 [[64, 239, 294, 514], [0, 70, 446, 483], [512, 0, 800, 533], [347, 0, 630, 335]]
Chk 5053 [[80, 296, 126, 423], [286, 296, 326, 439], [371, 288, 421, 442], [416, 281, 463, 439], [675, 322, 737, 474]]
Chk 5054 [[12, 274, 328, 600], [255, 374, 385, 598], [467, 385, 592, 600], [387, 98, 782, 600]]
Chk 5055 [[632, 109, 698, 264], [139, 113, 278, 392], [702, 113, 753, 264], [314, 133, 404, 333], [769, 142, 796, 229]]
Chk 5056 [[32, 183, 171, 341], [164, 155, 311, 306], [581, 143, 708, 321], [495, 163, 611, 313], [394, 212, 674, 519]]
Chk 5057 [[47, 293, 162, 531], [326, 279, 421, 529], [499, 279, 596, 531], [586, 10, 715, 296]]
Chk 5058 [[175, 18, 437, 509], [386, 60, 646, 530], [463, 195, 492, 228]]
Chk 5059 [[428, 106, 715, 527], [125, 3, 442, 546]]
Chk 5060 [[139, 193, 282, 523], [280, 141, 407, 468], [170, 567, 279, 800], [355, 633, 410, 777]]
Chk 5061 [[84, 168, 221, 358], [301, 178, 415, 600], [656, 187, 718, 325], [467, 125, 571, 328], [386, 136, 445, 334]]
Chk 5062 [[148, 73, 316, 458], [302, 71, 410, 330], [212, 82, 408, 483]]
Chk 5063 [[6, 168, 313, 531], [435, 82, 793, 531]]
Chk 5064 [[203, 166, 373, 472], [370, 19, 477, 192], [120, 37, 183, 219], [160, 20, 201, 196]]
Chk 5065 [[204, 99, 312, 320], [147, 139, 216, 290]]
Chk 5066 [[320, 225, 422, 531], [399, 238, 533, 538]]
Chk 5067 [[103, 220, 252, 482], [272, 176, 387, 481], [402, 204, 517, 488]]
Chk 5068 [[210, 562, 473, 758], [157, 246, 685, 800], [0, 32, 456, 689]]
Chk 5069 [[78, 162, 117, 303], [186, 165, 225, 301], [219, 150, 267, 283]]
Chk 5072 [[16, 179, 478, 639], [565, 106, 711, 532]]
Chk 5073 [[229, 35, 365, 432], [26, 80, 184, 435]]

Chk 5075 [[8, 137, 305, 529], [309, 25, 761, 526]]
Chk 5076 [[357, 329, 489, 777], [262, 316, 362, 502]]
Chk 5077 [[331, 179, 596, 503], [212, 321, 389, 517]]
Chk 5078 [[138, 90, 387, 526], [522, 261, 773, 488]]
Chk 5079 [[376, 254, 436, 402], [338, 252, 383, 389]]
Chk 5080 [[14, 138, 197, 382], [624, 127, 800, 541]]
Chk 5081 [[0, 31, 110, 505], [273, 40, 323, 81], [267, 0, 433, 486], [561, 33, 647, 379], [672, 6, 756, 382]]
Chk 5082 [[203, 143, 398, 533], [341, 117, 610, 533]]
Chk 5083 [[310, 80, 400, 303], [52, 110, 184, 313], [476, 162, 494, 212], [165, 120, 243, 252], [159, 79, 197, 165], [109, 108, 164, 188], [171, 128, 226, 186]]
Chk 5084 [[84, 15, 429, 514], [471, 0, 788, 478]]
Chk 5085 [[309, 121, 607, 530], [621, 337, 799, 530], [0, 210, 286, 530], [235, 252, 386, 530]]
Chk 5086 [[57, 194, 420, 600], [389, 0, 800, 516]]
Chk 5087 [[275, 112, 409, 522], [70, 79, 252, 459]]
Chk 5088 [[292, 279, 352, 435], [215, 274, 264, 426]]
Chk 5089 [[326, 14, 486, 586], [164, 0, 379, 603]]
Chk 5090 [[111, 356, 157, 500], [48, 318, 110, 459], [81, 252, 127, 342], [327, 252, 367, 346], [213, 240, 257, 335]]
Chk 5092 [[693, 19, 799, 521], [156, 121, 280, 277]]
Chk 5093 [[521, 96, 788, 479], [366, 209, 496, 506], [112, 200, 424, 511]]
Chk 5094 [[118, 226, 183, 452], [392, 237, 470, 346], [546, 151, 590, 337], [418, 142, 503, 307], [506, 133, 572, 292]]
Chk 5095 [[346, 151, 476, 346], [207, 69, 439, 599], [708, 178, 799, 377], [73, 58, 210, 565]]
Chk 5096 [[102, 467, 293, 695], [405, 485, 479, 642], [449, 474, 527, 641]]
Chk 5099 [[0, 0, 385, 600], [359, 88, 752, 597], [390, 58, 773, 592]]
Chk 5100 [[29, 434, 100, 618], [220, 361, 269, 504], [297, 338, 354, 449]]
Chk 5101 [[383, 218, 506, 494], [310, 295, 398, 468], [30, 236, 108, 483]]
Chk 5102 [[640, 211, 701, 434], [564, 225, 616, 361], [168, 245, 244, 481], [492, 171, 558, 346], [74, 258, 176, 458]]
Chk 5104 [[299, 6, 594, 488], [0, 151, 350, 436]]
Chk 5105 [[440, 297, 510, 456], [229, 91, 307, 328]]
Chk 5106 [[32, 69, 215, 401], [505, 36, 748, 401]]
Chk 5107 [[274, 168, 339, 319], [511, 161, 582, 467], [615, 169, 673, 426], [270, 123, 325, 204], [0, 270, 110, 515], [695, 155, 740, 377]]
Chk 5108 [[0, 111, 143, 279], [0, 196, 484, 421], [0, 251, 753, 534]]
Chk 5109 [[449, 82, 564, 475], [254, 96, 411, 473], [101, 88, 142, 215], [0, 96, 38, 279]]
Chk 5110 [[559, 140, 725, 527], [318, 143, 415, 459]]
Chk 5111 [[23, 25, 193, 289], [192, 64, 331, 250], [338, 23, 477, 239]]
Chk 5112 [[402, 120, 615, 393], [108, 118, 236, 332], [225, 92, 438, 415], [604, 146, 799, 412], [356, 107, 435, 359]]
Chk 5113 [[57, 184, 157, 400], [199, 149, 321, 485]]
Chk 5114 [[104, 287, 242, 421], [264, 297, 342, 399]]
Chk 5115 [[71, 102, 477, 570], [429, 0, 777, 570]]
Chk 5116 [[304, 115, 460, 577], [431, 179, 544, 545]]
Chk 5117 [[73, 108, 259, 600], [3, 114, 90, 317], [265, 180, 368, 508], [217, 210, 261, 319]]
Chk 5118 [[446, 145, 525, 271], [179, 117, 258, 431], [1, 160, 38, 228], [375, 125, 423, 184]]
Chk 5119 [[296, 229, 457, 533], [564, 225, 738, 533], [139, 195, 267, 533], [67, 175, 197, 533]]
Chk 5121 [[79, 182, 154, 340], [135, 181, 185, 321], [207, 173, 278, 312], [247, 167, 295, 287]]
Chk 5122 [[142, 60, 279, 212], [562, 87, 636, 171], [451, 66, 582, 194], [639, 80, 758, 341], [752, 55, 796, 159]]
Chk 5123 [[374, 264, 435, 428], [100, 343, 276, 558], [188, 246, 242, 354]]
Chk 5124 [[4, 229, 117, 531], [379, 225, 472, 362], [261, 262, 341, 382]]
Chk 5125 [[118, 193, 227, 482], [219, 208, 420, 636], [287, 166, 416, 269]]
Chk 5126 [[128, 124, 378, 800], [278, 169, 633, 800]]
Chk 5127 [[206, 187, 268, 441], [318, 215, 394, 445]]
Chk 5128 [[293, 97, 800, 514], [53, 56, 617, 533]]
Chk 5129 [[45, 64, 264, 371], [248, 46, 494, 401], [491, 61, 772, 411], [524, 1, 683, 186], [74, 0, 180, 147], [184, 0, 282, 137]]
Chk 5130 [[90, 164, 348, 755], [323, 243, 452, 415], [319, 230, 453, 673], [58, 226, 198, 663]]
Chk 5131 [[278, 4, 572, 800], [150, 135, 319, 645]]
Chk 5132 [[296, 221, 499, 533], [0, 116, 346, 533], [479, 41, 800, 533]]
Chk 5134 [[194, 52, 289, 367], [434, 66, 545, 462], [275, 105, 444, 797]]
Chk 5135 [[54, 206, 332, 533], [505, 201, 800, 508], [229, 91, 512, 491]]
Chk 5136 [[371, 72, 604, 678], [156, 44, 350, 660]]
Chk 5137 [[15, 77, 114, 533], [311, 62, 530, 778], [530, 77, 791, 750], [566, 26, 668, 236]]
Chk 5138 [[389, 0, 666, 486], [298, 244, 533, 500]]
Chk 5139 [[241, 91, 376, 332], [364, 92, 453, 332]]
Chk 5140 [[286, 92, 466, 533], [536, 197, 609, 427]]
Chk 5142 [[13, 287, 267, 500], [0, 367, 531, 637]]
Chk 5143 [[358, 29, 743, 629], [51, 96, 446, 628]]
Chk 5144 [[43, 165, 136, 361], [136, 135, 247, 382], [257, 13, 602, 429]]
Chk 5145 [[255, 14, 448, 337], [87, 45, 263, 304]]
Chk 5146 [[262, 171, 402, 702], [317, 74, 600, 800], [0, 89, 259, 800]]
Chk 5147 [[108, 16, 489, 532], [440, 15, 800, 532]]
Chk 5148 [[41, 150, 309, 521], [525, 143, 769, 532], [380, 114, 576, 498]]
Chk 5150 [[87, 39, 251, 528], [476, 197, 601, 363], [2, 196, 47, 403], [269, 186, 343, 288], [52, 211, 102, 353], [569, 207, 604, 301], [222, 175, 272, 348]]
Chk 5151 [[333, 43, 575, 566], [26, 40, 475, 567]]
Chk 5152 [[231, 45, 433, 594], [70, 51, 239, 592]]
Chk 5155 [[536, 143, 653, 417], [565, 130, 637, 233]]
Chk 5156 [[68, 175, 164, 310], [273, 170, 360, 274]]
Chk 5157 [[0, 302, 142, 738], [137, 391, 257, 757], [402, 385, 600, 800]]
Chk 5158 [[305, 95, 768, 490], [22, 127, 391, 477]]
Chk 5159 [[69, 109, 440, 556], [389, 88, 622, 569], [561, 144, 770, 569]]
Chk 5160 [[231, 148, 377, 448], [537, 71, 689, 519], [112, 180, 147, 238]]
Chk 5161 [[0, 88, 264, 533], [541, 96, 723, 388], [328, 84, 478, 287]]
Chk 5162 [[776, 150, 800, 306], [436, 214, 513, 312], [315, 173, 367, 274], [103, 177, 148, 222]]
Chk 5163 [[305, 173, 352, 336], [350, 171, 394, 352]]
Chk 5164 [[94, 247, 177, 478], [175, 205, 235, 411], [535, 193, 604, 382], [635, 178, 696, 387]]
Chk 5167 [[598, 135, 784, 534], [45, 208, 210, 416], [180, 202, 264, 359]]
Chk 5169 [[21, 188, 201, 398], [369, 165, 550, 377]]
Chk 5170 [[167, 37, 324, 485], [33, 29, 153, 480], [275, 65, 351, 433]]
Chk 5171 [[30, 160, 101, 359], [706, 176, 775, 380], [156, 165, 211, 319], [229, 150, 275, 310], [630, 195, 688, 379], [436, 174, 475, 293], [3, 200, 33, 336]]
Chk 5172 [[416, 99, 571, 379], [610, 109, 671, 356]]
Chk 5174 [[8, 174, 340, 800], [215, 139, 534, 800]]
Chk 5176 [[436, 183, 578, 522], [294, 198, 436, 351]]
Chk 5177 [[0, 176, 78, 454], [149, 181, 293, 362], [276, 94, 417, 310], [378, 565, 537, 748]]
Chk 5178 [[336, 196, 429, 389], [257, 162, 347, 364], [439, 191, 509, 380], [529, 160, 591, 363], [616, 149, 687, 350]]
Chk 5179 [[88, 104, 206, 310], [365, 133, 486, 281]]
Chk 5180 [[330, 54, 428, 341], [88, 87, 161, 201], [238, 53, 314, 341]]
Chk 5181 [[295, 62, 410, 297], [98, 132, 197, 288]]
Chk 5182 [[362, 144, 421, 292], [109, 135, 157, 249], [189, 163, 215, 230], [429, 160, 464, 202]]
Chk 5183 [[294, 162, 685, 513], [510, 231, 678, 516]]
Chk 5184 [[505, 33, 798, 573], [374, 203, 566, 517], [89, 192, 159, 264]]
Chk 5185 [[0, 499, 291, 799], [147, 227, 289, 595], [349, 249, 572, 691]]
Chk 5186 [[205, 259, 301, 366], [318, 179, 393, 378], [417, 171, 490, 375], [587, 172, 688, 398]]
Chk 5187 [[326, 211, 453, 313], [0, 115, 221, 362]]
Chk 5188 [[1, 293, 78, 509], [134, 226, 277, 429], [448, 121, 551, 305], [132, 210, 247, 417]]
Chk 5189 [[225, 166, 446, 737], [18, 151, 230, 734], [22, 420, 64, 510]]
Chk 5190 [[273, 215, 352, 477], [353, 201, 437, 453], [175, 208, 277, 481], [475, 245, 617, 428]]
Chk 5191 [[57, 182, 198, 600], [168, 154, 285, 348], [259, 177, 421, 353], [366, 253, 543, 600], [430, 188, 561, 368]]
Chk 5192 [[0, 54, 110, 295], [245, 143, 429, 276], [414, 178, 500, 374]]
Chk 5193 [[144, 135, 259, 666], [222, 99, 503, 627]]
Chk 5194 [[0, 70, 367, 747], [313, 191, 400, 440], [371, 99, 756, 699]]
Chk 5195 [[88, 110, 305, 534], [471, 132, 691, 503], [707, 54, 763, 158]]
Chk 5196 [[71, 68, 187, 310], [203, 47, 283, 326]]
Chk 5197 [[159, 202, 301, 451], [328, 221, 503, 536], [460, 202, 543, 297], [0, 57, 98, 485], [114, 192, 165, 284]]
Chk 5199 [[107, 140, 317, 532], [363, 130, 565, 532]]
Chk 5200 [[316, 131, 380, 190], [255, 125, 302, 177], [82, 116, 110, 157]]
Chk 5201 [[289, 120, 395, 338], [139, 125, 267, 357]]
Chk 5202 [[200, 79, 294, 363], [473, 57, 626, 347]]
Chk 5204 [[173, 31, 408, 342], [0, 100, 172, 340], [714, 216, 765, 322], [514, 230, 561, 319]]
Chk 5205 [[514, 181, 777, 545], [10, 7, 207, 527], [174, 28, 742, 553]]

Chk 5206 [[0, 0, 221, 697], [123, 0, 480, 698]]
Chk 5207 [[1, 252, 59, 405], [100, 193, 223, 471], [284, 237, 444, 361]]
Chk 5208 [[261, 129, 423, 532], [524, 109, 720, 532], [428, 90, 574, 532]]
Chk 5209 [[56, 63, 272, 728], [270, 42, 490, 780]]
Chk 5210 [[352, 63, 799, 526], [108, 67, 453, 519]]
Chk 5211 [[479, 77, 761, 532], [290, 83, 612, 532], [22, 35, 315, 532], [691, 299, 765, 522]]
Chk 5212 [[45, 98, 274, 600], [229, 190, 360, 599], [726, 164, 800, 417]]
Chk 5213 [[6, 254, 172, 393], [142, 157, 205, 325], [213, 223, 295, 314]]
Chk 5214 [[100, 98, 211, 374], [189, 109, 300, 373]]
Chk 5215 [[684, 211, 736, 454], [614, 211, 678, 524], [289, 181, 419, 499]]
Chk 5216 [[331, 49, 690, 535], [168, 122, 496, 535]]
Chk 5217 [[520, 195, 622, 329], [32, 292, 416, 565], [450, 193, 521, 262]]
Chk 5218 [[268, 85, 464, 374], [0, 102, 85, 316]]
Chk 5219 [[387, 282, 496, 431], [222, 239, 316, 440], [762, 349, 799, 417]]
Chk 5220 [[0, 55, 161, 533], [138, 0, 479, 533], [404, 76, 627, 458], [549, 99, 760, 431]]
Chk 5221 [[484, 70, 791, 534], [480, 285, 569, 441], [251, 92, 515, 534], [0, 48, 371, 534]]
Chk 5222 [[175, 382, 793, 600], [28, 10, 568, 588]]
Chk 5223 [[387, 68, 566, 575], [605, 107, 762, 562], [142, 110, 294, 558]]
Chk 5225 [[388, 15, 670, 581], [282, 253, 369, 400], [8, 91, 58, 346]]
Chk 5226 [[372, 354, 506, 742], [168, 441, 311, 546], [211, 280, 298, 473], [289, 359, 363, 457]]
Chk 5227 [[273, 120, 313, 220], [183, 110, 231, 235]]
Chk 5228 [[41, 130, 129, 382], [368, 152, 431, 319], [270, 175, 316, 289]]
Chk 5229 [[125, 206, 303, 532], [277, 213, 439, 527]]
Chk 5230 [[88, 28, 460, 533], [337, 102, 611, 533]]
Chk 5233 [[466, 215, 551, 353], [635, 200, 748, 528]]
Chk 5234 [[27, 17, 261, 584], [232, 0, 531, 498]]
Chk 5235 [[227, 77, 419, 369], [7, 85, 159, 416]]
Chk 5236 [[154, 51, 352, 492], [417, 74, 560, 537]]
Chk 5237 [[250, 72, 373, 300], [139, 68, 247, 300], [23, 40, 165, 300]]
Chk 5238 [[290, 53, 597, 374], [51, 160, 298, 474], [0, 208, 34, 314], [98, 107, 510, 460], [3, 199, 72, 474]]
Chk 5241 [[120, 113, 355, 533], [528, 93, 759, 533]]
Chk 5242 [[553, 216, 704, 391], [100, 234, 218, 391], [344, 221, 459, 368]]
Chk 5243 [[1, 181, 191, 767], [177, 270, 486, 644]]
Chk 5244 [[8, 217, 640, 529], [388, 177, 790, 520], [256, 31, 468, 446]]
Chk 5245 [[370, 205, 457, 454], [453, 149, 606, 594], [27, 164, 99, 378], [134, 162, 204, 358], [556, 104, 784, 501]]
Chk 5247 [[163, 13, 525, 583], [439, 66, 702, 583], [0, 52, 194, 583]]
Chk 5248 [[48, 189, 122, 373], [77, 198, 216, 378], [604, 218, 731, 394]]
Chk 5249 [[380, 98, 573, 427], [22, 152, 160, 316], [88, 59, 208, 276], [614, 139, 679, 277]]
Chk 5251 [[423, 105, 551, 543], [284, 60, 355, 215], [126, 66, 283, 501]]
Chk 5253 [[213, 228, 272, 395], [294, 213, 337, 392], [358, 211, 409, 434], [424, 217, 492, 416], [503, 215, 626, 505]]
Chk 5254 [[162, 86, 385, 521], [547, 106, 769, 533]]
Chk 5255 [[385, 251, 467, 517], [194, 261, 283, 546], [256, 243, 340, 524]]
Chk 5256 [[21, 178, 257, 386], [530, 185, 712, 412]]
Chk 5258 [[657, 125, 751, 375], [260, 154, 366, 386], [345, 148, 389, 350], [599, 153, 671, 400]]
Chk 5259 [[368, 206, 509, 384], [500, 208, 636, 363], [11, 229, 172, 491], [772, 212, 799, 337]]
Chk 5260 [[514, 133, 699, 598], [347, 137, 471, 506], [276, 140, 385, 485], [124, 186, 153, 263], [134, 178, 167, 257]]
Chk 5261 [[185, 113, 293, 475], [98, 123, 205, 527], [556, 91, 742, 599], [387, 138, 524, 524]]
Chk 5262 [[14, 427, 222, 596], [274, 140, 536, 494], [526, 326, 664, 597], [359, 469, 561, 599]]
Chk 5263 [[65, 210, 570, 769], [176, 102, 414, 537]]
Chk 5264 [[368, 295, 485, 548], [224, 309, 310, 540]]
Chk 5266 [[186, 66, 716, 522], [123, 194, 438, 529]]
Chk 5267 [[160, 169, 235, 341], [273, 173, 340, 288], [345, 145, 426, 274], [505, 138, 558, 316], [664, 99, 753, 276]]
Chk 5269 [[174, 36, 435, 791], [333, 182, 674, 786]]
Chk 5270 [[503, 353, 599, 576], [398, 395, 469, 590]]
Chk 5271 [[29, 365, 238, 571], [179, 260, 375, 571], [317, 123, 447, 432], [581, 123, 726, 513]]
Chk 5272 [[142, 142, 242, 409], [256, 164, 344, 393]]
Chk 5273 [[186, 89, 288, 359], [451, 91, 652, 519]]
Chk 5274 [[348, 287, 495, 470], [283, 198, 351, 378], [223, 212, 275, 288]]
Chk 5276 [[209, 173, 397, 516], [454, 167, 533, 479], [389, 17, 446, 111]]
Chk 5277 [[126, 157, 287, 450], [378, 189, 554, 511], [410, 160, 715, 533]]
Chk 5280 [[7, 16, 386, 799], [241, 282, 524, 799]]
Chk 5282 [[260, 42, 443, 378], [407, 62, 641, 429]]
Chk 5283 [[2, 88, 224, 514], [155, 169, 403, 601]]
Chk 5284 [[181, 41, 561, 491], [306, 180, 471, 438]]
Chk 5285 [[312, 229, 384, 364], [98, 176, 240, 590], [334, 206, 507, 556]]
Chk 5286 [[148, 59, 246, 396], [224, 60, 350, 375]]
Chk 5287 [[171, 240, 387, 600], [707, 224, 766, 452], [487, 203, 651, 600], [289, 194, 380, 499], [401, 236, 511, 486]]
Chk 5288 [[0, 0, 122, 293], [150, 35, 331, 294]]
Chk 5289 [[188, 145, 292, 457], [73, 98, 187, 431]]
Chk 5290 [[236, 221, 320, 429], [646, 198, 771, 478]]
Chk 5291 [[336, 124, 507, 572], [134, 161, 353, 572], [54, 232, 164, 556], [476, 206, 564, 572], [541, 203, 624, 493], [729, 241, 800, 462]]
Chk 5292 [[280, 69, 778, 494], [13, 23, 310, 508]]
Chk 5293 [[11, 0, 330, 499], [28, 275, 334, 483]]
Chk 5294 [[313, 38, 410, 337], [211, 31, 316, 347], [425, 12, 494, 297]]
Chk 5295 [[314, 160, 400, 368], [79, 204, 193, 315]]
Chk 5296 [[0, 46, 240, 519], [612, 112, 797, 448], [513, 86, 690, 379]]
Chk 5297 [[371, 162, 506, 435], [170, 177, 258, 426]]
Chk 5298 [[186, 44, 356, 328], [51, 55, 189, 396]]
Chk 5299 [[367, 110, 467, 332], [250, 138, 337, 244]]
Chk 5300 [[515, 242, 660, 504], [608, 381, 767, 508], [411, 323, 512, 523], [281, 413, 481, 527], [645, 389, 697, 452]]
Chk 5301 [[0, 41, 79, 476], [56, 27, 200, 531], [167, 64, 340, 510]]
Chk 5302 [[121, 180, 269, 689], [265, 213, 441, 753], [0, 160, 138, 799]]
Chk 5303 [[300, 294, 368, 451], [400, 293, 465, 432]]
Chk 5304 [[0, 15, 195, 530], [156, 41, 469, 530], [273, 68, 633, 530], [601, 11, 800, 530]]
Chk 5305 [[42, 133, 153, 502], [319, 187, 511, 387], [526, 87, 695, 365]]
Chk 5306 [[622, 339, 678, 480], [563, 281, 621, 391]]
Chk 5307 [[0, 56, 448, 530], [262, 0, 799, 530], [54, 0, 145, 87]]
Chk 5308 [[371, 94, 531, 518], [149, 95, 314, 515], [561, 74, 658, 324], [0, 210, 27, 416], [310, 112, 352, 215]]
Chk 5310 [[100, 125, 316, 600], [234, 20, 331, 223], [297, 112, 518, 563], [409, 147, 703, 589], [738, 211, 800, 342], [638, 172, 696, 251]]
Chk 5311 [[31, 96, 366, 533], [284, 76, 535, 533], [520, 42, 779, 533]]
Chk 5312 [[355, 116, 487, 479], [201, 122, 378, 648], [491, 117, 619, 474], [47, 144, 220, 617], [643, 135, 759, 496]]
Chk 5313 [[278, 150, 374, 414], [468, 3, 654, 529]]
Chk 5314 [[434, 143, 636, 511], [104, 143, 323, 519]]
Chk 5315 [[106, 14, 375, 475], [299, 58, 363, 315], [0, 2, 240, 517]]
Chk 5317 [[84, 225, 157, 485], [133, 235, 252, 494], [44, 214, 103, 296], [12, 207, 55, 286]]
Chk 5318 [[42, 253, 284, 635], [225, 295, 483, 760], [272, 268, 386, 414]]
Chk 5320 [[293, 22, 712, 536], [521, 29, 785, 536], [104, 261, 325, 536], [2, 238, 177, 533], [167, 185, 304, 431]]
Chk 5321 [[195, 234, 376, 534], [341, 186, 511, 530]]
Chk 5322 [[50, 121, 164, 480], [294, 69, 510, 528]]
Chk 5323 [[235, 125, 392, 535], [138, 192, 302, 440]]
Chk 5324 [[62, 109, 225, 533], [316, 86, 600, 533], [525, 272, 771, 533]]
Chk 5325 [[382, 168, 672, 769], [57, 166, 298, 659]]
Chk 5326 [[181, 132, 350, 502], [438, 98, 586, 472]]
Chk 5327 [[337, 114, 431, 307], [439, 120, 499, 293], [161, 142, 206, 293], [190, 107, 311, 324]]
Chk 5328 [[385, 125, 506, 472], [245, 201, 377, 452], [29, 214, 68, 278], [84, 216, 117, 277], [137, 210, 162, 244], [143, 179, 173, 235], [615, 179, 632, 211]]
Chk 5329 [[0, 194, 39, 580], [234, 273, 395, 660], [168, 196, 290, 597]]
Chk 5331 [[278, 123, 407, 517], [550, 132, 697, 514]]
Chk 5332 [[31, 89, 379, 692], [475, 157, 761, 692]]
Chk 5333 [[9, 69, 189, 600], [406, 158, 529, 580], [514, 172, 669, 588], [390, 279, 408, 323]]
Chk 5334 [[319, 218, 413, 408], [658, 226, 717, 358], [613, 231, 701, 375]]
Chk 5336 [[38, 5, 384, 511], [435, 66, 800, 461]]
Chk 5337 [[0, 44, 168, 408], [383, 138, 539, 382], [552, 38, 707, 409]]
Chk 5338 [[53, 24, 367, 600], [341, 0, 779, 600]]
Chk 5339 [[0, 93, 195, 713], [136, 216, 552, 709]]
Chk 5341 [[16, 25, 337, 533], [391, 16, 800, 533]]
Chk 5342 [[252, 407, 507, 514], [112, 11, 361, 498], [321, 0, 478, 407]]
Chk 5343 [[37, 78, 392, 504], [359, 92, 763, 498]]
Chk 5345 [[335, 50, 652, 532], [112, 83, 361, 521], [738, 76, 775, 115]]
Chk 5346 [[500, 37, 771, 533], [208, 53, 527, 533]]
Chk 5347 [[11, 33, 243, 453], [181, 51, 337, 389]]

Chk 5349 [[0, 310, 53, 438], [60, 322, 115, 452], [162, 268, 297, 682], [235, 296, 434, 606], [384, 310, 428, 396], [423, 319, 514, 541]]
Chk 5350 [[146, 341, 205, 587], [219, 354, 301, 593], [83, 340, 143, 605]]
Chk 5351 [[692, 126, 796, 499], [153, 165, 241, 287], [9, 196, 56, 349]]
Chk 5353 [[282, 133, 407, 587], [385, 24, 541, 278], [731, 344, 785, 452]]
Chk 5354 [[22, 249, 219, 495], [348, 154, 490, 388], [485, 124, 612, 375]]
Chk 5355 [[370, 92, 563, 479], [167, 141, 531, 498]]
Chk 5358 [[183, 249, 244, 310], [317, 244, 404, 312], [385, 138, 436, 312], [32, 145, 96, 294]]
Chk 5359 [[159, 27, 303, 451], [318, 61, 495, 532], [532, 57, 657, 443], [544, 121, 698, 532]]
Chk 5360 [[667, 8, 799, 531], [13, 39, 188, 506], [157, 32, 309, 310], [301, 85, 524, 533], [100, 14, 325, 505]]
Chk 5361 [[165, 232, 295, 472], [323, 212, 431, 472], [403, 236, 518, 472], [498, 242, 598, 452]]
Chk 5362 [[336, 336, 794, 799], [0, 81, 569, 799]]
Chk 5363 [[0, 431, 47, 628], [245, 299, 273, 440], [259, 323, 297, 477], [321, 348, 375, 505], [342, 392, 453, 738], [651, 454, 790, 734], [472, 401, 509, 494]]
Chk 5364 [[50, 107, 248, 375], [137, 154, 199, 273], [297, 128, 500, 375], [306, 357, 354, 375], [353, 192, 473, 372], [122, 270, 147, 307]]
Chk 5366 [[0, 123, 207, 531], [451, 37, 800, 600], [350, 87, 660, 575]]
Chk 5367 [[122, 294, 221, 496], [395, 102, 501, 332], [652, 104, 721, 325]]
Chk 5368 [[212, 368, 259, 523], [503, 284, 645, 517], [481, 308, 530, 441]]
Chk 5369 [[59, 305, 198, 590], [731, 324, 788, 498]]
Chk 5370 [[217, 302, 281, 579], [107, 277, 209, 600], [19, 400, 74, 529]]
Chk 5371 [[390, 98, 574, 599], [276, 40, 428, 599]]
Chk 5374 [[193, 157, 350, 589], [309, 107, 455, 556], [315, 199, 383, 543]]
Chk 5375 [[522, 182, 620, 426], [655, 161, 744, 441]]
Chk 5376 [[0, 229, 191, 522], [0, 231, 243, 588], [298, 111, 570, 565]]
Chk 5377 [[324, 271, 403, 508], [416, 261, 492, 507], [486, 280, 547, 504]]
Chk 5378 [[276, 96, 453, 347], [92, 47, 191, 315]]
Chk 5379 [[192, 127, 287, 300], [301, 105, 402, 284], [33, 77, 206, 367], [0, 120, 61, 349], [0, 130, 49, 205]]
Chk 5380 [[0, 153, 354, 467], [3, 0, 800, 533]]
Chk 5381 [[197, 103, 480, 532], [403, 149, 663, 532], [33, 134, 232, 532], [0, 177, 140, 532], [572, 224, 635, 335], [224, 234, 292, 295]]
Chk 5382 [[166, 86, 300, 429], [332, 65, 441, 403]]
Chk 5383 [[180, 143, 308, 464], [323, 114, 445, 430]]
Chk 5384 [[325, 184, 536, 391], [487, 153, 547, 271], [105, 9, 150, 102]]
Chk 5386 [[504, 60, 720, 720], [112, 19, 385, 675]]
Chk 5387 [[5, 13, 308, 571], [410, 5, 760, 571]]
Chk 5388 [[177, 77, 387, 676], [405, 76, 601, 690]]
Chk 5389 [[166, 122, 367, 724], [401, 163, 578, 746], [607, 207, 649, 382]]
Chk 5390 [[439, 198, 553, 311], [266, 207, 400, 382], [60, 241, 139, 362]]
Chk 5392 [[292, 89, 456, 571], [445, 81, 596, 553], [598, 39, 747, 553]]
Chk 5393 [[206, 165, 402, 439], [513, 58, 667, 533]]
Chk 5394 [[26, 249, 208, 566], [299, 146, 583, 440]]
Chk 5395 [[59, 99, 185, 282], [189, 80, 292, 285]]
Chk 5396 [[159, 272, 199, 331], [17, 213, 210, 600], [208, 189, 407, 600], [454, 201, 590, 600]]
Chk 5397 [[101, 199, 204, 444], [119, 195, 227, 410], [265, 188, 378, 488]]
Chk 5398 [[336, 321, 416, 450], [67, 310, 180, 604], [25, 319, 94, 516]]
Chk 5399 [[626, 268, 666, 370], [568, 248, 612, 358], [206, 334, 252, 406], [29, 144, 65, 189]]
Chk 5400 [[424, 44, 677, 481], [82, 43, 406, 599]]
Chk 5402 [[175, 234, 235, 295], [242, 180, 392, 526]]
Chk 5403 [[388, 181, 638, 799], [67, 116, 375, 799]]
Chk 5404 [[525, 131, 650, 377], [435, 119, 550, 323]]
Chk 5405 [[494, 132, 563, 424], [592, 137, 671, 368]]
Chk 5406 [[658, 225, 797, 599], [12, 270, 168, 449], [502, 329, 553, 397]]
Chk 5407 [[535, 171, 562, 271], [611, 160, 638, 213], [467, 132, 532, 450], [540, 131, 631, 532], [355, 131, 515, 532]]
Chk 5408 [[30, 217, 107, 398], [276, 202, 362, 455], [503, 202, 697, 508]]
Chk 5409 [[488, 311, 628, 558], [166, 250, 353, 575], [291, 226, 448, 443]]
Chk 5410 [[531, 373, 729, 533], [351, 386, 489, 490], [390, 401, 465, 469]]
Chk 5411 [[15, 116, 102, 391], [628, 134, 777, 528]]
Chk 5417 [[0, 130, 114, 331], [127, 116, 219, 317], [207, 108, 316, 302], [292, 115, 398, 327], [372, 108, 492, 313]]
Chk 5418 [[117, 7, 409, 591], [319, 15, 614, 555]]
Chk 5419 [[337, 274, 400, 443], [410, 260, 465, 412]]
Chk 5420 [[615, 234, 721, 364], [31, 82, 291, 533], [329, 45, 587, 533], [618, 28, 800, 533]]
Chk 5421 [[202, 107, 439, 532], [438, 173, 691, 532]]
Chk 5422 [[411, 245, 459, 363], [291, 247, 360, 374], [51, 313, 139, 437], [359, 240, 407, 357]]
Chk 5423 [[218, 304, 297, 561], [308, 292, 383, 564]]
Chk 5424 [[123, 78, 203, 301], [63, 86, 155, 315], [393, 106, 452, 164]]
Chk 5425 [[475, 64, 630, 477], [174, 119, 404, 515]]
Chk 5426 [[1, 88, 151, 333], [146, 98, 484, 333], [185, 101, 482, 333]]
Chk 5427 [[303, 213, 401, 431], [232, 265, 302, 390], [90, 218, 153, 417]]
Chk 5428 [[234, 186, 356, 375], [291, 1, 476, 326]]
Chk 5429 [[218, 4, 362, 166], [379, 50, 500, 330], [38, 44, 168, 209], [0, 78, 123, 333]]
Chk 5430 [[312, 30, 604, 532], [83, 105, 401, 532]]
Chk 5431 [[272, 243, 347, 437], [95, 221, 141, 312], [679, 241, 791, 395], [552, 248, 634, 343]]
Chk 5432 [[258, 168, 367, 503], [665, 127, 768, 368], [370, 222, 431, 370], [420, 178, 525, 489], [205, 161, 285, 464]]
Chk 5433 [[0, 41, 186, 647], [160, 120, 379, 706], [216, 35, 345, 204], [386, 55, 554, 689]]
Chk 5435 [[0, 51, 374, 659], [364, 42, 799, 659]]
Chk 5436 [[548, 145, 649, 287], [35, 38, 291, 531], [657, 126, 778, 269]]
Chk 5437 [[292, 21, 470, 282], [0, 22, 182, 534]]
Chk 5438 [[409, 213, 527, 533], [486, 208, 653, 533]]
Chk 5439 [[377, 166, 555, 559], [0, 131, 145, 671], [65, 205, 182, 609]]
Chk 5440 [[345, 115, 592, 793], [120, 61, 365, 654], [0, 169, 176, 799]]
Chk 5441 [[352, 67, 542, 325], [0, 270, 289, 622]]
Chk 5442 [[26, 26, 394, 588], [384, 80, 652, 485]]
Chk 5443 [[422, 81, 711, 560], [121, 35, 447, 570]]
Chk 5445 [[163, 307, 265, 465], [385, 251, 472, 418], [239, 327, 342, 483], [438, 326, 567, 473], [771, 225, 798, 359]]
Chk 5446 [[47, 160, 131, 374], [362, 134, 455, 374], [139, 106, 218, 287], [0, 159, 59, 374], [291, 91, 371, 262]]
Chk 5447 [[235, 199, 389, 460], [219, 27, 302, 288]]
Chk 5448 [[6, 295, 84, 469], [472, 318, 571, 504], [267, 297, 389, 560], [385, 358, 482, 537]]
Chk 5449 [[250, 82, 385, 522], [628, 69, 800, 458]]
Chk 5451 [[0, 44, 124, 454], [246, 14, 659, 528]]
Chk 5452 [[0, 117, 69, 366], [184, 96, 300, 465]]
Chk 5453 [[36, 68, 244, 318], [256, 75, 528, 515], [439, 32, 711, 598]]
Chk 5455 [[0, 193, 207, 392], [247, 102, 383, 398]]
Chk 5456 [[144, 223, 234, 456], [351, 215, 437, 449], [234, 211, 320, 474]]
Chk 5457 [[310, 167, 455, 470], [420, 152, 577, 507], [103, 93, 212, 423], [576, 152, 721, 469]]
Chk 5458 [[465, 54, 752, 589], [79, 98, 297, 593], [309, 49, 499, 575]]
Chk 5459 [[101, 140, 544, 581], [74, 98, 543, 561]]
Chk 5461 [[115, 156, 173, 364], [269, 163, 344, 393], [55, 157, 107, 341], [12, 163, 64, 347], [543, 165, 604, 233]]
Chk 5462 [[650, 103, 725, 184], [107, 46, 401, 438], [460, 84, 637, 403], [304, 59, 417, 242], [562, 80, 643, 234]]
Chk 5463 [[48, 113, 179, 416], [268, 208, 517, 552], [346, 0, 564, 350]]
Chk 5464 [[0, 0, 177, 169], [235, 114, 527, 469], [317, 3, 800, 533]]
Chk 5465 [[467, 171, 662, 439], [122, 116, 355, 505]]
Chk 5467 [[432, 293, 727, 533], [247, 57, 713, 533]]
Chk 5468 [[335, 215, 549, 474], [610, 220, 798, 466], [153, 256, 328, 476], [0, 203, 127, 493]]
Chk 5469 [[316, 108, 432, 422], [70, 176, 135, 340], [464, 137, 631, 448], [228, 191, 273, 292]]
Chk 5470 [[408, 259, 484, 512], [304, 273, 385, 448]]
Chk 5471 [[342, 36, 632, 560], [26, 41, 245, 501], [0, 381, 128, 798]]
Chk 5473 [[0, 82, 392, 800], [327, 109, 555, 583]]
Chk 5474 [[102, 288, 249, 600], [323, 311, 432, 573], [596, 312, 675, 422], [732, 318, 767, 388], [756, 303, 800, 432]]
Chk 5475 [[456, 489, 482, 563], [489, 488, 517, 561], [206, 471, 317, 796]]
Chk 5476 [[371, 86, 400, 130], [516, 66, 555, 140], [525, 105, 597, 192], [305, 117, 368, 234], [129, 182, 301, 464]]
Chk 5477 [[14, 128, 146, 510], [638, 168, 758, 522], [501, 166, 655, 532], [138, 159, 247, 520]]
Chk 5478 [[137, 97, 320, 496], [307, 64, 634, 502]]
Chk 5479 [[38, 115, 299, 757], [263, 118, 418, 761]]
Chk 5480 [[604, 244, 702, 529], [291, 264, 383, 519], [457, 270, 554, 523], [161, 276, 219, 355]]
Chk 5481 [[260, 250, 502, 799], [192, 336, 343, 644]]
Chk 5482 [[179, 86, 479, 612], [357, 140, 612, 612]]
Chk 5483 [[173, 33, 401, 542], [312, 139, 522, 515], [451, 273, 515, 509]]
Chk 5484 [[299, 70, 545, 519], [11, 89, 261, 519]]
Chk 5485 [[0, 42, 320, 531], [276, 231, 561, 531], [494, 99, 728, 519]]

Chk 5486 [[397, 328, 511, 715], [329, 303, 394, 468]]
Chk 5487 [[363, 4, 499, 363], [90, 59, 338, 361], [7, 51, 110, 367]]
Chk 5488 [[478, 151, 654, 483], [268, 99, 502, 427], [0, 148, 106, 351], [122, 163, 309, 391], [243, 159, 291, 226]]
Chk 5489 [[558, 166, 760, 800], [295, 120, 656, 800], [107, 196, 329, 796], [376, 7, 585, 289]]
Chk 5490 [[59, 75, 370, 524], [628, 108, 799, 527], [360, 102, 625, 527]]
Chk 5491 [[45, 105, 209, 462], [662, 84, 799, 288], [390, 108, 496, 470], [263, 101, 394, 405], [2, 114, 76, 450], [10, 134, 60, 318]]
Chk 5492 [[548, 46, 775, 532], [290, 142, 421, 328], [179, 69, 292, 387]]
Chk 5493 [[369, 276, 799, 640], [211, 92, 499, 631]]
Chk 5494 [[60, 86, 229, 590], [207, 32, 427, 559], [419, 56, 540, 540], [530, 84, 712, 586]]
Chk 5495 [[462, 192, 718, 513], [162, 108, 370, 469], [131, 84, 193, 182]]
Chk 5498 [[598, 136, 724, 494], [26, 205, 176, 592], [205, 163, 347, 500], [434, 212, 545, 422]]
Chk 5499 [[132, 65, 497, 532], [354, 26, 783, 532], [446, 417, 499, 492]]
Chk 5500 [[111, 107, 289, 290], [188, 176, 385, 428], [338, 284, 576, 540]]
Chk 5501 [[85, 286, 260, 596], [474, 61, 725, 517], [305, 279, 510, 599]]
Chk 5502 [[317, 126, 387, 261], [188, 59, 287, 332], [135, 153, 155, 209]]
Chk 5503 [[73, 151, 425, 533], [426, 170, 688, 533]]
Chk 5506 [[62, 548, 225, 748], [275, 579, 431, 752]]
Chk 5507 [[198, 65, 472, 500], [217, 72, 513, 500]]
Chk 5508 [[100, 361, 152, 472], [147, 291, 207, 488], [71, 273, 169, 353], [84, 280, 174, 487]]
Chk 5509 [[151, 198, 264, 531], [254, 226, 320, 510], [557, 265, 604, 390], [543, 268, 581, 374]]
Chk 5510 [[130, 226, 566, 799], [522, 0, 599, 426]]
Chk 5511 [[191, 90, 566, 534], [461, 118, 782, 534]]
Chk 5512 [[429, 309, 505, 441], [80, 344, 180, 526], [356, 157, 477, 329], [454, 112, 617, 269]]
Chk 5513 [[535, 100, 618, 314], [338, 108, 472, 327], [216, 134, 337, 335], [144, 156, 246, 295]]
Chk 5514 [[123, 280, 209, 452], [206, 261, 260, 386]]
Chk 5518 [[158, 219, 216, 341], [257, 193, 321, 354], [495, 209, 540, 394], [514, 191, 568, 407], [548, 190, 612, 433], [669, 212, 713, 375]]
Chk 5519 [[0, 298, 160, 534], [163, 291, 343, 534], [539, 97, 682, 367], [736, 109, 776, 155]]
Chk 5520 [[69, 446, 434, 800], [275, 127, 508, 764], [11, 127, 321, 782]]
Chk 5523 [[329, 214, 399, 490], [431, 214, 521, 473]]
Chk 5524 [[95, 85, 422, 533], [431, 196, 730, 492]]
Chk 5525 [[60, 92, 140, 268], [0, 102, 138, 453], [162, 48, 370, 321], [502, 7, 708, 308]]
Chk 5526 [[26, 167, 74, 278], [192, 149, 240, 270], [470, 157, 500, 223]]
Chk 5527 [[363, 56, 779, 403], [281, 90, 628, 523], [151, 92, 242, 207]]
Chk 5528 [[2, 292, 178, 600], [324, 265, 498, 600], [275, 291, 356, 431]]
Chk 5529 [[206, 82, 342, 320], [287, 97, 538, 386]]
Chk 5530 [[8, 176, 299, 437], [345, 166, 619, 432]]
Chk 5531 [[0, 36, 388, 450], [392, 53, 788, 505], [314, 0, 570, 385]]
Chk 5532 [[81, 69, 133, 192], [162, 96, 211, 199], [262, 121, 308, 219]]
Chk 5533 [[245, 195, 346, 374], [104, 225, 198, 324]]
Chk 5534 [[129, 153, 481, 533], [612, 139, 800, 533]]
Chk 5536 [[319, 0, 531, 422], [115, 133, 389, 376], [339, 128, 777, 512]]
Chk 5537 [[268, 411, 350, 613], [358, 412, 454, 607], [156, 432, 211, 578]]
Chk 5539 [[82, 119, 334, 549], [386, 55, 631, 439], [445, 77, 521, 147]]
Chk 5540 [[334, 38, 589, 445], [104, 141, 284, 425]]
Chk 5541 [[112, 209, 276, 412], [477, 184, 553, 353], [547, 178, 627, 360], [595, 256, 650, 360]]
Chk 5544 [[435, 202, 572, 426], [240, 217, 389, 411]]
Chk 5545 [[0, 290, 298, 599], [346, 156, 615, 548]]
Chk 5546 [[20, 123, 263, 756], [302, 153, 562, 662], [588, 39, 697, 610]]
Chk 5547 [[340, 166, 586, 446], [107, 135, 347, 439]]
Chk 5549 [[0, 70, 211, 600], [220, 280, 483, 600], [589, 228, 800, 600]]
Chk 5550 [[38, 25, 468, 533], [446, 93, 731, 533], [691, 0, 800, 529]]
Chk 5553 [[9, 305, 221, 696], [301, 403, 487, 671]]
Chk 5554 [[0, 144, 404, 706], [228, 171, 438, 394], [582, 167, 782, 483]]
Chk 5556 [[150, 31, 477, 531], [299, 12, 706, 504]]
Chk 5558 [[67, 119, 229, 565], [404, 172, 502, 470], [277, 206, 373, 466]]
Chk 5559 [[121, 125, 288, 498], [455, 157, 641, 476]]
Chk 5560 [[203, 44, 366, 403], [501, 60, 659, 435]]
Chk 5561 [[192, 93, 447, 799], [4, 71, 296, 799]]
Chk 5562 [[164, 65, 396, 499], [3, 33, 215, 499]]
Chk 5564 [[234, 177, 326, 407], [544, 202, 637, 540], [119, 213, 185, 307], [529, 209, 569, 296]]
Chk 5565 [[78, 74, 253, 546], [302, 107, 490, 313], [521, 136, 696, 378]]
Chk 5567 [[410, 164, 514, 472], [302, 129, 402, 466]]
Chk 5568 [[77, 249, 151, 352], [160, 278, 238, 386], [207, 243, 279, 327], [350, 179, 401, 347], [500, 137, 543, 239], [663, 138, 708, 240]]
Chk 5569 [[119, 71, 403, 777], [92, 74, 324, 446], [238, 338, 410, 787]]
Chk 5570 [[182, 96, 399, 325], [363, 115, 501, 360]]
Chk 5571 [[311, 34, 491, 308], [52, 120, 216, 300], [4, 129, 41, 284], [0, 150, 28, 234]]
Chk 5572 [[384, 176, 531, 593], [366, 251, 463, 432], [214, 204, 411, 600]]
Chk 5573 [[87, 80, 200, 423], [104, 3, 199, 147], [391, 0, 469, 289], [508, 61, 622, 445]]
Chk 5574 [[160, 144, 247, 333], [239, 141, 405, 330], [162, 26, 204, 147], [248, 0, 322, 131], [375, 31, 438, 171]]
Chk 5575 [[158, 123, 430, 564], [318, 3, 721, 600]]
Chk 5576 [[392, 227, 482, 494], [506, 238, 581, 484], [250, 228, 402, 599]]
Chk 5578 [[500, 13, 773, 675], [184, 40, 511, 672], [2, 247, 333, 675]]
Chk 5579 [[469, 154, 581, 326], [531, 136, 632, 306], [52, 224, 143, 455]]
Chk 5581 [[593, 416, 666, 639], [357, 256, 418, 482], [458, 263, 535, 481]]
Chk 5582 [[571, 41, 799, 271], [278, 5, 597, 289], [3, 0, 292, 305]]
Chk 5584 [[276, 337, 360, 422], [356, 356, 458, 451], [446, 306, 555, 480]]
Chk 5585 [[269, 169, 320, 236], [370, 326, 413, 457], [440, 216, 486, 337]]
Chk 5586 [[48, 88, 535, 572], [146, 78, 607, 572]]
Chk 5590 [[362, 132, 489, 359], [199, 133, 308, 366], [110, 143, 185, 230], [0, 142, 52, 353]]
Chk 5591 [[433, 116, 599, 430], [0, 0, 150, 455], [99, 120, 338, 513]]
Chk 5592 [[442, 111, 517, 306], [155, 200, 242, 396], [347, 300, 438, 475], [167, 486, 258, 664], [302, 209, 360, 383]]
Chk 5593 [[119, 230, 223, 470], [74, 250, 148, 485], [552, 228, 622, 391], [439, 219, 493, 350]]
Chk 5594 [[18, 151, 190, 600], [332, 141, 464, 600], [511, 105, 781, 600]]
Chk 5595 [[13, 29, 193, 330], [158, 22, 316, 330], [221, 3, 484, 330]]
Chk 5596 [[0, 56, 226, 534], [308, 17, 577, 534]]
Chk 5597 [[6, 98, 185, 529], [181, 80, 398, 534], [595, 126, 783, 533], [353, 114, 620, 534]]
Chk 5598 [[575, 105, 799, 637], [298, 71, 550, 637]]
Chk 5602 [[181, 34, 302, 188], [623, 42, 712, 146]]
Chk 5603 [[23, 1, 92, 233], [182, 25, 235, 182], [338, 48, 380, 214], [568, 69, 615, 211], [640, 101, 687, 199], [738, 123, 792, 256], [364, 166, 503, 407], [78, 176, 348, 522]]
Chk 5604 [[513, 72, 675, 346], [0, 254, 559, 495]]
Chk 5605 [[330, 135, 488, 302], [737, 186, 791, 386], [655, 130, 767, 346]]
Chk 5606 [[152, 51, 331, 634], [455, 72, 668, 622]]
Chk 5607 [[54, 0, 407, 579], [322, 149, 484, 379]]
Chk 5608 [[473, 117, 787, 538], [114, 132, 318, 455], [55, 156, 228, 523]]
Chk 5609 [[128, 231, 191, 382], [502, 140, 597, 463], [671, 201, 720, 258]]
Chk 5610 [[20, 50, 197, 403], [301, 116, 696, 532], [683, 78, 791, 358]]
Chk 5611 [[238, 349, 287, 557], [172, 319, 232, 528], [589, 296, 696, 419], [291, 298, 396, 599]]
Chk 5613 [[93, 96, 164, 357], [193, 39, 351, 493], [380, 90, 478, 239]]
Chk 5614 [[483, 25, 721, 446], [143, 155, 394, 390]]
Chk 5615 [[67, 21, 163, 192], [119, 18, 177, 157], [160, 42, 197, 139], [289, 23, 424, 166]]
Chk 5616 [[200, 247, 276, 366], [380, 219, 575, 640], [248, 342, 474, 640]]
Chk 5617 [[201, 89, 344, 398], [387, 82, 491, 390], [6, 220, 130, 408], [647, 65, 710, 272], [726, 76, 800, 372], [487, 87, 532, 217]]
Chk 5618 [[560, 191, 627, 331], [174, 180, 213, 249]]
Chk 5619 [[221, 87, 384, 496], [15, 34, 167, 325]]
Chk 5620 [[188, 110, 364, 457], [97, 106, 246, 464]]
Chk 5621 [[298, 61, 461, 366], [0, 0, 230, 331], [50, 39, 452, 321]]
Chk 5623 [[636, 343, 709, 583], [489, 205, 561, 432], [148, 222, 262, 396], [566, 197, 635, 392], [309, 205, 436, 405]]
Chk 5624 [[364, 107, 715, 408], [184, 174, 413, 404], [628, 372, 765, 441]]
Chk 5625 [[450, 47, 799, 530], [25, 101, 279, 527], [193, 40, 421, 530], [326, 69, 401, 208], [514, 88, 547, 161], [524, 77, 558, 141]]
Chk 5627 [[253, 315, 478, 796], [97, 320, 214, 655], [348, 172, 656, 730]]
Chk 5628 [[47, 41, 290, 442], [418, 32, 685, 531]]

Chk 5629 [[296, 185, 471, 690], [29, 199, 231, 697], [209, 227, 250, 396], [46, 253, 85, 305]]
Chk 5630 [[504, 89, 679, 277], [99, 74, 423, 358]]
Chk 5631 [[199, 31, 270, 169], [117, 249, 221, 393]]
Chk 5632 [[195, 87, 303, 325], [32, 71, 123, 465], [191, 321, 509, 699]]
Chk 5633 [[292, 182, 390, 346], [450, 175, 525, 365]]
Chk 5634 [[553, 229, 717, 592], [153, 335, 281, 507]]
Chk 5635 [[360, 86, 469, 318], [511, 94, 628, 304], [236, 113, 315, 310], [770, 120, 799, 201], [323, 142, 346, 191]]
Chk 5637 [[383, 91, 590, 548], [226, 129, 325, 294], [161, 119, 346, 352], [332, 123, 386, 288], [272, 468, 398, 565]]
Chk 5639 [[378, 239, 462, 375], [177, 230, 247, 293], [72, 199, 182, 363], [511, 209, 587, 413], [8, 226, 72, 360], [621, 218, 672, 345], [319, 232, 380, 308]]
Chk 5640 [[26, 91, 135, 467], [549, 81, 699, 446], [420, 69, 582, 454], [142, 70, 291, 450]]
Chk 5642 [[410, 125, 577, 533], [200, 87, 403, 294], [703, 151, 799, 528]]
Chk 5643 [[404, 143, 500, 342], [241, 242, 338, 353], [334, 236, 440, 341]]
Chk 5644 [[286, 169, 393, 312], [181, 153, 303, 331]]
Chk 5647 [[471, 91, 541, 208], [393, 82, 468, 203]]
Chk 5648 [[343, 45, 790, 533], [233, 76, 516, 449]]
Chk 5649 [[177, 120, 215, 209], [119, 155, 176, 288], [262, 121, 300, 186], [117, 150, 141, 180]]
Chk 5650 [[0, 306, 188, 750], [290, 267, 500, 524]]
Chk 5651 [[541, 161, 715, 435], [239, 164, 395, 470], [355, 147, 497, 434]]
Chk 5652 [[153, 65, 728, 592], [23, 180, 355, 641]]
Chk 5653 [[385, 75, 500, 366], [255, 30, 370, 349], [67, 11, 197, 348], [179, 29, 309, 366], [333, 48, 379, 105], [404, 57, 446, 106]]
Chk 5654 [[288, 461, 336, 665], [74, 371, 228, 723], [230, 425, 299, 686], [454, 427, 534, 703], [647, 415, 740, 689]]
Chk 5655 [[414, 158, 582, 614], [254, 215, 414, 632]]
Chk 5656 [[399, 100, 589, 593], [189, 78, 354, 592], [566, 115, 605, 214], [605, 104, 637, 208], [223, 79, 276, 201], [416, 101, 458, 220]]
Chk 5658 [[352, 221, 413, 386], [426, 233, 508, 328]]
Chk 5659 [[52, 71, 271, 375], [299, 67, 499, 375]]
Chk 5661 [[177, 164, 226, 245], [141, 174, 213, 321], [244, 159, 306, 309], [352, 169, 420, 326]]
Chk 5664 [[313, 250, 518, 569], [0, 0, 194, 582], [539, 108, 764, 408]]
Chk 5665 [[328, 54, 747, 531], [60, 106, 369, 530]]
Chk 5666 [[422, 167, 510, 303], [273, 163, 396, 311]]
Chk 5667 [[397, 102, 717, 347], [16, 37, 228, 434]]
Chk 5669 [[206, 323, 399, 620], [491, 240, 685, 575], [0, 318, 168, 656], [395, 335, 468, 471]]
Chk 5670 [[123, 195, 161, 271], [166, 195, 211, 284], [213, 194, 261, 320], [295, 196, 337, 273], [335, 195, 372, 267]]
Chk 5671 [[0, 15, 626, 533], [396, 14, 666, 421]]
Chk 5672 [[333, 111, 565, 526], [83, 76, 408, 524], [39, 301, 66, 372], [48, 292, 79, 365]]
Chk 5673 [[47, 88, 181, 332], [411, 54, 496, 184], [186, 25, 314, 282], [166, 29, 239, 250]]
Chk 5674 [[179, 426, 224, 527], [115, 261, 193, 556], [393, 265, 433, 349]]
Chk 5675 [[696, 160, 771, 371], [308, 191, 378, 387], [389, 70, 544, 444], [238, 203, 292, 266]]
Chk 5676 [[383, 163, 608, 500], [530, 32, 778, 513], [36, 81, 326, 505]]
Chk 5678 [[39, 18, 142, 397], [34, 20, 142, 398], [162, 0, 258, 368]]
Chk 5679 [[305, 233, 574, 600], [574, 229, 800, 600]]
Chk 5680 [[639, 202, 732, 437], [508, 172, 569, 430], [570, 218, 618, 424]]
Chk 5681 [[376, 207, 422, 366], [5, 128, 55, 294], [267, 268, 349, 384]]
Chk 5682 [[468, 200, 746, 444], [270, 100, 497, 508], [74, 98, 122, 245]]
Chk 5683 [[523, 215, 681, 446], [147, 182, 269, 334]]
Chk 5684 [[215, 144, 425, 577], [358, 129, 561, 586]]
Chk 5685 [[106, 193, 140, 277], [151, 173, 199, 304], [214, 188, 269, 253], [263, 137, 303, 219], [264, 211, 325, 293], [291, 130, 333, 231]]
Chk 5686 [[360, 93, 625, 470], [219, 131, 394, 481]]
Chk 5687 [[249, 119, 379, 491], [369, 159, 474, 286], [72, 197, 161, 271]]
Chk 5689 [[1, 149, 84, 496], [164, 177, 223, 280]]
Chk 5690 [[96, 126, 300, 641], [251, 125, 347, 537], [303, 124, 448, 420]]
Chk 5691 [[301, 502, 424, 716], [0, 403, 272, 673], [145, 114, 406, 473]]
Chk 5692 [[430, 218, 617, 505], [519, 139, 595, 418], [637, 158, 700, 398], [678, 142, 791, 532]]
Chk 5693 [[592, 121, 796, 600], [221, 133, 390, 600], [52, 162, 200, 591]]
Chk 5694 [[0, 28, 83, 277], [45, 26, 151, 243], [274, 0, 353, 175]]
Chk 5695 [[3, 50, 172, 505], [398, 27, 588, 509]]
Chk 5696 [[528, 96, 798, 531], [355, 187, 633, 472]]
Chk 5697 [[177, 94, 403, 509], [539, 68, 694, 487]]
Chk 5698 [[93, 26, 225, 486], [336, 196, 386, 280], [580, 71, 787, 504]]
Chk 5699 [[92, 204, 220, 535], [353, 216, 520, 535], [434, 31, 506, 206]]
Chk 5701 [[68, 79, 177, 342], [167, 68, 335, 237], [250, 62, 365, 352], [323, 69, 484, 364]]
Chk 5703 [[18, 188, 91, 332], [180, 192, 257, 331]]
Chk 5706 [[116, 243, 378, 534], [167, 33, 515, 534]]
Chk 5707 [[98, 91, 302, 355], [300, 120, 737, 600], [249, 89, 351, 284], [0, 372, 307, 600]]
Chk 5708 [[11, 154, 115, 425], [351, 292, 452, 412], [633, 206, 743, 381], [547, 178, 625, 394]]
Chk 5710 [[23, 246, 80, 331], [0, 245, 130, 537], [122, 233, 252, 485], [343, 249, 451, 448]]
Chk 5711 [[401, 224, 551, 459], [259, 61, 355, 318], [749, 392, 799, 529]]
Chk 5712 [[295, 275, 416, 448], [301, 94, 400, 233], [143, 300, 277, 446], [209, 88, 292, 217]]
Chk 5714 [[212, 81, 435, 369], [55, 59, 213, 369]]
Chk 5715 [[739, 100, 800, 416], [332, 90, 518, 531], [154, 47, 441, 531]]
Chk 5716 [[57, 0, 347, 565], [495, 308, 754, 571], [6, 341, 66, 553]]
Chk 5717 [[32, 75, 261, 438], [0, 56, 131, 477]]
Chk 5718 [[235, 274, 463, 606], [289, 256, 405, 452]]
Chk 5720 [[187, 87, 317, 464], [455, 117, 553, 380], [324, 81, 459, 435], [561, 220, 620, 375]]
Chk 5721 [[191, 190, 331, 495], [655, 174, 766, 510], [390, 167, 492, 510], [172, 188, 519, 474], [59, 138, 297, 484]]
Chk 5724 [[0, 296, 41, 427], [203, 330, 279, 428], [330, 289, 403, 415], [697, 349, 787, 488], [684, 452, 800, 544]]
Chk 5725 [[2, 200, 183, 476], [318, 208, 535, 388], [199, 106, 445, 411], [527, 6, 793, 507], [544, 25, 662, 389]]
Chk 5726 [[0, 129, 213, 496], [156, 95, 325, 405]]
Chk 5727 [[292, 21, 465, 486], [114, 131, 371, 472]]
Chk 5728 [[177, 173, 215, 216], [219, 171, 247, 209], [264, 173, 315, 268], [404, 151, 474, 288]]
Chk 5729 [[223, 89, 331, 234], [390, 18, 535, 237]]
Chk 5731 [[383, 130, 649, 585], [120, 28, 361, 597], [648, 242, 695, 309]]
Chk 5732 [[0, 54, 382, 762], [221, 259, 638, 799]]
Chk 5733 [[154, 71, 264, 327], [285, 79, 429, 321]]
Chk 5735 [[335, 214, 371, 338], [371, 240, 406, 337], [444, 205, 488, 338]]
Chk 5736 [[118, 234, 208, 456], [424, 235, 515, 439]]
Chk 5737 [[274, 91, 359, 420], [375, 158, 489, 374], [60, 134, 172, 401]]
Chk 5738 [[379, 219, 491, 470], [127, 233, 239, 552]]
Chk 5739 [[170, 540, 264, 756], [295, 532, 376, 738]]
Chk 5740 [[286, 43, 353, 142], [249, 56, 560, 463], [16, 22, 294, 504], [710, 195, 773, 287]]
Chk 5742 [[473, 159, 738, 529], [278, 113, 533, 532], [54, 9, 284, 531]]
Chk 5743 [[317, 138, 518, 674], [66, 173, 214, 685], [169, 216, 339, 722]]
Chk 5744 [[396, 207, 459, 267], [32, 167, 223, 535]]
Chk 5746 [[354, 28, 765, 528], [42, 88, 321, 531]]
Chk 5748 [[454, 54, 651, 506], [178, 85, 309, 416]]
Chk 5749 [[96, 255, 242, 714], [294, 269, 407, 742], [0, 252, 76, 681]]
Chk 5750 [[213, 77, 545, 711], [374, 281, 683, 798]]
Chk 5751 [[0, 128, 90, 297], [105, 115, 230, 245], [381, 157, 427, 206], [464, 148, 525, 222], [608, 153, 646, 208]]
Chk 5753 [[68, 163, 343, 705], [290, 160, 504, 753]]
Chk 5754 [[456, 323, 604, 599], [371, 121, 589, 395], [225, 405, 371, 584]]
Chk 5755 [[113, 144, 245, 600], [251, 182, 356, 459], [321, 305, 434, 518], [213, 200, 261, 414]]
Chk 5757 [[114, 103, 214, 185], [34, 129, 292, 533], [481, 173, 651, 470]]
Chk 5758 [[290, 100, 516, 756], [64, 142, 222, 660]]
Chk 5759 [[209, 33, 508, 756], [61, 35, 243, 741]]
Chk 5761 [[349, 80, 782, 622], [346, 40, 567, 490]]
Chk 5762 [[303, 36, 692, 669], [0, 46, 289, 637]]
Chk 5763 [[10, 120, 440, 531], [364, 185, 587, 531]]
Chk 5764 [[159, 91, 288, 491], [177, 86, 290, 488], [273, 95, 400, 516], [407, 68, 535, 490]]
Chk 5766 [[122, 65, 301, 725], [278, 346, 599, 787]]
Chk 5767 [[46, 78, 331, 597], [279, 7, 531, 655]]
Chk 5769 [[422, 424, 519, 800], [330, 416, 404, 774]]
Chk 5770 [[365, 88, 590, 532], [297, 119, 406, 532]]
Chk 5771 [[68, 257, 117, 339], [121, 259, 178, 336]]
Chk 5773 [[357, 249, 462, 367], [237, 207, 339, 373], [79, 238, 170, 373], [500, 217, 582, 388], [545, 184, 697, 402]]
Chk 5774 [[134, 267, 256, 398], [271, 220, 421, 399], [525, 176, 702, 392]]
Chk 5775 [[320, 131, 537, 733], [75, 56, 366, 723]]
Chk 5777 [[455, 56, 729, 511], [332, 35, 563, 505], [158, 19, 433, 524]]
Chk 5778 [[67, 128, 279, 461], [550, 72, 690, 430]]
Chk 5779 [[179, 128, 387, 768], [93, 267, 228, 733]]

Chk 5780 [[218, 40, 654, 533], [259, 64, 657, 533]]
Chk 5782 [[313, 233, 384, 495], [456, 264, 548, 609], [239, 260, 305, 357]]
Chk 5783 [[188, 51, 741, 504], [228, 5, 456, 432]]
Chk 5784 [[18, 101, 110, 341], [125, 99, 197, 246], [257, 90, 365, 231]]
Chk 5785 [[644, 366, 724, 530], [425, 235, 482, 401], [362, 225, 425, 391]]
Chk 5786 [[192, 245, 330, 542], [541, 224, 656, 467], [654, 249, 720, 445], [748, 240, 800, 471]]
Chk 5788 [[37, 239, 94, 382], [178, 285, 305, 540], [375, 268, 457, 416], [467, 97, 586, 341], [631, 99, 688, 210]]
Chk 5789 [[61, 241, 135, 398], [127, 236, 190, 365], [267, 216, 307, 271], [272, 244, 339, 353], [400, 219, 450, 326], [505, 209, 552, 338], [661, 194, 711, 314]]
Chk 5790 [[112, 224, 162, 279], [200, 260, 243, 308], [405, 190, 465, 261]]
Chk 5791 [[213, 129, 365, 533], [424, 125, 649, 316]]
Chk 5792 [[114, 184, 156, 286], [220, 187, 277, 271]]
Chk 5793 [[30, 423, 520, 609], [0, 43, 399, 564], [381, 71, 607, 453], [478, 107, 800, 609]]
Chk 5794 [[83, 407, 533, 800], [90, 0, 530, 490]]
Chk 5795 [[22, 19, 462, 555], [276, 119, 795, 535]]
Chk 5796 [[60, 42, 177, 293], [231, 12, 329, 342], [603, 54, 742, 372], [582, 6, 619, 51]]
Chk 5797 [[251, 45, 378, 617], [383, 58, 623, 597], [741, 26, 790, 153]]
Chk 5798 [[376, 260, 593, 799], [39, 43, 379, 799]]
Chk 5799 [[543, 115, 596, 291], [754, 102, 794, 206], [306, 119, 348, 215], [312, 120, 442, 334]]
Chk 5800 [[133, 128, 238, 421], [283, 144, 385, 391], [415, 203, 485, 397], [544, 146, 680, 404]]
Chk 5801 [[330, 113, 572, 572], [251, 133, 447, 371]]
Chk 5803 [[602, 31, 689, 263], [294, 119, 454, 360], [156, 178, 294, 464]]
Chk 5805 [[12, 107, 122, 375], [7, 107, 48, 189], [144, 96, 192, 196], [240, 105, 282, 177], [378, 117, 420, 255], [407, 132, 500, 266]]
Chk 5806 [[65, 97, 132, 223], [331, 95, 393, 220]]
Chk 5807 [[59, 109, 453, 659], [90, 104, 472, 661]]
Chk 5808 [[670, 319, 713, 432], [713, 132, 755, 270], [745, 255, 800, 412], [6, 80, 52, 342]]
Chk 5809 [[252, 227, 777, 534], [0, 20, 460, 534]]
Chk 5810 [[10, 26, 354, 729], [237, 46, 488, 469]]
Chk 5811 [[159, 214, 275, 385], [393, 209, 595, 630], [44, 519, 311, 800], [12, 438, 174, 712]]
Chk 5812 [[436, 0, 687, 471], [1, 152, 343, 484], [0, 344, 92, 534]]
Chk 5813 [[464, 204, 747, 470], [101, 187, 282, 412]]
Chk 5814 [[64, 297, 190, 559], [168, 266, 235, 542]]
Chk 5815 [[356, 173, 422, 334], [57, 125, 139, 417], [308, 167, 363, 334]]
Chk 5816 [[568, 171, 680, 447], [364, 186, 447, 434]]
Chk 5817 [[278, 77, 438, 481], [422, 85, 565, 499], [446, 66, 482, 171], [581, 63, 601, 121], [738, 68, 761, 127], [692, 62, 722, 127]]
Chk 5818 [[318, 47, 418, 375], [80, 211, 243, 375]]
Chk 5819 [[15, 99, 434, 632], [348, 0, 799, 632]]
Chk 5820 [[131, 141, 338, 480], [351, 170, 546, 461]]
Chk 5821 [[226, 45, 356, 223], [399, 132, 494, 515]]
Chk 5822 [[102, 35, 576, 530], [122, 41, 629, 530]]
Chk 5823 [[47, 15, 534, 793], [416, 265, 713, 575]]
Chk 5824 [[53, 265, 149, 454], [130, 4, 246, 374], [642, 120, 732, 443]]
Chk 5825 [[0, 0, 353, 375], [257, 0, 500, 375]]
Chk 5826 [[189, 120, 430, 531], [402, 88, 743, 531], [603, 328, 800, 531]]
Chk 5827 [[347, 280, 486, 385], [101, 303, 172, 381], [146, 285, 256, 396], [539, 302, 612, 377]]
Chk 5828 [[362, 98, 799, 533], [633, 104, 799, 523], [134, 220, 420, 525]]
Chk 5831 [[363, 347, 492, 565], [217, 203, 396, 611]]
Chk 5832 [[233, 231, 335, 574], [501, 245, 565, 459]]
Chk 5833 [[423, 0, 500, 222], [225, 31, 338, 228], [135, 79, 220, 333], [2, 29, 87, 273]]
Chk 5834 [[0, 18, 306, 629], [479, 32, 799, 632], [249, 205, 542, 632]]
Chk 5836 [[372, 332, 465, 526], [495, 310, 657, 537], [730, 291, 787, 400]]
Chk 5837 [[45, 77, 332, 549], [292, 103, 490, 524], [436, 19, 696, 550]]
Chk 5838 [[391, 160, 441, 218], [436, 160, 512, 450], [178, 122, 314, 450]]
Chk 5839 [[133, 120, 222, 346], [234, 126, 315, 355]]
Chk 5840 [[261, 234, 368, 447], [388, 211, 524, 424]]
Chk 5841 [[526, 51, 783, 445], [17, 87, 287, 477]]
Chk 5842 [[622, 203, 787, 364], [431, 192, 597, 377], [252, 207, 382, 358], [65, 218, 212, 355]]
Chk 5843 [[175, 99, 318, 499], [20, 115, 206, 499]]
Chk 5844 [[619, 77, 799, 598], [379, 27, 594, 497], [164, 23, 315, 542]]
Chk 5845 [[207, 153, 412, 739], [84, 288, 276, 562]]
Chk 5847 [[0, 49, 690, 555], [562, 0, 799, 430]]
Chk 5848 [[105, 101, 269, 483], [577, 28, 727, 516]]
Chk 5850 [[124, 419, 226, 563], [272, 406, 333, 560]]
Chk 5851 [[149, 405, 206, 595], [213, 439, 334, 772], [236, 241, 297, 431], [317, 214, 379, 429]]
Chk 5852 [[74, 19, 251, 429], [42, 163, 384, 534], [486, 135, 658, 445], [580, 58, 776, 534]]
Chk 5853 [[49, 114, 164, 417], [223, 96, 365, 444]]
Chk 5855 [[122, 200, 542, 641], [391, 319, 556, 631]]
Chk 5856 [[231, 58, 295, 196], [278, 67, 341, 217]]
Chk 5857 [[648, 128, 799, 531], [123, 87, 462, 529], [340, 101, 508, 531], [2, 181, 88, 472]]
Chk 5858 [[354, 427, 499, 648], [56, 604, 233, 756], [61, 300, 151, 495]]
Chk 5859 [[711, 336, 784, 504], [395, 412, 466, 552], [597, 255, 699, 436], [700, 204, 789, 390]]
Chk 5860 [[500, 41, 796, 412], [83, 151, 474, 532], [370, 86, 509, 469]]
Chk 5861 [[188, 61, 352, 329], [471, 99, 668, 390]]
Chk 5864 [[60, 229, 404, 534], [92, 198, 412, 534], [448, 47, 733, 534]]
Chk 5865 [[546, 41, 744, 685], [386, 103, 559, 628], [215, 32, 472, 676], [286, 60, 707, 666]]
Chk 5866 [[412, 181, 504, 698], [229, 215, 406, 452]]
Chk 5867 [[442, 143, 663, 406], [709, 191, 770, 287]]
Chk 5869 [[36, 71, 100, 213], [268, 166, 362, 343], [85, 6, 464, 446], [442, 129, 617, 446]]
Chk 5870 [[70, 114, 324, 533], [449, 145, 573, 533], [317, 187, 370, 259], [583, 186, 620, 267], [745, 192, 800, 295]]
Chk 5871 [[80, 78, 216, 555], [252, 106, 487, 554]]
Chk 5873 [[42, 48, 276, 361], [245, 22, 498, 379], [486, 45, 780, 403]]
Chk 5874 [[46, 237, 198, 580], [186, 461, 420, 735], [52, 154, 449, 734]]
Chk 5876 [[56, 321, 143, 560], [155, 289, 217, 393], [474, 311, 631, 586]]
Chk 5877 [[218, 38, 252, 126], [313, 53, 353, 118]]
Chk 5878 [[420, 222, 598, 632], [45, 47, 441, 639]]
Chk 5879 [[467, 84, 799, 531], [12, 96, 480, 528]]
Chk 5880 [[120, 71, 210, 342], [196, 67, 296, 339], [8, 140, 48, 248]]
Chk 5881 [[207, 184, 306, 452], [455, 174, 564, 451], [327, 179, 425, 469], [326, 178, 429, 462]]
Chk 5882 [[523, 196, 609, 344], [153, 213, 318, 404], [565, 121, 634, 298], [41, 249, 150, 452], [593, 5, 663, 76]]
Chk 5883 [[385, 559, 467, 776], [336, 557, 389, 761]]
Chk 5884 [[284, 224, 353, 428], [414, 293, 478, 423], [379, 228, 438, 369], [457, 230, 499, 297]]
Chk 5885 [[68, 191, 278, 411], [327, 181, 496, 374], [503, 208, 611, 357]]
Chk 5886 [[93, 83, 494, 444], [347, 110, 585, 426]]
Chk 5887 [[11, 139, 137, 441], [534, 95, 645, 465], [367, 127, 473, 424], [209, 142, 297, 260]]
Chk 5888 [[429, 14, 740, 565], [88, 0, 386, 565]]
Chk 5889 [[323, 119, 532, 633], [179, 192, 356, 594]]
Chk 5891 [[346, 273, 491, 690], [0, 464, 141, 799]]
Chk 5892 [[80, 109, 269, 340], [363, 90, 623, 339], [616, 74, 777, 246], [348, 0, 452, 247]]
Chk 5894 [[491, 189, 538, 266], [554, 172, 665, 266], [369, 195, 415, 335], [610, 178, 677, 247], [550, 169, 589, 258]]
Chk 5895 [[333, 34, 772, 495], [3, 53, 196, 411]]
Chk 5896 [[278, 64, 461, 290], [525, 50, 653, 238], [481, 25, 570, 126]]
Chk 5897 [[612, 212, 726, 470], [401, 190, 472, 469], [284, 202, 370, 457], [528, 207, 595, 374]]
Chk 5898 [[150, 23, 458, 298], [302, 49, 760, 443]]
Chk 5899 [[229, 4, 298, 213], [108, 0, 236, 265]]
Chk 5900 [[20, 19, 207, 299], [226, 0, 420, 299]]
Chk 5901 [[287, 0, 456, 410], [46, 6, 187, 246], [497, 147, 756, 430], [162, 339, 242, 434], [113, 283, 167, 437]]
Chk 5902 [[96, 85, 363, 533], [375, 0, 638, 532]]
Chk 5903 [[88, 134, 287, 540], [435, 148, 669, 540]]
Chk 5904 [[29, 27, 534, 756], [244, 328, 467, 738]]
Chk 5905 [[284, 203, 527, 514], [547, 173, 771, 494], [295, 123, 401, 284], [16, 139, 220, 321]]
Chk 5907 [[556, 401, 672, 576], [317, 167, 433, 506]]
Chk 5908 [[515, 159, 684, 531], [86, 206, 343, 531]]
Chk 5909 [[39, 100, 207, 415], [338, 221, 525, 435], [491, 195, 799, 436], [162, 234, 331, 403]]
Chk 5910 [[142, 11, 237, 251], [57, 296, 159, 500]]
Chk 5911 [[0, 24, 63, 147], [73, 112, 140, 238], [109, 59, 174, 144], [299, 184, 356, 302], [398, 251, 466, 337], [413, 119, 475, 203], [381, 151, 440, 238], [260, 76, 307, 172]]
Chk 5912 [[71, 241, 177, 492], [600, 236, 692, 452], [504, 265, 569, 497]]
Chk 5913 [[316, 193, 529, 523], [253, 12, 492, 276]]

Chk 5914 [[531, 192, 734, 562], [680, 93, 725, 222], [245, 216, 512, 544], [224, 305, 404, 518]]
Chk 5915 [[318, 22, 461, 238], [530, 0, 713, 205], [590, 308, 730, 532]]
Chk 5916 [[565, 212, 719, 569], [172, 100, 324, 450]]
Chk 5917 [[35, 63, 123, 232], [438, 20, 469, 108], [457, 11, 490, 111]]
Chk 5918 [[672, 13, 754, 287], [399, 138, 480, 269], [300, 119, 366, 269], [154, 103, 324, 343]]
Chk 5919 [[186, 131, 276, 472], [96, 158, 196, 458], [67, 201, 121, 442]]
Chk 5920 [[69, 241, 114, 407], [513, 222, 585, 390]]
Chk 5921 [[410, 199, 504, 483], [254, 188, 396, 361]]
Chk 5923 [[136, 245, 187, 323], [225, 103, 294, 177], [337, 153, 413, 250]]
Chk 5924 [[13, 18, 229, 361], [220, 143, 351, 331], [330, 129, 456, 334]]
Chk 5925 [[129, 193, 204, 651], [189, 151, 392, 747], [30, 289, 70, 414], [63, 278, 110, 431]]
Chk 5926 [[50, 119, 168, 521], [168, 121, 312, 488], [543, 133, 677, 503]]
Chk 5927 [[131, 162, 277, 602], [362, 188, 529, 616], [296, 154, 455, 615]]
Chk 5928 [[0, 5, 209, 600], [245, 70, 628, 600]]
Chk 5929 [[425, 150, 490, 241], [360, 132, 418, 201]]
Chk 5930 [[94, 55, 383, 532], [396, 136, 745, 532]]
Chk 5932 [[221, 74, 302, 412], [317, 191, 521, 426]]
Chk 5933 [[0, 16, 228, 372], [231, 0, 500, 375], [46, 247, 311, 375]]
Chk 5934 [[28, 166, 405, 598], [527, 210, 799, 599], [270, 186, 599, 595]]
Chk 5935 [[398, 31, 800, 533], [309, 53, 535, 442]]
Chk 5936 [[751, 55, 799, 232], [331, 81, 590, 533], [578, 165, 742, 431]]
Chk 5937 [[0, 163, 370, 800], [0, 219, 402, 800], [332, 627, 436, 800]]
Chk 5938 [[171, 65, 394, 300], [4, 74, 190, 452], [611, 100, 794, 368]]
Chk 5939 [[403, 113, 794, 531], [237, 98, 534, 531], [664, 114, 799, 524], [0, 152, 220, 520]]
Chk 5940 [[346, 87, 758, 532], [240, 198, 439, 532]]
Chk 5941 [[424, 2, 609, 161], [196, 0, 550, 530], [397, 155, 738, 534]]
Chk 5942 [[225, 26, 383, 332], [365, 35, 499, 332], [45, 40, 278, 332], [0, 43, 108, 332]]
Chk 5944 [[78, 6, 439, 532], [441, 10, 763, 515]]
Chk 5945 [[230, 414, 303, 492], [366, 428, 473, 507], [560, 423, 637, 504], [255, 499, 327, 534], [501, 504, 557, 534], [114, 483, 173, 534]]
Chk 5946 [[27, 179, 292, 677], [225, 106, 503, 763], [269, 0, 395, 290], [22, 0, 200, 395]]
Chk 5947 [[113, 460, 173, 596], [240, 348, 297, 449], [346, 352, 394, 478], [177, 434, 256, 598]]
Chk 5948 [[0, 60, 43, 232], [23, 125, 200, 375], [175, 110, 323, 375], [297, 111, 437, 294], [394, 32, 439, 139], [426, 42, 473, 135], [358, 72, 401, 128]]
Chk 5949 [[188, 38, 467, 583], [439, 87, 601, 596]]
Chk 5950 [[53, 108, 422, 375], [191, 21, 409, 265]]
Chk 5951 [[310, 161, 389, 293], [482, 225, 560, 294], [555, 162, 656, 376], [378, 280, 650, 499]]
Chk 5952 [[81, 56, 176, 195], [129, 63, 216, 195]]
Chk 5954 [[52, 184, 243, 704], [516, 224, 606, 481], [637, 219, 700, 407], [689, 218, 753, 396]]
Chk 5956 [[49, 104, 337, 618], [254, 144, 410, 535], [496, 119, 655, 521], [640, 106, 772, 415]]
Chk 5958 [[418, 226, 499, 351], [180, 232, 292, 384]]
Chk 5959 [[264, 316, 536, 800], [63, 87, 505, 800]]
Chk 5960 [[490, 132, 738, 533], [494, 214, 541, 372], [284, 223, 359, 346], [106, 220, 150, 315], [55, 202, 96, 315]]
Chk 5961 [[77, 112, 245, 421], [37, 111, 86, 260], [309, 54, 376, 184], [494, 95, 564, 186], [630, 77, 717, 205]]
Chk 5962 [[530, 42, 651, 435], [50, 75, 213, 505], [198, 150, 235, 217], [236, 153, 275, 213]]
Chk 5963 [[224, 55, 484, 481], [549, 109, 683, 510], [494, 7, 712, 364]]
Chk 5964 [[472, 89, 720, 533], [265, 49, 566, 533], [153, 26, 521, 533], [5, 210, 67, 430]]
Chk 5965 [[86, 149, 324, 400], [553, 226, 799, 522], [343, 164, 579, 509]]
Chk 5966 [[0, 63, 302, 797], [197, 76, 497, 712], [469, 94, 512, 173], [64, 10, 414, 546]]
Chk 5967 [[0, 239, 153, 800], [134, 264, 373, 800], [335, 145, 564, 749]]
Chk 5969 [[501, 5, 709, 433], [99, 11, 341, 268]]
Chk 5971 [[123, 209, 224, 384], [421, 187, 514, 317], [99, 171, 173, 388]]
Chk 5972 [[62, 95, 324, 600], [222, 38, 617, 592]]
Chk 5973 [[315, 80, 660, 570], [255, 51, 483, 570]]
Chk 5974 [[67, 39, 292, 737], [262, 75, 512, 755]]
Chk 5975 [[386, 276, 464, 411], [237, 264, 334, 401]]
Chk 5976 [[25, 137, 92, 325], [533, 24, 694, 533], [213, 70, 306, 439], [305, 42, 398, 215]]
Chk 5977 [[116, 59, 617, 530], [427, 15, 800, 530]]
Chk 5979 [[310, 117, 413, 286], [143, 87, 280, 292]]
Chk 5980 [[78, 118, 235, 532], [227, 77, 408, 532]]
Chk 5981 [[80, 144, 166, 332], [138, 152, 228, 242], [443, 133, 499, 332], [18, 116, 45, 158]]
Chk 5982 [[179, 69, 350, 361], [448, 22, 701, 358]]
Chk 5983 [[413, 141, 597, 369], [155, 165, 349, 625]]
Chk 5984 [[200, 297, 314, 504], [360, 265, 473, 560]]
Chk 5985 [[66, 211, 128, 373], [148, 175, 241, 357], [254, 207, 393, 478], [565, 174, 679, 323], [274, 192, 327, 273]]
Chk 5986 [[246, 55, 533, 554], [579, 26, 788, 532], [574, 58, 634, 209]]
Chk 5987 [[9, 51, 370, 599], [392, 123, 717, 599], [358, 82, 604, 406]]
Chk 5988 [[120, 2, 470, 532], [441, 0, 764, 533]]
Chk 5990 [[119, 58, 479, 579], [223, 244, 629, 587]]
Chk 5991 [[0, 345, 329, 733], [461, 460, 529, 799]]
Chk 5992 [[114, 225, 757, 533], [109, 149, 697, 526]]
Chk 5994 [[17, 57, 570, 528], [472, 61, 800, 528], [357, 0, 516, 197]]
Chk 5995 [[102, 236, 201, 426], [146, 248, 269, 433], [354, 285, 456, 449], [404, 231, 473, 319], [470, 191, 528, 451], [654, 296, 766, 472]]
Chk 5996 [[1, 164, 128, 528], [115, 173, 200, 351], [169, 247, 235, 334], [360, 174, 548, 330], [563, 143, 782, 528]]
Chk 5997 [[434, 316, 600, 628], [259, 445, 478, 712]]
Chk 5998 [[120, 234, 185, 309], [31, 251, 72, 354], [8, 252, 44, 348]]
Chk 5999 [[378, 113, 668, 373], [0, 142, 355, 600], [235, 53, 321, 246]]
Chk 6000 [[473, 152, 663, 514], [173, 214, 317, 470]]
Chk 6001 [[131, 107, 391, 534], [345, 54, 598, 534]]
Chk 6003 [[519, 35, 799, 504], [247, 110, 489, 467], [0, 0, 349, 481]]
Chk 6006 [[277, 151, 332, 242], [202, 155, 276, 265]]
Chk 6007 [[71, 43, 106, 107], [226, 61, 260, 142], [437, 65, 484, 208], [705, 158, 791, 212], [671, 53, 710, 189]]
Chk 6008 [[172, 163, 314, 336], [343, 171, 518, 443], [489, 192, 591, 476]]
Chk 6010 [[505, 79, 762, 499], [24, 68, 368, 498]]
Chk 6011 [[204, 280, 364, 731], [27, 281, 152, 754], [444, 261, 581, 667]]
Chk 6012 [[396, 268, 461, 366], [432, 239, 609, 511], [619, 296, 706, 451]]
Chk 6013 [[55, 97, 109, 189], [297, 9, 350, 89], [324, 181, 407, 366]]
Chk 6014 [[284, 88, 379, 363], [119, 151, 173, 287]]
Chk 6015 [[437, 362, 564, 649], [225, 364, 288, 532], [106, 369, 158, 526]]
Chk 6016 [[426, 210, 480, 403], [378, 190, 438, 390], [83, 45, 327, 533], [533, 27, 798, 533]]
Chk 6017 [[437, 118, 495, 324], [626, 189, 670, 300], [548, 198, 594, 342], [753, 219, 793, 337], [710, 235, 745, 329]]
Chk 6018 [[569, 158, 741, 309], [180, 171, 305, 309]]
Chk 6019 [[0, 0, 392, 537], [491, 0, 800, 537]]
Chk 6020 [[165, 173, 204, 286], [318, 126, 430, 478], [522, 178, 576, 314], [459, 177, 512, 305], [681, 177, 738, 317]]
Chk 6021 [[48, 111, 301, 763], [205, 21, 453, 743]]
Chk 6022 [[195, 224, 305, 525], [158, 185, 398, 568], [446, 102, 506, 163]]
Chk 6023 [[187, 49, 501, 533], [391, 48, 735, 533]]
Chk 6024 [[145, 170, 220, 388], [52, 197, 165, 450], [7, 155, 77, 270]]
Chk 6027 [[338, 64, 487, 516], [130, 75, 299, 525]]
Chk 6028 [[588, 49, 780, 531], [4, 114, 247, 533]]
Chk 6029 [[124, 96, 285, 291], [481, 114, 800, 535]]
Chk 6030 [[252, 231, 450, 560], [520, 265, 707, 491], [692, 190, 745, 241]]
Chk 6031 [[8, 133, 220, 426], [237, 112, 372, 298], [458, 110, 640, 301], [637, 104, 765, 380]]
Chk 6033 [[259, 57, 425, 352], [67, 63, 216, 332]]
Chk 6036 [[187, 65, 432, 443], [431, 18, 570, 491]]
Chk 6037 [[107, 218, 193, 452], [164, 167, 255, 379], [396, 147, 462, 369], [533, 99, 621, 299]]
Chk 6038 [[213, 48, 708, 571], [37, 37, 351, 596]]
Chk 6041 [[504, 144, 581, 490], [208, 119, 333, 494], [39, 92, 219, 369], [365, 130, 467, 286]]
Chk 6042 [[188, 102, 420, 452], [0, 68, 241, 452]]
Chk 6044 [[384, 249, 424, 429], [618, 304, 658, 375], [484, 237, 563, 429], [344, 254, 397, 427]]
Chk 6045 [[15, 152, 362, 530], [410, 217, 726, 530], [465, 169, 746, 530], [743, 137, 800, 506]]
Chk 6046 [[203, 248, 296, 543], [300, 253, 384, 336], [121, 223, 173, 312], [61, 230, 116, 406], [33, 241, 79, 409]]
Chk 6047 [[459, 211, 562, 486], [391, 242, 455, 303], [135, 227, 215, 295], [0, 157, 56, 516]]

Chk 6048 [[14, 156, 255, 532], [291, 54, 591, 532]]
Chk 6049 [[52, 48, 289, 324], [297, 109, 462, 332]]
Chk 6051 [[66, 51, 242, 281], [330, 90, 506, 278], [515, 153, 709, 399], [0, 258, 307, 600]]
Chk 6052 [[51, 272, 205, 597], [472, 266, 572, 411], [276, 246, 393, 429]]
Chk 6053 [[297, 159, 573, 549], [437, 120, 742, 552]]
Chk 6054 [[291, 0, 785, 533], [63, 53, 514, 533]]
Chk 6055 [[429, 100, 799, 632], [0, 15, 367, 632], [285, 98, 620, 632]]
Chk 6058 [[559, 106, 689, 495], [283, 221, 351, 399], [130, 89, 288, 435], [82, 149, 175, 406]]
Chk 6059 [[242, 126, 320, 383], [136, 199, 274, 434], [0, 206, 44, 365], [43, 298, 88, 358], [82, 253, 104, 310], [66, 251, 83, 302], [51, 254, 67, 280]]
Chk 6060 [[341, 22, 762, 530], [80, 105, 416, 530]]
Chk 6061 [[570, 229, 732, 425], [494, 382, 561, 438], [420, 216, 535, 435]]
Chk 6062 [[49, 157, 152, 374], [371, 171, 475, 261]]
Chk 6063 [[92, 0, 476, 426], [17, 53, 236, 354]]
Chk 6064 [[210, 16, 475, 533], [465, 136, 637, 533]]
Chk 6065 [[322, 155, 569, 335], [181, 218, 372, 463]]
Chk 6067 [[384, 390, 470, 581], [515, 429, 575, 593]]
Chk 6068 [[457, 192, 684, 556], [440, 109, 538, 232], [197, 106, 307, 283], [50, 118, 207, 339], [0, 261, 336, 600]]
Chk 6069 [[295, 199, 590, 532], [709, 376, 799, 507], [566, 360, 675, 493], [139, 186, 413, 491]]
Chk 6070 [[79, 23, 453, 533], [315, 0, 776, 533]]
Chk 6071 [[52, 81, 206, 642], [170, 368, 233, 617], [260, 154, 395, 646], [35, 473, 87, 611], [371, 237, 485, 557]]
Chk 6072 [[0, 12, 161, 581], [35, 64, 337, 704], [134, 81, 532, 800]]
Chk 6073 [[33, 127, 490, 600], [499, 31, 800, 600]]
Chk 6074 [[0, 0, 474, 536], [206, 112, 757, 548]]
Chk 6076 [[1, 113, 390, 599], [345, 112, 638, 541]]
Chk 6077 [[552, 52, 649, 198], [677, 72, 778, 204], [294, 56, 544, 354], [417, 36, 576, 417]]
Chk 6079 [[117, 118, 499, 743], [0, 41, 184, 591]]
Chk 6080 [[122, 169, 214, 433], [502, 224, 655, 474]]
Chk 6081 [[167, 188, 374, 444], [373, 117, 764, 534], [5, 190, 150, 420], [412, 148, 557, 534]]
Chk 6082 [[244, 327, 391, 749], [83, 360, 263, 791], [0, 357, 101, 734]]
Chk 6083 [[486, 128, 692, 664], [175, 121, 411, 664], [387, 192, 549, 664]]
Chk 6084 [[0, 41, 204, 445], [324, 208, 443, 364], [546, 195, 674, 362], [520, 238, 625, 374], [692, 177, 800, 407]]
Chk 6085 [[282, 68, 579, 485], [500, 93, 799, 527]]
Chk 6087 [[560, 91, 755, 763], [124, 265, 361, 585]]
Chk 6088 [[127, 241, 193, 465], [380, 271, 445, 461]]
Chk 6089 [[576, 310, 694, 396], [517, 305, 590, 395]]
Chk 6090 [[236, 70, 427, 800], [61, 94, 295, 784]]
Chk 6091 [[348, 78, 440, 275], [439, 113, 477, 179], [332, 73, 382, 191], [298, 73, 347, 208], [236, 55, 301, 184], [73, 104, 146, 234], [67, 101, 143, 221]]
Chk 6092 [[406, 107, 681, 536], [137, 146, 468, 536], [0, 0, 172, 536]]
Chk 6093 [[267, 190, 398, 381], [323, 131, 482, 673]]
Chk 6094 [[482, 298, 548, 465], [282, 314, 350, 448]]
Chk 6095 [[64, 100, 390, 516], [591, 13, 800, 516]]
Chk 6096 [[370, 19, 506, 279], [653, 108, 800, 532], [127, 92, 389, 451]]
Chk 6097 [[554, 320, 609, 430], [581, 200, 800, 600], [302, 183, 573, 582], [77, 227, 282, 600], [274, 314, 314, 421]]
Chk 6098 [[302, 100, 503, 534], [84, 104, 327, 534]]
Chk 6100 [[166, 37, 367, 499], [18, 49, 155, 473]]
Chk 6102 [[371, 336, 400, 438], [298, 377, 348, 447]]
Chk 6103 [[503, 208, 603, 590], [375, 201, 533, 597]]
Chk 6104 [[283, 168, 405, 445], [751, 190, 799, 405]]
Chk 6106 [[353, 24, 499, 374], [158, 119, 244, 330], [102, 104, 157, 236], [237, 127, 293, 254]]
Chk 6107 [[748, 235, 800, 454], [691, 211, 779, 486], [534, 235, 616, 367], [391, 214, 461, 491]]
Chk 6108 [[51, 14, 500, 509], [433, 105, 706, 464]]
Chk 6109 [[301, 166, 474, 693], [142, 183, 313, 748]]
Chk 6110 [[173, 125, 231, 206], [33, 0, 251, 534], [471, 140, 563, 250], [383, 167, 486, 522]]
Chk 6111 [[157, 617, 243, 800], [191, 400, 256, 612], [274, 473, 365, 695]]
Chk 6112 [[290, 364, 508, 741], [139, 333, 305, 661], [347, 142, 530, 661], [10, 244, 225, 593]]
Chk 6113 [[114, 208, 168, 356], [109, 388, 204, 527], [213, 334, 276, 484]]
Chk 6114 [[124, 38, 368, 284], [30, 531, 355, 727], [423, 429, 635, 685]]
Chk 6116 [[259, 187, 502, 494], [10, 75, 219, 528], [599, 185, 796, 520]]
Chk 6117 [[357, 93, 536, 448], [39, 206, 276, 436]]
Chk 6119 [[122, 59, 424, 599], [423, 115, 630, 569]]
Chk 6120 [[81, 54, 322, 282], [259, 19, 382, 255]]
Chk 6122 [[51, 0, 402, 588], [195, 29, 348, 386], [385, 62, 551, 355], [580, 93, 800, 360]]
Chk 6123 [[527, 104, 792, 517], [18, 96, 123, 209], [226, 120, 369, 423], [5, 87, 174, 337]]
Chk 6125 [[0, 26, 199, 730], [111, 215, 268, 551], [205, 223, 267, 344], [385, 129, 600, 635]]
Chk 6126 [[525, 84, 661, 505], [395, 90, 524, 505], [633, 111, 769, 526]]
Chk 6127 [[239, 92, 686, 575], [268, 78, 729, 575]]
Chk 6128 [[216, 380, 401, 611], [44, 125, 244, 623]]
Chk 6130 [[113, 105, 222, 383], [326, 42, 534, 633], [0, 33, 145, 704], [241, 60, 364, 428]]
Chk 6131 [[86, 150, 133, 271], [702, 179, 742, 298], [549, 356, 595, 423], [425, 335, 527, 429]]
Chk 6132 [[159, 260, 219, 431], [227, 253, 294, 417]]
Chk 6133 [[151, 159, 324, 567], [397, 38, 527, 301], [386, 208, 516, 532]]
Chk 6136 [[512, 175, 556, 260], [474, 145, 604, 380], [326, 119, 460, 364]]
Chk 6137 [[419, 79, 750, 595], [145, 36, 486, 599]]
Chk 6138 [[292, 71, 755, 533], [66, 31, 558, 533]]
Chk 6139 [[246, 72, 380, 276], [8, 10, 243, 335]]
Chk 6140 [[462, 240, 626, 437], [215, 103, 372, 429], [579, 134, 639, 196]]
Chk 6141 [[96, 0, 373, 598], [68, 296, 400, 495]]
Chk 6142 [[239, 198, 394, 459], [428, 183, 551, 452], [208, 103, 267, 229], [7, 101, 60, 234]]
Chk 6143 [[470, 425, 644, 739], [17, 87, 212, 520], [256, 157, 458, 704], [403, 205, 633, 681]]
Chk 6144 [[148, 226, 268, 582], [52, 244, 162, 589]]
Chk 6145 [[122, 151, 461, 637], [26, 51, 223, 666], [151, 40, 238, 300], [219, 98, 285, 238]]
Chk 6146 [[479, 171, 786, 496], [44, 69, 431, 520]]
Chk 6147 [[380, 43, 597, 541], [123, 87, 416, 770], [96, 139, 255, 558]]
Chk 6149 [[126, 264, 277, 496], [28, 103, 210, 532], [412, 282, 477, 455], [469, 145, 637, 521]]
Chk 6150 [[367, 402, 471, 676], [216, 320, 344, 656], [166, 351, 237, 656]]
Chk 6152 [[63, 93, 313, 740], [306, 77, 472, 750]]
Chk 6154 [[149, 45, 477, 678], [11, 124, 221, 674], [475, 60, 770, 678]]
Chk 6155 [[118, 371, 210, 546], [232, 363, 332, 586]]
Chk 6156 [[0, 59, 331, 799], [276, 249, 531, 785]]
Chk 6157 [[128, 90, 438, 449], [409, 92, 699, 445]]
Chk 6158 [[269, 2, 491, 374], [0, 0, 229, 374]]
Chk 6159 [[196, 474, 298, 710], [221, 288, 260, 413], [319, 315, 364, 414], [402, 302, 438, 416]]
Chk 6161 [[257, 30, 796, 633], [0, 34, 418, 651]]
Chk 6162 [[0, 61, 283, 375], [182, 0, 500, 375]]
Chk 6163 [[0, 191, 83, 693], [286, 100, 411, 725], [241, 227, 313, 678]]
Chk 6164 [[180, 231, 350, 751], [444, 312, 548, 527], [328, 283, 426, 465]]
Chk 6165 [[19, 77, 108, 273], [115, 65, 188, 268], [319, 28, 622, 782], [551, 22, 764, 756]]
Chk 6166 [[20, 78, 313, 594], [74, 91, 307, 627]]
Chk 6168 [[10, 28, 501, 587], [437, 120, 799, 599], [8, 321, 47, 392]]
Chk 6169 [[311, 220, 415, 565], [347, 168, 520, 595], [420, 179, 524, 463]]
Chk 6171 [[226, 367, 410, 467], [108, 205, 357, 336], [261, 58, 441, 178], [436, 247, 539, 387], [402, 388, 558, 517]]
Chk 6172 [[164, 171, 372, 448], [186, 123, 276, 297]]
Chk 6173 [[189, 67, 475, 519], [297, 159, 720, 519], [521, 174, 627, 305]]
Chk 6174 [[64, 136, 121, 221], [146, 96, 204, 172]]
Chk 6175 [[11, 128, 400, 702], [324, 153, 524, 417]]
Chk 6177 [[309, 129, 463, 597], [668, 173, 753, 418], [30, 209, 70, 286]]
Chk 6179 [[88, 55, 283, 696], [468, 26, 695, 697]]
Chk 6180 [[60, 325, 189, 541], [268, 325, 416, 604], [585, 174, 684, 613]]
Chk 6181 [[525, 81, 672, 572], [432, 67, 572, 318], [722, 310, 800, 353]]
Chk 6182 [[10, 73, 344, 759], [330, 27, 662, 718]]
Chk 6183 [[42, 116, 88, 182], [89, 122, 144, 218], [59, 108, 326, 736], [524, 72, 729, 671]]
Chk 6184 [[439, 109, 800, 799], [58, 40, 627, 799]]
Chk 6185 [[475, 121, 519, 200], [608, 126, 699, 277]]
Chk 6187 [[67, 49, 422, 436], [384, 145, 705, 535], [3, 233, 470, 469]]
Chk 6189 [[237, 86, 447, 692], [86, 104, 392, 590]]
Chk 6190 [[205, 156, 368, 593], [45, 209, 187, 607], [404, 189, 662, 786]]
Chk 6192 [[78, 220, 207, 431], [372, 299, 485, 445], [462, 194, 612, 415]]
Chk 6193 [[137, 173, 210, 260], [310, 149, 384, 258]]
Chk 6194 [[618, 301, 692, 540], [725, 334, 774, 399], [359, 298, 408, 510], [184, 346, 268, 461], [4, 397, 165, 640]]
Chk 6195 [[324, 98, 699, 528], [166, 120, 390, 359]]
Chk 6196 [[335, 27, 785, 799], [17, 222, 359, 789]]

Chk 6197 [[465, 136, 786, 500], [120, 264, 377, 526], [2, 121, 197, 532], [650, 223, 799, 514]]
Chk 6198 [[673, 251, 789, 383], [456, 254, 654, 552]]
Chk 6199 [[354, 257, 460, 563], [519, 257, 648, 579]]
Chk 6200 [[477, 346, 633, 545], [103, 264, 355, 481]]
Chk 6201 [[699, 67, 795, 329], [427, 118, 531, 328], [226, 94, 313, 403], [34, 123, 125, 362]]
Chk 6202 [[238, 62, 506, 800], [36, 50, 301, 781]]
Chk 6203 [[432, 115, 593, 430], [226, 42, 376, 476], [140, 176, 288, 530]]
Chk 6204 [[469, 175, 524, 316], [159, 267, 216, 449], [219, 202, 270, 364]]
Chk 6205 [[10, 118, 206, 458], [274, 190, 380, 426], [367, 201, 446, 338], [424, 236, 509, 369], [531, 152, 649, 346], [369, 304, 637, 600]]
Chk 6206 [[0, 31, 239, 375], [273, 39, 420, 261], [300, 55, 441, 263], [434, 14, 491, 245]]
Chk 6207 [[85, 32, 182, 374], [185, 129, 296, 375], [300, 47, 477, 375]]
Chk 6208 [[208, 169, 269, 269], [400, 158, 457, 260], [629, 148, 682, 269]]
Chk 6209 [[139, 271, 413, 779], [294, 143, 526, 699]]
Chk 6210 [[495, 98, 799, 492], [6, 109, 404, 530]]
Chk 6211 [[598, 145, 688, 345], [710, 131, 798, 353], [18, 268, 125, 432], [287, 331, 381, 496], [440, 221, 483, 325], [251, 295, 309, 435]]
Chk 6212 [[162, 95, 272, 349], [66, 151, 225, 365]]
Chk 6213 [[68, 91, 232, 460], [250, 224, 426, 433], [398, 188, 581, 428], [546, 68, 717, 438]]
Chk 6214 [[388, 29, 642, 600], [130, 77, 409, 600]]
Chk 6215 [[52, 78, 236, 748], [308, 53, 479, 730]]
Chk 6216 [[313, 155, 349, 210], [265, 146, 297, 219]]
Chk 6217 [[312, 162, 594, 532], [204, 77, 346, 418], [723, 89, 791, 252]]
Chk 6218 [[182, 131, 369, 347], [1, 150, 260, 412]]
Chk 6219 [[13, 73, 224, 432], [256, 93, 411, 412], [514, 143, 761, 448]]
Chk 6221 [[291, 119, 514, 769], [105, 200, 366, 742]]
Chk 6222 [[171, 140, 283, 343], [278, 147, 386, 381]]
Chk 6223 [[252, 252, 446, 489], [626, 51, 708, 263]]
Chk 6224 [[46, 300, 97, 430], [198, 280, 247, 437], [253, 281, 349, 442], [493, 289, 544, 435], [553, 296, 600, 425]]
Chk 6225 [[0, 0, 282, 529], [356, 140, 722, 585], [242, 288, 279, 376]]
Chk 6226 [[412, 107, 605, 510], [122, 85, 448, 531]]
Chk 6229 [[142, 110, 292, 490], [421, 190, 546, 547]]
Chk 6230 [[292, 157, 568, 780], [214, 253, 321, 608]]
Chk 6231 [[374, 87, 437, 323], [299, 107, 377, 309], [207, 121, 275, 307], [145, 114, 213, 313]]
Chk 6232 [[296, 34, 616, 422], [0, 96, 463, 538]]
Chk 6233 [[649, 53, 766, 364], [431, 58, 572, 440], [83, 67, 241, 396], [519, 108, 625, 351]]
Chk 6234 [[148, 130, 368, 467], [375, 157, 537, 449], [0, 241, 59, 407]]
Chk 6236 [[427, 0, 787, 595], [12, 199, 459, 599]]
Chk 6237 [[381, 66, 533, 444], [424, 53, 640, 506]]
Chk 6238 [[0, 42, 258, 532], [166, 3, 323, 517], [302, 74, 458, 391], [591, 18, 673, 232], [661, 29, 758, 384], [553, 52, 587, 109]]
Chk 6239 [[223, 58, 396, 432], [3, 70, 229, 568], [600, 68, 708, 210], [521, 83, 800, 540]]
Chk 6240 [[0, 243, 86, 411], [123, 223, 253, 455], [647, 197, 755, 442], [462, 332, 595, 568]]
Chk 6241 [[277, 60, 419, 438], [198, 85, 272, 305]]
Chk 6242 [[438, 246, 722, 591], [84, 92, 379, 596], [319, 151, 466, 599], [642, 164, 799, 599]]
Chk 6244 [[106, 41, 354, 705], [211, 57, 469, 705], [477, 66, 698, 695]]
Chk 6246 [[597, 230, 694, 413], [444, 209, 669, 532]]
Chk 6247 [[0, 0, 423, 600], [468, 163, 786, 574]]
Chk 6248 [[225, 294, 320, 497], [144, 312, 215, 516], [626, 304, 701, 438], [507, 311, 564, 445]]
Chk 6249 [[7, 65, 149, 499], [266, 19, 333, 499]]
Chk 6251 [[62, 68, 256, 343], [187, 63, 280, 339]]
Chk 6252 [[81, 37, 279, 381], [307, 6, 502, 366], [477, 129, 691, 393]]
Chk 6253 [[133, 38, 466, 532], [189, 121, 720, 532], [623, 152, 779, 532]]
Chk 6254 [[15, 27, 322, 630], [532, 70, 799, 636]]
Chk 6258 [[50, 21, 579, 533], [422, 100, 684, 533]]
Chk 6259 [[0, 27, 317, 800], [278, 123, 554, 800]]
Chk 6260 [[491, 26, 775, 495], [25, 8, 314, 464]]
Chk 6261 [[8, 35, 253, 325], [206, 105, 433, 331]]
Chk 6262 [[81, 143, 404, 534], [340, 4, 703, 534]]
Chk 6263 [[363, 76, 715, 597], [99, 87, 503, 599]]
Chk 6264 [[464, 206, 531, 429], [107, 253, 234, 457], [279, 250, 334, 459], [370, 248, 438, 469], [310, 263, 395, 477]]
Chk 6265 [[278, 155, 519, 533], [510, 91, 750, 533]]
Chk 6267 [[385, 44, 795, 506], [252, 0, 446, 534]]
Chk 6268 [[3, 15, 287, 533], [569, 0, 800, 533], [340, 8, 626, 533]]
Chk 6269 [[0, 0, 394, 521], [451, 22, 708, 587], [547, 53, 782, 500], [597, 111, 789, 347]]
Chk 6270 [[174, 76, 364, 385], [402, 112, 519, 369], [553, 104, 704, 375]]
Chk 6271 [[437, 44, 499, 210], [193, 8, 326, 273]]
Chk 6272 [[191, 77, 419, 474], [383, 49, 652, 537]]
Chk 6273 [[316, 167, 402, 333], [388, 180, 464, 249]]
Chk 6274 [[80, 143, 363, 453], [337, 169, 550, 405]]
Chk 6275 [[175, 147, 311, 491], [239, 136, 421, 531], [573, 79, 769, 507]]
Chk 6276 [[259, 117, 367, 415], [416, 136, 512, 369]]
Chk 6277 [[773, 313, 800, 530], [760, 274, 797, 480], [374, 298, 399, 337], [400, 308, 438, 405], [577, 291, 591, 316]]
Chk 6278 [[35, 114, 167, 424], [169, 96, 301, 419], [287, 133, 333, 251], [255, 127, 281, 160]]
Chk 6279 [[245, 106, 340, 321], [189, 313, 333, 599], [350, 335, 470, 595]]
Chk 6281 [[0, 20, 350, 799], [281, 168, 686, 799], [2, 46, 58, 227], [701, 137, 790, 505], [181, 209, 390, 776]]
Chk 6282 [[313, 59, 526, 676], [103, 81, 285, 679]]
Chk 6283 [[173, 84, 522, 517], [393, 109, 691, 532]]
Chk 6284 [[13, 1, 352, 522], [238, 84, 520, 507], [267, 125, 401, 346]]
Chk 6285 [[231, 92, 478, 531], [418, 81, 518, 442]]
Chk 6286 [[362, 143, 582, 471], [60, 144, 254, 477], [577, 166, 733, 454]]
Chk 6288 [[399, 70, 480, 378], [617, 89, 725, 323], [258, 194, 354, 439]]
Chk 6289 [[36, 48, 279, 332], [349, 46, 500, 332], [151, 184, 334, 332]]
Chk 6290 [[133, 244, 289, 534], [555, 244, 659, 534]]
Chk 6292 [[79, 83, 424, 791], [393, 74, 534, 735]]
Chk 6293 [[545, 154, 684, 592], [128, 199, 247, 532], [237, 212, 359, 560], [336, 174, 456, 572], [413, 180, 549, 565]]
Chk 6295 [[0, 90, 331, 611], [305, 434, 499, 728]]
Chk 6296 [[88, 157, 160, 400], [211, 204, 287, 369], [238, 172, 353, 287], [403, 183, 512, 308]]
Chk 6298 [[10, 60, 179, 595], [614, 287, 797, 599], [182, 331, 448, 598]]
Chk 6299 [[165, 197, 393, 465], [464, 193, 685, 471]]
Chk 6301 [[397, 160, 471, 305], [483, 132, 571, 331], [291, 153, 359, 316]]
Chk 6302 [[277, 0, 379, 185], [368, 77, 691, 513]]
Chk 6304 [[25, 17, 100, 219], [186, 9, 321, 248]]
Chk 6305 [[189, 133, 441, 531], [6, 162, 256, 533]]
Chk 6306 [[81, 134, 369, 758], [353, 136, 668, 756]]
Chk 6307 [[202, 246, 372, 597], [560, 299, 671, 600], [441, 384, 548, 457]]
Chk 6308 [[210, 112, 366, 408], [346, 80, 497, 320]]
Chk 6309 [[33, 107, 381, 534], [388, 39, 544, 480], [517, 67, 800, 534]]
Chk 6311 [[196, 221, 463, 794], [131, 216, 261, 705], [280, 195, 420, 470]]
Chk 6312 [[278, 52, 382, 480], [522, 168, 701, 483]]
Chk 6313 [[64, 267, 243, 660], [197, 113, 426, 704]]
Chk 6314 [[104, 9, 149, 77], [274, 18, 415, 433], [416, 99, 594, 493]]
Chk 6315 [[24, 111, 174, 224], [111, 125, 167, 205], [194, 149, 295, 224]]
Chk 6316 [[0, 107, 386, 553], [240, 88, 561, 553], [538, 0, 800, 553]]
Chk 6317 [[36, 160, 297, 800], [208, 50, 410, 470], [341, 30, 477, 406]]
Chk 6318 [[231, 18, 489, 397], [18, 18, 245, 365]]
Chk 6319 [[580, 53, 732, 431], [244, 66, 397, 427], [15, 64, 149, 464]]
Chk 6320 [[23, 118, 265, 768], [361, 224, 557, 754]]
Chk 6322 [[113, 67, 275, 332], [388, 123, 476, 284], [328, 103, 669, 535], [748, 125, 800, 283], [701, 152, 765, 415], [637, 136, 657, 201], [662, 146, 676, 187]]
Chk 6323 [[0, 229, 188, 390], [319, 39, 436, 372]]
Chk 6324 [[338, 209, 385, 261], [571, 186, 652, 342]]
Chk 6325 [[442, 196, 551, 600], [103, 201, 186, 375]]
Chk 6326 [[195, 154, 350, 468], [367, 151, 485, 469], [323, 103, 391, 195]]
Chk 6327 [[339, 173, 377, 234], [294, 169, 321, 233], [425, 168, 465, 250]]
Chk 6328 [[4, 96, 134, 554], [187, 104, 346, 292], [344, 64, 449, 342]]
Chk 6329 [[362, 92, 735, 535], [119, 52, 522, 535]]
Chk 6330 [[46, 160, 243, 600], [487, 37, 800, 600], [435, 158, 587, 597]]
Chk 6332 [[51, 93, 417, 705], [267, 0, 524, 758]]
Chk 6333 [[50, 249, 268, 530], [161, 140, 271, 341], [351, 169, 554, 448], [485, 197, 616, 386], [576, 173, 664, 361]]
Chk 6334 [[302, 20, 347, 176], [67, 84, 285, 751], [428, 52, 633, 753]]
Chk 6335 [[261, 338, 362, 607], [385, 296, 476, 558]]
Chk 6336 [[18, 195, 203, 623], [173, 343, 410, 800]]
Chk 6337 [[140, 128, 250, 253], [248, 102, 321, 298], [538, 135, 582, 237], [662, 159, 695, 227], [646, 152, 668, 185], [363, 172, 560, 345]]
Chk 6338 [[692, 221, 755, 459], [245, 60, 391, 356], [474, 44, 643, 497], [616, 216, 678, 424]]
Chk 6339 [[392, 129, 483, 285], [152, 124, 260, 239]]
Chk 6341 [[0, 48, 218, 260], [58, 161, 309, 326]]
Chk 6342 [[441, 114, 786, 625], [25, 62, 474, 625]]
Chk 6343 [[171, 44, 427, 476], [454, 111, 681, 450]]
Chk 6344 [[313, 124, 398, 341], [435, 135, 534, 352], [184, 113, 239, 300]]

Chk 6345 [[122, 116, 575, 528], [358, 30, 655, 528]]
Chk 6346 [[465, 238, 557, 355], [150, 230, 230, 362]]
Chk 6347 [[0, 153, 116, 481], [183, 139, 304, 487], [388, 128, 510, 492], [613, 143, 780, 496]]
Chk 6348 [[260, 237, 540, 519], [570, 51, 739, 619], [19, 250, 190, 621]]
Chk 6349 [[239, 132, 340, 263], [123, 147, 161, 193], [51, 140, 155, 334]]
Chk 6350 [[109, 18, 533, 800], [2, 359, 384, 554]]
Chk 6351 [[65, 57, 214, 353], [312, 12, 465, 375]]
Chk 6352 [[151, 122, 369, 599], [440, 192, 610, 378]]
Chk 6353 [[5, 18, 335, 776], [153, 190, 588, 799]]
Chk 6354 [[176, 199, 368, 532], [475, 126, 727, 532]]
Chk 6355 [[560, 215, 800, 600], [294, 159, 500, 600], [69, 128, 289, 600]]
Chk 6356 [[120, 9, 428, 602], [0, 174, 149, 794], [21, 126, 291, 576], [333, 374, 447, 799]]
Chk 6357 [[124, 134, 391, 518], [497, 86, 739, 532], [483, 345, 539, 500]]
Chk 6358 [[170, 228, 244, 400], [281, 221, 353, 392]]
Chk 6360 [[73, 175, 323, 771], [243, 137, 392, 684]]
Chk 6361 [[53, 122, 184, 369], [243, 205, 332, 383], [374, 216, 471, 394]]
Chk 6363 [[173, 221, 300, 600], [438, 202, 577, 569]]
Chk 6364 [[547, 211, 648, 458], [49, 228, 124, 315], [307, 231, 400, 455], [221, 216, 324, 475]]
Chk 6366 [[297, 312, 355, 510], [445, 300, 545, 568], [576, 299, 664, 564]]
Chk 6367 [[142, 367, 207, 489], [178, 320, 241, 488], [400, 316, 477, 476]]
Chk 6369 [[354, 84, 589, 739], [39, 45, 191, 644], [213, 92, 386, 228], [177, 244, 385, 460]]
Chk 6370 [[0, 102, 225, 533], [232, 92, 362, 324], [353, 49, 642, 458]]
Chk 6372 [[84, 73, 312, 551], [436, 111, 526, 201]]
Chk 6373 [[175, 222, 243, 387], [133, 197, 184, 351], [215, 49, 269, 163], [508, 164, 573, 328]]
Chk 6374 [[474, 409, 526, 548], [546, 449, 620, 576], [259, 398, 300, 482]]
Chk 6375 [[176, 273, 241, 372], [272, 300, 348, 410], [381, 261, 421, 362], [465, 298, 536, 445], [0, 266, 57, 487]]
Chk 6376 [[237, 141, 375, 531], [587, 131, 768, 529]]
Chk 6377 [[450, 456, 562, 736], [297, 488, 458, 706]]
Chk 6379 [[324, 353, 540, 654], [101, 319, 313, 652]]
Chk 6380 [[187, 152, 350, 542], [361, 146, 508, 534]]
Chk 6381 [[212, 192, 545, 532], [314, 191, 457, 421]]
Chk 6382 [[182, 60, 392, 324], [469, 43, 735, 323], [0, 70, 200, 314]]
Chk 6383 [[0, 305, 314, 743], [276, 198, 469, 800]]
Chk 6384 [[491, 105, 755, 640], [59, 91, 313, 640], [283, 55, 532, 640]]
Chk 6385 [[220, 115, 340, 523], [435, 139, 625, 518]]
Chk 6386 [[580, 165, 674, 403], [178, 133, 414, 599]]
Chk 6388 [[64, 126, 364, 791], [263, 147, 533, 787]]
Chk 6390 [[195, 144, 304, 520], [306, 197, 382, 501], [362, 138, 446, 524], [447, 171, 565, 500]]
Chk 6391 [[230, 126, 434, 476], [409, 18, 727, 495], [79, 247, 173, 336]]
Chk 6392 [[211, 171, 300, 371], [289, 167, 349, 374]]
Chk 6393 [[323, 51, 380, 219], [264, 92, 440, 142], [444, 44, 485, 226], [454, 53, 516, 242]]
Chk 6394 [[474, 172, 661, 531], [224, 176, 371, 382], [149, 271, 238, 348]]
Chk 6395 [[130, 198, 293, 593], [363, 190, 590, 599], [0, 234, 65, 514]]
Chk 6396 [[157, 229, 212, 372], [218, 223, 266, 367], [260, 221, 306, 375]]
Chk 6397 [[532, 121, 638, 302], [606, 31, 678, 251]]
Chk 6398 [[250, 160, 319, 392], [173, 167, 290, 471], [32, 206, 146, 487], [181, 128, 241, 269]]
Chk 6399 [[0, 0, 114, 295], [0, 136, 388, 537], [269, 107, 707, 537]]
Chk 6400 [[305, 247, 466, 800], [80, 265, 302, 800], [86, 3, 362, 390]]
Chk 6401 [[420, 140, 573, 496], [22, 220, 109, 403], [586, 175, 685, 356], [126, 251, 157, 301]]
Chk 6403 [[137, 174, 349, 452], [505, 171, 726, 619], [278, 184, 432, 368]]
Chk 6404 [[427, 389, 458, 425], [80, 74, 235, 344], [507, 116, 623, 385], [553, 243, 599, 277]]
Chk 6405 [[234, 58, 459, 533], [114, 90, 250, 476], [467, 36, 517, 233], [409, 48, 470, 212], [83, 41, 133, 208], [30, 44, 76, 180], [651, 39, 711, 262]]
Chk 6406 [[476, 9, 784, 533], [219, 68, 470, 533]]
Chk 6407 [[342, 0, 799, 528], [29, 66, 380, 530]]
Chk 6408 [[309, 152, 377, 502], [384, 147, 521, 484], [521, 169, 641, 504], [653, 212, 800, 417]]
Chk 6409 [[307, 301, 488, 688], [109, 61, 221, 347]]
Chk 6411 [[451, 77, 500, 240], [287, 146, 425, 250], [177, 99, 285, 328], [62, 134, 170, 302], [45, 110, 85, 195], [7, 104, 26, 130]]
Chk 6414 [[11, 21, 93, 212], [163, 27, 225, 192]]
Chk 6415 [[455, 87, 575, 423], [216, 116, 408, 458]]
Chk 6416 [[31, 129, 313, 531], [703, 210, 772, 319], [433, 110, 726, 531]]
Chk 6417 [[33, 52, 290, 791], [405, 26, 685, 799]]
Chk 6418 [[30, 35, 169, 484], [333, 162, 592, 477]]
Chk 6420 [[579, 75, 664, 315], [143, 189, 237, 364], [674, 185, 732, 340]]
Chk 6422 [[235, 191, 523, 600], [225, 174, 494, 600], [327, 47, 460, 261], [500, 121, 647, 541]]
Chk 6423 [[604, 224, 644, 320], [194, 239, 239, 338], [352, 198, 398, 316]]
Chk 6425 [[325, 87, 522, 515], [132, 113, 312, 532]]
Chk 6426 [[484, 77, 693, 422], [100, 84, 467, 434]]
Chk 6428 [[171, 120, 400, 691], [432, 108, 605, 705], [101, 144, 215, 638]]
Chk 6429 [[190, 40, 333, 274], [119, 97, 213, 256], [72, 188, 117, 254], [23, 171, 66, 236], [49, 189, 92, 246]]
Chk 6430 [[73, 114, 214, 431], [487, 79, 633, 485], [459, 100, 526, 337], [703, 96, 755, 236], [755, 109, 800, 217]]
Chk 6431 [[0, 3, 364, 529], [285, 36, 764, 533]]
Chk 6432 [[41, 202, 202, 483], [90, 114, 223, 358], [567, 141, 687, 358], [591, 231, 769, 492]]
Chk 6435 [[66, 112, 169, 365], [274, 110, 371, 313], [187, 136, 267, 328], [456, 124, 524, 312], [522, 122, 576, 293]]
Chk 6436 [[125, 64, 282, 363], [281, 42, 362, 407], [592, 46, 660, 140], [490, 66, 659, 362]]
Chk 6437 [[42, 360, 278, 473], [0, 85, 69, 457], [51, 74, 72, 95], [1, 76, 102, 452], [126, 0, 278, 479]]
Chk 6438 [[93, 114, 228, 560], [193, 97, 357, 560], [640, 131, 720, 353]]
Chk 6439 [[207, 35, 400, 286], [600, 95, 779, 448]]
Chk 6440 [[18, 138, 74, 264], [368, 156, 388, 210]]
Chk 6441 [[253, 189, 399, 490], [491, 56, 677, 475]]
Chk 6442 [[0, 0, 183, 408], [154, 123, 253, 323], [306, 105, 442, 339], [442, 163, 545, 321], [587, 150, 669, 301], [645, 91, 787, 530]]
Chk 6443 [[264, 134, 388, 407], [187, 142, 286, 381], [48, 105, 175, 403]]
Chk 6444 [[346, 307, 404, 726], [235, 126, 449, 750], [99, 129, 300, 760]]
Chk 6445 [[550, 137, 666, 515], [91, 155, 217, 517]]
Chk 6446 [[397, 87, 781, 444], [69, 73, 404, 462]]
Chk 6448 [[158, 156, 229, 418], [210, 161, 273, 412], [85, 201, 135, 411]]
Chk 6449 [[662, 11, 769, 215], [473, 32, 552, 215]]
Chk 6450 [[636, 56, 799, 349], [40, 183, 118, 353], [158, 230, 242, 341], [374, 173, 438, 325]]
Chk 6452 [[1, 165, 158, 589], [134, 111, 349, 598], [333, 96, 548, 598], [525, 87, 748, 598]]
Chk 6453 [[204, 97, 579, 507], [513, 66, 713, 304], [637, 72, 795, 244]]
Chk 6454 [[564, 146, 773, 350], [334, 94, 459, 242], [211, 94, 319, 217], [25, 75, 164, 201]]
Chk 6456 [[172, 89, 267, 293], [127, 73, 189, 257]]
Chk 6457 [[302, 239, 432, 589], [688, 252, 761, 564], [129, 277, 246, 591], [586, 460, 624, 533], [662, 466, 695, 537], [116, 458, 145, 553], [640, 463, 667, 533]]
Chk 6458 [[55, 327, 113, 438], [337, 380, 381, 506], [391, 384, 456, 497]]
Chk 6459 [[161, 167, 293, 321], [543, 92, 799, 563], [0, 201, 82, 587]]
Chk 6461 [[530, 113, 793, 586], [34, 114, 249, 599]]
Chk 6462 [[121, 293, 143, 373], [102, 289, 124, 374], [190, 305, 211, 380], [437, 106, 598, 745], [246, 100, 426, 736]]
Chk 6463 [[114, 71, 182, 243], [395, 144, 457, 302]]
Chk 6464 [[384, 37, 569, 525], [9, 113, 283, 599]]
Chk 6465 [[285, 61, 399, 326], [183, 65, 288, 314], [50, 88, 229, 333]]
Chk 6466 [[125, 273, 241, 531], [494, 123, 600, 308]]
Chk 6467 [[190, 75, 286, 235], [312, 177, 400, 318], [408, 309, 513, 462], [516, 413, 604, 552]]
Chk 6468 [[222, 144, 355, 400], [289, 84, 442, 442], [513, 97, 605, 498]]
Chk 6469 [[440, 378, 614, 469], [551, 90, 788, 476], [293, 158, 496, 440], [138, 139, 230, 406], [242, 201, 320, 373]]
Chk 6470 [[523, 215, 681, 446], [147, 182, 269, 334]]
Chk 6471 [[205, 95, 361, 534], [374, 136, 494, 534], [519, 118, 721, 534]]
Chk 6472 [[80, 103, 213, 509], [420, 3, 726, 373], [375, 55, 506, 305], [272, 86, 403, 383], [118, 91, 164, 154], [249, 120, 289, 228], [476, 116, 521, 183]]
Chk 6473 [[114, 0, 254, 441], [359, 192, 539, 370]]
Chk 6474 [[313, 105, 367, 258], [245, 94, 298, 258], [574, 214, 607, 274]]
Chk 6475 [[598, 181, 738, 462], [338, 69, 659, 476]]
Chk 6477 [[297, 38, 450, 317], [91, 124, 212, 321], [392, 0, 499, 332]]
Chk 6478 [[275, 134, 416, 291], [400, 131, 531, 328]]
Chk 6479 [[141, 132, 248, 331], [226, 141, 310, 331]]
Chk 6480 [[144, 129, 357, 600], [449, 65, 672, 600]]
Chk 6481 [[161, 22, 391, 600], [435, 14, 643, 623]]
Chk 6482 [[277, 132, 383, 281], [32, 40, 212, 256]]
Chk 6483 [[590, 125, 753, 592], [339, 170, 459, 329], [214, 179, 272, 313]]
Chk 6484 [[55, 34, 301, 534], [537, 185, 800, 534], [405, 37, 691, 534]]
Chk 6485 [[357, 247, 661, 534], [431, 125, 662, 387]]

Chk 6486 [[353, 178, 496, 539], [116, 146, 247, 521]]
Chk 6487 [[242, 224, 352, 357], [10, 190, 454, 521]]
Chk 6489 [[421, 72, 700, 528], [113, 69, 406, 532]]
Chk 6490 [[562, 70, 679, 410], [76, 34, 195, 356], [303, 41, 412, 330]]
Chk 6492 [[234, 29, 747, 800], [0, 164, 360, 800]]
Chk 6493 [[479, 126, 545, 331], [190, 179, 254, 397]]
Chk 6494 [[76, 223, 222, 450], [494, 171, 645, 384]]
Chk 6496 [[363, 9, 624, 496], [506, 5, 800, 533]]
Chk 6497 [[247, 153, 391, 533], [368, 226, 499, 398], [183, 204, 220, 266]]
Chk 6499 [[298, 97, 390, 327], [98, 68, 222, 349]]
Chk 6500 [[614, 91, 787, 530], [355, 145, 564, 533]]
Chk 6501 [[272, 209, 404, 499], [90, 181, 198, 449]]
Chk 6502 [[79, 57, 274, 612], [322, 34, 476, 613], [498, 28, 719, 615]]
Chk 6503 [[275, 236, 399, 350], [192, 254, 493, 602], [496, 0, 800, 718], [493, 0, 800, 744]]
Chk 6504 [[121, 197, 277, 399], [194, 275, 300, 381]]
Chk 6505 [[130, 252, 397, 478], [380, 23, 746, 532]]
Chk 6506 [[212, 292, 458, 775], [119, 162, 290, 697]]
Chk 6507 [[172, 80, 290, 373], [270, 72, 415, 429]]
Chk 6508 [[285, 99, 529, 798], [41, 92, 319, 794], [18, 239, 89, 427], [37, 202, 81, 262]]
Chk 6509 [[350, 223, 485, 529], [570, 296, 631, 371]]
Chk 6510 [[488, 180, 689, 387], [5, 142, 268, 465]]
Chk 6511 [[685, 305, 800, 581], [372, 300, 611, 551], [320, 215, 489, 595], [167, 298, 271, 535], [10, 318, 344, 686]]
Chk 6512 [[538, 136, 628, 457], [351, 155, 444, 256]]
Chk 6513 [[354, 32, 780, 473], [51, 31, 569, 551]]
Chk 6514 [[161, 94, 307, 428], [305, 112, 442, 446]]
Chk 6515 [[499, 129, 647, 401], [66, 126, 230, 600], [629, 213, 678, 281]]
Chk 6516 [[413, 61, 668, 574], [9, 67, 249, 592]]
Chk 6517 [[504, 105, 800, 533], [176, 84, 352, 533]]
Chk 6518 [[564, 324, 600, 499], [163, 442, 260, 725], [284, 486, 385, 704]]
Chk 6519 [[255, 171, 426, 599], [589, 119, 775, 596], [415, 107, 618, 599], [31, 187, 245, 599], [526, 163, 674, 599]]
Chk 6520 [[198, 194, 361, 498], [224, 51, 625, 531], [592, 238, 800, 531]]
Chk 6521 [[375, 153, 533, 766], [156, 142, 377, 800], [19, 203, 173, 780]]
Chk 6522 [[107, 31, 176, 180], [16, 614, 137, 779]]
Chk 6523 [[189, 180, 350, 499], [454, 169, 639, 487], [546, 155, 651, 366], [494, 141, 539, 236], [278, 158, 360, 327]]
Chk 6524 [[431, 42, 689, 464], [102, 201, 323, 518]]
Chk 6525 [[0, 15, 50, 162], [647, 195, 766, 325]]
Chk 6526 [[107, 23, 448, 366], [192, 116, 532, 530]]
Chk 6527 [[519, 106, 641, 336], [674, 110, 766, 253]]
Chk 6528 [[377, 135, 600, 533], [252, 124, 428, 533], [231, 84, 320, 250], [599, 295, 646, 399], [450, 101, 517, 216]]
Chk 6529 [[133, 7, 378, 634], [370, 67, 579, 644], [574, 128, 798, 634], [276, 441, 425, 633], [521, 452, 698, 608]]
Chk 6530 [[160, 222, 234, 388], [329, 219, 449, 428], [546, 230, 645, 479]]
Chk 6531 [[350, 201, 712, 451], [8, 192, 201, 781]]
Chk 6532 [[120, 216, 214, 481], [401, 232, 495, 554]]
Chk 6533 [[492, 32, 737, 420], [149, 44, 344, 417]]
Chk 6534 [[359, 106, 541, 609], [233, 126, 407, 667]]
Chk 6535 [[650, 219, 754, 370], [552, 229, 628, 363], [75, 124, 227, 455]]
Chk 6536 [[14, 56, 281, 360], [217, 22, 393, 305]]
Chk 6537 [[141, 122, 374, 663], [404, 185, 652, 699]]
Chk 6539 [[335, 183, 376, 294], [256, 115, 314, 216], [105, 135, 162, 193]]
Chk 6540 [[187, 93, 305, 579], [278, 82, 410, 598], [389, 192, 528, 481], [522, 94, 655, 488], [634, 97, 800, 581]]
Chk 6541 [[106, 25, 481, 685], [3, 0, 293, 636]]
Chk 6542 [[157, 312, 256, 616], [294, 308, 390, 621], [0, 312, 77, 725]]
Chk 6543 [[418, 156, 655, 363], [179, 136, 283, 294], [624, 157, 731, 320]]
Chk 6544 [[101, 264, 283, 629], [40, 177, 195, 629], [249, 208, 495, 629], [569, 253, 636, 629], [612, 225, 773, 629]]
Chk 6546 [[275, 131, 533, 504], [411, 32, 557, 443]]
Chk 6547 [[23, 0, 357, 564], [419, 0, 599, 718]]
Chk 6548 [[525, 0, 799, 594], [14, 17, 238, 594], [263, 77, 489, 587]]
Chk 6549 [[473, 42, 600, 800], [79, 150, 395, 800]]
Chk 6551 [[184, 122, 259, 386], [231, 127, 333, 390], [423, 119, 520, 383], [512, 124, 597, 403], [617, 148, 692, 421]]
Chk 6552 [[588, 144, 791, 599], [194, 170, 385, 599], [382, 160, 540, 580], [303, 182, 390, 319]]
Chk 6553 [[557, 242, 636, 516], [299, 225, 352, 414], [467, 240, 562, 505], [411, 241, 445, 369], [394, 257, 422, 350], [687, 287, 721, 372], [633, 238, 662, 388], [661, 275, 709, 370]]
Chk 6554 [[224, 312, 432, 713], [429, 161, 631, 604], [114, 114, 296, 713], [388, 325, 591, 713], [604, 63, 766, 650]]
Chk 6555 [[244, 95, 486, 324], [69, 23, 343, 332]]
Chk 6556 [[446, 193, 584, 552], [133, 212, 238, 536]]
Chk 6557 [[198, 137, 347, 516], [348, 114, 590, 496]]
Chk 6558 [[401, 66, 561, 404], [216, 159, 685, 727]]
Chk 6559 [[406, 35, 553, 467], [215, 48, 358, 498]]
Chk 6561 [[382, 130, 598, 770], [28, 35, 319, 791], [348, 340, 412, 471], [194, 146, 327, 647], [298, 187, 336, 241]]
Chk 6563 [[179, 103, 431, 588], [231, 195, 533, 600]]
Chk 6564 [[38, 266, 129, 533], [130, 361, 236, 533], [275, 51, 642, 533], [341, 134, 716, 532]]
Chk 6565 [[49, 177, 227, 648], [219, 212, 389, 565]]
Chk 6567 [[8, 7, 402, 520], [388, 63, 799, 513]]
Chk 6568 [[68, 45, 361, 600], [439, 90, 780, 610]]
Chk 6569 [[0, 13, 267, 533], [332, 37, 600, 454], [688, 125, 800, 569]]
Chk 6570 [[442, 5, 800, 448], [57, 7, 433, 471]]
Chk 6571 [[94, 226, 175, 424], [537, 238, 587, 327]]
Chk 6572 [[93, 47, 399, 390], [405, 68, 778, 481]]
Chk 6573 [[369, 122, 442, 195], [91, 137, 280, 419], [485, 161, 585, 360], [243, 150, 298, 241], [243, 89, 451, 421], [410, 176, 585, 427]]
Chk 6576 [[1, 122, 191, 496], [133, 126, 279, 478]]
Chk 6577 [[75, 77, 329, 421], [412, 112, 578, 421], [578, 288, 639, 426]]
Chk 6578 [[318, 157, 471, 443], [327, 80, 404, 372], [422, 66, 526, 386], [252, 98, 334, 379], [141, 96, 276, 385]]
Chk 6579 [[0, 0, 308, 474], [320, 118, 520, 469]]
Chk 6580 [[122, 120, 514, 479], [321, 148, 448, 473], [42, 168, 120, 272]]
Chk 6581 [[161, 128, 478, 512], [300, 72, 505, 453], [424, 17, 532, 122], [317, 0, 379, 111], [524, 0, 592, 75], [464, 52, 639, 407], [170, 0, 255, 134]]
Chk 6583 [[153, 91, 394, 424], [0, 124, 87, 310], [89, 89, 256, 417], [573, 178, 639, 295], [407, 297, 459, 372]]
Chk 6586 [[353, 34, 639, 419], [356, 164, 491, 425], [283, 107, 375, 394], [91, 86, 257, 335], [0, 273, 138, 421]]
Chk 6587 [[20, 72, 302, 311], [447, 22, 611, 346], [575, 100, 639, 278], [125, 98, 451, 353]]
Chk 6589 [[166, 3, 346, 224], [9, 126, 157, 421], [546, 111, 639, 343], [60, 263, 251, 426], [0, 1, 341, 300]]
Chk 6590 [[319, 195, 381, 411], [0, 137, 300, 639], [120, 3, 323, 521]]
Chk 6591 [[320, 60, 540, 328], [29, 81, 196, 413], [519, 56, 639, 295]]
Chk 6594 [[138, 134, 341, 537], [1, 60, 169, 632], [100, 188, 169, 535], [373, 467, 426, 537]]
Chk 6595 [[43, 224, 254, 425], [190, 152, 323, 425], [571, 183, 639, 408], [257, 226, 416, 425]]
Chk 6596 [[112, 59, 464, 372], [280, 1, 499, 370]]
Chk 6597 [[257, 175, 471, 372], [269, 151, 359, 245], [182, 160, 377, 315]]
Chk 6598 [[1, 125, 171, 628], [214, 155, 356, 596], [1, 99, 103, 291]]
Chk 6599 [[30, 63, 227, 416], [7, 115, 425, 474], [422, 50, 639, 479]]
Chk 6600 [[54, 198, 232, 569], [294, 189, 431, 602]]
Chk 6601 [[135, 51, 233, 356], [9, 14, 148, 358]]
Chk 6603 [[418, 113, 584, 423], [3, 140, 274, 471]]
Chk 6604 [[2, 30, 159, 270], [285, 52, 482, 242]]
Chk 6606 [[109, 50, 339, 215], [0, 66, 640, 428]]
Chk 6607 [[250, 178, 501, 413], [191, 170, 274, 327], [116, 207, 205, 305], [9, 187, 122, 311], [497, 224, 639, 414]]
Chk 6609 [[163, 54, 396, 438], [368, 127, 505, 398], [457, 95, 607, 329], [0, 5, 262, 473]]
Chk 6610 [[132, 88, 309, 422], [0, 45, 137, 420], [423, 51, 639, 422]]
Chk 6611 [[47, 0, 131, 207], [143, 55, 372, 392], [393, 103, 582, 371], [394, 31, 472, 186], [449, 23, 523, 252], [512, 35, 579, 142], [553, 14, 639, 235]]
Chk 6612 [[225, 195, 360, 604], [94, 229, 251, 617]]
Chk 6613 [[239, 255, 351, 587], [129, 214, 282, 576], [65, 231, 167, 415], [8, 231, 125, 396]]
Chk 6614 [[188, 153, 331, 420], [253, 251, 376, 389], [65, 179, 220, 400], [370, 72, 448, 143], [219, 64, 280, 145], [64, 55, 138, 132], [123, 50, 228, 144], [501, 20, 564, 139]]
Chk 6615 [[325, 74, 461, 342], [247, 1, 351, 245], [0, 7, 152, 422], [476, 84, 639, 427], [0, 195, 176, 390]]
Chk 6616 [[250, 18, 584, 367], [1, 39, 200, 262]]
Chk 6617 [[186, 193, 479, 639], [158, 504, 441, 638]]
Chk 6618 [[130, 188, 285, 471], [271, 180, 362, 415], [332, 171, 439, 449]]
Chk 6619 [[307, 3, 639, 446], [0, 29, 235, 328], [139, 160, 347, 324]]
Chk 6620 [[93, 85, 248, 419], [240, 122, 400, 423], [357, 102, 603, 422]]
Chk 6621 [[230, 30, 559, 358], [240, 124, 398, 313]]
Chk 6623 [[188, 155, 304, 430], [20, 140, 220, 450], [299, 136, 451, 457], [426, 143, 587, 451]]
Chk 6625 [[50, 29, 264, 591], [293, 68, 371, 350], [216, 73, 305, 358]]

Chk 6626 [[148, 5, 394, 425], [234, 103, 575, 421], [0, 239, 139, 420], [543, 191, 639, 424]]
Chk 6627 [[276, 99, 562, 420], [13, 43, 404, 421]]
Chk 6628 [[270, 8, 441, 347], [111, 8, 289, 268]]
Chk 6629 [[57, 67, 170, 449], [151, 5, 336, 451], [279, 74, 371, 306], [466, 17, 614, 450]]
Chk 6630 [[196, 124, 291, 404], [87, 162, 142, 260], [52, 192, 205, 479]]
Chk 6631 [[0, 125, 187, 635], [73, 20, 425, 631]]
Chk 6632 [[32, 188, 219, 444], [0, 187, 161, 471], [129, 106, 231, 178]]
Chk 6633 [[42, 157, 186, 494], [203, 150, 361, 492]]
Chk 6634 [[198, 21, 441, 309], [418, 18, 553, 213]]
Chk 6635 [[80, 126, 317, 415], [379, 124, 521, 418]]
Chk 6636 [[209, 24, 323, 369], [245, 129, 534, 418], [86, 67, 235, 396]]
Chk 6637 [[68, 51, 229, 316], [474, 48, 639, 296]]
Chk 6638 [[266, 4, 450, 411], [82, 64, 202, 396]]
Chk 6639 [[130, 97, 280, 397], [332, 216, 466, 395], [444, 187, 561, 420], [547, 3, 634, 110]]
Chk 6642 [[51, 33, 132, 314], [28, 136, 271, 639]]
Chk 6643 [[304, 119, 454, 498], [132, 32, 287, 485], [19, 265, 139, 432], [167, 328, 294, 482], [208, 132, 322, 469], [37, 153, 95, 307], [90, 151, 172, 313]]
Chk 6644 [[0, 2, 258, 232], [0, 131, 314, 311]]
Chk 6645 [[316, 164, 439, 550], [175, 300, 301, 516]]
Chk 6647 [[171, 7, 639, 421], [2, 2, 340, 420]]
Chk 6648 [[220, 182, 390, 479], [338, 149, 518, 462], [74, 185, 219, 479]]
Chk 6650 [[84, 228, 215, 638], [200, 254, 313, 627]]
Chk 6652 [[63, 63, 233, 548], [195, 107, 326, 335]]
Chk 6653 [[37, 38, 404, 425], [276, 1, 410, 252], [230, 50, 314, 240], [311, 138, 576, 417], [0, 1, 51, 163]]
Chk 6654 [[118, 193, 239, 463], [8, 248, 104, 439], [124, 118, 211, 287], [222, 114, 306, 291], [329, 43, 391, 97], [333, 181, 415, 286], [299, 108, 367, 287]]
Chk 6655 [[444, 229, 596, 426], [324, 46, 442, 421], [196, 95, 337, 422], [156, 27, 290, 427]]
Chk 6656 [[84, 60, 215, 489], [196, 112, 328, 479]]
Chk 6657 [[28, 240, 201, 472], [232, 237, 357, 479], [565, 281, 639, 471]]
Chk 6658 [[96, 151, 193, 479], [252, 198, 308, 324], [537, 209, 639, 472]]
Chk 6659 [[182, 168, 425, 637], [1, 319, 198, 633]]
Chk 6663 [[87, 147, 324, 397], [371, 218, 583, 407], [18, 93, 156, 238], [29, 75, 85, 153]]
Chk 6664 [[142, 43, 388, 295], [444, 9, 638, 310]]
Chk 6667 [[244, 225, 637, 386], [369, 173, 619, 327], [159, 240, 452, 477], [102, 154, 249, 410]]
Chk 6669 [[94, 88, 242, 362], [219, 133, 486, 362]]
Chk 6670 [[199, 33, 343, 357], [314, 41, 448, 362], [482, 116, 568, 348], [32, 30, 175, 357], [0, 127, 72, 352]]
Chk 6671 [[1, 23, 372, 420], [266, 54, 404, 256]]
Chk 6672 [[347, 205, 639, 425], [296, 124, 352, 225], [0, 135, 238, 419]]
Chk 6673 [[12, 128, 414, 412], [507, 294, 639, 413], [425, 231, 532, 412], [387, 266, 473, 417], [167, 69, 278, 193], [381, 97, 490, 295]]
Chk 6674 [[423, 65, 638, 420], [304, 104, 503, 401], [7, 187, 321, 425]]
Chk 6675 [[172, 6, 368, 335], [365, 135, 463, 299], [482, 185, 614, 329], [153, 154, 247, 278], [3, 17, 234, 372]]
Chk 6676 [[207, 110, 412, 394], [11, 184, 246, 391], [427, 23, 507, 209], [539, 1, 610, 205], [74, 73, 134, 206], [381, 27, 441, 209]]
Chk 6677 [[272, 127, 345, 355], [369, 12, 639, 375], [339, 142, 408, 375], [0, 82, 269, 371]]
Chk 6680 [[14, 33, 307, 517], [252, 41, 610, 517]]
Chk 6682 [[8, 117, 242, 628], [240, 142, 478, 639]]
Chk 6683 [[290, 190, 372, 410], [171, 27, 263, 335], [81, 113, 175, 273], [343, 71, 406, 209]]
Chk 6685 [[0, 86, 412, 403], [1, 184, 611, 602]]
Chk 6688 [[362, 45, 614, 419], [27, 231, 181, 425], [546, 201, 638, 420]]
Chk 6689 [[204, 43, 431, 444], [113, 31, 307, 353]]
Chk 6690 [[0, 2, 341, 474], [308, 144, 639, 474]]
Chk 6693 [[323, 92, 471, 352], [32, 88, 173, 323], [154, 62, 327, 335]]
Chk 6694 [[245, 48, 350, 300], [315, 76, 431, 319], [402, 29, 498, 329], [470, 61, 584, 397]]
Chk 6696 [[172, 64, 525, 421], [184, 60, 410, 420]]
Chk 6697 [[24, 170, 357, 522], [175, 264, 590, 532]]
Chk 6698 [[0, 30, 287, 471], [299, 57, 639, 471]]
Chk 6699 [[79, 30, 341, 455], [285, 103, 489, 412], [338, 0, 416, 132]]
Chk 6700 [[129, 108, 244, 368], [233, 277, 333, 475], [198, 274, 428, 463]]
Chk 6701 [[30, 225, 288, 522], [280, 225, 514, 452]]
Chk 6702 [[3, 38, 393, 473], [348, 0, 521, 369]]
Chk 6704 [[267, 74, 407, 356], [118, 132, 169, 266]]
Chk 6705 [[385, 63, 479, 354], [257, 20, 360, 358], [28, 60, 137, 338]]
Chk 6706 [[102, 15, 603, 460], [85, 124, 208, 302], [185, 115, 246, 220], [303, 127, 362, 206], [300, 58, 368, 194]]
Chk 6707 [[120, 25, 242, 464], [236, 141, 351, 474], [42, 186, 138, 454]]
Chk 6708 [[187, 77, 308, 387], [300, 59, 406, 356]]
Chk 6710 [[203, 74, 399, 394], [0, 47, 239, 479], [264, 82, 639, 479], [143, 216, 210, 347]]
Chk 6711 [[89, 3, 292, 420], [312, 82, 439, 389], [449, 85, 580, 373], [247, 162, 318, 235]]
Chk 6713 [[99, 18, 638, 425], [341, 67, 602, 425]]
Chk 6715 [[53, 38, 255, 567], [300, 68, 481, 552]]
Chk 6716 [[198, 129, 321, 626], [40, 171, 166, 546], [339, 170, 409, 464], [405, 179, 457, 284], [0, 178, 97, 639]]
Chk 6717 [[25, 6, 232, 431], [463, 114, 639, 512], [411, 199, 470, 377]]
Chk 6718 [[303, 32, 593, 475], [65, 45, 356, 479], [0, 158, 83, 470], [265, 65, 328, 169], [326, 54, 403, 192]]
Chk 6719 [[181, 69, 323, 432], [16, 70, 166, 449], [382, 133, 458, 399], [447, 96, 564, 382], [531, 98, 625, 299], [443, 94, 509, 250]]
Chk 6720 [[0, 151, 367, 466], [148, 148, 571, 474]]
Chk 6722 [[154, 40, 305, 223], [424, 138, 639, 336]]
Chk 6724 [[38, 131, 149, 354], [166, 157, 341, 330], [323, 98, 514, 347]]
Chk 6725 [[5, 57, 264, 367], [82, 70, 338, 350], [344, 97, 493, 278], [504, 71, 632, 309], [428, 85, 512, 225]]
Chk 6726 [[237, 5, 617, 479], [229, 344, 383, 479], [2, 201, 230, 471]]
Chk 6727 [[179, 83, 402, 352], [464, 182, 611, 367], [447, 53, 507, 134], [530, 70, 612, 141], [159, 26, 219, 96], [112, 44, 175, 111], [36, 27, 124, 105], [372, 47, 457, 129]]
Chk 6728 [[204, 189, 264, 361], [161, 170, 219, 328], [325, 176, 473, 631], [65, 134, 244, 639], [280, 250, 333, 338], [12, 191, 65, 332]]
Chk 6729 [[288, 65, 441, 479], [159, 131, 322, 474]]
Chk 6733 [[32, 114, 238, 298], [257, 151, 428, 332]]
Chk 6734 [[0, 0, 179, 309], [396, 3, 639, 337]]
Chk 6735 [[181, 52, 306, 363], [280, 52, 419, 355], [436, 51, 526, 363]]
Chk 6736 [[395, 91, 555, 388], [339, 86, 458, 336], [256, 114, 373, 320], [0, 209, 178, 479], [0, 415, 53, 479]]
Chk 6737 [[42, 8, 259, 429], [35, 293, 187, 554], [388, 3, 440, 75]]
Chk 6739 [[0, 33, 239, 354], [231, 99, 473, 360]]
Chk 6741 [[332, 33, 431, 421], [118, 37, 297, 426]]
Chk 6744 [[164, 121, 269, 401], [432, 75, 560, 470], [60, 327, 194, 472], [489, 214, 638, 479]]
Chk 6745 [[242, 19, 385, 400], [96, 22, 328, 424], [557, 156, 637, 407], [463, 170, 591, 428]]
Chk 6747 [[2, 154, 198, 473], [91, 228, 318, 472]]
Chk 6748 [[25, 4, 169, 349], [310, 87, 446, 347]]
Chk 6749 [[35, 121, 393, 473], [320, 119, 639, 470], [74, 142, 174, 340], [507, 163, 631, 282], [296, 174, 364, 273]]
Chk 6750 [[6, 2, 238, 471], [253, 133, 408, 468]]
Chk 6752 [[201, 108, 355, 429], [1, 160, 99, 445], [375, 109, 581, 318]]
Chk 6753 [[52, 120, 218, 479], [255, 40, 473, 470]]
Chk 6755 [[141, 65, 321, 471], [325, 71, 451, 453], [514, 41, 639, 473]]
Chk 6756 [[120, 15, 259, 345], [22, 45, 139, 304], [207, 109, 360, 341], [335, 44, 446, 351], [440, 1, 589, 365]]
Chk 6757 [[240, 108, 339, 370], [434, 144, 599, 409], [224, 36, 275, 117]]
Chk 6758 [[266, 64, 598, 478], [2, 33, 322, 477]]
Chk 6759 [[26, 136, 257, 326], [295, 175, 441, 327], [243, 69, 365, 218]]
Chk 6761 [[0, 166, 152, 474], [61, 93, 290, 429], [305, 105, 453, 336], [396, 95, 619, 479], [484, 66, 639, 477]]
Chk 6762 [[342, 159, 604, 426], [224, 0, 390, 426], [38, 112, 187, 277]]
Chk 6763 [[22, 182, 269, 420], [379, 22, 545, 426], [277, 55, 406, 302]]
Chk 6764 [[37, 2, 311, 263], [270, 89, 419, 329]]
Chk 6765 [[253, 14, 551, 341], [0, 29, 278, 341]]
Chk 6766 [[214, 0, 444, 357], [393, 27, 445, 223], [0, 0, 51, 151], [157, 73, 375, 347]]
Chk 6767 [[85, 195, 198, 379], [55, 104, 187, 377], [369, 182, 464, 380], [274, 193, 373, 378], [180, 163, 284, 383]]
Chk 6768 [[250, 21, 414, 309], [308, 12, 573, 370], [0, 175, 94, 400], [134, 69, 296, 337]]
Chk 6769 [[303, 107, 458, 321], [480, 181, 639, 348], [350, 0, 413, 65], [415, 2, 466, 54]]
Chk 6770 [[128, 0, 295, 204], [436, 0, 600, 363], [343, 64, 441, 228], [96, 54, 164, 206], [0, 88, 58, 232]]
Chk 6771 [[50, 20, 234, 588], [144, 187, 298, 619]]

Chk 6772 [[274, 147, 382, 411], [55, 103, 193, 468], [475, 139, 555, 356], [552, 143, 631, 345], [0, 161, 102, 430], [241, 157, 300, 385]]
Chk 6773 [[404, 114, 558, 370], [539, 176, 601, 312], [53, 138, 129, 339], [1, 141, 70, 352], [240, 245, 576, 368]]
Chk 6774 [[4, 3, 556, 605], [363, 0, 610, 605]]
Chk 6775 [[214, 72, 305, 291], [273, 71, 389, 280], [259, 95, 445, 356], [255, 0, 640, 418], [123, 70, 281, 222], [199, 55, 275, 211]]
Chk 6776 [[284, 40, 405, 421], [111, 67, 275, 422]]
Chk 6778 [[106, 186, 258, 548], [193, 203, 258, 312], [325, 287, 387, 458]]
Chk 6779 [[1, 122, 243, 461], [419, 156, 500, 230], [408, 69, 637, 471], [160, 131, 273, 334]]
Chk 6780 [[225, 111, 411, 473], [51, 45, 287, 478]]
Chk 6781 [[296, 133, 439, 469], [453, 119, 589, 476], [351, 126, 457, 247]]
Chk 6782 [[56, 55, 311, 474], [286, 122, 496, 479]]
Chk 6784 [[232, 11, 404, 200], [394, 6, 548, 205], [0, 156, 158, 371], [60, 1, 220, 177], [566, 71, 639, 224]]
Chk 6785 [[267, 4, 634, 408], [215, 103, 420, 286]]
Chk 6786 [[271, 87, 445, 422], [103, 254, 288, 426]]
Chk 6787 [[168, 234, 388, 579], [101, 149, 234, 347], [369, 316, 525, 572]]
Chk 6788 [[95, 121, 230, 397], [262, 127, 394, 395], [389, 132, 526, 402]]
Chk 6790 [[188, 17, 328, 352], [77, 173, 160, 350], [173, 179, 228, 349], [195, 114, 366, 356]]
Chk 6792 [[208, 0, 639, 474], [1, 128, 252, 409], [248, 1, 376, 137], [196, 0, 264, 94], [141, 2, 221, 87], [0, 0, 130, 174], [335, 0, 414, 93]]
Chk 6794 [[148, 89, 373, 251], [487, 61, 639, 378], [176, 212, 521, 367], [174, 0, 240, 74], [287, 0, 373, 61]]
Chk 6795 [[145, 36, 445, 419], [1, 50, 225, 419], [265, 0, 639, 425]]
Chk 6796 [[0, 142, 113, 424], [175, 210, 321, 424], [225, 114, 359, 365]]
Chk 6798 [[169, 186, 410, 377], [314, 17, 568, 192]]
Chk 6801 [[53, 102, 249, 336], [331, 3, 471, 274]]
Chk 6803 [[218, 120, 632, 624], [7, 154, 321, 636], [243, 46, 319, 114], [12, 23, 68, 202], [55, 61, 125, 125]]
Chk 6804 [[0, 81, 199, 400], [216, 79, 502, 405], [494, 277, 639, 431], [473, 144, 539, 258], [581, 88, 639, 253]]
Chk 6807 [[347, 28, 575, 479], [64, 67, 286, 472]]
Chk 6808 [[162, 113, 631, 425], [135, 105, 441, 418], [114, 0, 242, 209], [397, 12, 577, 186]]
Chk 6809 [[110, 4, 358, 357], [333, 46, 484, 358], [0, 21, 176, 358]]
Chk 6811 [[256, 85, 468, 470], [427, 27, 639, 477], [1, 78, 223, 473]]
Chk 6812 [[239, 120, 390, 329], [18, 0, 210, 298], [261, 113, 522, 427], [384, 29, 543, 304], [451, 221, 633, 421], [561, 181, 639, 427], [118, 230, 179, 332]]
Chk 6813 [[31, 18, 211, 631], [173, 77, 348, 520]]
Chk 6814 [[168, 11, 422, 453], [13, 271, 162, 531]]
Chk 6815 [[129, 94, 258, 426], [0, 94, 195, 422]]
Chk 6816 [[132, 33, 337, 330], [251, 115, 336, 333], [404, 103, 499, 330]]
Chk 6818 [[39, 67, 290, 329], [225, 21, 468, 331]]
Chk 6819 [[0, 4, 103, 323], [405, 59, 528, 383], [324, 154, 430, 352], [235, 159, 414, 353]]
Chk 6820 [[309, 59, 484, 339], [140, 215, 433, 339]]
Chk 6821 [[444, 1, 566, 285], [304, 18, 429, 297], [188, 46, 240, 170], [535, 31, 639, 237]]
Chk 6822 [[284, 270, 389, 447], [181, 209, 303, 408], [4, 264, 162, 441]]
Chk 6823 [[135, 191, 238, 409], [422, 269, 519, 420], [184, 117, 338, 425], [310, 94, 399, 422]]
Chk 6824 [[260, 10, 416, 422], [82, 29, 268, 420], [381, 86, 540, 353]]
Chk 6825 [[285, 74, 438, 332], [1, 15, 228, 447], [454, 94, 638, 343], [166, 60, 472, 346]]
Chk 6827 [[21, 57, 315, 347], [247, 112, 312, 281], [455, 195, 519, 270]]
Chk 6830 [[34, 1, 220, 422], [434, 119, 621, 427]]
Chk 6831 [[276, 201, 426, 402], [29, 203, 160, 471], [120, 243, 179, 324], [110, 281, 214, 358]]
Chk 6832 [[386, 87, 639, 472], [53, 8, 396, 474]]
Chk 6833 [[74, 1, 156, 227], [73, 11, 281, 381], [297, 28, 582, 384]]
Chk 6834 [[169, 120, 407, 392], [3, 130, 150, 404], [448, 77, 639, 455]]
Chk 6836 [[177, 132, 348, 479], [350, 99, 542, 473], [338, 98, 532, 479]]
Chk 6837 [[88, 288, 235, 459], [235, 144, 423, 570], [0, 482, 56, 639]]
Chk 6838 [[0, 43, 234, 432], [420, 64, 639, 453], [144, 83, 532, 446]]
Chk 6839 [[0, 94, 232, 465], [197, 155, 353, 395]]
Chk 6840 [[8, 101, 142, 332], [350, 88, 446, 328]]
Chk 6841 [[45, 41, 243, 392], [335, 31, 495, 332], [183, 111, 327, 229], [370, 183, 561, 426]]
Chk 6842 [[227, 93, 452, 356], [568, 61, 639, 339], [188, 188, 248, 274], [140, 192, 213, 275]]
Chk 6844 [[2, 62, 126, 301], [235, 157, 395, 474], [364, 36, 618, 473], [0, 164, 254, 479], [261, 124, 348, 268]]
Chk 6845 [[255, 102, 388, 479], [146, 108, 305, 479], [351, 116, 488, 479]]
Chk 6846 [[243, 169, 401, 620], [112, 162, 267, 577]]
Chk 6847 [[342, 23, 540, 472], [48, 311, 110, 413], [331, 121, 448, 443], [440, 125, 532, 444], [174, 157, 300, 422]]
Chk 6849 [[0, 3, 244, 561], [40, 187, 170, 350]]
Chk 6850 [[24, 46, 368, 472], [262, 118, 584, 372], [186, 317, 539, 443]]
Chk 6851 [[394, 22, 639, 420], [0, 122, 283, 419]]
Chk 6853 [[86, 81, 321, 630], [268, 87, 407, 638]]
Chk 6854 [[210, 160, 389, 502], [196, 266, 366, 501]]
Chk 6855 [[43, 64, 233, 469], [149, 152, 259, 499]]
Chk 6856 [[223, 264, 386, 531], [272, 133, 485, 575], [234, 164, 510, 522]]
Chk 6857 [[309, 98, 481, 328], [209, 68, 348, 332]]
Chk 6858 [[243, 8, 440, 432], [400, 72, 502, 449], [101, 55, 285, 410], [390, 62, 597, 531], [186, 41, 291, 383]]
Chk 6862 [[349, 0, 513, 242], [164, 0, 322, 195], [417, 228, 577, 419], [10, 79, 250, 273], [0, 0, 81, 87], [45, 252, 304, 418]]
Chk 6864 [[398, 86, 491, 356], [533, 0, 584, 66], [169, 121, 358, 353], [59, 77, 168, 378]]
Chk 6865 [[0, 0, 132, 403], [234, 77, 464, 308], [179, 0, 259, 92], [105, 0, 181, 88], [135, 22, 256, 318]]
Chk 6866 [[232, 172, 410, 488], [20, 16, 288, 631]]
Chk 6867 [[113, 99, 253, 540], [245, 144, 409, 531]]
Chk 6868 [[256, 1, 602, 426], [0, 203, 352, 426]]
Chk 6870 [[355, 74, 479, 404], [432, 69, 561, 457], [175, 151, 229, 284]]
Chk 6872 [[85, 51, 228, 425], [283, 113, 452, 420]]
Chk 6873 [[12, 3, 171, 280], [149, 48, 345, 276], [322, 58, 488, 280]]
Chk 6874 [[389, 173, 575, 420], [99, 125, 306, 422], [2, 341, 117, 421]]
Chk 6875 [[225, 124, 451, 632], [465, 264, 630, 629], [12, 203, 156, 639]]
Chk 6876 [[130, 254, 244, 479], [216, 154, 276, 318], [279, 152, 371, 428], [114, 136, 215, 459], [93, 144, 150, 415]]
Chk 6877 [[427, 101, 542, 383], [205, 67, 396, 410], [93, 64, 204, 423]]
Chk 6878 [[96, 151, 275, 526], [264, 194, 438, 569]]
Chk 6879 [[371, 18, 476, 372], [288, 15, 388, 358], [140, 8, 308, 368]]
Chk 6881 [[510, 133, 639, 329], [167, 128, 295, 338], [584, 85, 639, 250], [0, 119, 125, 456], [93, 107, 209, 306], [311, 123, 365, 227], [364, 93, 503, 235]]
Chk 6884 [[175, 121, 323, 369], [306, 4, 499, 369]]
Chk 6885 [[159, 48, 440, 407], [358, 10, 581, 405]]
Chk 6887 [[210, 204, 425, 633], [0, 241, 102, 435]]
Chk 6888 [[326, 104, 621, 356], [1, 44, 192, 373], [282, 84, 537, 359]]
Chk 6890 [[306, 39, 639, 472], [6, 32, 466, 479]]
Chk 6891 [[91, 196, 281, 419], [32, 112, 94, 197], [315, 184, 439, 421], [448, 158, 625, 427]]
Chk 6892 [[214, 23, 378, 398], [313, 41, 478, 465]]
Chk 6893 [[286, 104, 576, 537], [31, 44, 252, 535], [225, 187, 418, 544], [461, 24, 585, 190]]
Chk 6894 [[118, 72, 238, 337], [404, 62, 459, 206], [549, 83, 639, 343], [553, 66, 639, 299], [275, 70, 450, 377], [180, 41, 253, 265], [0, 106, 84, 306]]
Chk 6897 [[334, 112, 639, 455], [297, 193, 413, 455], [581, 159, 639, 271], [402, 165, 460, 259], [0, 181, 112, 451]]
Chk 6899 [[331, 94, 515, 372], [463, 2, 639, 274], [108, 51, 364, 391]]
Chk 6900 [[189, 91, 474, 410], [1, 2, 261, 627]]
Chk 6901 [[5, 36, 229, 585], [117, 110, 450, 561]]
Chk 6903 [[82, 173, 333, 422], [333, 215, 570, 426], [381, 91, 639, 426], [284, 62, 401, 182], [13, 66, 290, 190]]
Chk 6904 [[158, 21, 534, 596], [439, 79, 620, 374]]
Chk 6905 [[192, 274, 385, 584], [1, 189, 244, 630], [173, 135, 286, 460]]
Chk 6906 [[60, 113, 209, 455], [173, 125, 296, 492]]
Chk 6907 [[287, 110, 404, 369], [74, 84, 222, 374]]
Chk 6909 [[247, 2, 639, 422], [0, 130, 366, 422]]
Chk 6910 [[435, 166, 638, 422], [259, 113, 435, 422]]
Chk 6911 [[2, 1, 371, 476], [242, 1, 639, 483]]
Chk 6912 [[345, 23, 545, 420], [38, 71, 375, 419], [193, 50, 393, 361]]
Chk 6913 [[233, 52, 470, 367], [0, 15, 265, 365]]
Chk 6914 [[502, 141, 637, 474], [0, 134, 153, 470], [207, 85, 280, 269], [128, 99, 221, 383], [406, 98, 538, 421], [371, 96, 451, 290]]

Chk 6915 [[2, 182, 222, 602], [306, 187, 609, 604]]
Chk 6917 [[90, 68, 499, 479], [261, 40, 495, 473], [0, 353, 109, 479]]
Chk 6918 [[200, 79, 306, 287], [370, 113, 539, 289]]
Chk 6919 [[364, 152, 440, 317], [468, 154, 552, 318], [163, 123, 302, 394], [35, 126, 173, 396], [577, 163, 637, 287]]
Chk 6920 [[182, 79, 288, 389], [347, 135, 426, 323], [113, 104, 209, 396]]
Chk 6921 [[144, 194, 276, 369], [248, 185, 584, 603], [193, 106, 342, 345]]
Chk 6922 [[69, 13, 302, 267], [0, 5, 135, 474], [66, 47, 127, 154], [388, 45, 639, 325]]
Chk 6923 [[114, 191, 313, 419], [43, 48, 170, 385], [0, 22, 84, 333], [293, 180, 353, 247], [509, 142, 595, 282]]
Chk 6924 [[167, 6, 289, 410], [266, 156, 477, 407]]
Chk 6925 [[129, 118, 237, 359], [199, 232, 639, 425], [61, 219, 203, 374]]
Chk 6926 [[1, 210, 117, 473], [56, 43, 323, 423], [294, 2, 639, 472]]
Chk 6928 [[516, 104, 634, 256], [19, 114, 77, 329], [394, 106, 491, 412], [65, 152, 232, 474], [306, 110, 390, 390], [226, 111, 382, 465]]
Chk 6929 [[76, 161, 223, 452], [250, 158, 377, 453], [435, 184, 604, 447]]
Chk 6930 [[292, 238, 413, 474], [385, 219, 491, 479], [477, 211, 542, 453], [94, 260, 199, 470], [48, 253, 100, 365], [191, 248, 274, 477]]
Chk 6931 [[336, 93, 447, 435], [127, 120, 252, 366]]
Chk 6932 [[146, 142, 333, 387], [472, 160, 606, 396], [355, 230, 559, 394]]
Chk 6934 [[45, 166, 192, 345], [366, 113, 639, 406]]
Chk 6936 [[82, 110, 222, 336], [0, 104, 116, 342], [484, 94, 615, 399]]
Chk 6937 [[367, 32, 633, 452], [0, 33, 352, 448], [304, 156, 383, 287], [249, 141, 321, 262], [312, 221, 428, 425], [324, 130, 391, 194]]
Chk 6939 [[34, 23, 441, 639], [173, 160, 308, 336], [225, 148, 552, 632], [300, 176, 559, 412], [376, 176, 507, 310], [414, 179, 480, 247]]
Chk 6940 [[171, 49, 304, 375], [85, 83, 173, 354]]
Chk 6941 [[366, 100, 452, 462], [452, 117, 552, 446]]
Chk 6942 [[62, 131, 184, 468], [266, 67, 384, 173], [401, 85, 466, 223], [26, 176, 78, 297], [165, 120, 264, 479], [435, 123, 550, 472], [342, 139, 445, 471]]
Chk 6943 [[303, 129, 415, 401], [497, 280, 639, 473], [1, 1, 258, 471]]
Chk 6944 [[335, 33, 559, 466], [460, 90, 539, 396], [49, 62, 214, 331]]
Chk 6945 [[136, 18, 350, 396], [285, 73, 515, 396], [74, 10, 175, 301], [379, 390, 636, 474]]
Chk 6949 [[94, 188, 256, 472], [201, 205, 314, 405], [311, 171, 382, 465], [380, 190, 443, 421], [250, 181, 310, 421], [2, 245, 82, 326]]
Chk 6950 [[293, 213, 385, 451], [217, 212, 301, 447], [110, 199, 225, 446]]
Chk 6951 [[371, 16, 494, 285], [35, 72, 247, 516]]
Chk 6955 [[312, 130, 462, 461], [439, 115, 580, 450], [142, 124, 282, 462]]
Chk 6956 [[188, 69, 373, 499], [2, 27, 233, 408]]
Chk 6958 [[106, 3, 213, 259], [211, 136, 486, 484], [455, 44, 605, 441]]
Chk 6959 [[362, 87, 497, 377], [289, 101, 374, 419]]
Chk 6960 [[236, 9, 522, 444], [234, 142, 408, 387]]
Chk 6961 [[204, 42, 461, 327], [0, 142, 147, 472]]
Chk 6962 [[212, 46, 478, 344], [0, 36, 316, 399]]
Chk 6963 [[144, 140, 272, 428], [393, 148, 502, 404], [0, 142, 79, 405]]
Chk 6966 [[232, 84, 467, 368], [35, 78, 209, 374]]
Chk 6967 [[3, 115, 501, 473], [31, 80, 169, 337], [25, 97, 315, 403]]
Chk 6968 [[216, 21, 309, 359], [11, 73, 125, 288], [284, 3, 397, 369], [415, 61, 507, 290]]
Chk 6970 [[208, 94, 438, 630], [0, 40, 341, 632]]
Chk 6971 [[65, 37, 303, 503], [522, 183, 602, 351], [221, 105, 320, 351], [340, 68, 541, 530], [468, 97, 572, 335], [57, 82, 144, 496]]
Chk 6972 [[0, 34, 300, 421], [169, 124, 350, 343], [338, 5, 639, 413]]
Chk 6973 [[255, 39, 431, 300], [415, 52, 471, 211], [62, 72, 268, 473], [539, 46, 603, 227]]
Chk 6976 [[116, 176, 291, 418], [70, 157, 138, 370], [346, 154, 485, 427]]
Chk 6977 [[172, 79, 293, 344], [212, 32, 427, 142]]
Chk 6978 [[206, 283, 383, 639], [30, 80, 271, 617], [249, 89, 377, 352]]
Chk 6979 [[294, 93, 448, 381], [259, 88, 349, 301], [186, 69, 308, 347], [12, 43, 166, 388], [430, 101, 639, 427]]
Chk 6980 [[146, 63, 403, 537], [358, 22, 519, 587]]
Chk 6981 [[312, 43, 467, 416], [147, 51, 320, 479]]
Chk 6982 [[137, 141, 379, 416], [283, 61, 540, 417]]
Chk 6983 [[255, 243, 351, 477], [347, 293, 535, 365], [535, 3, 609, 178], [192, 153, 312, 380]]
Chk 6984 [[213, 75, 311, 417], [304, 80, 419, 413], [87, 61, 217, 419], [392, 66, 485, 411], [487, 53, 581, 400], [273, 49, 329, 148], [181, 43, 249, 401], [429, 39, 495, 286]]
Chk 6985 [[76, 13, 411, 459], [12, 203, 337, 466], [569, 252, 638, 375], [551, 267, 602, 330]]
Chk 6986 [[74, 155, 204, 539], [347, 121, 587, 585]]
Chk 6988 [[114, 87, 353, 390], [257, 174, 506, 375], [492, 126, 639, 381], [310, 71, 382, 156], [291, 180, 365, 294]]
Chk 6989 [[406, 62, 508, 319], [480, 67, 566, 368], [105, 99, 253, 473], [0, 74, 64, 288], [253, 91, 401, 436], [53, 55, 131, 276]]
Chk 6991 [[383, 32, 639, 545], [1, 8, 402, 544]]
Chk 6992 [[150, 290, 333, 466], [0, 173, 369, 497]]
Chk 6994 [[318, 83, 609, 473], [65, 8, 386, 475], [506, 404, 561, 479]]
Chk 6995 [[127, 44, 447, 369], [316, 14, 499, 325], [0, 13, 248, 374], [354, 215, 498, 310]]
Chk 6996 [[17, 199, 229, 496], [225, 28, 389, 386], [110, 2, 168, 91], [108, 26, 266, 338]]
Chk 6997 [[333, 123, 563, 472], [98, 171, 285, 471]]
Chk 6998 [[97, 187, 317, 362], [313, 195, 597, 372]]
Chk 6999 [[209, 60, 384, 358], [369, 106, 504, 368], [417, 46, 504, 164], [31, 38, 202, 387], [579, 45, 639, 337]]
Chk 7000 [[60, 83, 363, 428], [327, 75, 479, 259], [1, 171, 85, 398], [52, 87, 135, 229], [238, 77, 310, 201], [276, 353, 479, 463]]
Chk 7002 [[423, 0, 597, 240], [103, 0, 361, 317], [83, 157, 288, 457]]
Chk 7004 [[0, 42, 316, 473], [105, 73, 299, 401], [434, 0, 639, 480], [448, 0, 541, 143]]
Chk 7005 [[2, 47, 221, 494], [148, 14, 351, 482]]
Chk 7007 [[511, 83, 639, 470], [0, 53, 579, 473]]
Chk 7008 [[173, 122, 639, 623], [0, 24, 309, 638]]
Chk 7009 [[189, 194, 323, 438], [66, 109, 268, 479], [285, 83, 405, 432], [391, 98, 563, 449], [67, 72, 165, 218]]
Chk 7010 [[298, 92, 439, 479], [65, 130, 236, 443]]
Chk 7012 [[103, 238, 392, 359], [369, 78, 481, 355]]
Chk 7013 [[449, 48, 639, 474], [2, 138, 231, 473], [350, 169, 417, 339], [429, 179, 485, 340], [144, 76, 453, 479], [435, 172, 502, 283], [494, 168, 547, 253]]
Chk 7014 [[191, 282, 281, 524], [160, 257, 273, 523], [62, 261, 144, 528], [11, 266, 88, 546]]
Chk 7015 [[413, 31, 591, 423], [322, 115, 401, 422]]
Chk 7016 [[170, 0, 597, 515], [0, 213, 288, 514]]
Chk 7017 [[0, 55, 227, 338], [104, 59, 224, 216], [219, 26, 315, 155], [377, 34, 454, 136], [487, 15, 558, 132], [518, 33, 638, 205]]
Chk 7018 [[279, 140, 408, 420], [510, 165, 637, 420]]
Chk 7021 [[240, 55, 565, 423], [160, 55, 278, 338], [122, 63, 185, 347]]
Chk 7022 [[157, 201, 349, 432], [357, 125, 615, 474]]
Chk 7023 [[255, 47, 545, 361], [232, 109, 357, 361], [0, 1, 236, 425], [505, 45, 639, 368]]
Chk 7024 [[52, 110, 144, 290], [244, 49, 385, 223], [361, 159, 542, 449]]
Chk 7025 [[110, 77, 285, 471], [442, 90, 584, 474], [274, 12, 461, 336], [277, 378, 391, 479], [552, 96, 638, 296]]
Chk 7026 [[94, 7, 457, 418], [37, 152, 191, 399]]
Chk 7027 [[53, 0, 528, 355], [2, 273, 523, 474], [451, 47, 551, 183], [432, 79, 565, 158]]
Chk 7028 [[140, 0, 499, 329], [5, 150, 145, 326]]
Chk 7030 [[2, 74, 304, 296], [313, 45, 623, 419], [460, 70, 545, 138]]
Chk 7031 [[176, 27, 355, 250], [311, 85, 496, 247], [394, 102, 639, 306], [1, 74, 161, 272]]
Chk 7033 [[160, 26, 401, 355], [264, 35, 321, 102], [384, 26, 594, 373], [113, 2, 181, 245], [559, 34, 639, 264], [309, 4, 491, 339], [511, 28, 573, 246]]
Chk 7035 [[117, 90, 289, 424], [337, 37, 561, 418]]
Chk 7036 [[299, 108, 529, 425], [230, 105, 297, 268], [197, 115, 269, 335], [279, 104, 354, 282], [13, 75, 111, 331], [38, 141, 242, 419], [128, 158, 329, 419], [443, 100, 539, 328]]
Chk 7037 [[28, 281, 405, 632], [0, 0, 492, 640], [90, 239, 195, 344]]
Chk 7038 [[189, 94, 300, 412], [497, 90, 623, 409], [106, 167, 228, 310]]
Chk 7039 [[108, 10, 308, 400], [318, 131, 457, 425]]
Chk 7040 [[268, 39, 417, 515], [81, 67, 283, 463], [527, 39, 631, 516], [258, 100, 311, 244], [97, 0, 185, 81], [387, 56, 550, 532]]
Chk 7041 [[200, 67, 541, 601], [67, 119, 259, 605], [146, 233, 297, 429]]
Chk 7042 [[367, 29, 487, 333], [5, 46, 244, 396], [371, 127, 459, 384], [457, 60, 639, 424]]
Chk 7043 [[455, 16, 596, 262], [220, 39, 370, 385]]
Chk 7044 [[445, 135, 548, 443], [183, 28, 277, 301], [265, 39, 344, 172]]
Chk 7045 [[141, 96, 314, 293], [36, 240, 299, 499], [0, 146, 127, 499]]
Chk 7046 [[251, 130, 478, 639], [54, 97, 256, 627]]
Chk 7047 [[48, 220, 226, 549], [192, 197, 276, 500], [231, 214, 321, 501]]
Chk 7048 [[61, 97, 176, 485], [241, 178, 418, 510]]

Chk 7049 [[326, 217, 476, 639], [2, 133, 127, 630]]
Chk 7050 [[386, 5, 560, 248], [97, 18, 405, 419], [78, 0, 254, 109]]
Chk 7052 [[142, 190, 323, 379], [382, 71, 548, 312]]
Chk 7053 [[151, 97, 302, 422], [247, 120, 317, 400], [1, 109, 91, 417], [452, 165, 571, 448], [309, 91, 396, 323], [322, 102, 486, 457]]
Chk 7055 [[14, 2, 477, 474], [393, 32, 639, 478]]
Chk 7056 [[258, 43, 532, 424], [12, 21, 364, 419], [379, 26, 515, 339]]
Chk 7057 [[317, 129, 476, 479], [156, 77, 322, 469], [544, 124, 638, 455], [426, 204, 482, 415]]
Chk 7058 [[15, 280, 447, 365], [356, 16, 467, 336]]
Chk 7059 [[106, 106, 304, 318], [563, 146, 639, 335], [0, 134, 66, 307], [296, 126, 490, 322]]
Chk 7060 [[270, 434, 414, 599], [106, 333, 255, 604], [273, 336, 353, 437], [374, 372, 426, 451], [86, 362, 153, 420]]
Chk 7061 [[0, 34, 395, 426], [213, 123, 391, 422], [364, 60, 639, 411]]
Chk 7063 [[82, 25, 252, 362], [263, 151, 376, 364], [487, 62, 617, 295], [295, 178, 541, 479], [335, 7, 497, 373]]
Chk 7064 [[169, 120, 355, 376], [374, 203, 494, 371], [69, 79, 128, 204], [389, 156, 456, 210], [414, 68, 481, 137], [527, 64, 626, 369], [159, 150, 226, 204]]
Chk 7065 [[6, 17, 205, 368], [224, 135, 450, 379], [564, 132, 639, 420], [28, 252, 125, 403]]
Chk 7066 [[209, 66, 339, 373], [64, 57, 210, 374], [26, 112, 84, 244]]
Chk 7067 [[390, 0, 638, 418], [292, 129, 514, 437]]
Chk 7069 [[258, 360, 387, 627], [112, 308, 283, 615]]
Chk 7070 [[279, 67, 500, 373], [0, 0, 306, 423]]
Chk 7071 [[79, 199, 327, 478], [243, 169, 424, 433], [0, 202, 216, 478], [439, 193, 639, 432]]
Chk 7072 [[159, 68, 300, 386], [351, 70, 466, 395]]
Chk 7073 [[24, 60, 355, 479], [46, 170, 222, 440], [370, 137, 541, 479], [266, 11, 613, 474]]
Chk 7074 [[124, 0, 357, 420], [405, 51, 601, 380]]
Chk 7075 [[242, 91, 397, 426], [1, 39, 73, 420], [295, 0, 350, 137]]
Chk 7076 [[214, 50, 386, 596], [27, 12, 255, 596]]
Chk 7077 [[0, 0, 335, 218], [0, 341, 107, 479], [359, 40, 532, 309], [0, 0, 60, 247]]
Chk 7078 [[173, 74, 267, 309], [107, 221, 263, 445], [217, 197, 371, 416]]
Chk 7079 [[264, 107, 400, 467], [15, 82, 397, 471]]
Chk 7080 [[290, 16, 430, 262], [441, 84, 573, 406], [317, 198, 433, 420]]
Chk 7081 [[201, 112, 413, 537], [17, 49, 287, 562]]
Chk 7082 [[214, 51, 436, 568], [77, 228, 250, 466], [403, 264, 462, 402], [428, 250, 518, 397]]
Chk 7084 [[216, 63, 330, 472], [305, 145, 436, 390], [405, 69, 525, 397], [2, 180, 78, 377], [147, 67, 252, 412], [507, 80, 639, 471]]
Chk 7085 [[0, 53, 347, 472], [283, 113, 499, 477]]
Chk 7086 [[483, 78, 574, 394], [153, 82, 334, 414], [193, 77, 393, 398], [43, 90, 136, 374], [271, 79, 401, 398]]
Chk 7087 [[1, 302, 219, 638], [145, 0, 479, 639]]
Chk 7088 [[40, 21, 241, 384], [228, 67, 395, 350], [470, 35, 639, 467]]
Chk 7089 [[235, 211, 393, 558], [40, 405, 247, 560], [192, 233, 392, 548]]
Chk 7090 [[0, 135, 115, 414], [257, 91, 395, 356], [42, 200, 157, 376]]
Chk 7092 [[210, 27, 370, 473], [76, 73, 250, 606]]
Chk 7093 [[248, 108, 631, 535], [6, 24, 360, 528]]
Chk 7094 [[136, 201, 356, 618], [303, 176, 501, 491]]
Chk 7095 [[382, 119, 435, 256], [72, 84, 167, 311], [526, 92, 595, 268], [134, 60, 335, 413]]
Chk 7096 [[355, 66, 517, 276], [94, 91, 262, 281]]
Chk 7097 [[406, 96, 555, 421], [168, 105, 320, 420]]
Chk 7098 [[227, 38, 313, 360], [310, 66, 433, 354]]
Chk 7099 [[220, 155, 338, 329], [584, 172, 639, 400], [410, 147, 602, 356]]
Chk 7100 [[44, 121, 323, 397], [325, 124, 473, 391], [223, 114, 381, 391]]
Chk 7101 [[234, 2, 591, 432], [250, 109, 639, 504]]
Chk 7102 [[330, 188, 501, 416], [70, 239, 211, 462], [186, 287, 334, 447], [78, 0, 155, 95], [0, 0, 94, 105]]
Chk 7103 [[330, 68, 544, 424], [570, 142, 639, 376], [206, 159, 334, 416]]
Chk 7104 [[182, 67, 424, 630], [20, 94, 240, 571]]
Chk 7105 [[236, 74, 404, 465], [368, 74, 552, 468], [121, 105, 280, 450], [153, 258, 221, 431]]
Chk 7106 [[154, 24, 289, 333], [433, 94, 506, 173], [239, 53, 357, 328], [291, 54, 533, 416], [1, 73, 55, 132], [46, 73, 160, 257]]
Chk 7107 [[18, 24, 475, 584], [99, 0, 314, 310]]
Chk 7108 [[1, 2, 274, 479], [352, 252, 596, 479]]
Chk 7109 [[275, 56, 347, 314], [117, 128, 230, 336], [5, 70, 110, 363], [368, 86, 494, 374]]
Chk 7110 [[89, 61, 317, 332], [316, 85, 436, 323]]
Chk 7113 [[13, 90, 276, 419], [119, 235, 383, 424]]
Chk 7115 [[282, 87, 561, 474], [451, 212, 639, 477]]
Chk 7116 [[57, 61, 402, 475], [286, 115, 481, 472]]
Chk 7117 [[198, 312, 283, 574], [22, 136, 253, 628]]
Chk 7118 [[31, 124, 227, 473], [433, 145, 569, 479], [220, 117, 390, 329]]
Chk 7119 [[189, 77, 421, 349], [501, 100, 606, 213], [483, 97, 554, 206], [405, 94, 483, 208], [457, 170, 639, 355]]
Chk 7121 [[251, 47, 459, 369], [10, 4, 266, 374]]
Chk 7123 [[65, 78, 241, 521], [221, 152, 447, 521], [216, 103, 337, 320], [366, 109, 479, 466]]
Chk 7124 [[153, 125, 333, 499], [62, 157, 179, 379]]
Chk 7125 [[391, 160, 509, 470], [83, 164, 209, 481]]
Chk 7126 [[159, 68, 438, 482], [397, 247, 639, 557], [444, 344, 521, 426]]
Chk 7127 [[408, 179, 463, 285], [474, 166, 555, 352], [170, 177, 238, 241], [75, 129, 251, 421], [0, 163, 85, 425], [0, 136, 79, 260]]
Chk 7128 [[5, 86, 269, 421], [293, 33, 561, 425]]
Chk 7130 [[407, 264, 538, 430], [495, 245, 609, 438], [501, 114, 553, 191], [547, 115, 614, 194], [55, 0, 144, 147], [170, 192, 346, 432]]
Chk 7132 [[94, 66, 331, 472], [332, 92, 639, 472]]
Chk 7133 [[217, 123, 502, 639], [36, 119, 244, 639]]
Chk 7134 [[1, 61, 163, 629], [200, 129, 385, 639], [146, 122, 416, 632]]
Chk 7135 [[49, 0, 331, 489], [2, 25, 141, 444]]
Chk 7137 [[307, 31, 497, 180], [101, 69, 329, 190]]
Chk 7139 [[297, 143, 396, 369], [102, 154, 201, 374], [188, 144, 297, 367]]
Chk 7140 [[313, 154, 470, 378], [221, 159, 582, 463], [190, 160, 498, 395]]
Chk 7141 [[190, 264, 323, 455], [159, 88, 252, 310]]
Chk 7142 [[272, 116, 478, 638], [0, 23, 260, 638]]
Chk 7143 [[170, 163, 278, 422], [336, 149, 399, 421], [393, 156, 506, 420], [234, 196, 306, 426], [48, 167, 175, 426], [48, 163, 145, 400], [265, 150, 364, 426]]
Chk 7145 [[329, 46, 623, 418], [0, 92, 297, 419]]
Chk 7148 [[96, 172, 283, 625], [484, 238, 603, 510]]
Chk 7149 [[112, 73, 271, 335], [78, 60, 437, 474], [330, 127, 638, 479]]
Chk 7150 [[0, 25, 349, 426], [222, 54, 402, 416], [586, 63, 639, 189]]
Chk 7151 [[65, 129, 265, 425], [326, 118, 488, 420]]
Chk 7152 [[44, 133, 347, 382], [189, 65, 342, 399]]
Chk 7155 [[13, 133, 213, 397], [53, 0, 273, 204], [163, 0, 639, 609]]
Chk 7156 [[91, 140, 334, 479], [275, 0, 401, 397], [0, 270, 94, 478], [0, 126, 106, 384]]
Chk 7157 [[235, 183, 405, 407], [157, 260, 271, 400], [38, 211, 186, 397], [97, 92, 148, 172]]
Chk 7158 [[260, 91, 405, 403], [330, 69, 523, 429]]
Chk 7160 [[112, 93, 194, 265], [278, 175, 458, 474], [423, 279, 563, 430], [499, 137, 570, 335], [29, 180, 284, 474]]
Chk 7162 [[156, 81, 281, 384], [232, 64, 467, 425]]
Chk 7163 [[351, 46, 428, 257], [214, 115, 298, 352], [496, 1, 561, 146], [554, 40, 618, 142]]
Chk 7164 [[80, 1, 400, 359], [265, 4, 639, 406], [0, 81, 161, 360]]
Chk 7165 [[274, 2, 633, 421], [45, 2, 219, 421]]
Chk 7167 [[296, 22, 508, 257], [117, 50, 293, 231], [28, 41, 158, 240]]
Chk 7168 [[117, 134, 262, 360], [0, 210, 141, 378]]
Chk 7169 [[0, 136, 528, 373], [310, 73, 559, 373]]
Chk 7171 [[85, 139, 422, 374], [237, 151, 331, 223], [0, 113, 422, 374]]
Chk 7172 [[373, 120, 539, 479], [84, 122, 225, 472]]
Chk 7174 [[0, 56, 216, 353], [166, 46, 347, 245], [259, 83, 479, 356], [154, 173, 340, 293]]
Chk 7175 [[173, 4, 308, 595], [100, 6, 207, 588]]
Chk 7176 [[69, 0, 505, 479], [422, 75, 639, 471]]
Chk 7177 [[96, 125, 344, 426], [281, 24, 558, 417]]
Chk 7178 [[253, 101, 607, 477], [192, 2, 417, 280], [452, 0, 539, 106], [49, 0, 269, 137], [0, 0, 64, 67], [123, 62, 203, 150], [139, 54, 268, 248], [359, 0, 453, 138]]
Chk 7179 [[291, 88, 479, 357], [266, 6, 354, 147], [247, 21, 322, 105], [63, 49, 211, 252], [1, 88, 173, 354], [277, 37, 426, 217], [426, 24, 479, 125], [113, 24, 190, 206]]
Chk 7181 [[182, 58, 366, 554], [50, 64, 251, 551]]
Chk 7182 [[168, 47, 275, 211], [1, 203, 284, 472], [312, 183, 425, 412], [361, 290, 464, 472], [292, 22, 558, 367]]
Chk 7183 [[18, 356, 158, 581], [201, 163, 421, 322], [205, 108, 321, 255]]
Chk 7185 [[118, 196, 251, 421], [296, 123, 490, 421]]
Chk 7186 [[316, 5, 506, 298], [206, 85, 370, 343], [26, 0, 335, 399]]
Chk 7187 [[372, 110, 499, 363], [265, 70, 387, 301]]
Chk 7189 [[244, 172, 347, 415], [360, 142, 490, 416]]
Chk 7190 [[379, 28, 524, 421], [50, 20, 236, 376]]

Chk 7191 [[173, 167, 297, 470], [239, 151, 399, 477], [353, 164, 455, 474], [424, 166, 547, 460]]
Chk 7192 [[111, 116, 251, 436], [374, 95, 458, 432]]
Chk 7193 [[67, 81, 199, 359], [226, 74, 410, 525], [367, 76, 605, 532], [0, 120, 222, 525]]
Chk 7194 [[236, 61, 398, 318], [68, 80, 274, 339]]
Chk 7195 [[61, 123, 274, 471], [242, 39, 402, 471], [379, 126, 571, 474]]
Chk 7196 [[266, 0, 639, 417], [28, 93, 292, 361]]
Chk 7197 [[229, 1, 486, 368], [0, 20, 257, 368], [197, 109, 257, 189]]
Chk 7199 [[68, 112, 263, 453], [330, 108, 473, 414], [438, 61, 584, 457]]
Chk 7200 [[320, 188, 443, 479], [396, 172, 485, 466], [461, 157, 609, 468]]
Chk 7201 [[275, 66, 494, 295], [0, 54, 86, 280], [197, 42, 254, 106], [86, 0, 137, 103]]
Chk 7202 [[230, 215, 355, 444], [98, 106, 225, 440]]
Chk 7206 [[92, 185, 233, 526], [188, 182, 349, 511]]
Chk 7210 [[60, 130, 245, 320], [332, 89, 539, 315], [31, 0, 111, 159], [154, 69, 215, 159], [285, 13, 339, 87], [529, 1, 583, 70], [20, 100, 92, 211], [474, 12, 528, 73]]
Chk 7211 [[300, 130, 444, 359], [98, 36, 301, 325]]
Chk 7212 [[201, 123, 348, 351], [436, 195, 592, 397], [403, 201, 588, 375]]
Chk 7213 [[161, 0, 586, 198], [419, 70, 558, 169], [59, 130, 384, 420]]
Chk 7214 [[294, 127, 469, 554], [1, 101, 178, 543]]
Chk 7215 [[215, 44, 375, 422], [359, 33, 518, 284]]
Chk 7216 [[119, 0, 611, 609], [75, 17, 352, 440]]
Chk 7217 [[510, 141, 564, 388], [243, 15, 382, 339], [130, 20, 206, 283], [197, 10, 291, 323], [23, 73, 175, 415], [7, 41, 66, 377], [95, 32, 169, 165], [86, 73, 148, 189]]
Chk 7218 [[0, 151, 53, 366], [70, 107, 333, 631], [283, 205, 417, 595], [305, 111, 405, 258], [245, 138, 332, 246]]
Chk 7219 [[38, 82, 178, 316], [170, 157, 307, 314], [324, 126, 460, 309]]
Chk 7221 [[174, 129, 452, 450], [95, 198, 250, 456]]
Chk 7222 [[98, 9, 288, 575], [263, 60, 509, 588]]
Chk 7224 [[143, 209, 324, 593], [327, 164, 451, 545]]
Chk 7225 [[279, 267, 447, 513], [428, 244, 587, 519]]
Chk 7226 [[73, 109, 260, 378], [391, 115, 541, 377], [0, 195, 192, 479], [493, 157, 639, 479]]
Chk 7228 [[192, 77, 531, 424], [36, 68, 303, 353]]
Chk 7229 [[43, 9, 353, 630], [237, 124, 458, 615], [347, 0, 479, 531]]
Chk 7231 [[119, 168, 348, 587], [28, 309, 234, 600]]
Chk 7236 [[191, 42, 370, 254], [29, 187, 468, 369]]
Chk 7237 [[31, 202, 580, 474], [174, 35, 348, 270], [113, 98, 329, 348]]
Chk 7238 [[128, 42, 397, 479], [312, 136, 423, 329], [1, 2, 224, 472]]
Chk 7239 [[250, 155, 462, 423], [421, 171, 487, 263], [0, 86, 246, 423]]
Chk 7240 [[130, 195, 410, 639], [177, 246, 229, 317], [371, 260, 479, 607], [0, 121, 222, 631]]
Chk 7241 [[183, 44, 367, 419], [322, 170, 528, 419], [0, 261, 286, 417]]
Chk 7242 [[80, 130, 294, 475], [135, 441, 321, 630]]
Chk 7243 [[207, 141, 416, 469], [38, 151, 285, 545]]
Chk 7246 [[378, 101, 453, 368], [222, 96, 340, 419], [80, 237, 146, 382], [301, 126, 411, 214], [560, 11, 639, 413], [0, 140, 95, 399]]
Chk 7247 [[36, 204, 208, 511], [452, 72, 585, 357], [368, 215, 510, 359], [450, 103, 526, 237], [380, 108, 525, 412]]
Chk 7250 [[208, 279, 309, 512], [295, 262, 405, 505], [433, 326, 567, 507], [385, 286, 446, 354], [508, 318, 595, 507]]
Chk 7251 [[98, 101, 474, 469], [271, 116, 549, 336], [9, 69, 202, 435]]
Chk 7252 [[285, 65, 457, 345], [406, 28, 511, 280], [40, 76, 338, 474]]
Chk 7253 [[232, 113, 368, 339], [472, 27, 535, 347]]
Chk 7254 [[256, 146, 469, 479], [70, 150, 217, 479]]
Chk 7255 [[267, 137, 387, 602], [172, 149, 297, 585], [58, 116, 183, 570]]
Chk 7256 [[64, 201, 315, 452], [10, 100, 316, 463], [262, 121, 639, 478], [490, 0, 542, 105], [0, 15, 63, 68]]
Chk 7257 [[1, 87, 190, 391], [192, 41, 459, 399]]
Chk 7258 [[106, 252, 160, 386], [239, 68, 296, 129], [356, 22, 466, 353], [40, 249, 113, 359], [158, 160, 264, 492]]
Chk 7259 [[134, 106, 251, 378], [234, 114, 338, 360]]
Chk 7260 [[85, 80, 252, 425], [403, 105, 456, 270], [211, 112, 397, 399], [265, 39, 637, 419], [323, 116, 413, 341], [0, 94, 146, 425]]
Chk 7261 [[176, 150, 369, 629], [1, 67, 128, 631], [321, 329, 424, 500], [81, 293, 221, 547]]
Chk 7262 [[348, 10, 544, 355], [138, 17, 399, 359]]
Chk 7263 [[322, 12, 438, 179], [256, 1, 351, 129], [6, 78, 141, 272]]
Chk 7264 [[80, 116, 187, 376], [176, 158, 389, 383], [200, 25, 284, 202]]
Chk 7265 [[186, 169, 426, 632], [0, 161, 149, 639]]
Chk 7266 [[383, 133, 533, 468], [9, 54, 230, 477]]
Chk 7267 [[331, 9, 595, 400], [72, 15, 242, 227]]
Chk 7268 [[54, 18, 164, 233], [155, 20, 267, 270], [254, 64, 344, 289], [236, 323, 464, 569]]
Chk 7270 [[271, 6, 401, 340], [21, 20, 185, 323]]
Chk 7273 [[33, 65, 209, 364], [125, 70, 360, 367], [147, 69, 478, 369]]
Chk 7274 [[142, 162, 364, 439], [548, 232, 639, 473], [382, 282, 586, 464]]
Chk 7275 [[235, 237, 378, 425], [76, 131, 233, 421], [267, 160, 351, 280]]
Chk 7279 [[39, 16, 329, 193], [330, 125, 479, 286]]
Chk 7281 [[206, 50, 476, 363], [12, 50, 263, 363]]
Chk 7283 [[176, 114, 296, 545], [291, 110, 436, 634], [155, 152, 206, 250], [36, 210, 115, 339], [420, 159, 482, 407]]
Chk 7284 [[290, 32, 569, 400], [31, 35, 362, 357]]
Chk 7285 [[54, 76, 155, 398], [127, 46, 234, 336], [294, 345, 435, 473], [242, 63, 333, 337]]
Chk 7286 [[112, 34, 437, 370], [187, 540, 242, 639], [53, 19, 194, 283]]
Chk 7288 [[66, 111, 209, 311], [364, 125, 605, 409], [209, 112, 317, 264]]
Chk 7289 [[248, 174, 339, 285], [372, 187, 534, 425], [173, 194, 270, 326], [106, 208, 238, 339], [2, 208, 196, 415], [390, 209, 453, 298], [327, 176, 398, 287]]
Chk 7291 [[151, 326, 319, 512], [7, 84, 204, 564]]
Chk 7293 [[176, 56, 270, 238], [121, 199, 469, 420], [422, 38, 553, 324]]
Chk 7294 [[78, 116, 313, 473], [310, 297, 479, 538]]
Chk 7295 [[189, 89, 360, 426], [511, 143, 604, 421], [355, 210, 413, 273]]
Chk 7297 [[189, 135, 551, 419], [90, 0, 555, 420], [213, 8, 265, 97]]
Chk 7298 [[246, 79, 354, 216], [344, 78, 477, 294], [403, 117, 627, 479], [287, 18, 373, 100], [158, 6, 220, 114], [215, 3, 274, 119], [19, 113, 224, 443]]
Chk 7301 [[207, 141, 342, 478], [2, 1, 244, 471], [418, 105, 525, 475]]
Chk 7303 [[1, 1, 347, 471], [251, 29, 438, 335]]
Chk 7304 [[460, 0, 513, 151], [0, 155, 279, 440], [350, 77, 505, 378], [0, 128, 72, 222]]
Chk 7305 [[221, 26, 374, 398], [395, 66, 540, 259]]
Chk 7306 [[164, 60, 355, 358], [304, 0, 373, 141], [421, 161, 620, 385], [451, 1, 524, 149], [232, 0, 324, 81], [393, 6, 470, 131]]
Chk 7307 [[66, 126, 389, 604], [334, 26, 610, 604], [52, 193, 134, 327]]
Chk 7308 [[251, 111, 485, 278], [0, 123, 244, 290]]
Chk 7310 [[146, 183, 257, 478], [0, 178, 172, 479]]
Chk 7311 [[0, 89, 224, 473], [137, 154, 258, 323], [216, 175, 321, 404], [365, 181, 437, 291], [412, 190, 517, 329], [554, 208, 611, 283]]
Chk 7312 [[258, 99, 383, 465], [404, 175, 531, 415]]
Chk 7314 [[170, 339, 298, 638], [56, 326, 189, 630]]
Chk 7315 [[141, 32, 312, 382], [268, 330, 356, 389], [163, 189, 380, 383], [276, 27, 481, 384]]
Chk 7316 [[89, 110, 298, 303], [319, 92, 457, 323]]
Chk 7317 [[68, 91, 320, 478], [269, 113, 639, 479]]
Chk 7318 [[353, 0, 455, 78], [91, 75, 404, 413], [104, 0, 181, 56], [421, 239, 639, 442]]
Chk 7320 [[88, 167, 368, 471], [0, 419, 54, 479], [367, 156, 634, 473]]
Chk 7321 [[6, 180, 328, 562], [349, 54, 625, 569]]
Chk 7322 [[136, 68, 337, 396], [286, 53, 389, 289], [346, 18, 604, 424], [212, 71, 317, 337], [322, 50, 477, 275]]
Chk 7323 [[259, 45, 374, 341], [327, 90, 603, 406], [563, 85, 639, 252], [70, 122, 319, 361], [1, 171, 80, 340]]
Chk 7324 [[150, 188, 301, 421], [84, 62, 289, 421]]
Chk 7325 [[135, 23, 438, 407], [544, 353, 639, 418], [20, 0, 462, 403]]
Chk 7326 [[61, 63, 402, 493], [270, 20, 448, 398]]
Chk 7327 [[366, 118, 474, 407], [543, 148, 618, 415], [74, 112, 201, 297]]
Chk 7328 [[59, 96, 429, 479], [130, 1, 433, 477]]
Chk 7329 [[116, 269, 321, 639], [0, 307, 133, 639]]
Chk 7330 [[238, 17, 382, 481], [307, 33, 632, 542]]
Chk 7331 [[115, 47, 236, 338], [428, 24, 575, 349], [62, 95, 118, 243], [218, 81, 409, 333]]
Chk 7333 [[138, 47, 374, 599], [334, 136, 425, 476], [31, 41, 103, 131], [169, 8, 227, 117], [129, 254, 322, 631], [126, 34, 178, 130]]
Chk 7334 [[6, 148, 242, 498], [277, 2, 627, 494]]
Chk 7339 [[64, 82, 238, 323], [204, 152, 371, 322], [479, 51, 639, 327], [436, 0, 639, 315]]
Chk 7340 [[15, 14, 405, 599], [384, 225, 599, 605]]
Chk 7341 [[2, 4, 248, 357], [174, 58, 393, 364]]

Chk 7342 [[176, 138, 370, 639], [170, 129, 403, 599]]
Chk 7343 [[65, 62, 325, 449], [284, 17, 610, 461]]
Chk 7344 [[114, 230, 477, 638], [47, 88, 200, 247], [175, 91, 303, 271], [157, 165, 334, 397]]
Chk 7350 [[173, 88, 375, 384], [350, 72, 580, 383]]
Chk 7351 [[150, 40, 304, 385], [283, 50, 489, 361]]
Chk 7352 [[211, 25, 364, 400], [364, 21, 537, 403], [44, 104, 245, 377], [28, 124, 132, 347], [360, 99, 493, 397]]
Chk 7353 [[227, 65, 317, 274], [100, 126, 253, 322], [1, 156, 215, 453], [345, 239, 639, 473], [487, 110, 623, 274]]
Chk 7354 [[187, 175, 320, 513], [298, 159, 450, 557], [0, 198, 99, 481]]
Chk 7355 [[343, 68, 638, 479], [1, 48, 367, 469]]
Chk 7356 [[47, 194, 186, 626], [142, 180, 304, 631]]
Chk 7357 [[217, 201, 320, 632], [38, 195, 229, 630]]
Chk 7359 [[434, 37, 619, 354], [188, 45, 294, 309], [495, 46, 613, 308], [116, 39, 304, 364]]
Chk 7360 [[244, 436, 372, 631], [0, 506, 94, 640], [138, 452, 246, 639], [78, 519, 152, 638]]
Chk 7361 [[250, 120, 429, 375], [0, 103, 203, 422], [475, 117, 637, 422], [0, 171, 78, 363], [388, 140, 488, 295], [350, 158, 409, 262]]
Chk 7362 [[54, 169, 245, 631], [84, 99, 343, 639], [236, 212, 411, 409], [411, 240, 493, 522]]
Chk 7365 [[343, 116, 638, 419], [284, 91, 639, 423], [0, 26, 372, 428]]
Chk 7366 [[313, 247, 395, 519], [205, 224, 312, 517]]
Chk 7368 [[314, 90, 524, 328], [157, 15, 353, 420], [17, 23, 217, 419], [0, 5, 134, 426], [279, 0, 363, 228], [205, 0, 272, 84]]
Chk 7369 [[106, 13, 379, 365], [281, 21, 525, 370]]
Chk 7370 [[2, 1, 227, 461], [229, 214, 620, 472], [582, 1, 639, 254]]
Chk 7371 [[361, 45, 552, 266], [249, 32, 376, 267], [174, 55, 287, 259], [457, 0, 513, 102]]
Chk 7372 [[73, 85, 344, 478], [1, 0, 238, 473]]
Chk 7373 [[27, 1, 417, 474], [152, 64, 393, 437]]
Chk 7374 [[10, 39, 271, 579], [284, 41, 500, 566]]
Chk 7375 [[58, 103, 231, 372], [345, 53, 443, 237], [370, 20, 538, 443], [518, 26, 639, 476]]
Chk 7376 [[85, 23, 404, 426], [290, 52, 537, 191], [335, 122, 440, 281]]
Chk 7377 [[1, 74, 241, 535], [170, 316, 458, 533]]
Chk 7378 [[57, 114, 369, 484], [509, 0, 639, 287], [195, 17, 639, 639]]
Chk 7379 [[0, 46, 247, 370], [153, 0, 300, 372]]
Chk 7381 [[170, 142, 339, 544], [272, 131, 362, 535]]
Chk 7382 [[347, 89, 513, 473], [207, 152, 360, 479]]
Chk 7383 [[270, 83, 388, 348], [174, 121, 253, 277], [81, 93, 191, 242], [471, 1, 639, 371], [158, 181, 210, 245]]
Chk 7384 [[491, 140, 584, 371], [383, 138, 504, 400], [353, 242, 409, 394], [149, 190, 259, 430], [308, 183, 372, 380]]
Chk 7385 [[489, 1, 639, 471], [49, 62, 169, 407], [42, 39, 410, 479], [542, 126, 639, 195], [193, 207, 417, 452]]
Chk 7386 [[165, 99, 349, 421], [109, 23, 235, 371], [300, 84, 411, 374], [400, 136, 473, 372]]
Chk 7389 [[124, 237, 252, 444], [229, 176, 304, 373], [45, 13, 188, 462]]
Chk 7390 [[333, 147, 395, 307], [232, 141, 289, 306], [157, 142, 210, 300], [31, 111, 100, 316], [1, 83, 93, 474], [430, 150, 493, 343], [366, 140, 529, 426], [487, 124, 625, 478]]
Chk 7391 [[167, 15, 365, 299], [317, 6, 576, 350]]
Chk 7392 [[46, 0, 257, 253], [363, 1, 558, 187], [423, 0, 639, 358], [488, 166, 639, 428], [82, 65, 408, 403]]
Chk 7393 [[263, 16, 639, 419], [207, 168, 280, 381], [128, 158, 225, 418], [45, 169, 96, 305], [96, 171, 156, 387]]
Chk 7394 [[446, 24, 639, 273], [0, 0, 250, 334], [311, 52, 408, 258]]
Chk 7395 [[191, 59, 465, 391], [0, 174, 209, 421], [72, 0, 128, 141]]
Chk 7396 [[37, 129, 293, 419], [216, 142, 639, 419]]
Chk 7397 [[0, 92, 209, 419], [229, 163, 452, 426]]
Chk 7399 [[67, 67, 281, 315], [269, 118, 401, 315], [457, 7, 639, 420], [42, 143, 230, 422]]
Chk 7400 [[0, 105, 248, 473], [230, 151, 544, 472]]
Chk 7401 [[22, 68, 290, 421], [138, 56, 262, 190], [345, 97, 569, 404], [337, 65, 482, 195]]
Chk 7402 [[80, 2, 298, 382], [8, 161, 323, 633]]
Chk 7403 [[248, 72, 378, 354], [432, 154, 499, 358], [52, 34, 221, 358]]
Chk 7404 [[493, 248, 547, 319], [416, 227, 639, 448], [372, 263, 425, 321], [220, 236, 277, 416], [391, 261, 474, 354], [60, 263, 131, 410], [179, 67, 430, 451]]
Chk 7406 [[213, 28, 508, 602], [388, 24, 490, 324], [93, 12, 317, 524], [71, 22, 194, 225], [472, 43, 574, 396]]
Chk 7407 [[82, 169, 271, 460], [290, 154, 492, 405], [122, 245, 300, 437]]
Chk 7408 [[235, 43, 459, 311], [10, 62, 182, 359], [0, 211, 135, 406], [212, 338, 306, 406], [122, 339, 206, 405], [424, 346, 560, 406]]
Chk 7410 [[214, 148, 315, 413], [2, 113, 102, 420], [98, 235, 154, 286], [443, 85, 639, 419], [301, 48, 481, 331], [109, 168, 161, 238]]
Chk 7412 [[71, 98, 298, 423], [329, 116, 547, 299], [417, 253, 547, 344]]
Chk 7413 [[113, 127, 619, 304], [343, 112, 638, 307]]
Chk 7414 [[229, 97, 444, 470], [395, 130, 508, 408]]
Chk 7415 [[137, 2, 439, 433], [0, 1, 198, 554], [0, 277, 64, 399]]
Chk 7416 [[468, 25, 639, 346], [336, 56, 527, 318]]
Chk 7417 [[140, 62, 347, 425], [463, 80, 639, 421]]
Chk 7420 [[179, 195, 343, 397], [356, 49, 520, 380], [344, 35, 396, 165]]
Chk 7422 [[224, 168, 520, 412], [422, 20, 535, 328], [352, 64, 427, 308], [262, 22, 382, 387]]
Chk 7423 [[192, 67, 376, 479], [349, 89, 517, 479], [489, 194, 601, 445], [2, 411, 291, 474], [446, 169, 500, 409], [560, 187, 639, 450]]
Chk 7424 [[0, 1, 273, 304], [195, 1, 611, 281]]
Chk 7427 [[362, 186, 518, 342], [471, 161, 596, 368], [142, 137, 311, 367]]
Chk 7428 [[103, 159, 235, 434], [1, 107, 81, 427], [308, 185, 440, 436], [236, 243, 319, 378], [300, 218, 371, 384], [405, 176, 592, 427], [193, 189, 309, 434], [90, 148, 193, 439]]
Chk 7429 [[2, 12, 259, 417], [203, 80, 478, 415], [402, 82, 637, 425]]
Chk 7430 [[87, 44, 427, 473], [400, 133, 639, 471]]
Chk 7432 [[24, 21, 236, 417], [359, 9, 622, 422]]
Chk 7433 [[17, 35, 258, 629], [243, 19, 343, 639]]
Chk 7434 [[47, 136, 240, 416], [42, 287, 222, 466], [341, 168, 489, 358], [242, 240, 477, 467], [497, 107, 639, 473], [230, 0, 294, 126]]
Chk 7435 [[176, 72, 230, 161], [238, 159, 424, 425], [273, 48, 433, 363]]
Chk 7436 [[157, 51, 394, 473], [255, 65, 603, 473]]
Chk 7437 [[20, 207, 135, 448], [143, 255, 300, 432], [262, 63, 450, 319]]
Chk 7438 [[125, 385, 305, 628], [0, 373, 110, 577], [0, 327, 119, 466]]
Chk 7439 [[137, 109, 288, 402], [243, 86, 512, 379]]
Chk 7440 [[94, 70, 373, 417], [347, 158, 590, 417]]
Chk 7443 [[49, 0, 492, 328], [0, 0, 99, 328]]
Chk 7444 [[183, 146, 329, 374], [2, 97, 185, 370], [264, 148, 398, 370], [334, 188, 416, 351], [68, 49, 145, 253]]
Chk 7445 [[1, 1, 378, 344], [371, 100, 530, 326], [348, 116, 541, 297]]
Chk 7446 [[14, 51, 190, 290], [179, 86, 292, 251], [306, 70, 454, 265], [500, 66, 587, 193], [552, 93, 626, 291], [459, 107, 519, 218]]
Chk 7447 [[114, 217, 295, 447], [249, 137, 384, 422]]
Chk 7448 [[4, 131, 138, 470], [432, 55, 640, 479], [247, 183, 368, 368], [327, 148, 476, 398], [39, 305, 150, 392]]
Chk 7449 [[67, 62, 358, 406], [352, 83, 607, 420]]
Chk 7450 [[136, 229, 343, 610], [0, 310, 221, 639]]
Chk 7452 [[58, 145, 200, 323], [270, 18, 459, 233], [587, 242, 639, 351], [346, 1, 628, 398]]
Chk 7453 [[216, 123, 404, 605], [459, 129, 611, 604], [26, 48, 172, 449], [358, 127, 474, 604], [133, 119, 251, 414]]
Chk 7454 [[226, 173, 383, 639], [204, 97, 443, 631], [63, 294, 283, 638], [1, 290, 126, 639]]
Chk 7455 [[448, 48, 562, 323], [408, 81, 474, 315], [283, 56, 340, 274], [72, 77, 258, 448], [340, 68, 426, 297], [312, 66, 379, 287]]
Chk 7456 [[249, 118, 639, 452], [109, 108, 401, 450]]
Chk 7457 [[137, 106, 450, 562], [398, 139, 506, 456]]
Chk 7458 [[264, 22, 375, 417], [142, 25, 253, 449], [58, 52, 167, 371], [361, 20, 639, 474], [0, 299, 105, 478]]
Chk 7460 [[166, 66, 353, 352], [304, 5, 485, 263], [213, 4, 337, 138]]
Chk 7461 [[495, 110, 639, 474], [0, 82, 229, 472], [406, 125, 478, 252]]
Chk 7463 [[2, 0, 261, 354], [325, 6, 625, 406]]
Chk 7464 [[108, 163, 290, 469], [294, 173, 490, 473]]
Chk 7466 [[135, 44, 340, 370], [231, 44, 352, 374], [285, 126, 354, 295], [431, 111, 499, 281]]
Chk 7467 [[229, 46, 343, 306], [323, 92, 375, 318], [199, 67, 259, 275], [143, 69, 208, 221], [410, 72, 461, 170], [0, 64, 156, 404], [338, 81, 467, 391]]
Chk 7468 [[31, 74, 207, 474], [327, 45, 459, 356]]
Chk 7469 [[2, 147, 308, 631], [250, 140, 479, 631]]
Chk 7470 [[67, 18, 178, 312], [194, 15, 449, 328], [170, 28, 266, 293]]
Chk 7471 [[51, 130, 212, 474], [465, 1, 639, 473]]
Chk 7473 [[1, 3, 407, 461], [228, 91, 638, 458]]
Chk 7475 [[309, 151, 593, 474], [21, 60, 348, 474], [301, 186, 372, 283]]
Chk 7476 [[138, 36, 499, 419], [0, 0, 272, 421], [1, 0, 74, 141]]
Chk 7478 [[178, 58, 424, 467], [0, 49, 412, 628]]

Chk 7479 [[426, 88, 639, 381], [240, 103, 466, 418], [101, 160, 403, 479]]
Chk 7480 [[24, 59, 83, 203], [91, 108, 147, 190], [250, 59, 304, 215], [474, 12, 544, 275], [99, 148, 284, 286], [394, 45, 452, 240]]
Chk 7481 [[247, 106, 404, 326], [376, 103, 514, 343], [186, 102, 312, 320]]
Chk 7482 [[123, 97, 256, 386], [17, 105, 76, 286], [166, 73, 391, 419], [427, 112, 488, 244]]
Chk 7484 [[155, 139, 327, 357], [230, 110, 342, 352], [335, 117, 577, 378], [324, 154, 495, 382], [337, 120, 396, 306]]
Chk 7485 [[396, 150, 636, 474], [432, 167, 499, 299], [116, 165, 261, 415], [59, 115, 151, 270], [0, 148, 93, 310], [207, 146, 281, 262], [407, 124, 478, 237]]
Chk 7488 [[375, 94, 508, 420], [58, 20, 386, 420], [83, 90, 234, 418], [365, 99, 423, 222]]
Chk 7489 [[39, 372, 229, 639], [84, 330, 236, 526]]
Chk 7490 [[64, 30, 279, 479], [1, 159, 277, 470]]
Chk 7491 [[276, 103, 526, 462], [231, 36, 346, 341], [309, 176, 383, 379]]
Chk 7492 [[99, 191, 372, 638], [342, 225, 450, 629]]
Chk 7494 [[63, 114, 244, 473], [189, 115, 328, 479]]
Chk 7495 [[269, 69, 380, 283], [375, 103, 532, 460], [95, 119, 245, 478]]
Chk 7496 [[323, 87, 547, 309], [21, 1, 253, 263]]
Chk 7499 [[8, 138, 353, 333], [406, 64, 639, 339]]
Chk 7500 [[266, 14, 511, 473], [0, 155, 57, 279], [12, 42, 320, 479]]
Chk 7501 [[121, 1, 411, 378], [278, 66, 639, 396]]
Chk 7502 [[525, 123, 639, 372], [174, 118, 337, 379], [326, 190, 501, 374], [74, 189, 170, 352], [0, 192, 55, 348]]
Chk 7503 [[205, 128, 330, 381], [387, 136, 512, 363], [0, 279, 212, 474], [61, 144, 208, 260], [442, 203, 599, 423]]
Chk 7504 [[405, 24, 614, 417], [22, 37, 252, 419]]
Chk 7505 [[223, 63, 432, 362], [136, 6, 356, 383], [0, 54, 321, 538], [90, 227, 261, 415], [343, 224, 457, 339], [0, 462, 254, 639]]
Chk 7506 [[292, 146, 393, 440], [363, 128, 521, 445], [194, 134, 304, 451]]
Chk 7507 [[225, 166, 445, 370], [32, 50, 283, 368]]
Chk 7508 [[139, 130, 345, 639], [112, 136, 301, 393]]
Chk 7510 [[134, 64, 241, 228], [119, 164, 310, 425], [426, 110, 577, 425], [314, 20, 467, 109], [323, 159, 444, 332]]
Chk 7511 [[99, 162, 344, 430], [486, 170, 626, 468], [340, 99, 492, 401], [0, 125, 56, 271]]
Chk 7512 [[60, 264, 278, 522], [224, 282, 275, 397], [173, 256, 298, 417], [340, 265, 626, 631], [2, 237, 161, 639], [267, 280, 356, 394], [46, 262, 115, 381]]
Chk 7513 [[137, 73, 232, 197], [387, 57, 530, 167], [434, 117, 637, 347], [48, 100, 213, 318], [397, 84, 536, 233], [556, 420, 639, 479]]
Chk 7514 [[145, 95, 281, 266], [312, 81, 460, 277], [447, 89, 639, 365], [2, 95, 104, 192], [523, 410, 640, 475], [276, 60, 365, 198], [457, 68, 535, 221]]
Chk 7516 [[159, 43, 556, 599], [506, 92, 623, 517]]
Chk 7517 [[128, 123, 398, 630], [2, 131, 201, 639], [0, 61, 68, 244]]
Chk 7518 [[410, 94, 540, 252], [257, 113, 388, 238], [138, 119, 271, 254], [7, 102, 187, 299], [0, 125, 163, 418], [531, 82, 590, 165]]
Chk 7520 [[145, 93, 300, 314], [50, 148, 277, 422], [79, 145, 207, 369], [261, 93, 319, 158], [365, 101, 476, 270], [400, 88, 459, 159]]
Chk 7521 [[468, 73, 639, 473], [0, 0, 271, 479]]
Chk 7523 [[143, 68, 348, 497], [21, 69, 145, 470]]
Chk 7524 [[355, 153, 474, 411], [199, 152, 312, 383], [287, 179, 362, 405]]
Chk 7525 [[93, 99, 479, 629], [35, 137, 171, 394], [408, 172, 477, 370], [0, 132, 66, 402], [98, 64, 472, 438]]
Chk 7526 [[1, 57, 232, 455], [470, 0, 639, 349], [366, 1, 474, 197], [13, 0, 182, 147]]
Chk 7527 [[516, 165, 577, 224], [504, 67, 556, 223], [76, 28, 282, 420], [405, 5, 550, 367]]
Chk 7529 [[359, 199, 524, 357], [514, 119, 639, 365], [111, 91, 326, 330]]
Chk 7531 [[71, 103, 167, 326], [263, 93, 368, 327], [378, 118, 493, 328], [333, 84, 402, 198], [164, 119, 267, 328], [146, 90, 209, 167], [232, 77, 306, 165], [9, 88, 110, 328]]
Chk 7532 [[91, 13, 331, 456], [241, 199, 395, 479]]
Chk 7533 [[226, 78, 416, 302], [45, 201, 220, 379]]
Chk 7534 [[1, 116, 217, 330], [151, 108, 330, 342], [297, 70, 458, 314]]
Chk 7535 [[128, 135, 363, 427], [394, 128, 552, 321]]
Chk 7536 [[0, 25, 140, 212], [184, 34, 319, 211], [407, 5, 601, 212]]
Chk 7538 [[202, 104, 612, 508], [26, 104, 182, 261], [188, 209, 416, 490], [366, 90, 534, 286]]
Chk 7539 [[336, 7, 607, 324], [14, 13, 265, 396]]
Chk 7540 [[44, 135, 438, 632], [166, 222, 274, 639], [240, 243, 328, 581], [363, 324, 440, 564]]
Chk 7541 [[98, 214, 231, 587], [192, 236, 293, 541]]
Chk 7542 [[318, 253, 639, 420], [0, 249, 146, 421]]
Chk 7543 [[194, 138, 419, 576], [388, 83, 498, 209], [1, 89, 163, 562], [390, 197, 478, 384]]
Chk 7544 [[258, 36, 553, 474], [166, 217, 361, 473]]
Chk 7545 [[410, 87, 577, 423], [184, 86, 373, 421]]
Chk 7546 [[230, 121, 422, 462], [402, 18, 639, 472], [0, 72, 200, 473]]
Chk 7547 [[143, 202, 352, 409], [25, 142, 159, 405], [296, 90, 527, 372]]
Chk 7549 [[125, 65, 490, 353], [482, 63, 638, 358], [143, 98, 346, 340]]
Chk 7550 [[0, 17, 343, 419], [193, 0, 440, 417], [0, 1, 61, 196], [315, 57, 389, 231], [394, 10, 555, 371], [494, 3, 606, 424]]
Chk 7551 [[330, 80, 543, 554], [17, 56, 231, 631]]
Chk 7552 [[365, 108, 505, 270], [1, 116, 149, 302], [140, 98, 251, 240], [517, 51, 571, 151], [475, 130, 636, 440]]
Chk 7553 [[326, 86, 417, 232], [113, 171, 244, 479], [495, 200, 620, 473]]
Chk 7554 [[99, 252, 248, 631], [83, 296, 144, 535], [353, 260, 479, 631], [209, 254, 382, 633], [0, 533, 219, 639]]
Chk 7555 [[30, 137, 250, 536], [156, 97, 363, 493], [90, 0, 142, 51]]
Chk 7556 [[46, 133, 188, 317], [341, 40, 462, 309], [334, 209, 598, 480], [0, 200, 241, 474]]
Chk 7557 [[279, 104, 639, 471], [304, 80, 498, 479]]
Chk 7558 [[166, 0, 441, 380], [0, 26, 153, 369]]
Chk 7559 [[136, 99, 281, 473], [339, 75, 550, 463], [483, 381, 570, 476], [563, 363, 633, 479]]
Chk 7560 [[223, 152, 365, 532], [53, 99, 241, 629]]
Chk 7561 [[14, 88, 421, 423], [90, 54, 639, 424], [14, 269, 65, 423]]
Chk 7562 [[35, 80, 149, 428], [186, 142, 290, 442], [351, 238, 460, 465]]
Chk 7563 [[352, 95, 513, 380], [116, 92, 438, 419], [127, 240, 294, 407]]
Chk 7564 [[72, 289, 203, 478], [261, 299, 381, 517]]
Chk 7565 [[51, 75, 174, 321], [161, 62, 317, 350], [335, 3, 499, 370], [307, 111, 391, 331]]
Chk 7566 [[352, 70, 577, 321], [0, 62, 271, 335]]
Chk 7567 [[1, 117, 231, 414], [124, 198, 238, 313], [317, 205, 380, 288], [412, 202, 506, 291], [487, 198, 639, 321], [493, 23, 628, 262], [226, 208, 320, 310]]
Chk 7568 [[321, 102, 451, 426], [158, 26, 350, 426]]
Chk 7569 [[247, 13, 610, 393], [0, 132, 107, 419], [23, 0, 400, 421]]
Chk 7570 [[82, 203, 214, 422], [155, 177, 217, 263], [342, 187, 409, 256], [430, 169, 498, 259], [410, 206, 579, 422], [185, 224, 390, 420], [494, 180, 591, 376]]
Chk 7573 [[88, 44, 272, 353], [212, 71, 364, 359]]
Chk 7574 [[52, 78, 307, 374], [274, 22, 494, 369]]
Chk 7575 [[67, 3, 246, 465], [200, 46, 461, 472]]
Chk 7577 [[49, 29, 289, 482], [307, 79, 374, 299], [195, 34, 399, 482]]
Chk 7578 [[141, 144, 371, 437], [333, 253, 429, 474], [39, 52, 95, 233]]
Chk 7580 [[0, 155, 255, 581], [96, 58, 249, 214], [335, 7, 606, 279], [269, 0, 571, 186]]
Chk 7581 [[253, 69, 546, 465], [118, 5, 321, 292]]
Chk 7582 [[272, 121, 437, 473], [44, 181, 239, 476]]
Chk 7584 [[277, 71, 363, 287], [441, 104, 503, 294], [280, 52, 449, 317], [190, 50, 300, 256], [4, 83, 97, 278], [578, 103, 632, 251], [68, 82, 153, 267], [147, 100, 202, 237]]
Chk 7586 [[34, 73, 377, 538], [315, 82, 607, 538]]
Chk 7587 [[201, 35, 306, 340], [205, 220, 280, 387], [0, 114, 130, 364]]
Chk 7588 [[104, 275, 233, 482], [365, 123, 611, 502], [504, 154, 584, 306], [513, 229, 610, 458]]
Chk 7589 [[36, 26, 133, 341], [177, 91, 260, 278], [534, 108, 612, 324], [249, 89, 496, 260]]
Chk 7590 [[34, 148, 359, 605], [15, 17, 140, 358]]
Chk 7593 [[94, 34, 229, 328], [1, 2, 134, 171], [161, 92, 481, 473]]
Chk 7595 [[75, 48, 221, 506], [175, 62, 513, 554], [430, 84, 639, 556]]
Chk 7596 [[246, 113, 371, 494], [83, 32, 286, 536]]
Chk 7597 [[405, 134, 622, 366], [213, 154, 541, 424], [4, 395, 251, 473]]
Chk 7598 [[221, 76, 460, 303], [0, 45, 206, 394], [0, 0, 158, 316], [266, 31, 614, 291]]
Chk 7599 [[135, 162, 391, 597], [319, 13, 431, 218]]
Chk 7600 [[413, 202, 491, 427], [505, 41, 624, 192], [94, 25, 256, 400], [0, 1, 65, 427], [570, 62, 639, 420]]
Chk 7601 [[0, 53, 257, 632], [221, 11, 438, 629]]
Chk 7602 [[45, 265, 419, 496], [366, 9, 639, 489]]
Chk 7603 [[185, 59, 426, 566], [40, 61, 252, 471], [14, 47, 102, 403]]
Chk 7604 [[268, 70, 391, 579], [184, 81, 300, 552], [60, 73, 192, 556]]
Chk 7606 [[0, 34, 323, 372], [312, 73, 563, 363]]
Chk 7608 [[365, 27, 632, 423], [2, 44, 202, 320]]
Chk 7610 [[226, 106, 306, 426], [546, 123, 631, 331], [334, 107, 416, 417]]
Chk 7611 [[111, 105, 313, 284], [305, 108, 438, 265]]
Chk 7612 [[167, 150, 389, 479], [288, 207, 519, 474]]

Chk 7613 [[24, 220, 115, 329], [102, 132, 215, 367], [230, 140, 326, 374]]
Chk 7614 [[68, 105, 225, 416], [223, 109, 351, 424], [331, 67, 470, 418], [441, 17, 611, 418], [0, 125, 87, 424]]
Chk 7615 [[2, 14, 315, 476], [429, 0, 639, 165], [316, 1, 639, 473]]
Chk 7617 [[304, 33, 388, 315], [378, 141, 537, 405], [451, 145, 576, 352]]
Chk 7618 [[123, 16, 413, 599], [356, 65, 424, 193], [369, 142, 479, 427]]
Chk 7619 [[12, 1, 387, 571], [354, 64, 475, 285]]
Chk 7621 [[340, 84, 518, 347], [275, 87, 416, 306], [212, 83, 354, 311], [143, 91, 275, 303]]
Chk 7622 [[279, 103, 480, 422], [16, 83, 174, 421]]
Chk 7623 [[327, 55, 439, 429], [380, 92, 538, 472]]
Chk 7624 [[0, 0, 330, 640], [151, 29, 293, 219], [343, 0, 479, 142]]
Chk 7625 [[5, 6, 295, 455], [174, 39, 398, 455]]
Chk 7626 [[198, 10, 331, 408], [230, 21, 538, 401], [22, 59, 80, 128], [39, 121, 90, 182], [160, 59, 222, 181], [357, 59, 411, 119], [77, 69, 158, 180]]
Chk 7627 [[29, 22, 317, 423], [166, 43, 331, 425]]
Chk 7628 [[56, 376, 185, 546], [174, 140, 269, 284], [222, 278, 344, 523], [153, 326, 271, 592]]
Chk 7629 [[160, 3, 348, 420], [309, 110, 469, 423], [0, 0, 443, 422], [320, 138, 375, 245], [258, 150, 317, 220]]
Chk 7631 [[33, 16, 168, 366], [154, 8, 432, 406], [305, 70, 519, 395], [146, 78, 232, 322]]
Chk 7633 [[105, 24, 451, 639], [2, 261, 145, 630]]
Chk 7634 [[133, 150, 262, 580], [194, 185, 348, 636]]
Chk 7635 [[166, 87, 297, 401], [44, 69, 312, 474]]
Chk 7636 [[79, 21, 479, 630], [119, 317, 433, 432]]
Chk 7637 [[282, 31, 413, 398], [357, 75, 527, 405]]
Chk 7638 [[368, 115, 566, 347], [75, 52, 523, 419], [222, 133, 349, 228], [378, 162, 450, 213], [0, 137, 85, 224]]
Chk 7639 [[333, 49, 533, 255], [50, 9, 280, 471], [69, 124, 223, 312]]
Chk 7640 [[310, 226, 377, 323], [226, 130, 401, 422], [399, 238, 459, 343], [434, 197, 614, 422], [24, 127, 157, 360], [308, 122, 410, 346], [137, 89, 288, 427]]
Chk 7641 [[160, 237, 360, 624], [18, 262, 327, 625]]
Chk 7642 [[71, 155, 412, 522], [306, 12, 639, 523]]
Chk 7643 [[95, 132, 224, 473], [258, 125, 361, 480], [339, 147, 441, 480], [170, 222, 262, 452]]
Chk 7644 [[5, 81, 225, 299], [149, 152, 300, 311], [345, 96, 488, 325]]
Chk 7645 [[88, 114, 240, 451], [335, 174, 411, 357], [245, 203, 404, 429], [188, 176, 342, 468], [17, 139, 283, 628]]
Chk 7646 [[200, 123, 376, 349], [453, 246, 522, 364], [556, 193, 639, 419], [460, 198, 515, 296], [518, 179, 582, 290], [424, 296, 558, 424]]
Chk 7649 [[401, 104, 561, 235], [131, 26, 353, 445], [94, 93, 173, 472]]
Chk 7650 [[64, 32, 341, 442], [323, 56, 431, 347], [550, 0, 639, 342]]
Chk 7651 [[0, 137, 350, 479], [215, 49, 639, 479]]
Chk 7653 [[61, 16, 220, 309], [41, 52, 94, 187], [285, 55, 336, 181], [408, 25, 627, 456]]
Chk 7655 [[108, 39, 337, 470], [312, 23, 611, 479]]
Chk 7656 [[233, 116, 315, 278], [0, 315, 170, 499], [0, 62, 253, 499]]
Chk 7657 [[31, 76, 400, 427], [20, 50, 121, 293], [291, 12, 403, 348], [367, 106, 435, 305], [7, 94, 96, 351], [83, 70, 168, 231], [186, 66, 241, 130], [0, 78, 59, 422]]
Chk 7659 [[61, 60, 228, 549], [224, 41, 402, 496], [388, 39, 575, 529]]
Chk 7660 [[211, 141, 350, 418], [284, 155, 355, 282], [464, 187, 607, 624], [75, 265, 139, 435]]
Chk 7663 [[253, 59, 399, 418], [43, 101, 128, 375], [358, 91, 428, 284], [221, 120, 305, 334], [409, 99, 473, 248]]
Chk 7664 [[24, 88, 206, 423], [233, 68, 428, 298], [395, 48, 485, 281], [519, 81, 623, 282], [3, 106, 89, 244]]
Chk 7666 [[270, 64, 431, 248], [205, 49, 318, 174], [372, 61, 444, 214], [53, 1, 265, 300], [487, 168, 639, 321], [486, 62, 543, 114], [179, 74, 256, 143], [578, 80, 634, 137]]
Chk 7667 [[0, 88, 299, 431], [0, 77, 135, 437], [355, 0, 480, 282], [248, 130, 494, 431]]
Chk 7670 [[223, 164, 478, 628], [86, 397, 175, 517], [404, 395, 482, 541], [552, 315, 638, 488], [318, 153, 476, 624]]
Chk 7671 [[66, 135, 346, 479], [345, 0, 601, 478], [483, 58, 639, 254], [26, 280, 95, 371]]
Chk 7674 [[131, 2, 303, 325], [262, 12, 622, 456], [299, 25, 393, 209]]
Chk 7675 [[2, 7, 233, 420], [366, 205, 433, 413], [379, 67, 564, 418], [293, 209, 365, 390], [231, 19, 638, 422]]
Chk 7677 [[108, 166, 240, 352], [475, 148, 620, 471], [276, 165, 417, 391], [338, 112, 398, 220], [429, 163, 490, 274]]
Chk 7678 [[178, 150, 348, 370], [346, 34, 499, 369], [0, 46, 179, 369]]
Chk 7681 [[241, 220, 423, 466], [0, 137, 302, 451], [0, 182, 64, 342], [539, 272, 639, 472], [520, 167, 588, 381]]
Chk 7682 [[217, 54, 423, 385], [461, 148, 639, 385], [34, 109, 126, 232], [376, 105, 448, 252], [523, 98, 585, 190], [411, 27, 550, 261]]
Chk 7683 [[310, 89, 480, 296], [401, 91, 638, 472], [0, 141, 240, 474]]
Chk 7686 [[511, 145, 639, 425], [147, 171, 268, 353], [256, 183, 309, 303], [378, 155, 476, 413], [478, 195, 609, 426], [53, 193, 167, 376]]
Chk 7687 [[153, 51, 445, 260], [38, 172, 466, 426]]
Chk 7689 [[356, 45, 614, 377], [24, 64, 233, 358]]
Chk 7690 [[124, 187, 639, 452], [361, 94, 496, 290]]
Chk 7692 [[246, 63, 455, 360], [0, 93, 207, 427]]
Chk 7693 [[134, 158, 297, 413], [83, 179, 182, 404], [400, 153, 540, 431], [281, 171, 419, 422]]
Chk 7695 [[231, 117, 390, 419], [363, 130, 468, 423]]
Chk 7698 [[473, 81, 601, 420], [451, 163, 503, 388], [247, 99, 406, 436], [558, 180, 610, 401]]
Chk 7699 [[257, 208, 458, 430], [440, 351, 528, 444], [130, 48, 413, 463], [62, 198, 260, 489]]
Chk 7701 [[0, 25, 403, 474], [332, 122, 571, 479]]
Chk 7704 [[269, 96, 407, 473], [464, 83, 601, 460], [182, 106, 270, 401], [90, 80, 208, 423]]
Chk 7706 [[193, 193, 297, 462], [296, 203, 437, 479], [72, 265, 177, 473], [0, 222, 122, 479], [175, 119, 247, 267], [508, 186, 630, 444], [26, 122, 86, 256], [114, 145, 170, 256]]
Chk 7708 [[126, 41, 290, 367], [425, 138, 599, 381], [577, 68, 639, 413]]
Chk 7709 [[24, 16, 177, 321], [125, 130, 421, 593]]
Chk 7710 [[3, 0, 156, 204], [145, 0, 204, 207], [263, 79, 436, 298], [446, 189, 639, 390], [18, 108, 144, 248]]
Chk 7711 [[66, 199, 379, 619], [0, 13, 385, 489]]
Chk 7712 [[16, 10, 312, 527], [519, 120, 620, 441], [0, 130, 118, 428]]
Chk 7713 [[203, 66, 326, 347], [307, 35, 426, 364], [388, 29, 547, 369], [16, 78, 117, 356], [140, 87, 199, 193], [1, 137, 59, 258]]
Chk 7714 [[59, 1, 331, 369], [44, 120, 246, 305]]
Chk 7716 [[320, 2, 627, 274], [0, 0, 236, 258]]
Chk 7717 [[75, 183, 222, 396], [397, 28, 598, 427]]
Chk 7718 [[28, 82, 243, 598], [315, 178, 406, 454], [0, 358, 166, 434], [0, 256, 55, 631]]
Chk 7719 [[98, 0, 391, 365], [115, 178, 330, 368]]
Chk 7720 [[231, 27, 358, 220], [246, 20, 499, 374], [260, 36, 468, 292], [0, 79, 252, 354]]
Chk 7721 [[0, 0, 322, 421], [92, 3, 622, 422]]
Chk 7722 [[17, 81, 224, 369], [250, 16, 499, 368], [329, 124, 416, 368], [183, 258, 283, 374]]
Chk 7723 [[0, 268, 147, 631], [162, 115, 402, 631], [189, 253, 313, 639]]
Chk 7724 [[7, 171, 273, 363], [0, 47, 136, 343], [417, 26, 622, 375], [568, 2, 639, 322]]
Chk 7725 [[74, 300, 255, 639], [176, 239, 351, 639], [256, 209, 406, 639], [447, 307, 598, 632], [37, 239, 294, 610], [291, 147, 427, 339], [365, 307, 476, 597]]
Chk 7726 [[51, 107, 330, 483], [1, 262, 155, 489], [187, 1, 499, 415]]
Chk 7727 [[259, 125, 633, 471], [1, 86, 229, 473]]
Chk 7728 [[109, 0, 213, 294], [231, 3, 288, 286], [257, 5, 368, 304], [391, 5, 496, 294]]
Chk 7729 [[4, 256, 222, 420], [221, 118, 347, 401]]
Chk 7731 [[61, 0, 412, 458], [261, 146, 563, 413]]
Chk 7732 [[0, 2, 438, 631], [335, 279, 479, 627]]
Chk 7733 [[205, 186, 340, 492], [112, 183, 239, 489]]
Chk 7734 [[461, 39, 639, 380], [9, 7, 494, 435]]
Chk 7735 [[97, 193, 321, 352], [26, 148, 144, 344], [354, 119, 550, 336], [289, 112, 350, 201], [14, 0, 72, 131], [76, 0, 128, 54]]
Chk 7736 [[322, 51, 491, 455], [314, 37, 639, 456]]
Chk 7737 [[63, 219, 281, 528], [216, 204, 379, 522], [353, 24, 577, 495], [403, 409, 540, 522]]
Chk 7738 [[247, 93, 415, 505], [180, 131, 263, 336], [41, 145, 123, 445]]
Chk 7739 [[100, 75, 257, 408], [529, 67, 630, 414], [0, 79, 113, 414]]
Chk 7740 [[240, 204, 378, 479], [333, 192, 418, 423], [465, 216, 550, 474], [84, 191, 193, 451], [152, 146, 212, 326], [84, 101, 146, 236]]
Chk 7741 [[319, 19, 569, 424], [181, 108, 309, 421], [339, 120, 393, 228]]
Chk 7743 [[151, 63, 305, 471], [0, 68, 165, 479], [287, 54, 454, 474], [437, 45, 622, 479]]
Chk 7744 [[281, 231, 464, 421], [270, 40, 404, 263], [550, 70, 639, 420]]

Chk 7747 [[316, 112, 521, 419], [75, 110, 330, 420], [541, 148, 630, 284]]
Chk 7748 [[61, 53, 373, 420], [327, 113, 619, 408]]
Chk 7749 [[201, 3, 479, 639], [64, 306, 208, 502], [194, 331, 266, 449], [145, 297, 479, 591], [0, 294, 115, 578]]
Chk 7750 [[305, 112, 423, 369], [422, 120, 605, 421], [53, 79, 187, 409], [151, 184, 282, 386], [190, 72, 294, 384], [2, 158, 59, 278]]
Chk 7751 [[68, 28, 327, 448], [318, 179, 479, 565]]
Chk 7752 [[0, 352, 343, 495], [0, 126, 368, 288]]
Chk 7753 [[281, 184, 400, 428], [0, 118, 170, 444], [413, 204, 567, 425]]
Chk 7754 [[116, 57, 263, 378], [263, 56, 397, 361], [426, 63, 578, 391]]
Chk 7757 [[411, 175, 608, 447], [175, 148, 343, 434], [333, 135, 491, 398]]
Chk 7758 [[248, 137, 400, 479], [516, 131, 628, 471], [400, 148, 529, 479], [120, 96, 266, 474], [4, 154, 135, 479]]
Chk 7759 [[185, 162, 255, 400], [119, 178, 179, 259], [109, 209, 226, 438], [51, 132, 127, 408]]
Chk 7760 [[87, 91, 309, 341], [333, 181, 485, 364], [451, 115, 589, 284]]
Chk 7761 [[234, 1, 639, 474], [2, 88, 308, 474]]
Chk 7762 [[275, 59, 412, 479], [92, 3, 258, 351]]
Chk 7764 [[148, 199, 280, 619], [322, 289, 473, 570]]
Chk 7765 [[213, 91, 439, 473], [3, 116, 203, 473]]
Chk 7767 [[111, 69, 315, 399], [63, 118, 190, 379], [581, 320, 633, 387]]
Chk 7768 [[288, 110, 437, 367], [56, 32, 270, 374]]
Chk 7770 [[62, 84, 159, 330], [121, 107, 241, 334], [242, 128, 332, 211], [343, 81, 442, 330]]
Chk 7771 [[178, 179, 303, 340], [237, 73, 341, 217], [57, 119, 216, 365]]
Chk 7772 [[170, 199, 262, 444], [387, 108, 593, 593], [21, 244, 187, 467]]
Chk 7773 [[18, 18, 248, 322], [330, 136, 621, 283]]
Chk 7774 [[215, 97, 405, 639], [9, 67, 182, 578]]
Chk 7775 [[175, 0, 638, 474], [14, 44, 301, 478], [156, 1, 228, 222]]
Chk 7776 [[61, 93, 335, 639], [191, 284, 380, 639], [314, 85, 479, 639]]
Chk 7777 [[80, 129, 220, 527], [249, 178, 423, 561], [14, 199, 67, 348]]
Chk 7778 [[146, 147, 276, 401], [256, 247, 314, 372], [352, 137, 436, 300], [432, 138, 536, 378]]
Chk 7779 [[93, 80, 478, 521], [17, 342, 94, 408], [1, 161, 257, 468]]
Chk 7781 [[184, 54, 385, 630], [34, 42, 257, 639]]
Chk 7782 [[92, 115, 229, 458], [0, 43, 108, 356]]
Chk 7784 [[450, 63, 551, 350], [307, 18, 392, 245], [233, 54, 298, 180], [62, 55, 463, 370], [157, 181, 327, 367], [172, 49, 250, 194]]
Chk 7785 [[239, 3, 450, 391], [438, 23, 625, 428], [0, 70, 395, 505]]
Chk 7786 [[0, 28, 319, 428], [301, 184, 536, 415]]
Chk 7787 [[132, 38, 244, 322], [247, 216, 339, 381], [387, 66, 490, 352]]
Chk 7788 [[184, 210, 271, 330], [73, 262, 371, 566], [305, 241, 513, 566]]
Chk 7789 [[268, 19, 481, 320], [269, 27, 323, 265], [0, 129, 158, 329]]
Chk 7791 [[73, 15, 262, 375], [311, 241, 547, 421], [249, 48, 405, 306]]
Chk 7792 [[257, 129, 401, 361], [162, 236, 283, 414], [51, 199, 194, 408]]
Chk 7793 [[164, 125, 345, 479], [331, 163, 477, 472]]
Chk 7794 [[81, 223, 142, 426], [140, 211, 254, 425], [1, 212, 229, 420]]
Chk 7796 [[193, 128, 304, 370], [558, 208, 639, 361], [252, 215, 377, 346], [0, 124, 200, 416]]
Chk 7798 [[185, 88, 608, 424], [5, 13, 256, 419]]
Chk 7799 [[310, 227, 455, 619], [421, 203, 478, 458], [137, 78, 326, 397], [0, 245, 52, 441]]
Chk 7800 [[183, 143, 283, 285], [275, 145, 343, 478], [172, 213, 304, 469], [371, 190, 540, 473], [322, 173, 398, 472], [98, 124, 214, 402]]
Chk 7801 [[553, 213, 639, 479], [9, 148, 140, 470]]
Chk 7802 [[61, 87, 246, 314], [235, 84, 434, 304]]
Chk 7803 [[388, 123, 494, 310], [20, 103, 114, 328], [80, 91, 208, 399], [236, 167, 291, 270], [4, 168, 58, 270], [169, 128, 278, 321], [547, 174, 598, 267]]
Chk 7804 [[143, 151, 310, 478], [364, 41, 607, 479], [107, 224, 193, 479], [274, 302, 345, 478], [336, 410, 426, 479], [575, 384, 639, 479]]
Chk 7805 [[114, 0, 314, 342], [258, 1, 527, 404], [367, 0, 432, 72], [0, 3, 386, 472]]
Chk 7807 [[410, 153, 538, 474], [218, 100, 308, 232], [497, 138, 564, 279], [246, 171, 384, 479], [41, 148, 285, 478]]
Chk 7808 [[108, 78, 414, 419], [1, 0, 348, 352], [58, 48, 190, 274], [284, 47, 361, 218]]
Chk 7809 [[494, 60, 556, 172], [527, 128, 598, 249], [416, 71, 599, 399], [482, 100, 535, 179], [311, 124, 488, 394], [227, 62, 354, 395], [47, 55, 237, 395], [54, 111, 118, 169]]
Chk 7810 [[217, 253, 293, 462], [377, 250, 451, 474], [306, 246, 379, 472]]
Chk 7811 [[205, 80, 293, 352], [271, 21, 394, 369], [97, 67, 235, 406], [97, 182, 209, 450]]
Chk 7812 [[0, 34, 340, 388], [295, 6, 627, 384]]
Chk 7813 [[449, 51, 577, 260], [228, 239, 430, 402]]
Chk 7815 [[237, 299, 509, 487], [81, 204, 223, 485], [200, 178, 323, 475], [128, 94, 183, 251], [237, 98, 305, 239]]
Chk 7816 [[271, 63, 401, 516], [19, 159, 169, 516], [311, 313, 449, 522], [475, 38, 639, 498]]
Chk 7817 [[298, 91, 462, 452], [185, 14, 276, 124], [18, 33, 97, 131], [455, 85, 577, 446], [0, 16, 120, 124], [228, 31, 350, 336], [320, 0, 385, 102]]
Chk 7818 [[165, 65, 299, 328], [55, 64, 173, 572], [343, 136, 400, 323]]
Chk 7819 [[180, 74, 410, 631], [24, 74, 177, 622]]
Chk 7820 [[24, 151, 125, 263], [145, 154, 284, 421], [248, 138, 389, 406], [380, 61, 484, 411], [478, 146, 623, 422], [460, 73, 583, 381]]
Chk 7822 [[269, 64, 471, 332], [242, 26, 415, 311], [1, 0, 265, 406], [524, 162, 592, 227], [8, 99, 62, 263]]
Chk 7823 [[312, 128, 632, 473], [4, 2, 399, 473]]
Chk 7824 [[185, 126, 364, 629], [1, 131, 188, 633]]
Chk 7827 [[218, 9, 405, 306], [167, 1, 280, 305], [128, 14, 206, 141]]
Chk 7828 [[346, 76, 479, 364], [137, 131, 308, 342], [103, 124, 161, 239], [267, 137, 331, 325], [63, 111, 122, 216]]
Chk 7829 [[469, 213, 602, 422], [476, 225, 531, 342], [1, 0, 271, 428], [226, 121, 452, 427]]
Chk 7830 [[352, 106, 541, 443], [3, 200, 217, 444]]
Chk 7833 [[137, 74, 294, 416], [436, 0, 553, 267]]
Chk 7835 [[381, 43, 532, 622], [503, 197, 576, 425], [210, 155, 306, 403], [135, 144, 227, 405], [67, 198, 132, 374], [525, 202, 577, 426]]
Chk 7836 [[143, 9, 585, 421], [49, 5, 356, 419]]
Chk 7837 [[119, 34, 375, 426], [349, 93, 421, 266], [355, 5, 479, 391], [224, 0, 366, 191]]
Chk 7838 [[238, 190, 375, 472], [426, 134, 588, 473]]
Chk 7839 [[144, 171, 477, 629], [0, 158, 195, 629], [195, 285, 395, 633]]
Chk 7840 [[106, 94, 324, 426], [304, 188, 497, 421]]
Chk 7842 [[1, 95, 417, 544], [287, 57, 639, 552]]
Chk 7843 [[156, 46, 372, 316], [297, 45, 483, 263], [434, 3, 586, 138], [416, 51, 639, 475], [0, 5, 193, 372]]
Chk 7846 [[52, 207, 232, 485], [206, 75, 315, 331], [449, 237, 594, 480]]
Chk 7847 [[110, 0, 306, 351], [35, 171, 165, 313], [578, 259, 639, 425], [230, 129, 545, 398], [0, 346, 106, 401]]
Chk 7848 [[96, 19, 258, 337], [183, 132, 449, 430], [538, 87, 638, 431], [405, 75, 467, 238], [323, 66, 422, 222], [505, 70, 639, 431], [473, 54, 599, 266]]
Chk 7849 [[62, 94, 173, 421], [0, 164, 68, 287], [387, 66, 625, 423], [172, 128, 242, 274], [254, 151, 418, 411]]
Chk 7850 [[275, 10, 639, 472], [222, 1, 433, 338]]
Chk 7853 [[4, 138, 360, 578], [0, 121, 305, 416], [215, 162, 296, 373]]
Chk 7854 [[94, 96, 237, 366], [428, 75, 499, 185], [288, 84, 489, 367]]
Chk 7857 [[126, 137, 314, 489], [282, 149, 419, 489], [395, 127, 554, 478]]
Chk 7858 [[77, 175, 234, 479], [224, 168, 552, 474]]
Chk 7859 [[105, 61, 338, 334], [136, 31, 233, 329]]
Chk 7860 [[505, 159, 639, 478], [2, 159, 182, 473], [218, 145, 428, 456]]
Chk 7861 [[68, 51, 249, 302], [305, 109, 639, 369]]
Chk 7862 [[0, 209, 425, 631], [0, 1, 425, 459]]
Chk 7864 [[110, 172, 372, 478], [207, 52, 601, 473]]
Chk 7865 [[261, 1, 387, 275], [112, 1, 206, 258], [141, 3, 295, 378]]
Chk 7867 [[51, 21, 331, 365], [243, 73, 390, 349], [357, 95, 551, 355], [557, 224, 625, 359]]
Chk 7868 [[224, 118, 342, 425], [245, 108, 300, 182], [34, 129, 123, 369], [377, 112, 491, 424], [516, 86, 621, 425]]
Chk 7869 [[300, 11, 473, 353], [99, 9, 307, 355]]
Chk 7870 [[80, 27, 562, 473], [56, 36, 198, 446]]
Chk 7871 [[292, 22, 570, 374], [91, 147, 335, 382]]
Chk 7872 [[544, 161, 639, 286], [321, 0, 496, 223], [146, 45, 325, 321], [1, 1, 154, 277]]
Chk 7873 [[110, 110, 299, 625], [48, 16, 196, 198], [157, 0, 253, 161], [0, 27, 162, 272]]
Chk 7874 [[350, 155, 539, 419], [89, 120, 261, 407], [184, 62, 273, 278], [274, 184, 347, 294]]
Chk 7875 [[23, 151, 165, 509], [239, 160, 378, 493], [420, 153, 538, 498]]
Chk 7878 [[187, 55, 499, 323], [112, 38, 284, 290], [2, 1, 63, 84], [383, 107, 499, 326]]
Chk 7879 [[70, 202, 314, 627], [0, 62, 351, 629]]
Chk 7881 [[93, 15, 331, 499], [65, 94, 195, 499]]
Chk 7882 [[121, 166, 276, 441], [18, 89, 177, 413], [339, 48, 505, 414], [1, 1, 86, 88], [363, 0, 450, 65], [189, 0, 264, 63]]
Chk 7883 [[113, 132, 298, 454], [542, 190, 639, 477]]
Chk 7885 [[0, 0, 265, 479], [175, 1, 390, 262], [364, 0, 532, 135], [508, 359, 639, 459]]
Chk 7886 [[116, 185, 308, 464], [44, 192, 264, 479], [1, 127, 124, 546]]

Chk 7887 [[2, 84, 157, 420], [148, 88, 274, 419], [230, 91, 301, 207], [417, 77, 573, 425], [531, 49, 639, 419]]
Chk 7888 [[177, 228, 292, 546], [305, 127, 389, 317], [324, 248, 437, 557], [386, 120, 509, 419], [243, 243, 373, 548]]
Chk 7889 [[0, 117, 316, 639], [188, 238, 449, 639]]
Chk 7891 [[273, 127, 517, 480], [313, 157, 639, 472]]
Chk 7892 [[428, 96, 639, 423], [140, 15, 401, 376]]
Chk 7894 [[264, 219, 328, 341], [360, 120, 558, 395], [544, 211, 639, 391], [0, 228, 69, 342], [482, 102, 550, 164]]
Chk 7895 [[65, 29, 267, 474], [353, 66, 628, 471], [127, 250, 229, 388]]
Chk 7897 [[161, 84, 322, 381], [440, 173, 601, 384], [584, 105, 639, 418]]
Chk 7898 [[154, 100, 277, 429], [178, 142, 502, 479], [402, 229, 540, 386], [526, 202, 637, 371], [122, 220, 227, 389], [182, 230, 297, 373]]
Chk 7899 [[54, 86, 190, 592], [163, 98, 311, 555], [306, 110, 442, 629]]
Chk 7900 [[363, 97, 637, 479], [76, 67, 147, 138], [541, 54, 639, 236], [224, 94, 365, 268], [6, 129, 220, 461]]
Chk 7901 [[1, 28, 369, 515], [202, 50, 573, 510]]
Chk 7902 [[388, 225, 534, 424], [281, 125, 413, 473], [225, 182, 302, 479]]
Chk 7903 [[266, 132, 409, 350], [43, 128, 94, 228], [299, 20, 435, 326]]
Chk 7904 [[366, 103, 495, 474], [111, 57, 278, 479]]
Chk 7905 [[172, 86, 275, 379], [451, 58, 551, 384], [510, 0, 639, 476], [366, 63, 465, 353]]
Chk 7907 [[224, 348, 501, 602], [119, 13, 406, 371]]
Chk 7908 [[309, 89, 422, 390], [515, 98, 626, 379], [38, 118, 152, 363], [200, 90, 281, 379], [84, 92, 266, 393]]
Chk 7910 [[76, 258, 142, 417], [102, 252, 220, 472], [458, 258, 568, 614], [311, 245, 416, 584], [272, 272, 343, 559], [215, 283, 266, 426]]
Chk 7911 [[104, 0, 284, 270], [118, 120, 331, 333], [252, 235, 390, 333]]
Chk 7912 [[86, 124, 286, 411], [425, 132, 639, 424]]
Chk 7913 [[86, 162, 259, 441], [115, 71, 214, 239], [223, 127, 291, 367], [292, 118, 370, 380], [333, 150, 475, 426]]
Chk 7914 [[76, 93, 163, 356], [74, 62, 266, 417], [263, 107, 351, 366], [446, 75, 570, 418]]
Chk 7915 [[0, 64, 290, 473], [293, 137, 395, 407], [353, 234, 511, 442], [570, 119, 639, 440]]
Chk 7916 [[140, 43, 345, 419], [419, 56, 622, 426], [12, 21, 150, 426]]
Chk 7919 [[248, 175, 400, 472], [120, 28, 288, 479]]
Chk 7920 [[134, 7, 298, 189], [383, 41, 580, 352], [51, 0, 103, 104]]
Chk 7921 [[94, 92, 250, 378], [2, 235, 173, 632]]
Chk 7922 [[272, 295, 363, 631], [143, 345, 271, 639]]
Chk 7923 [[373, 19, 471, 339], [502, 23, 594, 340]]
Chk 7926 [[44, 35, 296, 473], [332, 67, 472, 476]]
Chk 7927 [[231, 97, 426, 632], [0, 118, 234, 639]]
Chk 7929 [[167, 54, 358, 421], [0, 267, 203, 419], [399, 193, 488, 426]]
Chk 7931 [[189, 306, 453, 474], [492, 84, 639, 464], [65, 98, 317, 479]]
Chk 7932 [[229, 78, 320, 199], [2, 75, 194, 353], [375, 46, 559, 280], [305, 82, 364, 195], [537, 99, 599, 166]]
Chk 7934 [[45, 55, 244, 416], [201, 117, 303, 217], [442, 63, 573, 319]]
Chk 7936 [[1, 25, 217, 328], [345, 2, 639, 437]]
Chk 7938 [[71, 149, 352, 542], [1, 217, 236, 631], [21, 0, 251, 256], [369, 159, 479, 632], [0, 457, 61, 606]]
Chk 7939 [[235, 278, 389, 552], [245, 214, 372, 335], [153, 192, 239, 297], [133, 190, 188, 286], [1, 211, 144, 551]]
Chk 7940 [[54, 132, 219, 387], [172, 114, 274, 354], [369, 119, 532, 378], [338, 80, 393, 210], [40, 70, 103, 223], [262, 129, 368, 363], [2, 33, 56, 299]]
Chk 7942 [[281, 35, 434, 184], [522, 1, 639, 270]]
Chk 7943 [[180, 80, 427, 623], [14, 84, 426, 506]]
Chk 7944 [[572, 141, 635, 222], [366, 118, 433, 234], [401, 114, 590, 238], [39, 71, 229, 413], [26, 1, 148, 389], [193, 92, 358, 378], [150, 105, 241, 254]]
Chk 7945 [[192, 235, 329, 378], [9, 189, 205, 378], [380, 161, 547, 385], [560, 41, 613, 95], [338, 30, 394, 100]]
Chk 7947 [[482, 97, 639, 461], [137, 154, 251, 279], [30, 136, 248, 368], [2, 10, 231, 479]]
Chk 7949 [[2, 175, 332, 629], [144, 99, 422, 533]]
Chk 7950 [[268, 78, 389, 359], [122, 108, 299, 452]]
Chk 7953 [[346, 123, 551, 347], [450, 105, 598, 326], [102, 63, 212, 232], [0, 62, 306, 393]]
Chk 7956 [[188, 166, 349, 454], [0, 90, 201, 469]]
Chk 7958 [[118, 221, 356, 401], [36, 0, 198, 434]]
Chk 7959 [[151, 151, 287, 442], [181, 52, 423, 591]]
Chk 7960 [[310, 140, 499, 332], [269, 68, 462, 328], [154, 38, 325, 328], [6, 50, 176, 328]]
Chk 7961 [[132, 91, 347, 338], [335, 2, 499, 353]]
Chk 7963 [[196, 310, 297, 582], [292, 313, 386, 581], [392, 276, 502, 581], [0, 296, 89, 565], [90, 303, 200, 569]]
Chk 7964 [[205, 123, 418, 402], [1, 13, 293, 632], [400, 97, 479, 392], [297, 97, 383, 181], [219, 78, 327, 245], [391, 105, 447, 211]]
Chk 7966 [[239, 92, 469, 272], [426, 2, 639, 419], [68, 0, 328, 304]]
Chk 7967 [[263, 170, 392, 376], [159, 70, 328, 368]]
Chk 7968 [[75, 86, 437, 374], [13, 80, 238, 369]]
Chk 7970 [[146, 104, 355, 473], [302, 2, 639, 474], [587, 95, 639, 475]]
Chk 7971 [[190, 18, 329, 390], [463, 177, 637, 405], [27, 0, 180, 415]]
Chk 7973 [[236, 66, 511, 634], [228, 50, 401, 339], [122, 143, 276, 481], [2, 116, 262, 524]]
Chk 7974 [[345, 71, 459, 475], [221, 52, 361, 480]]
Chk 7975 [[104, 120, 303, 520], [123, 112, 348, 610]]
Chk 7977 [[16, 25, 536, 359], [213, 56, 556, 323]]
Chk 7978 [[169, 131, 396, 393], [396, 101, 587, 400]]
Chk 7979 [[165, 225, 333, 441], [296, 79, 386, 425], [94, 92, 211, 419], [206, 87, 301, 266]]
Chk 7981 [[245, 122, 426, 637], [0, 27, 247, 639]]
Chk 7982 [[61, 200, 314, 438], [298, 102, 398, 223], [1, 155, 83, 332], [125, 88, 214, 181], [516, 136, 639, 302], [401, 103, 506, 250], [202, 88, 284, 195]]
Chk 7983 [[181, 78, 296, 258], [336, 134, 399, 198], [565, 136, 639, 456], [273, 87, 356, 321], [334, 85, 507, 416]]
Chk 7986 [[404, 101, 591, 424], [16, 125, 169, 418], [169, 106, 391, 458]]
Chk 7987 [[113, 273, 296, 423], [193, 179, 254, 276], [298, 212, 350, 273], [337, 222, 526, 428], [102, 47, 165, 101], [474, 170, 525, 252], [36, 228, 142, 428]]
Chk 7988 [[134, 25, 386, 420], [518, 97, 601, 370]]
Chk 7991 [[1, 121, 277, 491], [212, 107, 480, 493], [442, 71, 639, 490]]
Chk 7992 [[98, 313, 498, 438], [9, 93, 375, 473], [218, 116, 538, 365]]
Chk 7993 [[268, 134, 351, 339], [505, 326, 639, 479], [456, 158, 639, 396], [316, 172, 416, 360], [416, 251, 478, 328]]
Chk 7995 [[244, 117, 422, 377], [144, 231, 297, 420], [11, 167, 154, 421]]
Chk 7996 [[304, 57, 564, 421], [40, 97, 283, 421]]
Chk 8000 [[245, 159, 610, 425], [0, 80, 279, 419]]
Chk 8001 [[118, 85, 290, 422], [346, 15, 522, 423]]
Chk 8002 [[38, 47, 289, 563], [313, 131, 639, 562], [463, 6, 639, 346]]
Chk 8004 [[19, 118, 124, 421], [247, 122, 352, 348], [469, 149, 617, 418]]
Chk 8005 [[335, 119, 507, 473], [464, 113, 604, 447]]
Chk 8007 [[71, 153, 309, 532], [297, 138, 521, 365], [516, 217, 592, 370], [584, 251, 639, 369], [209, 93, 274, 257], [29, 197, 114, 340], [260, 122, 394, 339]]
Chk 8008 [[28, 67, 384, 424], [354, 79, 639, 424]]
Chk 8009 [[158, 24, 490, 374], [441, 102, 499, 363], [0, 107, 236, 369]]
Chk 8010 [[223, 220, 400, 628], [53, 168, 219, 508]]
Chk 8011 [[21, 9, 197, 559], [122, 24, 301, 364], [397, 111, 477, 271]]
Chk 8012 [[48, 106, 323, 477], [269, 22, 629, 473], [12, 219, 64, 394]]
Chk 8013 [[318, 4, 478, 347], [480, 130, 632, 479], [312, 246, 572, 479], [164, 76, 295, 337], [284, 64, 341, 190]]
Chk 8014 [[226, 129, 467, 418], [173, 18, 589, 420], [10, 61, 207, 419]]
Chk 8015 [[176, 31, 272, 304], [486, 20, 639, 335], [330, 71, 478, 321]]
Chk 8016 [[195, 91, 318, 443], [29, 206, 165, 371], [471, 212, 612, 441], [317, 44, 532, 471]]
Chk 8018 [[338, 15, 639, 423], [245, 88, 426, 421], [32, 88, 288, 428]]
Chk 8019 [[125, 31, 562, 419], [400, 1, 607, 420]]
Chk 8020 [[0, 314, 352, 617], [183, 0, 362, 254], [76, 223, 320, 419]]
Chk 8021 [[138, 141, 258, 487], [297, 102, 442, 500]]
Chk 8023 [[410, 39, 550, 436], [272, 49, 369, 215], [347, 63, 514, 492], [2, 103, 152, 287], [120, 146, 341, 490], [1, 210, 145, 456]]
Chk 8024 [[340, 78, 515, 451], [149, 27, 267, 209], [327, 29, 459, 198], [578, 5, 639, 183], [6, 170, 245, 461], [1, 104, 70, 218]]
Chk 8025 [[93, 41, 269, 324], [262, 38, 485, 328], [68, 0, 125, 149]]
Chk 8027 [[74, 46, 323, 399], [327, 78, 452, 347]]
Chk 8028 [[136, 147, 309, 470], [0, 188, 545, 453], [47, 327, 99, 395]]
Chk 8030 [[428, 100, 638, 378], [382, 57, 562, 251], [426, 39, 505, 163], [85, 39, 186, 198], [280, 43, 348, 141], [0, 16, 71, 105], [225, 33, 326, 192], [106, 108, 279, 369]]

Chk 8031 [[165, 168, 343, 629], [337, 175, 478, 476], [0, 86, 254, 639]]
Chk 8033 [[204, 104, 496, 309], [2, 144, 224, 340]]
Chk 8034 [[96, 127, 399, 567], [0, 316, 227, 635]]
Chk 8035 [[149, 175, 339, 419], [393, 212, 490, 423]]
Chk 8036 [[337, 139, 440, 439], [61, 84, 331, 614]]
Chk 8037 [[169, 69, 314, 461], [19, 30, 143, 487]]
Chk 8038 [[146, 103, 319, 395], [159, 164, 427, 395]]
Chk 8039 [[276, 163, 439, 576], [18, 106, 296, 563]]
Chk 8041 [[1, 146, 347, 531], [192, 216, 329, 459]]
Chk 8042 [[264, 35, 509, 464], [68, 38, 370, 462]]
Chk 8043 [[3, 3, 405, 473], [338, 0, 509, 279], [122, 2, 336, 303], [1, 0, 139, 261]]
Chk 8044 [[71, 133, 351, 555], [276, 86, 424, 574]]
Chk 8045 [[121, 2, 296, 267], [353, 5, 530, 279]]
Chk 8047 [[132, 127, 295, 497], [383, 95, 533, 483], [279, 129, 420, 478], [89, 275, 160, 501], [9, 251, 64, 483], [577, 252, 634, 414], [519, 265, 625, 457], [60, 293, 122, 500]]
Chk 8048 [[133, 26, 422, 430], [103, 232, 296, 395]]
Chk 8049 [[89, 147, 248, 346], [0, 0, 228, 417], [566, 243, 639, 480], [342, 126, 615, 477]]
Chk 8050 [[264, 0, 361, 281], [183, 130, 315, 341], [26, 22, 115, 355]]
Chk 8051 [[0, 54, 263, 479], [446, 91, 597, 472], [582, 147, 639, 473], [231, 74, 364, 358]]
Chk 8052 [[386, 109, 588, 449], [1, 180, 170, 424]]
Chk 8054 [[166, 41, 416, 370], [67, 102, 268, 368], [407, 222, 472, 303]]
Chk 8058 [[347, 97, 542, 422], [180, 137, 291, 393]]
Chk 8059 [[0, 0, 261, 328], [234, 7, 481, 328]]
Chk 8060 [[32, 106, 413, 547], [226, 2, 637, 544]]
Chk 8062 [[254, 68, 614, 624], [84, 326, 307, 527]]
Chk 8063 [[33, 335, 295, 631], [222, 117, 446, 498], [0, 258, 131, 622]]
Chk 8064 [[153, 84, 346, 427], [280, 384, 397, 512], [124, 370, 296, 511]]
Chk 8066 [[101, 117, 275, 509], [374, 132, 533, 514]]
Chk 8068 [[296, 131, 561, 451], [187, 0, 545, 258], [510, 127, 639, 478], [0, 206, 157, 348]]
Chk 8069 [[138, 113, 247, 394], [1, 89, 217, 419], [377, 98, 580, 288], [289, 171, 409, 399], [360, 220, 487, 373]]
Chk 8070 [[122, 0, 415, 427], [1, 361, 639, 472], [26, 294, 154, 346]]
Chk 8071 [[409, 253, 529, 557], [80, 103, 427, 551], [263, 361, 350, 531], [479, 209, 540, 368]]
Chk 8073 [[73, 48, 243, 626], [146, 50, 426, 639]]
Chk 8074 [[221, 122, 359, 460], [10, 6, 177, 482], [281, 118, 335, 226], [196, 104, 249, 240]]
Chk 8075 [[220, 206, 639, 401], [74, 154, 302, 316]]
Chk 8076 [[320, 197, 547, 376], [105, 195, 333, 396], [0, 265, 52, 465]]
Chk 8077 [[146, 146, 319, 499], [2, 153, 156, 491]]
Chk 8078 [[308, 138, 393, 444], [497, 132, 639, 475], [480, 250, 549, 440]]
Chk 8080 [[35, 12, 179, 411], [201, 56, 387, 395], [414, 50, 637, 439], [1, 103, 60, 269], [551, 210, 639, 403]]
Chk 8081 [[255, 144, 408, 478], [368, 178, 513, 473], [215, 360, 290, 479], [45, 20, 263, 479], [520, 132, 639, 479], [16, 262, 86, 387]]
Chk 8082 [[37, 276, 208, 631], [176, 74, 396, 629]]
Chk 8083 [[139, 146, 337, 477], [325, 142, 414, 430]]
Chk 8084 [[237, 103, 415, 329], [108, 212, 270, 330], [0, 153, 97, 328]]
Chk 8085 [[166, 104, 298, 318], [186, 22, 237, 92], [0, 14, 85, 319], [372, 275, 499, 356], [396, 198, 499, 322], [295, 71, 373, 163]]
Chk 8087 [[153, 40, 344, 303], [21, 81, 126, 426], [35, 4, 107, 105]]
Chk 8088 [[433, 140, 536, 371], [132, 212, 400, 561], [449, 189, 639, 597], [2, 86, 131, 216], [244, 26, 452, 508], [0, 218, 377, 597]]
Chk 8090 [[206, 146, 366, 552], [345, 150, 500, 546], [488, 176, 630, 552]]
Chk 8093 [[71, 23, 187, 373], [303, 66, 603, 474]]
Chk 8094 [[228, 116, 302, 315], [77, 119, 154, 320], [4, 113, 226, 326], [372, 102, 581, 297]]
Chk 8095 [[163, 207, 368, 361], [343, 199, 496, 392], [475, 185, 639, 442], [1, 166, 137, 469], [297, 423, 460, 475]]
Chk 8096 [[310, 60, 478, 405], [154, 198, 310, 411]]
Chk 8097 [[305, 148, 558, 473], [19, 230, 155, 452], [354, 135, 476, 350]]
Chk 8098 [[38, 99, 260, 634], [286, 42, 440, 480]]
Chk 8099 [[13, 13, 343, 420], [354, 43, 639, 379], [0, 130, 94, 333]]
Chk 8100 [[276, 48, 424, 420], [436, 19, 595, 423], [66, 19, 231, 412], [555, 254, 639, 331]]
Chk 8101 [[409, 322, 520, 492], [33, 353, 166, 590], [506, 396, 594, 523]]
Chk 8102 [[235, 84, 537, 383], [58, 101, 275, 363], [421, 73, 622, 369], [0, 0, 81, 463], [436, 63, 639, 462]]
Chk 8105 [[166, 74, 401, 401], [0, 200, 245, 422]]
Chk 8106 [[308, 68, 442, 631], [0, 130, 305, 532], [1, 37, 208, 555], [144, 232, 369, 536]]
Chk 8107 [[149, 154, 270, 479], [136, 196, 191, 431], [35, 178, 124, 479]]
Chk 8108 [[113, 189, 250, 637], [110, 201, 338, 626]]
Chk 8109 [[108, 141, 352, 473], [331, 109, 564, 479], [478, 148, 639, 479], [101, 172, 217, 479], [0, 147, 133, 479]]
Chk 8113 [[443, 87, 626, 423], [211, 57, 478, 423], [3, 107, 255, 420]]
Chk 8115 [[321, 32, 534, 357], [1, 68, 179, 379]]
Chk 8116 [[201, 0, 628, 624], [1, 257, 505, 625]]
Chk 8117 [[161, 71, 412, 409], [1, 230, 225, 427]]
Chk 8119 [[109, 21, 375, 630], [2, 424, 354, 636], [363, 6, 415, 94]]
Chk 8120 [[144, 189, 266, 418], [257, 75, 427, 479], [15, 133, 133, 301]]
Chk 8121 [[279, 37, 584, 426], [149, 4, 337, 418]]
Chk 8122 [[10, 73, 260, 373], [304, 59, 607, 357]]
Chk 8123 [[133, 94, 305, 462], [125, 150, 278, 501]]
Chk 8124 [[296, 12, 437, 453], [55, 69, 176, 453]]
Chk 8125 [[362, 102, 639, 478], [187, 128, 348, 479], [0, 237, 121, 424]]
Chk 8126 [[39, 152, 165, 469], [394, 152, 586, 540]]
Chk 8127 [[2, 98, 224, 339], [125, 106, 342, 371], [196, 77, 375, 199], [438, 87, 618, 288], [337, 118, 468, 283]]
Chk 8128 [[332, 52, 471, 409], [267, 114, 383, 409], [455, 271, 577, 414], [0, 266, 60, 409]]
Chk 8129 [[274, 169, 459, 512], [293, 25, 500, 458], [434, 102, 611, 435], [16, 71, 268, 501]]
Chk 8130 [[160, 16, 378, 222], [5, 86, 365, 473]]
Chk 8131 [[1, 100, 252, 472], [201, 145, 411, 479], [364, 39, 639, 477]]
Chk 8132 [[297, 96, 419, 406], [162, 0, 274, 225]]
Chk 8133 [[125, 111, 424, 610], [91, 76, 301, 611]]
Chk 8135 [[321, 106, 472, 340], [213, 134, 284, 188], [184, 113, 237, 177], [65, 199, 231, 352], [543, 0, 601, 92], [16, 159, 128, 348]]
Chk 8138 [[112, 46, 263, 271], [458, 115, 632, 298], [561, 97, 618, 152], [309, 126, 484, 291]]
Chk 8139 [[369, 4, 568, 366], [226, 94, 358, 337], [3, 4, 361, 412]]
Chk 8141 [[284, 58, 559, 421], [128, 105, 317, 426]]
Chk 8143 [[172, 55, 238, 150], [237, 47, 320, 422], [313, 50, 421, 438], [374, 46, 490, 395]]
Chk 8144 [[104, 44, 214, 317], [198, 190, 368, 356], [319, 129, 370, 209], [294, 176, 458, 384], [395, 132, 472, 204], [71, 149, 158, 292]]
Chk 8145 [[279, 72, 636, 479], [17, 113, 244, 479]]
Chk 8146 [[205, 210, 392, 385], [37, 187, 264, 345]]
Chk 8147 [[97, 217, 197, 530], [319, 253, 421, 537]]
Chk 8149 [[0, 99, 256, 631], [187, 74, 426, 639], [13, 380, 68, 534]]
Chk 8151 [[96, 187, 246, 489], [0, 198, 259, 567]]
Chk 8152 [[40, 98, 271, 334], [496, 15, 639, 472], [97, 259, 275, 414]]
Chk 8155 [[426, 123, 639, 370], [478, 82, 618, 222], [159, 55, 270, 223], [478, 67, 532, 155], [68, 73, 182, 269], [0, 118, 130, 319], [0, 76, 54, 130], [173, 93, 449, 300]]
Chk 8156 [[189, 37, 324, 299], [331, 0, 551, 422], [0, 108, 70, 404]]
Chk 8157 [[346, 65, 453, 373], [255, 29, 392, 336], [582, 52, 637, 192], [307, 78, 604, 384], [167, 47, 234, 216], [232, 51, 296, 171]]
Chk 8158 [[2, 0, 157, 422], [66, 119, 272, 427], [53, 0, 151, 201]]
Chk 8159 [[168, 212, 382, 488], [424, 168, 564, 521]]
Chk 8160 [[19, 53, 562, 473], [294, 119, 638, 469]]
Chk 8164 [[130, 68, 488, 421], [262, 127, 370, 423]]
Chk 8165 [[256, 115, 595, 496], [0, 98, 267, 497]]
Chk 8166 [[231, 227, 323, 426], [438, 122, 639, 418], [286, 37, 447, 421], [105, 143, 250, 425]]
Chk 8167 [[143, 82, 442, 382], [346, 61, 525, 370], [0, 42, 218, 377]]
Chk 8168 [[118, 115, 288, 328], [313, 191, 501, 336], [464, 136, 581, 344]]
Chk 8169 [[127, 142, 364, 529], [312, 148, 394, 287], [356, 130, 560, 536]]
Chk 8172 [[165, 12, 267, 247], [119, 182, 369, 409], [417, 144, 541, 410]]
Chk 8173 [[360, 0, 634, 423], [183, 9, 488, 301]]
Chk 8174 [[308, 63, 608, 472], [248, 105, 336, 252], [54, 52, 273, 375]]
Chk 8176 [[139, 64, 474, 302], [328, 20, 517, 314], [487, 4, 600, 227], [138, 0, 248, 98], [561, 1, 621, 85]]
Chk 8177 [[307, 109, 428, 239], [172, 15, 269, 304], [37, 98, 199, 280]]
Chk 8178 [[159, 140, 335, 359], [385, 209, 559, 369], [179, 0, 233, 83], [528, 172, 638, 353]]
Chk 8179 [[130, 110, 246, 441], [223, 98, 329, 446], [387, 107, 504, 439]]
Chk 8180 [[42, 49, 293, 459], [399, 2, 608, 449]]
Chk 8183 [[450, 122, 639, 338], [50, 149, 260, 290]]
Chk 8184 [[241, 62, 460, 419], [1, 57, 295, 432]]
Chk 8186 [[34, 104, 250, 472], [275, 90, 560, 414]]

Chk 8187 [[146, 81, 340, 431], [393, 197, 639, 421], [7, 312, 229, 471], [342, 130, 520, 398]]
Chk 8188 [[280, 160, 463, 319], [464, 154, 639, 377], [4, 134, 189, 395]]
Chk 8189 [[68, 29, 350, 369], [281, 95, 394, 372], [324, 95, 411, 280], [68, 104, 140, 293]]
Chk 8190 [[101, 176, 182, 430], [400, 167, 490, 416]]
Chk 8191 [[3, 130, 107, 419], [117, 143, 245, 418], [297, 149, 373, 378], [519, 139, 610, 419], [350, 208, 537, 383], [225, 243, 315, 416], [239, 170, 362, 304], [463, 154, 531, 269]]
Chk 8192 [[129, 26, 324, 296], [312, 37, 635, 376]]
Chk 8193 [[48, 164, 216, 426], [402, 175, 485, 346], [170, 141, 278, 266], [459, 181, 582, 420]]
Chk 8194 [[32, 21, 275, 419], [159, 83, 303, 425]]
Chk 8196 [[273, 121, 452, 467], [148, 156, 296, 472]]
Chk 8197 [[337, 224, 451, 392], [484, 145, 580, 402], [185, 24, 236, 97], [445, 0, 502, 61], [82, 148, 252, 393], [257, 34, 308, 105]]
Chk 8198 [[1, 202, 256, 639], [115, 103, 388, 429]]
Chk 8199 [[193, 131, 365, 455], [58, 113, 206, 473]]
Chk 8200 [[215, 13, 343, 308], [313, 46, 426, 401]]
Chk 8201 [[71, 208, 262, 471], [215, 132, 359, 479], [328, 156, 476, 473]]
Chk 8202 [[223, 113, 343, 337], [149, 114, 226, 369]]
Chk 8205 [[280, 14, 639, 447], [224, 9, 397, 438], [148, 102, 253, 399], [16, 35, 139, 361]]
Chk 8206 [[1, 74, 87, 472], [12, 72, 248, 474], [311, 59, 547, 477], [446, 37, 639, 473]]
Chk 8208 [[3, 74, 164, 431], [190, 86, 531, 413], [33, 541, 143, 638], [30, 76, 211, 485], [159, 57, 356, 464], [67, 58, 294, 491]]
Chk 8209 [[138, 198, 324, 500], [124, 26, 332, 494]]
Chk 8210 [[266, 160, 374, 419], [14, 277, 163, 499]]
Chk 8212 [[252, 111, 639, 420], [510, 26, 639, 168], [127, 59, 254, 281]]
Chk 8213 [[204, 71, 415, 334], [517, 20, 636, 320], [99, 50, 206, 334], [0, 159, 74, 327], [3, 60, 149, 181], [440, 63, 499, 219]]
Chk 8214 [[121, 103, 277, 389], [323, 55, 470, 393]]
Chk 8215 [[92, 122, 273, 367], [274, 130, 419, 386], [461, 131, 638, 422], [2, 142, 77, 338]]
Chk 8216 [[192, 145, 282, 354], [271, 143, 359, 351], [337, 189, 446, 343], [490, 158, 584, 335], [429, 191, 495, 337], [115, 153, 198, 354]]
Chk 8217 [[42, 281, 185, 513], [227, 232, 451, 628]]
Chk 8218 [[216, 17, 581, 424], [2, 24, 345, 421]]
Chk 8219 [[0, 227, 75, 595], [97, 169, 288, 504], [179, 200, 400, 622]]
Chk 8220 [[190, 60, 483, 462], [372, 6, 581, 468]]
Chk 8222 [[388, 198, 459, 474], [334, 219, 426, 479], [238, 212, 323, 479], [437, 183, 514, 479], [166, 184, 262, 471], [309, 208, 362, 479], [368, 173, 435, 240]]
Chk 8223 [[255, 161, 389, 409], [509, 153, 605, 398], [160, 271, 250, 384]]
Chk 8224 [[0, 28, 317, 629], [229, 88, 387, 631]]
Chk 8225 [[168, 1, 639, 473], [11, 244, 260, 479]]
Chk 8227 [[25, 93, 170, 399], [286, 65, 405, 383], [393, 244, 460, 308], [447, 228, 536, 305], [192, 85, 326, 389], [167, 99, 277, 387]]
Chk 8229 [[74, 55, 358, 639], [0, 133, 83, 614]]
Chk 8230 [[126, 92, 323, 410], [453, 212, 605, 455], [335, 232, 495, 444]]
Chk 8231 [[54, 91, 278, 407], [366, 170, 501, 412], [246, 222, 307, 412], [255, 180, 370, 405]]
Chk 8232 [[80, 125, 273, 498], [67, 142, 171, 468]]
Chk 8233 [[230, 126, 357, 458], [336, 111, 579, 479], [298, 144, 397, 376]]
Chk 8236 [[471, 284, 618, 420], [246, 71, 359, 210], [51, 32, 215, 182], [304, 232, 429, 394]]
Chk 8237 [[201, 62, 285, 273], [457, 142, 524, 349], [370, 163, 475, 423], [571, 143, 638, 364], [471, 171, 631, 442], [37, 208, 96, 297]]
Chk 8238 [[417, 178, 536, 360], [276, 183, 336, 310], [28, 198, 129, 479], [162, 173, 227, 265]]
Chk 8239 [[33, 123, 180, 418], [323, 72, 466, 371], [142, 212, 322, 406]]
Chk 8240 [[239, 68, 463, 636], [18, 206, 128, 630]]
Chk 8242 [[81, 37, 223, 419], [0, 68, 93, 408]]
Chk 8243 [[258, 114, 463, 358], [4, 200, 138, 462], [129, 266, 282, 457]]
Chk 8246 [[217, 170, 363, 406], [297, 127, 443, 415]]
Chk 8247 [[31, 5, 477, 479], [462, 31, 639, 309], [209, 143, 537, 471]]
Chk 8248 [[198, 107, 301, 317], [159, 21, 281, 316]]
Chk 8249 [[0, 77, 330, 639], [136, 76, 363, 574]]
Chk 8250 [[150, 79, 250, 427], [400, 58, 467, 329], [284, 49, 409, 452], [140, 67, 203, 318]]
Chk 8251 [[236, 137, 337, 511], [93, 147, 193, 515]]
Chk 8254 [[151, 182, 480, 472], [350, 215, 639, 479]]
Chk 8255 [[80, 8, 332, 368], [305, 20, 420, 369]]
Chk 8256 [[187, 44, 384, 321], [472, 302, 618, 478], [509, 34, 638, 302], [133, 155, 212, 309], [310, 191, 466, 414]]
Chk 8258 [[284, 73, 639, 474], [9, 9, 358, 446]]
Chk 8260 [[182, 138, 455, 632], [71, 135, 231, 620], [0, 118, 84, 639]]
Chk 8261 [[484, 79, 618, 391], [185, 87, 358, 469]]
Chk 8262 [[246, 22, 499, 330], [56, 107, 274, 330]]
Chk 8263 [[221, 231, 479, 630], [179, 96, 287, 252], [394, 138, 479, 331], [226, 130, 354, 323], [141, 100, 214, 175], [105, 89, 188, 258], [45, 148, 161, 390], [27, 115, 122, 255]]
Chk 8265 [[335, 41, 468, 371], [11, 286, 436, 368]]
Chk 8267 [[63, 106, 227, 512], [193, 68, 323, 606], [273, 42, 426, 639]]
Chk 8269 [[330, 161, 453, 316], [243, 192, 362, 448], [558, 193, 639, 479], [552, 127, 639, 305], [83, 64, 256, 478]]
Chk 8271 [[11, 159, 322, 626], [212, 80, 426, 632]]
Chk 8272 [[96, 125, 312, 452], [264, 79, 428, 454]]
Chk 8273 [[92, 53, 379, 419], [273, 7, 417, 340]]
Chk 8275 [[138, 39, 634, 610], [158, 8, 445, 607], [8, 53, 351, 611]]
Chk 8276 [[247, 35, 499, 328], [88, 48, 260, 327], [425, 0, 499, 128], [5, 258, 71, 326]]
Chk 8277 [[0, 31, 318, 375], [162, 72, 639, 420], [567, 8, 639, 103]]
Chk 8278 [[158, 203, 354, 386], [357, 82, 567, 365], [467, 107, 524, 225], [540, 98, 594, 201], [574, 128, 627, 191], [22, 157, 162, 397]]
Chk 8282 [[260, 74, 502, 421], [60, 28, 286, 427], [402, 147, 511, 401], [5, 326, 66, 421], [504, 191, 610, 426]]
Chk 8283 [[103, 155, 284, 520], [268, 25, 390, 412], [342, 33, 427, 417], [0, 77, 53, 252], [163, 55, 262, 414]]
Chk 8284 [[35, 59, 333, 420], [424, 80, 637, 420], [162, 112, 299, 419]]
Chk 8285 [[107, 165, 317, 363], [40, 134, 239, 387], [394, 99, 587, 359]]
Chk 8287 [[271, 118, 486, 473], [104, 100, 375, 478]]
Chk 8288 [[126, 80, 449, 493], [0, 6, 145, 457], [94, 274, 167, 396], [349, 386, 414, 481], [146, 271, 224, 423]]
Chk 8289 [[61, 202, 311, 640], [1, 159, 182, 630], [162, 330, 374, 637]]
Chk 8290 [[302, 67, 588, 479], [53, 52, 271, 472]]
Chk 8291 [[298, 87, 516, 477], [0, 0, 125, 418], [179, 96, 424, 471]]
Chk 8293 [[0, 184, 206, 479], [308, 169, 559, 479], [179, 188, 353, 479]]
Chk 8294 [[100, 14, 369, 272], [0, 0, 233, 272]]
Chk 8298 [[202, 221, 386, 382], [251, 115, 554, 420], [190, 155, 279, 337], [273, 145, 354, 290]]
Chk 8299 [[138, 8, 505, 414], [347, 22, 612, 417]]
Chk 8300 [[251, 34, 550, 420], [0, 0, 325, 421], [357, 204, 639, 426]]
Chk 8301 [[177, 64, 320, 477], [26, 64, 176, 492]]
Chk 8302 [[286, 95, 443, 421], [378, 106, 524, 428]]
Chk 8303 [[168, 181, 247, 362], [41, 201, 328, 479], [267, 185, 364, 323], [374, 249, 639, 473], [423, 196, 506, 291], [108, 189, 206, 413]]
Chk 8304 [[220, 79, 398, 387], [21, 6, 191, 391]]
Chk 8305 [[0, 72, 384, 461], [322, 41, 588, 271]]
Chk 8306 [[180, 31, 325, 263], [528, 0, 639, 267], [290, 39, 600, 420], [305, 1, 413, 160], [479, 1, 538, 66]]
Chk 8307 [[38, 19, 219, 317], [409, 37, 556, 302]]
Chk 8308 [[193, 64, 343, 390], [330, 56, 472, 374]]
Chk 8311 [[140, 105, 416, 421], [0, 267, 112, 413], [105, 204, 172, 396], [354, 150, 455, 426], [475, 167, 639, 426]]
Chk 8312 [[282, 32, 541, 377], [0, 57, 233, 323]]
Chk 8313 [[49, 166, 202, 344], [308, 88, 507, 322]]
Chk 8315 [[292, 53, 470, 354], [173, 121, 297, 310], [11, 7, 255, 423]]
Chk 8317 [[83, 33, 248, 435], [316, 91, 565, 435]]
Chk 8318 [[246, 343, 457, 629], [2, 337, 292, 630], [193, 3, 477, 319], [5, 0, 262, 305]]
Chk 8319 [[60, 184, 196, 393], [2, 115, 97, 369], [201, 2, 303, 156], [0, 68, 83, 140], [406, 50, 538, 149], [283, 75, 562, 376], [32, 65, 104, 161]]
Chk 8322 [[264, 140, 393, 331], [0, 29, 210, 426], [136, 87, 371, 393], [473, 120, 626, 321]]
Chk 8323 [[112, 107, 211, 403], [204, 97, 285, 398], [277, 79, 372, 399], [364, 206, 419, 340]]
Chk 8324 [[9, 139, 135, 342], [350, 89, 455, 345], [449, 100, 575, 364], [116, 97, 250, 270], [227, 73, 280, 178], [320, 114, 394, 287], [542, 87, 608, 217]]
Chk 8325 [[442, 142, 580, 455], [85, 128, 193, 456], [220, 120, 379, 450]]
Chk 8326 [[4, 5, 365, 567], [221, 319, 361, 581]]
Chk 8327 [[293, 215, 424, 634], [96, 222, 150, 291], [139, 226, 311, 629]]
Chk 8329 [[226, 46, 616, 472], [104, 129, 288, 403]]
Chk 8330 [[36, 81, 278, 417], [333, 85, 557, 422], [163, 154, 333, 426]]
Chk 8333 [[212, 143, 300, 398], [207, 2, 269, 138], [464, 50, 566, 235], [440, 187, 551, 420]]
Chk 8334 [[291, 59, 559, 479], [281, 0, 361, 187], [45, 43, 332, 474]]
Chk 8335 [[363, 99, 639, 475], [0, 66, 250, 472]]

Chk 8336 [[268, 100, 370, 472], [344, 94, 639, 474], [239, 183, 422, 467]]
Chk 8337 [[304, 32, 405, 153], [19, 4, 245, 479], [498, 23, 606, 225], [278, 0, 351, 97]]
Chk 8338 [[528, 107, 639, 343], [399, 97, 550, 268], [258, 96, 341, 198], [2, 123, 154, 458], [100, 135, 210, 343]]
Chk 8341 [[260, 104, 501, 425], [4, 58, 304, 418]]
Chk 8342 [[402, 117, 598, 324], [14, 66, 164, 291], [159, 187, 286, 277], [262, 116, 381, 268]]
Chk 8343 [[46, 28, 343, 421], [336, 77, 544, 419], [210, 78, 396, 416], [19, 0, 148, 196], [586, 0, 638, 69]]
Chk 8345 [[0, 11, 258, 581], [173, 91, 386, 531], [363, 54, 423, 253], [282, 65, 406, 211]]
Chk 8346 [[415, 55, 575, 343], [418, 128, 591, 419]]
Chk 8347 [[0, 0, 157, 639], [135, 112, 462, 516], [74, 209, 258, 639]]
Chk 8349 [[101, 14, 196, 365], [285, 29, 368, 375], [188, 41, 288, 179]]
Chk 8350 [[113, 181, 502, 539], [191, 53, 389, 553]]
Chk 8351 [[165, 45, 286, 283], [1, 113, 133, 333], [84, 105, 175, 304], [323, 64, 427, 173], [11, 0, 90, 150], [106, 0, 171, 173], [342, 0, 417, 100]]
Chk 8352 [[208, 153, 319, 363], [295, 113, 415, 354]]
Chk 8353 [[238, 89, 374, 583], [145, 38, 260, 397]]
Chk 8354 [[0, 153, 201, 419], [123, 222, 285, 407], [400, 131, 536, 251], [47, 138, 151, 388]]
Chk 8355 [[0, 156, 192, 479], [375, 288, 495, 472], [535, 247, 639, 478]]
Chk 8356 [[283, 4, 467, 381], [127, 15, 323, 380]]
Chk 8357 [[1, 161, 142, 424], [102, 144, 162, 221], [208, 65, 341, 180], [409, 80, 639, 431], [454, 119, 543, 274], [384, 48, 536, 238], [125, 90, 189, 208]]
Chk 8359 [[216, 0, 444, 317], [71, 28, 359, 332]]
Chk 8361 [[269, 21, 462, 270], [3, 83, 320, 390], [180, 215, 474, 479]]
Chk 8362 [[80, 100, 258, 494], [0, 262, 140, 619]]
Chk 8365 [[307, 18, 639, 410], [0, 47, 321, 415], [239, 67, 356, 255], [451, 0, 619, 195]]
Chk 8371 [[299, 63, 473, 277], [52, 34, 242, 223], [161, 64, 286, 275]]
Chk 8372 [[94, 52, 291, 479], [344, 78, 489, 478]]
Chk 8373 [[342, 165, 604, 589], [17, 246, 244, 571]]
Chk 8374 [[275, 115, 425, 381], [235, 80, 329, 379], [369, 78, 460, 309], [552, 96, 639, 378], [539, 95, 599, 303]]
Chk 8375 [[37, 60, 177, 408], [211, 80, 358, 470]]
Chk 8376 [[0, 123, 399, 407], [451, 23, 607, 230]]
Chk 8377 [[472, 308, 639, 458], [379, 154, 573, 308], [233, 132, 389, 263], [50, 170, 135, 251], [7, 239, 88, 413], [26, 252, 363, 625]]
Chk 8378 [[63, 211, 226, 559], [186, 212, 340, 536], [22, 0, 146, 160]]
Chk 8380 [[294, 136, 507, 362], [118, 110, 349, 322]]
Chk 8381 [[267, 103, 425, 384], [177, 131, 258, 288], [260, 127, 333, 287], [388, 207, 519, 379], [505, 145, 639, 386], [517, 56, 599, 318], [86, 180, 140, 265], [0, 175, 72, 284]]
Chk 8383 [[0, 9, 217, 370], [253, 10, 499, 370]]
Chk 8384 [[183, 92, 329, 372], [48, 100, 202, 611], [356, 144, 408, 348], [15, 131, 91, 343]]
Chk 8385 [[162, 39, 567, 388], [9, 0, 301, 284]]
Chk 8386 [[1, 88, 293, 473], [398, 47, 639, 345], [128, 3, 271, 288], [231, 17, 366, 256], [60, 75, 241, 370]]
Chk 8389 [[90, 206, 288, 426], [0, 95, 151, 421]]
Chk 8390 [[356, 94, 554, 479], [288, 145, 395, 258], [66, 148, 236, 473]]
Chk 8391 [[226, 94, 419, 385], [77, 97, 294, 363], [217, 52, 284, 127], [416, 67, 605, 372]]
Chk 8392 [[327, 147, 556, 420], [42, 223, 253, 424]]
Chk 8394 [[208, 17, 464, 421], [0, 1, 206, 207]]
Chk 8395 [[0, 42, 148, 511], [259, 46, 611, 462], [508, 346, 611, 518]]
Chk 8397 [[96, 19, 189, 371], [447, 131, 590, 436]]
Chk 8398 [[1, 143, 368, 600], [167, 80, 426, 486]]
Chk 8399 [[186, 70, 347, 328], [288, 111, 400, 313]]
Chk 8401 [[28, 148, 230, 471], [290, 119, 502, 474]]
Chk 8402 [[192, 92, 359, 391], [341, 153, 406, 312], [413, 73, 639, 412], [109, 96, 196, 394]]
Chk 8403 [[70, 14, 246, 355], [237, 38, 394, 368]]
Chk 8406 [[38, 126, 344, 630], [247, 66, 544, 622]]
Chk 8408 [[1, 145, 265, 383], [176, 161, 306, 317], [280, 173, 393, 291], [312, 139, 369, 227], [361, 180, 420, 260], [398, 174, 478, 280], [494, 136, 639, 445], [471, 166, 564, 309]]
Chk 8409 [[13, 78, 240, 591], [400, 6, 639, 583]]
Chk 8411 [[81, 63, 355, 509], [261, 160, 538, 503]]
Chk 8412 [[38, 131, 267, 398], [459, 37, 620, 382], [233, 131, 468, 381], [0, 133, 57, 214], [384, 57, 539, 369], [221, 34, 350, 288]]
Chk 8414 [[43, 149, 257, 370], [242, 0, 465, 342], [91, 0, 164, 88]]
Chk 8415 [[199, 108, 362, 330], [372, 117, 471, 318], [470, 33, 620, 352]]
Chk 8418 [[0, 18, 347, 421], [189, 83, 607, 421], [401, 315, 572, 425], [317, 352, 413, 421]]
Chk 8419 [[4, 143, 224, 639], [199, 155, 422, 562]]
Chk 8420 [[141, 155, 309, 394], [185, 218, 387, 422], [70, 298, 130, 426], [0, 310, 64, 419]]
Chk 8421 [[350, 92, 527, 300], [241, 66, 639, 425], [277, 206, 351, 417], [99, 260, 221, 421], [343, 193, 394, 418], [230, 279, 331, 398]]
Chk 8422 [[3, 63, 199, 340], [246, 30, 494, 336], [204, 67, 382, 336]]
Chk 8423 [[158, 43, 366, 257], [225, 177, 472, 395]]
Chk 8425 [[219, 18, 329, 374], [96, 28, 297, 405], [396, 22, 505, 355], [383, 5, 639, 414], [18, 44, 80, 268]]
Chk 8426 [[311, 49, 562, 298], [26, 106, 208, 388]]
Chk 8428 [[45, 329, 271, 611], [192, 0, 570, 611]]
Chk 8429 [[148, 150, 342, 624], [1, 298, 234, 639], [39, 66, 150, 328], [151, 37, 224, 269]]
Chk 8430 [[191, 20, 325, 299], [74, 95, 125, 163], [0, 104, 99, 300], [300, 99, 499, 331]]
Chk 8431 [[257, 190, 359, 349], [309, 222, 501, 421], [213, 160, 272, 270]]
Chk 8432 [[3, 188, 231, 465], [176, 169, 297, 299], [494, 82, 639, 358], [320, 107, 397, 280]]
Chk 8433 [[308, 0, 595, 419], [285, 32, 412, 383]]
Chk 8435 [[29, 171, 125, 303], [98, 157, 180, 278], [184, 114, 248, 174], [227, 140, 299, 249], [259, 167, 344, 313], [84, 274, 248, 494], [0, 225, 126, 498], [257, 216, 374, 499]]
Chk 8436 [[6, 13, 354, 390], [251, 45, 632, 390]]
Chk 8437 [[24, 261, 281, 630], [166, 129, 322, 320]]
Chk 8438 [[341, 86, 507, 452], [545, 133, 639, 382], [341, 319, 401, 374]]
Chk 8439 [[152, 106, 419, 479], [322, 100, 557, 325], [420, 46, 522, 187], [496, 28, 564, 135], [550, 60, 639, 207], [565, 24, 639, 138]]
Chk 8440 [[425, 247, 566, 388], [531, 198, 638, 397], [208, 170, 371, 404]]
Chk 8441 [[32, 235, 165, 418], [177, 204, 253, 315], [329, 149, 607, 408], [182, 198, 366, 479], [0, 228, 181, 471], [81, 255, 136, 339], [542, 183, 639, 479], [356, 250, 582, 479]]
Chk 8442 [[2, 402, 283, 630], [172, 300, 495, 630], [221, 3, 505, 364]]
Chk 8443 [[248, 89, 468, 400], [113, 107, 230, 349], [0, 50, 136, 395], [501, 107, 633, 424]]
Chk 8444 [[257, 56, 608, 403], [2, 3, 129, 375]]
Chk 8445 [[233, 27, 524, 420], [20, 25, 219, 425], [173, 106, 269, 426]]
Chk 8446 [[116, 176, 262, 369], [173, 101, 268, 306], [249, 87, 391, 374]]
Chk 8447 [[383, 67, 543, 285], [122, 87, 387, 326], [0, 104, 320, 474], [572, 60, 639, 246]]
Chk 8448 [[342, 112, 425, 408], [59, 154, 364, 476]]
Chk 8450 [[440, 78, 619, 363], [48, 95, 223, 375], [203, 167, 425, 359]]
Chk 8451 [[236, 84, 466, 421], [157, 98, 287, 403]]
Chk 8453 [[87, 46, 328, 409], [306, 90, 534, 372]]
Chk 8454 [[285, 337, 358, 426], [362, 344, 431, 426], [47, 81, 253, 421], [0, 350, 61, 426], [400, 1, 599, 426]]
Chk 8455 [[37, 187, 203, 512], [274, 142, 413, 603]]
Chk 8456 [[247, 226, 413, 428], [375, 242, 610, 540], [0, 261, 187, 533]]
Chk 8457 [[245, 50, 466, 599], [110, 20, 293, 420]]
Chk 8458 [[219, 219, 556, 469], [155, 386, 235, 479], [157, 328, 267, 450], [0, 56, 349, 472]]
Chk 8459 [[289, 206, 516, 340], [184, 175, 275, 278], [0, 162, 73, 285], [434, 132, 610, 298], [267, 165, 381, 368], [85, 167, 239, 292], [266, 193, 327, 269], [412, 106, 480, 211]]
Chk 8460 [[8, 12, 233, 632], [41, 0, 435, 629]]
Chk 8461 [[166, 64, 334, 345], [312, 127, 433, 337], [489, 84, 602, 333], [81, 1, 140, 86], [152, 0, 244, 76]]
Chk 8462 [[358, 179, 480, 473], [282, 226, 393, 478], [133, 327, 302, 479], [46, 344, 163, 479]]
Chk 8463 [[240, 162, 378, 421], [75, 163, 200, 409], [509, 37, 639, 421]]
Chk 8464 [[84, 76, 230, 373], [501, 98, 578, 321], [296, 38, 407, 360], [405, 41, 529, 365], [209, 43, 312, 354], [163, 318, 253, 413]]
Chk 8465 [[190, 53, 369, 473], [284, 111, 554, 471]]
Chk 8467 [[207, 120, 384, 380], [85, 7, 229, 411]]
Chk 8469 [[200, 371, 316, 589], [37, 98, 108, 342], [113, 62, 294, 435]]
Chk 8470 [[372, 206, 430, 288], [50, 67, 169, 377], [388, 82, 490, 382], [530, 172, 609, 297], [125, 213, 182, 292], [171, 213, 223, 297], [307, 203, 369, 280]]
Chk 8471 [[407, 44, 574, 601], [4, 1, 147, 295], [5, 196, 173, 624], [187, 143, 403, 626], [196, 43, 388, 270]]
Chk 8472 [[139, 139, 227, 420], [237, 136, 311, 416], [319, 136, 433, 419], [362, 125, 520, 419]]
Chk 8474 [[0, 61, 208, 343], [97, 0, 204, 234], [0, 55, 53, 170], [415, 27, 639, 427]]

Chk 8475 [[67, 154, 197, 350], [158, 168, 341, 468], [378, 86, 497, 369], [541, 164, 638, 361], [217, 134, 354, 364]]
Chk 8476 [[220, 94, 375, 386], [362, 62, 532, 414], [2, 78, 172, 306], [1, 134, 87, 298]]
Chk 8477 [[238, 116, 451, 318], [375, 122, 504, 416], [141, 177, 304, 487]]
Chk 8478 [[133, 109, 296, 366], [302, 190, 483, 386], [433, 162, 606, 388]]
Chk 8479 [[296, 17, 465, 347], [401, 21, 502, 259], [125, 38, 197, 232], [173, 19, 353, 406], [430, 111, 485, 260]]
Chk 8480 [[72, 44, 304, 639], [3, 64, 287, 638]]
Chk 8481 [[22, 6, 545, 503], [125, 71, 253, 273]]
Chk 8484 [[1, 79, 349, 528], [0, 0, 270, 529]]
Chk 8485 [[263, 154, 483, 427], [271, 147, 517, 427]]
Chk 8486 [[68, 76, 239, 366], [0, 80, 101, 369], [401, 97, 469, 264], [150, 105, 265, 235], [442, 97, 498, 295]]
Chk 8488 [[136, 116, 265, 411], [180, 31, 238, 118], [495, 83, 613, 356], [147, 79, 272, 258]]
Chk 8489 [[0, 109, 163, 493], [6, 131, 99, 460]]
Chk 8490 [[257, 76, 629, 346], [245, 275, 452, 409]]
Chk 8491 [[377, 173, 459, 338], [439, 265, 518, 352], [162, 128, 285, 386], [0, 1, 245, 475]]
Chk 8492 [[135, 89, 280, 459], [264, 17, 423, 523]]
Chk 8493 [[87, 45, 184, 328], [405, 79, 631, 418]]
Chk 8494 [[194, 106, 360, 341], [39, 95, 251, 311], [311, 141, 511, 473], [452, 7, 639, 474]]
Chk 8495 [[259, 100, 432, 318], [525, 95, 626, 242], [60, 140, 234, 368]]
Chk 8496 [[27, 54, 216, 420], [0, 27, 96, 327], [312, 87, 400, 246], [480, 88, 552, 196], [182, 187, 259, 426], [347, 137, 635, 396]]
Chk 8497 [[146, 186, 247, 465], [47, 183, 153, 482]]
Chk 8498 [[145, 187, 412, 529], [172, 228, 392, 529]]
Chk 8499 [[56, 130, 160, 416], [196, 137, 278, 391], [135, 148, 205, 401]]
Chk 8500 [[0, 147, 166, 542], [196, 140, 343, 454], [345, 129, 424, 327], [75, 143, 168, 267], [2, 137, 54, 191]]
Chk 8504 [[201, 86, 387, 359], [520, 104, 639, 284], [37, 86, 121, 213], [124, 74, 188, 203], [351, 73, 402, 219], [390, 173, 569, 345], [448, 12, 505, 64]]
Chk 8505 [[353, 151, 592, 523], [278, 111, 386, 367], [28, 97, 168, 306]]
Chk 8506 [[444, 16, 628, 478], [300, 71, 421, 332], [236, 58, 369, 474], [80, 19, 142, 224], [15, 56, 101, 228]]
Chk 8508 [[0, 251, 294, 370], [357, 290, 638, 451]]
Chk 8509 [[169, 128, 363, 424], [2, 291, 149, 418], [378, 169, 639, 425], [504, 143, 620, 285]]
Chk 8510 [[374, 71, 458, 348], [305, 77, 392, 235], [178, 191, 295, 367], [144, 56, 233, 353], [230, 61, 316, 281], [294, 179, 393, 374]]
Chk 8511 [[147, 130, 486, 443], [0, 109, 234, 373], [544, 163, 639, 271]]
Chk 8512 [[285, 26, 483, 305], [438, 128, 639, 324], [215, 2, 267, 94]]
Chk 8513 [[409, 79, 585, 474], [161, 93, 300, 474], [43, 90, 183, 473], [311, 59, 503, 479]]
Chk 8514 [[198, 104, 639, 472], [2, 91, 237, 476]]
Chk 8516 [[112, 138, 285, 387], [316, 222, 541, 401], [492, 205, 639, 407], [545, 0, 599, 76]]
Chk 8517 [[280, 133, 499, 367], [60, 53, 227, 370], [430, 98, 499, 248]]
Chk 8519 [[99, 74, 377, 452], [279, 73, 515, 451], [13, 93, 247, 398], [324, 20, 526, 141], [194, 27, 314, 170]]
Chk 8520 [[132, 214, 279, 633], [331, 425, 479, 639], [134, 378, 280, 639]]
Chk 8521 [[3, 115, 223, 632], [154, 153, 275, 418]]
Chk 8522 [[344, 148, 478, 478], [182, 159, 315, 449]]
Chk 8523 [[36, 73, 228, 421], [192, 69, 305, 420], [290, 69, 376, 425], [325, 50, 498, 426], [470, 15, 639, 426]]
Chk 8524 [[265, 67, 457, 364], [76, 79, 191, 415]]
Chk 8525 [[266, 266, 437, 479], [131, 125, 263, 479], [0, 73, 141, 479]]
Chk 8526 [[341, 141, 440, 462], [52, 84, 226, 479]]
Chk 8528 [[71, 292, 207, 474], [283, 238, 443, 458], [167, 350, 337, 472], [253, 0, 312, 118]]
Chk 8529 [[0, 168, 294, 534], [42, 0, 254, 340]]
Chk 8531 [[1, 189, 140, 493], [114, 112, 330, 492]]
Chk 8534 [[241, 16, 592, 604], [247, 6, 388, 158], [16, 104, 114, 210], [80, 16, 162, 132], [22, 16, 170, 194]]
Chk 8535 [[132, 128, 324, 476], [322, 83, 475, 481], [3, 132, 98, 468]]
Chk 8537 [[133, 20, 236, 372], [61, 132, 162, 363], [336, 155, 499, 372]]
Chk 8538 [[25, 83, 254, 421], [237, 115, 381, 366], [371, 123, 546, 310], [557, 162, 639, 363]]
Chk 8539 [[330, 128, 431, 455], [412, 150, 500, 466]]
Chk 8540 [[247, 18, 503, 407], [4, 145, 297, 419]]
Chk 8541 [[224, 194, 372, 552], [98, 195, 234, 517]]
Chk 8542 [[74, 43, 218, 395], [497, 58, 587, 390]]
Chk 8543 [[67, 260, 290, 636], [242, 122, 489, 638]]
Chk 8544 [[235, 98, 393, 499], [49, 95, 246, 370]]
Chk 8545 [[0, 75, 202, 420], [197, 93, 388, 419], [383, 123, 614, 416]]
Chk 8547 [[175, 185, 379, 615], [70, 170, 221, 610]]
Chk 8548 [[434, 223, 638, 373], [272, 27, 504, 372]]
Chk 8549 [[2, 65, 91, 209], [231, 147, 547, 479], [454, 165, 550, 310], [538, 147, 639, 338], [426, 163, 529, 377]]
Chk 8551 [[364, 65, 595, 412], [8, 10, 99, 417], [92, 40, 309, 425]]
Chk 8553 [[263, 79, 424, 395], [80, 51, 227, 218], [458, 238, 639, 416], [349, 111, 619, 420]]
Chk 8554 [[151, 42, 288, 345], [586, 25, 639, 226], [289, 12, 444, 345], [32, 50, 171, 377], [0, 74, 52, 386], [401, 11, 606, 410]]
Chk 8557 [[128, 72, 318, 421], [348, 91, 546, 422]]
Chk 8558 [[137, 156, 399, 479], [281, 127, 443, 473], [518, 236, 639, 479], [378, 79, 559, 473]]
Chk 8560 [[106, 137, 294, 417], [57, 92, 149, 409], [426, 109, 585, 416]]
Chk 8563 [[117, 72, 317, 416], [375, 76, 545, 426]]
Chk 8564 [[1, 38, 252, 451], [519, 1, 637, 321], [356, 11, 635, 445], [132, 1, 273, 93]]
Chk 8565 [[148, 50, 369, 249], [151, 100, 559, 421], [214, 56, 493, 416]]
Chk 8568 [[507, 86, 594, 414], [419, 84, 507, 325], [125, 94, 233, 392], [99, 85, 152, 306]]
Chk 8569 [[193, 141, 437, 599], [268, 139, 436, 476]]
Chk 8571 [[125, 106, 339, 351], [525, 166, 637, 374], [385, 157, 548, 323]]
Chk 8572 [[287, 246, 448, 423], [457, 226, 523, 423], [497, 237, 588, 419]]
Chk 8573 [[311, 78, 440, 447], [432, 111, 510, 340], [233, 104, 337, 445], [564, 108, 621, 270], [159, 120, 299, 472]]
Chk 8576 [[338, 24, 536, 316], [0, 35, 145, 220], [239, 69, 348, 166], [161, 82, 326, 264], [449, 25, 594, 213]]
Chk 8578 [[273, 108, 572, 441], [61, 32, 242, 421]]
Chk 8580 [[174, 57, 451, 425], [406, 61, 635, 426], [1, 49, 245, 426]]
Chk 8582 [[0, 86, 275, 360], [193, 65, 277, 266], [494, 101, 639, 301], [269, 114, 550, 356]]
Chk 8583 [[141, 25, 352, 485], [1, 29, 183, 491]]
Chk 8584 [[0, 22, 129, 421], [117, 74, 232, 223], [505, 96, 621, 263], [101, 87, 280, 420], [240, 112, 326, 407]]
Chk 8585 [[159, 122, 391, 419], [355, 251, 501, 417], [351, 202, 548, 287], [26, 274, 274, 425]]
Chk 8586 [[94, 241, 373, 479], [288, 194, 639, 479], [582, 191, 639, 381]]
Chk 8587 [[0, 4, 308, 323], [0, 100, 612, 604]]
Chk 8588 [[419, 76, 639, 470], [578, 117, 639, 281], [147, 16, 469, 473]]
Chk 8589 [[270, 46, 440, 237], [372, 73, 638, 314], [3, 98, 163, 430]]
Chk 8590 [[0, 88, 150, 271], [185, 148, 248, 262], [274, 111, 409, 295], [421, 97, 487, 225], [492, 1, 639, 297], [416, 54, 617, 365], [410, 153, 472, 284]]
Chk 8591 [[220, 88, 415, 424], [389, 185, 639, 426], [141, 206, 229, 393]]
Chk 8592 [[261, 1, 510, 183], [0, 88, 242, 258]]
Chk 8593 [[425, 1, 638, 425], [261, 31, 411, 225], [17, 107, 84, 170], [129, 41, 212, 112]]
Chk 8596 [[231, 182, 370, 428], [456, 213, 639, 428]]
Chk 8597 [[138, 118, 217, 419], [56, 97, 192, 421], [413, 88, 533, 419]]
Chk 8598 [[6, 261, 169, 439], [116, 276, 195, 414], [186, 274, 260, 370], [357, 235, 575, 449], [296, 274, 352, 347], [340, 270, 401, 387], [385, 249, 464, 346], [240, 283, 297, 350]]
Chk 8601 [[338, 0, 549, 226], [0, 0, 265, 113]]
Chk 8602 [[98, 128, 180, 376], [217, 163, 287, 360], [310, 143, 380, 364], [396, 111, 487, 373], [496, 42, 610, 395]]
Chk 8603 [[320, 31, 573, 527], [36, 31, 355, 533], [192, 43, 351, 333], [21, 2, 169, 167]]
Chk 8605 [[142, 171, 287, 394], [244, 265, 420, 439], [391, 220, 527, 445]]
Chk 8606 [[169, 0, 639, 477], [102, 3, 433, 473], [0, 57, 142, 216], [212, 21, 293, 248]]
Chk 8607 [[204, 137, 259, 267], [466, 192, 639, 479], [217, 119, 349, 431], [406, 271, 611, 479]]
Chk 8608 [[419, 104, 550, 370], [130, 139, 202, 418], [25, 77, 213, 444]]
Chk 8610 [[368, 166, 484, 415], [280, 181, 371, 422], [162, 179, 256, 419], [473, 185, 614, 415], [25, 193, 101, 437]]
Chk 8611 [[294, 0, 616, 472], [1, 110, 208, 474], [30, 3, 307, 479]]
Chk 8612 [[102, 67, 321, 329], [326, 0, 633, 420]]
Chk 8613 [[1, 2, 331, 467], [209, 51, 476, 459], [294, 9, 612, 459]]
Chk 8614 [[303, 87, 456, 340], [48, 42, 299, 432]]
Chk 8616 [[145, 108, 490, 499], [224, 114, 457, 370]]
Chk 8617 [[275, 90, 538, 374], [100, 72, 338, 380]]
Chk 8618 [[378, 67, 600, 420], [300, 24, 470, 419], [58, 21, 305, 419], [251, 58, 367, 419]]
Chk 8619 [[195, 112, 390, 425], [445, 146, 638, 419]]

Chk 8620 [[107, 159, 221, 420], [291, 139, 432, 426]]
Chk 8621 [[292, 98, 400, 310], [26, 143, 220, 470], [340, 119, 468, 276], [147, 112, 266, 377], [530, 26, 632, 236], [345, 149, 561, 474]]
Chk 8622 [[154, 12, 324, 332], [27, 82, 127, 228], [100, 23, 223, 326]]
Chk 8623 [[116, 1, 325, 331], [417, 16, 524, 336], [417, 4, 639, 345], [0, 164, 87, 244]]
Chk 8624 [[144, 111, 250, 278], [374, 134, 497, 329], [228, 106, 331, 309], [235, 110, 423, 327], [156, 106, 216, 192], [241, 162, 362, 229], [251, 159, 412, 288]]
Chk 8627 [[530, 31, 604, 248], [517, 148, 570, 218], [361, 140, 421, 217], [213, 135, 271, 209], [445, 212, 639, 449], [70, 225, 255, 469], [278, 296, 449, 446], [416, 166, 469, 218]]
Chk 8631 [[98, 134, 265, 370], [242, 59, 499, 372]]
Chk 8632 [[150, 133, 367, 474], [235, 158, 342, 479]]
Chk 8633 [[270, 82, 607, 605], [6, 85, 175, 381], [131, 77, 204, 255]]
Chk 8636 [[314, 74, 527, 369], [185, 105, 308, 423]]
Chk 8639 [[76, 85, 387, 632], [1, 186, 88, 561]]
Chk 8641 [[100, 169, 238, 429], [1, 300, 333, 564]]
Chk 8642 [[0, 201, 134, 639], [88, 0, 155, 53], [249, 231, 479, 639], [136, 0, 196, 51], [109, 95, 310, 626]]
Chk 8643 [[92, 131, 317, 364], [291, 127, 542, 423]]
Chk 8645 [[350, 208, 566, 425], [278, 108, 354, 212], [470, 124, 602, 294], [114, 193, 195, 345], [130, 129, 212, 266], [338, 37, 396, 171], [143, 178, 332, 416], [322, 108, 430, 251]]
Chk 8646 [[1, 134, 298, 470], [225, 84, 381, 278], [372, 101, 565, 412], [513, 66, 608, 156], [17, 59, 73, 129]]
Chk 8647 [[322, 119, 497, 370], [7, 61, 104, 277], [169, 102, 338, 337]]
Chk 8648 [[440, 58, 636, 144], [356, 97, 472, 211], [213, 62, 306, 204], [425, 90, 623, 291], [557, 116, 639, 268], [106, 94, 310, 426]]
Chk 8649 [[101, 137, 234, 562], [196, 148, 368, 556]]
Chk 8651 [[268, 162, 502, 473], [79, 33, 341, 474]]
Chk 8652 [[403, 152, 505, 426], [0, 112, 159, 422], [250, 153, 344, 377], [214, 100, 422, 423]]
Chk 8654 [[296, 152, 432, 347], [129, 64, 327, 357], [482, 73, 629, 345], [379, 4, 499, 59]]
Chk 8658 [[302, 81, 507, 384], [244, 62, 302, 279], [482, 85, 573, 248], [314, 63, 390, 295], [511, 89, 620, 356], [157, 97, 305, 343]]
Chk 8659 [[1, 153, 479, 631], [40, 219, 233, 450]]
Chk 8660 [[178, 125, 324, 418], [258, 96, 370, 403]]
Chk 8661 [[323, 128, 534, 423], [3, 25, 373, 418], [435, 33, 639, 416]]
Chk 8662 [[301, 83, 464, 472], [222, 232, 376, 479], [0, 60, 191, 473]]
Chk 8664 [[250, 239, 517, 474], [2, 2, 465, 473]]
Chk 8667 [[136, 86, 461, 421], [233, 1, 639, 426]]
Chk 8669 [[95, 109, 248, 578], [210, 76, 472, 626]]
Chk 8670 [[335, 87, 576, 423], [73, 2, 328, 291]]
Chk 8671 [[2, 7, 505, 474], [287, 60, 639, 479]]
Chk 8673 [[376, 82, 536, 420], [159, 51, 392, 419], [504, 82, 580, 427]]
Chk 8674 [[39, 16, 217, 479], [327, 43, 457, 407]]
Chk 8675 [[165, 0, 634, 385], [8, 90, 182, 326], [333, 35, 413, 147]]
Chk 8676 [[1, 143, 231, 473], [298, 62, 435, 301]]
Chk 8677 [[162, 143, 270, 392], [472, 107, 573, 411]]
Chk 8678 [[0, 0, 362, 370], [296, 0, 499, 369]]
Chk 8679 [[106, 87, 416, 421], [202, 87, 287, 211], [278, 160, 465, 327]]
Chk 8680 [[136, 86, 553, 500], [247, 94, 607, 428]]
Chk 8682 [[357, 71, 514, 359], [126, 58, 244, 333], [230, 369, 282, 420], [319, 348, 389, 403], [149, 346, 202, 401]]
Chk 8683 [[289, 142, 391, 432], [0, 171, 175, 474], [226, 190, 297, 260], [84, 213, 208, 384]]
Chk 8685 [[101, 279, 258, 595], [300, 254, 428, 478], [57, 265, 143, 594]]
Chk 8686 [[217, 30, 437, 374], [106, 172, 246, 374]]
Chk 8687 [[180, 139, 309, 321], [339, 113, 505, 420]]
Chk 8688 [[257, 66, 436, 391], [92, 89, 292, 399]]
Chk 8689 [[0, 118, 214, 406], [281, 171, 341, 297], [370, 67, 545, 392]]
Chk 8690 [[255, 167, 463, 418], [354, 0, 442, 194], [172, 105, 346, 462], [127, 42, 181, 104]]
Chk 8691 [[27, 53, 170, 249], [127, 68, 198, 235], [244, 100, 320, 228], [285, 78, 429, 306]]
Chk 8692 [[240, 31, 477, 482], [1, 25, 237, 427], [359, 16, 479, 293], [392, 379, 479, 637], [1, 375, 165, 485], [292, 329, 364, 424]]
Chk 8696 [[27, 53, 469, 421], [269, 11, 466, 427]]
Chk 8699 [[164, 127, 347, 433], [452, 81, 607, 567], [0, 121, 127, 454]]
Chk 8700 [[0, 127, 199, 438], [93, 105, 314, 440], [227, 36, 560, 440]]
Chk 8701 [[309, 119, 465, 385], [112, 118, 268, 359]]
Chk 8702 [[56, 47, 595, 473], [423, 36, 496, 125], [121, 61, 174, 112], [483, 0, 639, 479]]
Chk 8703 [[0, 0, 349, 480], [285, 96, 602, 436]]
Chk 8704 [[185, 61, 289, 375], [155, 239, 242, 422], [399, 155, 537, 375], [122, 56, 177, 234], [282, 56, 397, 153]]
Chk 8705 [[163, 68, 425, 374], [107, 75, 426, 287]]
Chk 8706 [[146, 194, 306, 459], [111, 159, 250, 363], [187, 217, 374, 499], [87, 69, 143, 245]]
Chk 8708 [[192, 112, 356, 348], [258, 67, 327, 263], [478, 109, 561, 339], [323, 80, 418, 298]]
Chk 8710 [[398, 129, 486, 425], [105, 136, 176, 370], [447, 116, 502, 186], [444, 69, 521, 152], [264, 116, 374, 404], [249, 79, 303, 138], [50, 87, 108, 138], [536, 65, 610, 149]]
Chk 8713 [[173, 10, 404, 631], [367, 39, 422, 404], [0, 9, 202, 595]]
Chk 8714 [[128, 1, 340, 411], [20, 336, 238, 626], [188, 265, 333, 449]]
Chk 8715 [[404, 66, 462, 308], [121, 66, 228, 235], [0, 90, 182, 409], [64, 62, 163, 248], [437, 90, 525, 352], [505, 71, 639, 424]]
Chk 8717 [[34, 206, 152, 562], [268, 30, 457, 625]]
Chk 8718 [[34, 106, 177, 429], [466, 154, 629, 477]]
Chk 8719 [[1, 67, 373, 498], [4, 45, 165, 427]]
Chk 8720 [[28, 155, 145, 369], [441, 1, 499, 181], [1, 26, 97, 78], [86, 8, 183, 73], [341, 7, 434, 311]]
Chk 8721 [[276, 81, 372, 356], [485, 95, 575, 353], [117, 137, 176, 308], [189, 138, 262, 309], [0, 1, 104, 422], [575, 201, 634, 307]]
Chk 8722 [[296, 102, 467, 426], [121, 148, 318, 426], [160, 261, 281, 426]]
Chk 8723 [[0, 77, 412, 628], [232, 83, 453, 623]]
Chk 8725 [[278, 42, 625, 421], [312, 102, 426, 420], [137, 324, 272, 418]]
Chk 8728 [[363, 45, 516, 479], [148, 46, 300, 473]]
Chk 8729 [[274, 91, 534, 405], [49, 250, 298, 438], [48, 1, 124, 65], [142, 0, 217, 63], [0, 8, 59, 61], [0, 184, 111, 436]]
Chk 8734 [[343, 98, 496, 306], [547, 87, 639, 348], [43, 54, 215, 302], [408, 314, 624, 429]]
Chk 8735 [[198, 3, 485, 418], [92, 0, 291, 471]]
Chk 8737 [[220, 72, 325, 317], [101, 81, 209, 414], [446, 87, 587, 421], [309, 83, 441, 277]]
Chk 8738 [[297, 118, 419, 548], [198, 140, 345, 624], [116, 201, 244, 345]]
Chk 8739 [[0, 91, 256, 421], [208, 84, 559, 420]]
Chk 8740 [[292, 18, 613, 350], [38, 33, 309, 350], [248, 83, 306, 163]]
Chk 8743 [[157, 0, 302, 205], [183, 41, 399, 296]]
Chk 8744 [[304, 145, 520, 479], [514, 109, 625, 280], [297, 108, 401, 225], [67, 155, 279, 416], [0, 119, 74, 383], [164, 122, 221, 188]]
Chk 8745 [[14, 75, 199, 330], [283, 29, 432, 331]]
Chk 8746 [[372, 169, 451, 418], [489, 196, 577, 423], [572, 172, 639, 424]]
Chk 8747 [[253, 23, 611, 636], [40, 256, 600, 631]]
Chk 8748 [[54, 116, 281, 502], [282, 116, 394, 539], [135, 203, 330, 562]]
Chk 8750 [[318, 107, 628, 469], [288, 83, 558, 384]]
Chk 8751 [[7, 130, 294, 630], [249, 220, 425, 639]]
Chk 8752 [[37, 54, 392, 630], [28, 109, 216, 632]]
Chk 8753 [[280, 0, 639, 421], [0, 24, 346, 421]]
Chk 8754 [[216, 52, 322, 445], [307, 65, 413, 442], [419, 57, 545, 447], [407, 91, 472, 291], [23, 293, 95, 435], [368, 45, 447, 447]]
Chk 8755 [[236, 58, 391, 407], [137, 114, 267, 378]]
Chk 8756 [[271, 111, 435, 485], [454, 76, 613, 490]]
Chk 8758 [[74, 51, 499, 327], [72, 38, 331, 333], [9, 52, 103, 333]]
Chk 8759 [[186, 94, 336, 259], [349, 82, 499, 261]]
Chk 8760 [[175, 189, 300, 473], [37, 180, 161, 473]]
Chk 8761 [[221, 139, 469, 369], [404, 0, 499, 375]]
Chk 8762 [[364, 145, 518, 418], [172, 121, 294, 425], [312, 284, 383, 425], [533, 261, 639, 425]]
Chk 8764 [[4, 50, 466, 628], [210, 287, 476, 635]]
Chk 8766 [[140, 55, 391, 419], [427, 5, 639, 373]]
Chk 8767 [[69, 45, 404, 473], [275, 50, 535, 471]]
Chk 8768 [[133, 182, 323, 425], [286, 188, 401, 425], [423, 212, 563, 425], [95, 114, 345, 306]]
Chk 8769 [[6, 25, 180, 370], [232, 81, 499, 370]]
Chk 8771 [[0, 195, 212, 630], [155, 129, 426, 632], [0, 238, 55, 369], [32, 244, 96, 362]]
Chk 8772 [[210, 192, 349, 630], [0, 118, 258, 632]]
Chk 8773 [[420, 154, 574, 473], [564, 306, 638, 470], [231, 220, 404, 479], [444, 317, 588, 452]]
Chk 8774 [[60, 109, 205, 334], [122, 96, 194, 184], [319, 270, 639, 418]]
Chk 8775 [[0, 99, 308, 479], [289, 101, 639, 469], [51, 1, 185, 82], [1, 0, 93, 114], [571, 26, 639, 90], [511, 0, 639, 73]]
Chk 8776 [[145, 46, 422, 308], [379, 82, 520, 335], [84, 163, 315, 424]]
Chk 8777 [[182, 107, 319, 299], [64, 108, 230, 381]]
Chk 8778 [[19, 65, 191, 328], [159, 67, 331, 363]]

Chk 8780 [[175, 303, 373, 474], [304, 2, 460, 223]]
Chk 8781 [[343, 85, 475, 406], [443, 77, 517, 323], [293, 90, 347, 167], [77, 97, 134, 196], [0, 70, 87, 251]]
Chk 8782 [[126, 251, 437, 547], [63, 215, 212, 390]]
Chk 8784 [[192, 51, 454, 374], [113, 84, 313, 370]]
Chk 8785 [[0, 200, 215, 420], [197, 138, 328, 323]]
Chk 8787 [[305, 132, 420, 378], [88, 202, 186, 561]]
Chk 8788 [[61, 1, 267, 374], [329, 67, 499, 288]]
Chk 8790 [[290, 21, 549, 397], [54, 71, 293, 365], [224, 0, 290, 157]]
Chk 8791 [[260, 88, 398, 316], [53, 45, 254, 287]]
Chk 8793 [[172, 103, 306, 460], [320, 63, 415, 383], [375, 95, 469, 345], [259, 101, 362, 390]]
Chk 8794 [[157, 110, 301, 422], [341, 120, 555, 422]]
Chk 8795 [[112, 26, 326, 425], [328, 101, 588, 426], [519, 58, 639, 417], [317, 61, 425, 426]]
Chk 8796 [[84, 19, 296, 284], [474, 49, 611, 283], [362, 112, 549, 280]]
Chk 8797 [[0, 134, 81, 419], [502, 127, 637, 418], [379, 91, 479, 289], [427, 60, 584, 400], [35, 86, 258, 418], [219, 114, 283, 252]]
Chk 8798 [[276, 166, 535, 447], [405, 159, 639, 505], [212, 76, 397, 436], [546, 2, 639, 207], [290, 0, 432, 227], [432, 0, 533, 166], [213, 80, 264, 134]]
Chk 8799 [[124, 85, 296, 479], [259, 78, 452, 470], [514, 167, 587, 385], [553, 59, 639, 479], [50, 164, 121, 397], [340, 22, 468, 361], [472, 188, 532, 353]]
Chk 8801 [[19, 42, 135, 292], [153, 11, 210, 89], [110, 44, 185, 208]]
Chk 8803 [[37, 147, 287, 416], [0, 52, 167, 437], [0, 44, 266, 445]]
Chk 8804 [[119, 75, 320, 443], [296, 1, 620, 331], [1, 40, 74, 382], [78, 15, 129, 70], [220, 24, 273, 95], [132, 10, 187, 78], [347, 104, 407, 209], [248, 1, 316, 88]]
Chk 8805 [[212, 1, 639, 421], [32, 82, 273, 382]]
Chk 8807 [[97, 173, 345, 415], [34, 152, 327, 340], [410, 156, 564, 386]]
Chk 8808 [[76, 0, 213, 176], [532, 0, 588, 106], [210, 2, 322, 173]]
Chk 8812 [[335, 44, 639, 421], [0, 0, 338, 424], [272, 153, 348, 220], [381, 153, 455, 223]]
Chk 8813 [[104, 36, 249, 437], [538, 148, 638, 391]]
Chk 8814 [[113, 24, 446, 533], [144, 195, 311, 553]]
Chk 8815 [[222, 60, 480, 473], [75, 122, 196, 398], [153, 78, 295, 479]]
Chk 8818 [[299, 236, 406, 478], [400, 264, 451, 398], [101, 283, 154, 379], [184, 269, 312, 478], [148, 259, 199, 398]]
Chk 8820 [[377, 126, 625, 377], [91, 149, 385, 422]]
Chk 8821 [[33, 212, 297, 368], [346, 212, 542, 371]]
Chk 8822 [[363, 215, 494, 490], [381, 391, 557, 637], [173, 40, 298, 225]]
Chk 8823 [[296, 52, 405, 426], [0, 154, 167, 473], [418, 111, 598, 455]]
Chk 8824 [[249, 192, 368, 318], [306, 308, 434, 425], [172, 264, 393, 425], [88, 190, 246, 420]]
Chk 8825 [[270, 0, 578, 469], [120, 22, 282, 382], [259, 19, 433, 395]]
Chk 8827 [[290, 5, 622, 465], [231, 75, 629, 454]]
Chk 8828 [[269, 0, 565, 584], [115, 136, 320, 564]]
Chk 8829 [[156, 76, 269, 368], [273, 81, 352, 361], [128, 208, 229, 370]]
Chk 8830 [[8, 94, 297, 422], [196, 52, 604, 422]]
Chk 8831 [[203, 64, 276, 292], [0, 63, 88, 303], [87, 94, 188, 329]]
Chk 8832 [[85, 94, 350, 480], [377, 185, 543, 367]]
Chk 8833 [[165, 88, 278, 268], [277, 103, 472, 310], [314, 128, 519, 351], [3, 129, 99, 279], [446, 155, 628, 353]]
Chk 8835 [[246, 104, 488, 385], [415, 215, 637, 416]]
Chk 8836 [[77, 8, 478, 390], [479, 3, 570, 231], [23, 87, 198, 247]]
Chk 8838 [[390, 116, 476, 322], [77, 30, 131, 179], [169, 108, 287, 337], [1, 107, 162, 374], [82, 109, 253, 373], [321, 100, 392, 241]]
Chk 8839 [[45, 51, 323, 369], [174, 19, 499, 375], [0, 0, 122, 150], [441, 91, 499, 217]]
Chk 8840 [[161, 110, 513, 426], [1, 130, 197, 403]]
Chk 8841 [[40, 78, 147, 340], [0, 0, 186, 461]]
Chk 8843 [[204, 113, 359, 553], [307, 112, 426, 468]]
Chk 8844 [[358, 114, 639, 427], [153, 82, 411, 432]]
Chk 8845 [[15, 175, 126, 365], [232, 250, 317, 391], [389, 195, 525, 430], [330, 256, 411, 401], [60, 18, 271, 302], [332, 191, 396, 315], [496, 85, 614, 467], [236, 199, 335, 293]]
Chk 8846 [[109, 17, 257, 316], [220, 64, 327, 268], [395, 10, 530, 307], [0, 154, 86, 315], [45, 146, 107, 207], [321, 59, 410, 271]]
Chk 8847 [[182, 134, 340, 418], [229, 117, 441, 416], [236, 285, 413, 420], [102, 165, 235, 400]]
Chk 8848 [[70, 145, 201, 387], [249, 284, 389, 472], [369, 321, 424, 448]]
Chk 8849 [[1, 65, 180, 473], [198, 35, 483, 479]]
Chk 8851 [[71, 89, 245, 623], [84, 383, 187, 630]]
Chk 8853 [[281, 36, 422, 385], [401, 71, 464, 275], [209, 82, 343, 306], [88, 99, 194, 286], [459, 86, 620, 319]]
Chk 8855 [[233, 135, 348, 407], [124, 112, 244, 409]]
Chk 8857 [[146, 101, 392, 632], [325, 112, 463, 632]]
Chk 8858 [[166, 122, 283, 574], [57, 123, 210, 630], [0, 210, 57, 330], [249, 107, 423, 633]]
Chk 8859 [[308, 158, 639, 480], [274, 135, 512, 475]]
Chk 8862 [[151, 188, 329, 395], [429, 154, 503, 237], [464, 184, 634, 309], [307, 127, 396, 221], [199, 129, 301, 216], [55, 144, 139, 314], [399, 197, 588, 391], [0, 187, 142, 447]]
Chk 8863 [[114, 116, 426, 639], [116, 82, 410, 632]]
Chk 8864 [[65, 37, 430, 494], [19, 77, 259, 499], [34, 333, 89, 424], [25, 347, 100, 499]]
Chk 8865 [[1, 0, 219, 441], [192, 81, 323, 281], [464, 70, 564, 479], [526, 104, 586, 420], [548, 36, 639, 479], [429, 106, 483, 212]]
Chk 8866 [[0, 75, 375, 374], [43, 184, 375, 369], [137, 12, 324, 83]]
Chk 8868 [[71, 101, 345, 426], [234, 55, 462, 354], [0, 0, 116, 131], [524, 0, 627, 82], [345, 55, 639, 425]]
Chk 8869 [[250, 86, 487, 415], [437, 154, 639, 420], [495, 84, 572, 218], [571, 96, 637, 235], [41, 65, 118, 227]]
Chk 8870 [[284, 60, 510, 420], [18, 65, 541, 417]]
Chk 8871 [[119, 146, 260, 382], [398, 194, 535, 394], [348, 271, 543, 384]]
Chk 8872 [[232, 38, 479, 633], [0, 147, 239, 637]]
Chk 8874 [[215, 144, 314, 472], [395, 140, 542, 479]]
Chk 8875 [[466, 172, 571, 254], [543, 152, 606, 249], [152, 190, 239, 450], [103, 114, 183, 232], [331, 134, 430, 252], [420, 152, 474, 228]]
Chk 8877 [[95, 17, 319, 418], [154, 88, 293, 399], [573, 160, 638, 285]]
Chk 8878 [[191, 55, 403, 253], [365, 18, 590, 318], [0, 0, 118, 296], [523, 108, 575, 180], [571, 116, 639, 220]]
Chk 8879 [[199, 45, 430, 543], [61, 67, 197, 489]]
Chk 8880 [[130, 50, 189, 250], [216, 29, 338, 332], [329, 55, 414, 284], [512, 27, 631, 331], [32, 49, 144, 332], [163, 61, 224, 256]]
Chk 8881 [[351, 25, 491, 372], [190, 36, 320, 379]]
Chk 8882 [[97, 45, 325, 479], [313, 100, 484, 474]]
Chk 8883 [[110, 93, 334, 370], [209, 28, 401, 368]]
Chk 8884 [[16, 123, 263, 425], [139, 104, 297, 425], [390, 25, 488, 334], [263, 89, 390, 349]]
Chk 8886 [[229, 48, 499, 370], [53, 124, 301, 367]]
Chk 8887 [[278, 119, 516, 418], [1, 113, 279, 421], [529, 215, 618, 419]]
Chk 8889 [[260, 40, 361, 305], [378, 72, 517, 289], [84, 102, 188, 325]]
Chk 8890 [[0, 248, 93, 426], [72, 219, 140, 339], [82, 248, 201, 420], [293, 236, 476, 421], [465, 230, 570, 426], [451, 198, 604, 371], [250, 222, 348, 316]]
Chk 8891 [[0, 4, 152, 393], [97, 40, 204, 313], [175, 94, 254, 283], [254, 140, 342, 282], [355, 118, 406, 284], [377, 95, 473, 288], [495, 43, 639, 305]]
Chk 8892 [[272, 168, 363, 352], [406, 172, 552, 479], [38, 168, 131, 415], [164, 184, 215, 262], [544, 177, 608, 308], [363, 148, 419, 275], [400, 162, 494, 275]]
Chk 8893 [[60, 171, 290, 597], [16, 134, 145, 394]]
Chk 8894 [[375, 31, 578, 479], [18, 79, 261, 479]]
Chk 8896 [[20, 0, 268, 397], [168, 106, 362, 408], [416, 243, 479, 416]]
Chk 8897 [[304, 141, 466, 414], [567, 259, 639, 420], [100, 155, 152, 242]]
Chk 8898 [[205, 27, 386, 423], [0, 119, 242, 425], [371, 114, 612, 426], [475, 137, 545, 259], [543, 160, 639, 425]]
Chk 8899 [[0, 153, 207, 473], [390, 155, 573, 397], [48, 123, 156, 284], [278, 94, 384, 221], [506, 136, 594, 309]]
Chk 8900 [[182, 77, 639, 422], [1, 0, 288, 421]]
Chk 8901 [[230, 18, 635, 422], [1, 23, 319, 405]]
Chk 8902 [[424, 117, 535, 366], [305, 122, 423, 365], [536, 84, 590, 221]]
Chk 8903 [[511, 117, 628, 262], [358, 79, 431, 216], [347, 127, 593, 423], [511, 107, 562, 193], [41, 44, 236, 297], [206, 64, 380, 254], [277, 132, 338, 236]]
Chk 8904 [[321, 83, 505, 393], [121, 127, 300, 345]]
Chk 8905 [[52, 0, 346, 356], [243, 110, 498, 314], [278, 0, 456, 249], [572, 0, 639, 100]]
Chk 8906 [[0, 1, 405, 426], [289, 0, 639, 427]]
Chk 8907 [[396, 60, 617, 424], [152, 45, 384, 424]]
Chk 8908 [[247, 96, 384, 375], [381, 52, 497, 420], [227, 132, 312, 332]]
Chk 8909 [[89, 145, 474, 426], [481, 30, 598, 414], [324, 31, 463, 299], [209, 70, 313, 382]]
Chk 8910 [[474, 105, 604, 421], [47, 117, 162, 422], [369, 75, 487, 365]]
Chk 8911 [[107, 151, 333, 431], [311, 125, 543, 431]]
Chk 8912 [[236, 225, 417, 595], [118, 262, 282, 568]]
Chk 8914 [[68, 0, 284, 402], [190, 87, 313, 351], [276, 0, 454, 245]]
Chk 8915 [[419, 159, 603, 444], [204, 145, 431, 451], [75, 156, 253, 453]]

Chk 8916 [[231, 92, 502, 473], [4, 52, 245, 479], [554, 62, 617, 170], [486, 62, 541, 187]]
Chk 8917 [[171, 118, 284, 372], [262, 119, 357, 370]]
Chk 8918 [[98, 111, 387, 531], [330, 32, 426, 416], [142, 20, 276, 142], [89, 41, 184, 244], [1, 49, 120, 438]]
Chk 8919 [[285, 122, 417, 473], [510, 145, 635, 473], [401, 162, 510, 379]]
Chk 8920 [[174, 96, 277, 381], [269, 81, 359, 367], [428, 140, 517, 376], [365, 124, 450, 385]]
Chk 8923 [[4, 144, 97, 261], [329, 146, 459, 532], [65, 98, 368, 554]]
Chk 8924 [[199, 21, 334, 278], [172, 100, 225, 326], [224, 3, 639, 447], [565, 164, 639, 321], [558, 208, 619, 263]]
Chk 8925 [[256, 146, 447, 629], [61, 186, 198, 639]]
Chk 8926 [[150, 136, 266, 419], [232, 101, 313, 377], [80, 131, 187, 401]]
Chk 8927 [[18, 150, 502, 425], [194, 100, 328, 453]]
Chk 8929 [[69, 69, 261, 443], [267, 111, 448, 401], [445, 73, 595, 410]]
Chk 8930 [[161, 0, 392, 193], [0, 14, 463, 479], [497, 3, 639, 175]]
Chk 8931 [[228, 12, 475, 468], [80, 0, 221, 127], [419, 1, 519, 118], [432, 59, 598, 311], [545, 39, 619, 155], [409, 25, 517, 148], [160, 34, 234, 131], [341, 0, 428, 143]]
Chk 8932 [[186, 122, 324, 353], [306, 250, 451, 409], [386, 206, 577, 416]]
Chk 8934 [[90, 102, 209, 388], [283, 159, 395, 342]]
Chk 8935 [[315, 170, 625, 479], [17, 144, 183, 367], [416, 135, 475, 306], [240, 112, 431, 339], [461, 126, 520, 179]]
Chk 8936 [[0, 195, 205, 395], [418, 191, 486, 280], [551, 208, 605, 272], [437, 77, 491, 130], [228, 62, 517, 388], [461, 197, 522, 252]]
Chk 8937 [[61, 234, 142, 564], [133, 228, 304, 623]]
Chk 8938 [[171, 78, 419, 334], [51, 170, 302, 364], [345, 104, 399, 165], [266, 38, 319, 121], [405, 72, 459, 164], [114, 33, 175, 98], [311, 182, 605, 386]]
Chk 8941 [[0, 172, 70, 363], [56, 157, 292, 582], [264, 177, 421, 590]]
Chk 8942 [[297, 24, 503, 344], [132, 99, 290, 276], [36, 110, 147, 264], [427, 8, 602, 401]]
Chk 8943 [[313, 217, 467, 382], [397, 142, 470, 313], [451, 194, 598, 399]]
Chk 8945 [[200, 125, 491, 502], [76, 165, 276, 493], [340, 533, 449, 639], [24, 536, 216, 630]]
Chk 8946 [[338, 49, 482, 473], [9, 33, 245, 426], [0, 13, 146, 479], [442, 58, 596, 475]]
Chk 8949 [[209, 26, 371, 375], [398, 17, 540, 80], [492, 0, 572, 81], [110, 82, 205, 350], [193, 16, 291, 73], [322, 14, 403, 77], [274, 0, 351, 60], [44, 8, 104, 64], [404, 120, 529, 376], [568, 1, 639, 82], [404, 0, 460, 59], [324, 0, 408, 62]]
Chk 8950 [[142, 0, 336, 421], [432, 40, 524, 319], [337, 20, 450, 220], [522, 46, 630, 357], [576, 36, 639, 281], [11, 40, 247, 421], [380, 196, 442, 290]]
Chk 8951 [[472, 10, 638, 420], [209, 55, 378, 426], [0, 123, 105, 426], [44, 62, 208, 425]]
Chk 8952 [[0, 26, 209, 427], [524, 149, 639, 417], [424, 132, 622, 427]]
Chk 8954 [[181, 188, 311, 423], [291, 173, 358, 418], [427, 148, 552, 422]]
Chk 8958 [[214, 98, 366, 333], [150, 118, 276, 328]]
Chk 8959 [[0, 30, 263, 419], [145, 114, 326, 328], [320, 20, 639, 393]]
Chk 8960 [[225, 0, 639, 422], [229, 1, 444, 276], [0, 22, 184, 252], [498, 85, 633, 167], [483, 114, 604, 260]]
Chk 8962 [[134, 83, 336, 382], [275, 139, 416, 381]]
Chk 8964 [[286, 130, 406, 325], [203, 145, 316, 321], [400, 5, 466, 291]]
Chk 8967 [[164, 154, 292, 567], [95, 222, 217, 561]]
Chk 8968 [[148, 14, 287, 314], [431, 143, 490, 226], [54, 10, 173, 296], [0, 167, 72, 261]]
Chk 8969 [[435, 35, 556, 397], [210, 101, 370, 445]]
Chk 8971 [[83, 4, 324, 531], [131, 93, 426, 541]]
Chk 8972 [[240, 88, 395, 294], [0, 74, 162, 354], [461, 50, 638, 209]]
Chk 8973 [[340, 43, 545, 430], [63, 30, 149, 352]]
Chk 8974 [[340, 93, 499, 460], [2, 30, 157, 308], [212, 153, 442, 470]]
Chk 8975 [[58, 4, 494, 479], [304, 4, 639, 473]]
Chk 8976 [[123, 156, 290, 496], [278, 199, 385, 567], [34, 143, 170, 399]]
Chk 8977 [[1, 172, 274, 630], [181, 84, 423, 629]]
Chk 8978 [[113, 83, 273, 421], [52, 43, 155, 420]]
Chk 8981 [[94, 0, 367, 359], [343, 37, 444, 267], [503, 20, 639, 306], [404, 70, 478, 263], [0, 137, 64, 375]]
Chk 8983 [[80, 40, 179, 254], [163, 77, 266, 243], [253, 56, 363, 274]]
Chk 8985 [[390, 171, 512, 358], [250, 188, 374, 364], [118, 188, 264, 380]]
Chk 8986 [[241, 168, 360, 397], [73, 222, 220, 444], [388, 126, 447, 257]]
Chk 8988 [[282, 55, 468, 270], [0, 103, 80, 332], [477, 106, 639, 342]]
Chk 8989 [[298, 196, 429, 397], [390, 137, 627, 418], [343, 101, 496, 272]]
Chk 8990 [[419, 157, 638, 347], [329, 318, 639, 455], [1, 200, 185, 455], [102, 141, 209, 296], [214, 131, 302, 230], [58, 179, 184, 342], [460, 138, 521, 203], [171, 140, 278, 247]]
Chk 8991 [[362, 108, 441, 177], [394, 138, 639, 420], [69, 17, 390, 418], [145, 291, 246, 409], [498, 305, 568, 411], [420, 272, 568, 413]]
Chk 8995 [[0, 59, 256, 269], [233, 15, 413, 248], [398, 45, 499, 249]]
Chk 8996 [[194, 17, 425, 415], [513, 116, 609, 300], [400, 91, 543, 363], [2, 3, 266, 474], [380, 98, 435, 187]]
Chk 8997 [[516, 154, 639, 478], [143, 225, 486, 470], [0, 170, 153, 474]]
Chk 8998 [[261, 133, 544, 472], [145, 165, 198, 229], [26, 119, 309, 473], [469, 152, 560, 387], [25, 189, 109, 340], [83, 181, 145, 239], [0, 141, 79, 479]]
Chk 8999 [[346, 84, 639, 479], [478, 298, 639, 479], [389, 287, 467, 479]]
Chk 9000 [[366, 110, 637, 439], [0, 13, 370, 445]]
Chk 9001 [[88, 137, 244, 424], [159, 207, 533, 419]]
Chk 9002 [[62, 104, 253, 465], [142, 330, 334, 494], [310, 346, 393, 499]]
Chk 9003 [[331, 24, 450, 402], [272, 196, 414, 409], [56, 26, 198, 449], [402, 138, 568, 422]]
Chk 9004 [[262, 16, 395, 236], [424, 0, 488, 129], [77, 349, 185, 464], [72, 0, 153, 95], [283, 170, 473, 472], [370, 183, 556, 436], [184, 0, 244, 78]]
Chk 9005 [[351, 13, 463, 265], [110, 34, 276, 264]]
Chk 9006 [[468, 82, 543, 374], [36, 71, 154, 409], [404, 92, 483, 362], [565, 93, 624, 251], [140, 47, 255, 382]]
Chk 9007 [[2, 57, 170, 418], [314, 41, 464, 423], [451, 46, 628, 420], [165, 40, 325, 424]]
Chk 9009 [[210, 326, 329, 598], [111, 308, 247, 607]]
Chk 9010 [[167, 184, 311, 510], [79, 209, 191, 541]]
Chk 9011 [[191, 100, 336, 504], [27, 115, 256, 501], [348, 76, 619, 511], [495, 160, 565, 242]]
Chk 9012 [[252, 242, 408, 621], [148, 98, 265, 522], [3, 145, 196, 533]]
Chk 9014 [[229, 108, 423, 312], [342, 120, 479, 421], [477, 66, 634, 421], [9, 94, 350, 426]]
Chk 9015 [[162, 34, 398, 358], [192, 238, 443, 473], [396, 18, 637, 472], [13, 40, 179, 235], [1, 148, 174, 471], [251, 0, 398, 70]]
Chk 9016 [[382, 82, 639, 427], [0, 84, 92, 456], [248, 49, 439, 358], [31, 61, 369, 452]]
Chk 9018 [[207, 152, 310, 327], [306, 165, 399, 345], [410, 178, 539, 388], [81, 140, 179, 475], [167, 250, 225, 389], [0, 210, 70, 370], [0, 317, 223, 474]]
Chk 9020 [[18, 79, 131, 426], [225, 149, 361, 365], [367, 158, 478, 360], [473, 156, 566, 344], [142, 173, 246, 383]]
Chk 9021 [[229, 112, 297, 379], [286, 126, 355, 366], [102, 41, 237, 459], [16, 124, 112, 378]]
Chk 9023 [[2, 1, 263, 472], [355, 123, 593, 478]]
Chk 9024 [[151, 153, 405, 627], [341, 198, 614, 639], [38, 120, 102, 257]]
Chk 9026 [[109, 74, 270, 331], [285, 62, 468, 331]]
Chk 9027 [[192, 2, 424, 554], [64, 69, 256, 629]]
Chk 9028 [[54, 3, 245, 343], [182, 100, 485, 361], [0, 40, 51, 160]]
Chk 9029 [[2, 100, 175, 383], [409, 120, 600, 422], [310, 40, 362, 113], [520, 60, 603, 174], [247, 91, 365, 285]]
Chk 9031 [[44, 51, 343, 584], [507, 0, 567, 86], [337, 53, 535, 609], [505, 231, 571, 301], [550, 194, 617, 301], [550, 0, 635, 97], [505, 157, 571, 280], [378, 26, 431, 115], [317, 225, 383, 286], [15, 19, 115, 122], [433, 9, 489, 75]]
Chk 9033 [[345, 73, 583, 499], [124, 74, 357, 502]]
Chk 9034 [[148, 0, 485, 313], [162, 33, 313, 258]]
Chk 9035 [[1, 114, 276, 367], [191, 41, 443, 369], [246, 20, 334, 118], [358, 0, 486, 202]]
Chk 9039 [[11, 109, 223, 353], [199, 179, 406, 358], [345, 86, 399, 166], [240, 72, 335, 206], [329, 64, 559, 378]]
Chk 9040 [[292, 11, 631, 412], [0, 18, 326, 410]]
Chk 9041 [[103, 38, 292, 471], [346, 33, 559, 474]]
Chk 9042 [[431, 115, 551, 352], [284, 135, 509, 385]]
Chk 9043 [[299, 70, 434, 446], [401, 101, 459, 315], [165, 98, 338, 472], [149, 163, 210, 303], [485, 149, 605, 473], [447, 387, 545, 471]]
Chk 9045 [[48, 34, 411, 630], [290, 81, 470, 639], [0, 3, 160, 401]]
Chk 9047 [[44, 87, 390, 330], [350, 13, 499, 219], [193, 9, 305, 136], [332, 0, 424, 181]]
Chk 9050 [[189, 127, 328, 358], [524, 3, 639, 361]]
Chk 9051 [[201, 59, 377, 424], [160, 254, 338, 424]]
Chk 9054 [[106, 38, 345, 294], [331, 55, 518, 310]]
Chk 9055 [[1, 144, 287, 475], [398, 1, 639, 469]]

Chk 9058 [[128, 184, 271, 632], [273, 146, 477, 639], [247, 250, 310, 425], [104, 196, 170, 279], [74, 283, 147, 556], [72, 212, 137, 281], [118, 264, 182, 316]]
Chk 9059 [[102, 144, 269, 579], [61, 225, 240, 629]]
Chk 9060 [[142, 16, 353, 381], [314, 75, 579, 340], [448, 48, 553, 189], [0, 169, 92, 337], [517, 85, 639, 204]]
Chk 9061 [[230, 162, 366, 466], [130, 198, 202, 476], [388, 203, 491, 474], [441, 189, 582, 473]]
Chk 9062 [[264, 160, 368, 278], [408, 163, 487, 274], [277, 174, 639, 478], [2, 195, 278, 474], [166, 159, 278, 306], [407, 186, 541, 377]]
Chk 9063 [[254, 3, 487, 421], [1, 56, 233, 348]]
Chk 9064 [[217, 139, 307, 395], [295, 131, 378, 393], [352, 145, 430, 400]]
Chk 9065 [[328, 31, 506, 440], [119, 67, 355, 451]]
Chk 9066 [[357, 109, 462, 411], [400, 233, 639, 434], [56, 179, 121, 275]]
Chk 9068 [[310, 134, 377, 373], [88, 110, 174, 367], [315, 124, 445, 369], [263, 143, 340, 319], [186, 148, 260, 317]]
Chk 9069 [[494, 55, 639, 474], [0, 50, 181, 472]]
Chk 9070 [[18, 65, 289, 639], [239, 77, 501, 625]]
Chk 9072 [[155, 194, 399, 473], [0, 182, 156, 479], [400, 20, 520, 311], [287, 103, 350, 228], [343, 16, 400, 79]]
Chk 9073 [[402, 2, 509, 263], [105, 229, 286, 418], [174, 39, 240, 193], [48, 46, 118, 192]]
Chk 9074 [[375, 50, 610, 349], [345, 113, 419, 225], [0, 211, 271, 426], [144, 70, 318, 242]]
Chk 9075 [[133, 173, 299, 441], [135, 150, 287, 226], [345, 167, 528, 451]]
Chk 9076 [[333, 148, 460, 349], [481, 74, 600, 361], [306, 147, 377, 254], [436, 81, 529, 282], [576, 0, 639, 111], [240, 196, 298, 254], [16, 9, 181, 365]]
Chk 9077 [[283, 197, 380, 361], [343, 203, 448, 388], [317, 257, 482, 472], [0, 240, 176, 439], [129, 160, 214, 302]]
Chk 9078 [[145, 122, 204, 306], [64, 109, 135, 313], [0, 108, 68, 316], [19, 116, 74, 317], [263, 125, 315, 285], [240, 50, 410, 307], [392, 10, 479, 394]]
Chk 9081 [[358, 224, 516, 405], [265, 232, 365, 369], [352, 162, 470, 290], [527, 221, 624, 328], [135, 239, 186, 330], [52, 232, 151, 428], [170, 248, 231, 398], [365, 145, 449, 215], [0, 247, 120, 479], [98, 235, 155, 340]]
Chk 9082 [[182, 137, 381, 471], [21, 110, 440, 472]]
Chk 9085 [[112, 193, 337, 590], [150, 16, 341, 521]]
Chk 9086 [[229, 195, 346, 479], [80, 217, 209, 477], [329, 168, 437, 472]]
Chk 9088 [[244, 67, 367, 272], [306, 31, 513, 313], [504, 71, 579, 268], [173, 84, 312, 300], [333, 48, 412, 305], [93, 94, 166, 238], [1, 96, 71, 267]]
Chk 9090 [[447, 81, 639, 426], [87, 125, 226, 308], [260, 92, 426, 259]]
Chk 9091 [[322, 415, 431, 639], [172, 220, 353, 522]]
Chk 9092 [[240, 91, 477, 330], [205, 96, 317, 333], [168, 114, 245, 210], [159, 100, 250, 269]]
Chk 9093 [[391, 77, 554, 325], [272, 73, 416, 310]]
Chk 9094 [[263, 167, 493, 416], [18, 0, 242, 423], [148, 0, 290, 416], [243, 32, 390, 347], [430, 117, 501, 287], [585, 156, 639, 212]]
Chk 9096 [[153, 123, 354, 492], [14, 5, 145, 462]]
Chk 9097 [[284, 71, 426, 426], [139, 74, 305, 419], [438, 56, 520, 426], [368, 6, 631, 426], [1, 86, 236, 426]]
Chk 9099 [[153, 245, 259, 600], [222, 225, 306, 548]]
Chk 9100 [[303, 165, 472, 324], [232, 158, 288, 256], [105, 175, 174, 256], [185, 107, 380, 326], [494, 141, 604, 320]]
Chk 9103 [[158, 16, 378, 304], [83, 146, 608, 511]]
Chk 9105 [[173, 68, 281, 363], [280, 30, 422, 368], [1, 51, 181, 369], [398, 135, 581, 388]]
Chk 9106 [[54, 2, 340, 438], [278, 16, 504, 434]]
Chk 9108 [[303, 137, 508, 392], [19, 98, 189, 479]]
Chk 9109 [[0, 36, 391, 422], [230, 116, 292, 187], [523, 68, 626, 376], [264, 32, 536, 420], [580, 53, 633, 134], [417, 100, 483, 291]]
Chk 9110 [[315, 40, 497, 308], [269, 33, 320, 148], [4, 23, 96, 208], [247, 8, 394, 306]]
Chk 9111 [[173, 12, 374, 396], [1, 48, 170, 489], [156, 128, 247, 201], [217, 150, 291, 296]]
Chk 9112 [[213, 131, 323, 337], [307, 113, 458, 441], [388, 32, 599, 471]]
Chk 9113 [[83, 190, 204, 394], [375, 114, 534, 376], [555, 165, 607, 275], [364, 189, 417, 272], [177, 238, 304, 383]]
Chk 9114 [[232, 108, 571, 559], [6, 121, 242, 507]]
Chk 9116 [[301, 142, 444, 425], [429, 200, 588, 421]]
Chk 9117 [[424, 29, 639, 421], [73, 0, 494, 429]]
Chk 9120 [[49, 49, 327, 414], [337, 96, 610, 419]]
Chk 9121 [[62, 133, 240, 638], [239, 163, 336, 518], [158, 146, 453, 483], [175, 149, 241, 318], [348, 149, 400, 318], [0, 168, 54, 277], [41, 131, 110, 288]]
Chk 9123 [[89, 108, 412, 471], [554, 173, 639, 263], [424, 199, 495, 259], [503, 239, 638, 479], [251, 0, 309, 170]]
Chk 9124 [[287, 10, 472, 189], [350, 115, 429, 223], [427, 51, 528, 258], [0, 115, 185, 430], [448, 88, 625, 431]]
Chk 9125 [[221, 30, 388, 488], [363, 69, 451, 451], [123, 55, 228, 437]]
Chk 9128 [[351, 70, 498, 402], [550, 126, 622, 257], [244, 125, 313, 256], [33, 73, 178, 402]]
Chk 9129 [[115, 97, 255, 413], [256, 83, 389, 420], [383, 113, 519, 419]]
Chk 9131 [[19, 129, 214, 391], [332, 129, 521, 389], [184, 30, 259, 147], [493, 30, 564, 155]]
Chk 9133 [[0, 2, 308, 312], [281, 3, 493, 263]]
Chk 9134 [[165, 137, 397, 476], [151, 101, 296, 411]]
Chk 9136 [[1, 358, 263, 553], [1, 1, 147, 249], [145, 4, 353, 249], [281, 62, 338, 152], [325, 58, 464, 237]]
Chk 9137 [[151, 106, 271, 388], [416, 1, 639, 413]]
Chk 9138 [[275, 41, 409, 336], [394, 235, 627, 473]]
Chk 9140 [[151, 71, 391, 615], [6, 63, 388, 611]]
Chk 9141 [[187, 142, 375, 639], [34, 139, 235, 639]]
Chk 9143 [[326, 151, 421, 417], [1, 184, 170, 579], [108, 221, 284, 391], [0, 543, 173, 638], [179, 229, 244, 334]]
Chk 9144 [[225, 52, 407, 385], [1, 4, 281, 475], [212, 93, 312, 207]]
Chk 9145 [[33, 97, 185, 328], [227, 154, 345, 328], [357, 58, 474, 332]]
Chk 9146 [[217, 6, 361, 273], [199, 24, 350, 309]]
Chk 9147 [[139, 58, 284, 599], [70, 254, 198, 600]]
Chk 9148 [[78, 94, 304, 475], [337, 112, 574, 479]]
Chk 9149 [[155, 21, 366, 362], [289, 67, 632, 383]]
Chk 9150 [[242, 57, 639, 479], [190, 1, 522, 273]]
Chk 9151 [[295, 201, 472, 631], [79, 202, 193, 540], [0, 159, 66, 399]]
Chk 9153 [[150, 15, 460, 373], [46, 91, 109, 208], [210, 88, 376, 381]]
Chk 9154 [[270, 95, 408, 473], [380, 58, 583, 475], [75, 74, 241, 473]]
Chk 9157 [[13, 56, 249, 473], [153, 116, 274, 345], [291, 106, 487, 479], [340, 71, 638, 474], [236, 114, 337, 479], [216, 134, 273, 241]]
Chk 9158 [[227, 196, 331, 472], [134, 212, 215, 474]]
Chk 9159 [[63, 104, 255, 386], [258, 96, 502, 397], [442, 33, 548, 358], [175, 69, 406, 381]]
Chk 9161 [[252, 339, 343, 615], [328, 267, 390, 569]]
Chk 9162 [[167, 222, 327, 419], [0, 277, 100, 419], [569, 242, 639, 424], [380, 225, 576, 425]]
Chk 9163 [[535, 101, 598, 220], [434, 127, 485, 221], [394, 74, 447, 165], [245, 117, 302, 200], [282, 116, 364, 205], [341, 140, 401, 340], [463, 103, 567, 426]]
Chk 9164 [[71, 94, 222, 418], [288, 199, 354, 360], [282, 76, 407, 370], [388, 149, 451, 252], [490, 106, 557, 258]]
Chk 9165 [[2, 0, 349, 420], [375, 2, 639, 431]]
Chk 9166 [[220, 251, 399, 632], [165, 257, 274, 610]]
Chk 9167 [[77, 73, 224, 423], [222, 106, 327, 424], [323, 87, 442, 431], [417, 122, 568, 422]]
Chk 9168 [[255, 48, 587, 417], [17, 20, 371, 425]]
Chk 9169 [[194, 56, 393, 248], [38, 39, 183, 358]]
Chk 9170 [[271, 232, 449, 414], [193, 97, 355, 348], [446, 177, 599, 432]]
Chk 9171 [[1, 363, 97, 479], [209, 113, 351, 350], [100, 189, 276, 456], [428, 93, 539, 363], [75, 52, 139, 187]]
Chk 9172 [[218, 174, 358, 630], [136, 173, 239, 622]]
Chk 9173 [[205, 159, 348, 423], [63, 141, 190, 425]]
Chk 9175 [[312, 102, 504, 452], [334, 192, 469, 465], [155, 86, 207, 220]]
Chk 9176 [[545, 139, 633, 393], [104, 105, 453, 598], [164, 139, 237, 327], [62, 133, 139, 259], [214, 122, 272, 269], [399, 120, 563, 372]]
Chk 9177 [[295, 93, 473, 331], [4, 183, 159, 354], [190, 97, 246, 236], [283, 88, 346, 231]]
Chk 9178 [[211, 85, 333, 384], [43, 65, 251, 413]]
Chk 9179 [[341, 70, 536, 470], [0, 155, 235, 472]]
Chk 9180 [[217, 96, 414, 354], [180, 39, 332, 354], [434, 138, 504, 320]]
Chk 9181 [[52, 57, 224, 466], [206, 63, 320, 261]]
Chk 9183 [[0, 131, 354, 472], [320, 120, 596, 427]]
Chk 9184 [[0, 82, 143, 479], [431, 118, 639, 472], [345, 94, 509, 473], [154, 96, 306, 272]]
Chk 9186 [[10, 165, 145, 420], [264, 144, 378, 382], [167, 182, 241, 351], [99, 157, 195, 374], [444, 97, 531, 424], [361, 135, 433, 337]]
Chk 9188 [[297, 219, 520, 474], [510, 173, 633, 456]]
Chk 9189 [[242, 79, 510, 395], [44, 51, 162, 321], [18, 60, 346, 412]]
Chk 9190 [[50, 91, 211, 400], [238, 134, 345, 417], [323, 169, 446, 395], [381, 197, 515, 474], [482, 202, 561, 431]]
Chk 9191 [[132, 6, 216, 166], [199, 18, 258, 219], [349, 27, 443, 264], [237, 0, 324, 259]]
Chk 9192 [[136, 105, 283, 340], [168, 141, 443, 466]]
Chk 9193 [[145, 142, 298, 442], [304, 138, 479, 442], [418, 160, 496, 449], [208, 146, 269, 270]]

Chk 9194 [[173, 80, 479, 629], [324, 25, 459, 216], [123, 2, 282, 206], [18, 32, 150, 211], [195, 47, 251, 103], [287, 38, 351, 150]]
Chk 9195 [[186, 121, 368, 331], [136, 90, 216, 303], [426, 244, 499, 332], [22, 106, 138, 326]]
Chk 9198 [[225, 128, 351, 368], [79, 172, 227, 369]]
Chk 9199 [[0, 123, 273, 424], [418, 75, 591, 270], [365, 210, 627, 418], [133, 96, 408, 376]]
Chk 9200 [[166, 57, 352, 400], [137, 88, 264, 288]]
Chk 9202 [[286, 59, 558, 470], [259, 31, 420, 395]]
Chk 9203 [[95, 172, 250, 597], [212, 123, 430, 505]]
Chk 9204 [[47, 280, 202, 485], [32, 56, 204, 292]]
Chk 9205 [[2, 77, 144, 486], [130, 45, 295, 481], [429, 16, 548, 356], [241, 19, 366, 411]]
Chk 9208 [[140, 128, 265, 582], [179, 95, 403, 592]]
Chk 9209 [[157, 209, 342, 478], [0, 2, 156, 479], [347, 303, 627, 473], [132, 244, 192, 336]]
Chk 9212 [[163, 113, 306, 601], [76, 148, 193, 589], [313, 139, 475, 576], [265, 98, 377, 551]]
Chk 9213 [[143, 118, 278, 286], [1, 143, 214, 420], [529, 273, 639, 419], [381, 46, 529, 329], [467, 140, 623, 399], [311, 139, 388, 265], [0, 333, 59, 426]]
Chk 9214 [[0, 64, 270, 479], [329, 3, 507, 314], [461, 157, 638, 478], [44, 2, 349, 421]]
Chk 9216 [[0, 133, 213, 408], [179, 66, 320, 371], [368, 265, 638, 355], [410, 17, 623, 260]]
Chk 9217 [[161, 142, 335, 291], [323, 108, 525, 241]]
Chk 9218 [[320, 3, 409, 129], [467, 7, 639, 212], [1, 0, 115, 87], [0, 294, 156, 613], [406, 1, 502, 160], [115, 0, 243, 106]]
Chk 9219 [[25, 7, 312, 421], [360, 38, 618, 419], [58, 2, 184, 113]]
Chk 9221 [[438, 56, 638, 345], [25, 70, 208, 343], [279, 0, 370, 127], [196, 143, 422, 341], [26, 0, 115, 247]]
Chk 9222 [[31, 39, 265, 608], [274, 80, 493, 533]]
Chk 9223 [[64, 198, 207, 396], [46, 5, 150, 304], [0, 0, 70, 304], [140, 12, 210, 217], [357, 0, 438, 284], [586, 1, 639, 216], [245, 3, 323, 244], [224, 191, 296, 391]]
Chk 9225 [[101, 9, 356, 633], [4, 3, 164, 640], [327, 66, 426, 245], [0, 14, 56, 189], [236, 89, 293, 175]]
Chk 9226 [[380, 31, 533, 325], [119, 48, 264, 379]]
Chk 9227 [[87, 198, 270, 572], [204, 165, 335, 567], [147, 223, 220, 466]]
Chk 9228 [[73, 16, 427, 607], [308, 4, 611, 604]]
Chk 9229 [[87, 252, 219, 566], [192, 211, 314, 579], [306, 151, 479, 596]]
Chk 9230 [[35, 161, 161, 495], [175, 76, 294, 436], [90, 348, 300, 639]]
Chk 9231 [[294, 49, 476, 369], [285, 52, 361, 210], [0, 47, 141, 371], [93, 89, 200, 375]]
Chk 9232 [[180, 151, 305, 328], [15, 142, 135, 328], [336, 140, 443, 285]]
Chk 9234 [[307, 70, 604, 326], [49, 91, 311, 425], [298, 60, 411, 285]]
Chk 9235 [[104, 187, 333, 332], [208, 75, 405, 309]]
Chk 9236 [[74, 231, 340, 612], [242, 59, 368, 516]]
Chk 9238 [[0, 56, 269, 382], [0, 32, 70, 289], [414, 59, 577, 417], [171, 139, 326, 392]]
Chk 9239 [[272, 270, 342, 543], [208, 317, 280, 581], [127, 267, 231, 561]]
Chk 9240 [[68, 149, 227, 350], [1, 184, 268, 479]]
Chk 9242 [[77, 63, 189, 330], [347, 25, 516, 331]]
Chk 9243 [[123, 11, 280, 574], [13, 76, 260, 610]]
Chk 9244 [[312, 11, 544, 330], [0, 83, 108, 425]]
Chk 9245 [[272, 102, 488, 370], [0, 9, 251, 369]]
Chk 9246 [[103, 333, 319, 633], [244, 170, 415, 377]]
Chk 9250 [[440, 140, 639, 295], [421, 93, 547, 229], [458, 0, 590, 138], [326, 31, 395, 125], [250, 112, 414, 245], [227, 7, 346, 225], [13, 109, 239, 291]]
Chk 9251 [[305, 20, 500, 299], [130, 125, 265, 246], [0, 167, 115, 424]]
Chk 9252 [[336, 109, 588, 479], [73, 173, 306, 435]]
Chk 9253 [[111, 112, 346, 328], [268, 138, 479, 576]]
Chk 9255 [[46, 65, 253, 474], [361, 4, 636, 472], [229, 47, 450, 473], [422, 83, 480, 167]]
Chk 9256 [[143, 170, 314, 461], [131, 204, 219, 481]]
Chk 9257 [[14, 239, 166, 450], [115, 263, 252, 349], [322, 188, 491, 424]]
Chk 9259 [[11, 293, 304, 639], [79, 149, 297, 402]]
Chk 9260 [[218, 141, 341, 407], [195, 97, 366, 318], [354, 115, 507, 402], [336, 108, 440, 274]]
Chk 9261 [[26, 64, 161, 330], [122, 50, 177, 160], [113, 121, 262, 490], [321, 262, 374, 495], [277, 148, 330, 233]]
Chk 9262 [[159, 35, 487, 453], [426, 7, 639, 324], [586, 120, 639, 242]]
Chk 9263 [[194, 79, 424, 479], [347, 0, 529, 473], [489, 214, 621, 477], [1, 33, 214, 471]]
Chk 9264 [[243, 61, 607, 427], [76, 38, 281, 423]]
Chk 9265 [[180, 85, 575, 378], [404, 90, 639, 376], [518, 49, 608, 309], [383, 47, 497, 224], [0, 46, 104, 413], [126, 96, 271, 382], [389, 38, 456, 174], [331, 278, 464, 379]]
Chk 9267 [[236, 16, 337, 218], [101, 93, 245, 330], [324, 0, 472, 130], [69, 0, 144, 141], [413, 150, 499, 332]]
Chk 9269 [[343, 49, 488, 420], [67, 36, 260, 273], [0, 104, 86, 269]]
Chk 9272 [[236, 114, 455, 418], [127, 126, 291, 425]]
Chk 9273 [[78, 64, 278, 473], [247, 45, 506, 479]]
Chk 9274 [[312, 50, 427, 338], [191, 59, 265, 315], [102, 30, 205, 324], [251, 39, 331, 318]]
Chk 9276 [[40, 85, 205, 498], [5, 119, 94, 445], [224, 46, 339, 209]]
Chk 9277 [[151, 135, 279, 386], [426, 192, 493, 268], [527, 193, 639, 402], [240, 164, 355, 260]]
Chk 9278 [[128, 107, 423, 462], [134, 277, 202, 376], [9, 129, 116, 444], [304, 64, 360, 133], [261, 44, 624, 453], [160, 226, 220, 299], [554, 294, 633, 365]]
Chk 9280 [[187, 199, 340, 366], [15, 79, 164, 359], [518, 87, 625, 375]]
Chk 9281 [[51, 67, 335, 477], [234, 79, 600, 473]]
Chk 9282 [[19, 46, 295, 295], [190, 190, 563, 580]]
Chk 9283 [[2, 1, 261, 629], [88, 243, 170, 502], [247, 159, 400, 532], [199, 163, 250, 243]]
Chk 9284 [[399, 168, 499, 396], [239, 172, 333, 457]]
Chk 9285 [[436, 207, 622, 348], [263, 193, 446, 364], [321, 191, 382, 303], [100, 115, 263, 329]]
Chk 9286 [[247, 74, 416, 374], [453, 206, 630, 416]]
Chk 9288 [[0, 115, 268, 585], [289, 6, 639, 579], [42, 17, 151, 123]]
Chk 9289 [[197, 17, 473, 421], [0, 59, 209, 421], [391, 66, 639, 426]]
Chk 9290 [[267, 59, 577, 414], [231, 28, 376, 258], [402, 18, 456, 109], [225, 53, 311, 231], [71, 31, 293, 291], [171, 38, 258, 194]]
Chk 9291 [[113, 241, 249, 421], [173, 200, 250, 374], [236, 165, 390, 363]]
Chk 9292 [[248, 208, 390, 406], [139, 226, 260, 515], [310, 212, 452, 334], [111, 199, 198, 359], [425, 218, 634, 515], [4, 212, 112, 504]]
Chk 9293 [[195, 96, 453, 364], [0, 27, 112, 371]]
Chk 9294 [[181, 98, 401, 371], [453, 169, 639, 358]]
Chk 9296 [[134, 91, 374, 499], [0, 197, 158, 420], [133, 145, 229, 323]]
Chk 9297 [[60, 60, 229, 369], [159, 62, 277, 253], [396, 174, 566, 443]]
Chk 9298 [[297, 48, 473, 304], [414, 108, 552, 273], [54, 75, 310, 464], [1, 217, 159, 472]]
Chk 9299 [[130, 185, 213, 418], [264, 183, 504, 426]]
Chk 9300 [[112, 83, 287, 391], [312, 142, 476, 449], [471, 146, 639, 452], [0, 164, 125, 457], [582, 138, 639, 453], [189, 99, 359, 457]]
Chk 9301 [[322, 78, 586, 459], [22, 119, 216, 472]]
Chk 9302 [[0, 102, 159, 446], [102, 146, 284, 550]]
Chk 9303 [[308, 218, 512, 479], [30, 63, 295, 479], [0, 50, 125, 479]]
Chk 9304 [[158, 339, 449, 632], [64, 128, 122, 345], [241, 100, 345, 401], [110, 126, 186, 391]]
Chk 9305 [[87, 44, 324, 471], [1, 42, 162, 491]]
Chk 9306 [[307, 139, 543, 426], [150, 93, 320, 426]]
Chk 9308 [[230, 19, 358, 415], [156, 67, 290, 420]]
Chk 9309 [[1, 102, 292, 632], [219, 64, 426, 614]]
Chk 9310 [[92, 204, 167, 357], [31, 267, 92, 374], [296, 190, 408, 359], [485, 173, 581, 479], [537, 166, 616, 425], [236, 195, 311, 299]]
Chk 9312 [[364, 159, 623, 532], [72, 150, 263, 528]]
Chk 9314 [[387, 175, 556, 438], [534, 115, 639, 359], [0, 57, 293, 442]]
Chk 9317 [[131, 4, 324, 484], [277, 1, 372, 445]]
Chk 9320 [[170, 180, 372, 601], [43, 37, 235, 561]]
Chk 9321 [[410, 139, 639, 426], [119, 69, 264, 385], [330, 288, 519, 422], [136, 41, 381, 421], [371, 179, 424, 255], [0, 165, 70, 273], [545, 169, 605, 248]]
Chk 9322 [[317, 89, 639, 389], [230, 87, 330, 286], [127, 158, 305, 335], [0, 7, 323, 469]]
Chk 9324 [[22, 107, 147, 473], [186, 151, 316, 471], [435, 113, 582, 472]]
Chk 9325 [[1, 110, 224, 355], [0, 43, 240, 144]]
Chk 9327 [[126, 51, 461, 479], [379, 94, 638, 471], [0, 31, 287, 472]]
Chk 9328 [[35, 145, 199, 489], [14, 165, 334, 499]]
Chk 9329 [[21, 10, 318, 420], [375, 54, 639, 426], [333, 160, 444, 426], [0, 177, 79, 420], [572, 78, 639, 224], [311, 153, 378, 281]]
Chk 9330 [[0, 196, 134, 484], [116, 206, 219, 454], [206, 188, 270, 453], [196, 219, 553, 584]]
Chk 9331 [[313, 98, 438, 307], [497, 74, 639, 473], [0, 87, 140, 479]]
Chk 9332 [[50, 13, 426, 466], [265, 44, 553, 465], [461, 226, 536, 331]]
Chk 9333 [[250, 42, 491, 460], [409, 40, 636, 471], [451, 29, 507, 83]]
Chk 9335 [[507, 120, 629, 308], [324, 155, 499, 307], [126, 94, 184, 146], [105, 73, 173, 138], [196, 91, 396, 313], [233, 58, 377, 113], [528, 25, 580, 82]]
Chk 9337 [[0, 6, 178, 328], [296, 52, 359, 269], [143, 5, 303, 326], [107, 64, 217, 328], [249, 62, 335, 309]]

Chk 9338 [[138, 113, 408, 479], [286, 87, 490, 477], [472, 2, 562, 136]]
Chk 9339 [[1, 31, 265, 603], [250, 4, 479, 616], [222, 106, 283, 235]]
Chk 9340 [[224, 123, 351, 438], [383, 158, 510, 432], [11, 270, 75, 438]]
Chk 9341 [[331, 65, 639, 478], [1, 60, 368, 469]]
Chk 9343 [[361, 148, 532, 400], [487, 46, 639, 424]]
Chk 9344 [[303, 54, 561, 357], [206, 2, 368, 215], [0, 15, 302, 470], [64, 3, 168, 183], [1, 11, 52, 127]]
Chk 9345 [[114, 47, 292, 382], [299, 43, 482, 387]]
Chk 9347 [[179, 1, 533, 530], [0, 1, 311, 603]]
Chk 9348 [[62, 106, 438, 474], [275, 103, 464, 466], [0, 212, 101, 436]]
Chk 9349 [[7, 132, 283, 526], [141, 120, 284, 430], [275, 270, 415, 526]]
Chk 9350 [[89, 121, 330, 460], [458, 156, 564, 446]]
Chk 9351 [[14, 6, 499, 418], [154, 91, 430, 421]]
Chk 9352 [[102, 241, 249, 549], [256, 222, 441, 543]]
Chk 9353 [[264, 173, 426, 479], [45, 95, 135, 385], [176, 189, 353, 445], [0, 213, 66, 409], [122, 297, 177, 367], [156, 393, 268, 479]]
Chk 9354 [[520, 97, 639, 299], [363, 115, 557, 264], [367, 190, 448, 421], [548, 206, 615, 281]]
Chk 9356 [[45, 195, 151, 430], [321, 178, 478, 400], [127, 288, 255, 434]]
Chk 9357 [[443, 80, 635, 559], [121, 51, 416, 513]]
Chk 9358 [[152, 223, 336, 368], [1, 227, 153, 373], [419, 307, 499, 372]]
Chk 9360 [[163, 68, 319, 418], [476, 341, 636, 418], [535, 234, 639, 349], [536, 48, 639, 323]]
Chk 9361 [[110, 18, 326, 264], [2, 110, 198, 286]]
Chk 9363 [[313, 123, 615, 472], [139, 258, 452, 474], [473, 8, 629, 324]]
Chk 9364 [[162, 76, 270, 389], [348, 80, 441, 376], [379, 39, 594, 479]]
Chk 9366 [[52, 66, 286, 469], [346, 58, 575, 372]]
Chk 9367 [[143, 91, 271, 450], [334, 105, 461, 469]]
Chk 9370 [[264, 116, 490, 478], [392, 118, 537, 472]]
Chk 9371 [[110, 161, 223, 501], [50, 144, 124, 461], [217, 175, 353, 501], [501, 175, 614, 365]]
Chk 9372 [[227, 52, 373, 368], [24, 75, 236, 370], [443, 190, 499, 372]]
Chk 9373 [[28, 127, 220, 427], [212, 125, 377, 354], [464, 37, 639, 421], [15, 97, 80, 285], [392, 97, 459, 281], [60, 42, 201, 229], [183, 26, 265, 135]]
Chk 9374 [[208, 74, 302, 331], [320, 53, 416, 342], [44, 84, 108, 295], [115, 79, 190, 313]]
Chk 9376 [[221, 145, 365, 426], [355, 141, 496, 426]]
Chk 9377 [[1, 2, 242, 564], [129, 307, 424, 632]]
Chk 9380 [[147, 187, 389, 616], [97, 71, 229, 567]]
Chk 9381 [[15, 2, 335, 473], [187, 30, 564, 475]]
Chk 9382 [[22, 0, 229, 369], [310, 0, 474, 369], [311, 254, 364, 370], [0, 273, 55, 357], [139, 0, 214, 368]]
Chk 9383 [[379, 82, 560, 390], [6, 96, 133, 413], [291, 82, 410, 389], [113, 62, 221, 322]]
Chk 9384 [[3, 39, 139, 426], [176, 31, 315, 386], [162, 147, 394, 426], [429, 35, 528, 297]]
Chk 9385 [[438, 23, 637, 524], [185, 26, 315, 332], [196, 35, 471, 432], [76, 64, 204, 261], [13, 59, 98, 223]]
Chk 9386 [[258, 300, 372, 630], [151, 314, 270, 630]]
Chk 9390 [[288, 25, 476, 473], [0, 142, 174, 473], [446, 298, 639, 469]]
Chk 9391 [[445, 63, 575, 444], [560, 105, 627, 354], [372, 182, 489, 284], [248, 176, 387, 401], [39, 208, 145, 334]]
Chk 9392 [[337, 41, 599, 455], [1, 1, 341, 430]]
Chk 9393 [[335, 24, 482, 294], [156, 75, 321, 293], [116, 127, 182, 274], [564, 56, 639, 323], [310, 95, 370, 278]]
Chk 9395 [[141, 224, 564, 478], [45, 215, 585, 455]]
Chk 9396 [[156, 17, 382, 511], [6, 110, 193, 511], [108, 122, 191, 233], [568, 171, 639, 405]]
Chk 9397 [[135, 72, 319, 473], [331, 121, 462, 471]]
Chk 9398 [[2, 2, 384, 474], [323, 29, 532, 277], [398, 71, 639, 479]]
Chk 9399 [[103, 165, 635, 473], [19, 4, 260, 250]]
Chk 9401 [[0, 52, 288, 326], [185, 0, 491, 374], [68, 75, 289, 368]]
Chk 9402 [[4, 45, 306, 502], [275, 4, 396, 250], [471, 0, 593, 202], [143, 0, 350, 362]]
Chk 9403 [[256, 64, 548, 443], [30, 93, 286, 445], [514, 91, 579, 258]]
Chk 9404 [[107, 45, 284, 451], [338, 100, 506, 439]]
Chk 9405 [[241, 84, 446, 610], [398, 49, 601, 597], [34, 18, 257, 605]]
Chk 9406 [[215, 57, 429, 234], [142, 301, 322, 397], [464, 315, 609, 374], [290, 305, 422, 385]]
Chk 9408 [[448, 54, 558, 324], [375, 71, 446, 321], [294, 85, 411, 419], [103, 48, 297, 426]]
Chk 9409 [[308, 109, 630, 473], [8, 28, 310, 473]]
Chk 9410 [[96, 53, 339, 467], [316, 63, 488, 475]]
Chk 9412 [[180, 35, 314, 421], [311, 34, 448, 400]]
Chk 9413 [[345, 145, 441, 395], [236, 123, 357, 391]]
Chk 9414 [[54, 175, 334, 425], [230, 0, 440, 200], [272, 43, 639, 426]]
Chk 9415 [[10, 33, 264, 354], [513, 101, 617, 351]]
Chk 9416 [[420, 65, 637, 409], [267, 5, 427, 181], [16, 39, 218, 413], [156, 0, 273, 147], [0, 12, 57, 127], [112, 0, 211, 54]]
Chk 9417 [[3, 11, 274, 397], [358, 6, 639, 391]]
Chk 9418 [[64, 111, 277, 426], [369, 120, 471, 306], [205, 162, 299, 259], [248, 83, 314, 191], [564, 82, 625, 158], [489, 79, 584, 182], [452, 67, 526, 166], [418, 100, 489, 231]]
Chk 9419 [[116, 53, 353, 472], [331, 41, 536, 473]]
Chk 9420 [[46, 39, 166, 414], [201, 51, 281, 365], [275, 19, 385, 460], [342, 25, 405, 326], [387, 34, 543, 448], [521, 67, 576, 184]]
Chk 9422 [[12, 188, 165, 362], [272, 151, 442, 376], [145, 217, 300, 356], [381, 22, 437, 80], [326, 18, 380, 80], [278, 9, 329, 80], [109, 25, 161, 83]]
Chk 9423 [[219, 55, 446, 331], [24, 39, 238, 330]]
Chk 9425 [[319, 89, 551, 354], [31, 155, 229, 414], [198, 216, 383, 407]]
Chk 9426 [[282, 86, 413, 364], [109, 0, 287, 374], [367, 108, 499, 369], [0, 210, 130, 281]]
Chk 9427 [[8, 120, 225, 554], [381, 119, 602, 512]]
Chk 9428 [[261, 168, 471, 345], [7, 244, 278, 438], [0, 0, 96, 307], [441, 127, 538, 306], [368, 3, 501, 212], [564, 98, 639, 231]]
Chk 9430 [[227, 101, 430, 306], [65, 0, 252, 294]]
Chk 9431 [[222, 12, 426, 500], [152, 121, 323, 493]]
Chk 9432 [[1, 63, 114, 374], [313, 0, 639, 420], [195, 73, 317, 402], [94, 98, 217, 377], [226, 175, 316, 295]]
Chk 9433 [[214, 28, 445, 338], [0, 25, 207, 425], [534, 139, 625, 297], [365, 211, 417, 319]]
Chk 9434 [[313, 76, 593, 420], [312, 1, 469, 292], [264, 39, 356, 247], [113, 31, 293, 344], [201, 20, 314, 281]]
Chk 9435 [[174, 116, 391, 494], [0, 2, 319, 634], [274, 34, 479, 508], [395, 308, 479, 639], [365, 468, 468, 639]]
Chk 9437 [[60, 120, 410, 555], [58, 45, 297, 530]]
Chk 9440 [[160, 182, 329, 519], [53, 183, 188, 537], [3, 135, 61, 252], [39, 38, 102, 149]]
Chk 9441 [[371, 195, 462, 517], [204, 271, 291, 404], [0, 362, 179, 626], [256, 268, 307, 338]]
Chk 9442 [[61, 245, 296, 580], [172, 35, 450, 513]]
Chk 9443 [[199, 45, 461, 446], [67, 36, 332, 478]]
Chk 9444 [[399, 186, 475, 363], [354, 186, 413, 394], [234, 147, 308, 389], [167, 156, 249, 406], [39, 137, 171, 414], [515, 208, 594, 376]]
Chk 9445 [[14, 131, 93, 373], [169, 174, 270, 395], [341, 206, 398, 387], [466, 225, 531, 401], [536, 216, 613, 430]]
Chk 9446 [[173, 109, 448, 543], [277, 82, 500, 344]]
Chk 9447 [[175, 95, 321, 354], [104, 110, 233, 335], [55, 81, 178, 318], [278, 109, 428, 362]]
Chk 9448 [[451, 36, 554, 320], [341, 83, 451, 420], [193, 95, 291, 348], [183, 20, 245, 194]]
Chk 9449 [[187, 21, 507, 421], [1, 196, 178, 427]]
Chk 9450 [[435, 20, 639, 364], [0, 216, 146, 448], [259, 215, 388, 384]]
Chk 9451 [[0, 48, 142, 476], [137, 39, 300, 480], [253, 43, 324, 176], [474, 35, 639, 474], [287, 49, 476, 475]]
Chk 9454 [[311, 171, 639, 473], [8, 88, 465, 452], [551, 136, 639, 187], [253, 88, 435, 360]]
Chk 9455 [[192, 168, 423, 632], [234, 41, 423, 483]]
Chk 9456 [[246, 92, 335, 346], [499, 110, 590, 377]]
Chk 9457 [[0, 118, 197, 477], [372, 105, 580, 479]]
Chk 9458 [[302, 22, 537, 304], [0, 0, 348, 421]]
Chk 9460 [[392, 219, 495, 426], [486, 236, 537, 415], [372, 302, 455, 421]]
Chk 9462 [[60, 42, 297, 421], [377, 42, 573, 426], [219, 49, 405, 425], [67, 118, 166, 250], [560, 1, 638, 419], [492, 0, 609, 154], [0, 6, 77, 417]]
Chk 9463 [[25, 117, 454, 623], [238, 126, 446, 459], [398, 0, 454, 295]]
Chk 9464 [[0, 0, 100, 295], [60, 149, 155, 297], [495, 95, 636, 293], [248, 34, 355, 299]]
Chk 9465 [[0, 292, 115, 425], [120, 20, 235, 400], [451, 0, 608, 420], [2, 51, 100, 349], [267, 191, 485, 422]]
Chk 9466 [[73, 151, 293, 406], [410, 151, 587, 469], [196, 111, 303, 244], [428, 139, 578, 354], [353, 103, 471, 276]]
Chk 9467 [[327, 77, 634, 436], [3, 98, 286, 438]]
Chk 9468 [[138, 53, 279, 470], [266, 79, 408, 479], [9, 100, 137, 474], [481, 53, 639, 479]]
Chk 9470 [[237, 38, 357, 188], [416, 165, 608, 462]]
Chk 9471 [[362, 155, 464, 253], [0, 132, 249, 355], [434, 140, 639, 355]]
Chk 9472 [[18, 129, 369, 638], [150, 274, 426, 629]]
Chk 9474 [[257, 90, 435, 420], [383, 38, 514, 427], [102, 0, 175, 66], [495, 138, 578, 341]]
Chk 9475 [[118, 98, 200, 323], [206, 110, 259, 309], [251, 80, 334, 368], [365, 79, 452, 358]]
Chk 9477 [[0, 101, 282, 384], [132, 55, 501, 427]]
Chk 9478 [[343, 107, 512, 473], [276, 1, 490, 297]]
Chk 9479 [[147, 159, 298, 412], [420, 147, 526, 406], [296, 161, 385, 411]]

Chk 9480 [[126, 119, 254, 467], [224, 63, 356, 479], [339, 147, 435, 385], [504, 167, 639, 344], [256, 0, 340, 134]]
Chk 9481 [[114, 100, 409, 479], [335, 46, 639, 479]]
Chk 9483 [[149, 0, 618, 632], [153, 288, 411, 625]]
Chk 9484 [[229, 89, 367, 580], [89, 88, 340, 596]]
Chk 9485 [[181, 67, 328, 417], [0, 264, 96, 422], [332, 73, 627, 417]]
Chk 9486 [[197, 131, 426, 563], [125, 343, 194, 512], [4, 45, 154, 629]]
Chk 9487 [[156, 147, 295, 404], [48, 127, 165, 446]]
Chk 9488 [[160, 41, 355, 319], [49, 86, 277, 321]]
Chk 9489 [[199, 161, 402, 627], [0, 34, 234, 639]]
Chk 9492 [[32, 130, 169, 424], [162, 148, 344, 456], [448, 157, 637, 473]]
Chk 9493 [[212, 146, 336, 446], [54, 201, 158, 467]]
Chk 9494 [[95, 201, 261, 419], [492, 1, 568, 67], [14, 107, 115, 416], [368, 71, 548, 410], [325, 0, 390, 71], [567, 0, 639, 67], [387, 0, 475, 70], [312, 0, 398, 52]]
Chk 9495 [[2, 136, 238, 472], [513, 203, 639, 478], [189, 169, 314, 473]]
Chk 9496 [[190, 29, 384, 260], [1, 5, 194, 309], [510, 219, 639, 479], [518, 0, 639, 224]]
Chk 9497 [[192, 0, 371, 412], [26, 12, 217, 402]]
Chk 9498 [[203, 63, 303, 267], [290, 66, 397, 368]]
Chk 9499 [[145, 120, 266, 358], [41, 119, 185, 369], [458, 141, 596, 378], [395, 128, 507, 366], [289, 128, 409, 366]]
Chk 9500 [[181, 68, 453, 329], [185, 56, 299, 327]]
Chk 9501 [[209, 92, 384, 260], [500, 118, 639, 298], [15, 110, 161, 300]]
Chk 9503 [[309, 217, 427, 408], [86, 231, 300, 389]]
Chk 9504 [[154, 111, 345, 357], [365, 64, 509, 352]]
Chk 9505 [[162, 230, 291, 575], [2, 224, 183, 629], [330, 257, 483, 632]]
Chk 9506 [[186, 116, 437, 539], [180, 255, 281, 440], [382, 41, 563, 492]]
Chk 9508 [[432, 137, 527, 452], [113, 131, 208, 446]]
Chk 9509 [[181, 119, 364, 304], [79, 77, 209, 284], [397, 1, 499, 329], [123, 0, 195, 169], [41, 0, 93, 102]]
Chk 9513 [[302, 71, 460, 459], [448, 58, 636, 384], [107, 77, 239, 463], [44, 102, 120, 471]]
Chk 9514 [[359, 99, 488, 449], [1, 202, 156, 453], [324, 93, 405, 190], [60, 68, 372, 474]]
Chk 9516 [[346, 32, 596, 424], [1, 51, 362, 348]]
Chk 9517 [[0, 12, 258, 349], [267, 63, 428, 346]]
Chk 9518 [[133, 63, 307, 436], [447, 276, 607, 472], [325, 344, 512, 479]]
Chk 9520 [[265, 67, 373, 392], [98, 192, 234, 416]]
Chk 9521 [[81, 127, 403, 597], [346, 256, 479, 497], [356, 176, 408, 307], [300, 1, 369, 52], [417, 165, 478, 347], [75, 221, 162, 494]]
Chk 9522 [[132, 61, 417, 421], [369, 80, 596, 425]]
Chk 9523 [[46, 70, 537, 419], [300, 59, 639, 425], [318, 13, 380, 120]]
Chk 9524 [[323, 93, 601, 349], [230, 50, 526, 335]]
Chk 9525 [[197, 121, 422, 568], [68, 48, 285, 562], [0, 205, 91, 639]]
Chk 9526 [[323, 127, 442, 472], [42, 196, 246, 473], [499, 162, 639, 474], [463, 166, 577, 422]]
Chk 9527 [[283, 127, 527, 543], [19, 249, 274, 511], [533, 54, 631, 266], [309, 60, 363, 124], [461, 145, 524, 247], [164, 33, 235, 129], [0, 191, 106, 281], [379, 64, 432, 121]]
Chk 9528 [[254, 237, 386, 465], [23, 212, 174, 465]]
Chk 9529 [[241, 164, 525, 454], [0, 112, 316, 482], [193, 197, 290, 338], [493, 115, 634, 461], [271, 152, 345, 268]]
Chk 9530 [[176, 58, 394, 418], [271, 42, 394, 432]]
Chk 9531 [[412, 120, 639, 418], [52, 77, 517, 418]]
Chk 9532 [[379, 0, 639, 510], [1, 70, 423, 504]]
Chk 9533 [[111, 5, 488, 474], [156, 203, 422, 472]]
Chk 9534 [[270, 111, 393, 360], [383, 101, 434, 291], [580, 127, 639, 360], [440, 125, 521, 348], [387, 202, 439, 360], [36, 70, 285, 354]]
Chk 9535 [[175, 43, 327, 416], [51, 22, 342, 423]]
Chk 9536 [[139, 102, 361, 343], [287, 61, 361, 226], [540, 48, 639, 271], [372, 170, 638, 387], [0, 43, 90, 263]]
Chk 9537 [[288, 158, 455, 479], [183, 8, 399, 442], [0, 222, 211, 479], [154, 59, 274, 347]]
Chk 9538 [[143, 25, 302, 316], [2, 5, 143, 318], [347, 180, 419, 315], [442, 165, 498, 313]]
Chk 9539 [[184, 107, 307, 463], [275, 144, 376, 456], [425, 220, 530, 287], [0, 228, 68, 302]]
Chk 9543 [[1, 69, 438, 437], [215, 234, 339, 375], [53, 206, 451, 425]]
Chk 9544 [[124, 56, 370, 406], [148, 214, 211, 350]]
Chk 9545 [[82, 66, 304, 479], [79, 58, 381, 433]]
Chk 9547 [[172, 125, 344, 415], [323, 142, 509, 403], [7, 51, 144, 248], [322, 5, 496, 93]]
Chk 9548 [[78, 72, 306, 276], [302, 146, 637, 420], [0, 0, 84, 170]]
Chk 9549 [[2, 71, 459, 379], [431, 96, 639, 414]]
Chk 9550 [[125, 128, 303, 355], [229, 103, 290, 170], [375, 112, 460, 249], [414, 109, 533, 289], [365, 259, 536, 426], [320, 133, 383, 196], [29, 160, 261, 421]]
Chk 9551 [[123, 39, 360, 472], [114, 113, 639, 479]]
Chk 9553 [[131, 99, 377, 480], [314, 150, 432, 479], [323, 276, 490, 387], [3, 355, 140, 473]]
Chk 9554 [[233, 63, 399, 300], [443, 78, 602, 309], [536, 103, 591, 157]]
Chk 9557 [[209, 45, 492, 448], [54, 80, 232, 455], [488, 110, 596, 304]]
Chk 9558 [[156, 100, 305, 423], [18, 158, 174, 415], [39, 77, 168, 240], [444, 120, 603, 418]]
Chk 9559 [[17, 94, 85, 233], [8, 0, 408, 473], [483, 77, 639, 474], [390, 86, 467, 319], [321, 66, 422, 301], [370, 44, 424, 133], [0, 299, 52, 479]]
Chk 9560 [[179, 35, 417, 433], [321, 45, 584, 430]]
Chk 9561 [[98, 105, 261, 633], [233, 87, 381, 570]]
Chk 9562 [[60, 159, 325, 420], [371, 66, 617, 421], [64, 232, 135, 379], [342, 182, 447, 423]]
Chk 9563 [[190, 183, 393, 464], [367, 218, 485, 407], [173, 200, 224, 277]]
Chk 9565 [[215, 120, 328, 479], [317, 136, 445, 479]]
Chk 9567 [[1, 62, 303, 474], [188, 170, 401, 472], [363, 195, 639, 391]]
Chk 9568 [[112, 139, 229, 369], [207, 141, 353, 368], [328, 103, 475, 370]]
Chk 9570 [[1, 92, 386, 422], [240, 14, 515, 384]]
Chk 9571 [[228, 22, 383, 258], [441, 14, 639, 246], [53, 46, 222, 258]]
Chk 9572 [[236, 116, 544, 419], [186, 53, 324, 291], [115, 81, 247, 292], [1, 120, 83, 259]]
Chk 9574 [[29, 35, 542, 475], [389, 0, 639, 474]]
Chk 9575 [[77, 266, 344, 599], [94, 16, 402, 396]]
Chk 9576 [[141, 46, 560, 426], [425, 80, 637, 382]]
Chk 9577 [[48, 72, 446, 476], [19, 77, 143, 364], [348, 71, 600, 411], [1, 43, 304, 484]]
Chk 9578 [[40, 132, 340, 437], [515, 204, 573, 274], [327, 216, 528, 407], [382, 287, 549, 437]]
Chk 9579 [[234, 52, 639, 473], [206, 183, 402, 479]]
Chk 9581 [[186, 86, 349, 343], [155, 126, 235, 222], [221, 26, 274, 179], [440, 78, 612, 420]]
Chk 9583 [[47, 87, 344, 462], [392, 50, 592, 478], [256, 76, 436, 472]]
Chk 9584 [[1, 1, 287, 474], [375, 252, 622, 473]]
Chk 9587 [[0, 70, 91, 374], [78, 75, 205, 368]]
Chk 9588 [[0, 64, 110, 288], [71, 47, 275, 297], [364, 0, 639, 323]]
Chk 9589 [[66, 156, 219, 395], [172, 214, 406, 401], [325, 99, 592, 354]]
Chk 9590 [[197, 89, 344, 350], [384, 211, 539, 368], [576, 5, 639, 107], [474, 129, 639, 374]]
Chk 9591 [[457, 158, 576, 371], [323, 97, 426, 427]]
Chk 9592 [[283, 45, 399, 423], [80, 23, 176, 250], [449, 48, 544, 300]]
Chk 9593 [[176, 42, 448, 412], [441, 137, 554, 317], [75, 146, 218, 478], [585, 189, 639, 347]]
Chk 9594 [[246, 77, 639, 418], [176, 129, 405, 307]]
Chk 9595 [[89, 34, 257, 340], [339, 97, 478, 421], [393, 217, 525, 367]]
Chk 9596 [[224, 0, 639, 480], [194, 37, 393, 282], [65, 1, 337, 376]]
Chk 9597 [[3, 52, 271, 362], [237, 61, 429, 255]]
Chk 9602 [[134, 53, 269, 388], [11, 66, 153, 262]]
Chk 9604 [[3, 4, 639, 474], [38, 89, 323, 193]]
Chk 9605 [[170, 162, 328, 344], [8, 109, 156, 358], [403, 65, 624, 359]]
Chk 9606 [[299, 124, 404, 359], [38, 239, 216, 438], [0, 31, 120, 434]]
Chk 9607 [[7, 195, 273, 421], [416, 161, 639, 426], [0, 261, 118, 342]]
Chk 9608 [[0, 140, 296, 630], [173, 116, 352, 484], [5, 79, 64, 282], [63, 95, 298, 456]]
Chk 9609 [[299, 85, 464, 424], [412, 89, 577, 479]]
Chk 9610 [[31, 59, 535, 419], [194, 96, 445, 310], [243, 72, 321, 195]]
Chk 9611 [[249, 18, 388, 342], [420, 35, 540, 413], [106, 142, 212, 284], [0, 67, 126, 393], [5, 226, 157, 349]]
Chk 9612 [[378, 156, 492, 364], [274, 213, 396, 366], [489, 126, 558, 190], [227, 114, 292, 173], [125, 152, 216, 342]]
Chk 9614 [[359, 22, 522, 419], [529, 19, 639, 421]]
Chk 9615 [[209, 84, 407, 451], [250, 14, 614, 638]]
Chk 9616 [[43, 133, 275, 588], [1, 5, 128, 318], [162, 5, 249, 252]]
Chk 9617 [[33, 150, 248, 419], [386, 173, 440, 336], [476, 130, 636, 415]]
Chk 9619 [[293, 87, 625, 588], [57, 49, 328, 586]]
Chk 9620 [[157, 113, 340, 368], [62, 96, 200, 346], [303, 0, 473, 374]]
Chk 9621 [[326, 2, 499, 251], [78, 9, 278, 236]]
Chk 9624 [[272, 126, 521, 395], [0, 128, 247, 426]]
Chk 9625 [[1, 124, 171, 378], [165, 53, 328, 333], [327, 7, 426, 161], [348, 513, 426, 639], [233, 272, 426, 505]]
Chk 9626 [[199, 140, 357, 499], [0, 94, 219, 491]]
Chk 9627 [[87, 43, 627, 544], [18, 159, 197, 592]]

Chk 9628 [[1, 130, 319, 599], [242, 160, 558, 484]]
Chk 9629 [[74, 88, 324, 600], [353, 5, 561, 608]]
Chk 9630 [[125, 72, 401, 474], [335, 77, 549, 474]]
Chk 9631 [[72, 162, 278, 472], [337, 12, 426, 313]]
Chk 9632 [[384, 110, 509, 418], [74, 84, 366, 426]]
Chk 9633 [[1, 64, 273, 469], [228, 147, 552, 477]]
Chk 9634 [[61, 67, 243, 472], [216, 31, 639, 479], [0, 10, 68, 185]]
Chk 9635 [[111, 228, 426, 620], [29, 123, 181, 584], [226, 198, 308, 309]]
Chk 9636 [[350, 35, 617, 429], [240, 30, 356, 203], [19, 84, 167, 339], [185, 13, 246, 158]]
Chk 9638 [[0, 2, 298, 336], [140, 0, 387, 316], [232, 0, 499, 277]]
Chk 9639 [[377, 37, 607, 605], [64, 62, 233, 596]]
Chk 9640 [[222, 155, 405, 436], [443, 31, 585, 436]]
Chk 9642 [[48, 101, 345, 425], [346, 156, 562, 424]]
Chk 9643 [[148, 67, 306, 362], [359, 186, 499, 370], [396, 54, 477, 150], [0, 0, 51, 114]]
Chk 9644 [[76, 23, 465, 473], [178, 15, 636, 474], [58, 46, 274, 474], [1, 6, 102, 471]]
Chk 9645 [[304, 46, 458, 372], [85, 16, 357, 418]]
Chk 9646 [[291, 247, 402, 472], [0, 219, 178, 471], [116, 285, 298, 396]]
Chk 9648 [[242, 178, 446, 410], [113, 172, 350, 426], [547, 117, 639, 402], [299, 194, 402, 289]]
Chk 9649 [[116, 66, 336, 448], [319, 50, 524, 445]]
Chk 9650 [[0, 11, 78, 421], [96, 202, 304, 426], [68, 69, 178, 244], [234, 55, 370, 419]]
Chk 9651 [[105, 97, 404, 479], [343, 120, 553, 473]]
Chk 9652 [[241, 97, 409, 397], [33, 92, 229, 344]]
Chk 9653 [[19, 195, 288, 491], [263, 220, 393, 431], [407, 250, 496, 453], [481, 256, 555, 439], [0, 394, 55, 527], [322, 224, 455, 451]]
Chk 9654 [[1, 215, 299, 485], [31, 0, 293, 306]]
Chk 9656 [[350, 46, 534, 444], [138, 38, 327, 465]]
Chk 9657 [[199, 41, 401, 506], [282, 202, 373, 536], [387, 279, 473, 447], [0, 212, 114, 474], [417, 304, 478, 530], [156, 60, 295, 499], [11, 74, 149, 530]]
Chk 9659 [[173, 77, 393, 440], [181, 131, 261, 317], [115, 139, 190, 380], [412, 244, 512, 370], [60, 235, 113, 376], [0, 196, 81, 377]]
Chk 9660 [[11, 5, 345, 542], [302, 112, 639, 533]]
Chk 9662 [[125, 51, 360, 332], [293, 38, 446, 327]]
Chk 9663 [[195, 13, 459, 338], [451, 98, 637, 337]]
Chk 9664 [[147, 48, 362, 316], [265, 138, 506, 368], [501, 90, 639, 331]]
Chk 9665 [[396, 93, 594, 419], [67, 68, 309, 311], [585, 176, 639, 327]]
Chk 9666 [[0, 149, 99, 479], [90, 79, 330, 472], [328, 162, 446, 375]]
Chk 9667 [[323, 37, 639, 473], [111, 99, 292, 467], [45, 24, 157, 239], [7, 38, 67, 138], [74, 8, 177, 117], [177, 8, 300, 100], [323, 4, 398, 96], [551, 0, 639, 170]]
Chk 9668 [[0, 44, 184, 479], [223, 168, 390, 479]]
Chk 9669 [[354, 28, 504, 404], [193, 64, 298, 387], [477, 69, 599, 402], [303, 71, 390, 401]]
Chk 9670 [[118, 119, 342, 382], [278, 51, 470, 413]]
Chk 9671 [[147, 32, 373, 639], [14, 30, 232, 590]]
Chk 9673 [[155, 101, 454, 479], [0, 218, 305, 479]]
Chk 9675 [[28, 119, 328, 411], [263, 98, 591, 376], [249, 50, 322, 224]]
Chk 9676 [[484, 110, 638, 301], [5, 79, 210, 263], [259, 112, 426, 282]]
Chk 9678 [[69, 129, 158, 287], [161, 98, 248, 290], [520, 120, 632, 420], [434, 123, 554, 425], [560, 101, 622, 205], [0, 112, 91, 286]]
Chk 9679 [[253, 168, 347, 372], [325, 93, 442, 319], [111, 189, 222, 442], [11, 307, 143, 385]]
Chk 9680 [[30, 65, 387, 472], [353, 1, 639, 473]]
Chk 9682 [[192, 221, 276, 405], [220, 257, 324, 463], [123, 220, 218, 482]]
Chk 9683 [[218, 119, 419, 377], [219, 206, 293, 291], [135, 232, 196, 291], [360, 160, 447, 322], [444, 220, 618, 379], [51, 94, 103, 160], [112, 62, 165, 160]]
Chk 9686 [[242, 64, 391, 407], [193, 84, 274, 299], [399, 74, 469, 258], [527, 89, 587, 205], [523, 55, 576, 121], [439, 41, 512, 97], [121, 62, 187, 170]]
Chk 9687 [[59, 34, 336, 427], [360, 53, 579, 432]]
Chk 9689 [[0, 3, 358, 471], [299, 1, 639, 474]]
Chk 9690 [[207, 142, 305, 299], [6, 137, 124, 316], [368, 109, 528, 356], [480, 102, 639, 381]]
Chk 9691 [[213, 76, 503, 382], [0, 71, 333, 421], [537, 48, 634, 226]]
Chk 9692 [[92, 16, 258, 474], [442, 82, 617, 479]]
Chk 9693 [[100, 115, 337, 445], [312, 50, 639, 436]]
Chk 9694 [[0, 160, 149, 421], [346, 143, 474, 425], [100, 88, 252, 417], [453, 108, 637, 416]]
Chk 9695 [[290, 88, 575, 421], [0, 162, 230, 419], [121, 31, 331, 294], [11, 2, 108, 119], [103, 0, 167, 109], [183, 20, 364, 296], [458, 0, 599, 150]]
Chk 9696 [[75, 89, 232, 511], [380, 96, 536, 504]]
Chk 9697 [[188, 174, 425, 631], [178, 186, 298, 524]]
Chk 9700 [[152, 28, 288, 331], [5, 41, 167, 309]]
Chk 9701 [[82, 70, 379, 425], [323, 96, 508, 356], [0, 159, 55, 394], [66, 177, 136, 247], [63, 167, 114, 246]]
Chk 9702 [[5, 117, 296, 420], [258, 48, 527, 421]]
Chk 9704 [[12, 87, 224, 371], [349, 2, 639, 349], [271, 0, 360, 173], [20, 1, 160, 158], [156, 0, 231, 212], [222, 0, 286, 201], [344, 0, 403, 133]]
Chk 9705 [[171, 54, 323, 368], [341, 56, 483, 370]]
Chk 9707 [[219, 54, 312, 406], [309, 95, 384, 369], [392, 99, 513, 378], [545, 82, 628, 283], [119, 101, 174, 400], [182, 103, 233, 256]]
Chk 9708 [[140, 35, 295, 496], [42, 66, 164, 492]]
Chk 9709 [[371, 67, 496, 389], [8, 105, 285, 388], [374, 20, 461, 168]]
Chk 9710 [[227, 74, 376, 332], [223, 106, 573, 472]]
Chk 9711 [[200, 163, 394, 342], [187, 201, 265, 301], [66, 189, 317, 393]]
Chk 9712 [[140, 9, 423, 421], [346, 136, 475, 379], [0, 147, 221, 426]]
Chk 9713 [[88, 84, 212, 388], [206, 178, 305, 379], [209, 114, 322, 280], [581, 115, 637, 437], [394, 131, 528, 341], [323, 145, 417, 338]]
Chk 9714 [[303, 8, 483, 461], [0, 0, 307, 494], [286, 271, 350, 406]]
Chk 9715 [[230, 191, 291, 376], [240, 130, 433, 478], [241, 130, 498, 473], [239, 163, 376, 436]]
Chk 9716 [[375, 67, 610, 344], [48, 62, 279, 299]]
Chk 9717 [[170, 93, 366, 472], [340, 125, 568, 471]]
Chk 9719 [[226, 42, 394, 315], [5, 1, 270, 264]]
Chk 9721 [[174, 204, 251, 299], [248, 227, 322, 290], [306, 214, 384, 286], [321, 381, 436, 479], [404, 221, 639, 469]]
Chk 9722 [[177, 64, 497, 374], [0, 130, 198, 368]]
Chk 9723 [[186, 69, 333, 331], [405, 101, 481, 327], [41, 84, 160, 326], [0, 138, 62, 327]]
Chk 9724 [[176, 69, 364, 370], [326, 56, 416, 333], [392, 0, 468, 330], [230, 27, 284, 97], [527, 34, 629, 205]]
Chk 9725 [[1, 107, 208, 604], [184, 125, 383, 508]]
Chk 9726 [[119, 122, 280, 408], [35, 122, 141, 299], [402, 133, 593, 397], [457, 112, 537, 238], [528, 54, 583, 124], [419, 112, 483, 201], [279, 100, 358, 183], [9, 43, 88, 333]]
Chk 9727 [[17, 53, 267, 461], [210, 92, 398, 397], [423, 104, 619, 416], [416, 11, 569, 452]]
Chk 9728 [[231, 50, 426, 386], [36, 130, 232, 384], [138, 249, 500, 473]]
Chk 9729 [[7, 139, 279, 476], [375, 128, 613, 477]]
Chk 9730 [[0, 1, 325, 474], [326, 54, 470, 279], [164, 89, 247, 229]]
Chk 9732 [[145, 277, 500, 471], [80, 220, 190, 472], [327, 249, 489, 436], [424, 238, 610, 396], [219, 213, 369, 346]]
Chk 9735 [[0, 87, 184, 422], [368, 67, 605, 420]]
Chk 9736 [[209, 110, 426, 475], [19, 152, 228, 483]]
Chk 9737 [[207, 10, 425, 499], [0, 3, 174, 494]]
Chk 9739 [[86, 126, 187, 347], [162, 118, 247, 210], [352, 167, 467, 279], [407, 191, 550, 376], [440, 202, 639, 473], [1, 168, 148, 474]]
Chk 9740 [[42, 143, 263, 331], [166, 6, 343, 307], [397, 15, 564, 235], [377, 132, 586, 321]]
Chk 9741 [[231, 0, 639, 421], [75, 4, 326, 420]]
Chk 9743 [[109, 42, 306, 287], [59, 17, 119, 74], [177, 11, 237, 82], [379, 32, 467, 148], [329, 151, 485, 302], [326, 76, 382, 145], [119, 16, 199, 127]]
Chk 9745 [[151, 14, 297, 281], [309, 201, 466, 412]]
Chk 9749 [[173, 181, 459, 433], [86, 184, 430, 479]]
Chk 9751 [[2, 129, 270, 638], [217, 154, 404, 597]]
Chk 9752 [[157, 65, 299, 348], [330, 79, 490, 385]]
Chk 9753 [[281, 94, 546, 400], [143, 82, 243, 395]]
Chk 9754 [[203, 25, 332, 221], [318, 52, 499, 321], [64, 33, 220, 231]]
Chk 9755 [[334, 35, 485, 283], [287, 23, 363, 230], [134, 62, 208, 196], [89, 91, 153, 243], [486, 0, 565, 191]]
Chk 9756 [[304, 151, 515, 440], [1, 39, 373, 448]]
Chk 9757 [[321, 112, 515, 413], [108, 198, 205, 364], [0, 217, 145, 420], [356, 93, 453, 381]]
Chk 9758 [[4, 105, 301, 470], [282, 101, 613, 469]]
Chk 9759 [[75, 70, 366, 469], [321, 19, 589, 475]]
Chk 9761 [[56, 135, 226, 372], [326, 64, 386, 166], [311, 100, 441, 376], [429, 130, 627, 388]]
Chk 9763 [[461, 213, 588, 572], [266, 253, 393, 498], [192, 232, 245, 355], [0, 257, 96, 533], [319, 225, 371, 347]]
Chk 9764 [[295, 138, 404, 355], [0, 144, 114, 353], [386, 99, 486, 358]]
Chk 9765 [[188, 0, 378, 425], [365, 201, 567, 425]]
Chk 9766 [[0, 183, 285, 426], [0, 63, 205, 348]]
Chk 9767 [[267, 0, 639, 422], [286, 104, 403, 405]]

Chk 9768 [[166, 84, 372, 271], [34, 111, 524, 467], [426, 68, 612, 326], [339, 98, 633, 331]]
Chk 9769 [[105, 163, 231, 555], [303, 129, 474, 585]]
Chk 9770 [[7, 21, 405, 627], [77, 134, 479, 639]]
Chk 9771 [[36, 399, 252, 639], [290, 432, 425, 630]]
Chk 9774 [[315, 114, 404, 205], [60, 93, 194, 260], [0, 105, 93, 307], [321, 215, 638, 476], [166, 91, 280, 226], [469, 95, 552, 218], [494, 124, 564, 244], [536, 123, 639, 247]]
Chk 9775 [[191, 75, 579, 420], [0, 19, 335, 419]]
Chk 9776 [[282, 15, 504, 450], [440, 275, 549, 479]]
Chk 9778 [[408, 83, 635, 420], [447, 113, 565, 283], [222, 140, 390, 286], [2, 106, 191, 422]]
Chk 9779 [[3, 116, 286, 445], [294, 15, 589, 442]]
Chk 9781 [[68, 108, 316, 370], [260, 101, 452, 366]]
Chk 9782 [[86, 66, 322, 471], [408, 106, 511, 316], [580, 134, 639, 316]]
Chk 9783 [[428, 0, 638, 453], [218, 69, 539, 452], [16, 59, 342, 450]]
Chk 9788 [[180, 90, 354, 418], [186, 28, 507, 417]]
Chk 9789 [[88, 179, 241, 343], [331, 124, 639, 472], [235, 159, 360, 363], [528, 171, 606, 317]]
Chk 9792 [[170, 8, 430, 319], [257, 149, 409, 382]]
Chk 9795 [[360, 130, 470, 334], [101, 55, 334, 445], [59, 190, 120, 269], [1, 319, 191, 479]]
Chk 9796 [[340, 110, 542, 474], [586, 270, 639, 382], [149, 29, 333, 474]]
Chk 9797 [[131, 30, 345, 448], [404, 78, 611, 448], [29, 48, 241, 448]]
Chk 9798 [[340, 31, 511, 326], [87, 36, 300, 355]]
Chk 9799 [[188, 49, 250, 210], [132, 208, 276, 479], [431, 106, 515, 346], [532, 16, 592, 118], [225, 285, 405, 472], [366, 342, 509, 471]]
Chk 9800 [[345, 98, 456, 419], [210, 101, 336, 410], [102, 133, 201, 398]]
Chk 9801 [[182, 155, 479, 633], [0, 79, 235, 632]]
Chk 9802 [[178, 86, 292, 379], [352, 63, 462, 420], [35, 140, 260, 473], [471, 110, 560, 354], [549, 115, 639, 311], [516, 29, 604, 162], [428, 47, 490, 195], [322, 53, 374, 179]]
Chk 9805 [[135, 24, 291, 421], [387, 171, 475, 371], [411, 162, 487, 386], [359, 169, 443, 347]]
Chk 9806 [[172, 79, 330, 379], [101, 82, 208, 390], [485, 85, 586, 285], [49, 17, 117, 74], [89, 66, 151, 209], [23, 128, 92, 237], [500, 0, 555, 94], [285, 67, 359, 243]]
Chk 9807 [[385, 148, 550, 419], [248, 135, 433, 424]]
Chk 9808 [[327, 122, 506, 316], [570, 312, 638, 505], [42, 24, 513, 510]]
Chk 9810 [[380, 121, 606, 362], [1, 188, 119, 377], [190, 154, 456, 356], [56, 177, 216, 377], [14, 321, 172, 408], [0, 242, 297, 466]]
Chk 9813 [[173, 96, 334, 355], [35, 86, 179, 354], [336, 82, 402, 359], [285, 38, 517, 329], [556, 13, 611, 151], [403, 20, 516, 141]]
Chk 9814 [[23, 117, 104, 380], [220, 154, 280, 351], [277, 123, 360, 351], [276, 64, 631, 401], [105, 98, 209, 385]]
Chk 9815 [[43, 176, 238, 576], [141, 71, 355, 592]]
Chk 9817 [[218, 7, 400, 251], [223, 140, 350, 426]]
Chk 9818 [[222, 171, 388, 445], [229, 25, 439, 444]]
Chk 9820 [[276, 101, 566, 339], [495, 89, 639, 469], [5, 90, 203, 474]]
Chk 9823 [[426, 116, 584, 474], [51, 168, 143, 475]]
Chk 9824 [[546, 98, 630, 316], [173, 25, 354, 293], [399, 128, 585, 317]]
Chk 9825 [[359, 79, 496, 421], [480, 61, 639, 415], [76, 44, 190, 401], [285, 31, 384, 388]]
Chk 9826 [[356, 79, 512, 417], [300, 115, 385, 416], [127, 155, 237, 392], [0, 170, 57, 417], [538, 161, 639, 417]]
Chk 9830 [[20, 217, 196, 549], [300, 278, 437, 569], [282, 447, 437, 557], [221, 88, 321, 259]]
Chk 9831 [[310, 228, 462, 404], [0, 142, 226, 631]]
Chk 9833 [[101, 156, 306, 420], [305, 143, 564, 419], [427, 125, 592, 397]]
Chk 9834 [[214, 325, 399, 631], [40, 141, 226, 515], [247, 131, 479, 638]]
Chk 9835 [[75, 89, 272, 353], [370, 77, 638, 353]]
Chk 9836 [[261, 139, 410, 384], [406, 209, 534, 359], [509, 11, 573, 79]]
Chk 9837 [[2, 200, 132, 364], [89, 86, 247, 359], [357, 125, 512, 346], [238, 181, 327, 317]]
Chk 9839 [[191, 57, 462, 347], [87, 90, 288, 347]]
Chk 9840 [[0, 115, 352, 475], [36, 157, 143, 299], [581, 174, 639, 275], [296, 153, 360, 357], [347, 100, 632, 471], [504, 155, 623, 334], [371, 209, 423, 275]]
Chk 9841 [[0, 28, 328, 472], [297, 4, 638, 473]]
Chk 9844 [[66, 59, 290, 444], [485, 154, 635, 410], [458, 179, 539, 402], [192, 186, 368, 394]]
Chk 9845 [[52, 105, 205, 426], [295, 39, 560, 395], [0, 133, 98, 422]]
Chk 9846 [[137, 136, 513, 479], [57, 55, 186, 471], [478, 227, 639, 444]]
Chk 9847 [[60, 74, 321, 450], [4, 129, 284, 497]]
Chk 9849 [[123, 139, 354, 606], [276, 133, 479, 629]]
Chk 9850 [[62, 14, 176, 414], [422, 5, 592, 337], [65, 0, 383, 385]]
Chk 9851 [[3, 137, 159, 412], [94, 119, 357, 421], [480, 101, 639, 424], [226, 112, 531, 427], [157, 63, 269, 226]]
Chk 9852 [[136, 153, 347, 631], [211, 87, 479, 630]]
Chk 9854 [[187, 99, 432, 632], [60, 82, 222, 417], [5, 240, 56, 307]]
Chk 9855 [[77, 91, 337, 494], [264, 111, 514, 499]]
Chk 9856 [[78, 216, 284, 399], [379, 59, 574, 410], [0, 178, 156, 396]]
Chk 9857 [[130, 77, 386, 459], [255, 81, 537, 477]]
Chk 9858 [[267, 105, 438, 347], [99, 196, 245, 360], [88, 64, 140, 182], [0, 137, 79, 362], [31, 71, 100, 150], [376, 53, 446, 169]]
Chk 9859 [[235, 29, 448, 420], [15, 100, 267, 426], [425, 10, 639, 418]]
Chk 9860 [[225, 76, 379, 632], [57, 33, 244, 632]]
Chk 9864 [[314, 60, 553, 397], [75, 112, 226, 452], [554, 0, 638, 75]]
Chk 9865 [[352, 134, 483, 479], [194, 121, 325, 471]]
Chk 9866 [[238, 45, 315, 244], [24, 43, 149, 301], [406, 64, 528, 382]]
Chk 9867 [[82, 119, 272, 429], [183, 49, 277, 249], [356, 58, 477, 430], [478, 15, 570, 247]]
Chk 9869 [[417, 48, 626, 353], [157, 90, 288, 386], [86, 42, 174, 340], [54, 58, 306, 382]]
Chk 9870 [[92, 76, 481, 423], [242, 58, 513, 363], [384, 34, 505, 272]]
Chk 9871 [[203, 150, 395, 405], [2, 129, 205, 381], [462, 91, 639, 412]]
Chk 9872 [[2, 0, 280, 473], [180, 65, 342, 412], [275, 0, 504, 308]]
Chk 9874 [[336, 63, 533, 344], [4, 85, 275, 361]]
Chk 9875 [[151, 59, 275, 374], [350, 48, 451, 374]]
Chk 9876 [[430, 0, 636, 269], [0, 2, 198, 277], [125, 53, 187, 116]]
Chk 9877 [[239, 100, 350, 365], [0, 113, 122, 399], [528, 269, 639, 417]]
Chk 9878 [[422, 155, 597, 347], [254, 136, 410, 399], [29, 145, 227, 383], [528, 309, 639, 389]]
Chk 9879 [[137, 179, 261, 439], [219, 141, 435, 480]]
Chk 9880 [[258, 74, 468, 399], [0, 66, 342, 631]]
Chk 9881 [[63, 124, 245, 469], [497, 130, 630, 225], [24, 272, 213, 451], [368, 109, 505, 420]]
Chk 9882 [[459, 274, 582, 393], [150, 124, 453, 407], [0, 22, 83, 353], [80, 177, 191, 381], [323, 187, 460, 399]]
Chk 9883 [[44, 86, 164, 407], [236, 194, 407, 504], [113, 445, 227, 630]]
Chk 9887 [[342, 141, 499, 378], [13, 224, 191, 388], [1, 169, 62, 286]]
Chk 9888 [[3, 20, 606, 490], [165, 106, 291, 399], [99, 0, 293, 293]]
Chk 9889 [[233, 155, 413, 365], [264, 273, 509, 419]]
Chk 9890 [[56, 99, 232, 403], [317, 117, 501, 426], [462, 126, 639, 418]]
Chk 9891 [[359, 36, 633, 599], [1, 66, 211, 593], [202, 285, 319, 437], [46, 239, 128, 338]]
Chk 9892 [[38, 93, 307, 344], [105, 80, 203, 195], [97, 27, 498, 369]]
Chk 9894 [[101, 160, 326, 548], [359, 196, 639, 547]]
Chk 9895 [[21, 23, 235, 456], [189, 22, 479, 456], [464, 107, 566, 438], [506, 98, 568, 213], [550, 90, 603, 313], [583, 93, 635, 256]]
Chk 9897 [[216, 107, 320, 475], [331, 37, 559, 470]]
Chk 9898 [[163, 58, 449, 400], [443, 60, 618, 360], [58, 27, 188, 380]]
Chk 9899 [[46, 41, 457, 639], [2, 83, 240, 632]]
Chk 9900 [[334, 35, 591, 391], [214, 41, 449, 282]]
Chk 9901 [[317, 137, 584, 473], [246, 124, 520, 334], [21, 99, 271, 474], [102, 92, 159, 215]]
Chk 9902 [[60, 107, 234, 424], [242, 226, 340, 362], [418, 151, 549, 397], [410, 245, 521, 372], [525, 151, 613, 401]]
Chk 9903 [[0, 0, 391, 328], [329, 2, 635, 296]]
Chk 9904 [[0, 178, 264, 452], [180, 4, 474, 427]]
Chk 9905 [[257, 113, 420, 379], [174, 329, 421, 556], [50, 83, 332, 639]]
Chk 9906 [[252, 45, 365, 410], [363, 43, 483, 393]]
Chk 9907 [[79, 267, 227, 421], [147, 58, 257, 341]]
Chk 9911 [[6, 143, 405, 620], [93, 22, 230, 593]]
Chk 9912 [[190, 64, 379, 369], [124, 123, 262, 369]]
Chk 9913 [[206, 131, 284, 405], [95, 97, 198, 402], [381, 139, 465, 418], [299, 143, 376, 414], [458, 139, 531, 422]]
Chk 9914 [[320, 14, 464, 324], [277, 9, 432, 313], [141, 10, 245, 311]]
Chk 9915 [[231, 29, 483, 426], [25, 46, 422, 419]]
Chk 9916 [[34, 105, 388, 616], [239, 13, 355, 267], [0, 10, 58, 62]]
Chk 9917 [[171, 222, 303, 499], [79, 253, 184, 499]]
Chk 9919 [[0, 31, 156, 421], [103, 53, 257, 373], [251, 14, 409, 371], [390, 0, 605, 423]]
Chk 9920 [[309, 42, 585, 473], [200, 114, 392, 474], [103, 62, 294, 479], [0, 262, 66, 472]]
Chk 9922 [[49, 129, 212, 420], [193, 51, 473, 420], [399, 99, 578, 424]]

Chk 9924 [[152, 224, 380, 632], [329, 278, 409, 480], [404, 438, 475, 552], [1, 317, 85, 637]]
Chk 9925 [[263, 120, 378, 367], [378, 125, 507, 340], [3, 158, 240, 397]]
Chk 9927 [[286, 39, 417, 277], [130, 14, 268, 276]]
Chk 9929 [[201, 115, 485, 518], [279, 282, 457, 593]]
Chk 9931 [[26, 177, 179, 387], [325, 23, 479, 456]]
Chk 9932 [[191, 117, 472, 417], [0, 32, 200, 421], [470, 4, 639, 425]]
Chk 9933 [[1, 51, 160, 336], [224, 126, 537, 393]]
Chk 9934 [[215, 141, 351, 470], [71, 139, 365, 465]]
Chk 9935 [[122, 140, 258, 294], [47, 149, 173, 323], [322, 130, 431, 465], [400, 180, 466, 255]]
Chk 9937 [[35, 55, 215, 474], [287, 106, 421, 479], [400, 85, 639, 470], [192, 95, 309, 479]]
Chk 9939 [[136, 30, 436, 324], [306, 0, 382, 128], [484, 0, 590, 285], [512, 1, 639, 315], [208, 4, 315, 252], [429, 55, 538, 263]]
Chk 9940 [[145, 46, 378, 346], [207, 212, 332, 380]]
Chk 9941 [[135, 244, 312, 402], [377, 171, 560, 393], [270, 40, 353, 212], [159, 48, 235, 213], [335, 51, 435, 208], [80, 24, 154, 208], [0, 47, 76, 230], [34, 180, 147, 399]]
Chk 9942 [[97, 242, 416, 639], [80, 107, 294, 607]]
Chk 9943 [[0, 0, 241, 419], [195, 60, 347, 242], [460, 65, 515, 133], [408, 66, 639, 288]]
Chk 9944 [[318, 357, 500, 478], [496, 355, 639, 479]]
Chk 9945 [[103, 96, 220, 398], [69, 94, 158, 361], [323, 120, 426, 338]]
Chk 9947 [[253, 62, 398, 497], [77, 73, 237, 501], [324, 83, 384, 172]]
Chk 9948 [[340, 112, 489, 420], [182, 142, 318, 421]]
Chk 9950 [[206, 47, 309, 415], [343, 58, 532, 329], [519, 49, 632, 417], [25, 55, 219, 325]]
Chk 9951 [[256, 150, 428, 368], [113, 212, 263, 357], [0, 183, 101, 374], [112, 0, 169, 67], [442, 0, 502, 53], [72, 4, 129, 66]]
Chk 9953 [[0, 8, 343, 419], [304, 80, 598, 426], [126, 178, 423, 420]]
Chk 9954 [[213, 124, 318, 408], [88, 59, 188, 422], [309, 264, 374, 417]]
Chk 9955 [[0, 39, 205, 332], [276, 27, 498, 327]]
Chk 9956 [[530, 169, 639, 396], [256, 124, 435, 419], [269, 114, 375, 325], [361, 146, 476, 397]]
Chk 9959 [[280, 61, 445, 389], [431, 81, 601, 414], [0, 29, 188, 425], [147, 103, 304, 384]]
Chk 9960 [[261, 76, 520, 415], [190, 266, 387, 421], [0, 150, 206, 421]]
Chk 9962 [[118, 220, 240, 420], [213, 143, 276, 306], [238, 217, 328, 322], [523, 144, 631, 413], [451, 166, 519, 296], [341, 182, 427, 321], [0, 183, 101, 405]]
Chk 9965 [[130, 67, 287, 329], [281, 33, 404, 332], [326, 14, 477, 328]]
Chk 9967 [[0, 40, 244, 374], [266, 38, 497, 369]]
Chk 9970 [[310, 133, 545, 333], [134, 111, 263, 299]]
Chk 9971 [[314, 207, 399, 366], [0, 141, 76, 410], [192, 154, 306, 368]]
Chk 9972 [[138, 138, 285, 421], [385, 140, 492, 369], [277, 137, 416, 386]]
Chk 9975 [[145, 100, 436, 557], [163, 126, 428, 606]]
Chk 9976 [[186, 150, 312, 489], [303, 286, 454, 625], [0, 101, 374, 629]]
Chk 9977 [[154, 30, 304, 323], [286, 25, 390, 283], [321, 8, 638, 416], [44, 88, 109, 261], [0, 67, 53, 269], [296, 24, 481, 355]]
Chk 9978 [[414, 181, 488, 287], [469, 175, 547, 288], [540, 174, 603, 279], [339, 176, 413, 287], [221, 150, 401, 426]]
Chk 9979 [[28, 166, 281, 638], [177, 0, 478, 639]]
Chk 9980 [[240, 18, 451, 327], [17, 42, 240, 331]]
Chk 9981 [[228, 149, 362, 421], [337, 139, 469, 408], [450, 116, 530, 339], [322, 152, 380, 349]]
Chk 9982 [[210, 94, 358, 284], [342, 151, 456, 478]]
Chk 9983 [[213, 132, 479, 389], [85, 268, 285, 389], [364, 19, 551, 388], [143, 29, 292, 284]]
Chk 9984 [[0, 0, 328, 479], [174, 115, 469, 471]]
Chk 9992 [[12, 1, 88, 80], [369, 84, 533, 329], [85, 14, 197, 234], [0, 66, 115, 278], [0, 229, 230, 639]]
Chk 9993 [[221, 194, 352, 337], [222, 168, 427, 426], [323, 88, 639, 421]]
Chk 9994 [[1, 107, 371, 422], [270, 240, 525, 422]]
Chk 9996 [[189, 263, 301, 506], [263, 112, 470, 497]]
Chk 9997 [[8, 24, 179, 398], [145, 28, 319, 376], [264, 36, 418, 345], [391, 26, 635, 299], [552, 35, 639, 256], [479, 4, 547, 102], [210, 0, 261, 53]]
Chk 9999 [[460, 45, 636, 472], [11, 1, 207, 413], [9, 355, 191, 479]]
Chk 10000 [[352, 163, 514, 341], [331, 180, 406, 301], [26, 159, 221, 383], [491, 176, 597, 252], [588, 184, 639, 286], [508, 209, 569, 263]]
Chk 10001 [[110, 22, 366, 420], [329, 125, 639, 418]]
Chk 10002 [[226, 68, 326, 362], [101, 74, 159, 319], [504, 98, 635, 473], [509, 54, 575, 176], [546, 62, 612, 169], [470, 65, 528, 128], [352, 112, 409, 179]]
Chk 10003 [[125, 115, 275, 370], [242, 77, 336, 373], [311, 90, 432, 374]]
Chk 10004 [[91, 73, 258, 414], [337, 22, 477, 403], [459, 112, 549, 374]]
Chk 10005 [[0, 50, 343, 369], [198, 28, 414, 316], [410, 41, 499, 232]]
Chk 10006 [[26, 42, 315, 363], [1, 237, 225, 474], [309, 1, 628, 254], [515, 2, 639, 265]]
Chk 10007 [[86, 171, 363, 425], [0, 68, 182, 425], [157, 78, 227, 184], [360, 69, 558, 381], [351, 300, 464, 424]]
Chk 10008 [[164, 181, 495, 489], [1, 217, 235, 483], [446, 138, 516, 301]]
Chk 10009 [[284, 116, 407, 376], [520, 97, 591, 293], [576, 103, 639, 281], [83, 110, 212, 369]]
Chk 10011 [[241, 163, 399, 331], [408, 179, 559, 327], [74, 166, 246, 336]]
Chk 10014 [[98, 120, 329, 472], [309, 96, 521, 478]]
Chk 10015 [[435, 80, 627, 469], [330, 148, 459, 465], [27, 160, 158, 378]]
Chk 10016 [[100, 216, 265, 513], [220, 251, 384, 526], [315, 232, 426, 520]]
Chk 10017 [[70, 3, 381, 420], [317, 154, 609, 420]]
Chk 10018 [[226, 176, 368, 426], [219, 364, 325, 471], [76, 234, 272, 480]]
Chk 10019 [[207, 137, 379, 472], [1, 181, 86, 454]]
Chk 10020 [[150, 86, 374, 493], [140, 41, 286, 341]]
Chk 10021 [[107, 80, 276, 476], [259, 72, 445, 429], [414, 87, 508, 355], [465, 56, 630, 449], [2, 76, 72, 447], [585, 113, 639, 358]]
Chk 10022 [[227, 263, 317, 531], [139, 262, 237, 521]]
Chk 10023 [[1, 155, 262, 517], [0, 1, 115, 196], [245, 0, 483, 545]]
Chk 10024 [[20, 52, 407, 609], [407, 8, 622, 612], [108, 0, 253, 51], [241, 0, 359, 51], [372, 0, 428, 55], [393, 232, 448, 482], [578, 174, 639, 491]]
Chk 10025 [[7, 1, 124, 115], [395, 0, 632, 456], [8, 3, 358, 127]]
Chk 10026 [[500, 49, 631, 386], [317, 82, 450, 426], [431, 68, 490, 228], [94, 49, 209, 356], [544, 54, 633, 366], [107, 108, 334, 426], [283, 155, 335, 219]]
Chk 10027 [[80, 116, 223, 573], [252, 174, 350, 483]]
Chk 10028 [[9, 191, 182, 433], [1, 336, 110, 472], [294, 115, 436, 266], [432, 180, 638, 411]]
Chk 10029 [[120, 42, 395, 214], [1, 1, 499, 358], [164, 40, 238, 126]]
Chk 10031 [[375, 46, 570, 396], [23, 194, 227, 391], [0, 138, 74, 400]]
Chk 10033 [[319, 95, 453, 298], [266, 216, 338, 280], [484, 0, 639, 420], [19, 32, 191, 418]]
Chk 10034 [[36, 23, 347, 367], [184, 62, 639, 405]]
Chk 10035 [[200, 116, 391, 378], [415, 217, 597, 375], [552, 158, 639, 377], [365, 221, 451, 359], [354, 99, 414, 184], [428, 63, 482, 189], [451, 167, 507, 233], [219, 104, 273, 173]]
Chk 10036 [[94, 51, 212, 410], [200, 60, 313, 390], [312, 87, 390, 370], [374, 74, 465, 356], [459, 80, 540, 368]]
Chk 10037 [[87, 94, 241, 632], [0, 61, 97, 639], [221, 100, 366, 629]]
Chk 10038 [[84, 39, 263, 363], [268, 15, 519, 402], [342, 59, 400, 174], [3, 62, 98, 239], [226, 53, 356, 228], [280, 54, 360, 185]]
Chk 10040 [[58, 355, 267, 613], [130, 262, 360, 632], [129, 43, 224, 118]]
Chk 10041 [[143, 63, 259, 403], [387, 65, 487, 438], [259, 54, 391, 407]]
Chk 10042 [[402, 19, 611, 416], [511, 32, 639, 395], [399, 172, 532, 373], [195, 62, 328, 311], [205, 13, 394, 422]]
Chk 10043 [[255, 122, 474, 332], [74, 15, 292, 358]]
Chk 10044 [[0, 90, 137, 421], [350, 108, 419, 358], [389, 82, 487, 341]]
Chk 10045 [[123, 44, 350, 471], [328, 93, 452, 370]]
Chk 10047 [[295, 154, 468, 371], [72, 269, 530, 461]]
Chk 10049 [[404, 149, 509, 385], [80, 130, 305, 416]]
Chk 10051 [[0, 156, 124, 479], [410, 131, 555, 472], [38, 169, 123, 478]]
Chk 10052 [[0, 177, 182, 630], [135, 240, 351, 632], [242, 275, 315, 370]]
Chk 10053 [[294, 1, 639, 421], [1, 205, 130, 422], [141, 94, 398, 425]]
Chk 10054 [[216, 191, 421, 623], [105, 270, 222, 464]]
Chk 10055 [[317, 143, 498, 361], [190, 126, 335, 305]]
Chk 10056 [[16, 185, 79, 297], [63, 180, 153, 296], [185, 243, 619, 425], [273, 103, 332, 180], [202, 66, 272, 359]]
Chk 10057 [[266, 77, 384, 422], [449, 98, 639, 421], [0, 47, 215, 423]]
Chk 10058 [[250, 79, 391, 399], [0, 178, 95, 419], [506, 111, 569, 292], [104, 97, 639, 295]]
Chk 10059 [[178, 85, 311, 311], [532, 78, 629, 294], [78, 7, 296, 342], [301, 133, 381, 264], [19, 144, 88, 277], [51, 145, 107, 278]]
Chk 10060 [[92, 261, 202, 511], [160, 240, 217, 385], [275, 108, 402, 342]]
Chk 10061 [[213, 160, 323, 297], [131, 175, 254, 337], [11, 69, 181, 473], [461, 156, 629, 355]]
Chk 10062 [[172, 56, 430, 434], [421, 167, 640, 419], [120, 47, 246, 272]]
Chk 10063 [[445, 60, 620, 480], [133, 81, 293, 471], [275, 83, 446, 479]]

Chk 10064 [[436, 227, 628, 422], [188, 48, 430, 399]]
Chk 10065 [[347, 88, 637, 419], [377, 120, 495, 407]]
Chk 10066 [[158, 163, 343, 359], [375, 23, 564, 310]]
Chk 10067 [[202, 21, 270, 110], [343, 24, 431, 130], [0, 0, 177, 269], [285, 168, 499, 374], [412, 1, 499, 142]]
Chk 10070 [[251, 52, 405, 379], [422, 100, 579, 386], [1, 59, 173, 420], [7, 22, 101, 295]]
Chk 10072 [[251, 242, 422, 630], [121, 181, 326, 639]]
Chk 10073 [[16, 339, 271, 543], [127, 280, 291, 602], [239, 232, 367, 513], [162, 99, 250, 270]]
Chk 10074 [[133, 184, 330, 639], [398, 360, 467, 497], [305, 410, 360, 501]]
Chk 10076 [[116, 258, 275, 600], [269, 352, 418, 633]]
Chk 10077 [[117, 115, 302, 328], [287, 52, 358, 263], [319, 72, 534, 322]]
Chk 10079 [[186, 61, 412, 625], [55, 228, 204, 436], [0, 429, 271, 639], [109, 177, 165, 263], [152, 177, 209, 313]]
Chk 10081 [[212, 1, 494, 290], [252, 1, 499, 368]]
Chk 10082 [[113, 118, 327, 630], [279, 61, 426, 639]]
Chk 10084 [[62, 98, 306, 420], [304, 81, 621, 419]]
Chk 10086 [[188, 1, 507, 639], [88, 193, 395, 461]]
Chk 10087 [[255, 81, 477, 332], [0, 0, 225, 332], [135, 0, 273, 250]]
Chk 10088 [[84, 102, 276, 479], [249, 97, 469, 479]]
Chk 10089 [[181, 105, 281, 328], [321, 82, 449, 327], [60, 105, 198, 328]]
Chk 10090 [[341, 165, 572, 421], [136, 15, 348, 420], [577, 123, 639, 419]]
Chk 10093 [[151, 262, 305, 474], [236, 200, 393, 358], [482, 208, 578, 341], [530, 217, 639, 428], [429, 167, 484, 259], [254, 184, 305, 253], [149, 149, 210, 258], [40, 152, 92, 249]]
Chk 10094 [[100, 121, 222, 420], [232, 135, 363, 409], [0, 143, 104, 370]]
Chk 10095 [[306, 50, 608, 604], [125, 4, 412, 498]]
Chk 10096 [[146, 51, 420, 292], [0, 0, 158, 292]]
Chk 10099 [[153, 64, 442, 629], [5, 12, 314, 630]]
Chk 10100 [[300, 95, 467, 448], [186, 157, 252, 229], [126, 182, 379, 497], [225, 141, 276, 209], [0, 132, 136, 497]]
Chk 10102 [[438, 148, 611, 404], [78, 178, 249, 424], [222, 135, 342, 424], [327, 163, 434, 424]]
Chk 10103 [[80, 1, 396, 293], [258, 92, 437, 342]]
Chk 10104 [[340, 156, 436, 293], [267, 148, 367, 278], [3, 115, 136, 367], [436, 115, 632, 463]]
Chk 10105 [[153, 129, 356, 407], [266, 129, 436, 413], [411, 127, 488, 412], [454, 138, 632, 420]]
Chk 10106 [[195, 152, 420, 601], [389, 203, 611, 611], [0, 130, 238, 611]]
Chk 10108 [[171, 77, 365, 428], [339, 71, 600, 473], [515, 141, 630, 226], [0, 55, 91, 473]]
Chk 10109 [[205, 47, 408, 370], [35, 41, 214, 370]]
Chk 10110 [[292, 127, 378, 408], [237, 148, 314, 414], [55, 146, 161, 419]]
Chk 10111 [[0, 33, 384, 629], [143, 5, 329, 321]]
Chk 10113 [[193, 161, 304, 497], [238, 146, 443, 639], [15, 187, 184, 632]]
Chk 10114 [[19, 87, 233, 421], [332, 50, 619, 420], [268, 91, 400, 426]]
Chk 10115 [[247, 181, 342, 479], [283, 177, 432, 479], [419, 168, 577, 468], [136, 161, 281, 472]]
Chk 10116 [[215, 111, 303, 405], [130, 129, 210, 411], [55, 127, 169, 428], [0, 11, 122, 416], [504, 114, 622, 423]]
Chk 10117 [[410, 24, 637, 319], [2, 14, 349, 472]]
Chk 10118 [[99, 92, 207, 347], [207, 87, 297, 332], [300, 97, 444, 338]]
Chk 10119 [[0, 142, 404, 630], [148, 264, 427, 632]]
Chk 10122 [[4, 47, 201, 313], [365, 28, 639, 431], [341, 101, 425, 173]]
Chk 10123 [[192, 128, 294, 387], [388, 190, 466, 356], [37, 135, 176, 379]]
Chk 10124 [[35, 147, 268, 370], [394, 189, 455, 285]]
Chk 10125 [[397, 39, 639, 339], [106, 37, 176, 144], [96, 56, 275, 335], [0, 45, 113, 332], [245, 22, 402, 336]]
Chk 10126 [[4, 0, 430, 470], [191, 21, 522, 475]]
Chk 10127 [[179, 76, 322, 304], [45, 13, 142, 267], [345, 32, 421, 190], [463, 4, 577, 213]]
Chk 10131 [[93, 41, 262, 604], [224, 187, 332, 467], [3, 198, 117, 458]]
Chk 10132 [[200, 83, 370, 255], [68, 135, 305, 419], [233, 253, 500, 419]]
Chk 10133 [[193, 126, 325, 393], [310, 129, 455, 410]]
Chk 10134 [[247, 51, 396, 420], [453, 84, 580, 422], [85, 35, 217, 418]]
Chk 10135 [[0, 38, 639, 473], [460, 62, 639, 325]]
Chk 10136 [[310, 116, 420, 422], [112, 116, 261, 418]]
Chk 10137 [[223, 200, 358, 483], [41, 161, 211, 479]]
Chk 10139 [[342, 119, 490, 407], [41, 80, 139, 312], [249, 140, 320, 375], [163, 26, 352, 375], [209, 59, 298, 341]]
Chk 10140 [[273, 103, 361, 352], [499, 118, 563, 421], [11, 32, 151, 464]]
Chk 10142 [[189, 120, 404, 376], [135, 86, 352, 364]]
Chk 10143 [[81, 46, 319, 387], [296, 2, 573, 365]]
Chk 10145 [[376, 39, 612, 473], [139, 90, 377, 408]]
Chk 10146 [[13, 206, 257, 630], [201, 313, 340, 551]]
Chk 10148 [[220, 152, 348, 365], [129, 63, 257, 374]]
Chk 10149 [[136, 299, 202, 473], [526, 295, 582, 479], [355, 286, 457, 473], [465, 304, 519, 479]]
Chk 10151 [[290, 0, 416, 313], [200, 92, 332, 398]]
Chk 10152 [[446, 19, 605, 201], [309, 4, 476, 201]]
Chk 10153 [[200, 85, 313, 445], [286, 130, 435, 377], [401, 190, 622, 469], [403, 418, 546, 472]]
Chk 10155 [[0, 3, 320, 471], [314, 0, 637, 477]]
Chk 10156 [[238, 46, 425, 370], [44, 35, 296, 367]]
Chk 10158 [[106, 414, 234, 629], [320, 318, 457, 630], [62, 27, 415, 639]]
Chk 10159 [[61, 77, 278, 479], [318, 44, 517, 480]]
Chk 10160 [[396, 46, 463, 162], [195, 5, 297, 262], [266, 44, 326, 165], [71, 45, 219, 271], [9, 43, 64, 166], [61, 23, 114, 80], [324, 37, 399, 161], [12, 51, 170, 268]]
Chk 10161 [[194, 38, 396, 368], [223, 2, 499, 369], [378, 0, 472, 152]]
Chk 10162 [[381, 36, 639, 353], [23, 82, 281, 369]]
Chk 10164 [[51, 145, 315, 628], [316, 85, 422, 333], [55, 62, 128, 177], [105, 50, 159, 132], [225, 103, 308, 238]]
Chk 10165 [[90, 93, 294, 367], [357, 76, 482, 373], [431, 117, 516, 363]]
Chk 10166 [[53, 300, 227, 632], [366, 96, 492, 631]]
Chk 10168 [[2, 76, 288, 479], [267, 159, 331, 394], [339, 118, 639, 473]]
Chk 10169 [[263, 145, 351, 328], [345, 123, 432, 356], [180, 139, 262, 347]]
Chk 10171 [[211, 107, 332, 280], [155, 174, 252, 290], [0, 167, 157, 377]]
Chk 10172 [[241, 147, 332, 408], [310, 123, 417, 416], [416, 114, 504, 416], [560, 110, 638, 400]]
Chk 10173 [[325, 132, 537, 474], [473, 165, 639, 474], [384, 231, 448, 338]]
Chk 10174 [[134, 96, 390, 422], [256, 109, 380, 359]]
Chk 10175 [[129, 81, 361, 434], [322, 70, 446, 437], [450, 4, 585, 263], [129, 0, 217, 101], [161, 0, 214, 86], [0, 0, 114, 98]]
Chk 10176 [[117, 28, 275, 484], [0, 103, 131, 494], [323, 180, 374, 285], [245, 209, 311, 292]]
Chk 10177 [[175, 286, 350, 585], [0, 16, 180, 319], [0, 155, 231, 542]]
Chk 10180 [[142, 155, 286, 588], [61, 325, 218, 616], [269, 292, 358, 614], [149, 129, 235, 475]]
Chk 10181 [[164, 117, 285, 416], [324, 146, 433, 389], [360, 425, 479, 507], [112, 321, 362, 626]]
Chk 10182 [[339, 36, 638, 471], [61, 33, 288, 400]]
Chk 10183 [[366, 67, 482, 304], [128, 189, 253, 327], [248, 207, 432, 422], [255, 73, 324, 311]]
Chk 10184 [[150, 118, 304, 402], [263, 137, 378, 393], [323, 127, 481, 406]]
Chk 10185 [[79, 176, 187, 432], [309, 181, 413, 479], [403, 126, 593, 471]]
Chk 10186 [[5, 0, 297, 480], [357, 129, 563, 475], [273, 0, 628, 474]]
Chk 10188 [[277, 31, 462, 369], [53, 14, 268, 370]]
Chk 10189 [[153, 144, 255, 450], [94, 282, 166, 455], [18, 260, 106, 455], [243, 131, 380, 450]]
Chk 10190 [[444, 140, 639, 464], [390, 121, 502, 318], [326, 148, 401, 289], [237, 130, 350, 263], [72, 173, 149, 276], [0, 160, 204, 479]]
Chk 10191 [[87, 47, 202, 318], [461, 38, 594, 329]]
Chk 10192 [[122, 55, 491, 416], [98, 121, 262, 419]]
Chk 10193 [[574, 14, 639, 421], [63, 139, 394, 417], [72, 188, 135, 354], [65, 137, 223, 352], [174, 51, 275, 247]]
Chk 10194 [[29, 73, 298, 473], [390, 58, 639, 470]]
Chk 10195 [[477, 242, 583, 361], [35, 231, 198, 448], [272, 148, 365, 282], [364, 181, 468, 344], [290, 234, 425, 392], [505, 235, 639, 375], [3, 157, 135, 323], [243, 214, 341, 355]]
Chk 10197 [[211, 81, 426, 365], [447, 163, 628, 365], [384, 88, 442, 189], [457, 104, 515, 220], [180, 84, 260, 225], [245, 103, 296, 223], [2, 87, 59, 205]]
Chk 10198 [[107, 92, 321, 330], [284, 154, 421, 364]]
Chk 10199 [[2, 312, 169, 632], [283, 79, 424, 534]]
Chk 10200 [[321, 72, 422, 338], [473, 179, 607, 403], [99, 186, 537, 406], [374, 26, 426, 112], [430, 41, 495, 114], [235, 70, 301, 130], [145, 45, 218, 124], [0, 18, 51, 103]]
Chk 10201 [[64, 94, 225, 590], [221, 101, 415, 535]]
Chk 10203 [[214, 124, 372, 573], [34, 252, 264, 588]]
Chk 10204 [[81, 43, 299, 357], [340, 76, 416, 248], [418, 91, 487, 262], [437, 33, 589, 424], [0, 88, 82, 194]]
Chk 10205 [[156, 155, 252, 433], [62, 122, 126, 261], [114, 165, 165, 266], [7, 143, 88, 431]]
Chk 10206 [[10, 129, 133, 510], [310, 154, 418, 340]]
Chk 10207 [[17, 65, 359, 612], [334, 2, 426, 389]]
Chk 10208 [[239, 256, 470, 471], [0, 0, 352, 480]]
Chk 10209 [[351, 52, 515, 417], [216, 61, 330, 408], [123, 59, 245, 412], [0, 57, 171, 409]]

Chk 10210 [[2, 25, 260, 354], [201, 82, 382, 327]]
Chk 10211 [[202, 105, 394, 410], [486, 138, 560, 259], [443, 134, 522, 266], [444, 228, 623, 425], [152, 180, 208, 252], [81, 185, 138, 250], [586, 119, 639, 252]]
Chk 10212 [[506, 122, 631, 490], [287, 122, 405, 478], [395, 60, 516, 473]]
Chk 10213 [[12, 68, 246, 475], [386, 96, 593, 473], [389, 25, 483, 134]]
Chk 10214 [[398, 12, 555, 322], [295, 0, 443, 325], [184, 43, 331, 344], [106, 18, 234, 324]]
Chk 10216 [[132, 56, 551, 452], [44, 82, 322, 449]]
Chk 10217 [[244, 152, 419, 382], [0, 193, 130, 419], [275, 0, 373, 76], [91, 247, 247, 417]]
Chk 10218 [[124, 102, 316, 631], [292, 128, 442, 638]]
Chk 10219 [[5, 4, 264, 417], [331, 45, 639, 415]]
Chk 10220 [[280, 48, 428, 479], [133, 0, 333, 482]]
Chk 10222 [[303, 108, 528, 504], [21, 117, 192, 452]]
Chk 10224 [[127, 177, 329, 332], [275, 92, 468, 298]]
Chk 10227 [[247, 53, 639, 471], [0, 64, 385, 479]]
Chk 10228 [[324, 57, 555, 425], [58, 191, 230, 452], [159, 0, 233, 132], [0, 2, 59, 122]]
Chk 10229 [[2, 75, 148, 420], [496, 63, 639, 346], [209, 83, 348, 478], [546, 141, 639, 289]]
Chk 10230 [[162, 157, 242, 497], [226, 141, 333, 480], [268, 164, 332, 329]]
Chk 10231 [[273, 122, 347, 281], [509, 132, 638, 422], [524, 126, 618, 250], [227, 126, 298, 296], [87, 123, 161, 202], [332, 147, 559, 473], [34, 129, 99, 205]]
Chk 10232 [[205, 0, 324, 233], [142, 42, 219, 178], [0, 175, 117, 370], [280, 119, 458, 320], [143, 51, 330, 374]]
Chk 10233 [[0, 2, 332, 371], [258, 66, 336, 256], [311, 20, 488, 424]]
Chk 10234 [[261, 162, 368, 414], [510, 168, 583, 426], [376, 210, 474, 422], [238, 48, 312, 114], [577, 183, 629, 268], [530, 26, 592, 87]]
Chk 10235 [[205, 159, 374, 492], [82, 168, 197, 387], [167, 196, 275, 289], [11, 177, 69, 373], [0, 284, 301, 500]]
Chk 10237 [[220, 6, 546, 458], [43, 200, 280, 453], [0, 17, 64, 106], [99, 14, 211, 104], [217, 15, 314, 105], [452, 7, 560, 97], [446, 0, 554, 82], [535, 0, 639, 86]]
Chk 10239 [[6, 0, 371, 243], [458, 1, 635, 229], [0, 106, 105, 290], [390, 0, 638, 222], [102, 0, 228, 76]]
Chk 10240 [[46, 182, 196, 432], [484, 43, 639, 456], [65, 121, 278, 421], [480, 23, 548, 173], [194, 32, 264, 94], [3, 0, 97, 164], [249, 71, 401, 442], [274, 30, 353, 146]]
Chk 10242 [[72, 228, 307, 471], [205, 177, 312, 479], [76, 188, 175, 346]]
Chk 10243 [[570, 113, 639, 422], [112, 172, 197, 421], [0, 138, 53, 420], [251, 157, 313, 404], [178, 166, 276, 425], [307, 159, 377, 233]]
Chk 10244 [[0, 38, 369, 421], [365, 87, 639, 420]]
Chk 10245 [[53, 109, 197, 479], [281, 135, 399, 479], [400, 136, 519, 475]]
Chk 10246 [[185, 217, 300, 397], [512, 93, 576, 350], [45, 59, 175, 404], [352, 64, 468, 372], [467, 109, 550, 365]]
Chk 10247 [[30, 43, 371, 454], [409, 219, 637, 475], [0, 169, 55, 274], [520, 124, 583, 295], [217, 183, 301, 303], [19, 167, 126, 275], [50, 194, 156, 321], [254, 215, 323, 329]]
Chk 10250 [[61, 349, 173, 615], [25, 272, 98, 460], [208, 244, 336, 569], [340, 393, 397, 516], [159, 375, 232, 511], [250, 292, 351, 582]]
Chk 10251 [[457, 210, 639, 473], [223, 187, 429, 479], [66, 187, 297, 479]]
Chk 10252 [[148, 97, 289, 254], [0, 117, 247, 479], [384, 86, 521, 240]]
Chk 10253 [[85, 89, 335, 419], [1, 326, 103, 421], [418, 197, 613, 426]]
Chk 10255 [[332, 244, 500, 472], [279, 257, 390, 479], [235, 333, 293, 456], [503, 217, 637, 475], [53, 350, 125, 452], [78, 422, 145, 479]]
Chk 10256 [[409, 15, 561, 421], [194, 65, 412, 365]]
Chk 10259 [[0, 70, 161, 333], [124, 75, 220, 212], [376, 82, 437, 173], [216, 81, 374, 330], [335, 127, 500, 334]]
Chk 10260 [[110, 247, 241, 422], [178, 161, 424, 425], [0, 43, 414, 639], [417, 265, 479, 376], [96, 134, 185, 262], [271, 194, 421, 378]]
Chk 10261 [[126, 112, 380, 550], [49, 6, 212, 468]]
Chk 10262 [[241, 104, 627, 509], [1, 73, 279, 504]]
Chk 10264 [[2, 62, 322, 417], [281, 64, 388, 288], [377, 85, 483, 253], [450, 103, 510, 228], [0, 42, 74, 246]]
Chk 10265 [[81, 67, 185, 337], [342, 108, 424, 243], [478, 74, 555, 359], [249, 86, 328, 311], [180, 97, 250, 309], [413, 116, 486, 306], [196, 204, 284, 312]]
Chk 10267 [[132, 328, 333, 562], [334, 350, 425, 532], [188, 106, 355, 495], [72, 277, 154, 347]]
Chk 10268 [[83, 219, 155, 479], [201, 298, 376, 479], [374, 202, 476, 452], [433, 0, 497, 78], [54, 0, 117, 108]]
Chk 10269 [[414, 116, 608, 260], [382, 244, 623, 470], [34, 120, 192, 367], [184, 91, 311, 272]]
Chk 10270 [[141, 2, 472, 351], [0, 104, 161, 352], [416, 190, 498, 351], [72, 221, 211, 356]]
Chk 10271 [[201, 61, 469, 419], [302, 60, 373, 166], [378, 58, 563, 395]]
Chk 10273 [[195, 96, 356, 358], [220, 102, 447, 346], [397, 77, 472, 271], [506, 79, 587, 290], [106, 91, 236, 364]]
Chk 10275 [[436, 70, 628, 475], [4, 12, 160, 460], [179, 129, 321, 474]]
Chk 10276 [[64, 6, 558, 399], [0, 37, 172, 273], [395, 2, 487, 163]]
Chk 10277 [[95, 0, 316, 364], [0, 45, 105, 339], [282, 33, 476, 411], [239, 11, 639, 423], [352, 0, 419, 102], [458, 0, 575, 107], [0, 262, 140, 407], [65, 74, 163, 385]]
Chk 10278 [[263, 45, 616, 472], [146, 21, 438, 472], [7, 148, 147, 341], [0, 221, 56, 292], [348, 112, 464, 479]]
Chk 10279 [[352, 88, 474, 389], [195, 106, 386, 340], [6, 90, 86, 297]]
Chk 10281 [[34, 211, 273, 493], [283, 218, 406, 491]]
Chk 10282 [[62, 70, 377, 401], [330, 116, 595, 440]]
Chk 10286 [[293, 73, 447, 420], [126, 54, 256, 421], [426, 74, 544, 418], [165, 92, 297, 415], [217, 47, 358, 189]]
Chk 10290 [[218, 79, 323, 529], [123, 170, 239, 569]]
Chk 10291 [[114, 93, 227, 368], [272, 96, 354, 353]]
Chk 10292 [[132, 4, 374, 492], [1, 324, 116, 492], [90, 351, 189, 499]]
Chk 10293 [[353, 56, 499, 257], [1, 64, 159, 336]]
Chk 10294 [[175, 127, 297, 498], [417, 73, 540, 495], [56, 101, 188, 569], [315, 162, 420, 502]]
Chk 10296 [[264, 208, 377, 506], [137, 168, 238, 487], [221, 169, 285, 467]]
Chk 10298 [[20, 162, 444, 604], [330, 156, 611, 602]]
Chk 10299 [[292, 216, 436, 464], [293, 176, 426, 436], [538, 190, 639, 457]]
Chk 10300 [[0, 38, 253, 459], [403, 141, 493, 484], [405, 0, 511, 487], [107, 0, 355, 266], [80, 0, 137, 130], [1, 254, 455, 607], [0, 0, 81, 244]]
Chk 10302 [[253, 59, 474, 263], [262, 48, 378, 222], [0, 0, 216, 480], [67, 93, 142, 221], [160, 85, 235, 216], [479, 132, 639, 356]]
Chk 10303 [[30, 50, 248, 383], [151, 188, 305, 422]]
Chk 10304 [[334, 97, 463, 353], [239, 157, 309, 317], [131, 150, 237, 368], [8, 147, 90, 330], [559, 85, 639, 368], [462, 115, 513, 270]]
Chk 10306 [[191, 21, 338, 380], [333, 67, 493, 369], [122, 181, 190, 275], [363, 83, 513, 311]]
Chk 10307 [[285, 74, 415, 441], [43, 115, 233, 479], [458, 100, 592, 479]]
Chk 10308 [[536, 94, 639, 394], [149, 35, 349, 398], [110, 110, 241, 286]]
Chk 10310 [[122, 63, 289, 386], [417, 9, 572, 370]]
Chk 10311 [[222, 180, 477, 460], [457, 66, 639, 487], [0, 1, 198, 263], [500, 261, 639, 518], [193, 0, 337, 114], [6, 0, 67, 53], [18, 32, 354, 486]]
Chk 10312 [[282, 315, 430, 632], [30, 275, 220, 621], [184, 87, 353, 433]]
Chk 10314 [[444, 194, 531, 385], [225, 184, 436, 372], [1, 197, 231, 401], [262, 201, 324, 316]]
Chk 10315 [[222, 84, 309, 387], [303, 91, 382, 368], [380, 78, 495, 383], [454, 104, 509, 318], [540, 92, 602, 316]]
Chk 10316 [[518, 12, 639, 317], [199, 2, 296, 261], [105, 59, 273, 341], [160, 28, 213, 99], [100, 62, 359, 339], [92, 155, 244, 328]]
Chk 10318 [[456, 136, 509, 224], [504, 134, 564, 360], [575, 140, 639, 465], [96, 140, 249, 473], [346, 134, 528, 471]]
Chk 10319 [[0, 53, 207, 376], [368, 83, 598, 354]]
Chk 10320 [[28, 3, 471, 442], [367, 57, 585, 482], [234, 0, 409, 55]]
Chk 10321 [[139, 123, 308, 414], [0, 187, 479, 637]]
Chk 10322 [[174, 59, 373, 457], [181, 188, 302, 473], [25, 215, 180, 377], [342, 233, 437, 435], [340, 264, 424, 379], [0, 287, 75, 401]]
Chk 10325 [[266, 149, 373, 431], [132, 189, 278, 467], [95, 150, 190, 417], [8, 144, 86, 398]]
Chk 10326 [[11, 19, 329, 341], [336, 47, 557, 326], [539, 41, 607, 249]]
Chk 10327 [[0, 0, 374, 368], [313, 97, 499, 374]]
Chk 10328 [[208, 0, 412, 594], [295, 359, 421, 559], [65, 119, 308, 564]]
Chk 10331 [[237, 111, 327, 377], [479, 132, 574, 421]]
Chk 10334 [[130, 78, 387, 472], [299, 122, 611, 472]]
Chk 10335 [[130, 134, 280, 537], [317, 13, 382, 174], [356, 286, 595, 575], [295, 224, 563, 608], [73, 70, 263, 205]]

Chk 10336 [[161, 62, 280, 465], [238, 146, 383, 433], [409, 204, 488, 351], [508, 207, 592, 360], [565, 213, 633, 363], [266, 108, 354, 421], [8, 101, 86, 345]]
Chk 10337 [[155, 182, 382, 479], [79, 242, 193, 470]]
Chk 10338 [[272, 37, 520, 421], [240, 11, 395, 330]]
Chk 10339 [[342, 94, 456, 370], [365, 66, 513, 346], [430, 54, 639, 371], [0, 88, 121, 371], [1, 43, 108, 359], [292, 149, 383, 333], [286, 99, 345, 172]]
Chk 10340 [[196, 56, 285, 277], [402, 124, 489, 234]]
Chk 10341 [[267, 260, 504, 482], [0, 139, 348, 522], [193, 114, 329, 448]]
Chk 10342 [[302, 143, 452, 421], [357, 74, 639, 423], [66, 160, 219, 317]]
Chk 10343 [[293, 91, 489, 260], [6, 51, 183, 374], [155, 49, 371, 368], [275, 59, 499, 307]]
Chk 10344 [[0, 47, 325, 474], [313, 70, 613, 471]]
Chk 10345 [[307, 67, 509, 301], [260, 74, 327, 203], [414, 56, 476, 142], [551, 72, 604, 142], [183, 77, 237, 242], [53, 52, 106, 109]]
Chk 10346 [[323, 125, 402, 426], [371, 74, 538, 331], [176, 110, 283, 426]]
Chk 10347 [[206, 2, 384, 366], [35, 28, 294, 367]]
Chk 10348 [[239, 69, 331, 399], [358, 69, 461, 417], [433, 55, 525, 405]]
Chk 10349 [[38, 69, 337, 408], [291, 8, 639, 470], [297, 21, 417, 271]]
Chk 10351 [[491, 74, 619, 362], [303, 102, 370, 293], [105, 220, 339, 473], [325, 207, 426, 390], [1, 150, 76, 306]]
Chk 10354 [[284, 10, 443, 307], [11, 1, 315, 350]]
Chk 10355 [[223, 72, 283, 265], [439, 45, 507, 169], [42, 243, 249, 421], [146, 44, 221, 324], [309, 55, 379, 308], [190, 21, 253, 121]]
Chk 10356 [[341, 146, 532, 317], [149, 167, 314, 347], [3, 174, 143, 306]]
Chk 10357 [[83, 118, 217, 413], [367, 74, 595, 420]]
Chk 10358 [[153, 101, 353, 349], [0, 104, 170, 329], [315, 110, 478, 374]]
Chk 10359 [[29, 2, 212, 328], [192, 0, 500, 328]]
Chk 10360 [[131, 161, 288, 419], [257, 29, 639, 419], [17, 153, 213, 395]]
Chk 10362 [[233, 136, 366, 312], [89, 39, 249, 296], [352, 103, 470, 322]]
Chk 10365 [[76, 88, 327, 354], [307, 25, 435, 335], [406, 170, 501, 314]]
Chk 10366 [[115, 257, 371, 491], [38, 73, 200, 240], [213, 6, 351, 229], [31, 291, 198, 498]]
Chk 10368 [[140, 65, 202, 361], [195, 68, 267, 322], [437, 108, 534, 369], [59, 30, 163, 454]]
Chk 10369 [[7, 138, 584, 337], [5, 237, 427, 450]]
Chk 10371 [[44, 47, 227, 363], [125, 33, 179, 154], [249, 80, 439, 417], [408, 11, 505, 287]]
Chk 10372 [[184, 101, 349, 629], [305, 97, 413, 422]]
Chk 10373 [[0, 54, 364, 418], [188, 98, 526, 473]]
Chk 10374 [[560, 0, 626, 183], [5, 136, 153, 382], [155, 172, 338, 387], [288, 70, 495, 366]]
Chk 10375 [[201, 75, 408, 405], [314, 82, 522, 421], [196, 74, 265, 219], [315, 70, 371, 221], [98, 50, 153, 214], [520, 109, 639, 422], [383, 66, 449, 189]]
Chk 10376 [[150, 44, 526, 631], [466, 75, 571, 406], [91, 85, 171, 294], [5, 69, 82, 311], [395, 82, 477, 361], [140, 20, 308, 393], [101, 173, 176, 332]]
Chk 10378 [[67, 67, 335, 420], [402, 27, 636, 419]]
Chk 10379 [[0, 36, 339, 370], [0, 8, 110, 172], [257, 39, 405, 183], [340, 0, 409, 83]]
Chk 10381 [[402, 188, 493, 369], [166, 63, 389, 426], [257, 48, 520, 419]]
Chk 10382 [[10, 110, 246, 471], [309, 48, 639, 473]]
Chk 10383 [[136, 47, 239, 362], [361, 37, 498, 311], [235, 67, 364, 312]]
Chk 10385 [[29, 142, 320, 478], [277, 36, 629, 478]]
Chk 10386 [[7, 0, 615, 474], [197, 153, 392, 391]]
Chk 10387 [[2, 31, 266, 304], [246, 41, 468, 334], [200, 214, 439, 338], [0, 193, 68, 339], [53, 257, 138, 340]]
Chk 10389 [[267, 39, 387, 344], [359, 31, 533, 345], [97, 73, 167, 129]]
Chk 10390 [[71, 96, 357, 479], [152, 129, 219, 208], [374, 31, 603, 474], [11, 129, 163, 471]]
Chk 10391 [[224, 60, 479, 483], [57, 143, 253, 637]]
Chk 10392 [[404, 132, 600, 465], [337, 97, 474, 281], [218, 95, 346, 232], [19, 121, 178, 363]]
Chk 10393 [[424, 49, 629, 371], [92, 80, 402, 464], [396, 73, 474, 200], [128, 32, 227, 201], [0, 79, 162, 356]]
Chk 10395 [[83, 136, 221, 509], [178, 158, 329, 533]]
Chk 10396 [[263, 27, 510, 628], [38, 15, 273, 639]]
Chk 10399 [[0, 14, 173, 359], [110, 130, 238, 359]]
Chk 10402 [[62, 68, 358, 479], [406, 136, 639, 474]]
Chk 10403 [[0, 1, 353, 373], [158, 140, 340, 374]]
Chk 10405 [[0, 17, 71, 378], [328, 44, 611, 420], [129, 37, 263, 283]]
Chk 10406 [[285, 117, 374, 352], [155, 114, 309, 295], [4, 186, 126, 489]]
Chk 10407 [[43, 232, 191, 421], [172, 247, 396, 426]]
Chk 10408 [[375, 38, 507, 399], [340, 124, 432, 398], [476, 80, 593, 384]]
Chk 10409 [[265, 74, 639, 421], [540, 68, 601, 130], [0, 125, 289, 426], [290, 115, 376, 237]]
Chk 10410 [[328, 31, 593, 350], [100, 11, 370, 346]]
Chk 10411 [[261, 21, 357, 458], [102, 38, 308, 494], [416, 65, 500, 248], [345, 58, 457, 315], [0, 0, 154, 640]]
Chk 10413 [[163, 106, 288, 445], [74, 100, 168, 464]]
Chk 10414 [[107, 50, 212, 351], [163, 60, 231, 376], [329, 88, 441, 383], [205, 33, 397, 401], [411, 68, 496, 357]]
Chk 10415 [[2, 115, 139, 380], [415, 96, 554, 421], [224, 90, 451, 422], [125, 130, 247, 387]]
Chk 10416 [[97, 183, 252, 414], [253, 85, 380, 349], [246, 215, 393, 400]]
Chk 10417 [[259, 204, 380, 388], [470, 157, 639, 479], [138, 176, 265, 400]]
Chk 10418 [[215, 114, 316, 385], [290, 110, 450, 390]]
Chk 10419 [[299, 58, 517, 469], [79, 77, 398, 471], [0, 0, 126, 205]]
Chk 10420 [[246, 132, 465, 448], [45, 57, 245, 450]]
Chk 10422 [[124, 151, 286, 417], [366, 110, 505, 431], [474, 257, 536, 414]]
Chk 10423 [[332, 153, 573, 421], [0, 115, 131, 341], [74, 42, 219, 261], [285, 133, 393, 374], [347, 150, 413, 288], [267, 62, 353, 294]]
Chk 10425 [[284, 35, 539, 333], [574, 80, 627, 239], [205, 127, 263, 243], [8, 154, 231, 345], [516, 93, 568, 244]]
Chk 10427 [[14, 24, 156, 421], [183, 71, 409, 421], [446, 64, 588, 426], [152, 59, 245, 251], [330, 73, 455, 426]]
Chk 10430 [[46, 77, 214, 416], [243, 113, 331, 283], [534, 124, 638, 425], [20, 108, 100, 425], [351, 121, 439, 262]]
Chk 10431 [[116, 58, 326, 304], [347, 84, 532, 347]]
Chk 10433 [[203, 13, 566, 473], [253, 87, 401, 358], [133, 226, 340, 475], [3, 188, 221, 472]]
Chk 10434 [[110, 87, 343, 422], [33, 1, 151, 155], [19, 2, 616, 421], [287, 0, 609, 172]]
Chk 10435 [[395, 0, 639, 417], [374, 26, 499, 249], [0, 59, 236, 419]]
Chk 10437 [[281, 16, 419, 398], [385, 19, 481, 305]]
Chk 10438 [[390, 107, 581, 330], [145, 149, 303, 358], [0, 142, 101, 332]]
Chk 10439 [[196, 87, 302, 297], [171, 264, 399, 545]]
Chk 10443 [[80, 217, 181, 536], [90, 190, 314, 565], [224, 224, 351, 617]]
Chk 10444 [[140, 19, 435, 567], [105, 42, 639, 575]]
Chk 10446 [[151, 184, 425, 477], [0, 187, 206, 475]]
Chk 10448 [[269, 94, 580, 418], [420, 94, 639, 419]]
Chk 10449 [[111, 17, 261, 372], [237, 96, 333, 374], [75, 178, 136, 361]]
Chk 10450 [[123, 44, 283, 443], [232, 111, 411, 459], [0, 177, 88, 422]]
Chk 10451 [[208, 3, 442, 498], [103, 15, 285, 351]]
Chk 10452 [[309, 34, 499, 240], [226, 64, 413, 298], [2, 106, 81, 241]]
Chk 10453 [[350, 160, 463, 362], [58, 100, 313, 421]]
Chk 10455 [[480, 63, 594, 355], [369, 62, 524, 369]]
Chk 10456 [[68, 152, 184, 525], [0, 53, 80, 321], [411, 131, 592, 525]]
Chk 10457 [[214, 6, 406, 573], [215, 305, 341, 597]]
Chk 10458 [[176, 28, 355, 588], [93, 141, 207, 545], [392, 41, 470, 204], [317, 114, 413, 201]]
Chk 10461 [[236, 45, 583, 419], [42, 44, 319, 418], [469, 109, 527, 180], [576, 106, 636, 315], [0, 110, 70, 269], [257, 186, 309, 269], [551, 149, 639, 424]]
Chk 10463 [[340, 123, 449, 381], [340, 81, 563, 473]]
Chk 10464 [[336, 232, 463, 475], [55, 221, 285, 603], [516, 240, 583, 383]]
Chk 10465 [[367, 174, 465, 368], [387, 99, 476, 221], [84, 95, 212, 385], [273, 153, 357, 331], [536, 30, 601, 103], [468, 136, 550, 421]]
Chk 10468 [[98, 156, 373, 503], [210, 0, 639, 506]]
Chk 10469 [[275, 120, 358, 453], [351, 150, 443, 400], [85, 122, 240, 473]]
Chk 10470 [[250, 108, 453, 356], [80, 89, 202, 355]]
Chk 10473 [[120, 68, 278, 393], [249, 56, 374, 292], [32, 73, 97, 277]]
Chk 10474 [[297, 71, 639, 315], [15, 10, 639, 399]]
Chk 10475 [[102, 148, 272, 400], [394, 58, 608, 420], [275, 128, 417, 409], [0, 171, 56, 274], [277, 125, 335, 229]]
Chk 10477 [[0, 32, 343, 417], [339, 119, 632, 420]]
Chk 10478 [[41, 105, 138, 420], [234, 137, 386, 317], [560, 175, 639, 332], [164, 189, 224, 263]]
Chk 10479 [[187, 68, 454, 315], [46, 61, 181, 316]]
Chk 10480 [[364, 50, 639, 426], [0, 39, 367, 421], [73, 73, 131, 177], [0, 74, 84, 232]]
Chk 10482 [[0, 15, 363, 632], [286, 72, 637, 638]]
Chk 10484 [[158, 198, 544, 321], [108, 155, 409, 331]]
Chk 10485 [[215, 93, 585, 425], [20, 114, 287, 423]]
Chk 10486 [[295, 39, 463, 425], [0, 170, 202, 340], [446, 38, 596, 420]]
Chk 10488 [[166, 8, 318, 219], [7, 7, 149, 221], [331, 0, 485, 221]]
Chk 10489 [[416, 89, 624, 472], [153, 185, 354, 400]]
Chk 10490 [[222, 74, 401, 283], [358, 24, 497, 366], [0, 29, 177, 370], [67, 90, 191, 254]]
Chk 10492 [[103, 108, 510, 467], [278, 130, 640, 439]]

Chk 10493 [[93, 65, 221, 378], [440, 0, 586, 418]]
Chk 10494 [[182, 89, 404, 487], [77, 365, 328, 598], [16, 126, 126, 463], [14, 180, 126, 412]]
Chk 10495 [[219, 67, 430, 330], [58, 9, 137, 261]]
Chk 10496 [[0, 69, 273, 474], [508, 247, 639, 474], [499, 231, 575, 337], [429, 284, 534, 479]]
Chk 10497 [[357, 56, 499, 421], [240, 134, 374, 421]]
Chk 10498 [[77, 77, 224, 354], [79, 165, 305, 359], [296, 99, 479, 354]]
Chk 10499 [[112, 28, 319, 337], [310, 83, 456, 260]]
Chk 10500 [[168, 151, 393, 419], [305, 133, 545, 416]]
Chk 10501 [[124, 59, 360, 405], [301, 56, 481, 349]]
Chk 10502 [[1, 94, 257, 630], [320, 51, 427, 424]]
Chk 10503 [[64, 211, 222, 422], [218, 268, 386, 426]]
Chk 10504 [[85, 27, 288, 391], [229, 40, 397, 403], [371, 4, 588, 345]]
Chk 10505 [[56, 111, 241, 379], [220, 101, 287, 187], [364, 96, 519, 311]]
Chk 10507 [[147, 22, 347, 451], [124, 103, 264, 456], [329, 70, 472, 448]]
Chk 10509 [[82, 59, 459, 426], [289, 1, 494, 409]]
Chk 10510 [[24, 123, 188, 368], [121, 109, 297, 373], [235, 130, 499, 370]]
Chk 10511 [[220, 97, 348, 381], [15, 128, 172, 377], [462, 131, 616, 346]]
Chk 10513 [[251, 55, 605, 425], [0, 8, 367, 420]]
Chk 10514 [[106, 34, 296, 425], [284, 30, 458, 425]]
Chk 10515 [[64, 40, 368, 479], [346, 0, 639, 478]]
Chk 10516 [[0, 8, 264, 479], [83, 38, 371, 479]]
Chk 10517 [[1, 128, 176, 490], [152, 0, 332, 500]]
Chk 10518 [[78, 68, 262, 549], [1, 12, 117, 177]]
Chk 10519 [[100, 94, 223, 427], [223, 101, 347, 447]]
Chk 10521 [[210, 252, 451, 480], [45, 240, 290, 440]]
Chk 10522 [[194, 47, 470, 613], [31, 57, 252, 615]]
Chk 10523 [[207, 144, 378, 601], [26, 140, 261, 604], [27, 124, 171, 379]]
Chk 10524 [[453, 47, 639, 479], [52, 118, 195, 347], [279, 64, 385, 472], [408, 22, 566, 479], [217, 80, 329, 455]]
Chk 10525 [[33, 83, 332, 417], [1, 298, 353, 451], [159, 75, 291, 290], [402, 11, 619, 451]]
Chk 10526 [[0, 4, 330, 420], [287, 91, 574, 421]]
Chk 10527 [[0, 75, 226, 422], [359, 189, 572, 421], [86, 1, 148, 90], [233, 2, 498, 427]]
Chk 10529 [[166, 52, 316, 395], [282, 66, 401, 359], [330, 62, 407, 296], [249, 93, 639, 406]]
Chk 10530 [[378, 9, 595, 585], [279, 105, 431, 305]]
Chk 10531 [[310, 39, 500, 449], [489, 28, 639, 459], [232, 1, 352, 162], [1, 34, 202, 441]]
Chk 10532 [[185, 60, 392, 359], [464, 4, 636, 320]]
Chk 10533 [[234, 240, 328, 480], [322, 230, 391, 478], [425, 254, 558, 479], [318, 236, 464, 478]]
Chk 10535 [[178, 84, 333, 420], [345, 11, 522, 419]]
Chk 10536 [[169, 39, 379, 277], [0, 28, 108, 280]]
Chk 10537 [[339, 147, 494, 444], [518, 177, 579, 388], [233, 30, 336, 391], [517, 217, 639, 453], [120, 223, 189, 392], [118, 206, 201, 381], [168, 33, 299, 404]]
Chk 10538 [[130, 205, 286, 627], [368, 120, 479, 632]]
Chk 10539 [[248, 97, 333, 368], [106, 117, 213, 370], [366, 115, 438, 301]]
Chk 10541 [[0, 113, 303, 419], [229, 212, 307, 268], [297, 209, 414, 268], [401, 114, 639, 421]]
Chk 10542 [[442, 107, 529, 374], [372, 115, 433, 295], [229, 119, 329, 417]]
Chk 10543 [[328, 194, 492, 473], [392, 199, 591, 472], [204, 186, 376, 380], [0, 137, 184, 469]]
Chk 10544 [[0, 30, 213, 291], [264, 45, 455, 381]]
Chk 10547 [[248, 84, 358, 370], [358, 67, 498, 234], [122, 75, 261, 374], [0, 59, 143, 374]]
Chk 10548 [[370, 100, 637, 377], [0, 63, 132, 372]]
Chk 10549 [[149, 92, 407, 370], [412, 72, 499, 325], [1, 1, 124, 367], [313, 81, 407, 265], [270, 229, 499, 374], [175, 64, 275, 194]]
Chk 10550 [[151, 59, 258, 385], [223, 236, 364, 473], [289, 174, 436, 331], [432, 31, 564, 454]]
Chk 10551 [[315, 56, 638, 440], [281, 98, 454, 343], [25, 218, 212, 549], [183, 122, 316, 190], [401, 7, 606, 343], [161, 132, 515, 546]]
Chk 10552 [[385, 7, 634, 471], [2, 1, 363, 473]]
Chk 10553 [[342, 300, 543, 421], [136, 233, 322, 425]]
Chk 10554 [[78, 40, 241, 259], [366, 72, 598, 209]]
Chk 10556 [[228, 62, 431, 461], [398, 34, 639, 454], [49, 0, 329, 462], [150, 94, 310, 441], [239, 203, 320, 255]]
Chk 10557 [[170, 328, 298, 586], [41, 229, 256, 569], [257, 241, 364, 422]]
Chk 10558 [[248, 273, 510, 472], [499, 339, 639, 473], [0, 232, 255, 472]]
Chk 10559 [[413, 35, 591, 410], [22, 71, 338, 446]]
Chk 10566 [[149, 124, 358, 583], [281, 130, 416, 485]]
Chk 10567 [[143, 138, 309, 466], [218, 135, 298, 331], [350, 148, 429, 266], [456, 172, 593, 478], [369, 154, 491, 301]]
Chk 10569 [[0, 2, 158, 417], [308, 94, 519, 425], [154, 180, 230, 269], [228, 129, 306, 338], [244, 45, 425, 376], [468, 56, 639, 425]]
Chk 10570 [[2, 15, 290, 472], [304, 186, 424, 477], [371, 158, 629, 479]]
Chk 10571 [[214, 61, 382, 525], [172, 118, 291, 422], [33, 335, 214, 532]]
Chk 10572 [[255, 0, 525, 437], [127, 34, 393, 460]]
Chk 10574 [[71, 217, 243, 473], [235, 156, 485, 479]]
Chk 10575 [[318, 302, 426, 630], [212, 302, 369, 505], [135, 297, 210, 530], [121, 271, 183, 413], [32, 278, 134, 505], [0, 288, 71, 474], [159, 285, 263, 638]]
Chk 10577 [[47, 174, 247, 429], [4, 66, 140, 341], [126, 100, 249, 225]]
Chk 10580 [[142, 138, 350, 411], [112, 160, 223, 406]]
Chk 10582 [[12, 111, 366, 427], [264, 99, 635, 423]]
Chk 10583 [[0, 24, 511, 639], [330, 4, 510, 361]]
Chk 10584 [[303, 42, 496, 470], [168, 216, 288, 477]]
Chk 10585 [[195, 73, 309, 451], [7, 104, 354, 466], [434, 120, 639, 474]]
Chk 10587 [[496, 125, 639, 333], [0, 151, 122, 479]]
Chk 10590 [[181, 47, 273, 398], [82, 18, 215, 399], [387, 52, 505, 384], [453, 71, 574, 401]]
Chk 10591 [[15, 59, 450, 445], [431, 170, 638, 449], [0, 137, 68, 254]]
Chk 10592 [[164, 54, 364, 388], [326, 106, 474, 356]]
Chk 10594 [[320, 0, 479, 476], [61, 0, 348, 574]]
Chk 10595 [[55, 42, 294, 321], [270, 92, 370, 275], [298, 57, 531, 314], [193, 52, 293, 290]]
Chk 10596 [[317, 240, 484, 394], [480, 195, 582, 390], [102, 125, 276, 362], [122, 84, 174, 152], [236, 94, 298, 163], [384, 103, 435, 175], [414, 100, 472, 180], [499, 116, 550, 182]]
Chk 10598 [[87, 101, 327, 392], [234, 62, 357, 378]]
Chk 10600 [[71, 236, 424, 639], [0, 117, 327, 624], [0, 469, 61, 639]]
Chk 10601 [[235, 110, 416, 418], [89, 88, 278, 420], [368, 64, 549, 421]]
Chk 10603 [[0, 110, 320, 494], [0, 64, 101, 352]]
Chk 10607 [[144, 92, 299, 372], [12, 35, 201, 371]]
Chk 10608 [[343, 6, 635, 418], [45, 26, 382, 427]]
Chk 10609 [[0, 128, 160, 475], [175, 165, 335, 401]]
Chk 10610 [[260, 0, 637, 474], [0, 52, 403, 479]]
Chk 10612 [[334, 58, 466, 353], [403, 28, 528, 301], [228, 85, 387, 393], [88, 104, 243, 447], [481, 20, 593, 269]]
Chk 10614 [[256, 266, 445, 470], [11, 20, 386, 474], [391, 136, 573, 479]]
Chk 10615 [[0, 3, 208, 279], [268, 25, 425, 246], [527, 303, 638, 423]]
Chk 10616 [[118, 65, 293, 495], [532, 131, 588, 491], [239, 47, 438, 491], [271, 46, 557, 639]]
Chk 10617 [[203, 92, 377, 428], [119, 219, 224, 461]]
Chk 10620 [[210, 109, 485, 406], [2, 1, 281, 470]]
Chk 10621 [[21, 171, 466, 605], [144, 130, 444, 396]]
Chk 10622 [[240, 280, 427, 455], [456, 185, 639, 442], [84, 141, 268, 404]]
Chk 10624 [[222, 36, 350, 395], [322, 88, 409, 396]]
Chk 10625 [[235, 54, 370, 468], [61, 64, 188, 459]]
Chk 10626 [[151, 106, 297, 471], [294, 200, 504, 467]]
Chk 10627 [[254, 62, 364, 313], [29, 212, 272, 379], [483, 43, 545, 152], [391, 2, 598, 398]]
Chk 10628 [[147, 199, 618, 607], [216, 180, 401, 418], [4, 202, 303, 596]]
Chk 10630 [[96, 67, 260, 621], [273, 86, 377, 490]]
Chk 10631 [[275, 109, 496, 420], [282, 61, 372, 263], [454, 99, 639, 420]]
Chk 10632 [[35, 193, 451, 553], [431, 153, 637, 558]]
Chk 10633 [[217, 110, 467, 370], [2, 22, 197, 280]]
Chk 10634 [[363, 48, 511, 359], [154, 23, 303, 355]]
Chk 10635 [[236, 121, 468, 462], [297, 2, 638, 473], [0, 161, 262, 404], [44, 1, 191, 236], [343, 1, 428, 136], [0, 0, 76, 245], [281, 78, 375, 245]]
Chk 10636 [[251, 130, 489, 420], [80, 26, 227, 420]]
Chk 10637 [[311, 8, 420, 297], [93, 148, 277, 468]]
Chk 10638 [[52, 164, 341, 357], [294, 100, 639, 359]]
Chk 10639 [[87, 339, 200, 482], [198, 351, 322, 515], [361, 423, 479, 639], [259, 355, 442, 557]]
Chk 10640 [[405, 58, 625, 378], [221, 85, 328, 275], [11, 13, 175, 359]]
Chk 10644 [[168, 51, 584, 399], [1, 0, 400, 472], [567, 39, 639, 327]]
Chk 10645 [[282, 83, 465, 332], [55, 112, 190, 376], [2, 141, 79, 473], [279, 287, 371, 362], [205, 263, 619, 471], [60, 351, 229, 479]]
Chk 10646 [[68, 0, 394, 480], [372, 118, 527, 429]]
Chk 10647 [[242, 6, 499, 370], [161, 57, 405, 368], [15, 129, 280, 366]]
Chk 10648 [[521, 166, 621, 390], [295, 273, 478, 426], [267, 278, 329, 367], [189, 259, 244, 356]]
Chk 10650 [[92, 119, 221, 476], [320, 130, 458, 478]]
Chk 10651 [[124, 198, 253, 484], [323, 72, 456, 383], [453, 175, 616, 478], [451, 66, 556, 350], [511, 68, 626, 263]]
Chk 10652 [[193, 34, 357, 537], [238, 129, 538, 582]]

Chk 10653 [[444, 20, 639, 419], [0, 1, 227, 417], [360, 46, 560, 288], [298, 65, 359, 197], [156, 61, 296, 386]]
Chk 10654 [[39, 43, 375, 427], [178, 0, 267, 140], [244, 0, 409, 222], [380, 126, 553, 366]]
Chk 10656 [[20, 278, 223, 631], [192, 30, 437, 637]]
Chk 10657 [[30, 76, 281, 472], [369, 35, 636, 453]]
Chk 10658 [[355, 218, 540, 374], [537, 194, 639, 395], [166, 138, 371, 376], [437, 83, 491, 139]]
Chk 10659 [[194, 90, 285, 339], [84, 25, 214, 354], [302, 99, 384, 199], [378, 52, 459, 328], [427, 83, 538, 357]]
Chk 10660 [[308, 69, 638, 483], [1, 194, 229, 485], [202, 113, 376, 483]]
Chk 10661 [[165, 92, 302, 360], [332, 79, 458, 281], [41, 85, 99, 228]]
Chk 10662 [[240, 310, 381, 522], [147, 180, 232, 438], [0, 329, 279, 551]]
Chk 10663 [[187, 45, 299, 429], [169, 77, 222, 166], [12, 31, 173, 440]]
Chk 10665 [[63, 205, 190, 539], [348, 221, 448, 511], [181, 217, 352, 508], [457, 240, 559, 349]]
Chk 10666 [[171, 281, 343, 486], [0, 279, 178, 505], [117, 285, 180, 360], [373, 254, 426, 329]]
Chk 10667 [[208, 91, 285, 289], [275, 148, 399, 356], [327, 211, 480, 425], [233, 80, 338, 302]]
Chk 10668 [[355, 65, 607, 420], [216, 35, 288, 172], [59, 15, 327, 425]]
Chk 10671 [[175, 170, 396, 421], [416, 131, 589, 270]]
Chk 10672 [[78, 159, 359, 591], [183, 59, 520, 615], [1, 195, 133, 631], [183, 240, 373, 638]]
Chk 10675 [[124, 168, 367, 486], [81, 174, 210, 451]]
Chk 10676 [[91, 159, 234, 361], [0, 140, 133, 362], [335, 55, 566, 353]]
Chk 10677 [[172, 451, 366, 639], [5, 360, 161, 637]]
Chk 10678 [[189, 191, 622, 591], [196, 124, 392, 469], [136, 275, 209, 400], [196, 263, 261, 353], [60, 254, 236, 520], [0, 257, 76, 472]]
Chk 10679 [[245, 143, 605, 452], [0, 18, 254, 479]]
Chk 10680 [[59, 89, 299, 426], [294, 2, 425, 425], [371, 0, 424, 88], [0, 55, 155, 365]]
Chk 10681 [[245, 59, 385, 213], [413, 0, 639, 422], [0, 54, 99, 281]]
Chk 10682 [[55, 129, 312, 479], [415, 159, 535, 479], [403, 140, 538, 479]]
Chk 10683 [[165, 109, 276, 406], [337, 139, 436, 420], [60, 155, 182, 420], [261, 137, 353, 412], [504, 104, 626, 425], [17, 136, 72, 286]]
Chk 10684 [[99, 61, 554, 474], [48, 65, 406, 423]]
Chk 10686 [[0, 5, 165, 289], [358, 151, 545, 504]]
Chk 10687 [[143, 73, 369, 429], [372, 54, 607, 429]]
Chk 10688 [[411, 276, 613, 479], [30, 276, 287, 473], [278, 334, 344, 430]]
Chk 10689 [[216, 98, 268, 160], [125, 37, 342, 330], [245, 50, 375, 330]]
Chk 10690 [[301, 82, 583, 442], [60, 59, 324, 448]]
Chk 10691 [[115, 54, 293, 328], [54, 97, 183, 327], [222, 183, 333, 332]]
Chk 10692 [[102, 16, 333, 359], [314, 81, 541, 359]]
Chk 10693 [[273, 92, 396, 403], [546, 68, 639, 410], [0, 0, 127, 141], [419, 83, 501, 186]]
Chk 10694 [[97, 87, 290, 337], [235, 36, 313, 259], [255, 29, 469, 324]]
Chk 10695 [[338, 153, 400, 332], [245, 175, 362, 338], [474, 240, 637, 470], [138, 169, 219, 346], [338, 212, 532, 477], [517, 324, 602, 381]]
Chk 10696 [[3, 21, 217, 351], [230, 81, 363, 292], [236, 17, 317, 153], [407, 33, 497, 157], [396, 90, 499, 232], [0, 85, 51, 265], [351, 100, 414, 168]]
Chk 10697 [[243, 11, 408, 333], [36, 50, 246, 329]]
Chk 10698 [[13, 121, 300, 506], [356, 155, 632, 510]]
Chk 10700 [[263, 112, 319, 185], [115, 154, 231, 321], [4, 156, 138, 417], [460, 154, 579, 400], [194, 137, 296, 248], [443, 139, 498, 261]]
Chk 10701 [[11, 30, 347, 420], [344, 58, 625, 420], [0, 28, 90, 252]]
Chk 10702 [[281, 105, 492, 369], [435, 86, 499, 324], [84, 105, 194, 278], [271, 91, 370, 255], [1, 137, 181, 367]]
Chk 10703 [[36, 106, 275, 369], [351, 0, 486, 258], [116, 0, 206, 120], [230, 0, 349, 180], [175, 74, 246, 194]]
Chk 10704 [[185, 200, 310, 400], [331, 102, 521, 369], [50, 137, 167, 392]]
Chk 10705 [[248, 41, 485, 603], [114, 141, 351, 634], [12, 7, 178, 571]]
Chk 10707 [[352, 115, 634, 479], [73, 137, 367, 479], [0, 135, 140, 319]]
Chk 10708 [[0, 14, 451, 422], [73, 0, 530, 374], [296, 0, 639, 421]]
Chk 10709 [[30, 235, 246, 450], [39, 183, 187, 287], [0, 1, 255, 237], [378, 385, 456, 474]]
Chk 10711 [[416, 23, 613, 320], [36, 30, 269, 364], [0, 262, 92, 353], [560, 337, 639, 392]]
Chk 10712 [[7, 98, 136, 419], [101, 0, 500, 426], [449, 140, 631, 426]]
Chk 10713 [[0, 52, 148, 377], [438, 23, 619, 242], [230, 56, 383, 259]]
Chk 10715 [[197, 141, 518, 473], [152, 105, 416, 406]]
Chk 10716 [[343, 19, 482, 333], [46, 15, 196, 329], [194, 7, 393, 331]]
Chk 10717 [[87, 122, 262, 324], [0, 12, 226, 327]]
Chk 10719 [[470, 119, 592, 340], [323, 15, 451, 317], [274, 159, 350, 295]]
Chk 10721 [[146, 82, 358, 338], [336, 111, 473, 316]]
Chk 10722 [[34, 77, 407, 352], [353, 156, 629, 421]]
Chk 10723 [[145, 138, 328, 376], [295, 64, 423, 389], [357, 138, 639, 419], [440, 50, 603, 356]]
Chk 10724 [[160, 39, 272, 312], [7, 47, 125, 369]]
Chk 10725 [[48, 228, 236, 599], [206, 244, 349, 509]]
Chk 10726 [[2, 39, 255, 415], [335, 1, 635, 421], [250, 176, 429, 426]]
Chk 10727 [[382, 50, 502, 405], [241, 30, 352, 408], [125, 81, 262, 413], [0, 112, 57, 331]]
Chk 10730 [[140, 101, 288, 318], [0, 78, 147, 269], [431, 136, 631, 401], [467, 90, 527, 317], [524, 87, 590, 277], [283, 99, 468, 353]]
Chk 10731 [[341, 122, 447, 409], [29, 1, 280, 426]]
Chk 10732 [[23, 110, 159, 347], [179, 124, 426, 638], [307, 92, 424, 270], [183, 81, 269, 317], [0, 135, 83, 493]]
Chk 10733 [[268, 31, 404, 342], [550, 53, 639, 316], [461, 24, 559, 186]]
Chk 10734 [[28, 49, 253, 491], [213, 67, 370, 489]]
Chk 10736 [[417, 107, 545, 317], [320, 58, 463, 337]]
Chk 10737 [[172, 67, 373, 473], [233, 323, 432, 474], [499, 79, 639, 474], [0, 237, 136, 479]]
Chk 10738 [[277, 2, 388, 307], [11, 11, 110, 297], [95, 39, 350, 440], [124, 1, 211, 133]]
Chk 10739 [[134, 12, 426, 517], [123, 212, 344, 485]]
Chk 10741 [[173, 82, 304, 479], [364, 31, 469, 416], [0, 159, 78, 474], [0, 69, 93, 372]]
Chk 10742 [[0, 0, 479, 629], [47, 148, 270, 553]]
Chk 10743 [[21, 4, 353, 611], [336, 189, 611, 604]]
Chk 10745 [[311, 77, 483, 318], [4, 49, 144, 250], [139, 87, 361, 314]]
Chk 10746 [[86, 23, 374, 562], [66, 224, 145, 580], [122, 65, 214, 614]]
Chk 10747 [[9, 82, 349, 422], [159, 148, 353, 415], [478, 153, 639, 285], [120, 284, 198, 389], [128, 73, 234, 136]]
Chk 10748 [[34, 0, 506, 640], [212, 291, 511, 633], [266, 0, 416, 127]]
Chk 10749 [[68, 111, 239, 388], [0, 36, 71, 182], [233, 107, 639, 410], [359, 111, 529, 420], [1, 166, 235, 420], [0, 147, 67, 215], [198, 39, 301, 424]]
Chk 10750 [[2, 78, 285, 628], [411, 113, 559, 632], [255, 152, 369, 598], [299, 113, 401, 528]]
Chk 10751 [[266, 102, 494, 369], [14, 42, 228, 374]]
Chk 10752 [[217, 101, 479, 369], [0, 85, 223, 374]]
Chk 10754 [[181, 118, 447, 631], [66, 244, 266, 526]]
Chk 10755 [[201, 54, 482, 493], [17, 218, 230, 499]]
Chk 10756 [[301, 329, 479, 549], [19, 220, 258, 524], [300, 157, 360, 292]]
Chk 10757 [[64, 277, 421, 631], [2, 29, 405, 588]]
Chk 10758 [[275, 0, 614, 284], [346, 114, 441, 258], [0, 2, 85, 173], [337, 130, 479, 229], [121, 1, 332, 266]]
Chk 10760 [[141, 95, 397, 597], [167, 178, 322, 620], [318, 72, 384, 199], [82, 205, 173, 463], [43, 185, 143, 446], [0, 1, 71, 120], [46, 113, 97, 193]]
Chk 10761 [[39, 53, 244, 451], [268, 156, 326, 317], [86, 119, 195, 455]]
Chk 10762 [[3, 168, 114, 307], [124, 166, 215, 323], [158, 161, 329, 347], [317, 149, 411, 262], [389, 125, 635, 328], [503, 77, 589, 230]]
Chk 10763 [[3, 85, 190, 483], [150, 116, 359, 474], [325, 170, 429, 482], [415, 43, 639, 476]]
Chk 10764 [[121, 255, 337, 479], [361, 205, 557, 421], [299, 0, 563, 391], [114, 0, 269, 283], [455, 2, 545, 122]]
Chk 10765 [[325, 58, 639, 479], [167, 79, 431, 472], [0, 18, 222, 474]]
Chk 10766 [[133, 160, 224, 347], [306, 147, 547, 373], [284, 28, 336, 94], [72, 198, 138, 299], [474, 42, 529, 112], [133, 9, 196, 88]]
Chk 10767 [[0, 66, 249, 424], [275, 171, 397, 398]]
Chk 10769 [[349, 253, 480, 473], [437, 218, 515, 466], [268, 179, 379, 414]]
Chk 10770 [[216, 96, 393, 371], [158, 91, 284, 372]]
Chk 10771 [[252, 106, 318, 321], [0, 151, 210, 415], [557, 90, 612, 234], [303, 61, 545, 445], [12, 158, 77, 222], [117, 106, 172, 179], [249, 88, 310, 182], [48, 99, 126, 178]]
Chk 10772 [[273, 104, 327, 387], [75, 114, 212, 494], [192, 88, 297, 450], [240, 315, 331, 499]]
Chk 10773 [[305, 62, 458, 397], [51, 147, 126, 213], [2, 210, 213, 408]]
Chk 10775 [[289, 144, 500, 479], [0, 112, 394, 474]]
Chk 10776 [[123, 103, 338, 424], [319, 175, 574, 419]]
Chk 10777 [[178, 50, 616, 639], [1, 258, 137, 627], [500, 356, 639, 629], [161, 318, 282, 635]]
Chk 10778 [[222, 145, 415, 395], [564, 217, 639, 433], [349, 256, 530, 433]]
Chk 10780 [[112, 145, 227, 419], [330, 141, 477, 419], [215, 151, 314, 420], [476, 133, 594, 424], [577, 200, 639, 424], [336, 182, 390, 424]]
Chk 10781 [[0, 9, 340, 392], [343, 42, 639, 393]]

Chk 10782 [[358, 160, 517, 386], [91, 63, 190, 437], [166, 55, 291, 440], [473, 142, 639, 364], [540, 156, 618, 253]]
Chk 10783 [[55, 81, 291, 333], [358, 5, 626, 479]]
Chk 10784 [[445, 94, 598, 439], [449, 0, 623, 279], [213, 0, 333, 219], [175, 69, 239, 327], [228, 0, 339, 171]]
Chk 10786 [[159, 72, 479, 540], [0, 66, 283, 638]]
Chk 10787 [[138, 18, 276, 468], [352, 109, 552, 383]]
Chk 10788 [[168, 71, 350, 420], [323, 80, 537, 426]]
Chk 10790 [[137, 64, 381, 475], [303, 61, 480, 474], [468, 230, 583, 469], [547, 215, 613, 326], [547, 215, 638, 473]]
Chk 10791 [[335, 57, 429, 478], [127, 73, 294, 468]]
Chk 10792 [[200, 69, 448, 639], [0, 118, 289, 639]]
Chk 10793 [[235, 146, 541, 428], [32, 175, 221, 384]]
Chk 10795 [[188, 48, 425, 407], [1, 96, 143, 375], [95, 86, 275, 375]]
Chk 10797 [[357, 83, 515, 288], [232, 81, 379, 376]]
Chk 10798 [[37, 131, 302, 463], [51, 168, 223, 389], [294, 12, 639, 472], [466, 80, 565, 424], [193, 288, 454, 469]]
Chk 10800 [[161, 81, 331, 389], [438, 57, 513, 254], [508, 37, 569, 209], [559, 61, 639, 242], [6, 62, 91, 282], [53, 37, 119, 155], [197, 115, 294, 343], [244, 136, 394, 392]]
Chk 10802 [[128, 17, 295, 417], [290, 178, 442, 381], [468, 26, 639, 363], [302, 0, 436, 111], [475, 1, 602, 69], [137, 0, 263, 74], [432, 0, 505, 204]]
Chk 10803 [[91, 24, 587, 598], [73, 276, 276, 493], [389, 429, 522, 630], [525, 494, 587, 639]]
Chk 10804 [[0, 115, 95, 254], [308, 121, 373, 379], [424, 87, 527, 352], [516, 30, 639, 426], [66, 37, 148, 149], [154, 109, 234, 390], [249, 37, 300, 114]]
Chk 10806 [[21, 226, 121, 396], [152, 188, 317, 450], [312, 72, 449, 492]]
Chk 10807 [[319, 147, 478, 416], [77, 123, 276, 384], [187, 36, 479, 327]]
Chk 10808 [[24, 223, 332, 473], [9, 102, 171, 360], [452, 359, 635, 479]]
Chk 10809 [[468, 64, 599, 397], [46, 29, 169, 386]]
Chk 10810 [[0, 156, 247, 474], [224, 192, 417, 369], [584, 162, 639, 302], [258, 170, 355, 306], [0, 151, 110, 248], [187, 10, 639, 472]]
Chk 10811 [[348, 113, 440, 396], [386, 117, 489, 404], [138, 95, 197, 324], [243, 124, 302, 292], [561, 125, 612, 263], [92, 117, 153, 264]]
Chk 10812 [[74, 234, 320, 596], [28, 277, 218, 596], [290, 258, 547, 596]]
Chk 10813 [[67, 126, 317, 365], [272, 68, 345, 215]]
Chk 10815 [[121, 85, 460, 417], [374, 23, 467, 305]]
Chk 10816 [[57, 24, 373, 318], [102, 256, 509, 398]]
Chk 10818 [[349, 106, 499, 326], [0, 93, 145, 330], [153, 166, 233, 295]]
Chk 10819 [[368, 45, 548, 373], [2, 56, 212, 291]]
Chk 10820 [[265, 26, 494, 387], [3, 68, 334, 412], [284, 35, 337, 90], [499, 3, 573, 81], [276, 14, 335, 76]]
Chk 10821 [[221, 61, 400, 300], [269, 170, 492, 420]]
Chk 10822 [[196, 145, 293, 434], [127, 149, 220, 395], [1, 9, 144, 275], [87, 128, 144, 341]]
Chk 10824 [[222, 19, 348, 313], [114, 32, 263, 376], [0, 6, 267, 381], [337, 91, 398, 247]]
Chk 10825 [[226, 27, 383, 416], [330, 101, 492, 423], [54, 228, 145, 340]]
Chk 10826 [[392, 104, 486, 376], [420, 114, 525, 409], [83, 135, 224, 384]]
Chk 10827 [[489, 122, 639, 479], [177, 57, 253, 206], [1, 52, 176, 414], [443, 74, 515, 309], [476, 97, 561, 340], [375, 68, 464, 234], [94, 55, 206, 275]]
Chk 10828 [[42, 4, 362, 605], [356, 22, 421, 628]]
Chk 10829 [[28, 162, 231, 376], [292, 17, 526, 469], [463, 51, 639, 479]]
Chk 10830 [[269, 102, 351, 227], [488, 149, 604, 338], [326, 123, 455, 279], [58, 114, 134, 288], [112, 138, 258, 372]]
Chk 10831 [[307, 134, 611, 451], [1, 361, 66, 493], [147, 127, 386, 405]]
Chk 10833 [[0, 4, 193, 277], [109, 49, 279, 355], [276, 0, 561, 467], [446, 42, 639, 473]]
Chk 10834 [[425, 45, 544, 194], [73, 23, 161, 155], [232, 18, 339, 155], [37, 0, 113, 132], [1, 2, 119, 273], [430, 2, 639, 312]]
Chk 10835 [[488, 52, 539, 218], [584, 117, 639, 194], [177, 68, 350, 477], [339, 67, 479, 456]]
Chk 10836 [[35, 205, 252, 639], [61, 306, 191, 631], [314, 319, 426, 632], [57, 293, 109, 406], [0, 325, 66, 546]]
Chk 10838 [[211, 182, 408, 565], [55, 203, 238, 576], [1, 211, 65, 459]]
Chk 10839 [[5, 123, 143, 453], [39, 177, 197, 356], [334, 128, 479, 499], [113, 163, 167, 318], [131, 169, 239, 314], [70, 124, 190, 318], [1, 142, 62, 524], [308, 171, 412, 302]]
Chk 10840 [[42, 226, 216, 391], [262, 109, 453, 394], [0, 166, 84, 405]]
Chk 10841 [[344, 216, 492, 453], [184, 50, 382, 471], [8, 95, 221, 469]]
Chk 10842 [[405, 21, 593, 236], [0, 16, 236, 318]]
Chk 10844 [[432, 77, 639, 469], [139, 80, 466, 474]]
Chk 10845 [[127, 141, 300, 473], [352, 155, 576, 479]]
Chk 10846 [[242, 86, 392, 356], [38, 51, 325, 417], [269, 41, 619, 418], [194, 91, 290, 325]]
Chk 10848 [[426, 15, 639, 273], [0, 0, 631, 345]]
Chk 10849 [[99, 218, 191, 462], [345, 82, 421, 133], [60, 71, 127, 123], [240, 49, 297, 129], [304, 202, 372, 434], [297, 47, 370, 127], [159, 34, 213, 116]]
Chk 10850 [[134, 157, 536, 472], [371, 127, 639, 473]]
Chk 10851 [[449, 177, 608, 393], [130, 57, 303, 310], [379, 176, 531, 341]]
Chk 10852 [[384, 2, 610, 422], [87, 49, 290, 347], [186, 0, 311, 286], [558, 0, 623, 123], [82, 0, 135, 97], [0, 0, 82, 116], [1, 112, 94, 226]]
Chk 10853 [[270, 148, 638, 440], [54, 185, 440, 473]]
Chk 10854 [[404, 22, 637, 426], [260, 1, 420, 262], [160, 3, 229, 174], [273, 0, 329, 117], [219, 0, 283, 139], [25, 0, 166, 177]]
Chk 10855 [[0, 0, 166, 301], [157, 25, 310, 257], [405, 54, 466, 173], [445, 60, 499, 182], [354, 52, 449, 182]]
Chk 10856 [[197, 114, 336, 299], [469, 294, 610, 474], [279, 332, 548, 475], [338, 382, 414, 463], [335, 168, 453, 312], [152, 238, 224, 322], [3, 176, 223, 422]]
Chk 10859 [[22, 324, 218, 579], [422, 11, 607, 303], [490, 436, 543, 599], [121, 5, 304, 308], [100, 26, 191, 303]]
Chk 10861 [[49, 27, 162, 349], [579, 84, 639, 242], [148, 78, 492, 368], [134, 57, 203, 272], [391, 129, 479, 274], [472, 128, 558, 181], [510, 127, 604, 276], [357, 167, 409, 269]]
Chk 10862 [[323, 74, 426, 374], [231, 200, 445, 425], [548, 133, 639, 426], [466, 0, 548, 78], [551, 14, 633, 95]]
Chk 10863 [[99, 30, 248, 449], [349, 31, 492, 429], [233, 12, 363, 437], [462, 44, 616, 437]]
Chk 10864 [[164, 122, 405, 416], [392, 221, 625, 423]]
Chk 10866 [[180, 129, 324, 360], [333, 88, 473, 344], [223, 207, 400, 386], [58, 65, 154, 368], [7, 66, 113, 407], [145, 74, 204, 346], [443, 114, 499, 194]]
Chk 10867 [[165, 135, 475, 399], [167, 57, 308, 350], [411, 1, 600, 397], [296, 69, 368, 136], [377, 91, 448, 157], [2, 0, 165, 397]]
Chk 10869 [[366, 116, 639, 460], [0, 100, 267, 454]]
Chk 10870 [[0, 58, 193, 551], [170, 69, 333, 439], [303, 83, 487, 402]]
Chk 10871 [[0, 73, 445, 421], [321, 164, 555, 396], [157, 63, 226, 125]]
Chk 10872 [[144, 136, 322, 337], [136, 82, 396, 360]]
Chk 10873 [[107, 346, 401, 639], [79, 140, 273, 515], [20, 39, 95, 181], [299, 0, 385, 193]]
Chk 10875 [[54, 5, 269, 596], [136, 186, 326, 566]]
Chk 10877 [[221, 88, 385, 479], [121, 104, 295, 479], [364, 91, 526, 473]]
Chk 10878 [[117, 92, 342, 493], [307, 73, 566, 495]]
Chk 10879 [[79, 131, 333, 462], [2, 94, 236, 476]]
Chk 10882 [[107, 195, 309, 418], [230, 45, 472, 366], [53, 251, 121, 324], [290, 230, 489, 473]]
Chk 10883 [[6, 124, 281, 470], [408, 133, 559, 322], [219, 80, 427, 352]]
Chk 10884 [[134, 27, 328, 332], [436, 81, 616, 331], [173, 16, 588, 320], [581, 111, 637, 330]]
Chk 10886 [[216, 39, 494, 370], [1, 40, 311, 370]]
Chk 10887 [[30, 0, 357, 478], [447, 156, 567, 472], [398, 304, 466, 445]]
Chk 10888 [[248, 37, 530, 357], [116, 49, 563, 308], [547, 1, 639, 270], [0, 0, 93, 418]]
Chk 10889 [[0, 0, 195, 367], [352, 1, 503, 218], [500, 1, 596, 196], [186, 0, 355, 129]]
Chk 10890 [[313, 55, 509, 307], [268, 43, 397, 321], [30, 35, 316, 373], [392, 2, 514, 199], [170, 56, 316, 357]]
Chk 10891 [[213, 107, 437, 355], [31, 0, 98, 67], [53, 146, 182, 418], [293, 188, 491, 357], [478, 0, 564, 67]]
Chk 10893 [[0, 180, 145, 474], [370, 151, 522, 467], [179, 131, 356, 474]]
Chk 10894 [[203, 89, 353, 403], [436, 1, 639, 420], [0, 16, 229, 405]]
Chk 10895 [[43, 9, 315, 368], [206, 122, 499, 223]]
Chk 10896 [[29, 199, 225, 467], [165, 165, 414, 467], [334, 166, 585, 474], [457, 167, 633, 456]]
Chk 10897 [[359, 56, 605, 414], [31, 51, 320, 414]]
Chk 10899 [[0, 150, 237, 549], [85, 106, 468, 639]]
Chk 10901 [[48, 158, 376, 471], [421, 102, 637, 474], [0, 127, 158, 399], [387, 132, 455, 184]]
Chk 10902 [[312, 180, 482, 622], [349, 124, 432, 224], [76, 173, 239, 566]]
Chk 10905 [[59, 17, 183, 414], [191, 108, 305, 347], [261, 90, 430, 358], [496, 78, 581, 355], [330, 76, 491, 354]]
Chk 10906 [[34, 109, 177, 477], [437, 162, 535, 289], [341, 148, 430, 455], [326, 131, 394, 403], [530, 163, 614, 263]]
Chk 10908 [[180, 11, 373, 490], [1, 25, 181, 497]]
Chk 10909 [[359, 70, 514, 346], [279, 33, 497, 359]]

Chk 10910 [[448, 21, 639, 272], [1, 0, 244, 325]]
Chk 10911 [[3, 34, 280, 492], [51, 276, 221, 498]]
Chk 10912 [[147, 127, 354, 586], [249, 131, 360, 577]]
Chk 10913 [[211, 0, 284, 114], [405, 339, 628, 472], [335, 205, 473, 473]]
Chk 10914 [[200, 182, 426, 479], [371, 3, 639, 474], [1, 57, 171, 474], [117, 21, 280, 206], [250, 55, 317, 132], [378, 49, 437, 125]]
Chk 10915 [[223, 79, 409, 366], [379, 72, 499, 371], [493, 81, 637, 418]]
Chk 10916 [[154, 153, 277, 363], [89, 77, 183, 334]]
Chk 10918 [[1, 7, 223, 639], [194, 161, 326, 624]]
Chk 10919 [[252, 109, 461, 423], [422, 276, 638, 446]]
Chk 10920 [[15, 133, 502, 479], [198, 38, 325, 306], [318, 161, 560, 384]]
Chk 10921 [[271, 42, 531, 297], [148, 54, 259, 291], [255, 65, 411, 287]]
Chk 10922 [[191, 177, 288, 285], [0, 184, 139, 434], [161, 274, 373, 493]]
Chk 10923 [[17, 3, 264, 492], [71, 178, 499, 466], [0, 186, 65, 297], [381, 186, 481, 364]]
Chk 10924 [[267, 176, 546, 473], [308, 11, 438, 194], [467, 24, 639, 471], [0, 90, 286, 474]]
Chk 10926 [[312, 27, 499, 314], [0, 23, 160, 281], [194, 88, 335, 313], [140, 92, 253, 317]]
Chk 10927 [[108, 98, 470, 424], [378, 27, 563, 419], [49, 18, 118, 218]]
Chk 10930 [[306, 88, 549, 335], [505, 21, 573, 133], [427, 43, 532, 185], [573, 17, 639, 133], [534, 9, 586, 98], [564, 76, 639, 202], [134, 92, 403, 473]]
Chk 10931 [[1, 4, 128, 337], [80, 22, 265, 369], [262, 0, 420, 377], [230, 0, 304, 139], [119, 0, 265, 110]]
Chk 10933 [[345, 24, 595, 451], [306, 0, 436, 419], [40, 4, 194, 455], [149, 53, 414, 451]]
Chk 10935 [[158, 6, 326, 182], [27, 9, 307, 311], [159, 23, 456, 261], [217, 116, 293, 183]]
Chk 10936 [[304, 101, 362, 426], [119, 179, 249, 479], [65, 190, 139, 473], [280, 148, 463, 469]]
Chk 10937 [[303, 0, 460, 187], [174, 40, 239, 192], [66, 80, 221, 314], [140, 1, 211, 109], [453, 173, 562, 459]]
Chk 10938 [[0, 141, 181, 501], [123, 91, 465, 420], [448, 136, 639, 468], [487, 0, 639, 202], [0, 0, 56, 285]]
Chk 10940 [[261, 92, 579, 471], [322, 77, 449, 300], [124, 72, 325, 472]]
Chk 10941 [[0, 115, 228, 425], [169, 188, 224, 255], [345, 110, 551, 421], [470, 106, 639, 424], [256, 164, 362, 392], [231, 198, 287, 282]]
Chk 10942 [[150, 84, 337, 474], [340, 199, 549, 472], [10, 122, 160, 479], [314, 40, 464, 471]]
Chk 10944 [[180, 17, 366, 319], [309, 59, 448, 324], [524, 46, 622, 213], [575, 4, 632, 233], [430, 56, 505, 148]]
Chk 10945 [[175, 97, 343, 383], [328, 33, 636, 479], [557, 75, 626, 159]]
Chk 10946 [[0, 86, 237, 421], [279, 5, 639, 420]]
Chk 10947 [[292, 2, 595, 474], [0, 0, 403, 480]]
Chk 10948 [[299, 46, 522, 328], [201, 46, 349, 263]]
Chk 10949 [[8, 3, 262, 579], [226, 64, 401, 408], [306, 47, 412, 254]]
Chk 10950 [[2, 4, 240, 420], [449, 37, 552, 151], [587, 62, 639, 140], [563, 97, 639, 342], [169, 199, 411, 310], [357, 88, 591, 425]]
Chk 10953 [[251, 1, 391, 362], [92, 156, 266, 395]]
Chk 10954 [[231, 196, 481, 514], [36, 34, 318, 550]]
Chk 10955 [[163, 119, 352, 467], [0, 109, 296, 639]]
Chk 10956 [[231, 184, 428, 632], [101, 177, 280, 632]]
Chk 10957 [[210, 106, 443, 478], [370, 122, 518, 479]]
Chk 10959 [[187, 100, 334, 367], [354, 93, 518, 363]]
Chk 10960 [[34, 139, 168, 566], [174, 96, 308, 630]]
Chk 10961 [[73, 199, 426, 602], [195, 164, 426, 432], [313, 139, 426, 248], [0, 277, 427, 632], [0, 408, 279, 638], [162, 192, 406, 512], [0, 465, 64, 639]]
Chk 10962 [[292, 67, 424, 577], [27, 4, 238, 609], [227, 133, 326, 381], [12, 67, 112, 236]]
Chk 10963 [[423, 70, 639, 425], [370, 174, 488, 420], [242, 169, 321, 397], [123, 147, 248, 379], [109, 131, 164, 319], [56, 174, 130, 334], [241, 122, 298, 202], [268, 111, 419, 425]]
Chk 10964 [[225, 119, 315, 369], [5, 116, 87, 351], [113, 47, 220, 374]]
Chk 10965 [[234, 54, 414, 370], [393, 47, 558, 327]]
Chk 10966 [[130, 37, 252, 287], [243, 59, 332, 280]]
Chk 10968 [[209, 101, 343, 442], [367, 120, 514, 442], [512, 79, 639, 442], [0, 53, 190, 442]]
Chk 10969 [[103, 61, 348, 311], [247, 86, 428, 271]]
Chk 10970 [[456, 105, 620, 404], [468, 158, 526, 341], [141, 102, 305, 409], [158, 159, 215, 342]]
Chk 10971 [[1, 159, 121, 421], [238, 190, 417, 393], [292, 179, 435, 311], [519, 161, 613, 297], [456, 193, 561, 319], [406, 234, 477, 309]]
Chk 10972 [[13, 77, 216, 425], [0, 138, 185, 425]]
Chk 10974 [[99, 52, 298, 329], [301, 68, 499, 329]]
Chk 10975 [[185, 89, 249, 217], [284, 157, 429, 391], [418, 121, 521, 295], [0, 36, 236, 340]]
Chk 10976 [[216, 33, 464, 323], [364, 0, 638, 351], [448, 166, 560, 294]]
Chk 10977 [[223, 86, 426, 522], [48, 43, 202, 526], [12, 110, 343, 574]]
Chk 10978 [[241, 110, 383, 379], [309, 27, 422, 368]]
Chk 10980 [[266, 280, 372, 464], [30, 301, 205, 475], [134, 181, 479, 632], [345, 37, 479, 379]]
Chk 10981 [[12, 326, 124, 583], [272, 118, 400, 585], [234, 202, 317, 282]]
Chk 10982 [[0, 13, 237, 331], [267, 76, 499, 330]]
Chk 10983 [[0, 124, 295, 422], [140, 158, 291, 295], [287, 135, 408, 290], [418, 0, 639, 417], [358, 135, 418, 279]]
Chk 10986 [[79, 110, 351, 474], [250, 95, 631, 479]]
Chk 10987 [[293, 182, 389, 265], [468, 0, 593, 331], [0, 106, 124, 332]]
Chk 10988 [[151, 157, 280, 425], [65, 168, 165, 414]]
Chk 10989 [[43, 145, 368, 579], [50, 63, 146, 354], [1, 274, 166, 623]]
Chk 10990 [[225, 0, 477, 370], [8, 5, 183, 374]]
Chk 10991 [[368, 36, 559, 359], [203, 54, 397, 359], [118, 115, 219, 359]]
Chk 10992 [[0, 142, 118, 318], [180, 310, 423, 627], [306, 148, 380, 311], [120, 133, 302, 604]]
Chk 10993 [[80, 46, 213, 382], [0, 30, 100, 382], [557, 41, 624, 201], [226, 47, 363, 381], [410, 54, 557, 382]]
Chk 10994 [[314, 119, 445, 479], [295, 96, 609, 470]]
Chk 10995 [[117, 142, 289, 399], [0, 215, 140, 559], [270, 0, 477, 605]]
Chk 10996 [[240, 87, 443, 391], [313, 94, 627, 472], [57, 110, 251, 371]]
Chk 10997 [[387, 55, 638, 420], [230, 79, 495, 420]]
Chk 10998 [[171, 96, 467, 531], [285, 57, 502, 360], [45, 264, 180, 429], [18, 311, 108, 460], [1, 370, 55, 463], [242, 103, 344, 262]]
Chk 10999 [[1, 0, 264, 339], [177, 53, 551, 355]]
Chk 11000 [[155, 80, 262, 374], [417, 59, 520, 354], [335, 83, 441, 360], [256, 110, 354, 381], [81, 83, 237, 387]]
Chk 11002 [[274, 77, 382, 293], [209, 66, 615, 420], [0, 34, 251, 245]]
Chk 11003 [[2, 78, 331, 483], [0, 42, 226, 340]]
Chk 11004 [[131, 71, 294, 338], [256, 27, 412, 311], [313, 16, 570, 377], [21, 179, 95, 395]]
Chk 11007 [[3, 440, 200, 638], [90, 114, 421, 590]]
Chk 11008 [[183, 147, 324, 421], [308, 234, 369, 386], [508, 185, 567, 253], [523, 143, 639, 380], [359, 211, 433, 396], [449, 184, 504, 282]]
Chk 11009 [[34, 45, 217, 595], [154, 39, 360, 639]]
Chk 11010 [[234, 150, 347, 418], [421, 143, 515, 409]]
Chk 11011 [[361, 15, 639, 405], [1, 20, 77, 254], [44, 95, 97, 171], [135, 51, 367, 300]]
Chk 11012 [[249, 139, 335, 234], [136, 131, 238, 262], [342, 158, 530, 425], [354, 140, 445, 230], [63, 144, 210, 382], [543, 150, 600, 255], [503, 175, 600, 354]]
Chk 11014 [[1, 7, 100, 303], [201, 94, 356, 367], [215, 47, 305, 185]]
Chk 11015 [[475, 178, 612, 397], [422, 180, 495, 300], [318, 200, 417, 302], [230, 149, 342, 306]]
Chk 11016 [[250, 139, 383, 285], [50, 120, 222, 293], [451, 92, 629, 278]]
Chk 11019 [[29, 106, 294, 473], [358, 99, 564, 471]]
Chk 11020 [[344, 154, 569, 385], [13, 205, 235, 479]]
Chk 11021 [[376, 66, 612, 421], [16, 15, 267, 420]]
Chk 11023 [[371, 11, 607, 571], [34, 76, 224, 609]]
Chk 11025 [[162, 173, 365, 568], [0, 171, 174, 555]]
Chk 11026 [[126, 57, 467, 367], [148, 46, 266, 275], [0, 0, 135, 418], [299, 205, 580, 333]]
Chk 11028 [[143, 201, 265, 421], [19, 193, 194, 421], [251, 183, 397, 421], [368, 162, 594, 421]]
Chk 11031 [[505, 93, 593, 415], [450, 68, 545, 398], [375, 85, 460, 354], [60, 88, 232, 418]]
Chk 11032 [[256, 102, 335, 395], [295, 56, 401, 419], [184, 194, 235, 305]]
Chk 11033 [[131, 0, 367, 420], [0, 88, 176, 424], [407, 310, 639, 420], [91, 110, 391, 424]]
Chk 11034 [[66, 174, 244, 471], [30, 119, 124, 187], [397, 124, 472, 278], [422, 24, 585, 315], [1, 177, 72, 385]]
Chk 11035 [[529, 117, 633, 382], [84, 142, 180, 358], [8, 118, 102, 351], [221, 149, 452, 382]]
Chk 11036 [[136, 103, 287, 354], [331, 106, 465, 351], [301, 108, 371, 323], [247, 112, 302, 280], [0, 144, 127, 402], [242, 141, 307, 300]]
Chk 11037 [[218, 235, 331, 620], [34, 139, 228, 606]]
Chk 11039 [[3, 138, 220, 382], [229, 146, 381, 312], [319, 155, 415, 279], [442, 148, 639, 479], [0, 337, 156, 479]]
Chk 11040 [[215, 200, 558, 471], [235, 193, 439, 443], [0, 130, 264, 435]]
Chk 11041 [[284, 138, 409, 462], [0, 117, 139, 474]]

Chk 11042 [[328, 74, 594, 365], [201, 106, 355, 304], [0, 141, 82, 361], [581, 1, 639, 153]]
Chk 11043 [[245, 74, 370, 312], [183, 9, 252, 107], [119, 66, 275, 316], [322, 18, 398, 96], [394, 11, 458, 96], [122, 1, 189, 70], [197, 174, 273, 276], [245, 11, 317, 96]]
Chk 11044 [[76, 87, 294, 629], [257, 320, 382, 610], [348, 304, 434, 457]]
Chk 11045 [[211, 136, 425, 470], [388, 1, 639, 472]]
Chk 11046 [[2, 23, 319, 401], [385, 5, 640, 402], [225, 10, 380, 237], [9, 0, 99, 166]]
Chk 11048 [[242, 378, 434, 639], [122, 390, 202, 639], [6, 378, 145, 639], [219, 423, 292, 639]]
Chk 11049 [[115, 53, 426, 469], [346, 78, 429, 334], [2, 8, 216, 473], [531, 89, 639, 343], [571, 60, 639, 155], [509, 96, 580, 266]]
Chk 11050 [[216, 143, 318, 472], [50, 136, 156, 473]]
Chk 11051 [[227, 203, 426, 478], [25, 240, 232, 479], [451, 5, 638, 479]]
Chk 11052 [[220, 90, 552, 573], [183, 70, 418, 453], [1, 25, 55, 112]]
Chk 11053 [[182, 110, 345, 356], [350, 85, 550, 425], [206, 171, 271, 354]]
Chk 11054 [[0, 0, 228, 355], [221, 76, 468, 356], [353, 94, 428, 261], [529, 27, 639, 223], [395, 109, 475, 224]]
Chk 11055 [[310, 69, 590, 341], [136, 23, 345, 371], [296, 10, 367, 167], [1, 169, 95, 352], [482, 56, 567, 185], [530, 80, 639, 206]]
Chk 11056 [[195, 102, 350, 323], [206, 235, 337, 615], [53, 203, 293, 533], [16, 215, 279, 562]]
Chk 11057 [[304, 87, 520, 385], [0, 218, 203, 430]]
Chk 11058 [[71, 229, 297, 472], [2, 192, 110, 386], [569, 131, 639, 246], [322, 161, 488, 387], [238, 157, 426, 266]]
Chk 11059 [[271, 201, 331, 412], [212, 201, 279, 402], [110, 200, 176, 420], [499, 180, 586, 479], [562, 164, 639, 471]]
Chk 11060 [[293, 40, 436, 331], [138, 225, 639, 464]]
Chk 11061 [[156, 278, 407, 629], [291, 338, 456, 632], [419, 496, 479, 632]]
Chk 11062 [[12, 506, 262, 623], [2, 0, 182, 337], [151, 1, 315, 343], [342, 103, 423, 543]]
Chk 11065 [[251, 0, 639, 419], [319, 1, 510, 416]]
Chk 11066 [[181, 1, 439, 249], [3, 1, 270, 210], [369, 133, 499, 228], [219, 0, 300, 109]]
Chk 11067 [[542, 204, 639, 284], [330, 20, 546, 255], [112, 46, 341, 266]]
Chk 11068 [[128, 80, 496, 326], [64, 0, 299, 302]]
Chk 11069 [[262, 86, 454, 422], [524, 34, 598, 238], [394, 62, 479, 246], [1, 224, 155, 407], [23, 47, 110, 250], [331, 38, 410, 119], [166, 30, 236, 247], [162, 173, 254, 248]]
Chk 11070 [[27, 1, 514, 357], [289, 133, 639, 444]]
Chk 11071 [[117, 46, 292, 334], [213, 221, 440, 334], [419, 117, 499, 330]]
Chk 11072 [[131, 124, 246, 469], [523, 75, 638, 471], [511, 193, 567, 467], [315, 211, 417, 450]]
Chk 11073 [[131, 119, 324, 419], [227, 148, 569, 479]]
Chk 11074 [[299, 14, 616, 242], [20, 47, 315, 312]]
Chk 11076 [[167, 97, 308, 409], [357, 65, 582, 413]]
Chk 11079 [[170, 55, 376, 396], [427, 163, 582, 462], [502, 148, 575, 296], [374, 110, 501, 422]]
Chk 11080 [[307, 40, 468, 269], [138, 55, 258, 268], [3, 73, 114, 274]]
Chk 11081 [[155, 218, 425, 639], [114, 216, 264, 606]]
Chk 11082 [[236, 77, 399, 419], [398, 22, 639, 414], [77, 39, 251, 418]]
Chk 11083 [[160, 108, 430, 450], [405, 39, 496, 307]]
Chk 11084 [[510, 0, 640, 299], [278, 370, 360, 426], [0, 194, 171, 419], [153, 247, 276, 420]]
Chk 11086 [[132, 343, 269, 584], [10, 104, 214, 414], [233, 208, 408, 624]]
Chk 11088 [[93, 84, 217, 476], [189, 136, 282, 494], [260, 139, 350, 434]]
Chk 11090 [[137, 73, 283, 566], [145, 16, 424, 639]]
Chk 11094 [[225, 116, 403, 362], [344, 22, 589, 411]]
Chk 11095 [[62, 50, 258, 425], [352, 32, 515, 412], [474, 0, 575, 353]]
Chk 11096 [[100, 75, 203, 358], [260, 87, 553, 426]]
Chk 11098 [[0, 2, 107, 347], [206, 18, 437, 399], [399, 1, 531, 156], [221, 4, 284, 124], [140, 5, 220, 160]]
Chk 11099 [[75, 127, 359, 313], [263, 72, 598, 329], [281, 53, 356, 129], [242, 47, 297, 127], [199, 1, 275, 139], [51, 0, 122, 144], [15, 2, 68, 139]]
Chk 11100 [[89, 49, 425, 475], [341, 64, 583, 472]]
Chk 11102 [[339, 0, 594, 425], [190, 134, 380, 406], [531, 1, 639, 360], [87, 17, 152, 274], [69, 32, 275, 407]]
Chk 11103 [[19, 84, 248, 422], [224, 87, 401, 419], [364, 33, 598, 419], [69, 146, 143, 220], [26, 147, 99, 284]]
Chk 11106 [[143, 73, 639, 479], [5, 100, 262, 474]]
Chk 11107 [[158, 2, 455, 600], [114, 17, 221, 528]]
Chk 11108 [[102, 24, 185, 151], [163, 274, 326, 487], [38, 150, 249, 447], [247, 237, 332, 489]]
Chk 11111 [[38, 0, 506, 421], [226, 21, 423, 422], [391, 2, 505, 263], [518, 11, 619, 295]]
Chk 11112 [[253, 213, 345, 456], [280, 126, 404, 323], [550, 106, 639, 444], [260, 103, 335, 267], [478, 148, 551, 299], [78, 135, 188, 456], [411, 132, 497, 257]]
Chk 11113 [[348, 11, 606, 338], [169, 73, 306, 227], [0, 155, 192, 420], [575, 0, 639, 251], [405, 0, 536, 262]]
Chk 11114 [[172, 225, 286, 353], [234, 195, 310, 282], [262, 169, 341, 252], [352, 242, 569, 479], [137, 295, 414, 478], [389, 214, 483, 348], [24, 237, 209, 479]]
Chk 11115 [[255, 196, 340, 440], [456, 119, 598, 424], [173, 213, 271, 417]]
Chk 11116 [[99, 109, 327, 639], [47, 242, 191, 615], [251, 318, 384, 575], [0, 323, 51, 511]]
Chk 11117 [[91, 176, 170, 482], [173, 283, 276, 460], [180, 173, 267, 327], [40, 266, 110, 396], [264, 123, 361, 459]]
Chk 11118 [[215, 173, 340, 424], [353, 147, 474, 426]]
Chk 11120 [[57, 52, 525, 417], [452, 13, 639, 419], [0, 202, 78, 424]]
Chk 11121 [[230, 100, 325, 420], [52, 68, 261, 410]]
Chk 11122 [[320, 100, 529, 399], [210, 181, 375, 378], [478, 0, 535, 83]]
Chk 11124 [[262, 3, 501, 335], [59, 1, 188, 165], [0, 1, 138, 307], [413, 0, 512, 287]]
Chk 11125 [[0, 175, 120, 473], [38, 172, 197, 334], [96, 116, 252, 268], [253, 88, 337, 203], [403, 135, 481, 247], [478, 128, 626, 471], [405, 179, 510, 336]]
Chk 11126 [[0, 178, 80, 451], [151, 247, 300, 592]]
Chk 11127 [[228, 214, 432, 605], [184, 148, 289, 359]]
Chk 11128 [[227, 11, 455, 299], [0, 10, 64, 293], [419, 37, 499, 337], [53, 0, 248, 306]]
Chk 11129 [[110, 2, 380, 375], [309, 64, 445, 351], [425, 144, 639, 421], [384, 155, 455, 266]]
Chk 11131 [[249, 313, 448, 472], [272, 167, 404, 392], [73, 196, 148, 270], [61, 213, 160, 344], [217, 184, 294, 369], [395, 183, 461, 357], [444, 257, 607, 479]]
Chk 11132 [[184, 188, 403, 627], [241, 155, 307, 424], [0, 189, 85, 490], [307, 156, 366, 290], [68, 179, 120, 276], [64, 154, 232, 639]]
Chk 11133 [[85, 53, 231, 428], [11, 97, 91, 398], [274, 132, 499, 428]]
Chk 11134 [[172, 144, 313, 394], [400, 219, 523, 374], [475, 220, 612, 462]]
Chk 11135 [[371, 78, 513, 412], [163, 133, 259, 399], [312, 94, 425, 364]]
Chk 11137 [[40, 110, 218, 479], [194, 117, 260, 436], [257, 86, 308, 211], [255, 138, 400, 477], [335, 87, 418, 310], [360, 160, 604, 471], [398, 75, 541, 189]]
Chk 11138 [[203, 164, 378, 425], [116, 21, 262, 343]]
Chk 11139 [[74, 292, 202, 478], [223, 105, 287, 237], [369, 10, 455, 259], [110, 0, 200, 293]]
Chk 11140 [[513, 33, 639, 324], [0, 0, 244, 425], [196, 46, 313, 211], [5, 33, 59, 117], [358, 49, 445, 233]]
Chk 11143 [[0, 23, 637, 420], [275, 25, 474, 244]]
Chk 11144 [[233, 218, 360, 585], [99, 231, 244, 630]]
Chk 11145 [[511, 251, 631, 447], [569, 1, 637, 210], [142, 201, 360, 459], [111, 0, 199, 143], [373, 273, 541, 434]]
Chk 11146 [[28, 77, 125, 533], [51, 16, 258, 513], [241, 104, 372, 406]]
Chk 11147 [[243, 51, 411, 380], [4, 6, 223, 380]]
Chk 11148 [[73, 55, 273, 628], [246, 85, 427, 592], [388, 54, 596, 619]]
Chk 11149 [[0, 278, 286, 637], [182, 254, 318, 639]]
Chk 11150 [[159, 77, 271, 398], [376, 26, 470, 304], [280, 94, 422, 410]]
Chk 11151 [[309, 134, 450, 479], [51, 101, 198, 472]]
Chk 11153 [[0, 90, 202, 306], [228, 122, 385, 328], [584, 2, 639, 266], [281, 31, 639, 426]]
Chk 11154 [[20, 43, 139, 356], [148, 103, 253, 393], [221, 5, 403, 433], [279, 22, 638, 449]]
Chk 11155 [[75, 251, 269, 494], [123, 30, 317, 364], [0, 109, 177, 491], [228, 198, 365, 499]]
Chk 11157 [[207, 74, 463, 427], [141, 135, 279, 420], [9, 62, 237, 420], [421, 152, 489, 375]]
Chk 11158 [[86, 1, 249, 183], [393, 56, 509, 190], [345, 46, 413, 179], [246, 170, 403, 260], [172, 1, 267, 159], [47, 0, 141, 164], [0, 0, 94, 213], [417, 1, 626, 232]]
Chk 11159 [[184, 58, 518, 474], [473, 96, 619, 460], [374, 0, 455, 168], [0, 2, 196, 355], [198, 47, 249, 127], [451, 39, 535, 197], [532, 1, 639, 279]]
Chk 11160 [[358, 148, 499, 375], [0, 2, 347, 421]]
Chk 11161 [[146, 238, 363, 374], [0, 0, 259, 375]]

Chk 11162 [[235, 127, 428, 479], [87, 107, 406, 479]]
Chk 11163 [[171, 157, 447, 423], [417, 142, 533, 421], [487, 151, 550, 360], [73, 58, 174, 232], [392, 140, 445, 197]]
Chk 11164 [[520, 189, 584, 353], [398, 41, 543, 361], [161, 70, 260, 370]]
Chk 11165 [[276, 86, 426, 421], [343, 149, 520, 421]]
Chk 11167 [[2, 35, 406, 479], [372, 0, 573, 383]]
Chk 11168 [[57, 90, 235, 381], [341, 87, 553, 410]]
Chk 11169 [[94, 21, 296, 427], [333, 148, 639, 442], [207, 38, 414, 398], [10, 386, 152, 473]]
Chk 11171 [[395, 80, 550, 342], [554, 76, 623, 305], [120, 187, 242, 339], [14, 126, 154, 337]]
Chk 11172 [[171, 228, 302, 442], [66, 188, 447, 626], [291, 119, 374, 364], [153, 254, 244, 412], [126, 206, 186, 397], [14, 133, 121, 469], [83, 179, 141, 412]]
Chk 11173 [[0, 29, 136, 411], [119, 31, 290, 343], [290, 64, 420, 358], [489, 18, 639, 376]]
Chk 11175 [[82, 101, 217, 323], [378, 0, 627, 418], [200, 155, 323, 315]]
Chk 11177 [[212, 38, 499, 369], [1, 0, 227, 374]]
Chk 11178 [[74, 98, 187, 482], [280, 75, 397, 476], [387, 174, 612, 488]]
Chk 11180 [[138, 5, 328, 296], [246, 15, 414, 268], [394, 109, 522, 290]]
Chk 11181 [[127, 173, 242, 419], [172, 164, 309, 421], [282, 47, 508, 422], [319, 213, 385, 421]]
Chk 11182 [[100, 21, 210, 364], [161, 118, 285, 365]]
Chk 11183 [[357, 117, 503, 424], [98, 104, 256, 429]]
Chk 11184 [[418, 105, 615, 418], [132, 107, 194, 220], [1, 4, 56, 218], [119, 36, 367, 474], [533, 99, 616, 223], [360, 99, 429, 209]]
Chk 11185 [[3, 101, 269, 473], [425, 96, 580, 474]]
Chk 11186 [[128, 100, 336, 498], [262, 73, 438, 536]]
Chk 11187 [[189, 109, 325, 418], [53, 70, 133, 314], [0, 15, 74, 300]]
Chk 11188 [[162, 82, 287, 474], [351, 24, 540, 471], [494, 262, 612, 450], [258, 235, 393, 476]]
Chk 11189 [[375, 185, 484, 386], [1, 170, 142, 420], [0, 158, 71, 286], [0, 111, 70, 197], [500, 191, 620, 367], [312, 150, 394, 296], [421, 135, 484, 215]]
Chk 11190 [[81, 66, 252, 380], [436, 112, 573, 326], [331, 157, 442, 331]]
Chk 11192 [[232, 30, 534, 422], [96, 119, 231, 423], [512, 174, 626, 418], [207, 165, 266, 333]]
Chk 11193 [[162, 174, 299, 352], [287, 128, 472, 338]]
Chk 11194 [[428, 107, 612, 421], [252, 132, 441, 427], [75, 128, 256, 427]]
Chk 11195 [[210, 30, 411, 479], [440, 224, 587, 478]]
Chk 11196 [[18, 146, 327, 442], [28, 129, 249, 399]]
Chk 11197 [[46, 83, 199, 632], [180, 92, 314, 615]]
Chk 11198 [[13, 29, 200, 374], [316, 88, 499, 374]]
Chk 11199 [[0, 95, 261, 359], [323, 6, 600, 368]]
Chk 11200 [[271, 141, 361, 412], [448, 122, 529, 386], [576, 136, 639, 399], [553, 163, 604, 222], [112, 130, 164, 189], [361, 152, 424, 207]]
Chk 11202 [[146, 65, 380, 600], [488, 285, 583, 598]]
Chk 11203 [[368, 70, 503, 301], [486, 36, 621, 268]]
Chk 11204 [[0, 96, 239, 613], [160, 164, 248, 422], [4, 368, 228, 629], [161, 163, 367, 638]]
Chk 11206 [[334, 102, 447, 321], [5, 2, 257, 421]]
Chk 11207 [[198, 53, 347, 466], [330, 65, 478, 461]]
Chk 11208 [[0, 150, 424, 316], [17, 0, 200, 256]]
Chk 11209 [[92, 3, 198, 272], [434, 265, 639, 479], [386, 237, 527, 474], [207, 103, 342, 285]]
Chk 11210 [[151, 93, 243, 375], [428, 64, 499, 369], [277, 78, 416, 370], [23, 51, 107, 370], [89, 105, 155, 363]]
Chk 11211 [[93, 7, 277, 466], [239, 23, 445, 471]]
Chk 11212 [[0, 0, 367, 391], [319, 78, 538, 409]]
Chk 11213 [[318, 1, 477, 248], [497, 1, 638, 289], [0, 39, 316, 426], [0, 75, 130, 288]]
Chk 11214 [[199, 123, 411, 531], [71, 86, 216, 528], [7, 89, 129, 362]]
Chk 11215 [[338, 50, 480, 265], [396, 0, 639, 289], [270, 2, 377, 125], [117, 6, 215, 113], [0, 22, 64, 137], [95, 39, 490, 421]]
Chk 11216 [[148, 53, 532, 432], [1, 186, 150, 602], [403, 219, 609, 603], [135, 0, 236, 54], [40, 0, 155, 68]]
Chk 11217 [[40, 128, 152, 321], [163, 102, 242, 372], [260, 201, 373, 370], [384, 113, 549, 367], [268, 29, 322, 92], [369, 37, 433, 103]]
Chk 11218 [[173, 130, 322, 357], [423, 128, 591, 356], [278, 149, 330, 212]]
Chk 11219 [[348, 144, 639, 474], [175, 209, 327, 477]]
Chk 11221 [[2, 16, 323, 421], [132, 163, 578, 420]]
Chk 11222 [[80, 160, 294, 557], [261, 150, 359, 557]]
Chk 11223 [[129, 74, 487, 538], [49, 93, 332, 551]]
Chk 11224 [[269, 12, 444, 353], [340, 38, 567, 422]]
Chk 11225 [[229, 27, 292, 276], [327, 26, 425, 280], [413, 18, 499, 280], [169, 33, 249, 276], [125, 55, 177, 167], [41, 28, 128, 170], [270, 40, 343, 277]]
Chk 11227 [[32, 0, 382, 630], [224, 106, 380, 569]]
Chk 11228 [[112, 152, 277, 361], [45, 1, 293, 284], [395, 117, 524, 312]]
Chk 11230 [[508, 120, 606, 374], [500, 121, 555, 212], [0, 130, 142, 426]]
Chk 11231 [[133, 15, 346, 369], [375, 147, 499, 369]]
Chk 11232 [[177, 67, 332, 473], [322, 130, 403, 429], [9, 196, 94, 291]]
Chk 11233 [[20, 93, 243, 368], [0, 128, 81, 273], [277, 70, 499, 344]]
Chk 11234 [[201, 104, 344, 453], [340, 57, 605, 471]]
Chk 11235 [[204, 185, 296, 426], [277, 154, 386, 426], [0, 1, 81, 425]]
Chk 11238 [[71, 98, 408, 543], [188, 93, 409, 632], [377, 314, 479, 639], [362, 131, 446, 510], [410, 109, 479, 376]]
Chk 11240 [[514, 80, 573, 284], [0, 135, 182, 407], [433, 93, 514, 286], [101, 36, 368, 388]]
Chk 11242 [[104, 142, 267, 395], [135, 120, 370, 398]]
Chk 11243 [[0, 155, 66, 371], [87, 126, 207, 400], [127, 124, 254, 414], [228, 95, 392, 445], [30, 158, 105, 351]]
Chk 11245 [[267, 85, 379, 328], [167, 174, 309, 364], [9, 151, 222, 377], [582, 113, 639, 191]]
Chk 11246 [[277, 95, 461, 428], [387, 105, 533, 428]]
Chk 11247 [[363, 163, 525, 579], [77, 149, 197, 497]]
Chk 11248 [[53, 155, 196, 317], [299, 155, 561, 422], [524, 218, 586, 360], [269, 125, 419, 299]]
Chk 11249 [[0, 23, 225, 423], [388, 75, 605, 423]]
Chk 11250 [[206, 18, 639, 474], [150, 98, 359, 360]]
Chk 11251 [[402, 215, 474, 470], [122, 161, 274, 490], [0, 247, 64, 495], [332, 288, 389, 381], [507, 209, 604, 415], [252, 225, 330, 481]]
Chk 11252 [[0, 0, 261, 421], [443, 1, 639, 426]]
Chk 11253 [[131, 88, 256, 470], [361, 56, 599, 470]]
Chk 11254 [[24, 44, 271, 345], [273, 18, 581, 545]]
Chk 11255 [[53, 177, 179, 365], [282, 169, 419, 499], [0, 304, 52, 505], [400, 89, 612, 499], [393, 242, 553, 420]]
Chk 11256 [[330, 110, 539, 413], [123, 73, 310, 413]]
Chk 11257 [[228, 0, 435, 321], [115, 36, 601, 492]]
Chk 11258 [[326, 31, 535, 479], [118, 51, 355, 476]]
Chk 11259 [[359, 27, 431, 149], [404, 75, 473, 179], [160, 87, 354, 285], [29, 16, 296, 292], [256, 5, 365, 160]]
Chk 11260 [[1, 7, 285, 507], [366, 151, 639, 513]]
Chk 11261 [[254, 93, 562, 418], [209, 24, 528, 407]]
Chk 11263 [[334, 75, 616, 435], [0, 123, 135, 430]]
Chk 11264 [[126, 127, 357, 514], [362, 128, 609, 506]]
Chk 11265 [[319, 12, 471, 427], [464, 33, 639, 438], [181, 95, 324, 443], [7, 5, 224, 443]]
Chk 11267 [[113, 134, 266, 339], [339, 123, 507, 337]]
Chk 11269 [[182, 241, 277, 488], [0, 336, 53, 466], [90, 414, 264, 613], [37, 372, 186, 559]]
Chk 11271 [[86, 73, 355, 474], [377, 155, 639, 473]]
Chk 11272 [[113, 13, 257, 420], [145, 212, 337, 426], [388, 243, 537, 420]]
Chk 11273 [[172, 78, 308, 509], [50, 90, 180, 527], [299, 79, 424, 494]]
Chk 11274 [[318, 163, 639, 433], [0, 166, 309, 400], [513, 411, 639, 479]]
Chk 11276 [[38, 97, 209, 423], [270, 111, 401, 237], [408, 133, 613, 310], [219, 96, 313, 219], [0, 0, 107, 254]]
Chk 11277 [[265, 60, 486, 441], [106, 205, 299, 435], [71, 5, 317, 416]]
Chk 11278 [[153, 159, 342, 539], [97, 174, 245, 473]]
Chk 11279 [[50, 74, 262, 514], [274, 13, 385, 251]]
Chk 11280 [[0, 124, 206, 339], [249, 33, 441, 349]]
Chk 11281 [[366, 0, 637, 340], [20, 0, 350, 320]]
Chk 11282 [[490, 93, 637, 479], [305, 134, 582, 479], [232, 139, 414, 296], [50, 143, 221, 367], [187, 130, 244, 223], [226, 138, 279, 217], [14, 90, 86, 154], [6, 128, 64, 249]]
Chk 11283 [[250, 150, 425, 638], [249, 85, 403, 639], [108, 87, 271, 634], [0, 128, 210, 639]]
Chk 11284 [[219, 72, 295, 269], [77, 126, 138, 202], [227, 54, 519, 261]]
Chk 11285 [[147, 19, 274, 370], [408, 161, 561, 458]]
Chk 11287 [[286, 20, 639, 389], [504, 60, 616, 259], [203, 42, 423, 348], [181, 71, 262, 269], [73, 99, 206, 210]]
Chk 11288 [[472, 102, 617, 418], [338, 98, 484, 417], [240, 145, 357, 418]]
Chk 11289 [[30, 66, 223, 632], [180, 397, 314, 639], [243, 105, 390, 613]]
Chk 11292 [[77, 2, 287, 446], [0, 98, 133, 437], [331, 1, 602, 292]]
Chk 11293 [[20, 86, 189, 472], [181, 121, 274, 363], [378, 92, 536, 466], [118, 99, 206, 379]]
Chk 11294 [[122, 36, 380, 548], [264, 227, 416, 598]]
Chk 11296 [[380, 121, 607, 473], [137, 81, 358, 479]]
Chk 11297 [[107, 113, 308, 284], [1, 3, 210, 416]]
Chk 11298 [[252, 7, 516, 421], [155, 31, 263, 426]]
Chk 11299 [[431, 101, 503, 372], [303, 112, 420, 394], [93, 87, 207, 405], [217, 111, 302, 327], [551, 111, 625, 339]]

Chk 11300 [[153, 176, 355, 616], [50, 72, 277, 609]]
Chk 11302 [[289, 55, 560, 328], [64, 31, 300, 356], [550, 45, 626, 252], [472, 57, 554, 203], [574, 66, 639, 270]]
Chk 11303 [[12, 114, 141, 419], [135, 240, 259, 417], [441, 122, 528, 417]]
Chk 11305 [[230, 4, 497, 370], [114, 94, 251, 368]]
Chk 11306 [[2, 79, 184, 474], [166, 89, 342, 334], [392, 111, 639, 472]]
Chk 11308 [[240, 5, 504, 276], [392, 3, 639, 314]]
Chk 11309 [[317, 109, 575, 425], [246, 233, 514, 427], [23, 242, 86, 314], [75, 199, 167, 426]]
Chk 11310 [[225, 214, 338, 543], [455, 218, 508, 406], [152, 191, 207, 290], [376, 187, 491, 562]]
Chk 11316 [[0, 0, 267, 427], [355, 42, 547, 287], [543, 117, 625, 219]]
Chk 11317 [[183, 65, 300, 389], [300, 74, 427, 383]]
Chk 11318 [[0, 51, 267, 421], [205, 107, 329, 339]]
Chk 11319 [[20, 107, 306, 478], [318, 77, 618, 333]]
Chk 11320 [[280, 155, 511, 479], [126, 284, 238, 479], [69, 278, 147, 479]]
Chk 11321 [[94, 94, 409, 479], [274, 59, 446, 472]]
Chk 11322 [[404, 131, 528, 362], [489, 117, 554, 300], [178, 114, 239, 267], [210, 123, 427, 428]]
Chk 11323 [[362, 248, 599, 474], [356, 141, 500, 387], [320, 88, 431, 242], [155, 90, 231, 170], [111, 144, 284, 406], [245, 94, 344, 202], [87, 120, 170, 325]]
Chk 11325 [[196, 125, 338, 318], [82, 154, 276, 426], [289, 104, 413, 258], [238, 71, 309, 176], [306, 78, 359, 150], [0, 210, 170, 426]]
Chk 11326 [[277, 136, 374, 245], [388, 113, 569, 420], [122, 28, 177, 183], [0, 243, 90, 420], [329, 36, 383, 218], [242, 216, 467, 425], [495, 110, 573, 214], [0, 59, 79, 202]]
Chk 11327 [[373, 50, 601, 351], [537, 123, 608, 195], [252, 23, 397, 359]]
Chk 11328 [[1, 32, 610, 418], [214, 145, 396, 345], [476, 107, 639, 346]]
Chk 11329 [[236, 17, 401, 342], [119, 47, 265, 337], [8, 53, 160, 342], [379, 53, 515, 339], [472, 17, 639, 342]]
Chk 11330 [[140, 176, 349, 473], [9, 153, 227, 471], [403, 237, 518, 479], [482, 181, 639, 478]]
Chk 11331 [[0, 77, 124, 479], [159, 36, 630, 473]]
Chk 11333 [[378, 127, 561, 478], [500, 126, 639, 467]]
Chk 11334 [[354, 123, 639, 479], [97, 87, 222, 314]]
Chk 11335 [[143, 111, 492, 474], [1, 11, 139, 477], [424, 154, 603, 405], [375, 198, 444, 362]]
Chk 11336 [[189, 69, 324, 418], [224, 179, 428, 581], [84, 187, 245, 582]]
Chk 11338 [[251, 107, 379, 476], [0, 138, 94, 466], [233, 0, 286, 152], [113, 92, 185, 255]]
Chk 11339 [[118, 221, 297, 457], [14, 40, 228, 376]]
Chk 11341 [[268, 65, 429, 377], [27, 172, 235, 315], [181, 87, 328, 306]]
Chk 11343 [[297, 195, 611, 597], [0, 232, 293, 605]]
Chk 11345 [[56, 430, 326, 628], [258, 485, 426, 630], [2, 44, 374, 541]]
Chk 11346 [[581, 152, 638, 288], [511, 168, 622, 395], [511, 195, 562, 369], [449, 141, 507, 314], [360, 151, 494, 418], [186, 94, 278, 358], [268, 170, 335, 332], [360, 158, 411, 338]]
Chk 11347 [[110, 227, 200, 427], [210, 197, 338, 420], [452, 206, 525, 422]]
Chk 11348 [[175, 311, 263, 605], [75, 309, 188, 612], [435, 16, 511, 144]]
Chk 11352 [[352, 157, 475, 445], [443, 46, 564, 464], [0, 81, 179, 441], [502, 72, 639, 474]]
Chk 11353 [[374, 7, 556, 243], [81, 63, 266, 302], [170, 46, 431, 430], [294, 30, 544, 404], [132, 58, 352, 384], [0, 196, 67, 313], [178, 59, 247, 126]]
Chk 11355 [[270, 135, 457, 403], [29, 69, 106, 136], [420, 168, 475, 278], [455, 239, 639, 395]]
Chk 11357 [[2, 97, 244, 440], [148, 111, 356, 435], [286, 99, 534, 440], [473, 80, 631, 435], [9, 20, 63, 211]]
Chk 11360 [[33, 192, 352, 600], [352, 161, 422, 418], [0, 242, 73, 448], [16, 139, 108, 432]]
Chk 11361 [[251, 23, 528, 469], [154, 90, 257, 321], [67, 85, 148, 353], [0, 225, 100, 448], [444, 125, 510, 286], [478, 129, 557, 267], [281, 107, 341, 321], [257, 82, 341, 312]]
Chk 11362 [[266, 117, 390, 484], [385, 97, 582, 337], [77, 123, 200, 381], [348, 128, 436, 227], [0, 116, 135, 500]]
Chk 11364 [[256, 37, 498, 363], [119, 78, 399, 354]]
Chk 11365 [[20, 54, 176, 416], [223, 9, 417, 418], [411, 60, 609, 424], [188, 69, 284, 404], [168, 78, 246, 240], [0, 60, 53, 220], [164, 91, 226, 157]]
Chk 11367 [[100, 78, 290, 320], [328, 20, 615, 343]]
Chk 11369 [[167, 58, 345, 308], [1, 4, 90, 243], [41, 0, 109, 162], [95, 0, 213, 189], [439, 5, 496, 74], [179, 0, 266, 149]]
Chk 11370 [[313, 229, 428, 403], [37, 132, 164, 404], [408, 191, 551, 420]]
Chk 11371 [[513, 56, 635, 389], [10, 59, 124, 387], [388, 86, 554, 387]]
Chk 11373 [[19, 366, 178, 474], [297, 169, 395, 472], [377, 300, 537, 419], [3, 123, 291, 480]]
Chk 11375 [[237, 117, 347, 456], [161, 72, 274, 453]]
Chk 11376 [[7, 56, 287, 425], [274, 47, 596, 425]]
Chk 11377 [[182, 194, 245, 350], [158, 168, 213, 338], [247, 155, 376, 374]]
Chk 11378 [[163, 122, 457, 473], [418, 331, 638, 477]]
Chk 11379 [[147, 87, 374, 639], [82, 148, 213, 479], [0, 399, 85, 631]]
Chk 11380 [[118, 69, 267, 360], [256, 90, 383, 322]]
Chk 11381 [[238, 5, 387, 257], [86, 155, 249, 479]]
Chk 11382 [[0, 181, 169, 354], [329, 163, 591, 459]]
Chk 11383 [[132, 96, 426, 632], [333, 16, 426, 451], [74, 35, 170, 445], [267, 44, 334, 202], [179, 3, 318, 197]]
Chk 11384 [[192, 1, 341, 472], [0, 25, 154, 500]]
Chk 11385 [[67, 116, 320, 473], [321, 134, 442, 391]]
Chk 11386 [[1, 252, 247, 626], [179, 4, 427, 556], [215, 97, 277, 199], [0, 30, 67, 256], [293, 121, 344, 271], [151, 101, 223, 211]]
Chk 11387 [[117, 121, 248, 264], [580, 1, 639, 245], [334, 112, 584, 302], [0, 244, 216, 446]]
Chk 11388 [[0, 0, 123, 639], [148, 68, 479, 519]]
Chk 11389 [[69, 9, 237, 402], [290, 25, 538, 452], [0, 115, 63, 230]]
Chk 11390 [[222, 12, 603, 415], [371, 132, 572, 421], [310, 112, 423, 351]]
Chk 11391 [[149, 227, 310, 534], [87, 125, 307, 531]]
Chk 11392 [[105, 72, 303, 386], [371, 129, 453, 286]]
Chk 11393 [[0, 276, 117, 485], [181, 221, 465, 453], [280, 3, 638, 381], [42, 108, 273, 266], [580, 124, 639, 254]]
Chk 11395 [[500, 142, 637, 418], [392, 99, 578, 416], [576, 23, 639, 154], [325, 51, 479, 301], [498, 74, 581, 145]]
Chk 11397 [[385, 136, 465, 422], [470, 131, 543, 413]]
Chk 11398 [[78, 238, 243, 381], [0, 210, 148, 371], [69, 55, 122, 108], [153, 15, 221, 104], [314, 135, 460, 370], [208, 14, 260, 98]]
Chk 11399 [[65, 115, 221, 422], [309, 100, 448, 369]]
Chk 11400 [[280, 94, 431, 372], [210, 78, 329, 271], [132, 106, 189, 176]]
Chk 11401 [[139, 185, 340, 517], [78, 124, 201, 433]]
Chk 11402 [[203, 92, 639, 474], [77, 155, 360, 472]]
Chk 11403 [[68, 69, 284, 356], [419, 105, 490, 326], [282, 116, 347, 330], [180, 96, 238, 328], [261, 80, 445, 328]]
Chk 11404 [[374, 176, 434, 420], [434, 160, 543, 425], [54, 146, 121, 291], [0, 258, 110, 419]]
Chk 11405 [[118, 246, 377, 427], [4, 141, 454, 427]]
Chk 11407 [[145, 90, 365, 476], [52, 252, 114, 367], [376, 206, 479, 457]]
Chk 11408 [[67, 95, 345, 420], [336, 177, 449, 302], [478, 98, 612, 299]]
Chk 11409 [[179, 83, 399, 562], [1, 9, 266, 574], [307, 69, 424, 238]]
Chk 11410 [[320, 156, 605, 473], [52, 190, 336, 450], [568, 206, 639, 382]]
Chk 11411 [[138, 78, 340, 418], [443, 62, 635, 416]]
Chk 11413 [[141, 28, 296, 447], [224, 143, 378, 479], [20, 12, 181, 426], [365, 0, 478, 416]]
Chk 11414 [[133, 122, 374, 632], [288, 463, 477, 639], [407, 391, 478, 623], [0, 26, 175, 631]]
Chk 11416 [[31, 8, 247, 208], [72, 173, 374, 499]]
Chk 11417 [[1, 192, 235, 437], [330, 168, 477, 405], [260, 107, 400, 349], [20, 72, 216, 345], [26, 41, 124, 176]]
Chk 11418 [[81, 107, 337, 430], [81, 41, 406, 261], [407, 47, 584, 471], [501, 184, 639, 473]]
Chk 11420 [[115, 38, 363, 350], [326, 14, 402, 166], [558, 53, 639, 157], [400, 143, 619, 327]]
Chk 11422 [[76, 130, 260, 629], [274, 202, 426, 624]]
Chk 11425 [[336, 97, 499, 284], [0, 108, 216, 295]]
Chk 11427 [[1, 116, 219, 423], [441, 113, 574, 467]]
Chk 11429 [[133, 84, 331, 471], [381, 40, 569, 455], [148, 59, 211, 156]]
Chk 11430 [[24, 172, 215, 423], [264, 176, 449, 423], [156, 75, 311, 410]]
Chk 11431 [[1, 174, 326, 444], [424, 55, 624, 436], [327, 218, 443, 459]]
Chk 11432 [[299, 86, 440, 247], [564, 101, 639, 292], [13, 68, 233, 378], [0, 30, 183, 426]]
Chk 11433 [[224, 103, 416, 387], [467, 60, 559, 379]]
Chk 11434 [[97, 45, 248, 320], [448, 24, 634, 443]]
Chk 11435 [[212, 85, 368, 259], [380, 82, 537, 271], [5, 132, 211, 419], [395, 148, 638, 423]]
Chk 11436 [[15, 108, 247, 473], [362, 73, 639, 469]]
Chk 11437 [[275, 55, 377, 535], [22, 70, 176, 390]]

Chk 11438 [[250, 32, 493, 427], [379, 36, 514, 427], [28, 20, 175, 422], [484, 44, 610, 421], [129, 33, 269, 421]]
Chk 11439 [[176, 127, 303, 369], [248, 130, 342, 369], [54, 107, 151, 345], [0, 138, 51, 245], [363, 136, 439, 369], [0, 244, 99, 369], [437, 201, 490, 328]]
Chk 11440 [[323, 198, 434, 479], [331, 168, 557, 479]]
Chk 11442 [[174, 98, 266, 371], [257, 101, 329, 354], [384, 91, 521, 405], [311, 100, 401, 387]]
Chk 11443 [[55, 26, 204, 327], [242, 40, 358, 328], [269, 9, 476, 328]]
Chk 11444 [[244, 67, 395, 421], [374, 34, 543, 425]]
Chk 11445 [[225, 163, 414, 639], [1, 21, 356, 577]]
Chk 11447 [[111, 114, 346, 381], [553, 213, 605, 285], [286, 198, 365, 279], [315, 28, 366, 93], [444, 64, 499, 125]]
Chk 11448 [[122, 144, 296, 319], [292, 144, 441, 323]]
Chk 11449 [[369, 187, 495, 360], [366, 216, 638, 419], [50, 172, 203, 343], [263, 165, 374, 334]]
Chk 11450 [[0, 75, 245, 420], [487, 116, 550, 206], [515, 79, 639, 419], [202, 19, 594, 425]]
Chk 11451 [[0, 154, 226, 404], [279, 65, 476, 393]]
Chk 11452 [[233, 26, 443, 289], [433, 129, 497, 252], [0, 4, 344, 359]]
Chk 11453 [[223, 234, 286, 372], [343, 229, 470, 491], [444, 205, 543, 417], [71, 231, 173, 511], [145, 207, 231, 370], [561, 210, 621, 438], [269, 316, 433, 514], [524, 198, 576, 374]]
Chk 11454 [[90, 67, 252, 259], [248, 21, 373, 284], [177, 8, 264, 156]]
Chk 11456 [[3, 324, 234, 639], [158, 191, 296, 533], [356, 190, 424, 403], [0, 456, 74, 639]]
Chk 11459 [[36, 123, 513, 470], [174, 48, 552, 381], [374, 12, 584, 288]]
Chk 11460 [[57, 64, 286, 570], [193, 257, 332, 575], [270, 68, 506, 517], [32, 140, 107, 327], [537, 127, 589, 255]]
Chk 11461 [[244, 34, 401, 383], [255, 26, 323, 130], [377, 43, 494, 363], [72, 38, 173, 350], [511, 67, 613, 363]]
Chk 11462 [[129, 30, 309, 417], [322, 28, 546, 426], [276, 233, 349, 426], [548, 256, 618, 421]]
Chk 11463 [[0, 5, 424, 421], [284, 59, 510, 409]]
Chk 11465 [[0, 108, 312, 409], [301, 78, 639, 469], [340, 184, 465, 418], [36, 0, 215, 246], [268, 124, 320, 237]]
Chk 11467 [[523, 99, 639, 419], [0, 86, 82, 356], [336, 146, 515, 420], [244, 137, 319, 248], [60, 98, 238, 421]]
Chk 11469 [[54, 0, 260, 420], [325, 0, 433, 325], [371, 21, 517, 339], [572, 9, 639, 271], [222, 4, 305, 325]]
Chk 11470 [[482, 113, 543, 359], [398, 121, 473, 359], [362, 132, 418, 260], [234, 130, 341, 260], [41, 110, 160, 353], [92, 105, 219, 354]]
Chk 11471 [[11, 66, 248, 632], [194, 18, 480, 590]]
Chk 11472 [[211, 25, 347, 365], [0, 80, 142, 405], [123, 83, 180, 237], [337, 76, 391, 227], [384, 60, 573, 421], [527, 55, 639, 422], [45, 52, 117, 193]]
Chk 11474 [[210, 54, 396, 470], [403, 1, 575, 468], [536, 86, 625, 215]]
Chk 11475 [[452, 103, 572, 411], [350, 132, 443, 390], [129, 132, 211, 378], [266, 132, 359, 393]]
Chk 11476 [[228, 128, 423, 632], [56, 199, 423, 627]]
Chk 11477 [[74, 15, 291, 325], [294, 69, 427, 323]]
Chk 11478 [[152, 106, 321, 479], [322, 102, 466, 474]]
Chk 11479 [[177, 95, 281, 449], [20, 79, 224, 447]]
Chk 11480 [[163, 42, 372, 248], [362, 53, 639, 406], [97, 45, 385, 408]]
Chk 11482 [[536, 180, 639, 428], [129, 205, 284, 479], [325, 187, 376, 285], [354, 168, 503, 465]]
Chk 11483 [[261, 100, 359, 463], [346, 99, 455, 447], [438, 62, 545, 434], [188, 102, 283, 472]]
Chk 11484 [[290, 111, 536, 350], [11, 106, 81, 208], [44, 83, 314, 505]]
Chk 11485 [[0, 84, 345, 419], [283, 74, 627, 420]]
Chk 11486 [[165, 63, 348, 629], [312, 186, 391, 295], [121, 18, 181, 130], [242, 13, 295, 102], [325, 208, 427, 548], [45, 211, 124, 386]]
Chk 11487 [[157, 152, 293, 301], [301, 142, 426, 319]]
Chk 11489 [[0, 337, 263, 634], [80, 155, 377, 574], [215, 114, 268, 187]]
Chk 11491 [[18, 143, 143, 420], [393, 79, 579, 420], [557, 141, 608, 280], [238, 96, 420, 425]]
Chk 11492 [[165, 89, 346, 618], [25, 18, 237, 607]]
Chk 11494 [[250, 72, 344, 361], [368, 78, 443, 270], [157, 69, 262, 327]]
Chk 11495 [[0, 30, 134, 222], [156, 2, 302, 217], [81, 13, 245, 228], [295, 1, 436, 193], [504, 2, 613, 170], [214, 50, 348, 202]]
Chk 11496 [[331, 208, 583, 354], [38, 93, 166, 355]]
Chk 11497 [[151, 210, 255, 454], [186, 96, 329, 477]]
Chk 11498 [[537, 85, 639, 216], [180, 153, 447, 391], [470, 286, 639, 418], [421, 106, 548, 383], [57, 1, 251, 392], [322, 102, 404, 235]]
Chk 11499 [[69, 63, 275, 314], [403, 78, 542, 264]]
Chk 11501 [[1, 25, 261, 369], [251, 21, 448, 278]]
Chk 11502 [[1, 61, 285, 412], [434, 96, 634, 427]]
Chk 11503 [[257, 134, 388, 364], [117, 165, 274, 369]]
Chk 11504 [[193, 39, 379, 434], [53, 110, 219, 441]]
Chk 11505 [[351, 57, 592, 382], [275, 0, 462, 117], [0, 182, 168, 474]]
Chk 11506 [[336, 52, 452, 389], [205, 88, 324, 393], [56, 54, 188, 387]]
Chk 11507 [[5, 62, 304, 426], [480, 1, 639, 298], [17, 14, 181, 262], [325, 10, 531, 229]]
Chk 11508 [[0, 140, 173, 492], [280, 277, 407, 436], [484, 205, 639, 466], [114, 252, 172, 382], [0, 52, 291, 639]]
Chk 11509 [[31, 46, 193, 430], [287, 37, 451, 435], [398, 72, 514, 435], [400, 30, 552, 263]]
Chk 11510 [[166, 232, 355, 542], [0, 137, 382, 535]]
Chk 11511 [[119, 13, 319, 477], [297, 127, 497, 471]]
Chk 11512 [[20, 113, 281, 564], [179, 126, 393, 518]]
Chk 11513 [[44, 99, 303, 552], [346, 76, 591, 566], [256, 112, 440, 544]]
Chk 11514 [[140, 94, 357, 390], [112, 391, 359, 626]]
Chk 11516 [[418, 37, 543, 410], [352, 45, 444, 398], [256, 54, 403, 381], [61, 102, 169, 392], [105, 70, 353, 400]]
Chk 11517 [[108, 124, 286, 328], [333, 121, 477, 296], [0, 133, 132, 333], [264, 128, 324, 197], [0, 142, 53, 230], [225, 122, 323, 294]]
Chk 11518 [[220, 134, 446, 314], [11, 135, 224, 300], [452, 160, 619, 290]]
Chk 11520 [[85, 67, 220, 447], [191, 52, 393, 361], [0, 171, 67, 331]]
Chk 11521 [[444, 165, 542, 295], [277, 28, 433, 420], [134, 87, 262, 422], [18, 139, 150, 420], [109, 234, 217, 406], [488, 233, 639, 426]]
Chk 11522 [[502, 31, 579, 115], [326, 106, 469, 417], [182, 220, 348, 406], [112, 72, 167, 176], [539, 243, 627, 312], [0, 106, 124, 403]]
Chk 11524 [[114, 122, 233, 290], [315, 119, 464, 356]]
Chk 11525 [[301, 27, 610, 473], [316, 3, 483, 368]]
Chk 11527 [[313, 53, 639, 421], [560, 72, 639, 358]]
Chk 11528 [[68, 144, 248, 479], [429, 126, 639, 471]]
Chk 11529 [[338, 0, 487, 175], [227, 20, 373, 203], [0, 0, 143, 421]]
Chk 11530 [[44, 174, 241, 473], [244, 123, 438, 475]]
Chk 11533 [[340, 145, 616, 479], [580, 108, 638, 477], [346, 127, 440, 313], [491, 145, 605, 246], [51, 77, 256, 479]]
Chk 11534 [[69, 34, 417, 414], [314, 35, 593, 425], [27, 152, 80, 411], [0, 188, 57, 420]]
Chk 11535 [[109, 16, 469, 425], [349, 74, 587, 366], [568, 166, 638, 343], [535, 139, 609, 195]]
Chk 11536 [[134, 47, 321, 332], [312, 0, 370, 90], [321, 155, 517, 355], [435, 134, 639, 329], [552, 118, 639, 342]]
Chk 11537 [[164, 93, 386, 540], [241, 84, 385, 482]]
Chk 11538 [[132, 6, 332, 632], [1, 263, 206, 611], [295, 263, 402, 520], [395, 337, 479, 567]]
Chk 11539 [[146, 125, 288, 421], [303, 123, 457, 417], [403, 43, 544, 371], [257, 115, 338, 305], [89, 14, 304, 393]]
Chk 11540 [[305, 169, 439, 426], [109, 168, 219, 421], [0, 149, 52, 256], [0, 104, 110, 422], [236, 220, 407, 427]]
Chk 11541 [[130, 144, 271, 526], [235, 129, 400, 543]]
Chk 11542 [[317, 205, 481, 479], [85, 35, 298, 421]]
Chk 11543 [[0, 74, 639, 479], [0, 143, 264, 323]]
Chk 11544 [[31, 243, 132, 365], [15, 267, 329, 498], [463, 92, 556, 243], [414, 70, 488, 161], [399, 224, 639, 455]]
Chk 11545 [[243, 41, 470, 322], [29, 42, 266, 348]]
Chk 11546 [[52, 140, 349, 579], [18, 278, 207, 496]]
Chk 11550 [[370, 165, 540, 421], [263, 151, 384, 426]]
Chk 11551 [[185, 169, 340, 601], [323, 13, 416, 355]]
Chk 11553 [[123, 136, 356, 446], [286, 139, 426, 464], [5, 77, 152, 571]]
Chk 11554 [[171, 396, 254, 639], [286, 325, 384, 638]]
Chk 11555 [[88, 82, 396, 596], [82, 82, 396, 593], [194, 179, 286, 413]]
Chk 11556 [[351, 91, 562, 420], [203, 63, 383, 419], [82, 85, 238, 423]]
Chk 11557 [[222, 113, 419, 398], [463, 196, 609, 381], [396, 88, 462, 163], [466, 0, 559, 145], [53, 40, 124, 246], [588, 83, 639, 170], [290, 74, 365, 155]]
Chk 11558 [[143, 321, 466, 593], [83, 63, 415, 596]]
Chk 11559 [[272, 81, 390, 251], [465, 151, 607, 368], [293, 185, 506, 350]]
Chk 11561 [[33, 129, 250, 354], [320, 96, 521, 320]]
Chk 11562 [[23, 27, 212, 462], [148, 35, 380, 474], [289, 21, 396, 181], [361, 0, 427, 97], [0, 15, 51, 254]]

Chk 11563 [[117, 72, 320, 328], [0, 152, 149, 442], [319, 61, 404, 181], [478, 100, 584, 333], [459, 144, 639, 430], [237, 87, 326, 221], [224, 0, 294, 143], [14, 55, 157, 235]]
Chk 11564 [[142, 77, 295, 414], [414, 278, 561, 418]]
Chk 11565 [[351, 2, 639, 323], [0, 19, 524, 406], [35, 16, 100, 122], [0, 0, 125, 180]]
Chk 11566 [[190, 189, 415, 472], [304, 173, 440, 473]]
Chk 11567 [[25, 53, 134, 188], [338, 77, 422, 247], [582, 79, 639, 188], [125, 0, 207, 139], [489, 39, 632, 319], [410, 105, 497, 257], [159, 64, 224, 154]]
Chk 11568 [[106, 130, 220, 393], [209, 172, 420, 402]]
Chk 11569 [[210, 79, 407, 453], [426, 72, 629, 472]]
Chk 11570 [[257, 187, 471, 496], [271, 91, 377, 284], [40, 190, 210, 502]]
Chk 11572 [[210, 94, 406, 453], [281, 131, 432, 389], [1, 100, 236, 470], [396, 144, 537, 313]]
Chk 11573 [[34, 154, 262, 494], [267, 116, 441, 495]]
Chk 11574 [[411, 81, 472, 192], [350, 78, 431, 335], [85, 44, 142, 205], [9, 0, 124, 360], [203, 32, 328, 361]]
Chk 11575 [[130, 124, 261, 428], [235, 85, 355, 433], [337, 92, 472, 433]]
Chk 11576 [[284, 181, 444, 639], [76, 208, 251, 629]]
Chk 11577 [[86, 71, 338, 475], [194, 28, 405, 446], [386, 73, 568, 408]]
Chk 11579 [[69, 174, 250, 522], [0, 166, 86, 476], [246, 73, 386, 496]]
Chk 11580 [[370, 20, 639, 419], [117, 45, 424, 417]]
Chk 11581 [[1, 177, 247, 463], [218, 23, 426, 462]]
Chk 11582 [[86, 206, 475, 631], [70, 149, 250, 633]]
Chk 11583 [[325, 81, 398, 265], [404, 72, 525, 331], [481, 67, 617, 307], [211, 101, 346, 275], [4, 88, 57, 203]]
Chk 11584 [[76, 106, 282, 421], [242, 49, 470, 356], [384, 48, 549, 408]]
Chk 11585 [[419, 31, 639, 468], [324, 94, 428, 213], [42, 150, 300, 430], [21, 82, 188, 230], [0, 402, 143, 474], [1, 197, 194, 467], [384, 2, 490, 305]]
Chk 11586 [[12, 4, 317, 325], [190, 17, 354, 329]]
Chk 11587 [[316, 127, 519, 479], [55, 130, 319, 472]]
Chk 11588 [[72, 168, 281, 490], [248, 206, 473, 618]]
Chk 11589 [[67, 30, 306, 275], [353, 27, 499, 369]]
Chk 11590 [[385, 90, 509, 474], [116, 66, 245, 473], [228, 131, 287, 217], [0, 177, 83, 359]]
Chk 11591 [[264, 131, 426, 352], [1, 101, 205, 409]]
Chk 11592 [[15, 63, 215, 445], [142, 58, 207, 142], [295, 17, 452, 388], [199, 8, 316, 142], [215, 130, 308, 378], [331, 202, 392, 353], [29, 42, 396, 421]]
Chk 11593 [[200, 8, 625, 451], [155, 164, 244, 394], [41, 157, 215, 451], [132, 117, 207, 200]]
Chk 11594 [[272, 22, 400, 337], [105, 20, 318, 370]]
Chk 11595 [[386, 278, 510, 479], [475, 247, 557, 472]]
Chk 11598 [[1, 28, 358, 419], [175, 46, 365, 271], [265, 51, 394, 233], [326, 51, 462, 220], [410, 54, 510, 186]]
Chk 11599 [[70, 26, 312, 400], [297, 27, 548, 308]]
Chk 11600 [[1, 81, 261, 435], [157, 119, 339, 440], [475, 95, 620, 318], [293, 122, 414, 261]]
Chk 11602 [[28, 11, 320, 472], [308, 181, 464, 473]]
Chk 11604 [[425, 274, 485, 396], [474, 321, 554, 405], [551, 300, 620, 411], [256, 306, 423, 479]]
Chk 11605 [[57, 135, 225, 566], [198, 307, 272, 588], [244, 134, 381, 573], [8, 322, 73, 575], [48, 312, 146, 583]]
Chk 11606 [[33, 132, 245, 474], [414, 78, 639, 478], [347, 148, 447, 301]]
Chk 11607 [[46, 124, 158, 326], [259, 110, 406, 325], [477, 114, 596, 300]]
Chk 11608 [[194, 6, 473, 406], [455, 143, 636, 379], [29, 18, 108, 267], [103, 22, 176, 273]]
Chk 11611 [[166, 54, 417, 545], [37, 39, 253, 524]]
Chk 11612 [[28, 80, 201, 238], [234, 122, 316, 227], [164, 110, 239, 196], [398, 0, 639, 480]]
Chk 11614 [[0, 41, 178, 426], [190, 29, 336, 426], [339, 18, 443, 400], [447, 13, 573, 397], [535, 17, 628, 349], [585, 97, 639, 317]]
Chk 11615 [[169, 84, 286, 392], [353, 61, 448, 299], [284, 46, 366, 377]]
Chk 11616 [[1, 43, 365, 472], [313, 57, 639, 479]]
Chk 11617 [[98, 39, 239, 421], [210, 70, 312, 422], [291, 44, 410, 348], [371, 23, 527, 337]]
Chk 11618 [[260, 214, 417, 459], [417, 130, 604, 472], [239, 134, 300, 192]]
Chk 11620 [[80, 95, 304, 468], [390, 56, 586, 446]]
Chk 11621 [[71, 64, 136, 255], [114, 71, 209, 257], [217, 1, 334, 412], [371, 47, 453, 420], [434, 42, 541, 376]]
Chk 11622 [[336, 113, 594, 422], [14, 111, 305, 421], [561, 211, 625, 402]]
Chk 11623 [[443, 106, 578, 472], [140, 115, 354, 473], [94, 124, 160, 397], [22, 102, 135, 471]]
Chk 11624 [[112, 111, 246, 368], [396, 175, 573, 412], [343, 208, 503, 377]]
Chk 11625 [[322, 225, 405, 538], [250, 239, 328, 493], [139, 259, 240, 542], [90, 266, 149, 386], [409, 200, 580, 624], [389, 266, 444, 485], [42, 307, 101, 454]]
Chk 11626 [[1, 102, 111, 443], [209, 142, 267, 281], [54, 153, 218, 444], [150, 128, 254, 330]]
Chk 11628 [[88, 58, 163, 332], [185, 45, 395, 461], [24, 67, 88, 332], [178, 70, 260, 302]]
Chk 11630 [[1, 232, 387, 532], [284, 14, 420, 278]]
Chk 11631 [[97, 95, 254, 580], [214, 118, 366, 574], [2, 130, 61, 485], [334, 131, 387, 275]]
Chk 11632 [[333, 112, 486, 424], [82, 30, 315, 421], [28, 299, 262, 355]]
Chk 11636 [[348, 175, 639, 479], [0, 149, 157, 447], [358, 148, 510, 381], [481, 107, 550, 202], [125, 133, 216, 337], [410, 43, 481, 146]]
Chk 11637 [[392, 156, 639, 477], [327, 156, 503, 368], [229, 85, 298, 210], [400, 98, 469, 222], [452, 125, 557, 308], [227, 127, 349, 285], [344, 137, 420, 238]]
Chk 11639 [[1, 61, 285, 504], [299, 197, 464, 394], [202, 56, 639, 511]]
Chk 11640 [[112, 156, 264, 475], [0, 139, 162, 632]]
Chk 11641 [[287, 103, 541, 425], [65, 1, 526, 424]]
Chk 11647 [[62, 94, 233, 418], [193, 196, 279, 328], [259, 165, 355, 297], [557, 128, 620, 414], [0, 99, 54, 200], [419, 123, 602, 416], [380, 163, 454, 405]]
Chk 11648 [[468, 220, 639, 475], [249, 105, 366, 248], [136, 7, 301, 219], [147, 136, 267, 323], [0, 175, 208, 350]]
Chk 11650 [[211, 71, 332, 377], [484, 167, 639, 420], [526, 315, 609, 391]]
Chk 11652 [[337, 231, 608, 625], [389, 201, 497, 477], [55, 218, 199, 543], [133, 223, 222, 394], [99, 172, 170, 248]]
Chk 11653 [[251, 212, 324, 463], [199, 192, 492, 506], [33, 195, 263, 509]]
Chk 11654 [[182, 132, 357, 418], [580, 212, 639, 426], [453, 242, 596, 444], [65, 44, 136, 162], [197, 106, 255, 179], [433, 124, 496, 204], [350, 114, 403, 190], [1, 32, 64, 157]]
Chk 11656 [[138, 109, 244, 378], [226, 194, 324, 354], [0, 218, 116, 461]]
Chk 11657 [[29, 108, 172, 470], [250, 145, 382, 388], [3, 134, 622, 373]]
Chk 11658 [[267, 120, 369, 471], [353, 82, 489, 480], [546, 119, 635, 420]]
Chk 11659 [[229, 86, 623, 516], [561, 246, 639, 405], [2, 0, 87, 234], [96, 58, 169, 189], [0, 0, 368, 522], [509, 221, 567, 325], [526, 227, 603, 341]]
Chk 11660 [[5, 47, 454, 440], [310, 146, 543, 440], [533, 341, 639, 447]]
Chk 11662 [[50, 189, 201, 327], [335, 18, 622, 385], [0, 0, 137, 341]]
Chk 11665 [[244, 104, 417, 398], [72, 100, 247, 374], [414, 84, 586, 424]]
Chk 11666 [[75, 29, 229, 275], [298, 166, 621, 304]]
Chk 11667 [[64, 170, 326, 464], [215, 195, 411, 557], [14, 243, 150, 557]]
Chk 11668 [[349, 19, 639, 473], [0, 79, 389, 479]]
Chk 11669 [[27, 43, 237, 338], [111, 49, 270, 337], [314, 49, 376, 218], [60, 40, 140, 258]]
Chk 11670 [[70, 85, 459, 421], [22, 43, 173, 366]]
Chk 11671 [[5, 63, 281, 420], [344, 107, 639, 417]]
Chk 11672 [[256, 42, 541, 426], [405, 25, 639, 426], [438, 8, 500, 64], [23, 23, 358, 420], [506, 0, 557, 57], [587, 65, 639, 341], [330, 32, 400, 125]]
Chk 11673 [[294, 55, 424, 418], [112, 64, 331, 419]]
Chk 11674 [[150, 264, 224, 530], [222, 265, 317, 555]]
Chk 11675 [[86, 2, 606, 424], [347, 27, 513, 269], [0, 74, 178, 419]]
Chk 11676 [[142, 29, 240, 357], [273, 87, 554, 486], [0, 230, 212, 497]]
Chk 11678 [[73, 169, 212, 630], [128, 101, 469, 637]]
Chk 11679 [[323, 24, 492, 318], [324, 45, 639, 474]]
Chk 11681 [[5, 126, 294, 606], [234, 90, 456, 566], [456, 103, 514, 200], [4, 19, 65, 174], [13, 64, 166, 501], [123, 44, 182, 116]]
Chk 11682 [[330, 0, 557, 473], [0, 0, 379, 477]]
Chk 11685 [[26, 46, 257, 631], [247, 24, 375, 381]]
Chk 11686 [[260, 44, 637, 423], [401, 50, 636, 378], [38, 60, 397, 419], [450, 0, 553, 114], [241, 0, 307, 131], [200, 0, 256, 102], [308, 0, 372, 56], [367, 1, 452, 174]]
Chk 11687 [[2, 36, 364, 471], [339, 40, 639, 479], [137, 65, 281, 479]]
Chk 11688 [[0, 0, 263, 363], [177, 0, 334, 264]]
Chk 11690 [[241, 93, 379, 422], [368, 89, 478, 420], [195, 151, 273, 269], [70, 116, 161, 383]]
Chk 11691 [[240, 122, 402, 632], [100, 114, 270, 639]]
Chk 11692 [[332, 27, 528, 511], [147, 43, 344, 279]]
Chk 11693 [[236, 133, 340, 400], [393, 88, 480, 406]]
Chk 11694 [[247, 92, 420, 632], [0, 100, 182, 632]]
Chk 11695 [[103, 88, 256, 310], [244, 166, 414, 306]]
Chk 11698 [[117, 104, 228, 389], [213, 127, 300, 387], [359, 139, 433, 383], [423, 121, 512, 385], [289, 160, 364, 385]]
Chk 11701 [[111, 54, 300, 421], [435, 88, 602, 375], [273, 52, 483, 425]]

Chk 11702 [[57, 46, 387, 424], [289, 73, 594, 421]]
Chk 11704 [[154, 49, 482, 631], [1, 15, 226, 626]]
Chk 11705 [[92, 107, 277, 377], [247, 98, 364, 365], [455, 58, 601, 280], [13, 88, 85, 268], [398, 64, 460, 247]]
Chk 11706 [[143, 138, 620, 394], [24, 151, 509, 479], [283, 33, 609, 220], [222, 92, 370, 257]]
Chk 11707 [[336, 156, 572, 413], [108, 148, 216, 416]]
Chk 11709 [[111, 93, 374, 496], [121, 51, 276, 491]]
Chk 11710 [[25, 149, 269, 479], [293, 155, 371, 264], [368, 118, 610, 472], [245, 157, 403, 474], [2, 169, 86, 309]]
Chk 11711 [[0, 299, 301, 639], [47, 31, 438, 630]]
Chk 11712 [[450, 90, 530, 171], [32, 96, 217, 349], [163, 99, 261, 205], [252, 86, 342, 189], [434, 114, 595, 336]]
Chk 11713 [[156, 181, 424, 555], [24, 110, 431, 624]]
Chk 11715 [[304, 38, 510, 420], [422, 103, 639, 424]]
Chk 11716 [[218, 36, 452, 225], [393, 59, 544, 242], [470, 23, 610, 175], [0, 10, 305, 347]]
Chk 11717 [[353, 223, 639, 632], [283, 126, 461, 609], [0, 153, 128, 630]]
Chk 11719 [[125, 119, 328, 439], [13, 125, 204, 492]]
Chk 11720 [[170, 17, 320, 377], [265, 74, 388, 369], [517, 111, 570, 248], [111, 39, 174, 178], [394, 119, 490, 282], [468, 106, 525, 238]]
Chk 11721 [[2, 109, 324, 472], [294, 88, 547, 472]]
Chk 11722 [[0, 86, 375, 418], [194, 5, 639, 419], [0, 74, 130, 388], [544, 116, 638, 420]]
Chk 11723 [[56, 117, 204, 328], [300, 47, 472, 328]]
Chk 11727 [[338, 216, 479, 569], [73, 185, 259, 623]]
Chk 11728 [[217, 52, 562, 628], [158, 63, 365, 629], [38, 165, 244, 632], [271, 1, 375, 67]]
Chk 11730 [[202, 76, 357, 427], [8, 98, 222, 422], [377, 23, 609, 423]]
Chk 11731 [[239, 303, 350, 523], [116, 41, 259, 584]]
Chk 11734 [[103, 117, 424, 559], [59, 165, 172, 317], [65, 183, 281, 458], [359, 143, 424, 238]]
Chk 11735 [[282, 104, 499, 298], [444, 1, 499, 121], [352, 0, 424, 116], [32, 0, 151, 318]]
Chk 11736 [[267, 19, 639, 451], [1, 1, 388, 450], [474, 1, 639, 289]]
Chk 11737 [[302, 98, 456, 466], [30, 69, 222, 418], [503, 128, 601, 372]]
Chk 11739 [[31, 105, 238, 639], [385, 133, 450, 297], [0, 79, 90, 550], [217, 78, 448, 631]]
Chk 11740 [[39, 97, 374, 500], [311, 16, 477, 488], [407, 28, 628, 511], [0, 72, 104, 483]]
Chk 11741 [[497, 17, 611, 313], [182, 137, 423, 388]]
Chk 11742 [[4, 16, 252, 285], [409, 97, 639, 330]]
Chk 11743 [[138, 182, 281, 424], [260, 170, 483, 423], [56, 233, 109, 311]]
Chk 11744 [[134, 185, 355, 427], [399, 126, 518, 387], [477, 31, 635, 288]]
Chk 11745 [[338, 91, 624, 418], [54, 120, 252, 340], [588, 152, 639, 248]]
Chk 11748 [[496, 78, 637, 472], [60, 110, 452, 479]]
Chk 11749 [[326, 40, 541, 330], [149, 63, 352, 274], [513, 87, 564, 149]]
Chk 11750 [[224, 133, 378, 386], [360, 164, 534, 407], [556, 163, 623, 248], [0, 177, 150, 381], [391, 235, 639, 479]]
Chk 11751 [[215, 62, 457, 413], [389, 25, 595, 411]]
Chk 11752 [[43, 0, 472, 426], [241, 126, 562, 422]]
Chk 11753 [[137, 33, 486, 418], [361, 41, 505, 414]]
Chk 11756 [[150, 229, 426, 632], [75, 112, 221, 463], [13, 144, 142, 448]]
Chk 11757 [[128, 93, 347, 425], [322, 79, 535, 426]]
Chk 11758 [[239, 72, 358, 399], [117, 174, 209, 417]]
Chk 11760 [[162, 46, 381, 329], [64, 142, 220, 326]]
Chk 11761 [[1, 122, 172, 320], [408, 112, 499, 172], [377, 255, 499, 327], [102, 128, 380, 323]]
Chk 11762 [[440, 2, 639, 426], [310, 118, 468, 358], [101, 134, 326, 337]]
Chk 11763 [[264, 58, 468, 340], [439, 73, 596, 359], [28, 59, 347, 438]]
Chk 11765 [[288, 113, 445, 305], [0, 231, 186, 639], [0, 161, 176, 430], [141, 91, 311, 306]]
Chk 11766 [[112, 9, 197, 147], [216, 50, 422, 355], [316, 37, 377, 224], [372, 94, 449, 292], [429, 47, 503, 176], [476, 17, 582, 324], [527, 0, 637, 319], [0, 48, 466, 418]]
Chk 11767 [[1, 112, 383, 445], [348, 6, 562, 317]]
Chk 11768 [[0, 114, 98, 381], [278, 28, 560, 469], [135, 132, 229, 385], [200, 128, 259, 325], [339, 92, 392, 319], [232, 157, 285, 386], [69, 136, 155, 378], [516, 200, 618, 349]]
Chk 11770 [[56, 96, 303, 343], [428, 39, 579, 415]]
Chk 11771 [[320, 95, 563, 410], [60, 0, 510, 465], [0, 0, 298, 476], [584, 222, 639, 479]]
Chk 11772 [[353, 163, 606, 473], [63, 105, 314, 479], [358, 126, 438, 318], [1, 193, 68, 479]]
Chk 11775 [[202, 86, 390, 317], [6, 56, 611, 600]]
Chk 11776 [[316, 20, 593, 592], [15, 24, 364, 604]]
Chk 11778 [[240, 29, 584, 419], [0, 51, 291, 425], [533, 172, 591, 255]]
Chk 11779 [[468, 88, 587, 421], [579, 94, 639, 249], [337, 67, 485, 420], [219, 18, 356, 256], [580, 114, 639, 418], [80, 89, 145, 165]]
Chk 11780 [[428, 275, 553, 479], [145, 161, 322, 417], [261, 310, 441, 473]]
Chk 11782 [[289, 107, 395, 229], [455, 136, 551, 276], [544, 135, 639, 366], [0, 135, 306, 426], [104, 103, 243, 341], [415, 260, 534, 420]]
Chk 11784 [[442, 146, 499, 374], [322, 88, 442, 374], [37, 79, 236, 369], [201, 80, 319, 373], [267, 197, 349, 373], [0, 249, 101, 374]]
Chk 11785 [[213, 46, 467, 413], [184, 111, 328, 419]]
Chk 11786 [[109, 94, 240, 518], [231, 104, 283, 191], [276, 116, 391, 533]]
Chk 11789 [[188, 257, 302, 537], [0, 340, 69, 639], [163, 247, 236, 473]]
Chk 11791 [[119, 102, 302, 478], [348, 132, 514, 479]]
Chk 11792 [[197, 80, 308, 387], [317, 78, 449, 399]]
Chk 11793 [[281, 59, 378, 374], [0, 27, 100, 373], [187, 26, 290, 374], [73, 49, 226, 370]]
Chk 11795 [[215, 77, 331, 326], [316, 94, 429, 317], [300, 112, 490, 326], [148, 103, 219, 245]]
Chk 11797 [[175, 103, 337, 405], [376, 277, 546, 463], [532, 265, 639, 474]]
Chk 11798 [[111, 103, 185, 327], [194, 86, 324, 360], [329, 108, 454, 324], [442, 91, 568, 392], [554, 79, 639, 295], [249, 84, 371, 351], [574, 292, 639, 411]]
Chk 11799 [[37, 133, 254, 374], [358, 88, 499, 364], [15, 0, 131, 199], [212, 69, 375, 368]]
Chk 11800 [[261, 121, 396, 387], [177, 136, 268, 273], [371, 173, 453, 288], [504, 236, 638, 353], [34, 148, 190, 294]]
Chk 11802 [[293, 86, 407, 363], [374, 119, 570, 394], [1, 46, 268, 414]]
Chk 11805 [[428, 107, 549, 403], [33, 132, 144, 430], [129, 125, 227, 403], [400, 113, 452, 382], [247, 117, 342, 393], [337, 117, 431, 401], [202, 97, 268, 385]]
Chk 11807 [[401, 122, 537, 473], [77, 46, 217, 363]]
Chk 11808 [[112, 152, 410, 479], [346, 107, 637, 471], [321, 81, 421, 206], [3, 105, 245, 472]]
Chk 11809 [[4, 2, 362, 371], [1, 230, 130, 628], [284, 142, 420, 315], [247, 49, 303, 209], [184, 10, 313, 240], [13, 65, 74, 146], [287, 56, 425, 220]]
Chk 11811 [[148, 67, 262, 325], [216, 76, 275, 319], [245, 103, 338, 367], [347, 122, 447, 367], [125, 75, 193, 186]]
Chk 11813 [[52, 84, 388, 477], [333, 115, 543, 326], [220, 1, 319, 276], [27, 25, 107, 126]]
Chk 11815 [[91, 136, 258, 620], [244, 132, 441, 620]]
Chk 11817 [[50, 117, 212, 590], [153, 20, 358, 543]]
Chk 11818 [[369, 3, 611, 419], [153, 35, 338, 362]]
Chk 11819 [[517, 198, 639, 349], [14, 28, 158, 271], [213, 148, 324, 274], [99, 144, 202, 252], [289, 189, 348, 256], [181, 184, 362, 435], [396, 162, 492, 275], [316, 160, 401, 369]]
Chk 11822 [[341, 133, 553, 381], [89, 116, 281, 383]]
Chk 11823 [[474, 202, 640, 487], [14, 158, 200, 487], [170, 36, 500, 480]]
Chk 11824 [[198, 139, 415, 485], [17, 79, 221, 544]]
Chk 11825 [[199, 66, 495, 472], [62, 115, 299, 482]]
Chk 11826 [[139, 108, 400, 327], [0, 0, 363, 326]]
Chk 11828 [[245, 1, 635, 474], [305, 118, 449, 334]]
Chk 11829 [[268, 82, 386, 322], [92, 68, 230, 328]]
Chk 11830 [[50, 120, 220, 481], [160, 276, 387, 632]]
Chk 11831 [[114, 76, 308, 349], [273, 49, 449, 238], [37, 75, 220, 240], [19, 81, 175, 217]]
Chk 11832 [[48, 101, 171, 374], [208, 105, 477, 455]]
Chk 11833 [[104, 236, 190, 492], [173, 211, 273, 499]]
Chk 11834 [[235, 116, 347, 301], [362, 40, 449, 273], [341, 30, 609, 419]]
Chk 11835 [[448, 0, 639, 479], [258, 0, 425, 341]]
Chk 11836 [[4, 74, 114, 403], [358, 188, 496, 369], [19, 216, 170, 404], [8, 309, 274, 607]]
Chk 11837 [[439, 199, 556, 414], [93, 117, 217, 408], [219, 163, 281, 269]]
Chk 11838 [[88, 181, 227, 425], [180, 151, 262, 313], [432, 59, 553, 222], [455, 142, 550, 382], [386, 123, 484, 305], [246, 113, 300, 211], [286, 107, 338, 176]]
Chk 11839 [[145, 106, 397, 350], [15, 195, 247, 450], [123, 368, 182, 452], [313, 355, 380, 436]]
Chk 11840 [[189, 30, 618, 458], [209, 129, 516, 472]]
Chk 11841 [[497, 121, 639, 335], [564, 102, 617, 173], [318, 140, 546, 405], [1, 165, 86, 419], [114, 94, 189, 188], [55, 92, 119, 167]]
Chk 11842 [[1, 67, 477, 632], [185, 67, 475, 629]]

Chk 11843 [[149, 1, 350, 195], [358, 0, 529, 159], [195, 248, 590, 470], [76, 0, 211, 280], [0, 0, 117, 308], [512, 62, 613, 161], [0, 331, 54, 442], [548, 359, 639, 466]]
Chk 11845 [[235, 226, 476, 632], [60, 182, 354, 428], [16, 206, 167, 402], [235, 100, 353, 266], [379, 14, 479, 242]]
Chk 11846 [[226, 84, 394, 425], [369, 96, 458, 369], [425, 31, 543, 421], [240, 62, 297, 219]]
Chk 11847 [[165, 75, 253, 271], [409, 206, 504, 445], [221, 129, 380, 479]]
Chk 11849 [[269, 72, 501, 343], [80, 46, 236, 342]]
Chk 11850 [[39, 1, 336, 421], [181, 98, 364, 329], [278, 34, 479, 305]]
Chk 11851 [[224, 149, 364, 610], [95, 141, 226, 623]]
Chk 11853 [[190, 167, 363, 415], [511, 94, 639, 381], [17, 175, 97, 361], [275, 143, 401, 415]]
Chk 11854 [[165, 65, 325, 291], [442, 162, 532, 395]]
Chk 11855 [[434, 131, 524, 468], [256, 136, 345, 470], [153, 162, 253, 418], [110, 142, 169, 327], [578, 154, 639, 356], [520, 212, 576, 348]]
Chk 11858 [[157, 91, 298, 375], [280, 56, 538, 419], [267, 84, 350, 274]]
Chk 11859 [[441, 63, 610, 477], [238, 46, 435, 479]]
Chk 11860 [[72, 48, 239, 558], [283, 402, 425, 547], [41, 254, 129, 559]]
Chk 11861 [[255, 100, 402, 441], [366, 44, 578, 447], [119, 236, 177, 364], [561, 200, 639, 456]]
Chk 11862 [[1, 102, 130, 496], [121, 97, 367, 494], [184, 1, 367, 214]]
Chk 11863 [[117, 127, 356, 591], [357, 27, 494, 611]]
Chk 11864 [[300, 196, 639, 333], [34, 219, 309, 322]]
Chk 11865 [[1, 185, 68, 348], [93, 168, 174, 370], [470, 115, 606, 346], [130, 214, 269, 425], [460, 246, 639, 471]]
Chk 11866 [[249, 197, 379, 638], [26, 270, 177, 634], [388, 156, 518, 627]]
Chk 11867 [[21, 0, 388, 467], [1, 77, 575, 478]]
Chk 11869 [[33, 29, 203, 334], [180, 24, 324, 421], [334, 20, 477, 399], [450, 9, 581, 368]]
Chk 11871 [[17, 0, 330, 225], [43, 113, 248, 347], [394, 47, 639, 479], [427, 8, 529, 95]]
Chk 11872 [[282, 59, 523, 438], [69, 130, 304, 443]]
Chk 11874 [[391, 108, 621, 420], [232, 38, 428, 421], [35, 38, 266, 417]]
Chk 11875 [[3, 89, 296, 462], [212, 162, 271, 302], [203, 85, 382, 400]]
Chk 11877 [[140, 170, 225, 420], [275, 139, 348, 419], [337, 154, 416, 405], [212, 145, 277, 417]]
Chk 11878 [[46, 0, 208, 352], [0, 0, 167, 472]]
Chk 11879 [[304, 136, 410, 236], [290, 201, 427, 368], [82, 90, 276, 331]]
Chk 11881 [[542, 10, 639, 416], [88, 39, 326, 338], [279, 151, 540, 379]]
Chk 11882 [[179, 107, 479, 547], [39, 107, 170, 323], [0, 155, 92, 269]]
Chk 11883 [[378, 60, 569, 452], [349, 30, 462, 310]]
Chk 11884 [[108, 52, 263, 420], [316, 96, 513, 412]]
Chk 11885 [[227, 136, 477, 494], [409, 290, 639, 564]]
Chk 11887 [[377, 163, 559, 474], [149, 121, 336, 479]]
Chk 11888 [[187, 41, 524, 421], [43, 143, 349, 426]]
Chk 11889 [[56, 0, 330, 411], [370, 102, 563, 416]]
Chk 11890 [[545, 44, 639, 357], [374, 107, 515, 357], [63, 52, 318, 363], [239, 165, 292, 260], [290, 168, 366, 273]]
Chk 11891 [[0, 156, 301, 473], [286, 155, 560, 479]]
Chk 11892 [[240, 48, 441, 472], [0, 121, 332, 472], [121, 67, 211, 225], [463, 81, 639, 479], [0, 92, 194, 479], [451, 153, 514, 306]]
Chk 11893 [[1, 189, 272, 629], [146, 199, 425, 631]]
Chk 11894 [[72, 0, 481, 419], [365, 2, 639, 420], [48, 0, 169, 79]]
Chk 11895 [[52, 73, 566, 421], [0, 120, 184, 420], [303, 60, 572, 423]]
Chk 11896 [[166, 7, 374, 384], [1, 10, 169, 364]]
Chk 11898 [[2, 53, 279, 390], [274, 62, 638, 309], [259, 119, 330, 219], [492, 118, 575, 249]]
Chk 11899 [[62, 78, 181, 433], [175, 85, 296, 426]]
Chk 11900 [[83, 86, 305, 420], [318, 112, 506, 425]]
Chk 11901 [[50, 198, 281, 403], [106, 225, 424, 455]]
Chk 11902 [[184, 152, 410, 623], [47, 76, 197, 505]]
Chk 11904 [[122, 204, 373, 523], [134, 133, 256, 281], [228, 57, 397, 332], [209, 45, 270, 135]]
Chk 11905 [[54, 165, 303, 414], [221, 0, 624, 421], [505, 369, 639, 426]]
Chk 11906 [[300, 136, 639, 468], [154, 134, 379, 479]]
Chk 11907 [[332, 20, 521, 199], [458, 74, 639, 393], [106, 48, 279, 221]]
Chk 11908 [[273, 30, 552, 376], [26, 1, 341, 379]]
Chk 11910 [[3, 21, 274, 422], [385, 99, 516, 411], [551, 112, 639, 419], [267, 125, 358, 310], [267, 163, 404, 426]]
Chk 11911 [[84, 364, 246, 629], [230, 102, 381, 488], [216, 340, 398, 639]]
Chk 11912 [[302, 151, 519, 466], [10, 289, 174, 454], [0, 255, 51, 479]]
Chk 11914 [[137, 120, 408, 572], [0, 105, 115, 560], [165, 32, 279, 259], [337, 89, 426, 469]]
Chk 11915 [[77, 60, 355, 417], [332, 25, 639, 416]]
Chk 11916 [[226, 168, 371, 621], [138, 201, 254, 599]]
Chk 11917 [[366, 43, 637, 420], [0, 134, 273, 419]]
Chk 11918 [[246, 64, 457, 330], [120, 67, 298, 327]]
Chk 11920 [[234, 29, 505, 423], [433, 49, 553, 423], [577, 92, 639, 404]]
Chk 11921 [[109, 101, 311, 491], [313, 70, 524, 492]]
Chk 11922 [[22, 47, 431, 474], [379, 1, 639, 474]]
Chk 11924 [[187, 31, 361, 272], [294, 80, 428, 394], [462, 121, 639, 419], [21, 114, 153, 386], [135, 140, 209, 384]]
Chk 11925 [[327, 145, 463, 501], [148, 190, 283, 504]]
Chk 11926 [[269, 221, 551, 639], [249, 224, 462, 624], [100, 234, 291, 593], [214, 266, 387, 607]]
Chk 11927 [[381, 36, 617, 404], [250, 65, 507, 368], [173, 172, 224, 234]]
Chk 11928 [[24, 88, 390, 374], [0, 104, 117, 374]]
Chk 11929 [[95, 190, 361, 629], [10, 76, 411, 639]]
Chk 11931 [[227, 21, 426, 233], [111, 62, 237, 330]]
Chk 11932 [[1, 3, 243, 380], [418, 0, 639, 423]]
Chk 11933 [[165, 142, 317, 470], [306, 132, 523, 479]]
Chk 11934 [[307, 162, 433, 356], [371, 107, 544, 575], [272, 123, 408, 529]]
Chk 11935 [[252, 76, 467, 424], [493, 204, 637, 416]]
Chk 11936 [[2, 11, 264, 456], [363, 66, 632, 429]]
Chk 11938 [[184, 67, 397, 622], [41, 87, 211, 593]]
Chk 11939 [[15, 53, 223, 315], [309, 55, 623, 427]]
Chk 11940 [[176, 122, 405, 420], [0, 23, 204, 420], [402, 87, 533, 426]]
Chk 11941 [[312, 168, 499, 420], [172, 150, 341, 426], [197, 9, 284, 162]]
Chk 11944 [[132, 71, 329, 493], [0, 68, 137, 500]]
Chk 11945 [[211, 18, 364, 369], [429, 25, 549, 363], [401, 139, 454, 262], [537, 179, 599, 273], [38, 210, 92, 289]]
Chk 11946 [[0, 50, 190, 426], [169, 154, 240, 321], [220, 137, 326, 228], [445, 122, 502, 323], [502, 125, 556, 295]]
Chk 11948 [[1, 18, 325, 490], [41, 22, 399, 499]]
Chk 11949 [[221, 36, 612, 408], [34, 70, 437, 486]]
Chk 11951 [[0, 20, 366, 472], [274, 142, 639, 479]]
Chk 11952 [[2, 37, 246, 449], [334, 96, 603, 401]]
Chk 11953 [[249, 59, 341, 307], [355, 69, 504, 378], [317, 48, 629, 415], [172, 74, 229, 270], [102, 88, 169, 250], [567, 94, 632, 220], [316, 17, 394, 283]]
Chk 11954 [[79, 0, 267, 470], [227, 103, 513, 479]]
Chk 11955 [[64, 16, 256, 423], [297, 80, 513, 391]]
Chk 11956 [[223, 22, 423, 418], [65, 15, 379, 426]]
Chk 11957 [[288, 129, 410, 621], [63, 118, 274, 628], [89, 145, 149, 282], [58, 155, 295, 562]]
Chk 11958 [[297, 171, 382, 420], [357, 121, 451, 423]]
Chk 11959 [[208, 103, 392, 479], [375, 83, 539, 384], [0, 163, 92, 308]]
Chk 11960 [[39, 36, 219, 486], [428, 27, 580, 511]]
Chk 11961 [[413, 78, 581, 423], [306, 116, 432, 452], [201, 89, 367, 474], [45, 297, 100, 419], [58, 110, 235, 474], [32, 355, 88, 431]]
Chk 11962 [[2, 234, 216, 474], [285, 126, 429, 447]]
Chk 11963 [[53, 154, 390, 456], [50, 115, 246, 317]]
Chk 11964 [[271, 83, 499, 377], [1, 87, 435, 377]]
Chk 11965 [[103, 33, 258, 385], [226, 21, 402, 427], [156, 44, 239, 246]]
Chk 11966 [[0, 132, 92, 479], [362, 126, 434, 472], [289, 115, 398, 478], [282, 113, 338, 290], [202, 128, 324, 284], [390, 129, 596, 472], [195, 112, 302, 278]]
Chk 11967 [[256, 45, 471, 291], [0, 164, 215, 410]]
Chk 11969 [[26, 64, 596, 606], [460, 115, 590, 476], [20, 166, 159, 448]]
Chk 11970 [[0, 20, 364, 395], [266, 93, 582, 399]]
Chk 11971 [[306, 190, 412, 413], [444, 56, 639, 479], [0, 0, 164, 473], [283, 386, 426, 473]]
Chk 11972 [[117, 54, 274, 471], [355, 15, 526, 379]]
Chk 11973 [[2, 162, 264, 479], [385, 148, 639, 479], [364, 180, 514, 406], [572, 80, 639, 277], [165, 178, 324, 376]]
Chk 11974 [[260, 178, 455, 322], [4, 24, 236, 386]]
Chk 11975 [[193, 149, 337, 384], [166, 43, 334, 398], [480, 32, 638, 349]]
Chk 11976 [[110, 181, 353, 544], [74, 209, 136, 320], [250, 355, 307, 521], [433, 208, 512, 316], [142, 221, 193, 317], [297, 203, 414, 596]]
Chk 11977 [[380, 166, 504, 426], [291, 160, 404, 426]]
Chk 11978 [[80, 183, 224, 406], [118, 54, 258, 318], [68, 83, 134, 180], [2, 79, 116, 256], [182, 15, 307, 244]]
Chk 11979 [[80, 20, 244, 354], [211, 51, 395, 359], [297, 71, 396, 359]]
Chk 11980 [[292, 15, 501, 472], [472, 65, 590, 467]]
Chk 11981 [[179, 126, 424, 639], [0, 130, 190, 630]]
Chk 11982 [[319, 115, 446, 387], [282, 47, 378, 350], [381, 23, 474, 271], [458, 38, 558, 368]]
Chk 11983 [[135, 5, 339, 449], [466, 16, 618, 450], [56, 70, 172, 448], [284, 74, 369, 312]]
Chk 11984 [[0, 109, 359, 472], [164, 104, 454, 387], [494, 174, 639, 380]]

Chk 11985 [[50, 36, 503, 350], [64, 214, 370, 434], [8, 24, 75, 102], [180, 31, 271, 111]]
Chk 11986 [[201, 5, 615, 479], [0, 64, 241, 479]]
Chk 11989 [[118, 35, 414, 412], [1, 195, 265, 448]]
Chk 11991 [[0, 204, 139, 423], [391, 143, 639, 473]]
Chk 11994 [[34, 183, 154, 494], [90, 188, 151, 458], [267, 184, 374, 490], [201, 163, 305, 319], [302, 176, 353, 386]]
Chk 11995 [[355, 153, 457, 382], [90, 246, 212, 500], [490, 252, 638, 446], [427, 198, 582, 470], [466, 226, 528, 371], [46, 138, 166, 310]]
Chk 11997 [[389, 8, 533, 400], [385, 67, 639, 473], [363, 87, 450, 330], [3, 79, 232, 473], [10, 38, 130, 197], [269, 68, 330, 217], [0, 207, 57, 294]]
Chk 11998 [[278, 7, 504, 328], [23, 192, 185, 361]]
Chk 11999 [[94, 0, 495, 367], [0, 41, 190, 374]]
Chk 12000 [[117, 93, 245, 332], [298, 62, 420, 362], [268, 75, 334, 357], [404, 82, 459, 188], [23, 101, 191, 362]]
Chk 12001 [[50, 111, 285, 473], [225, 88, 447, 478]]
Chk 12002 [[153, 30, 400, 502], [330, 1, 564, 502]]
Chk 12003 [[291, 168, 470, 492], [207, 153, 351, 492], [316, 8, 470, 164], [2, 136, 177, 490], [0, 116, 268, 499]]
Chk 12004 [[297, 189, 426, 639], [265, 94, 406, 581], [15, 159, 260, 633], [198, 314, 279, 639]]
Chk 12005 [[91, 188, 216, 398], [178, 105, 278, 398]]
Chk 12006 [[217, 65, 519, 606], [95, 41, 279, 539]]
Chk 12007 [[207, 156, 314, 436], [247, 212, 394, 418], [103, 155, 207, 434]]
Chk 12008 [[31, 72, 202, 399], [281, 23, 516, 518]]
Chk 12009 [[230, 65, 454, 414], [169, 95, 273, 408], [0, 122, 157, 418], [426, 87, 618, 414]]
Chk 12010 [[455, 11, 639, 267], [36, 83, 199, 263]]
Chk 12013 [[230, 23, 410, 345], [23, 56, 189, 345], [65, 130, 157, 345]]
Chk 12014 [[230, 76, 464, 423], [514, 89, 606, 418], [387, 1, 445, 147], [0, 151, 51, 410]]
Chk 12015 [[394, 50, 639, 422], [584, 144, 639, 286], [221, 26, 453, 416], [0, 137, 321, 426], [0, 163, 78, 361], [411, 176, 487, 375], [188, 86, 250, 160]]
Chk 12017 [[94, 22, 591, 420], [338, 51, 543, 418]]
Chk 12018 [[304, 77, 481, 419], [10, 27, 350, 426]]
Chk 12019 [[81, 107, 377, 637], [0, 3, 190, 631]]
Chk 12022 [[2, 219, 251, 638], [24, 94, 443, 515]]
Chk 12023 [[369, 208, 466, 304], [0, 76, 506, 469], [231, 140, 468, 442]]
Chk 12024 [[21, 310, 182, 555], [23, 201, 105, 254], [410, 125, 466, 292], [198, 204, 316, 518]]
Chk 12025 [[0, 12, 421, 419], [204, 36, 329, 224], [252, 89, 471, 412]]
Chk 12026 [[205, 48, 370, 478], [63, 128, 145, 394]]
Chk 12027 [[122, 3, 599, 475], [3, 189, 444, 471]]
Chk 12028 [[369, 148, 575, 502], [233, 149, 403, 474], [99, 136, 231, 392]]
Chk 12029 [[105, 49, 432, 479], [1, 7, 216, 471], [365, 77, 428, 347], [529, 87, 639, 348], [569, 59, 639, 152], [508, 95, 580, 266]]
Chk 12030 [[68, 75, 240, 446], [343, 111, 487, 359]]
Chk 12031 [[28, 81, 228, 326], [185, 83, 322, 301], [290, 52, 450, 296], [398, 91, 590, 361]]
Chk 12032 [[173, 76, 300, 403], [332, 79, 505, 416], [513, 85, 615, 413], [0, 25, 51, 208]]
Chk 12033 [[399, 165, 561, 420], [169, 142, 259, 322], [315, 129, 412, 276], [61, 14, 174, 305], [392, 152, 463, 285], [104, 109, 188, 282]]
Chk 12034 [[429, 125, 585, 447], [315, 190, 367, 297]]
Chk 12035 [[71, 8, 370, 426], [438, 114, 598, 402], [0, 140, 143, 426]]
Chk 12036 [[221, 312, 385, 513], [17, 30, 247, 639], [0, 396, 110, 618]]
Chk 12037 [[152, 107, 270, 378], [248, 124, 351, 375], [330, 80, 458, 373]]
Chk 12038 [[0, 81, 480, 639], [107, 1, 479, 633]]
Chk 12039 [[41, 290, 231, 428], [109, 429, 244, 592], [62, 76, 237, 225]]
Chk 12041 [[274, 60, 403, 202], [174, 82, 297, 239], [46, 59, 263, 328], [436, 28, 499, 148], [163, 55, 239, 187], [0, 70, 86, 333]]
Chk 12044 [[274, 14, 637, 419], [136, 106, 259, 277]]
Chk 12045 [[60, 180, 296, 472], [481, 99, 623, 275], [273, 101, 417, 477]]
Chk 12046 [[447, 102, 639, 418], [373, 41, 542, 420], [4, 1, 195, 418]]
Chk 12048 [[2, 276, 59, 448], [249, 23, 436, 547], [390, 55, 507, 275], [105, 215, 193, 309]]
Chk 12049 [[201, 227, 295, 513], [314, 127, 507, 507]]
Chk 12050 [[30, 61, 282, 464], [408, 140, 639, 466], [393, 245, 463, 466]]
Chk 12051 [[158, 140, 400, 349], [431, 252, 639, 433], [19, 228, 126, 346]]
Chk 12052 [[119, 132, 388, 474], [302, 97, 635, 472]]
Chk 12053 [[67, 41, 282, 421], [266, 55, 444, 248], [333, 162, 620, 426]]
Chk 12054 [[11, 146, 307, 451], [371, 104, 639, 450]]
Chk 12056 [[0, 127, 270, 639], [166, 318, 328, 611]]
Chk 12058 [[115, 30, 413, 394], [328, 145, 413, 304], [551, 133, 639, 357], [541, 76, 614, 184], [418, 227, 546, 401]]
Chk 12059 [[15, 180, 198, 358], [191, 172, 317, 323], [0, 196, 54, 296], [346, 117, 479, 360]]
Chk 12061 [[165, 120, 639, 426], [243, 115, 389, 421]]
Chk 12062 [[72, 61, 197, 420], [440, 87, 610, 391]]
Chk 12063 [[97, 181, 320, 354], [210, 194, 334, 313], [303, 189, 432, 305], [540, 203, 639, 303], [476, 102, 639, 418]]
Chk 12066 [[233, 95, 319, 332], [211, 89, 275, 284], [155, 65, 229, 281], [85, 87, 192, 325], [354, 117, 498, 331], [288, 106, 391, 332], [0, 63, 131, 328]]
Chk 12067 [[259, 63, 566, 424], [5, 81, 291, 419], [577, 318, 639, 425], [570, 272, 635, 363]]
Chk 12068 [[196, 36, 362, 421], [332, 29, 498, 276]]
Chk 12070 [[183, 51, 449, 419], [328, 52, 562, 402], [375, 0, 526, 203]]
Chk 12071 [[276, 21, 411, 225], [68, 159, 203, 303], [265, 158, 403, 273], [489, 10, 615, 194], [416, 200, 639, 341], [446, 108, 571, 229]]
Chk 12072 [[328, 55, 481, 334], [80, 49, 235, 350]]
Chk 12073 [[79, 95, 294, 422], [277, 111, 567, 427]]
Chk 12074 [[0, 49, 234, 374], [312, 76, 472, 370], [168, 57, 326, 368], [435, 101, 499, 203]]
Chk 12075 [[409, 15, 542, 416], [105, 88, 200, 298], [47, 115, 98, 166], [185, 81, 457, 475], [351, 74, 410, 193]]
Chk 12077 [[107, 41, 343, 447], [0, 240, 204, 521]]
Chk 12079 [[188, 375, 315, 558], [40, 378, 167, 639]]
Chk 12080 [[157, 64, 373, 472], [1, 53, 198, 238]]
Chk 12081 [[231, 185, 366, 374], [336, 65, 530, 458], [508, 139, 578, 262]]
Chk 12082 [[8, 149, 336, 604], [209, 24, 436, 335]]
Chk 12085 [[284, 85, 442, 420], [90, 125, 268, 420]]
Chk 12086 [[62, 14, 339, 419], [535, 6, 634, 273]]
Chk 12087 [[61, 1, 339, 346], [393, 0, 639, 437], [379, 63, 456, 215], [233, 18, 355, 302]]
Chk 12088 [[193, 134, 413, 420], [134, 61, 328, 421], [334, 2, 503, 420]]
Chk 12089 [[296, 164, 434, 586], [260, 272, 340, 611], [9, 323, 166, 627], [142, 271, 277, 639], [138, 313, 259, 620]]
Chk 12091 [[0, 15, 177, 421], [270, 103, 409, 419], [504, 108, 639, 426]]
Chk 12092 [[301, 8, 446, 215], [0, 59, 220, 397], [298, 110, 562, 370], [447, 1, 639, 265], [0, 289, 116, 423]]
Chk 12093 [[379, 0, 639, 427], [299, 199, 438, 421], [286, 168, 366, 343], [64, 187, 170, 391], [216, 192, 283, 382], [0, 186, 51, 332]]
Chk 12094 [[5, 2, 112, 317], [49, 0, 307, 311]]
Chk 12096 [[52, 59, 273, 365], [262, 40, 499, 370]]
Chk 12097 [[437, 24, 618, 408], [23, 43, 243, 422]]
Chk 12098 [[560, 174, 638, 432], [457, 308, 639, 530], [96, 190, 169, 272], [240, 205, 352, 493]]
Chk 12099 [[88, 107, 214, 356], [425, 137, 548, 358], [318, 165, 409, 235], [347, 232, 418, 334], [397, 235, 459, 328], [347, 3, 436, 80], [301, 12, 355, 75], [434, 74, 507, 140]]
Chk 12100 [[83, 28, 324, 474], [304, 24, 543, 473], [568, 118, 639, 424]]
Chk 12101 [[156, 167, 268, 493], [0, 132, 110, 498], [205, 99, 374, 493]]
Chk 12102 [[288, 49, 563, 473], [1, 0, 300, 474]]
Chk 12106 [[85, 259, 217, 472], [229, 323, 408, 475], [327, 213, 463, 459], [144, 0, 216, 97]]
Chk 12107 [[220, 0, 475, 421], [422, 140, 544, 390], [70, 218, 186, 386]]
Chk 12108 [[350, 79, 485, 478], [516, 0, 612, 243], [108, 114, 263, 472]]
Chk 12109 [[354, 123, 557, 527], [296, 0, 566, 520], [150, 392, 211, 530]]
Chk 12110 [[127, 51, 310, 460], [0, 4, 138, 472], [430, 0, 637, 251], [162, 0, 260, 66]]
Chk 12111 [[242, 118, 441, 342], [442, 61, 638, 325], [0, 100, 242, 479]]
Chk 12114 [[235, 53, 537, 438], [157, 87, 292, 465]]
Chk 12115 [[1, 35, 289, 474], [296, 0, 639, 410]]
Chk 12118 [[188, 17, 369, 421], [376, 0, 563, 427], [46, 97, 165, 364], [283, 0, 483, 328]]
Chk 12120 [[69, 137, 381, 631], [352, 290, 477, 632]]
Chk 12121 [[104, 175, 245, 410], [289, 251, 521, 426], [187, 90, 438, 426], [521, 90, 627, 223], [245, 136, 324, 189]]
Chk 12123 [[21, 214, 219, 540], [176, 173, 347, 412], [210, 157, 357, 307]]
Chk 12124 [[419, 109, 539, 381], [19, 172, 235, 393]]
Chk 12125 [[221, 24, 542, 421], [0, 148, 160, 376], [33, 90, 110, 174], [505, 141, 583, 273], [585, 152, 639, 270], [430, 119, 481, 185]]
Chk 12126 [[271, 5, 639, 499], [263, 73, 438, 357], [73, 176, 176, 343]]
Chk 12128 [[215, 109, 289, 357], [338, 133, 428, 360], [307, 117, 374, 360], [474, 132, 559, 356], [105, 93, 162, 284], [25, 102, 116, 399], [464, 142, 520, 315], [162, 127, 224, 352]]
Chk 12129 [[266, 262, 479, 602], [36, 207, 149, 499], [180, 1, 291, 56]]
Chk 12130 [[248, 140, 351, 360], [78, 151, 133, 311], [443, 2, 544, 427]]
Chk 12131 [[213, 59, 430, 311], [0, 69, 182, 308], [472, 94, 633, 301]]
Chk 12132 [[459, 143, 542, 431], [129, 141, 341, 435]]
Chk 12133 [[173, 161, 382, 566], [65, 112, 270, 538]]
Chk 12134 [[251, 17, 453, 386], [124, 44, 188, 243], [432, 36, 637, 364]]

Chk 12135 [[161, 95, 288, 294], [440, 94, 557, 286], [393, 81, 466, 214]]
Chk 12136 [[262, 146, 374, 419], [454, 158, 580, 426], [0, 4, 157, 426]]
Chk 12137 [[275, 93, 444, 331], [109, 117, 325, 381], [0, 3, 224, 385]]
Chk 12138 [[22, 198, 122, 368], [9, 165, 108, 348], [255, 43, 557, 431], [531, 178, 632, 449], [190, 21, 363, 403]]
Chk 12140 [[201, 13, 471, 341], [57, 104, 324, 413]]
Chk 12141 [[254, 136, 475, 578], [311, 85, 639, 632], [0, 164, 89, 350]]
Chk 12142 [[224, 0, 499, 367], [139, 94, 399, 368]]
Chk 12143 [[2, 0, 527, 395], [268, 99, 578, 426]]
Chk 12144 [[253, 92, 429, 426], [496, 0, 629, 209], [103, 0, 223, 87], [18, 275, 177, 426], [132, 154, 307, 420]]
Chk 12145 [[414, 193, 556, 426], [148, 157, 251, 288], [5, 175, 203, 419], [231, 140, 315, 261], [101, 127, 156, 179]]
Chk 12146 [[48, 213, 178, 483], [191, 0, 263, 87], [77, 0, 203, 86], [271, 0, 340, 90], [0, 0, 106, 87], [56, 79, 386, 614]]
Chk 12147 [[146, 6, 363, 361], [5, 3, 188, 287]]
Chk 12148 [[121, 196, 237, 574], [2, 175, 109, 582], [287, 146, 424, 574]]
Chk 12149 [[0, 45, 143, 419], [186, 143, 287, 329], [427, 87, 597, 426], [303, 238, 478, 426]]
Chk 12151 [[231, 96, 341, 349], [117, 63, 239, 381], [28, 81, 142, 323], [113, 108, 168, 323]]
Chk 12152 [[90, 76, 141, 204], [402, 259, 550, 452], [68, 160, 277, 463], [545, 235, 639, 471], [528, 11, 606, 105], [129, 94, 201, 175], [242, 112, 329, 196]]
Chk 12154 [[279, 184, 468, 334], [334, 116, 560, 325], [114, 1, 173, 197]]
Chk 12155 [[130, 110, 285, 367], [95, 92, 189, 296], [0, 197, 174, 342]]
Chk 12156 [[239, 141, 413, 426], [361, 108, 482, 420], [95, 143, 262, 425]]
Chk 12158 [[201, 79, 355, 297], [341, 118, 419, 266], [0, 108, 157, 327], [415, 349, 639, 471], [540, 298, 639, 359], [137, 203, 202, 271]]
Chk 12159 [[334, 100, 639, 474], [26, 30, 390, 472], [253, 102, 325, 187]]
Chk 12160 [[173, 68, 396, 487], [0, 23, 266, 520]]
Chk 12161 [[97, 152, 227, 470], [368, 198, 577, 472]]
Chk 12162 [[377, 66, 533, 438], [102, 33, 440, 531]]
Chk 12168 [[0, 121, 225, 478], [77, 76, 214, 320], [476, 50, 639, 373], [414, 68, 465, 165], [166, 73, 283, 263], [453, 83, 533, 219], [205, 53, 293, 179]]
Chk 12170 [[362, 37, 537, 379], [51, 167, 281, 295]]
Chk 12171 [[126, 60, 351, 632], [18, 208, 212, 639], [0, 311, 76, 615]]
Chk 12172 [[101, 110, 290, 545], [254, 0, 426, 528]]
Chk 12173 [[164, 169, 427, 639], [65, 133, 274, 632]]
Chk 12174 [[217, 41, 398, 634], [43, 86, 273, 616]]
Chk 12176 [[294, 84, 545, 421], [0, 68, 325, 422]]
Chk 12177 [[224, 155, 323, 438], [336, 161, 435, 437]]
Chk 12178 [[136, 62, 306, 357], [309, 66, 375, 226], [379, 178, 608, 355], [245, 107, 320, 307]]
Chk 12179 [[51, 38, 294, 437], [6, 335, 418, 604]]
Chk 12180 [[171, 221, 478, 629], [37, 242, 261, 471], [91, 251, 182, 364], [0, 251, 60, 371]]
Chk 12181 [[21, 92, 353, 489], [333, 20, 426, 384]]
Chk 12182 [[83, 181, 207, 356], [1, 0, 407, 474]]
Chk 12183 [[318, 15, 430, 341], [176, 30, 258, 352]]
Chk 12184 [[245, 53, 443, 338], [1, 91, 142, 479], [577, 111, 636, 275], [125, 176, 177, 231], [485, 119, 545, 273], [526, 109, 580, 274]]
Chk 12185 [[111, 64, 328, 473], [309, 44, 564, 473]]
Chk 12187 [[461, 119, 617, 381], [352, 110, 482, 380], [140, 118, 351, 418], [44, 112, 193, 379]]
Chk 12188 [[0, 73, 330, 472], [301, 363, 572, 479]]
Chk 12189 [[119, 116, 426, 544], [102, 155, 208, 317], [0, 229, 350, 639], [210, 178, 297, 474], [0, 164, 86, 250]]
Chk 12190 [[338, 0, 577, 229], [0, 0, 83, 312], [396, 141, 639, 347], [84, 1, 278, 263]]
Chk 12192 [[16, 195, 134, 405], [193, 16, 595, 596]]
Chk 12194 [[212, 51, 397, 600], [64, 54, 213, 622]]
Chk 12197 [[1, 71, 276, 372], [279, 91, 518, 346]]
Chk 12198 [[365, 286, 549, 469], [160, 260, 279, 468], [53, 257, 105, 341], [0, 259, 68, 383]]
Chk 12199 [[209, 229, 274, 307], [266, 208, 356, 314], [503, 154, 599, 279], [1, 103, 296, 473], [398, 176, 473, 285], [376, 7, 639, 472]]
Chk 12200 [[401, 70, 632, 426], [1, 17, 81, 415], [356, 38, 636, 256], [144, 47, 442, 389]]
Chk 12201 [[360, 169, 613, 505], [223, 255, 360, 511], [131, 173, 343, 505]]
Chk 12203 [[390, 130, 531, 406], [123, 95, 266, 479]]
Chk 12205 [[295, 40, 588, 349], [0, 25, 323, 421]]
Chk 12206 [[159, 177, 231, 338], [222, 47, 343, 274], [399, 176, 533, 328], [526, 197, 635, 384], [163, 152, 248, 233], [0, 177, 255, 426]]
Chk 12207 [[207, 104, 339, 272], [515, 91, 639, 470]]
Chk 12208 [[204, 31, 359, 391], [318, 1, 510, 423]]
Chk 12209 [[140, 224, 375, 582], [225, 168, 279, 229], [18, 129, 82, 255], [173, 143, 245, 247], [108, 150, 180, 258], [64, 194, 131, 257], [455, 198, 511, 418], [334, 113, 407, 401]]
Chk 12210 [[43, 95, 233, 587], [117, 84, 318, 584], [17, 272, 96, 505], [0, 281, 68, 520], [221, 120, 334, 573]]
Chk 12211 [[185, 166, 580, 370], [4, 6, 112, 285]]
Chk 12212 [[64, 135, 159, 426], [148, 159, 236, 402], [192, 119, 288, 318], [312, 57, 400, 289], [341, 131, 410, 330], [376, 113, 453, 418], [473, 119, 572, 328], [165, 89, 237, 215]]
Chk 12213 [[110, 161, 311, 403], [363, 257, 558, 426], [524, 220, 639, 427], [363, 1, 426, 77]]
Chk 12214 [[178, 221, 268, 546], [242, 225, 336, 545]]
Chk 12215 [[362, 42, 613, 424], [135, 135, 258, 254], [401, 83, 639, 270], [0, 77, 82, 236], [1, 62, 254, 420]]
Chk 12217 [[99, 0, 446, 480], [274, 27, 513, 472]]
Chk 12220 [[134, 197, 261, 396], [327, 78, 486, 368], [3, 129, 124, 384], [256, 73, 320, 129], [181, 80, 250, 133], [66, 65, 140, 137], [12, 48, 75, 144], [406, 0, 471, 98]]
Chk 12221 [[9, 41, 180, 499], [139, 13, 341, 493]]
Chk 12222 [[147, 178, 336, 408], [89, 185, 262, 414]]
Chk 12223 [[306, 28, 409, 283], [244, 104, 342, 270], [370, 66, 565, 363], [544, 23, 639, 398], [157, 69, 216, 239], [0, 90, 87, 226], [8, 60, 94, 169], [36, 55, 229, 415]]
Chk 12224 [[311, 104, 455, 323], [67, 155, 300, 419], [1, 170, 108, 420]]
Chk 12228 [[178, 56, 324, 275], [4, 36, 390, 412]]
Chk 12229 [[141, 34, 207, 209], [297, 44, 365, 236], [341, 28, 438, 294]]
Chk 12231 [[51, 34, 425, 369], [221, 149, 356, 339]]
Chk 12232 [[98, 232, 251, 549], [225, 149, 348, 455]]
Chk 12233 [[253, 121, 368, 277], [79, 35, 184, 319], [174, 245, 527, 423]]
Chk 12235 [[114, 0, 294, 381], [229, 6, 397, 464], [378, 4, 639, 255]]
Chk 12236 [[314, 278, 479, 579], [145, 237, 229, 403], [67, 268, 159, 519], [0, 303, 184, 631]]
Chk 12237 [[114, 204, 254, 510], [5, 127, 205, 505]]
Chk 12238 [[334, 141, 418, 384], [242, 214, 293, 342], [380, 147, 449, 406], [416, 121, 553, 478], [113, 224, 246, 394], [55, 93, 292, 465]]
Chk 12239 [[84, 43, 191, 416], [386, 40, 486, 410]]
Chk 12241 [[67, 166, 500, 639], [64, 1, 639, 632], [364, 0, 592, 141], [0, 0, 190, 629]]
Chk 12242 [[42, 41, 195, 327], [315, 62, 439, 290]]
Chk 12243 [[294, 98, 486, 409], [129, 30, 259, 380], [10, 120, 149, 425], [465, 115, 553, 407]]
Chk 12244 [[53, 59, 194, 417], [156, 55, 280, 237], [256, 57, 336, 182], [110, 2, 161, 62], [422, 44, 519, 189], [566, 54, 633, 144], [0, 192, 54, 265], [509, 58, 574, 132]]
Chk 12245 [[63, 223, 230, 638], [167, 230, 234, 513], [300, 381, 354, 605], [226, 249, 318, 601]]
Chk 12246 [[7, 54, 608, 370], [1, 19, 345, 234], [1, 19, 242, 97]]
Chk 12247 [[298, 85, 441, 402], [2, 157, 247, 473]]
Chk 12248 [[20, 120, 90, 327], [36, 89, 183, 286], [117, 83, 292, 407], [223, 159, 451, 474], [354, 83, 639, 477], [410, 125, 495, 308]]
Chk 12250 [[189, 108, 360, 327], [133, 54, 331, 326], [16, 254, 106, 331]]
Chk 12251 [[93, 159, 242, 479], [244, 149, 321, 381], [340, 189, 438, 363], [420, 144, 531, 475], [200, 161, 271, 403]]
Chk 12252 [[313, 52, 627, 417], [352, 72, 504, 379], [324, 12, 414, 277], [174, 79, 226, 268], [573, 95, 631, 224], [99, 89, 167, 246], [251, 60, 358, 312]]
Chk 12253 [[155, 0, 611, 605], [179, 20, 332, 372], [243, 71, 328, 235]]
Chk 12254 [[86, 126, 425, 631], [0, 0, 319, 633]]
Chk 12256 [[222, 104, 368, 274], [307, 130, 499, 331], [89, 75, 147, 170], [113, 64, 215, 191], [29, 83, 95, 149], [219, 1, 306, 164], [430, 0, 498, 170]]
Chk 12259 [[142, 66, 301, 377], [0, 18, 211, 639]]
Chk 12260 [[356, 87, 426, 630], [51, 158, 192, 421], [3, 280, 114, 560], [0, 187, 114, 312], [279, 172, 362, 268], [0, 81, 411, 639], [311, 196, 393, 270]]
Chk 12262 [[119, 49, 265, 327], [242, 9, 365, 299], [325, 24, 484, 325], [458, 47, 587, 331], [0, 8, 146, 271], [546, 66, 606, 253]]
Chk 12263 [[272, 105, 379, 404], [481, 132, 639, 420]]
Chk 12265 [[347, 34, 638, 410], [122, 71, 325, 288], [264, 156, 382, 316], [13, 55, 108, 211], [91, 48, 163, 182], [472, 11, 537, 102]]
Chk 12266 [[165, 38, 342, 328], [178, 106, 277, 324]]
Chk 12267 [[103, 120, 187, 223], [0, 73, 94, 310], [0, 198, 253, 533]]
Chk 12269 [[245, 27, 422, 278], [127, 7, 227, 252], [530, 211, 592, 377]]

Chk 12270 [[43, 80, 390, 471], [232, 5, 634, 474]]
Chk 12271 [[99, 81, 233, 223], [0, 51, 199, 308], [402, 86, 495, 236], [327, 104, 405, 213], [492, 61, 639, 309]]
Chk 12272 [[135, 47, 319, 366], [311, 36, 483, 371]]
Chk 12273 [[188, 74, 308, 318], [248, 3, 350, 294], [341, 0, 498, 260], [165, 211, 265, 327], [0, 273, 64, 326]]
Chk 12274 [[103, 170, 334, 406], [404, 84, 537, 384], [75, 108, 201, 394], [467, 17, 522, 86], [170, 125, 227, 220], [336, 163, 396, 216], [312, 120, 365, 202]]
Chk 12275 [[148, 129, 361, 434], [238, 221, 634, 423], [398, 132, 639, 367], [334, 92, 431, 285], [355, 206, 610, 434]]
Chk 12276 [[340, 1, 638, 421], [243, 105, 459, 415], [124, 164, 307, 406], [15, 206, 234, 396], [1, 200, 109, 381]]
Chk 12277 [[429, 166, 548, 394], [513, 114, 639, 422]]
Chk 12279 [[61, 170, 278, 620], [268, 270, 398, 497]]
Chk 12280 [[280, 52, 427, 282], [79, 164, 209, 354], [176, 179, 342, 346]]
Chk 12282 [[171, 81, 329, 628], [267, 135, 354, 576], [51, 323, 191, 632], [14, 267, 125, 497]]
Chk 12283 [[0, 0, 215, 255], [377, 21, 611, 248], [360, 111, 476, 237], [0, 269, 101, 419]]
Chk 12284 [[53, 21, 296, 418], [484, 237, 550, 361], [355, 140, 415, 387], [538, 232, 602, 356]]
Chk 12285 [[126, 101, 248, 401], [254, 92, 386, 400], [35, 62, 121, 308], [456, 81, 559, 399], [548, 251, 606, 324], [244, 191, 301, 326]]
Chk 12286 [[512, 408, 639, 479], [0, 182, 99, 377], [271, 143, 406, 234], [485, 369, 595, 472], [401, 161, 615, 401], [127, 159, 221, 274], [536, 329, 638, 434], [213, 147, 319, 259]]
Chk 12287 [[394, 136, 564, 379], [8, 130, 110, 275], [305, 118, 422, 231], [251, 130, 324, 224], [186, 127, 339, 299], [58, 180, 255, 419]]
Chk 12288 [[0, 38, 423, 493], [298, 144, 455, 451]]
Chk 12289 [[574, 61, 639, 324], [499, 35, 639, 357], [102, 63, 394, 359]]
Chk 12290 [[176, 23, 378, 390], [85, 47, 224, 373]]
Chk 12291 [[284, 23, 560, 637], [21, 37, 376, 632]]
Chk 12292 [[211, 44, 422, 427], [11, 1, 219, 427], [293, 41, 354, 116]]
Chk 12293 [[295, 73, 604, 467], [72, 67, 300, 479]]
Chk 12294 [[360, 0, 606, 257], [1, 0, 577, 473]]
Chk 12295 [[67, 169, 323, 602], [1, 246, 139, 462]]
Chk 12296 [[379, 237, 536, 471], [280, 254, 369, 368], [164, 297, 329, 475], [1, 258, 117, 478], [548, 235, 639, 479]]
Chk 12297 [[97, 297, 348, 550], [0, 146, 469, 569]]
Chk 12298 [[151, 196, 426, 639], [0, 88, 347, 631]]
Chk 12299 [[284, 147, 516, 532], [80, 101, 217, 427], [176, 125, 288, 451]]
Chk 12300 [[321, 0, 486, 397], [266, 128, 397, 421], [187, 137, 263, 327], [30, 202, 90, 292], [504, 107, 591, 291]]
Chk 12301 [[63, 38, 186, 154], [294, 70, 447, 215], [229, 43, 431, 311], [55, 42, 232, 293]]
Chk 12302 [[354, 107, 626, 472], [1, 180, 280, 465], [241, 134, 404, 456]]
Chk 12303 [[21, 114, 223, 624], [187, 38, 425, 639]]
Chk 12304 [[95, 1, 350, 274], [22, 247, 126, 343], [417, 4, 639, 270]]
Chk 12305 [[184, 111, 299, 452], [300, 103, 404, 360], [6, 114, 78, 345], [236, 98, 310, 388], [507, 63, 587, 174], [107, 104, 161, 353], [443, 86, 629, 295]]
Chk 12306 [[145, 69, 235, 406], [318, 104, 431, 402]]
Chk 12308 [[50, 24, 204, 470], [163, 103, 250, 479], [306, 51, 425, 479], [434, 14, 623, 473], [244, 44, 345, 395]]
Chk 12309 [[126, 40, 632, 426], [2, 10, 276, 426]]
Chk 12310 [[383, 122, 605, 291], [223, 57, 437, 298], [4, 149, 88, 299], [318, 45, 381, 124], [184, 112, 263, 217], [540, 173, 627, 350], [466, 22, 557, 119], [427, 45, 481, 168]]
Chk 12311 [[274, 138, 495, 479], [154, 181, 211, 476], [265, 252, 316, 377], [122, 131, 286, 472], [13, 161, 95, 436]]
Chk 12312 [[341, 128, 438, 436], [229, 73, 377, 453], [74, 108, 225, 461], [528, 134, 639, 425]]
Chk 12313 [[291, 85, 639, 471], [225, 162, 388, 471], [29, 177, 265, 479]]
Chk 12314 [[368, 115, 503, 438], [20, 211, 158, 423], [220, 17, 329, 241]]
Chk 12315 [[333, 129, 461, 413], [231, 81, 343, 410], [0, 59, 71, 425]]
Chk 12316 [[256, 58, 614, 630], [294, 49, 460, 552]]
Chk 12317 [[148, 123, 393, 493], [362, 106, 611, 496]]
Chk 12318 [[121, 133, 270, 425], [352, 50, 548, 425], [372, 146, 428, 337], [515, 133, 567, 297], [525, 230, 639, 419], [245, 242, 309, 392]]
Chk 12319 [[0, 174, 293, 592], [34, 93, 232, 406], [148, 102, 278, 355], [203, 76, 262, 210], [244, 71, 296, 181]]
Chk 12320 [[179, 293, 357, 525], [20, 164, 314, 584], [364, 456, 424, 638], [300, 328, 424, 639]]
Chk 12321 [[358, 94, 537, 473], [194, 305, 348, 471], [316, 106, 416, 400], [252, 154, 325, 323], [145, 142, 265, 339], [526, 166, 639, 471], [468, 133, 565, 267], [196, 111, 251, 194]]
Chk 12322 [[382, 149, 490, 425], [471, 108, 584, 426], [236, 134, 368, 421]]
Chk 12324 [[227, 90, 510, 627], [177, 160, 396, 565]]
Chk 12326 [[83, 138, 288, 479], [153, 115, 211, 179], [391, 117, 558, 472], [558, 156, 619, 258], [355, 94, 447, 472], [260, 120, 363, 471]]
Chk 12327 [[32, 4, 372, 427], [319, 96, 639, 427], [555, 171, 637, 312]]
Chk 12330 [[126, 120, 295, 473], [301, 167, 421, 479]]
Chk 12332 [[142, 170, 211, 280], [90, 159, 317, 472], [17, 126, 152, 414], [421, 175, 513, 290], [290, 132, 549, 473], [516, 110, 639, 476], [505, 210, 575, 343]]
Chk 12333 [[351, 37, 610, 424], [197, 41, 403, 420], [1, 1, 285, 419]]
Chk 12334 [[78, 139, 273, 470], [370, 143, 611, 421]]
Chk 12335 [[14, 38, 280, 271], [368, 19, 484, 272], [274, 222, 326, 275]]
Chk 12336 [[346, 24, 479, 390], [94, 1, 329, 570], [0, 0, 124, 491]]
Chk 12337 [[165, 6, 602, 328], [181, 87, 317, 275]]
Chk 12338 [[178, 93, 314, 447], [244, 113, 386, 609], [155, 134, 216, 215]]
Chk 12339 [[32, 190, 142, 442], [484, 178, 636, 479], [177, 185, 255, 466], [97, 211, 153, 370]]
Chk 12341 [[115, 55, 350, 292], [333, 63, 587, 373]]
Chk 12342 [[468, 176, 639, 479], [475, 283, 638, 471], [200, 120, 375, 445]]
Chk 12343 [[172, 307, 376, 631], [2, 314, 189, 639]]
Chk 12344 [[5, 5, 477, 523], [220, 88, 293, 254], [0, 1, 117, 459]]
Chk 12345 [[190, 0, 396, 359], [283, 36, 639, 479]]
Chk 12346 [[19, 151, 260, 425], [263, 176, 361, 375], [375, 103, 639, 389]]
Chk 12348 [[302, 140, 467, 400], [538, 245, 639, 413]]
Chk 12349 [[161, 224, 349, 601], [343, 112, 535, 297]]
Chk 12350 [[99, 319, 244, 632], [212, 14, 427, 635]]
Chk 12352 [[46, 171, 186, 348], [310, 212, 463, 452], [197, 139, 297, 290], [125, 242, 387, 522]]
Chk 12353 [[304, 45, 510, 356], [68, 10, 317, 376], [517, 178, 639, 348]]
Chk 12354 [[118, 25, 346, 315], [349, 82, 575, 472], [302, 98, 374, 175]]
Chk 12356 [[185, 176, 304, 545], [18, 149, 207, 545], [429, 158, 605, 545]]
Chk 12357 [[271, 107, 402, 437], [14, 120, 317, 474], [246, 103, 339, 288]]
Chk 12358 [[100, 143, 266, 370], [48, 123, 132, 374]]
Chk 12359 [[0, 225, 195, 369], [348, 221, 499, 374]]
Chk 12360 [[401, 147, 521, 307], [145, 145, 312, 336]]
Chk 12361 [[2, 125, 121, 473], [107, 29, 163, 109], [61, 41, 117, 110], [200, 46, 264, 121], [238, 143, 372, 418]]
Chk 12362 [[307, 33, 479, 453], [41, 5, 373, 426], [297, 0, 479, 420]]
Chk 12364 [[123, 96, 333, 346], [334, 98, 475, 370]]
Chk 12366 [[81, 63, 309, 631], [257, 201, 477, 631], [0, 124, 155, 626]]
Chk 12367 [[292, 133, 447, 331], [169, 79, 277, 334], [88, 68, 186, 331]]
Chk 12369 [[376, 36, 496, 422], [69, 89, 239, 419]]
Chk 12372 [[306, 143, 483, 288], [190, 44, 347, 204]]
Chk 12373 [[92, 153, 354, 477], [0, 102, 225, 471], [423, 104, 611, 339], [40, 34, 191, 163]]
Chk 12375 [[139, 17, 305, 473], [370, 30, 535, 469]]
Chk 12376 [[281, 93, 379, 204], [420, 181, 639, 421], [64, 66, 201, 419]]
Chk 12378 [[169, 138, 288, 473], [501, 203, 639, 479], [1, 155, 130, 473], [286, 154, 444, 470]]
Chk 12380 [[166, 252, 303, 426], [44, 239, 191, 342], [371, 256, 566, 426], [480, 232, 535, 306], [535, 219, 627, 316], [368, 231, 432, 317], [571, 352, 639, 426]]
Chk 12382 [[107, 164, 234, 354], [258, 167, 364, 422], [112, 145, 174, 267], [529, 118, 589, 285], [562, 144, 635, 322], [215, 208, 437, 277]]
Chk 12383 [[242, 220, 411, 631], [189, 71, 297, 558]]
Chk 12384 [[346, 28, 604, 477], [90, 85, 379, 596]]
Chk 12385 [[446, 27, 530, 323], [385, 56, 462, 312]]
Chk 12386 [[117, 146, 279, 389], [433, 125, 628, 384]]
Chk 12387 [[117, 14, 519, 632], [11, 237, 398, 639]]
Chk 12389 [[260, 137, 406, 347], [37, 142, 211, 386], [415, 127, 592, 320]]
Chk 12390 [[451, 39, 601, 264], [105, 189, 313, 349], [293, 0, 415, 225], [37, 17, 175, 315], [179, 24, 359, 235]]
Chk 12391 [[146, 11, 409, 328], [93, 38, 343, 329], [317, 14, 390, 268], [11, 19, 89, 247], [93, 33, 172, 233], [357, 0, 460, 268], [420, 105, 499, 279], [55, 19, 107, 241]]

Chk 12392 [[116, 105, 199, 289], [289, 61, 426, 323], [11, 283, 305, 533], [13, 63, 108, 314], [0, 203, 84, 535], [364, 548, 426, 621]]
Chk 12393 [[7, 0, 237, 422], [498, 210, 635, 480], [297, 90, 573, 375], [281, 93, 378, 205], [1, 337, 102, 415], [0, 416, 244, 479]]
Chk 12394 [[294, 172, 383, 465], [382, 149, 477, 468], [7, 177, 88, 467]]
Chk 12396 [[290, 73, 529, 479], [126, 142, 613, 473]]
Chk 12398 [[274, 354, 366, 616], [152, 355, 225, 611], [217, 337, 285, 614]]
Chk 12400 [[307, 55, 397, 352], [366, 25, 501, 360]]
Chk 12402 [[88, 35, 402, 354], [7, 349, 329, 639]]
Chk 12403 [[308, 30, 606, 420], [142, 50, 352, 420]]
Chk 12404 [[0, 152, 204, 474], [146, 240, 338, 464], [271, 192, 501, 465], [435, 85, 639, 466]]
Chk 12405 [[220, 71, 626, 477], [138, 121, 430, 431]]
Chk 12406 [[211, 2, 420, 630], [0, 43, 249, 639]]
Chk 12408 [[217, 96, 327, 426], [324, 112, 430, 300], [371, 134, 496, 425], [66, 98, 288, 421]]
Chk 12409 [[255, 50, 579, 433], [296, 103, 400, 386], [228, 34, 329, 396], [537, 123, 618, 276], [363, 35, 495, 335]]
Chk 12410 [[176, 90, 513, 470], [198, 144, 342, 479], [495, 315, 613, 479]]
Chk 12411 [[167, 0, 297, 238], [253, 7, 464, 288], [0, 192, 284, 308], [306, 104, 446, 301]]
Chk 12412 [[1, 68, 310, 309], [394, 134, 490, 225], [154, 99, 390, 361], [318, 199, 591, 440]]
Chk 12414 [[189, 44, 448, 330], [0, 49, 147, 344]]
Chk 12416 [[39, 48, 303, 426], [0, 32, 51, 417], [283, 48, 440, 378], [479, 108, 639, 421]]
Chk 12417 [[0, 0, 463, 349], [259, 2, 516, 183], [26, 37, 80, 128], [547, 0, 639, 271], [515, 0, 566, 102]]
Chk 12418 [[37, 98, 104, 297], [117, 244, 278, 479], [325, 108, 489, 439]]
Chk 12419 [[153, 171, 295, 501], [48, 320, 274, 535], [275, 204, 347, 367]]
Chk 12421 [[209, 81, 429, 327], [87, 83, 293, 325]]
Chk 12422 [[416, 67, 639, 316], [359, 198, 435, 317], [221, 86, 486, 318]]
Chk 12423 [[45, 8, 480, 413], [228, 155, 443, 332]]
Chk 12424 [[342, 99, 638, 327], [0, 81, 204, 287]]
Chk 12426 [[64, 48, 449, 384], [314, 1, 568, 314], [467, 1, 639, 260], [551, 242, 639, 421]]
Chk 12427 [[122, 101, 425, 330], [225, 93, 522, 298]]
Chk 12428 [[82, 52, 297, 487], [285, 257, 461, 639]]
Chk 12430 [[14, 107, 183, 368], [485, 99, 636, 387], [173, 92, 327, 293]]
Chk 12431 [[32, 252, 116, 407], [93, 234, 182, 375], [120, 267, 216, 393], [177, 123, 287, 435], [407, 221, 495, 427], [306, 31, 605, 472], [579, 299, 639, 377], [328, 197, 466, 412]]
Chk 12432 [[241, 74, 377, 382], [307, 88, 468, 385]]
Chk 12433 [[148, 136, 359, 348], [292, 85, 429, 386]]
Chk 12436 [[239, 119, 375, 475], [183, 139, 264, 451]]
Chk 12437 [[208, 191, 344, 426], [276, 0, 519, 427]]
Chk 12438 [[98, 0, 382, 409], [0, 2, 453, 433]]
Chk 12440 [[201, 133, 311, 531], [104, 166, 215, 536]]
Chk 12441 [[245, 23, 639, 472], [1, 86, 307, 457]]
Chk 12442 [[103, 99, 289, 420], [379, 117, 568, 421]]
Chk 12444 [[214, 78, 412, 279], [508, 67, 639, 420], [0, 52, 246, 342]]
Chk 12445 [[50, 32, 449, 425], [196, 0, 307, 312], [495, 121, 591, 237], [583, 125, 639, 299], [289, 6, 396, 296], [0, 0, 55, 480]]
Chk 12447 [[418, 44, 639, 424], [0, 54, 211, 421]]
Chk 12448 [[356, 178, 456, 310], [426, 168, 547, 311], [255, 160, 320, 240], [120, 199, 315, 426], [142, 165, 243, 300], [114, 160, 187, 274], [488, 215, 639, 410], [349, 164, 432, 260]]
Chk 12450 [[533, 75, 596, 237], [176, 82, 250, 364], [226, 65, 300, 345], [350, 110, 466, 402], [24, 182, 79, 317]]
Chk 12451 [[350, 172, 476, 416], [199, 185, 319, 426]]
Chk 12452 [[0, 203, 126, 345], [80, 201, 216, 352], [190, 169, 367, 477], [370, 110, 622, 470]]
Chk 12454 [[366, 136, 506, 401], [79, 276, 354, 479], [412, 204, 639, 458]]
Chk 12455 [[242, 51, 639, 421], [1, 0, 247, 304], [26, 283, 223, 426]]
Chk 12456 [[448, 159, 611, 600], [115, 142, 300, 370], [1, 144, 144, 604], [273, 126, 417, 318], [235, 31, 316, 192], [448, 32, 571, 218], [367, 119, 559, 376], [130, 120, 202, 231]]
Chk 12458 [[262, 81, 366, 274], [3, 224, 140, 479], [289, 184, 559, 467], [465, 22, 576, 340]]
Chk 12459 [[0, 0, 239, 471], [377, 86, 538, 474]]
Chk 12462 [[410, 172, 583, 479], [172, 176, 245, 295], [342, 171, 441, 333], [0, 157, 362, 478]]
Chk 12463 [[133, 30, 466, 474], [300, 150, 556, 473], [520, 0, 639, 143]]
Chk 12464 [[123, 96, 377, 381], [90, 79, 231, 357]]
Chk 12465 [[367, 97, 523, 418], [243, 108, 356, 322]]
Chk 12466 [[192, 45, 351, 348], [61, 88, 209, 589]]
Chk 12467 [[458, 74, 621, 259], [112, 74, 255, 342], [0, 96, 157, 428]]
Chk 12468 [[331, 162, 440, 375], [240, 66, 351, 298], [432, 105, 590, 354], [551, 133, 605, 194], [154, 90, 299, 361], [316, 28, 369, 96]]
Chk 12470 [[95, 3, 352, 345], [1, 48, 135, 342]]
Chk 12471 [[49, 96, 254, 423], [259, 39, 450, 356]]
Chk 12473 [[66, 3, 639, 420], [125, 66, 364, 416]]
Chk 12474 [[361, 44, 597, 425], [154, 124, 284, 425]]
Chk 12475 [[270, 134, 382, 397], [52, 97, 302, 380], [415, 119, 561, 301]]
Chk 12476 [[288, 104, 534, 427], [393, 101, 540, 424]]
Chk 12478 [[2, 74, 321, 418], [199, 125, 392, 352]]
Chk 12479 [[22, 79, 263, 556], [115, 157, 266, 560]]
Chk 12480 [[359, 151, 636, 341], [123, 18, 416, 337], [314, 134, 366, 266], [67, 135, 124, 289], [14, 139, 74, 267]]
Chk 12481 [[345, 103, 497, 472], [126, 188, 272, 467]]
Chk 12482 [[300, 86, 419, 319], [232, 100, 316, 314]]
Chk 12483 [[75, 281, 224, 522], [215, 31, 435, 419]]
Chk 12484 [[145, 204, 283, 419], [120, 339, 253, 535]]
Chk 12485 [[160, 270, 314, 638], [12, 229, 309, 639]]
Chk 12487 [[155, 132, 322, 421], [452, 197, 560, 417]]
Chk 12488 [[265, 126, 392, 266], [236, 2, 344, 133], [3, 143, 119, 396], [54, 276, 207, 420], [350, 310, 573, 425], [0, 128, 63, 273], [0, 29, 65, 153]]
Chk 12489 [[312, 27, 632, 635], [0, 404, 249, 639]]
Chk 12490 [[325, 24, 568, 479], [167, 182, 329, 479], [304, 104, 404, 263], [293, 176, 404, 474], [211, 163, 272, 263], [0, 184, 105, 479]]
Chk 12493 [[205, 69, 372, 479], [350, 37, 497, 472], [0, 211, 106, 369]]
Chk 12495 [[113, 30, 369, 382], [359, 6, 569, 316], [1, 36, 101, 407], [552, 45, 639, 272], [41, 59, 164, 402]]
Chk 12496 [[311, 85, 394, 333], [175, 84, 277, 342], [11, 9, 209, 374]]
Chk 12498 [[292, 70, 503, 393], [54, 141, 281, 400], [1, 102, 116, 401]]
Chk 12499 [[214, 312, 360, 470], [84, 309, 217, 502], [315, 315, 398, 448]]
Chk 12500 [[368, 114, 486, 474], [63, 300, 209, 472], [234, 97, 394, 475], [88, 96, 278, 470], [481, 183, 639, 472]]
Chk 12501 [[148, 67, 372, 403], [338, 114, 511, 473]]
Chk 12502 [[282, 117, 401, 431], [144, 147, 239, 430]]
Chk 12503 [[100, 144, 296, 479], [336, 133, 529, 367], [491, 102, 637, 473], [321, 128, 393, 317], [0, 167, 136, 479]]
Chk 12504 [[12, 209, 139, 499], [58, 273, 242, 492], [185, 345, 304, 499], [153, 105, 324, 266]]
Chk 12505 [[199, 62, 412, 283], [526, 202, 639, 426], [0, 42, 158, 319], [1, 207, 83, 420]]
Chk 12507 [[222, 103, 456, 466], [123, 151, 255, 357]]
Chk 12510 [[301, 64, 629, 479], [39, 42, 394, 468]]
Chk 12511 [[176, 186, 275, 417], [337, 67, 471, 379]]
Chk 12512 [[5, 90, 283, 629], [223, 247, 451, 639]]
Chk 12513 [[107, 83, 358, 424], [550, 92, 601, 156], [385, 40, 479, 119], [294, 131, 471, 419]]
Chk 12514 [[136, 29, 362, 425], [1, 114, 113, 420]]
Chk 12515 [[318, 94, 602, 311], [76, 113, 497, 420]]
Chk 12517 [[146, 184, 478, 632], [0, 301, 188, 639]]
Chk 12518 [[65, 109, 304, 420], [314, 108, 483, 426]]
Chk 12519 [[206, 110, 348, 411], [517, 144, 639, 383], [332, 37, 552, 346], [182, 7, 370, 158], [47, 202, 316, 402]]
Chk 12520 [[300, 3, 630, 502], [240, 73, 631, 506]]
Chk 12522 [[25, 136, 207, 446], [278, 150, 436, 417], [366, 169, 639, 477]]
Chk 12525 [[288, 183, 408, 393], [360, 153, 435, 380], [169, 204, 433, 416], [409, 109, 514, 370]]
Chk 12526 [[70, 157, 311, 485], [260, 121, 391, 339], [203, 91, 308, 326], [31, 196, 118, 339], [302, 138, 526, 361], [510, 203, 591, 374]]
Chk 12527 [[166, 235, 430, 485], [1, 126, 364, 545]]
Chk 12528 [[227, 70, 366, 330], [191, 92, 308, 302]]
Chk 12529 [[162, 24, 360, 565], [51, 48, 176, 485]]
Chk 12531 [[436, 79, 547, 472], [311, 117, 431, 473], [195, 122, 318, 461], [38, 101, 182, 302], [1, 186, 209, 471]]
Chk 12532 [[99, 45, 203, 368], [190, 2, 314, 391], [373, 36, 478, 381], [461, 48, 554, 354], [290, 36, 395, 376]]
Chk 12533 [[0, 76, 267, 368], [234, 60, 497, 374]]
Chk 12534 [[0, 58, 256, 361], [2, 364, 210, 452], [214, 73, 300, 180]]
Chk 12535 [[199, 24, 355, 372], [105, 108, 217, 252], [120, 240, 424, 630]]
Chk 12537 [[418, 147, 534, 450], [60, 145, 201, 471]]
Chk 12538 [[316, 95, 453, 424], [273, 135, 332, 365], [152, 65, 282, 419]]
Chk 12540 [[8, 47, 166, 372], [264, 68, 498, 393]]

Chk 12541 [[1, 39, 137, 474], [93, 24, 205, 411], [509, 70, 639, 474], [452, 267, 534, 471], [345, 107, 451, 472]]
Chk 12542 [[33, 132, 387, 612], [284, 139, 622, 611]]
Chk 12543 [[259, 197, 450, 366], [313, 66, 395, 211], [241, 87, 317, 205], [73, 128, 259, 366], [383, 66, 483, 365]]
Chk 12544 [[42, 175, 227, 491], [213, 53, 332, 442]]
Chk 12545 [[223, 104, 332, 512], [452, 103, 631, 514], [0, 126, 188, 514], [157, 339, 222, 509]]
Chk 12546 [[65, 46, 285, 470], [483, 131, 637, 474], [266, 39, 576, 471]]
Chk 12548 [[155, 30, 321, 417], [351, 48, 453, 421]]
Chk 12549 [[270, 67, 443, 350], [396, 15, 595, 350], [235, 110, 326, 351], [177, 120, 251, 331], [1, 9, 134, 350], [81, 84, 152, 264], [558, 130, 638, 344], [111, 116, 165, 322]]
Chk 12551 [[0, 0, 148, 632], [238, 29, 479, 620], [80, 57, 371, 462]]
Chk 12552 [[143, 62, 343, 356], [191, 183, 496, 393], [305, 105, 378, 160]]
Chk 12554 [[69, 0, 300, 639], [295, 240, 455, 594]]
Chk 12555 [[226, 93, 415, 306], [107, 76, 282, 255], [382, 155, 590, 419]]
Chk 12556 [[419, 1, 598, 407], [109, 181, 286, 347]]
Chk 12557 [[142, 128, 381, 327], [0, 37, 104, 292], [312, 0, 456, 252], [17, 0, 102, 61]]
Chk 12558 [[49, 165, 222, 426], [413, 202, 575, 426]]
Chk 12559 [[305, 0, 479, 372], [4, 22, 212, 279]]
Chk 12560 [[10, 181, 224, 639], [409, 205, 532, 639], [175, 56, 347, 260], [343, 460, 469, 638]]
Chk 12561 [[191, 195, 422, 470], [29, 16, 195, 340], [120, 151, 257, 342], [572, 240, 639, 463], [381, 68, 565, 345]]
Chk 12562 [[164, 14, 524, 426], [0, 151, 168, 425], [345, 80, 541, 413]]
Chk 12563 [[84, 37, 351, 440], [424, 131, 637, 474]]
Chk 12564 [[288, 78, 492, 348], [72, 43, 333, 389]]
Chk 12565 [[84, 59, 295, 421], [376, 122, 503, 480]]
Chk 12566 [[2, 12, 496, 516], [347, 1, 639, 535]]
Chk 12567 [[59, 110, 231, 426], [0, 219, 97, 327], [413, 31, 639, 394], [194, 152, 288, 409], [339, 151, 460, 418]]
Chk 12570 [[336, 119, 534, 472], [305, 86, 411, 326], [112, 165, 401, 474], [0, 291, 85, 479], [530, 161, 639, 476]]
Chk 12572 [[129, 64, 224, 253], [11, 137, 331, 306], [419, 145, 518, 313], [482, 150, 639, 350], [316, 147, 461, 333], [550, 135, 639, 284], [452, 89, 515, 181]]
Chk 12574 [[55, 65, 173, 474], [189, 105, 266, 338], [132, 268, 265, 479]]
Chk 12575 [[45, 195, 242, 353], [367, 144, 624, 353], [171, 114, 399, 354]]
Chk 12576 [[105, 166, 479, 628], [267, 128, 363, 279], [0, 119, 94, 572]]
Chk 12577 [[357, 233, 439, 410], [585, 329, 639, 473], [148, 360, 316, 473], [307, 415, 424, 479], [266, 210, 328, 297], [453, 323, 591, 472], [457, 218, 512, 301]]
Chk 12578 [[215, 98, 406, 492], [12, 11, 104, 327]]
Chk 12579 [[293, 84, 417, 479], [109, 18, 313, 479]]
Chk 12580 [[98, 85, 527, 426], [19, 11, 214, 364], [172, 0, 279, 57]]
Chk 12581 [[37, 83, 245, 478], [465, 155, 576, 396]]
Chk 12582 [[0, 281, 264, 473], [362, 159, 535, 344], [318, 186, 402, 304], [270, 163, 347, 276], [110, 168, 236, 290], [0, 186, 113, 303], [331, 294, 600, 471]]
Chk 12583 [[100, 233, 192, 385], [0, 232, 101, 397], [2, 291, 121, 529], [364, 165, 418, 228], [0, 206, 55, 264], [369, 244, 468, 554], [341, 219, 430, 381], [189, 214, 317, 337]]
Chk 12584 [[348, 35, 476, 421], [283, 177, 383, 391], [113, 89, 240, 434], [30, 83, 147, 426]]
Chk 12585 [[245, 108, 385, 418], [492, 88, 616, 400], [1, 116, 97, 413], [39, 73, 107, 222], [1, 92, 65, 239]]
Chk 12586 [[572, 117, 639, 337], [470, 110, 594, 365], [174, 172, 249, 330], [280, 83, 360, 371], [380, 124, 462, 305], [27, 110, 136, 377]]
Chk 12587 [[359, 124, 547, 435], [102, 110, 214, 454], [224, 192, 282, 246], [294, 178, 365, 240], [259, 134, 315, 193], [224, 12, 276, 133]]
Chk 12588 [[25, 9, 252, 328], [345, 127, 531, 334], [490, 69, 639, 347]]
Chk 12589 [[19, 228, 249, 639], [351, 160, 550, 626], [274, 367, 566, 639]]
Chk 12590 [[243, 59, 499, 286], [0, 0, 261, 283]]
Chk 12591 [[315, 85, 426, 425], [208, 165, 307, 370], [546, 79, 639, 419]]
Chk 12592 [[390, 92, 637, 371], [397, 106, 519, 217], [278, 119, 356, 221], [181, 95, 273, 284], [201, 68, 290, 184], [0, 114, 234, 420]]
Chk 12595 [[11, 218, 150, 497], [104, 354, 234, 547], [193, 342, 482, 610], [333, 181, 481, 445]]
Chk 12596 [[430, 136, 536, 264], [321, 161, 432, 390], [17, 156, 238, 468]]
Chk 12597 [[377, 77, 639, 423], [87, 46, 424, 415]]
Chk 12598 [[199, 312, 320, 564], [292, 294, 407, 553], [55, 223, 151, 517]]
Chk 12599 [[73, 101, 327, 451], [212, 101, 325, 458], [314, 92, 454, 448], [416, 14, 569, 383], [402, 187, 552, 458]]
Chk 12600 [[2, 128, 342, 474], [292, 101, 639, 479]]
Chk 12601 [[445, 61, 622, 479], [158, 244, 418, 473], [89, 175, 268, 356], [401, 198, 498, 434], [0, 97, 111, 456], [296, 175, 399, 257]]
Chk 12603 [[172, 127, 339, 400], [117, 64, 229, 385]]
Chk 12606 [[307, 72, 417, 303], [131, 57, 365, 345]]
Chk 12608 [[103, 57, 399, 399], [3, 0, 299, 197], [408, 82, 639, 405]]
Chk 12609 [[210, 139, 291, 430], [326, 121, 422, 381]]
Chk 12610 [[10, 34, 286, 420], [473, 187, 553, 399], [298, 145, 445, 404]]
Chk 12611 [[317, 246, 432, 383], [213, 257, 335, 400], [87, 231, 282, 479], [412, 279, 561, 470]]
Chk 12613 [[70, 112, 299, 404], [324, 46, 639, 527]]
Chk 12614 [[199, 105, 294, 378], [344, 85, 435, 370], [279, 107, 356, 378]]
Chk 12616 [[0, 288, 137, 479], [227, 167, 433, 454]]
Chk 12619 [[239, 81, 431, 491], [434, 39, 639, 493], [0, 19, 210, 492]]
Chk 12621 [[198, 265, 300, 478], [95, 301, 185, 477], [457, 255, 515, 372], [289, 308, 346, 372], [397, 268, 456, 367], [0, 318, 108, 478], [59, 287, 125, 361], [147, 284, 201, 429]]
Chk 12622 [[419, 120, 639, 474], [437, 129, 570, 345], [257, 81, 308, 169], [0, 105, 244, 408], [188, 101, 240, 212], [371, 104, 458, 277], [133, 118, 248, 282]]
Chk 12623 [[283, 76, 386, 291], [562, 44, 639, 336], [159, 92, 388, 348], [548, 25, 639, 325]]
Chk 12624 [[211, 276, 310, 530], [137, 279, 212, 578], [87, 294, 147, 431], [392, 344, 479, 639], [420, 405, 477, 631]]
Chk 12625 [[0, 115, 272, 413], [193, 120, 311, 412], [342, 118, 463, 320], [449, 121, 530, 258], [0, 123, 75, 313], [579, 98, 639, 417]]
Chk 12626 [[187, 105, 304, 290], [72, 245, 280, 479], [332, 205, 459, 458], [409, 198, 466, 312], [421, 91, 584, 473]]
Chk 12627 [[141, 20, 430, 223], [501, 0, 554, 54], [347, 30, 616, 201]]
Chk 12629 [[0, 63, 471, 424], [404, 93, 639, 408]]
Chk 12630 [[289, 110, 579, 475], [117, 300, 292, 480]]
Chk 12631 [[505, 153, 639, 418], [325, 101, 495, 418], [193, 165, 329, 418], [3, 137, 195, 417]]
Chk 12632 [[123, 95, 384, 417], [327, 13, 639, 419], [136, 236, 282, 419]]
Chk 12633 [[2, 114, 347, 575], [257, 274, 638, 611], [38, 5, 620, 380]]
Chk 12634 [[107, 131, 255, 382], [258, 147, 365, 253], [435, 84, 535, 386], [169, 83, 244, 158], [118, 85, 180, 231]]
Chk 12635 [[263, 57, 335, 379], [340, 108, 464, 408], [365, 62, 454, 169], [229, 75, 287, 271]]
Chk 12637 [[415, 32, 620, 505], [5, 173, 102, 495], [220, 268, 317, 477], [542, 215, 634, 496], [160, 118, 487, 535], [441, 268, 527, 495]]
Chk 12638 [[92, 24, 390, 471], [241, 45, 464, 467], [406, 312, 503, 435]]
Chk 12639 [[293, 153, 441, 580], [174, 340, 349, 565], [18, 217, 162, 599], [46, 21, 207, 258], [96, 79, 235, 579], [367, 437, 434, 511]]
Chk 12640 [[207, 113, 317, 423], [385, 81, 528, 472], [491, 212, 594, 379], [89, 234, 217, 401], [356, 246, 499, 395], [149, 208, 253, 374]]
Chk 12643 [[153, 186, 325, 426], [43, 3, 394, 472]]
Chk 12645 [[343, 113, 473, 401], [143, 106, 270, 394], [56, 132, 137, 323], [331, 124, 386, 284]]
Chk 12646 [[207, 161, 280, 368], [0, 0, 395, 569], [4, 208, 405, 499], [340, 285, 425, 472]]
Chk 12647 [[49, 73, 422, 474], [312, 224, 456, 473]]
Chk 12648 [[0, 36, 303, 424], [322, 78, 585, 420]]
Chk 12649 [[277, 133, 437, 446], [554, 117, 639, 445], [5, 179, 115, 498], [357, 165, 443, 287], [443, 187, 577, 450]]
Chk 12650 [[211, 48, 335, 363], [129, 64, 215, 364], [2, 250, 130, 374], [408, 73, 478, 185]]
Chk 12651 [[332, 113, 478, 632], [0, 59, 121, 639], [99, 145, 234, 416], [411, 54, 479, 219], [36, 144, 99, 225], [54, 186, 115, 267], [150, 90, 253, 330]]
Chk 12652 [[62, 204, 244, 503], [184, 196, 433, 538]]
Chk 12654 [[346, 0, 499, 170], [0, 0, 158, 139]]
Chk 12655 [[384, 92, 485, 381], [141, 86, 256, 374]]
Chk 12656 [[21, 94, 191, 417], [179, 186, 328, 551], [82, 271, 149, 415], [159, 267, 214, 404]]

Chk 12659 [[46, 203, 172, 391], [249, 170, 369, 268], [357, 173, 419, 277], [148, 199, 234, 334], [220, 190, 295, 309], [390, 170, 531, 420]]
Chk 12661 [[267, 1, 530, 422], [104, 16, 491, 258], [98, 217, 313, 416], [481, 19, 623, 325], [146, 2, 231, 325], [561, 17, 634, 307], [477, 9, 538, 182]]
Chk 12665 [[196, 200, 366, 494], [1, 131, 226, 493]]
Chk 12666 [[365, 55, 443, 129], [229, 146, 378, 354], [384, 36, 544, 313], [561, 28, 629, 142], [21, 35, 157, 353], [292, 56, 360, 118], [242, 65, 312, 148]]
Chk 12669 [[106, 166, 409, 421], [303, 82, 570, 419]]
Chk 12670 [[167, 150, 562, 473], [81, 100, 335, 474]]
Chk 12671 [[159, 199, 262, 542], [257, 212, 358, 446]]
Chk 12672 [[262, 118, 395, 345], [356, 114, 454, 342], [412, 89, 498, 341], [75, 42, 296, 373], [111, 135, 167, 271], [15, 84, 89, 340]]
Chk 12673 [[139, 174, 248, 454], [354, 178, 464, 448], [264, 187, 378, 374], [34, 193, 159, 589], [82, 173, 144, 317]]
Chk 12674 [[394, 76, 639, 474], [0, 10, 267, 472]]
Chk 12676 [[139, 251, 215, 385], [125, 211, 230, 490], [26, 225, 130, 499]]
Chk 12677 [[129, 97, 327, 526], [15, 115, 181, 563], [290, 126, 413, 568], [22, 158, 88, 329], [135, 74, 187, 161]]
Chk 12678 [[332, 4, 585, 421], [52, 20, 297, 426]]
Chk 12681 [[232, 252, 430, 464], [346, 232, 589, 465], [314, 42, 507, 302]]
Chk 12682 [[464, 52, 618, 474], [161, 43, 346, 479], [12, 90, 168, 479], [328, 68, 475, 479]]
Chk 12683 [[211, 197, 343, 479], [72, 173, 187, 466]]
Chk 12684 [[14, 44, 207, 540], [149, 205, 425, 639]]
Chk 12686 [[338, 101, 478, 330], [99, 100, 241, 378]]
Chk 12687 [[4, 99, 226, 626], [271, 141, 425, 620]]
Chk 12688 [[165, 25, 305, 412], [23, 149, 224, 492]]
Chk 12689 [[561, 125, 639, 419], [317, 177, 392, 328], [0, 163, 105, 418], [389, 109, 519, 420], [215, 175, 290, 337], [140, 162, 219, 349]]
Chk 12690 [[21, 15, 214, 425], [195, 54, 419, 421], [418, 10, 638, 423]]
Chk 12691 [[73, 257, 202, 479], [220, 266, 335, 474], [329, 218, 421, 479], [406, 263, 462, 474]]
Chk 12692 [[190, 250, 311, 623], [0, 238, 68, 579], [264, 263, 426, 639]]
Chk 12694 [[327, 175, 418, 423], [395, 150, 469, 422], [295, 154, 355, 417], [174, 162, 280, 423], [242, 126, 305, 423]]
Chk 12695 [[275, 25, 420, 370], [19, 27, 188, 374], [177, 41, 301, 374], [364, 0, 420, 90], [37, 2, 115, 173], [0, 258, 104, 364]]
Chk 12696 [[234, 107, 374, 414], [305, 11, 628, 422]]
Chk 12698 [[0, 19, 282, 404], [240, 92, 622, 384], [272, 1, 639, 278]]
Chk 12699 [[160, 132, 376, 382], [412, 104, 597, 389], [522, 135, 638, 353]]
Chk 12700 [[0, 41, 199, 456], [321, 106, 374, 295], [158, 140, 374, 500]]
Chk 12701 [[104, 125, 267, 293], [208, 31, 406, 392]]
Chk 12702 [[38, 30, 234, 639], [194, 76, 393, 580]]
Chk 12703 [[0, 0, 248, 416], [249, 76, 448, 210], [368, 50, 513, 255], [32, 109, 86, 228], [141, 120, 216, 194], [234, 120, 297, 188], [498, 55, 608, 265]]
Chk 12704 [[0, 1, 141, 370], [161, 42, 392, 374], [346, 75, 499, 368], [324, 35, 420, 287]]
Chk 12705 [[4, 174, 258, 371], [259, 134, 468, 328]]
Chk 12706 [[93, 216, 231, 527], [219, 127, 341, 379], [84, 199, 242, 348]]
Chk 12707 [[228, 147, 396, 456], [347, 187, 472, 451], [422, 2, 599, 473]]
Chk 12711 [[283, 256, 454, 554], [86, 214, 310, 608]]
Chk 12714 [[223, 134, 503, 430], [479, 164, 598, 425], [39, 135, 191, 425]]
Chk 12716 [[2, 256, 295, 420], [276, 183, 352, 282], [379, 166, 493, 420], [530, 158, 639, 420], [158, 122, 262, 360], [97, 283, 411, 422]]
Chk 12717 [[303, 69, 596, 494], [47, 107, 302, 465]]
Chk 12718 [[0, 32, 588, 422], [192, 64, 285, 320], [288, 65, 440, 339], [432, 83, 588, 343], [582, 240, 639, 306], [12, 95, 70, 211]]
Chk 12719 [[175, 152, 399, 428], [391, 167, 624, 356], [223, 87, 370, 249], [26, 79, 126, 314]]
Chk 12720 [[135, 89, 328, 444], [322, 106, 518, 470]]
Chk 12723 [[59, 85, 220, 597], [180, 91, 336, 355], [301, 114, 360, 344], [0, 131, 68, 343]]
Chk 12724 [[85, 89, 229, 416], [0, 183, 73, 423], [62, 63, 121, 162], [479, 120, 559, 204], [267, 161, 380, 300], [434, 130, 494, 229], [397, 142, 449, 230]]
Chk 12725 [[0, 0, 335, 427], [422, 116, 481, 214], [201, 104, 259, 208], [456, 43, 619, 243]]
Chk 12726 [[217, 150, 341, 473], [133, 246, 292, 603], [84, 406, 217, 639]]
Chk 12727 [[84, 314, 273, 631], [334, 158, 426, 353], [82, 82, 233, 323], [247, 1, 311, 78]]
Chk 12728 [[8, 112, 285, 476], [168, 183, 303, 412], [0, 193, 83, 407]]
Chk 12730 [[17, 42, 479, 421], [10, 113, 402, 355], [379, 129, 639, 426], [351, 55, 639, 289]]
Chk 12731 [[356, 44, 631, 366], [544, 93, 639, 371], [125, 197, 414, 345]]
Chk 12733 [[288, 100, 590, 450], [1, 4, 151, 449]]
Chk 12734 [[122, 29, 260, 316], [282, 127, 490, 328], [60, 24, 232, 313], [158, 105, 285, 286]]
Chk 12735 [[2, 94, 304, 451], [263, 297, 471, 630]]
Chk 12736 [[17, 129, 243, 639], [204, 114, 424, 639], [62, 66, 301, 427]]
Chk 12737 [[345, 48, 487, 381], [433, 73, 513, 300], [155, 21, 372, 377], [120, 138, 192, 278]]
Chk 12739 [[90, 140, 245, 302], [3, 153, 198, 430], [0, 115, 51, 198], [420, 170, 582, 450], [84, 114, 144, 227], [231, 136, 327, 266]]
Chk 12740 [[67, 30, 236, 502], [207, 71, 336, 517]]
Chk 12741 [[36, 80, 380, 484], [116, 6, 266, 199], [43, 82, 125, 200]]
Chk 12742 [[217, 5, 545, 511], [392, 259, 608, 621], [100, 103, 295, 404], [18, 283, 218, 500]]
Chk 12743 [[283, 75, 639, 419], [0, 92, 153, 310], [172, 153, 249, 265], [241, 171, 296, 249], [393, 103, 456, 173], [93, 126, 187, 265]]
Chk 12744 [[179, 18, 352, 198], [197, 126, 451, 417], [426, 47, 639, 417], [174, 173, 230, 269]]
Chk 12745 [[136, 58, 492, 638], [211, 102, 375, 343]]
Chk 12746 [[193, 62, 340, 348], [361, 27, 460, 290], [275, 33, 346, 126], [4, 130, 95, 205]]
Chk 12747 [[210, 83, 379, 309], [2, 62, 105, 479], [341, 39, 622, 472]]
Chk 12748 [[2, 46, 141, 421], [142, 113, 354, 420], [348, 162, 534, 421], [509, 163, 637, 419]]
Chk 12749 [[362, 114, 532, 425], [174, 61, 389, 420]]
Chk 12751 [[235, 18, 587, 593], [65, 109, 359, 593]]
Chk 12752 [[134, 122, 507, 502], [1, 270, 574, 558]]
Chk 12753 [[96, 81, 298, 426], [203, 79, 300, 313], [456, 120, 519, 213]]
Chk 12754 [[149, 87, 321, 343], [430, 35, 499, 256], [36, 0, 113, 203], [248, 65, 326, 236], [311, 59, 444, 300], [115, 53, 221, 166], [6, 82, 184, 368]]
Chk 12755 [[338, 95, 638, 473], [46, 87, 369, 473], [46, 113, 204, 239], [158, 116, 219, 204], [527, 118, 629, 260], [516, 120, 572, 207], [0, 170, 71, 337]]
Chk 12756 [[313, 0, 417, 342], [127, 4, 274, 332], [197, 112, 409, 362], [502, 45, 574, 261]]
Chk 12757 [[154, 143, 235, 477], [42, 195, 95, 396], [333, 214, 443, 471]]
Chk 12758 [[141, 100, 296, 277], [243, 77, 311, 157], [29, 18, 163, 275]]
Chk 12759 [[462, 80, 639, 390], [0, 64, 151, 349], [260, 112, 416, 394]]
Chk 12760 [[78, 157, 232, 424], [231, 42, 606, 425]]
Chk 12761 [[50, 177, 170, 354], [385, 161, 494, 363], [338, 180, 639, 479], [158, 176, 261, 294], [267, 151, 388, 252]]
Chk 12763 [[252, 65, 336, 372], [358, 54, 491, 432], [77, 89, 260, 474], [153, 79, 228, 342]]
Chk 12764 [[304, 133, 416, 297], [577, 188, 638, 479], [14, 88, 209, 473], [461, 148, 581, 457]]
Chk 12765 [[200, 53, 467, 419], [420, 55, 636, 417], [427, 119, 480, 196], [0, 127, 59, 224], [170, 111, 247, 292], [0, 136, 210, 425], [362, 100, 416, 190]]
Chk 12766 [[156, 100, 231, 210], [0, 105, 167, 417], [442, 121, 609, 416], [50, 91, 146, 229]]
Chk 12768 [[3, 222, 136, 473], [443, 220, 639, 479], [1, 158, 124, 349], [137, 163, 230, 254], [339, 183, 445, 307], [403, 214, 552, 380]]
Chk 12769 [[35, 68, 337, 456], [297, 114, 479, 340], [254, 168, 311, 271]]
Chk 12771 [[437, 34, 592, 163], [18, 94, 264, 313], [362, 167, 534, 456], [372, 48, 447, 146], [326, 77, 446, 276]]
Chk 12772 [[444, 66, 639, 479], [281, 135, 507, 471], [1, 1, 385, 470]]
Chk 12773 [[180, 67, 461, 562], [4, 26, 234, 265], [309, 0, 468, 119]]
Chk 12774 [[226, 80, 352, 367], [49, 89, 178, 357], [185, 159, 245, 263], [418, 160, 474, 288], [472, 84, 609, 366]]
Chk 12775 [[266, 23, 466, 155], [207, 1, 284, 61], [64, 136, 185, 426], [145, 86, 351, 343]]
Chk 12777 [[129, 135, 206, 379], [206, 165, 267, 378], [260, 137, 346, 376]]
Chk 12778 [[195, 85, 377, 378], [159, 166, 233, 251], [346, 0, 639, 485]]
Chk 12780 [[200, 165, 327, 383], [172, 68, 336, 530], [280, 0, 478, 625]]
Chk 12781 [[174, 26, 376, 381], [279, 239, 639, 404]]
Chk 12782 [[217, 119, 345, 373], [411, 68, 498, 374]]
Chk 12784 [[289, 121, 493, 281], [41, 122, 139, 262], [249, 139, 347, 202], [0, 243, 56, 325], [224, 125, 499, 385]]
Chk 12787 [[50, 135, 139, 469], [127, 126, 223, 460], [443, 154, 528, 333], [539, 154, 612, 344]]
Chk 12788 [[255, 3, 389, 243], [210, 114, 308, 274], [108, 50, 275, 479]]

Chk 12789 [[327, 45, 638, 418], [11, 125, 273, 316]]
Chk 12791 [[99, 24, 192, 484], [98, 75, 293, 498]]
Chk 12793 [[73, 234, 176, 494], [152, 164, 276, 507], [254, 119, 366, 499]]
Chk 12795 [[284, 69, 512, 417], [75, 16, 264, 419]]
Chk 12796 [[117, 0, 246, 391], [336, 114, 401, 295], [387, 0, 602, 404]]
Chk 12797 [[147, 35, 499, 374], [158, 61, 219, 237], [0, 28, 181, 374]]
Chk 12798 [[166, 234, 478, 629], [0, 1, 314, 639]]
Chk 12800 [[354, 35, 516, 282], [48, 132, 214, 288], [0, 90, 77, 288], [304, 112, 368, 206], [263, 112, 323, 211]]
Chk 12801 [[231, 114, 460, 374], [88, 90, 298, 373], [2, 102, 150, 374], [6, 87, 83, 193], [207, 72, 278, 310]]
Chk 12803 [[228, 166, 338, 420], [370, 168, 449, 418], [425, 164, 483, 420], [318, 130, 387, 290]]
Chk 12804 [[172, 73, 458, 570], [112, 178, 242, 625]]
Chk 12805 [[202, 82, 580, 479], [154, 216, 411, 447], [0, 394, 120, 471], [0, 298, 534, 479]]
Chk 12806 [[321, 27, 483, 374], [153, 71, 314, 374]]
Chk 12807 [[406, 38, 479, 96], [255, 52, 334, 310], [125, 118, 268, 332], [300, 33, 383, 113], [104, 44, 197, 308], [3, 28, 115, 337]]
Chk 12808 [[187, 85, 380, 403], [337, 58, 499, 420], [484, 43, 639, 416], [0, 80, 208, 419]]
Chk 12809 [[492, 120, 639, 415], [24, 69, 263, 412], [358, 0, 450, 112], [533, 0, 588, 120], [275, 14, 329, 165], [241, 174, 469, 409]]
Chk 12810 [[249, 38, 380, 315], [61, 75, 193, 318], [410, 192, 465, 309], [356, 159, 413, 317], [189, 218, 246, 319], [234, 149, 345, 309], [49, 194, 124, 322]]
Chk 12811 [[20, 29, 219, 422], [265, 127, 396, 399], [564, 18, 624, 100], [509, 127, 611, 420], [231, 9, 285, 92]]
Chk 12812 [[470, 1, 637, 340], [25, 108, 516, 360], [30, 24, 270, 330]]
Chk 12813 [[16, 43, 129, 192], [432, 64, 639, 418], [185, 43, 397, 249], [94, 69, 239, 225], [390, 54, 491, 306], [240, 37, 312, 160]]
Chk 12814 [[207, 154, 365, 421], [31, 0, 216, 427], [561, 255, 639, 345]]
Chk 12815 [[170, 45, 542, 474], [372, 108, 592, 473]]
Chk 12816 [[292, 79, 633, 446], [38, 83, 309, 356], [0, 116, 64, 315]]
Chk 12817 [[262, 75, 516, 377], [80, 14, 302, 429]]
Chk 12819 [[78, 72, 316, 450], [260, 85, 449, 436]]
Chk 12820 [[211, 44, 499, 332], [0, 37, 489, 332]]
Chk 12821 [[298, 79, 499, 304], [161, 34, 333, 351], [1, 153, 82, 270]]
Chk 12822 [[210, 162, 340, 335], [62, 194, 309, 475], [382, 232, 637, 473], [202, 105, 253, 174], [400, 28, 545, 325]]
Chk 12823 [[346, 146, 455, 435], [96, 104, 243, 439]]
Chk 12824 [[251, 159, 544, 472], [1, 28, 308, 473]]
Chk 12826 [[413, 9, 518, 297], [359, 164, 446, 479]]
Chk 12827 [[0, 28, 447, 631], [0, 122, 163, 362]]
Chk 12829 [[155, 86, 289, 438], [339, 73, 480, 436]]
Chk 12830 [[222, 261, 339, 564], [69, 205, 247, 568], [343, 257, 414, 491], [244, 179, 312, 274]]
Chk 12832 [[266, 73, 464, 330], [117, 141, 298, 350], [1, 110, 128, 369]]
Chk 12833 [[146, 194, 376, 619], [12, 109, 250, 616]]
Chk 12835 [[206, 0, 426, 593], [63, 23, 327, 562]]
Chk 12836 [[250, 69, 390, 425], [190, 193, 263, 407], [128, 189, 212, 394], [462, 181, 639, 425], [33, 182, 142, 417]]
Chk 12838 [[240, 139, 639, 390], [281, 91, 639, 387]]
Chk 12839 [[47, 24, 334, 493], [30, 179, 145, 396]]
Chk 12840 [[407, 106, 568, 420], [94, 101, 229, 391]]
Chk 12841 [[291, 45, 601, 377], [342, 106, 505, 380], [61, 24, 211, 380]]
Chk 12842 [[321, 163, 509, 473], [247, 16, 540, 456], [82, 118, 160, 311]]
Chk 12845 [[0, 104, 209, 601], [289, 200, 438, 461]]
Chk 12846 [[179, 101, 280, 345], [297, 102, 442, 403]]
Chk 12848 [[268, 85, 467, 593], [141, 72, 349, 592]]
Chk 12849 [[214, 32, 528, 472], [2, 77, 349, 473], [391, 57, 563, 452]]
Chk 12851 [[288, 255, 388, 547], [317, 195, 391, 330], [396, 63, 597, 458], [0, 182, 82, 494]]
Chk 12853 [[30, 99, 212, 315], [225, 205, 420, 358], [567, 0, 639, 59], [398, 177, 526, 345]]
Chk 12854 [[37, 113, 276, 478], [467, 142, 614, 281]]
Chk 12855 [[196, 94, 516, 579], [14, 100, 336, 632]]
Chk 12856 [[103, 54, 506, 629], [503, 78, 639, 454]]
Chk 12857 [[275, 181, 488, 479], [218, 231, 388, 474], [415, 407, 586, 472]]
Chk 12858 [[285, 40, 473, 328], [9, 54, 238, 332]]
Chk 12859 [[182, 108, 405, 346], [217, 110, 309, 284], [345, 119, 477, 470], [170, 101, 235, 176]]
Chk 12860 [[247, 49, 500, 380], [83, 68, 422, 424]]
Chk 12861 [[16, 0, 429, 427], [214, 1, 453, 325]]
Chk 12862 [[351, 140, 553, 369], [201, 155, 351, 338], [407, 0, 639, 420], [1, 40, 119, 281]]
Chk 12863 [[206, 116, 395, 382], [432, 118, 538, 344], [27, 283, 88, 424], [0, 330, 89, 426], [483, 36, 592, 348], [106, 308, 169, 408]]
Chk 12864 [[225, 59, 326, 383], [420, 158, 608, 426]]
Chk 12865 [[48, 117, 271, 426], [229, 177, 322, 425], [334, 169, 405, 375], [403, 174, 486, 376], [536, 184, 621, 305], [533, 220, 639, 426], [0, 231, 94, 426]]
Chk 12867 [[405, 61, 486, 361], [341, 156, 423, 386], [282, 62, 364, 204], [248, 71, 299, 329], [179, 49, 262, 197], [167, 141, 253, 380], [244, 142, 350, 386], [349, 68, 414, 207]]
Chk 12868 [[112, 61, 479, 633], [1, 145, 256, 623]]
Chk 12870 [[323, 44, 625, 425], [102, 59, 327, 323], [58, 54, 183, 315], [586, 51, 639, 285], [546, 67, 597, 193]]
Chk 12872 [[77, 56, 412, 331], [58, 112, 529, 479]]
Chk 12873 [[73, 135, 211, 533], [189, 147, 307, 514], [283, 162, 369, 559], [60, 145, 119, 239]]
Chk 12875 [[0, 82, 256, 479], [202, 66, 382, 407], [248, 165, 637, 474]]
Chk 12877 [[1, 65, 251, 370], [269, 71, 499, 374]]
Chk 12879 [[263, 68, 465, 422], [235, 89, 365, 422]]
Chk 12880 [[3, 1, 229, 490], [136, 189, 374, 499]]
Chk 12882 [[40, 93, 268, 494], [246, 103, 434, 487], [0, 224, 54, 454]]
Chk 12883 [[354, 65, 535, 419], [285, 4, 393, 292], [155, 0, 294, 295], [0, 89, 115, 388], [0, 259, 59, 425]]
Chk 12884 [[140, 340, 308, 528], [13, 388, 152, 518], [31, 277, 84, 407], [270, 275, 330, 409], [291, 99, 343, 155], [161, 288, 224, 404], [343, 283, 428, 406]]
Chk 12885 [[314, 96, 412, 451], [388, 147, 494, 444], [235, 121, 335, 446], [154, 149, 241, 435]]
Chk 12886 [[0, 3, 320, 326], [248, 31, 499, 328]]
Chk 12888 [[134, 63, 525, 426], [488, 268, 639, 421]]
Chk 12889 [[269, 36, 458, 625], [1, 249, 265, 639]]
Chk 12894 [[242, 111, 408, 420], [377, 199, 515, 426]]
Chk 12896 [[190, 43, 309, 238], [5, 123, 317, 369], [107, 0, 194, 137], [50, 25, 117, 154]]
Chk 12897 [[5, 110, 190, 319], [302, 102, 441, 287], [443, 118, 639, 424]]
Chk 12900 [[111, 186, 254, 468], [192, 155, 300, 441]]
Chk 12901 [[167, 80, 435, 472], [365, 4, 469, 297], [391, 41, 638, 479]]
Chk 12902 [[160, 42, 319, 302], [366, 49, 606, 456], [548, 74, 600, 212]]
Chk 12904 [[357, 64, 449, 264], [406, 75, 638, 473], [447, 30, 505, 217], [117, 39, 169, 253], [565, 55, 639, 199], [218, 126, 464, 479], [39, 42, 115, 291]]
Chk 12906 [[0, 105, 312, 439], [270, 117, 490, 443], [441, 131, 634, 438]]
Chk 12907 [[141, 25, 454, 361], [0, 156, 238, 392]]
Chk 12908 [[129, 126, 280, 472], [0, 67, 286, 479]]
Chk 12911 [[59, 84, 258, 420], [427, 46, 592, 419]]
Chk 12913 [[174, 73, 353, 301], [0, 34, 150, 222], [343, 0, 479, 229], [390, 533, 479, 629]]
Chk 12914 [[190, 95, 358, 475], [305, 56, 504, 474], [437, 89, 639, 479], [2, 39, 211, 471]]
Chk 12918 [[416, 53, 520, 337], [132, 143, 292, 478], [117, 45, 216, 352], [271, 64, 392, 343]]
Chk 12920 [[499, 158, 639, 417], [125, 15, 302, 421], [3, 73, 159, 426]]
Chk 12922 [[145, 64, 231, 369], [90, 57, 438, 369], [433, 250, 499, 309]]
Chk 12923 [[78, 214, 238, 425], [91, 145, 265, 421]]
Chk 12924 [[227, 123, 372, 420], [300, 97, 484, 426]]
Chk 12926 [[485, 157, 633, 354], [383, 103, 478, 218], [576, 347, 639, 435]]
Chk 12927 [[176, 67, 298, 350], [353, 19, 553, 549]]
Chk 12928 [[12, 63, 168, 313], [145, 48, 274, 324], [284, 135, 639, 426], [141, 94, 368, 422]]
Chk 12929 [[200, 40, 499, 425], [373, 79, 639, 424]]
Chk 12930 [[359, 16, 583, 359], [300, 184, 405, 355], [275, 100, 373, 245], [533, 97, 624, 248], [0, 96, 245, 359], [244, 63, 383, 187], [535, 54, 625, 221]]
Chk 12931 [[120, 127, 263, 478], [228, 106, 296, 223], [368, 173, 504, 472], [316, 39, 452, 245], [249, 128, 397, 473], [0, 196, 175, 360]]
Chk 12932 [[214, 69, 309, 456], [306, 64, 441, 467]]
Chk 12933 [[235, 87, 379, 458], [457, 50, 599, 455], [28, 83, 169, 462]]
Chk 12934 [[176, 35, 386, 580], [34, 56, 170, 579], [460, 148, 533, 344]]
Chk 12935 [[356, 37, 572, 452], [188, 6, 415, 457]]
Chk 12936 [[92, 174, 346, 519], [0, 299, 112, 572]]
Chk 12937 [[298, 381, 425, 598], [99, 96, 376, 518]]
Chk 12938 [[48, 99, 346, 432], [257, 170, 508, 437]]
Chk 12940 [[227, 50, 405, 413], [147, 25, 280, 416], [0, 108, 132, 335]]
Chk 12941 [[86, 245, 278, 625], [353, 335, 479, 614]]
Chk 12942 [[210, 193, 299, 554], [95, 208, 233, 511]]
Chk 12943 [[314, 7, 605, 474], [1, 1, 459, 473]]

Chk 12944 [[187, 57, 503, 452], [35, 183, 603, 474]]
Chk 12945 [[269, 112, 429, 395], [129, 64, 318, 345], [511, 0, 639, 424], [432, 107, 541, 392], [26, 189, 84, 318], [29, 90, 85, 218]]
Chk 12946 [[172, 60, 378, 540], [15, 89, 194, 573]]
Chk 12947 [[277, 42, 635, 479], [45, 86, 227, 479], [554, 123, 639, 280]]
Chk 12949 [[0, 189, 168, 628], [138, 128, 343, 533], [408, 228, 469, 383]]
Chk 12950 [[155, 81, 282, 396], [462, 117, 596, 436], [425, 16, 501, 93], [288, 0, 377, 82], [96, 1, 153, 59], [276, 0, 345, 75], [275, 230, 413, 435]]
Chk 12951 [[116, 15, 240, 342], [342, 41, 450, 351], [440, 13, 621, 359]]
Chk 12952 [[30, 133, 304, 496], [355, 25, 572, 461]]
Chk 12954 [[123, 26, 360, 399], [40, 26, 115, 186], [231, 4, 585, 413]]
Chk 12955 [[308, 70, 500, 510], [19, 48, 374, 579]]
Chk 12956 [[356, 27, 639, 479], [3, 2, 411, 432]]
Chk 12957 [[214, 12, 339, 447], [346, 83, 504, 417]]
Chk 12958 [[0, 313, 86, 453], [237, 348, 341, 541], [78, 145, 220, 402], [93, 302, 238, 631]]
Chk 12960 [[209, 70, 382, 418], [3, 74, 134, 492]]
Chk 12962 [[151, 204, 260, 479], [284, 197, 411, 337], [144, 186, 246, 394], [404, 204, 462, 301], [485, 207, 562, 318], [531, 181, 618, 474], [3, 199, 88, 478]]
Chk 12963 [[29, 122, 101, 211], [83, 9, 175, 136], [97, 67, 209, 238], [174, 114, 296, 249], [273, 22, 400, 195], [390, 49, 508, 185], [411, 47, 595, 234]]
Chk 12964 [[0, 144, 211, 419], [313, 152, 509, 419]]
Chk 12965 [[0, 26, 171, 369], [145, 50, 277, 370], [213, 51, 351, 354], [284, 119, 463, 374]]
Chk 12966 [[8, 30, 204, 394], [134, 58, 285, 400], [257, 96, 315, 179], [157, 17, 217, 84], [330, 87, 489, 338], [317, 172, 406, 367], [0, 203, 73, 313]]
Chk 12967 [[1, 21, 223, 357], [321, 16, 605, 273], [69, 0, 137, 200], [412, 1, 574, 143], [537, 0, 639, 368]]
Chk 12968 [[7, 15, 263, 328], [326, 35, 497, 328]]
Chk 12969 [[113, 212, 205, 521], [188, 190, 284, 525]]
Chk 12970 [[254, 73, 412, 632], [112, 169, 277, 624]]
Chk 12971 [[119, 43, 359, 632], [1, 100, 178, 639]]
Chk 12972 [[142, 53, 432, 583], [0, 4, 337, 632], [428, 323, 479, 638], [315, 234, 368, 368], [353, 276, 451, 399], [412, 300, 463, 371], [379, 277, 451, 378]]
Chk 12973 [[369, 93, 497, 501], [249, 23, 406, 506], [97, 79, 262, 501]]
Chk 12974 [[41, 96, 135, 422], [260, 75, 473, 421], [352, 54, 540, 426]]
Chk 12975 [[362, 3, 639, 423], [0, 59, 377, 426]]
Chk 12976 [[320, 1, 639, 379], [486, 31, 558, 121], [42, 4, 325, 383], [558, 85, 639, 206], [39, 1, 158, 146], [319, 171, 392, 270]]
Chk 12977 [[125, 58, 393, 425], [2, 329, 204, 503]]
Chk 12978 [[119, 222, 252, 602], [206, 142, 284, 579], [231, 223, 383, 603]]
Chk 12979 [[9, 30, 233, 436], [184, 60, 383, 328]]
Chk 12980 [[0, 31, 399, 446], [337, 185, 499, 465], [371, 223, 614, 460], [422, 236, 508, 355], [475, 288, 528, 366], [515, 314, 626, 463], [215, 96, 432, 462], [0, 372, 208, 479]]
Chk 12981 [[147, 148, 304, 493], [31, 159, 154, 460], [276, 342, 374, 499]]
Chk 12982 [[298, 51, 409, 360], [39, 190, 170, 509]]
Chk 12983 [[196, 136, 363, 441], [295, 161, 394, 456]]
Chk 12986 [[294, 207, 351, 408], [399, 199, 462, 380], [1, 195, 100, 462], [543, 195, 639, 463]]
Chk 12987 [[372, 145, 499, 370], [141, 102, 228, 237], [12, 91, 139, 374], [229, 83, 346, 243], [370, 125, 439, 269]]
Chk 12990 [[27, 100, 286, 342], [136, 34, 252, 225], [359, 80, 589, 387], [292, 58, 404, 157]]
Chk 12993 [[228, 86, 416, 400], [2, 1, 207, 467], [184, 127, 254, 345]]
Chk 12994 [[0, 0, 282, 473], [417, 229, 638, 479]]
Chk 12995 [[157, 104, 378, 479], [236, 75, 545, 473]]
Chk 12996 [[7, 64, 187, 479], [256, 38, 407, 479], [368, 19, 639, 474]]
Chk 12997 [[4, 191, 219, 445], [428, 167, 639, 393]]
Chk 13000 [[0, 160, 165, 401], [109, 223, 289, 388], [284, 87, 481, 346]]
Chk 13002 [[159, 271, 413, 393], [341, 2, 591, 415]]
Chk 13003 [[314, 42, 452, 327], [100, 51, 279, 389]]
Chk 13004 [[122, 35, 612, 425], [12, 95, 366, 419]]
Chk 13005 [[378, 6, 639, 425], [0, 119, 263, 420]]
Chk 13006 [[85, 106, 226, 433], [333, 1, 499, 426], [316, 246, 371, 403]]
Chk 13007 [[95, 102, 207, 358], [262, 88, 385, 260], [472, 104, 597, 361]]
Chk 13008 [[90, 28, 232, 419], [157, 0, 208, 243], [421, 77, 531, 374], [0, 0, 65, 362]]
Chk 13009 [[63, 1, 358, 341], [317, 38, 546, 400], [416, 18, 547, 204]]
Chk 13010 [[7, 102, 244, 474], [125, 224, 279, 473], [272, 179, 509, 474]]
Chk 13013 [[128, 37, 337, 370], [145, 312, 303, 588]]
Chk 13014 [[70, 120, 253, 428], [296, 68, 573, 427]]
Chk 13015 [[32, 83, 188, 461], [452, 96, 589, 490]]
Chk 13016 [[22, 83, 256, 405], [550, 30, 637, 208], [391, 86, 560, 411], [308, 9, 390, 174], [510, 100, 561, 188], [238, 52, 305, 147], [243, 87, 403, 304], [98, 92, 154, 181]]
Chk 13017 [[284, 98, 444, 432], [421, 96, 581, 445]]
Chk 13018 [[243, 175, 445, 381], [409, 160, 597, 384], [396, 0, 455, 79], [200, 0, 268, 61], [78, 2, 190, 53], [91, 84, 329, 349]]
Chk 13020 [[269, 101, 405, 493], [209, 225, 312, 490]]
Chk 13021 [[232, 183, 417, 473], [364, 132, 520, 472], [123, 116, 186, 182], [1, 4, 116, 475], [102, 134, 231, 314]]
Chk 13022 [[212, 5, 354, 402], [135, 95, 333, 421], [539, 57, 639, 426], [480, 103, 531, 230], [414, 103, 513, 247], [228, 73, 532, 418]]
Chk 13023 [[237, 0, 508, 374], [253, 0, 307, 68], [31, 88, 272, 393]]
Chk 13024 [[247, 148, 377, 355], [1, 149, 488, 474]]
Chk 13025 [[317, 69, 487, 370], [145, 47, 321, 384], [450, 160, 587, 363], [22, 271, 151, 381]]
Chk 13026 [[43, 1, 634, 466], [59, 43, 309, 475], [314, 86, 421, 333]]
Chk 13027 [[276, 38, 435, 474], [140, 51, 344, 483]]
Chk 13028 [[138, 4, 475, 434], [0, 74, 273, 460], [0, 454, 192, 606]]
Chk 13031 [[0, 3, 247, 468], [201, 180, 381, 391], [334, 80, 499, 390]]
Chk 13032 [[313, 16, 480, 338], [191, 11, 325, 317]]
Chk 13033 [[448, 86, 594, 323], [26, 76, 185, 476]]
Chk 13034 [[360, 96, 468, 353], [274, 85, 395, 373], [0, 84, 136, 372]]
Chk 13035 [[76, 7, 304, 395], [353, 30, 499, 392]]
Chk 13036 [[140, 230, 257, 631], [206, 239, 327, 549]]
Chk 13037 [[158, 241, 254, 530], [235, 247, 302, 531], [53, 572, 165, 640]]
Chk 13038 [[480, 71, 639, 297], [338, 135, 510, 303], [43, 18, 232, 303]]
Chk 13039 [[233, 16, 489, 339], [5, 0, 263, 314], [221, 50, 277, 107], [390, 29, 483, 167]]
Chk 13040 [[41, 9, 315, 408], [351, 147, 436, 421]]
Chk 13041 [[275, 32, 490, 235], [83, 18, 237, 196]]
Chk 13042 [[63, 126, 359, 412], [289, 177, 598, 412], [272, 227, 426, 416]]
Chk 13043 [[343, 77, 499, 332], [299, 105, 393, 331], [185, 92, 334, 328], [53, 98, 243, 332]]
Chk 13044 [[119, 54, 326, 445], [245, 48, 324, 236], [417, 104, 541, 225], [305, 16, 415, 322]]
Chk 13046 [[328, 115, 450, 266], [175, 143, 311, 309], [397, 159, 638, 478], [586, 146, 639, 205]]
Chk 13047 [[218, 226, 383, 639], [143, 153, 301, 631]]
Chk 13048 [[66, 47, 437, 242], [288, 27, 464, 431], [71, 33, 190, 313]]
Chk 13049 [[217, 1, 458, 370], [1, 50, 177, 241], [0, 0, 89, 190]]
Chk 13050 [[15, 135, 322, 525], [331, 220, 461, 500]]
Chk 13051 [[398, 0, 523, 308], [173, 20, 322, 269], [269, 31, 360, 217], [320, 47, 385, 160], [292, 41, 359, 197]]
Chk 13052 [[257, 83, 370, 498], [332, 133, 410, 434], [28, 35, 246, 604], [158, 60, 329, 542]]
Chk 13053 [[281, 69, 481, 292], [6, 95, 210, 353]]
Chk 13056 [[379, 116, 497, 392], [0, 138, 112, 369], [78, 198, 213, 379]]
Chk 13059 [[63, 30, 365, 420], [302, 22, 616, 425]]
Chk 13060 [[0, 132, 165, 357], [108, 137, 245, 298], [204, 108, 273, 261], [413, 160, 515, 304], [291, 132, 638, 426]]
Chk 13061 [[90, 126, 397, 479], [352, 212, 519, 479]]
Chk 13064 [[21, 253, 81, 367], [79, 239, 214, 392], [252, 128, 442, 425], [472, 148, 558, 404]]
Chk 13065 [[268, 58, 478, 414], [465, 182, 562, 375], [545, 179, 608, 355], [0, 312, 164, 415], [191, 175, 250, 332], [3, 260, 124, 346], [241, 78, 363, 414]]
Chk 13067 [[113, 89, 478, 639], [173, 227, 359, 550], [292, 291, 362, 410]]
Chk 13069 [[183, 35, 436, 355], [213, 66, 523, 381]]
Chk 13070 [[69, 181, 222, 443], [184, 202, 375, 450], [128, 135, 210, 311]]
Chk 13071 [[309, 86, 416, 317], [466, 97, 568, 377], [14, 100, 233, 360], [573, 69, 639, 246], [32, 78, 88, 223]]
Chk 13072 [[189, 131, 311, 474], [449, 127, 639, 479]]
Chk 13073 [[36, 15, 151, 403], [450, 32, 639, 414], [135, 67, 270, 367], [209, 157, 378, 420]]
Chk 13074 [[376, 154, 483, 432], [259, 129, 372, 438], [142, 65, 281, 429]]
Chk 13075 [[278, 128, 456, 368], [0, 165, 127, 397], [15, 4, 90, 82], [356, 0, 411, 63], [136, 176, 298, 399]]
Chk 13076 [[80, 112, 203, 340], [212, 258, 374, 467], [262, 281, 370, 420]]
Chk 13077 [[211, 0, 499, 374], [94, 158, 238, 341]]

Chk 13078 [[100, 15, 458, 425], [346, 145, 430, 313], [370, 190, 437, 287], [294, 113, 492, 419], [0, 144, 119, 425]]
Chk 13079 [[375, 125, 459, 402], [430, 51, 551, 413], [72, 146, 196, 382], [584, 148, 639, 381]]
Chk 13080 [[217, 72, 365, 372], [497, 190, 628, 334], [552, 169, 639, 405]]
Chk 13081 [[0, 0, 258, 369], [243, 80, 499, 370]]
Chk 13082 [[234, 82, 494, 393], [0, 199, 181, 407]]
Chk 13084 [[272, 87, 381, 383], [232, 93, 312, 375], [188, 107, 255, 367], [390, 115, 482, 377], [155, 126, 215, 364], [473, 134, 538, 356], [120, 121, 197, 352], [501, 134, 558, 352], [568, 136, 628, 340], [90, 130, 161, 346]]
Chk 13085 [[114, 56, 183, 268], [204, 37, 307, 296], [431, 39, 532, 298]]
Chk 13086 [[84, 27, 404, 572], [438, 109, 629, 395]]
Chk 13088 [[161, 67, 389, 620], [25, 171, 137, 508]]
Chk 13089 [[0, 73, 245, 421], [302, 56, 638, 423]]
Chk 13091 [[260, 101, 389, 337], [315, 199, 488, 397], [464, 155, 611, 414]]
Chk 13092 [[180, 128, 329, 397], [395, 29, 495, 253], [325, 31, 406, 236], [220, 57, 291, 149], [90, 129, 269, 382], [290, 27, 363, 186]]
Chk 13093 [[36, 182, 279, 597], [350, 105, 593, 569]]
Chk 13095 [[320, 74, 482, 331], [0, 56, 178, 330]]
Chk 13096 [[178, 17, 312, 426], [365, 29, 549, 249], [490, 12, 634, 424], [54, 26, 236, 247]]
Chk 13097 [[279, 73, 429, 372], [78, 70, 226, 369]]
Chk 13098 [[331, 35, 497, 369], [123, 71, 310, 365], [0, 87, 117, 369]]
Chk 13099 [[28, 190, 253, 404], [247, 164, 302, 244], [329, 170, 477, 558]]
Chk 13100 [[0, 39, 233, 421], [264, 158, 359, 268], [206, 174, 303, 302], [325, 112, 588, 420], [384, 142, 440, 210]]
Chk 13101 [[86, 29, 285, 432], [272, 35, 352, 346]]
Chk 13102 [[373, 12, 539, 414], [64, 55, 429, 449]]
Chk 13103 [[154, 65, 372, 437], [393, 354, 470, 437], [83, 177, 194, 432], [313, 190, 446, 432]]
Chk 13104 [[172, 56, 326, 382], [357, 140, 498, 417]]
Chk 13107 [[140, 63, 295, 436], [227, 57, 343, 411], [522, 81, 639, 442], [473, 150, 527, 270], [440, 148, 496, 272]]
Chk 13109 [[344, 2, 639, 420], [102, 73, 505, 426], [154, 64, 346, 260], [7, 9, 371, 289]]
Chk 13110 [[227, 0, 479, 410], [2, 5, 282, 380]]
Chk 13111 [[352, 73, 558, 372], [18, 56, 212, 398]]
Chk 13112 [[297, 96, 495, 333], [418, 125, 496, 304], [363, 27, 414, 89], [121, 95, 203, 175], [53, 158, 192, 333], [18, 141, 126, 332], [443, 10, 512, 74], [137, 0, 189, 76]]
Chk 13113 [[327, 0, 494, 277], [162, 100, 289, 271], [3, 0, 147, 281]]
Chk 13114 [[57, 30, 314, 468], [113, 394, 293, 639]]
Chk 13115 [[91, 130, 306, 299], [278, 143, 492, 324]]
Chk 13116 [[449, 153, 639, 478], [442, 64, 521, 304], [8, 88, 126, 342]]
Chk 13117 [[449, 314, 530, 416], [29, 87, 140, 422], [158, 156, 256, 426], [272, 185, 371, 426], [57, 111, 186, 421]]
Chk 13118 [[276, 39, 494, 374], [15, 49, 267, 358]]
Chk 13119 [[315, 10, 473, 219], [476, 33, 639, 264], [355, 123, 639, 479], [0, 65, 198, 479], [37, 12, 159, 209]]
Chk 13120 [[25, 69, 267, 443], [340, 94, 632, 448]]
Chk 13121 [[0, 146, 217, 473], [340, 121, 537, 321]]
Chk 13122 [[207, 50, 494, 420], [85, 115, 220, 397]]
Chk 13124 [[103, 131, 249, 375], [210, 135, 318, 375]]
Chk 13125 [[7, 64, 195, 328], [186, 105, 289, 290], [354, 78, 499, 302], [426, 259, 499, 332]]
Chk 13126 [[416, 151, 504, 427], [126, 122, 227, 421]]
Chk 13127 [[122, 90, 301, 335], [460, 117, 528, 295], [255, 60, 382, 319], [0, 235, 76, 479]]
Chk 13128 [[327, 22, 471, 217], [461, 38, 599, 193], [131, 33, 191, 102], [33, 281, 87, 339], [181, 341, 286, 428], [17, 294, 96, 413], [96, 353, 178, 420], [279, 486, 400, 577]]
Chk 13129 [[310, 49, 389, 315], [41, 60, 306, 473]]
Chk 13130 [[0, 36, 336, 421], [347, 105, 541, 336]]
Chk 13131 [[139, 104, 425, 369], [504, 100, 603, 327], [225, 117, 281, 178], [0, 103, 53, 316], [402, 214, 594, 365]]
Chk 13132 [[236, 121, 401, 474], [59, 140, 261, 472], [37, 178, 115, 479], [379, 167, 538, 479]]
Chk 13133 [[124, 130, 329, 467], [213, 129, 351, 476]]
Chk 13134 [[13, 39, 173, 421], [258, 92, 350, 240], [471, 60, 639, 305], [152, 87, 288, 351], [378, 79, 505, 275]]
Chk 13136 [[219, 64, 353, 419], [130, 53, 229, 426]]
Chk 13137 [[0, 68, 271, 398], [350, 106, 639, 420]]
Chk 13138 [[113, 42, 246, 349], [23, 70, 150, 353]]
Chk 13139 [[308, 32, 542, 334], [201, 2, 331, 318]]
Chk 13140 [[198, 64, 563, 475], [488, 5, 639, 389]]
Chk 13141 [[20, 56, 322, 421], [275, 56, 638, 422]]
Chk 13142 [[236, 63, 343, 584], [32, 174, 148, 569]]
Chk 13143 [[414, 268, 549, 479], [292, 188, 501, 479]]
Chk 13144 [[348, 235, 561, 470], [381, 215, 457, 331], [0, 192, 197, 473], [212, 223, 304, 460], [520, 181, 598, 282]]
Chk 13145 [[55, 30, 398, 626], [71, 143, 204, 542], [26, 243, 92, 417]]
Chk 13146 [[0, 9, 296, 201], [330, 297, 399, 422], [235, 230, 327, 420], [407, 297, 490, 426], [452, 232, 610, 421], [388, 286, 455, 426]]
Chk 13147 [[99, 106, 404, 454], [270, 60, 589, 372]]
Chk 13148 [[49, 144, 218, 461], [208, 242, 339, 422], [520, 123, 616, 253]]
Chk 13151 [[109, 129, 276, 385], [420, 211, 525, 388], [491, 187, 618, 399]]
Chk 13153 [[343, 69, 598, 543], [245, 50, 456, 531], [1, 298, 221, 555]]
Chk 13154 [[261, 117, 413, 382], [1, 102, 281, 421], [185, 120, 346, 425]]
Chk 13155 [[198, 147, 268, 244], [25, 123, 233, 469], [259, 138, 437, 373], [436, 123, 568, 250]]
Chk 13156 [[47, 81, 327, 420], [257, 274, 381, 421], [365, 282, 623, 425], [0, 249, 66, 426], [310, 271, 480, 426]]
Chk 13157 [[23, 60, 273, 418], [234, 75, 600, 475]]
Chk 13159 [[313, 102, 511, 350], [109, 40, 263, 191]]
Chk 13160 [[262, 110, 355, 445], [212, 129, 283, 431], [5, 178, 70, 247]]
Chk 13161 [[1, 112, 103, 550], [496, 154, 612, 339], [221, 188, 351, 350], [392, 225, 639, 632]]
Chk 13162 [[163, 31, 490, 438], [61, 28, 298, 439]]
Chk 13163 [[316, 2, 410, 301], [103, 16, 168, 275], [0, 2, 135, 293], [0, 232, 151, 402]]
Chk 13164 [[202, 64, 340, 374], [144, 84, 258, 361]]
Chk 13166 [[1, 94, 379, 634], [206, 50, 479, 632]]
Chk 13168 [[191, 258, 372, 622], [319, 136, 423, 397], [23, 44, 215, 621]]
Chk 13171 [[500, 38, 592, 598], [9, 151, 293, 600], [302, 56, 516, 574], [115, 103, 364, 601]]
Chk 13172 [[54, 27, 189, 250], [260, 63, 383, 191], [238, 34, 503, 331]]
Chk 13173 [[296, 44, 419, 359], [203, 52, 309, 355], [454, 79, 545, 414], [533, 86, 625, 341], [396, 75, 492, 385]]
Chk 13174 [[36, 82, 202, 469], [168, 87, 460, 474]]
Chk 13175 [[250, 81, 357, 345], [129, 76, 236, 341], [428, 106, 509, 338]]
Chk 13176 [[249, 135, 347, 406], [431, 114, 520, 373], [586, 123, 639, 371], [373, 54, 433, 118], [481, 52, 544, 127], [539, 50, 598, 112], [261, 42, 316, 138]]
Chk 13177 [[67, 234, 198, 462], [158, 290, 334, 491]]
Chk 13179 [[101, 19, 193, 241], [165, 73, 219, 200], [467, 54, 626, 399], [443, 68, 506, 149], [310, 80, 362, 229], [212, 35, 364, 282]]
Chk 13181 [[278, 137, 438, 425], [212, 63, 279, 208], [372, 42, 531, 421], [502, 75, 556, 187]]
Chk 13182 [[14, 138, 424, 632], [49, 45, 424, 639]]
Chk 13183 [[0, 0, 383, 423], [174, 52, 554, 376]]
Chk 13184 [[25, 106, 250, 625], [237, 62, 371, 395]]
Chk 13185 [[168, 60, 381, 360], [16, 209, 179, 385], [0, 138, 52, 392]]
Chk 13186 [[305, 47, 638, 421], [8, 5, 385, 418]]
Chk 13187 [[203, 217, 405, 456], [402, 198, 575, 421], [99, 92, 179, 238], [265, 80, 349, 233], [501, 84, 591, 316], [19, 254, 138, 485], [32, 84, 84, 159]]
Chk 13188 [[87, 0, 506, 420], [346, 6, 639, 413], [1, 0, 147, 426], [1, 148, 98, 238]]
Chk 13189 [[330, 1, 451, 255], [255, 129, 317, 329], [0, 0, 84, 332], [62, 1, 152, 233]]
Chk 13190 [[355, 135, 534, 434], [145, 96, 384, 430]]
Chk 13194 [[2, 25, 210, 266], [189, 4, 262, 173], [248, 0, 318, 119], [48, 0, 134, 131], [423, 146, 639, 418], [0, 48, 51, 155], [545, 8, 639, 156]]
Chk 13195 [[273, 53, 605, 632], [21, 207, 485, 630]]
Chk 13197 [[189, 72, 370, 374], [334, 130, 639, 421], [237, 136, 596, 462]]
Chk 13198 [[561, 254, 639, 472], [371, 313, 600, 473], [152, 210, 353, 458]]
Chk 13199 [[333, 22, 598, 269], [41, 168, 357, 288]]
Chk 13200 [[348, 208, 454, 405], [172, 208, 249, 503], [142, 180, 199, 282], [38, 8, 180, 553]]
Chk 13202 [[195, 158, 388, 440], [361, 247, 469, 427], [536, 225, 639, 438], [83, 3, 251, 252], [403, 18, 462, 92], [0, 0, 58, 62]]
Chk 13204 [[231, 97, 412, 340], [170, 210, 371, 351], [451, 47, 639, 422], [305, 41, 569, 388]]
Chk 13205 [[102, 67, 367, 425], [359, 108, 479, 415]]
Chk 13206 [[184, 119, 434, 325], [190, 186, 398, 420]]
Chk 13207 [[13, 7, 423, 440], [371, 101, 639, 434], [502, 81, 636, 276], [332, 84, 415, 437], [353, 158, 451, 395]]
Chk 13208 [[265, 144, 556, 425], [413, 25, 639, 422]]
Chk 13210 [[189, 211, 327, 474], [405, 189, 593, 477]]
Chk 13211 [[3, 222, 494, 430], [167, 172, 535, 273], [269, 82, 353, 165], [250, 171, 479, 222]]

Chk 13212 [[202, 72, 422, 463], [365, 118, 588, 475], [50, 58, 230, 414], [144, 17, 284, 242]]
Chk 13214 [[238, 58, 391, 285], [433, 174, 631, 342]]
Chk 13215 [[99, 106, 242, 298], [473, 112, 570, 421]]
Chk 13216 [[2, 84, 360, 393], [313, 92, 571, 318]]
Chk 13217 [[42, 176, 234, 411], [297, 171, 450, 430]]
Chk 13218 [[331, 213, 574, 469], [1, 197, 284, 473], [558, 205, 639, 479]]
Chk 13219 [[191, 142, 398, 595], [1, 73, 133, 464], [475, 157, 616, 491]]
Chk 13220 [[25, 31, 350, 439], [3, 102, 210, 440], [291, 33, 635, 438]]
Chk 13221 [[87, 123, 213, 367], [11, 85, 317, 374], [293, 110, 478, 281]]
Chk 13223 [[58, 99, 434, 369], [0, 73, 247, 371]]
Chk 13224 [[100, 205, 288, 382], [0, 93, 175, 360], [515, 140, 615, 385], [284, 52, 513, 388], [385, 55, 471, 143]]
Chk 13230 [[95, 252, 202, 630], [184, 242, 333, 636]]
Chk 13232 [[298, 26, 458, 369], [101, 0, 272, 370]]
Chk 13234 [[49, 5, 197, 473], [181, 56, 323, 474], [411, 82, 593, 470], [276, 19, 457, 475], [1, 122, 70, 314]]
Chk 13235 [[43, 214, 219, 370], [221, 100, 320, 226], [397, 131, 499, 369], [76, 104, 158, 233]]
Chk 13236 [[98, 257, 273, 419], [237, 249, 369, 423], [81, 203, 218, 376], [580, 215, 638, 424], [427, 212, 602, 417], [412, 222, 475, 379]]
Chk 13237 [[18, 10, 179, 439], [421, 207, 639, 488], [242, 151, 442, 495], [267, 32, 407, 486]]
Chk 13239 [[363, 63, 636, 400], [403, 0, 492, 143], [506, 6, 639, 294], [281, 55, 528, 391], [394, 127, 456, 225]]
Chk 13240 [[212, 233, 285, 484], [297, 198, 410, 620], [39, 179, 221, 634]]
Chk 13243 [[77, 113, 406, 639], [50, 128, 421, 369]]
Chk 13244 [[115, 193, 210, 509], [238, 180, 347, 476]]
Chk 13247 [[243, 82, 499, 378], [68, 192, 153, 324], [153, 141, 238, 325], [253, 64, 385, 129], [148, 147, 255, 324]]
Chk 13248 [[207, 83, 350, 422], [95, 77, 186, 400], [449, 96, 544, 410], [369, 87, 436, 369]]
Chk 13249 [[229, 71, 402, 419], [94, 73, 224, 420], [375, 48, 588, 420]]
Chk 13250 [[246, 68, 510, 420], [235, 103, 494, 415], [37, 222, 226, 420]]
Chk 13251 [[213, 137, 338, 472], [323, 129, 424, 474], [453, 146, 524, 425], [421, 143, 526, 391]]
Chk 13253 [[81, 175, 225, 345], [378, 113, 579, 345]]
Chk 13254 [[298, 0, 601, 415], [32, 144, 305, 420]]
Chk 13255 [[290, 184, 479, 629], [93, 200, 298, 630]]
Chk 13256 [[203, 139, 446, 313], [380, 64, 639, 424]]
Chk 13257 [[2, 124, 192, 412], [187, 160, 308, 379]]
Chk 13258 [[312, 166, 433, 355], [127, 155, 239, 426], [447, 105, 580, 426], [0, 107, 125, 349]]
Chk 13259 [[0, 1, 343, 397], [185, 117, 376, 322]]
Chk 13260 [[342, 5, 639, 415], [81, 125, 371, 422]]
Chk 13261 [[393, 105, 577, 471], [235, 80, 366, 470], [354, 116, 444, 479], [50, 125, 307, 474]]
Chk 13262 [[487, 36, 639, 348], [0, 76, 288, 471], [202, 23, 489, 346]]
Chk 13263 [[324, 103, 438, 331], [73, 114, 230, 368], [156, 0, 231, 65]]
Chk 13264 [[278, 118, 405, 368], [16, 60, 265, 374]]
Chk 13265 [[178, 60, 356, 383], [412, 73, 576, 383]]
Chk 13267 [[2, 260, 155, 434], [199, 50, 436, 362], [117, 293, 309, 434]]
Chk 13268 [[238, 60, 299, 268], [348, 8, 465, 308], [265, 126, 337, 268], [172, 74, 298, 328]]
Chk 13269 [[14, 119, 123, 420], [439, 94, 549, 275]]
Chk 13270 [[259, 31, 458, 426], [459, 0, 639, 421]]
Chk 13271 [[180, 230, 466, 639], [294, 107, 403, 434]]
Chk 13272 [[159, 61, 327, 266], [344, 69, 510, 293], [0, 313, 173, 543], [560, 342, 639, 435]]
Chk 13273 [[164, 133, 272, 403], [302, 162, 389, 391], [392, 143, 531, 409]]
Chk 13275 [[458, 111, 591, 424], [267, 89, 497, 289]]
Chk 13277 [[390, 76, 639, 479], [60, 104, 235, 473]]
Chk 13279 [[360, 116, 574, 469], [31, 107, 300, 477]]
Chk 13280 [[536, 145, 639, 416], [129, 192, 195, 384], [400, 181, 468, 338], [505, 191, 559, 310], [283, 193, 359, 390], [202, 269, 288, 424], [460, 178, 517, 356]]
Chk 13281 [[0, 126, 295, 426], [217, 62, 383, 426], [339, 19, 639, 426]]
Chk 13282 [[14, 0, 285, 541], [371, 119, 427, 191], [427, 279, 486, 406], [198, 37, 316, 376], [488, 81, 540, 296], [512, 79, 639, 525]]
Chk 13283 [[103, 48, 453, 424], [445, 144, 518, 207], [372, 271, 463, 418], [522, 179, 639, 421], [291, 318, 373, 414], [209, 314, 279, 416], [40, 50, 100, 135]]
Chk 13285 [[123, 42, 357, 426], [0, 134, 68, 283], [372, 87, 623, 426], [439, 148, 495, 230], [318, 149, 378, 277], [347, 129, 402, 257]]
Chk 13286 [[157, 37, 286, 173], [277, 128, 420, 308], [75, 98, 222, 338]]
Chk 13288 [[244, 10, 415, 381], [34, 31, 224, 319], [502, 1, 639, 416], [370, 0, 485, 107], [275, 0, 340, 83], [90, 0, 188, 91]]
Chk 13289 [[247, 36, 428, 608], [38, 46, 260, 608]]
Chk 13290 [[216, 94, 461, 364], [0, 97, 216, 334]]
Chk 13291 [[456, 88, 630, 416], [25, 41, 236, 419], [407, 266, 470, 392]]
Chk 13293 [[116, 47, 338, 497], [41, 137, 159, 491], [313, 163, 417, 572]]
Chk 13295 [[104, 54, 292, 472], [39, 113, 125, 467], [225, 249, 305, 406], [0, 410, 132, 478]]
Chk 13296 [[162, 48, 316, 298], [1, 15, 151, 398], [392, 262, 479, 581]]
Chk 13297 [[138, 61, 380, 420], [0, 71, 166, 420]]
Chk 13298 [[167, 35, 381, 426], [467, 95, 632, 425], [291, 95, 456, 418], [0, 26, 157, 380]]
Chk 13300 [[115, 34, 353, 281], [254, 30, 409, 287], [417, 40, 613, 326], [551, 40, 639, 321], [518, 86, 578, 162]]
Chk 13301 [[116, 87, 456, 479], [500, 58, 607, 260], [294, 180, 499, 469]]
Chk 13302 [[23, 60, 369, 632], [271, 20, 498, 391]]
Chk 13303 [[329, 79, 596, 385], [160, 0, 398, 347], [32, 137, 231, 351]]
Chk 13305 [[171, 159, 275, 471], [264, 158, 352, 393], [343, 186, 439, 448]]
Chk 13306 [[361, 103, 628, 343], [3, 125, 193, 345]]
Chk 13307 [[309, 101, 502, 417], [112, 25, 354, 426]]
Chk 13308 [[320, 114, 419, 450], [229, 112, 319, 415]]
Chk 13309 [[19, 23, 170, 357], [175, 60, 330, 358], [490, 15, 639, 353], [317, 31, 520, 357], [265, 46, 377, 350]]
Chk 13310 [[3, 89, 136, 369], [292, 80, 411, 370], [164, 76, 299, 374]]
Chk 13311 [[44, 62, 276, 419], [6, 50, 92, 320], [1, 15, 229, 452], [330, 0, 461, 345], [186, 60, 384, 388], [245, 117, 334, 348]]
Chk 13312 [[315, 1, 464, 217], [138, 63, 303, 446], [149, 1, 231, 175]]
Chk 13313 [[25, 48, 206, 368], [274, 41, 329, 241], [412, 68, 487, 219], [302, 126, 452, 369]]
Chk 13314 [[0, 173, 268, 426], [275, 264, 383, 426], [199, 253, 356, 420], [462, 282, 545, 426], [349, 292, 400, 343], [389, 254, 493, 426], [0, 226, 76, 400]]
Chk 13315 [[219, 23, 434, 410], [508, 1, 639, 426], [17, 31, 258, 420], [406, 39, 513, 182], [0, 0, 95, 160]]
Chk 13316 [[1, 91, 273, 391], [394, 109, 638, 379]]
Chk 13317 [[147, 209, 260, 478], [261, 217, 356, 479], [329, 180, 451, 479]]
Chk 13318 [[70, 60, 374, 627], [285, 38, 478, 577]]
Chk 13319 [[74, 104, 327, 595], [229, 57, 395, 552]]
Chk 13320 [[220, 75, 584, 383], [297, 180, 492, 383]]
Chk 13321 [[73, 142, 214, 479], [197, 194, 357, 479]]
Chk 13322 [[0, 19, 242, 279], [76, 0, 400, 277]]
Chk 13323 [[15, 19, 386, 574], [377, 27, 639, 555]]
Chk 13324 [[458, 3, 563, 327], [341, 0, 465, 333], [239, 0, 346, 325], [2, 0, 639, 340]]
Chk 13325 [[248, 117, 358, 505], [62, 121, 191, 538]]
Chk 13326 [[251, 59, 340, 129], [147, 42, 218, 276], [328, 39, 403, 310], [383, 61, 452, 291], [41, 48, 158, 329]]
Chk 13327 [[196, 38, 360, 237], [353, 18, 535, 375]]
Chk 13328 [[326, 90, 500, 427], [138, 116, 337, 421], [265, 116, 408, 421], [499, 134, 639, 426], [0, 179, 175, 419]]
Chk 13330 [[10, 25, 297, 617], [277, 12, 495, 608], [40, 81, 118, 216]]
Chk 13331 [[0, 106, 311, 482], [292, 3, 639, 483]]
Chk 13333 [[330, 84, 573, 405], [166, 88, 531, 420]]
Chk 13334 [[393, 7, 616, 233], [13, 13, 228, 421]]
Chk 13336 [[1, 86, 326, 479], [329, 65, 629, 303]]
Chk 13337 [[299, 254, 441, 614], [113, 204, 312, 589]]
Chk 13338 [[135, 22, 269, 161], [26, 64, 300, 420], [393, 56, 578, 302], [485, 9, 623, 131]]
Chk 13339 [[280, 254, 376, 566], [141, 272, 243, 562], [234, 282, 307, 572]]
Chk 13340 [[171, 183, 400, 519], [468, 264, 601, 450], [435, 194, 615, 512]]
Chk 13341 [[1, 65, 163, 638], [99, 11, 426, 632], [129, 152, 308, 626]]
Chk 13342 [[231, 75, 487, 419], [0, 94, 212, 330]]
Chk 13343 [[121, 12, 492, 374], [156, 0, 327, 291]]
Chk 13344 [[28, 4, 277, 306], [109, 67, 399, 307]]
Chk 13347 [[352, 35, 517, 317], [192, 48, 372, 355]]
Chk 13348 [[237, 56, 524, 444], [209, 242, 529, 551], [0, 233, 225, 508]]
Chk 13351 [[156, 152, 479, 639], [0, 94, 232, 629], [192, 175, 300, 294], [0, 118, 74, 242]]
Chk 13352 [[97, 77, 327, 426], [394, 132, 513, 267], [498, 147, 568, 245], [1, 268, 136, 426], [563, 119, 639, 254], [0, 122, 67, 302]]
Chk 13353 [[203, 22, 453, 430], [11, 21, 321, 417]]

Chk 13354 [[133, 189, 286, 631], [0, 132, 117, 364], [217, 100, 311, 446], [312, 160, 370, 235], [111, 124, 254, 247], [333, 164, 426, 385], [108, 107, 166, 282]]
Chk 13356 [[377, 280, 637, 474], [40, 134, 230, 316], [369, 172, 516, 314], [207, 159, 299, 260], [451, 171, 619, 354], [165, 143, 239, 252], [312, 171, 406, 258]]
Chk 13357 [[2, 49, 191, 325], [159, 90, 350, 325], [348, 111, 497, 328]]
Chk 13358 [[494, 74, 637, 473], [292, 73, 473, 477]]
Chk 13360 [[337, 128, 459, 424], [191, 138, 355, 424], [73, 128, 165, 419]]
Chk 13361 [[361, 113, 542, 370], [22, 166, 243, 380], [478, 89, 551, 175], [186, 210, 301, 350]]
Chk 13362 [[0, 200, 315, 450], [258, 41, 524, 456]]
Chk 13363 [[240, 10, 586, 356], [120, 59, 298, 296], [453, 22, 639, 340], [0, 55, 162, 284]]
Chk 13365 [[122, 159, 256, 419], [260, 127, 348, 350], [362, 52, 485, 362]]
Chk 13366 [[111, 141, 365, 619], [70, 150, 233, 622]]
Chk 13368 [[195, 0, 385, 336], [89, 68, 263, 299], [0, 122, 154, 350]]
Chk 13369 [[6, 108, 349, 370], [51, 0, 345, 321], [427, 74, 499, 373]]
Chk 13371 [[457, 114, 639, 478], [90, 253, 179, 355], [450, 248, 508, 322], [180, 251, 341, 479], [468, 171, 609, 386], [1, 240, 168, 473]]
Chk 13372 [[31, 126, 280, 443], [305, 128, 443, 286], [161, 83, 235, 217], [5, 51, 56, 104], [412, 141, 562, 341], [0, 165, 73, 320], [92, 74, 165, 151], [0, 52, 123, 143]]
Chk 13373 [[446, 0, 569, 175], [423, 141, 639, 422]]
Chk 13374 [[289, 45, 435, 364], [30, 221, 390, 544]]
Chk 13375 [[318, 174, 416, 446], [187, 206, 275, 448], [40, 129, 166, 451]]
Chk 13376 [[199, 12, 441, 631], [0, 86, 239, 639]]
Chk 13377 [[3, 6, 270, 388], [357, 110, 553, 383]]
Chk 13378 [[40, 6, 287, 419], [256, 1, 519, 401]]
Chk 13380 [[156, 91, 337, 418], [343, 27, 612, 420]]
Chk 13382 [[97, 213, 226, 467], [208, 206, 318, 464]]
Chk 13385 [[287, 27, 491, 465], [177, 87, 318, 469], [17, 161, 227, 473], [12, 129, 207, 210], [356, 156, 639, 472]]
Chk 13386 [[132, 153, 312, 413], [228, 23, 476, 394]]
Chk 13387 [[115, 0, 284, 336], [18, 0, 149, 336]]
Chk 13388 [[183, 75, 332, 498], [11, 82, 137, 427]]
Chk 13389 [[312, 2, 638, 506], [21, 141, 232, 527]]
Chk 13391 [[174, 146, 412, 373], [135, 3, 423, 301]]
Chk 13392 [[232, 303, 330, 608], [326, 313, 428, 602]]
Chk 13393 [[54, 350, 331, 629], [1, 0, 473, 639]]
Chk 13395 [[16, 148, 188, 342], [341, 146, 621, 455], [342, 86, 457, 310], [0, 253, 109, 356]]
Chk 13396 [[58, 139, 235, 466], [306, 146, 419, 275], [181, 120, 303, 278], [405, 139, 601, 465]]
Chk 13398 [[137, 75, 318, 382], [418, 10, 598, 369], [449, 0, 628, 79]]
Chk 13399 [[0, 151, 237, 479], [224, 165, 372, 320], [396, 141, 638, 479], [0, 175, 165, 345]]
Chk 13400 [[318, 90, 417, 229], [299, 140, 639, 479], [0, 106, 305, 475], [473, 115, 608, 332], [543, 0, 639, 242], [99, 0, 283, 111]]
Chk 13401 [[192, 75, 319, 402], [99, 107, 198, 394]]
Chk 13402 [[183, 103, 263, 364], [464, 156, 563, 406], [280, 114, 382, 416], [379, 121, 473, 405]]
Chk 13403 [[85, 78, 520, 414], [380, 128, 572, 376]]
Chk 13404 [[133, 64, 332, 491], [0, 236, 177, 638]]
Chk 13405 [[142, 181, 336, 422], [370, 245, 535, 421], [505, 89, 576, 167], [574, 94, 638, 186], [456, 87, 518, 165], [539, 199, 638, 426], [302, 45, 367, 146]]
Chk 13406 [[118, 49, 358, 385], [2, 8, 148, 354], [312, 140, 484, 268], [478, 148, 569, 266], [500, 111, 639, 409], [476, 135, 542, 213], [280, 137, 411, 256]]
Chk 13407 [[277, 31, 379, 168], [214, 175, 498, 473], [389, 0, 638, 144], [101, 0, 290, 198]]
Chk 13408 [[37, 104, 295, 632], [353, 176, 425, 558], [244, 153, 346, 544], [42, 272, 127, 562]]
Chk 13409 [[0, 53, 252, 499], [207, 114, 400, 389]]
Chk 13411 [[545, 86, 639, 238], [249, 101, 349, 227], [156, 80, 291, 331], [105, 85, 211, 278], [50, 89, 110, 211], [51, 1, 106, 159], [340, 0, 417, 140], [245, 72, 308, 197], [434, 72, 605, 329], [99, 0, 565, 145], [340, 87, 447, 327], [0, 115, 104, 221]]
Chk 13412 [[23, 43, 288, 424], [224, 179, 399, 420], [528, 41, 593, 96], [342, 28, 536, 417], [475, 44, 535, 122]]
Chk 13413 [[371, 81, 639, 321], [0, 36, 394, 327]]
Chk 13414 [[13, 66, 481, 600], [363, 211, 479, 517]]
Chk 13415 [[53, 42, 275, 530], [266, 54, 439, 563]]
Chk 13416 [[32, 0, 469, 480], [408, 31, 639, 478]]
Chk 13417 [[274, 184, 376, 537], [94, 342, 479, 633]]
Chk 13418 [[61, 65, 327, 377], [269, 0, 374, 281], [327, 65, 582, 340], [9, 18, 157, 251], [237, 14, 310, 105], [492, 0, 639, 306], [374, 0, 425, 65]]
Chk 13419 [[0, 149, 106, 367], [121, 45, 176, 99], [222, 10, 280, 85], [177, 9, 238, 92], [227, 113, 410, 339], [0, 43, 54, 109]]
Chk 13420 [[275, 63, 461, 395], [194, 70, 326, 375]]
Chk 13421 [[114, 119, 315, 468], [405, 34, 574, 461]]
Chk 13422 [[136, 134, 223, 414], [492, 104, 555, 230], [24, 127, 121, 422], [554, 107, 624, 324]]
Chk 13423 [[214, 82, 571, 423], [25, 99, 258, 423]]
Chk 13424 [[318, 222, 462, 479], [51, 39, 200, 276]]
Chk 13425 [[111, 69, 469, 421], [391, 1, 561, 421], [506, 43, 572, 243], [87, 0, 234, 231], [0, 1, 62, 300], [536, 0, 591, 113]]
Chk 13426 [[327, 32, 528, 472], [0, 29, 317, 474], [297, 112, 393, 412], [410, 74, 637, 470]]
Chk 13427 [[55, 83, 305, 476], [247, 41, 347, 213], [147, 0, 213, 118], [305, 128, 639, 473], [101, 0, 158, 188]]
Chk 13428 [[206, 214, 432, 426], [447, 112, 614, 421], [236, 58, 454, 302], [544, 70, 615, 172]]
Chk 13430 [[286, 81, 559, 479], [0, 84, 300, 455]]
Chk 13431 [[288, 1, 639, 563], [55, 49, 297, 421], [229, 88, 349, 265], [35, 111, 121, 366], [486, 0, 639, 182]]
Chk 13433 [[19, 72, 241, 421], [395, 68, 620, 411]]
Chk 13434 [[237, 12, 339, 185], [188, 181, 523, 305], [76, 212, 355, 312], [47, 0, 187, 305], [553, 0, 639, 253], [445, 7, 639, 353]]
Chk 13435 [[221, 150, 406, 413], [170, 167, 328, 401]]
Chk 13436 [[395, 37, 552, 394], [38, 40, 220, 395]]
Chk 13437 [[131, 75, 247, 375], [241, 165, 414, 412], [415, 61, 546, 420]]
Chk 13439 [[215, 14, 634, 461], [73, 56, 333, 456]]
Chk 13440 [[95, 26, 277, 355], [250, 77, 385, 353]]
Chk 13441 [[501, 70, 637, 308], [430, 78, 514, 233], [89, 76, 339, 347], [7, 61, 261, 380], [342, 94, 491, 280]]
Chk 13442 [[87, 128, 284, 513], [132, 99, 426, 527]]
Chk 13443 [[256, 148, 522, 423], [209, 107, 338, 378]]
Chk 13444 [[15, 73, 291, 471], [391, 179, 477, 452]]
Chk 13445 [[244, 68, 390, 345], [50, 146, 252, 420], [203, 191, 343, 400]]
Chk 13446 [[4, 217, 278, 494], [208, 146, 301, 397], [6, 126, 62, 202]]
Chk 13448 [[270, 26, 506, 358], [427, 233, 639, 396], [510, 231, 586, 348], [499, 305, 574, 396], [21, 243, 74, 306], [555, 271, 608, 344], [11, 10, 293, 391]]
Chk 13449 [[86, 71, 221, 379], [181, 51, 331, 490], [1, 406, 77, 493]]
Chk 13450 [[41, 124, 214, 421], [206, 56, 391, 399]]
Chk 13451 [[97, 69, 513, 422], [357, 136, 462, 318], [423, 101, 639, 422], [188, 138, 273, 269], [0, 158, 175, 421], [519, 99, 639, 211]]
Chk 13452 [[207, 0, 359, 174], [406, 0, 639, 238], [6, 0, 174, 202], [415, 25, 475, 98]]
Chk 13453 [[75, 183, 281, 452], [243, 159, 314, 247], [1, 174, 83, 378], [326, 150, 563, 479], [332, 159, 427, 266], [32, 153, 118, 256], [166, 160, 252, 261]]
Chk 13454 [[366, 116, 539, 385], [249, 226, 348, 366], [47, 109, 239, 356], [0, 201, 62, 341]]
Chk 13455 [[256, 145, 389, 479], [120, 130, 241, 479], [476, 130, 584, 474]]
Chk 13456 [[253, 188, 468, 298], [227, 152, 330, 276], [125, 164, 560, 421]]
Chk 13457 [[264, 14, 470, 351], [424, 76, 593, 368], [19, 55, 345, 435]]
Chk 13458 [[63, 283, 161, 518], [93, 70, 344, 523], [0, 274, 53, 436], [79, 121, 143, 309]]
Chk 13459 [[169, 130, 296, 431], [169, 381, 221, 448], [37, 371, 97, 535], [0, 348, 58, 591], [304, 108, 382, 444], [374, 107, 427, 409], [16, 370, 69, 533], [124, 0, 354, 273]]
Chk 13461 [[393, 74, 522, 448], [233, 91, 381, 467], [49, 112, 216, 450], [378, 26, 446, 104]]
Chk 13462 [[2, 140, 400, 318], [177, 176, 425, 318]]
Chk 13464 [[218, 85, 395, 423], [275, 96, 506, 423], [466, 10, 567, 295], [527, 2, 637, 380]]
Chk 13466 [[25, 1, 350, 354], [360, 1, 639, 351]]
Chk 13467 [[302, 249, 407, 473], [499, 156, 639, 473]]
Chk 13468 [[149, 94, 307, 419], [0, 32, 257, 419]]
Chk 13470 [[55, 104, 619, 422], [260, 0, 479, 427]]
Chk 13471 [[194, 177, 439, 405], [469, 112, 551, 367], [542, 118, 639, 426], [118, 157, 235, 402], [540, 105, 605, 374]]
Chk 13472 [[250, 74, 582, 420], [162, 124, 316, 341], [0, 47, 202, 425], [462, 53, 639, 425]]
Chk 13474 [[53, 9, 240, 415], [228, 114, 330, 409], [277, 127, 442, 386], [443, 51, 639, 406]]
Chk 13475 [[270, 15, 361, 350], [0, 2, 119, 421], [225, 115, 290, 376]]
Chk 13476 [[168, 22, 526, 405], [0, 141, 80, 397], [1, 16, 68, 83]]
Chk 13477 [[73, 156, 158, 332], [378, 136, 578, 458], [431, 228, 639, 462], [226, 27, 375, 449]]
Chk 13479 [[102, 74, 186, 349], [415, 32, 504, 386]]
Chk 13483 [[252, 106, 383, 350], [511, 190, 636, 359], [420, 24, 473, 84]]
Chk 13484 [[186, 9, 407, 494], [0, 69, 255, 499]]

Chk 13486 [[133, 175, 319, 474], [277, 107, 619, 479]]
Chk 13487 [[295, 5, 499, 363], [126, 149, 273, 362]]
Chk 13488 [[53, 36, 247, 429], [174, 16, 407, 482], [205, 59, 606, 413]]
Chk 13489 [[295, 24, 378, 342], [98, 43, 186, 347], [368, 37, 450, 339], [31, 142, 85, 281], [179, 29, 294, 341]]
Chk 13490 [[303, 58, 489, 579], [212, 73, 370, 562]]
Chk 13491 [[1, 19, 93, 236], [49, 14, 295, 239]]
Chk 13492 [[397, 45, 615, 419], [314, 39, 445, 299]]
Chk 13494 [[45, 15, 101, 202], [196, 163, 406, 374], [67, 164, 219, 339]]
Chk 13496 [[304, 141, 435, 440], [108, 119, 255, 472]]
Chk 13497 [[190, 0, 554, 479], [196, 84, 382, 469]]
Chk 13498 [[187, 129, 396, 478], [274, 107, 577, 474]]
Chk 13499 [[43, 141, 276, 638], [223, 93, 427, 589]]
Chk 13500 [[67, 81, 361, 535], [0, 2, 193, 474]]
Chk 13501 [[117, 37, 471, 636], [16, 452, 220, 639]]
Chk 13502 [[88, 186, 346, 473], [262, 64, 542, 479], [588, 227, 639, 472]]
Chk 13503 [[79, 217, 395, 388], [508, 5, 617, 266], [332, 225, 556, 360]]
Chk 13504 [[237, 104, 407, 323], [3, 149, 72, 238], [213, 103, 379, 443], [413, 133, 536, 365], [527, 138, 628, 364], [136, 150, 209, 284], [34, 140, 149, 279]]
Chk 13505 [[255, 201, 406, 428], [439, 125, 513, 318], [139, 192, 248, 354], [72, 209, 279, 472], [364, 217, 471, 410]]
Chk 13508 [[1, 64, 157, 473], [447, 75, 639, 479]]
Chk 13509 [[256, 81, 361, 352], [391, 82, 508, 372]]
Chk 13510 [[129, 72, 480, 355], [254, 1, 639, 354]]
Chk 13511 [[54, 253, 277, 639], [44, 20, 393, 638]]
Chk 13512 [[307, 20, 545, 608], [111, 11, 336, 632]]
Chk 13513 [[14, 21, 309, 472], [269, 109, 523, 471], [291, 60, 355, 183], [543, 46, 604, 169]]
Chk 13517 [[225, 107, 406, 327], [328, 103, 509, 322]]
Chk 13518 [[202, 59, 303, 393], [419, 161, 531, 402], [484, 143, 553, 393], [198, 26, 275, 300]]
Chk 13519 [[201, 121, 335, 500], [303, 124, 401, 498], [370, 122, 481, 401], [77, 127, 232, 499], [387, 108, 591, 501]]
Chk 13520 [[37, 46, 186, 465], [38, 58, 207, 438], [8, 75, 79, 332]]
Chk 13523 [[168, 1, 293, 184], [257, 0, 387, 160], [0, 6, 354, 422], [588, 78, 639, 299]]
Chk 13524 [[96, 83, 305, 379], [297, 92, 483, 394]]
Chk 13525 [[102, 103, 410, 384], [447, 104, 600, 296]]
Chk 13526 [[355, 166, 570, 476], [270, 163, 383, 379], [230, 180, 308, 367], [185, 185, 242, 282], [183, 200, 259, 307], [538, 197, 589, 248], [334, 144, 583, 353]]
Chk 13528 [[26, 96, 211, 303], [171, 63, 277, 236], [337, 62, 451, 198], [449, 74, 507, 207], [419, 57, 639, 474]]
Chk 13529 [[509, 39, 639, 328], [70, 75, 333, 300], [506, 247, 639, 427]]
Chk 13531 [[115, 161, 369, 470], [179, 145, 256, 342], [237, 125, 292, 241], [291, 107, 364, 207], [383, 132, 536, 370], [450, 108, 548, 279]]
Chk 13532 [[125, 41, 383, 423], [578, 192, 639, 315], [426, 89, 618, 452], [0, 64, 255, 443], [287, 67, 533, 452]]
Chk 13533 [[230, 149, 588, 472], [9, 140, 240, 477], [123, 178, 360, 477]]
Chk 13534 [[8, 3, 222, 306], [229, 95, 330, 295], [252, 8, 469, 291]]
Chk 13535 [[222, 289, 413, 635], [66, 390, 248, 639], [153, 189, 339, 455]]
Chk 13536 [[142, 42, 327, 434], [200, 228, 459, 458], [434, 150, 639, 479]]
Chk 13538 [[74, 3, 331, 630], [64, 13, 316, 638]]
Chk 13539 [[56, 51, 324, 328], [294, 150, 374, 263], [285, 71, 449, 346]]
Chk 13541 [[296, 115, 532, 418], [0, 168, 84, 372], [59, 111, 339, 452], [68, 165, 141, 248]]
Chk 13542 [[124, 220, 249, 422], [244, 233, 336, 421], [333, 248, 421, 426]]
Chk 13543 [[405, 41, 624, 280], [143, 0, 391, 280], [0, 25, 184, 280]]
Chk 13544 [[143, 41, 265, 448], [244, 45, 371, 458], [306, 32, 450, 457]]
Chk 13545 [[72, 49, 194, 341], [299, 84, 417, 366]]
Chk 13546 [[1, 1, 310, 332], [243, 38, 499, 332]]
Chk 13547 [[197, 93, 423, 338], [458, 150, 597, 414], [188, 155, 284, 410]]
Chk 13548 [[385, 105, 515, 402], [146, 160, 235, 392]]
Chk 13549 [[261, 43, 506, 422], [15, 209, 220, 426]]
Chk 13551 [[211, 224, 395, 549], [212, 65, 436, 530]]
Chk 13552 [[230, 164, 358, 573], [8, 163, 68, 228], [375, 166, 612, 575]]
Chk 13553 [[348, 77, 591, 313], [0, 77, 116, 252], [165, 55, 378, 398], [410, 276, 638, 474]]
Chk 13554 [[252, 3, 535, 473], [0, 0, 258, 478]]
Chk 13555 [[220, 145, 457, 599], [224, 57, 637, 599]]
Chk 13556 [[55, 28, 297, 474], [107, 1, 373, 474], [232, 70, 315, 403], [449, 0, 631, 474]]
Chk 13558 [[231, 95, 471, 630], [14, 134, 257, 639]]
Chk 13560 [[72, 103, 256, 356], [260, 119, 410, 352]]
Chk 13561 [[325, 24, 639, 417], [10, 43, 336, 419]]
Chk 13562 [[209, 143, 309, 426], [336, 153, 426, 395], [453, 125, 586, 421]]
Chk 13563 [[318, 142, 457, 425], [164, 133, 276, 432], [496, 177, 599, 369]]
Chk 13565 [[461, 98, 637, 409], [346, 47, 552, 342], [422, 134, 562, 254]]
Chk 13566 [[1, 4, 329, 401], [315, 179, 611, 440]]
Chk 13567 [[404, 150, 556, 491], [237, 155, 345, 475], [47, 157, 187, 474]]
Chk 13570 [[0, 121, 185, 413], [140, 190, 441, 479], [152, 80, 335, 364], [293, 81, 401, 295], [353, 102, 475, 279], [492, 105, 639, 283], [450, 82, 522, 215], [379, 93, 487, 217]]
Chk 13571 [[0, 27, 212, 369], [333, 150, 486, 302], [189, 112, 387, 368], [159, 170, 215, 255]]
Chk 13573 [[260, 122, 354, 413], [350, 104, 454, 375]]
Chk 13574 [[411, 130, 523, 440], [225, 128, 385, 295], [69, 21, 222, 278], [496, 116, 577, 228], [191, 89, 264, 234], [568, 80, 628, 220]]
Chk 13575 [[208, 66, 372, 368], [17, 66, 212, 400], [0, 131, 60, 217]]
Chk 13576 [[6, 108, 168, 472], [452, 164, 557, 479], [417, 140, 477, 479], [276, 101, 440, 473]]
Chk 13578 [[230, 36, 505, 622], [0, 50, 282, 585], [18, 39, 173, 402]]
Chk 13579 [[338, 147, 416, 387], [169, 154, 318, 416], [56, 143, 172, 442]]
Chk 13580 [[282, 92, 569, 312], [59, 20, 380, 286]]
Chk 13581 [[312, 92, 445, 398], [366, 58, 551, 360]]
Chk 13582 [[0, 145, 273, 588], [269, 118, 418, 289], [375, 1, 556, 319]]
Chk 13583 [[59, 15, 491, 380], [312, 207, 639, 420], [447, 207, 535, 374], [223, 0, 355, 168]]
Chk 13584 [[57, 178, 261, 551], [179, 177, 341, 558]]
Chk 13585 [[324, 78, 431, 380], [396, 155, 470, 342], [282, 125, 336, 216], [244, 100, 297, 164], [208, 157, 267, 217]]
Chk 13586 [[100, 40, 254, 369], [1, 32, 131, 370], [245, 75, 393, 371], [302, 56, 370, 161], [222, 60, 288, 359]]
Chk 13588 [[353, 201, 455, 609], [151, 141, 336, 536], [7, 278, 181, 490], [1, 117, 157, 457], [106, 217, 267, 474], [420, 374, 479, 551]]
Chk 13589 [[52, 183, 527, 473], [0, 0, 130, 279], [471, 92, 567, 209], [212, 101, 475, 392], [46, 3, 298, 290]]
Chk 13590 [[233, 51, 478, 367], [46, 61, 241, 369]]
Chk 13591 [[170, 250, 305, 456], [38, 194, 153, 546], [322, 220, 395, 443], [277, 257, 328, 355]]
Chk 13593 [[159, 78, 274, 473], [263, 69, 431, 434], [377, 77, 551, 473], [374, 284, 492, 478]]
Chk 13595 [[0, 256, 111, 525], [180, 246, 303, 418], [451, 340, 547, 399]]
Chk 13597 [[210, 105, 335, 407], [277, 129, 361, 400], [343, 98, 463, 392]]
Chk 13598 [[290, 134, 468, 465], [435, 147, 578, 336], [17, 136, 322, 590]]
Chk 13599 [[315, 133, 423, 425], [502, 140, 609, 417], [38, 118, 176, 417], [200, 120, 291, 423]]
Chk 13600 [[203, 69, 303, 424], [284, 58, 378, 405], [361, 64, 462, 417], [450, 41, 576, 406]]
Chk 13601 [[446, 122, 639, 474], [399, 109, 515, 376], [370, 133, 427, 242], [35, 175, 229, 479], [117, 103, 258, 325], [171, 88, 259, 287], [553, 71, 639, 171], [221, 120, 328, 237]]
Chk 13602 [[0, 88, 166, 361], [355, 139, 493, 272], [152, 99, 223, 303], [476, 321, 639, 479], [178, 129, 331, 275], [475, 167, 595, 280], [468, 118, 639, 376]]
Chk 13603 [[265, 43, 443, 255], [90, 55, 274, 313]]
Chk 13604 [[105, 24, 192, 293], [182, 13, 273, 300], [265, 61, 356, 303]]
Chk 13605 [[1, 81, 240, 384], [194, 119, 363, 341], [483, 112, 639, 439]]
Chk 13606 [[311, 118, 408, 372], [453, 84, 576, 397], [582, 106, 639, 321], [546, 179, 600, 311], [22, 88, 73, 162]]
Chk 13607 [[181, 0, 364, 274], [21, 66, 235, 346]]
Chk 13608 [[532, 181, 639, 422], [316, 254, 542, 435], [65, 178, 300, 405], [517, 1, 580, 107], [577, 0, 635, 115]]
Chk 13609 [[113, 97, 410, 418], [343, 107, 608, 426]]
Chk 13610 [[0, 158, 289, 373], [259, 62, 553, 392], [373, 1, 615, 402]]
Chk 13611 [[179, 17, 393, 410], [354, 72, 489, 420], [479, 164, 614, 423], [67, 116, 207, 405], [556, 205, 639, 420]]
Chk 13613 [[1, 62, 415, 621], [338, 53, 636, 625]]
Chk 13615 [[308, 118, 621, 435], [48, 70, 243, 440]]
Chk 13617 [[51, 151, 232, 514], [185, 45, 407, 639]]
Chk 13618 [[434, 290, 580, 495], [226, 134, 400, 389]]
Chk 13619 [[33, 41, 231, 314], [170, 140, 402, 616]]
Chk 13620 [[0, 12, 248, 375], [244, 60, 405, 272], [417, 31, 639, 378]]
Chk 13621 [[306, 164, 477, 424], [471, 131, 601, 421], [137, 145, 326, 421], [0, 107, 115, 421], [584, 238, 639, 421], [58, 128, 185, 420]]

Chk 13622 [[162, 63, 496, 421], [251, 178, 367, 375], [529, 196, 638, 426]]
Chk 13623 [[38, 478, 117, 626], [140, 340, 258, 639], [189, 222, 294, 551], [5, 471, 57, 610]]
Chk 13624 [[19, 20, 152, 538], [123, 45, 371, 535], [294, 35, 591, 595]]
Chk 13625 [[153, 95, 306, 419], [30, 0, 208, 384]]
Chk 13626 [[57, 6, 533, 402], [157, 0, 639, 424]]
Chk 13627 [[194, 89, 422, 421], [508, 0, 639, 427]]
Chk 13629 [[219, 133, 329, 347], [114, 0, 441, 479]]
Chk 13630 [[178, 104, 425, 606], [155, 135, 284, 444]]
Chk 13631 [[0, 0, 119, 370], [125, 133, 249, 368], [273, 116, 409, 373], [407, 88, 524, 383], [492, 159, 598, 386]]
Chk 13633 [[249, 68, 460, 466], [419, 84, 521, 320], [495, 45, 632, 422], [11, 121, 188, 494], [554, 67, 618, 201]]
Chk 13634 [[125, 277, 351, 487], [139, 65, 274, 303]]
Chk 13635 [[81, 184, 255, 454], [247, 176, 388, 453], [263, 152, 588, 453], [458, 163, 598, 446]]
Chk 13636 [[269, 89, 422, 468], [415, 52, 587, 479], [177, 119, 293, 423]]
Chk 13637 [[274, 146, 406, 295], [1, 220, 292, 428], [375, 243, 639, 479]]
Chk 13638 [[150, 78, 301, 428], [364, 76, 512, 424]]
Chk 13639 [[330, 67, 533, 421], [160, 30, 395, 416]]
Chk 13640 [[87, 195, 208, 421], [340, 71, 442, 378]]
Chk 13643 [[0, 36, 366, 386], [208, 9, 434, 271], [488, 3, 638, 266]]
Chk 13644 [[215, 138, 303, 303], [356, 97, 553, 368], [245, 109, 407, 403]]
Chk 13645 [[247, 149, 383, 497], [66, 96, 280, 610]]
Chk 13646 [[274, 221, 422, 405], [120, 173, 194, 410], [136, 198, 294, 632], [411, 164, 510, 404]]
Chk 13647 [[372, 42, 604, 503], [280, 20, 473, 472]]
Chk 13648 [[93, 4, 306, 442], [5, 11, 148, 460]]
Chk 13650 [[172, 54, 330, 447], [346, 35, 468, 437], [439, 116, 596, 470], [0, 188, 56, 402]]
Chk 13651 [[440, 120, 564, 470], [550, 161, 639, 466], [40, 61, 230, 462]]
Chk 13652 [[224, 103, 484, 337], [441, 112, 609, 414], [312, 165, 639, 420], [1, 126, 219, 425], [28, 48, 118, 157], [183, 36, 262, 195], [274, 50, 347, 184]]
Chk 13654 [[471, 96, 639, 295], [349, 88, 534, 305], [240, 89, 460, 350], [35, 7, 311, 376], [556, 127, 639, 291]]
Chk 13655 [[112, 161, 195, 249], [254, 259, 308, 324], [447, 178, 639, 369], [0, 101, 314, 425]]
Chk 13656 [[14, 145, 290, 630], [248, 252, 422, 509]]
Chk 13657 [[143, 156, 502, 632], [50, 76, 290, 631]]
Chk 13658 [[123, 126, 473, 629], [71, 196, 204, 595]]
Chk 13659 [[76, 136, 261, 426], [211, 89, 447, 421]]
Chk 13661 [[261, 62, 455, 327], [109, 73, 265, 327]]
Chk 13663 [[125, 173, 267, 375], [0, 158, 106, 471], [415, 155, 564, 310]]
Chk 13664 [[101, 144, 266, 422], [201, 9, 335, 160], [248, 2, 561, 425]]
Chk 13665 [[254, 171, 367, 470], [462, 148, 540, 335], [324, 267, 581, 472]]
Chk 13666 [[71, 110, 348, 552], [307, 120, 436, 438]]
Chk 13667 [[237, 0, 377, 419], [430, 35, 598, 401], [28, 62, 155, 420], [181, 140, 265, 424]]
Chk 13668 [[490, 148, 607, 317], [181, 50, 337, 219]]
Chk 13669 [[373, 56, 533, 378], [158, 87, 281, 404], [54, 64, 201, 421], [563, 108, 639, 259], [256, 70, 394, 406]]
Chk 13670 [[70, 90, 298, 637], [99, 6, 413, 546]]
Chk 13672 [[0, 126, 228, 587], [306, 220, 511, 569], [274, 143, 466, 250], [151, 241, 256, 444], [334, 282, 522, 591]]
Chk 13673 [[158, 189, 272, 433], [381, 9, 585, 369], [561, 30, 638, 282], [30, 8, 98, 171], [561, 0, 613, 79], [114, 114, 367, 434], [412, 1, 465, 86]]
Chk 13676 [[165, 523, 273, 639], [93, 366, 236, 606], [267, 236, 421, 580], [387, 567, 449, 638]]
Chk 13678 [[327, 31, 480, 419], [171, 37, 291, 443]]
Chk 13679 [[0, 64, 322, 352], [235, 73, 575, 344]]
Chk 13680 [[0, 6, 340, 476], [326, 0, 639, 481]]
Chk 13681 [[194, 45, 427, 421], [430, 10, 617, 398]]
Chk 13682 [[220, 60, 353, 422], [321, 62, 422, 389], [459, 63, 559, 339], [541, 122, 614, 319], [178, 157, 230, 225], [34, 47, 221, 422], [0, 144, 56, 293], [400, 51, 466, 301]]
Chk 13683 [[267, 44, 397, 321], [174, 57, 307, 343], [322, 64, 512, 311], [396, 14, 515, 199], [33, 32, 326, 375]]
Chk 13684 [[160, 119, 357, 386], [0, 281, 239, 374], [512, 78, 639, 420]]
Chk 13685 [[80, 51, 271, 335], [199, 84, 452, 408], [483, 61, 624, 426], [0, 361, 115, 428], [424, 9, 560, 219], [14, 5, 130, 174]]
Chk 13686 [[175, 38, 478, 456], [371, 48, 494, 351]]
Chk 13687 [[216, 422, 344, 638], [79, 254, 275, 631]]
Chk 13688 [[253, 166, 424, 625], [112, 181, 257, 411]]
Chk 13689 [[153, 68, 245, 360], [242, 56, 344, 355], [524, 32, 595, 419]]
Chk 13690 [[362, 74, 522, 231], [119, 209, 369, 581], [0, 1, 213, 490], [249, 68, 376, 228], [501, 68, 632, 432], [156, 6, 226, 221]]
Chk 13691 [[91, 226, 271, 567], [76, 41, 306, 506]]
Chk 13692 [[200, 17, 429, 422], [0, 0, 198, 343]]
Chk 13693 [[0, 36, 207, 420], [65, 61, 250, 287], [257, 27, 431, 317], [381, 9, 639, 420], [256, 27, 337, 184]]
Chk 13695 [[332, 183, 472, 367], [506, 152, 571, 237], [407, 127, 459, 191], [280, 55, 342, 148], [49, 64, 243, 394], [450, 137, 501, 209], [561, 176, 620, 262]]
Chk 13696 [[345, 251, 639, 453], [104, 125, 296, 342], [378, 153, 590, 386]]
Chk 13697 [[158, 26, 247, 310], [201, 139, 298, 411], [396, 139, 483, 254]]
Chk 13698 [[307, 97, 463, 631], [156, 44, 355, 589], [0, 79, 209, 608]]
Chk 13699 [[73, 25, 256, 355], [216, 33, 415, 359], [397, 76, 577, 342]]
Chk 13700 [[352, 111, 603, 404], [48, 96, 265, 326]]
Chk 13701 [[174, 44, 357, 383], [74, 99, 216, 346]]
Chk 13702 [[68, 73, 399, 420], [342, 90, 555, 426]]
Chk 13703 [[289, 73, 468, 325], [191, 116, 319, 351]]
Chk 13704 [[44, 82, 214, 591], [215, 67, 345, 476]]
Chk 13705 [[123, 67, 219, 467], [160, 32, 314, 464], [282, 76, 381, 452], [360, 64, 451, 447]]
Chk 13706 [[190, 118, 368, 354], [470, 205, 635, 363], [446, 72, 501, 142], [0, 110, 53, 313], [588, 152, 639, 294], [171, 43, 249, 100], [497, 0, 576, 97]]
Chk 13707 [[315, 69, 460, 350], [187, 55, 359, 374]]
Chk 13708 [[72, 55, 320, 421], [7, 100, 107, 422]]
Chk 13710 [[355, 219, 611, 603], [369, 239, 443, 370], [0, 282, 108, 571], [415, 306, 476, 369], [311, 277, 375, 363], [95, 247, 161, 377]]
Chk 13711 [[302, 37, 545, 479], [93, 139, 315, 474]]
Chk 13712 [[339, 4, 639, 460], [5, 41, 331, 459], [0, 333, 99, 464]]
Chk 13713 [[203, 102, 501, 421], [72, 40, 215, 421]]
Chk 13715 [[403, 36, 529, 366], [519, 95, 599, 298], [42, 44, 268, 456], [289, 151, 350, 243]]
Chk 13716 [[178, 121, 283, 376], [279, 107, 410, 376]]
Chk 13717 [[186, 130, 298, 426], [2, 71, 205, 418], [289, 155, 383, 422], [355, 115, 424, 235]]
Chk 13718 [[361, 0, 468, 359], [124, 109, 311, 353], [0, 109, 52, 261], [202, 79, 277, 178], [79, 132, 137, 254]]
Chk 13719 [[136, 29, 397, 416], [382, 182, 578, 462]]
Chk 13720 [[0, 207, 102, 437], [331, 160, 513, 409], [42, 0, 120, 96], [79, 261, 290, 449]]
Chk 13721 [[24, 104, 77, 247], [265, 32, 426, 433], [387, 175, 453, 283], [479, 118, 547, 322], [200, 26, 409, 439], [112, 60, 166, 120]]
Chk 13723 [[11, 181, 240, 479], [236, 2, 639, 472]]
Chk 13724 [[312, 81, 461, 294], [476, 37, 587, 209], [341, 74, 624, 272]]
Chk 13725 [[10, 58, 249, 515], [151, 157, 322, 467]]
Chk 13726 [[122, 30, 323, 473], [306, 153, 455, 472], [488, 19, 639, 473], [583, 124, 639, 479]]
Chk 13728 [[336, 30, 486, 368], [290, 25, 398, 307], [244, 53, 326, 302], [107, 28, 237, 334]]
Chk 13729 [[109, 88, 255, 422], [382, 60, 519, 422], [254, 86, 392, 427]]
Chk 13730 [[244, 115, 467, 632], [17, 113, 293, 632]]
Chk 13732 [[6, 56, 276, 511], [299, 198, 504, 500]]
Chk 13733 [[38, 20, 447, 384], [165, 70, 384, 240]]
Chk 13735 [[58, 60, 291, 526], [191, 215, 307, 435]]
Chk 13736 [[0, 91, 163, 370], [156, 4, 358, 370], [296, 54, 496, 368], [115, 79, 231, 368], [270, 32, 490, 340]]
Chk 13737 [[231, 192, 479, 361], [122, 399, 405, 639]]
Chk 13738 [[402, 4, 610, 334], [31, 108, 191, 347], [433, 59, 488, 144], [251, 56, 304, 127], [198, 100, 327, 297], [163, 67, 246, 302], [312, 44, 443, 309], [244, 8, 337, 102]]
Chk 13739 [[111, 26, 330, 510], [317, 198, 624, 509]]
Chk 13740 [[37, 0, 462, 421], [302, 49, 639, 423]]
Chk 13741 [[104, 257, 384, 626], [130, 37, 312, 391]]
Chk 13743 [[82, 103, 290, 423], [503, 88, 639, 417], [272, 125, 433, 421], [341, 105, 515, 419], [39, 223, 125, 423]]
Chk 13744 [[129, 251, 211, 505], [0, 245, 109, 539], [302, 210, 438, 639]]
Chk 13745 [[84, 106, 203, 498], [2, 87, 205, 493]]
Chk 13746 [[111, 131, 274, 471], [483, 228, 639, 479], [252, 161, 376, 479], [350, 167, 420, 402], [543, 152, 607, 242]]

Chk 13747 [[140, 80, 282, 377], [507, 98, 637, 421], [93, 154, 220, 335], [326, 77, 534, 347], [47, 63, 206, 382], [494, 100, 590, 426]]
Chk 13748 [[416, 197, 584, 434], [200, 60, 319, 320], [250, 229, 475, 435], [77, 162, 312, 434]]
Chk 13749 [[0, 183, 192, 608], [166, 224, 266, 397], [394, 193, 513, 443], [366, 222, 432, 338], [559, 218, 611, 297]]
Chk 13752 [[0, 3, 315, 426], [131, 61, 270, 426], [250, 44, 440, 422]]
Chk 13753 [[195, 1, 637, 466], [201, 0, 488, 350]]
Chk 13754 [[222, 129, 631, 473], [0, 0, 566, 473]]
Chk 13755 [[1, 199, 190, 474], [268, 249, 334, 479], [210, 267, 287, 469], [307, 254, 451, 474]]
Chk 13756 [[273, 137, 443, 431], [58, 115, 317, 455], [17, 4, 193, 304], [198, 1, 282, 186], [448, 0, 638, 473]]
Chk 13757 [[214, 108, 357, 345], [366, 244, 557, 426]]
Chk 13759 [[276, 181, 612, 473], [1, 163, 246, 472], [132, 114, 331, 394]]
Chk 13760 [[444, 236, 639, 473], [22, 261, 192, 472]]
Chk 13761 [[200, 169, 412, 423], [35, 193, 235, 424]]
Chk 13762 [[280, 160, 341, 313], [160, 242, 335, 472], [362, 173, 443, 393], [112, 168, 188, 266], [34, 228, 97, 337], [459, 182, 534, 421], [47, 225, 190, 440], [539, 371, 639, 478]]
Chk 13763 [[142, 69, 375, 420], [112, 28, 572, 417]]
Chk 13764 [[5, 35, 369, 253], [100, 169, 582, 479], [330, 77, 427, 191], [161, 127, 501, 314]]
Chk 13765 [[153, 116, 222, 302], [417, 120, 537, 332], [167, 207, 276, 348], [295, 129, 364, 313], [342, 96, 442, 322], [222, 110, 316, 316]]
Chk 13766 [[288, 236, 375, 353], [338, 167, 426, 288], [171, 307, 302, 479], [399, 184, 530, 332], [164, 165, 263, 283], [3, 192, 137, 422], [97, 180, 201, 319], [468, 204, 633, 404]]
Chk 13768 [[400, 64, 499, 326], [263, 113, 370, 273], [0, 97, 145, 321], [149, 120, 201, 224], [81, 131, 216, 320]]
Chk 13770 [[293, 27, 439, 328], [432, 1, 499, 327], [149, 82, 257, 327], [26, 76, 124, 332]]
Chk 13771 [[25, 15, 244, 317], [134, 63, 213, 165], [291, 25, 499, 370], [200, 74, 256, 129], [0, 143, 83, 355]]
Chk 13772 [[0, 149, 112, 254], [232, 21, 364, 202], [388, 21, 545, 242], [523, 17, 639, 270], [389, 59, 454, 124], [0, 219, 130, 347]]
Chk 13774 [[310, 203, 553, 469], [327, 153, 460, 330], [62, 182, 180, 324], [48, 67, 164, 284], [0, 146, 103, 435], [253, 169, 349, 278]]
Chk 13775 [[72, 40, 215, 312], [142, 182, 343, 362]]
Chk 13777 [[66, 70, 200, 451], [81, 66, 345, 445], [329, 110, 479, 432], [409, 50, 587, 420]]
Chk 13778 [[183, 308, 322, 576], [107, 254, 243, 580]]
Chk 13779 [[127, 181, 368, 479], [103, 121, 518, 472]]
Chk 13780 [[15, 96, 297, 420], [352, 42, 632, 424], [207, 107, 399, 420]]
Chk 13781 [[165, 138, 360, 394], [343, 71, 553, 403]]
Chk 13782 [[133, 28, 326, 548], [215, 110, 451, 619], [51, 102, 272, 490]]
Chk 13783 [[52, 42, 350, 464], [265, 52, 542, 465]]
Chk 13784 [[106, 233, 259, 453], [160, 77, 258, 250], [236, 232, 354, 413]]
Chk 13785 [[0, 78, 371, 505], [271, 85, 611, 611]]
Chk 13786 [[108, 18, 358, 365], [427, 44, 594, 284]]
Chk 13788 [[501, 116, 567, 401], [426, 120, 514, 394], [360, 85, 419, 385], [197, 161, 256, 306], [0, 178, 68, 344], [374, 131, 459, 396]]
Chk 13789 [[338, 0, 397, 120], [483, 91, 639, 417], [210, 2, 290, 133], [247, 117, 537, 371], [5, 149, 347, 391]]
Chk 13791 [[278, 139, 336, 249], [487, 85, 579, 351]]
Chk 13792 [[0, 25, 201, 485], [210, 7, 388, 476], [455, 1, 639, 490]]
Chk 13793 [[124, 180, 215, 478], [242, 190, 397, 587]]
Chk 13795 [[39, 0, 195, 331], [273, 114, 434, 328], [205, 184, 278, 332], [1, 209, 58, 328]]
Chk 13796 [[136, 91, 320, 258], [333, 42, 558, 408]]
Chk 13798 [[409, 66, 530, 271], [285, 82, 471, 329], [535, 20, 639, 279], [176, 14, 242, 203], [436, 17, 497, 148], [234, 22, 296, 214]]
Chk 13799 [[16, 124, 151, 449], [75, 158, 404, 510], [113, 84, 228, 424]]
Chk 13803 [[301, 96, 466, 385], [426, 68, 499, 200], [425, 0, 639, 422], [209, 17, 361, 371], [105, 35, 219, 387], [0, 31, 136, 417], [237, 1, 307, 94], [62, 188, 158, 283]]
Chk 13804 [[280, 24, 613, 354], [548, 63, 639, 354]]
Chk 13805 [[0, 93, 170, 571], [312, 115, 482, 519]]
Chk 13806 [[108, 248, 374, 391], [1, 3, 228, 436], [109, 67, 368, 403]]
Chk 13807 [[152, 1, 450, 476], [406, 47, 554, 369]]
Chk 13808 [[421, 109, 590, 348], [69, 51, 224, 287]]
Chk 13809 [[1, 89, 289, 381], [485, 126, 636, 379]]
Chk 13810 [[0, 1, 191, 387], [169, 42, 356, 381], [407, 87, 506, 380], [314, 90, 471, 387], [501, 142, 639, 384]]
Chk 13812 [[2, 7, 181, 499], [124, 100, 235, 499], [292, 159, 374, 442], [208, 157, 284, 427]]
Chk 13813 [[59, 115, 229, 359], [365, 128, 447, 354], [273, 130, 378, 354], [252, 15, 600, 353]]
Chk 13814 [[249, 77, 634, 535], [7, 2, 393, 527]]
Chk 13815 [[319, 54, 560, 440], [3, 14, 276, 454]]
Chk 13816 [[357, 50, 526, 471], [202, 77, 392, 472]]
Chk 13817 [[406, 139, 497, 408], [224, 58, 391, 422], [0, 22, 249, 422]]
Chk 13818 [[0, 99, 151, 446], [1, 107, 399, 472]]
Chk 13819 [[16, 40, 490, 427], [340, 152, 483, 308], [502, 197, 639, 342], [473, 223, 531, 275]]
Chk 13820 [[84, 17, 145, 103], [0, 225, 154, 407], [161, 75, 408, 407], [133, 19, 202, 100], [189, 0, 284, 100], [242, 27, 311, 100], [1, 0, 54, 104], [400, 15, 484, 91]]
Chk 13822 [[107, 27, 341, 639], [365, 140, 479, 469]]
Chk 13824 [[1, 64, 271, 486], [230, 104, 571, 363]]
Chk 13825 [[237, 272, 455, 586], [39, 124, 149, 261], [146, 135, 383, 544]]
Chk 13827 [[217, 188, 479, 632], [220, 138, 479, 631]]
Chk 13828 [[290, 25, 496, 425], [84, 31, 341, 437], [464, 0, 528, 95], [575, 4, 639, 135], [142, 1, 200, 153]]
Chk 13830 [[111, 50, 345, 355], [1, 177, 107, 354], [73, 2, 141, 204], [139, 6, 201, 106], [507, 162, 581, 349], [35, 107, 88, 188]]
Chk 13831 [[413, 428, 479, 639], [389, 403, 462, 613], [86, 315, 145, 402], [314, 344, 387, 510], [0, 343, 93, 630], [53, 317, 164, 504], [0, 253, 99, 387]]
Chk 13832 [[0, 109, 97, 471], [84, 105, 294, 478], [247, 125, 356, 276], [333, 103, 448, 290], [433, 119, 561, 301], [587, 179, 639, 307]]
Chk 13833 [[151, 17, 346, 441], [369, 22, 531, 438]]
Chk 13834 [[1, 116, 216, 393], [0, 102, 78, 234], [396, 129, 639, 423]]
Chk 13835 [[131, 158, 189, 265], [222, 101, 325, 374], [327, 107, 504, 401]]
Chk 13836 [[101, 103, 235, 370], [241, 95, 448, 370], [180, 154, 245, 374], [0, 220, 63, 348], [426, 136, 499, 373], [0, 202, 64, 353]]
Chk 13837 [[307, 123, 513, 355], [268, 149, 396, 354]]
Chk 13838 [[287, 91, 591, 402], [166, 113, 336, 404]]
Chk 13839 [[250, 104, 479, 621], [87, 102, 171, 303], [0, 126, 179, 622]]
Chk 13840 [[0, 31, 114, 535], [144, 32, 310, 533], [254, 91, 478, 535]]
Chk 13841 [[121, 54, 327, 314], [244, 2, 636, 444]]
Chk 13843 [[155, 132, 292, 374], [0, 26, 89, 274], [353, 0, 421, 118], [57, 0, 228, 285]]
Chk 13844 [[44, 137, 293, 639], [165, 170, 376, 574]]
Chk 13845 [[439, 20, 499, 267], [316, 44, 423, 288], [183, 44, 305, 314], [58, 73, 166, 329], [0, 127, 78, 322]]
Chk 13846 [[90, 61, 356, 448], [363, 99, 639, 527]]
Chk 13848 [[37, 57, 218, 511], [212, 51, 316, 223], [349, 56, 427, 218], [204, 220, 466, 556]]
Chk 13849 [[461, 178, 624, 407], [309, 143, 568, 352], [344, 133, 473, 320], [187, 85, 342, 281], [20, 128, 146, 300]]
Chk 13850 [[158, 208, 345, 423], [0, 53, 217, 467]]
Chk 13851 [[107, 116, 214, 491], [10, 146, 163, 496], [246, 203, 306, 307], [269, 116, 374, 410], [87, 114, 145, 390]]
Chk 13853 [[297, 65, 424, 396], [0, 204, 112, 479], [465, 326, 639, 479], [519, 215, 631, 334]]
Chk 13857 [[335, 142, 516, 408], [146, 209, 271, 400], [314, 174, 379, 325], [216, 189, 302, 301], [48, 231, 123, 322], [103, 115, 156, 171], [0, 99, 74, 395]]
Chk 13858 [[0, 92, 499, 370], [8, 80, 199, 243]]
Chk 13859 [[334, 0, 603, 453], [35, 54, 299, 447]]
Chk 13860 [[1, 1, 158, 237], [0, 33, 464, 428]]
Chk 13861 [[43, 74, 234, 631], [214, 123, 438, 603]]
Chk 13864 [[392, 207, 598, 532], [38, 0, 271, 495]]
Chk 13865 [[387, 15, 589, 526], [188, 50, 352, 523]]
Chk 13866 [[119, 359, 344, 532], [440, 320, 797, 527], [388, 75, 588, 519], [184, 116, 435, 532], [145, 157, 288, 505]]
Chk 13867 [[0, 123, 279, 494], [175, 85, 561, 507], [391, 134, 800, 552]]
Chk 13868 [[399, 29, 781, 532], [0, 46, 320, 532]]
Chk 13869 [[0, 72, 316, 573], [266, 38, 533, 800]]
Chk 13870 [[0, 15, 165, 365], [239, 21, 434, 344], [426, 68, 470, 147]]
Chk 13871 [[344, 496, 466, 787], [70, 468, 165, 785]]
Chk 13872 [[489, 48, 685, 440], [10, 101, 143, 436], [369, 83, 555, 434], [258, 104, 400, 366], [418, 377, 645, 448]]
Chk 13873 [[465, 175, 773, 515], [191, 179, 428, 483], [159, 4, 269, 154]]
Chk 13874 [[106, 94, 418, 334], [456, 0, 639, 359]]
Chk 13875 [[163, 155, 307, 695], [255, 61, 490, 792], [491, 169, 529, 302], [38, 256, 174, 551]]
Chk 13876 [[0, 3, 90, 181], [197, 13, 300, 180]]
Chk 13878 [[42, 142, 252, 773], [153, 112, 306, 703]]
Chk 13879 [[99, 152, 406, 788], [11, 10, 278, 588]]

Chk 13881 [[408, 27, 762, 532], [15, 114, 382, 522], [696, 127, 799, 532]]
Chk 13883 [[457, 141, 602, 532], [384, 193, 490, 532]]
Chk 13884 [[51, 171, 375, 488], [0, 0, 204, 478]]
Chk 13886 [[368, 317, 455, 566], [269, 272, 396, 567]]
Chk 13887 [[100, 109, 505, 600], [219, 0, 800, 600]]
Chk 13888 [[39, 122, 302, 780], [135, 152, 522, 795]]
Chk 13890 [[256, 128, 790, 593], [54, 90, 447, 600]]
Chk 13891 [[463, 59, 657, 360], [162, 72, 352, 353]]
Chk 13892 [[358, 101, 555, 519], [511, 110, 753, 532]]
Chk 13893 [[45, 57, 462, 531], [326, 95, 648, 531], [729, 108, 799, 350], [545, 81, 753, 456], [690, 62, 749, 161], [282, 103, 416, 257]]
Chk 13894 [[180, 85, 522, 732], [55, 80, 343, 704]]
Chk 13895 [[53, 48, 452, 607], [414, 50, 768, 607]]
Chk 13896 [[287, 116, 461, 525], [146, 117, 298, 532], [576, 151, 672, 415], [515, 134, 588, 376]]
Chk 13897 [[19, 6, 320, 494], [114, 208, 301, 446]]
Chk 13898 [[566, 104, 684, 370], [430, 100, 558, 493]]
Chk 13899 [[23, 117, 467, 573], [410, 65, 587, 564], [451, 129, 782, 562]]
Chk 13900 [[71, 107, 285, 477], [309, 97, 407, 215], [474, 57, 629, 458], [395, 73, 483, 223], [8, 91, 77, 216], [71, 72, 168, 195], [685, 76, 760, 196]]
Chk 13901 [[25, 25, 195, 478], [255, 39, 374, 483]]
Chk 13902 [[522, 203, 785, 597], [326, 213, 608, 591], [88, 29, 281, 310]]
Chk 13903 [[239, 24, 728, 525], [25, 48, 388, 533]]
Chk 13904 [[446, 26, 542, 133], [40, 96, 637, 582], [428, 145, 767, 543]]
Chk 13906 [[100, 34, 295, 757], [227, 94, 402, 781]]
Chk 13908 [[51, 224, 364, 577], [91, 41, 516, 579]]
Chk 13909 [[273, 53, 361, 231], [20, 6, 480, 309]]
Chk 13910 [[0, 43, 229, 310], [172, 73, 351, 333], [266, 30, 500, 316]]
Chk 13911 [[208, 18, 531, 487], [17, 106, 270, 505]]
Chk 13912 [[143, 62, 313, 334], [283, 107, 383, 322], [364, 50, 518, 328]]
Chk 13913 [[463, 103, 747, 545], [227, 28, 548, 537]]
Chk 13914 [[105, 84, 412, 333], [139, 10, 435, 333]]
Chk 13915 [[0, 0, 440, 527], [185, 129, 549, 473]]
Chk 13916 [[5, 142, 317, 494], [81, 62, 751, 473], [470, 101, 790, 462]]
Chk 13917 [[528, 114, 659, 505], [58, 75, 237, 507], [109, 79, 177, 150]]
Chk 13918 [[28, 44, 304, 569], [478, 60, 782, 570]]
Chk 13919 [[199, 160, 461, 436], [92, 133, 320, 403]]
Chk 13920 [[15, 73, 290, 442], [516, 93, 646, 277], [566, 63, 799, 332], [397, 131, 455, 247], [297, 127, 338, 183], [341, 124, 389, 179], [232, 72, 275, 164], [426, 123, 467, 239]]
Chk 13921 [[381, 141, 567, 581], [53, 197, 310, 445], [615, 53, 799, 407]]
Chk 13923 [[124, 45, 212, 319], [378, 16, 455, 312], [217, 79, 300, 342], [297, 46, 369, 337], [450, 58, 496, 346], [457, 48, 499, 194]]
Chk 13925 [[361, 121, 710, 529], [63, 72, 405, 529]]
Chk 13926 [[53, 6, 212, 500], [210, 24, 374, 500]]
Chk 13928 [[131, 77, 384, 612], [5, 196, 162, 391], [472, 66, 725, 611]]
Chk 13929 [[22, 23, 496, 529], [362, 44, 669, 513]]
Chk 13930 [[7, 69, 174, 370], [236, 54, 492, 368]]
Chk 13932 [[6, 48, 478, 529], [370, 14, 782, 534]]
Chk 13933 [[276, 212, 382, 386], [329, 107, 464, 358], [684, 69, 788, 283]]
Chk 13934 [[128, 134, 364, 529], [286, 128, 609, 527]]
Chk 13935 [[27, 78, 206, 439], [157, 69, 300, 453]]
Chk 13936 [[120, 156, 499, 483], [33, 173, 260, 471]]
Chk 13937 [[300, 106, 382, 378], [351, 81, 456, 383]]
Chk 13938 [[400, 191, 544, 517], [307, 136, 439, 508]]
Chk 13939 [[320, 106, 731, 542], [83, 76, 403, 509]]
Chk 13940 [[438, 118, 793, 535], [7, 128, 410, 521]]
Chk 13941 [[104, 101, 375, 490], [365, 96, 516, 496]]
Chk 13942 [[224, 142, 384, 793], [0, 9, 283, 783]]
Chk 13943 [[8, 14, 187, 418], [263, 27, 420, 474], [192, 78, 302, 499]]
Chk 13944 [[132, 198, 498, 491], [343, 188, 462, 404], [486, 225, 534, 298], [725, 232, 800, 594]]
Chk 13945 [[415, 145, 582, 436], [6, 16, 50, 100], [203, 99, 340, 389], [245, 6, 289, 71], [76, 24, 184, 120]]
Chk 13946 [[27, 154, 168, 443], [0, 300, 317, 531], [152, 113, 347, 361], [344, 146, 513, 353], [585, 85, 800, 522], [480, 12, 538, 80]]
Chk 13947 [[104, 146, 269, 558], [199, 151, 471, 559]]
Chk 13948 [[72, 102, 182, 519], [126, 95, 175, 216], [493, 121, 764, 573]]
Chk 13949 [[152, 74, 429, 480], [386, 52, 591, 459], [440, 0, 502, 143]]
Chk 13950 [[28, 94, 508, 484], [329, 1, 666, 422]]
Chk 13951 [[23, 24, 560, 664], [194, 294, 484, 631]]
Chk 13952 [[442, 12, 702, 441], [164, 39, 362, 457], [335, 197, 478, 417]]
Chk 13953 [[427, 132, 758, 464], [126, 40, 436, 434]]
Chk 13954 [[10, 53, 364, 549], [194, 89, 540, 533]]
Chk 13955 [[380, 0, 800, 530], [12, 39, 392, 532]]
Chk 13956 [[0, 45, 254, 368], [0, 30, 377, 367], [304, 106, 472, 368]]
Chk 13957 [[0, 14, 181, 341], [187, 102, 394, 324], [130, 0, 500, 354]]
Chk 13958 [[15, 37, 487, 159], [0, 77, 469, 334]]
Chk 13959 [[57, 88, 406, 367], [263, 27, 446, 319]]
Chk 13960 [[385, 115, 549, 527], [498, 109, 633, 486]]
Chk 13961 [[127, 1, 394, 530], [319, 197, 735, 525], [9, 7, 259, 532], [5, 13, 124, 463]]
Chk 13962 [[333, 300, 427, 455], [61, 350, 247, 588]]
Chk 13963 [[1, 62, 117, 394], [361, 16, 571, 513], [163, 49, 289, 405], [187, 21, 453, 453], [737, 103, 795, 297]]
Chk 13964 [[111, 11, 269, 322], [251, 13, 451, 358], [406, 71, 492, 367]]
Chk 13965 [[0, 63, 296, 531], [231, 57, 795, 533]]
Chk 13966 [[105, 4, 341, 280], [29, 0, 262, 281]]
Chk 13967 [[0, 33, 678, 595], [213, 263, 777, 590]]
Chk 13968 [[63, 49, 350, 558], [366, 151, 665, 560], [608, 32, 755, 458], [443, 61, 543, 174]]
Chk 13969 [[172, 80, 310, 307], [10, 171, 293, 530], [362, 80, 502, 295], [583, 132, 799, 524], [483, 100, 654, 515], [0, 89, 47, 224], [37, 210, 153, 319], [10, 191, 182, 388]]
Chk 13970 [[433, 267, 502, 433], [663, 281, 732, 426], [524, 284, 589, 432]]
Chk 13971 [[137, 17, 494, 532], [358, 0, 695, 532]]
Chk 13973 [[477, 107, 625, 511], [59, 72, 188, 523]]
Chk 13974 [[2, 52, 404, 563], [458, 10, 799, 563]]
Chk 13975 [[32, 64, 380, 593], [380, 112, 629, 595]]
Chk 13976 [[628, 87, 745, 302], [377, 11, 522, 466], [524, 81, 612, 241], [102, 18, 246, 390], [240, 49, 398, 267], [130, 44, 441, 448]]
Chk 13978 [[107, 158, 338, 575], [214, 160, 354, 426], [510, 165, 733, 475], [448, 161, 616, 309]]
Chk 13979 [[3, 74, 280, 496], [181, 9, 442, 496]]
Chk 13980 [[75, 176, 369, 529], [529, 177, 750, 512], [375, 131, 532, 368]]
Chk 13981 [[300, 100, 724, 532], [79, 100, 423, 532]]
Chk 13982 [[172, 226, 378, 491], [36, 27, 225, 479]]
Chk 13983 [[349, 15, 525, 573], [722, 46, 799, 315], [624, 69, 710, 320], [28, 64, 239, 574], [525, 61, 625, 269], [214, 292, 348, 569]]
Chk 13984 [[0, 149, 303, 512], [338, 181, 665, 466]]
Chk 13985 [[525, 363, 693, 532], [313, 335, 521, 532], [186, 312, 332, 532]]
Chk 13986 [[19, 37, 539, 533], [81, 126, 198, 304], [389, 138, 442, 230], [497, 6, 800, 533]]
Chk 13987 [[224, 436, 423, 587], [29, 508, 508, 779]]
Chk 13988 [[271, 140, 398, 549], [176, 144, 290, 545]]
Chk 13989 [[138, 245, 259, 517], [443, 225, 506, 375]]
Chk 13990 [[113, 106, 216, 375], [216, 114, 330, 375], [0, 129, 98, 374]]
Chk 13991 [[161, 86, 403, 456], [213, 112, 615, 523]]
Chk 13992 [[87, 131, 378, 523], [333, 106, 678, 493]]
Chk 13993 [[280, 66, 396, 298], [71, 60, 163, 299], [5, 81, 126, 295]]
Chk 13994 [[431, 256, 631, 595], [217, 273, 379, 599]]
Chk 13997 [[194, 107, 343, 521], [329, 140, 533, 530]]
Chk 13998 [[269, 479, 432, 702], [20, 476, 165, 733]]
Chk 13999 [[132, 100, 509, 524], [488, 60, 797, 525], [9, 9, 307, 534]]
Chk 14000 [[129, 132, 427, 533], [407, 106, 735, 533], [733, 161, 779, 316], [646, 65, 698, 244], [355, 53, 415, 219]]
Chk 14001 [[531, 261, 768, 598], [10, 176, 204, 599]]
Chk 14002 [[38, 5, 483, 600], [310, 36, 649, 573], [513, 74, 739, 501]]
Chk 14003 [[17, 37, 194, 377], [311, 98, 557, 440]]
Chk 14004 [[159, 69, 458, 504], [217, 76, 604, 528]]
Chk 14005 [[106, 295, 273, 527], [389, 155, 639, 530], [244, 197, 446, 532], [11, 284, 147, 500], [705, 269, 784, 411]]
Chk 14006 [[148, 0, 424, 366], [19, 190, 509, 599]]
Chk 14007 [[199, 92, 329, 330], [65, 96, 184, 349]]
Chk 14008 [[333, 64, 539, 527], [442, 59, 715, 533]]
Chk 14009 [[166, 136, 291, 506], [461, 41, 617, 534]]
Chk 14011 [[68, 55, 368, 566], [454, 130, 780, 573]]
Chk 14012 [[433, 193, 573, 539], [547, 246, 752, 573]]
Chk 14014 [[506, 127, 734, 592], [38, 97, 315, 520], [247, 213, 532, 559]]
Chk 14016 [[413, 72, 669, 531], [0, 45, 169, 522], [137, 0, 448, 531], [580, 104, 799, 522], [422, 98, 474, 255]]

Chk 14017 [[220, 70, 363, 334], [423, 113, 494, 326], [341, 60, 436, 334], [142, 151, 194, 265], [181, 157, 224, 244]]
Chk 14020 [[242, 0, 577, 799], [204, 127, 353, 787]]
Chk 14022 [[67, 25, 460, 569], [378, 6, 708, 557]]
Chk 14023 [[290, 28, 679, 532], [0, 1, 340, 533]]
Chk 14024 [[418, 45, 756, 579], [21, 115, 269, 579]]
Chk 14025 [[305, 22, 797, 534], [0, 12, 370, 516]]
Chk 14027 [[96, 39, 289, 794], [114, 58, 462, 800]]
Chk 14028 [[252, 244, 421, 489], [451, 129, 664, 498]]
Chk 14029 [[36, 141, 116, 352], [112, 143, 207, 356]]
Chk 14031 [[125, 87, 348, 577], [329, 55, 791, 609], [662, 369, 743, 543], [5, 397, 80, 561], [628, 88, 779, 606]]
Chk 14032 [[29, 15, 102, 259], [220, 30, 450, 332], [92, 35, 262, 330]]
Chk 14033 [[17, 104, 488, 325], [264, 41, 458, 332], [431, 107, 499, 332]]
Chk 14034 [[237, 97, 321, 363], [513, 111, 619, 411], [342, 92, 507, 408], [106, 69, 220, 415], [328, 77, 394, 402]]
Chk 14035 [[276, 96, 443, 348], [63, 149, 252, 329]]
Chk 14039 [[7, 48, 323, 374], [206, 63, 474, 374], [421, 230, 499, 374]]
Chk 14040 [[138, 151, 338, 460], [16, 181, 105, 412]]
Chk 14042 [[110, 24, 424, 297], [465, 8, 799, 497]]
Chk 14043 [[224, 75, 566, 478], [464, 44, 791, 637]]
Chk 14044 [[0, 103, 413, 669], [357, 108, 799, 670], [294, 138, 418, 378]]
Chk 14045 [[538, 52, 748, 448], [37, 30, 230, 433]]
Chk 14046 [[343, 128, 506, 510], [278, 178, 338, 259], [52, 261, 111, 363], [569, 117, 772, 504]]
Chk 14047 [[429, 156, 552, 399], [213, 175, 339, 475]]
Chk 14048 [[23, 139, 619, 600], [491, 38, 800, 600]]
Chk 14049 [[0, 15, 119, 434], [63, 52, 291, 689], [280, 21, 530, 765], [508, 56, 575, 210], [88, 59, 146, 153], [244, 66, 285, 132], [461, 35, 504, 120]]
Chk 14050 [[419, 188, 650, 456], [191, 240, 445, 562]]
Chk 14051 [[16, 259, 237, 800], [209, 238, 362, 795], [232, 231, 508, 800]]
Chk 14052 [[87, 48, 401, 367], [391, 47, 617, 419]]
Chk 14053 [[216, 206, 343, 507], [422, 253, 547, 483]]
Chk 14054 [[378, 4, 548, 365], [68, 48, 240, 363], [189, 25, 379, 363]]
Chk 14056 [[0, 0, 265, 326], [212, 10, 499, 332], [132, 71, 274, 277]]
Chk 14057 [[164, 98, 439, 525], [426, 10, 775, 542]]
Chk 14058 [[0, 53, 174, 401], [56, 209, 259, 515]]
Chk 14059 [[0, 54, 162, 281], [107, 1, 300, 273], [303, 82, 500, 281]]
Chk 14060 [[1, 1, 271, 590], [275, 273, 506, 593]]
Chk 14062 [[215, 251, 377, 440], [2, 284, 253, 569], [31, 236, 98, 323]]
Chk 14063 [[9, 109, 197, 532], [199, 80, 339, 532], [382, 90, 591, 525], [546, 233, 702, 518]]
Chk 14064 [[327, 31, 499, 374], [181, 103, 325, 373], [8, 11, 210, 374]]
Chk 14065 [[17, 222, 155, 533], [399, 234, 543, 533], [198, 226, 369, 533]]
Chk 14066 [[268, 207, 460, 599], [100, 190, 320, 599], [430, 121, 664, 588], [272, 143, 346, 235]]
Chk 14067 [[235, 253, 405, 528], [61, 209, 229, 523]]
Chk 14068 [[161, 189, 241, 427], [201, 190, 280, 417]]
Chk 14069 [[94, 385, 274, 529], [382, 275, 576, 412], [374, 0, 776, 529]]
Chk 14070 [[0, 34, 573, 532], [376, 158, 640, 515]]
Chk 14071 [[496, 23, 589, 295], [388, 25, 492, 272]]
Chk 14072 [[445, 142, 608, 482], [213, 151, 368, 486], [355, 134, 486, 482]]
Chk 14073 [[218, 2, 426, 287], [193, 53, 321, 230]]
Chk 14074 [[133, 202, 325, 800], [297, 242, 532, 800]]
Chk 14076 [[437, 218, 501, 479], [402, 173, 515, 460]]
Chk 14077 [[118, 167, 479, 762], [290, 142, 603, 780]]
Chk 14078 [[3, 35, 109, 372], [179, 92, 391, 523], [391, 17, 503, 261], [432, 116, 730, 633], [699, 65, 799, 387]]
Chk 14080 [[495, 371, 599, 650], [567, 350, 666, 550]]
Chk 14082 [[151, 186, 431, 532], [368, 190, 722, 532]]
Chk 14083 [[0, 0, 582, 531], [307, 160, 516, 427], [481, 0, 800, 531]]
Chk 14084 [[178, 13, 530, 532], [364, 57, 716, 503]]
Chk 14085 [[39, 39, 407, 600], [453, 57, 777, 600]]
Chk 14086 [[238, 138, 332, 415], [148, 184, 235, 414], [88, 175, 179, 445]]
Chk 14087 [[413, 285, 492, 473], [562, 252, 641, 488]]
Chk 14088 [[441, 357, 548, 560], [322, 353, 472, 601]]
Chk 14089 [[416, 39, 787, 540], [352, 77, 567, 508]]
Chk 14090 [[43, 193, 194, 499], [126, 37, 327, 487]]
Chk 14091 [[430, 91, 626, 599], [348, 287, 471, 582], [72, 346, 223, 599]]
Chk 14092 [[64, 19, 234, 374], [243, 18, 417, 374]]
Chk 14094 [[203, 163, 331, 415], [432, 165, 608, 410]]
Chk 14095 [[18, 64, 388, 799], [160, 39, 528, 696]]
Chk 14096 [[277, 63, 492, 371], [289, 82, 332, 145], [75, 67, 398, 371], [421, 8, 499, 239], [195, 78, 346, 315]]
Chk 14097 [[0, 21, 468, 553], [398, 100, 597, 540]]
Chk 14098 [[0, 65, 364, 534], [446, 86, 800, 534]]
Chk 14099 [[266, 133, 478, 620], [56, 111, 422, 637]]
Chk 14100 [[0, 158, 374, 599], [578, 115, 793, 599]]
Chk 14101 [[21, 105, 397, 525], [311, 17, 728, 520], [713, 294, 759, 425]]
Chk 14102 [[102, 61, 230, 451], [319, 86, 548, 451], [591, 71, 768, 451]]
Chk 14103 [[100, 163, 356, 599], [303, 197, 454, 599]]
Chk 14104 [[0, 173, 376, 600], [192, 128, 417, 466], [398, 123, 540, 370], [580, 123, 736, 334]]
Chk 14105 [[0, 132, 87, 344], [84, 47, 377, 439], [509, 0, 800, 579]]
Chk 14106 [[253, 162, 533, 799], [199, 223, 386, 799], [0, 351, 119, 776]]
Chk 14107 [[153, 289, 304, 481], [85, 169, 331, 448]]
Chk 14108 [[5, 62, 127, 358], [112, 78, 215, 356], [200, 48, 310, 452]]
Chk 14110 [[203, 65, 494, 498], [332, 120, 661, 544]]
Chk 14111 [[201, 160, 585, 528], [513, 148, 797, 532]]
Chk 14112 [[119, 58, 422, 530], [403, 70, 706, 530]]
Chk 14113 [[123, 89, 254, 387], [47, 111, 132, 386]]
Chk 14114 [[0, 201, 144, 599], [83, 84, 401, 599], [474, 174, 728, 599], [383, 140, 584, 583], [667, 137, 799, 402]]
Chk 14115 [[252, 114, 464, 524], [443, 135, 700, 531]]
Chk 14116 [[317, 69, 588, 599], [206, 51, 450, 599], [681, 145, 772, 450]]
Chk 14117 [[0, 0, 334, 530], [280, 65, 528, 512], [593, 71, 800, 476], [627, 246, 797, 455]]
Chk 14118 [[151, 231, 247, 520], [572, 178, 791, 532], [293, 109, 458, 532], [355, 109, 617, 532], [57, 315, 109, 421], [2, 313, 106, 501]]
Chk 14119 [[6, 57, 337, 773], [244, 0, 533, 798]]
Chk 14120 [[383, 88, 731, 639], [68, 24, 407, 639]]
Chk 14121 [[119, 189, 313, 799], [13, 147, 222, 799]]
Chk 14122 [[42, 31, 504, 533], [124, 36, 536, 533]]
Chk 14123 [[534, 11, 715, 570], [12, 245, 145, 439]]
Chk 14124 [[157, 316, 224, 770], [42, 105, 255, 800], [202, 175, 389, 753]]
Chk 14125 [[19, 92, 159, 343], [355, 73, 499, 319]]
Chk 14127 [[27, 66, 308, 329], [145, 58, 295, 328], [319, 48, 496, 332]]
Chk 14129 [[38, 116, 221, 792], [164, 136, 303, 722], [241, 55, 474, 767]]
Chk 14132 [[2, 100, 428, 595], [306, 156, 473, 508], [592, 93, 799, 581]]
Chk 14133 [[102, 246, 558, 799], [0, 88, 369, 779]]
Chk 14135 [[527, 6, 794, 558], [79, 86, 420, 552], [323, 119, 558, 471]]
Chk 14136 [[540, 101, 652, 389], [687, 167, 764, 372], [96, 66, 239, 470]]
Chk 14137 [[342, 45, 456, 280], [40, 23, 390, 433], [443, 221, 727, 438], [645, 44, 757, 174], [531, 54, 603, 123], [597, 36, 695, 148]]
Chk 14138 [[325, 295, 417, 467], [260, 308, 315, 484]]
Chk 14139 [[371, 245, 415, 356], [221, 161, 381, 508], [416, 165, 546, 445], [588, 137, 648, 318], [654, 138, 703, 281], [500, 161, 547, 308]]
Chk 14140 [[348, 103, 799, 541], [44, 152, 306, 545]]
Chk 14141 [[69, 203, 118, 274], [40, 111, 330, 600], [353, 127, 579, 599]]
Chk 14142 [[358, 268, 613, 599], [506, 209, 686, 599]]
Chk 14145 [[329, 46, 409, 283], [261, 60, 352, 313]]
Chk 14146 [[0, 0, 264, 520], [217, 37, 611, 532], [613, 157, 799, 532]]
Chk 14147 [[33, 60, 341, 769], [275, 64, 571, 702]]
Chk 14149 [[185, 60, 381, 510], [345, 266, 467, 483]]
Chk 14150 [[247, 193, 379, 543], [499, 25, 669, 500]]
Chk 14151 [[33, 147, 148, 435], [146, 133, 237, 281], [296, 146, 368, 273], [52, 108, 373, 527], [341, 36, 729, 533], [646, 166, 747, 368]]
Chk 14152 [[270, 14, 516, 497], [577, 45, 766, 416], [25, 18, 236, 470]]
Chk 14153 [[0, 22, 522, 529], [236, 51, 730, 533]]
Chk 14154 [[237, 112, 394, 493], [382, 113, 566, 468]]
Chk 14156 [[154, 138, 208, 322], [199, 148, 255, 321]]
Chk 14157 [[279, 147, 441, 509], [528, 114, 698, 527], [101, 76, 246, 478], [46, 155, 97, 236], [56, 225, 116, 346]]
Chk 14158 [[87, 137, 332, 502], [290, 179, 468, 454], [30, 240, 89, 321], [343, 37, 750, 533], [708, 270, 782, 351]]
Chk 14159 [[254, 16, 796, 599], [163, 56, 498, 599]]
Chk 14160 [[18, 110, 92, 211], [245, 96, 335, 208], [433, 88, 499, 241], [107, 93, 190, 192], [318, 87, 427, 306]]
Chk 14161 [[455, 87, 683, 639], [171, 37, 448, 625]]
Chk 14162 [[0, 227, 193, 800], [86, 0, 600, 800]]

Chk 14163 [[311, 93, 765, 532], [56, 162, 349, 470]]
Chk 14165 [[0, 69, 232, 374], [333, 75, 500, 375]]
Chk 14166 [[224, 50, 473, 339], [4, 57, 225, 348]]
Chk 14167 [[344, 85, 691, 777], [582, 265, 760, 766]]
Chk 14168 [[353, 54, 747, 522], [150, 27, 408, 526]]
Chk 14169 [[56, 100, 249, 720], [218, 30, 507, 718], [179, 33, 285, 182]]
Chk 14170 [[90, 352, 371, 668], [173, 360, 421, 657]]
Chk 14171 [[172, 8, 527, 533], [592, 30, 800, 514]]
Chk 14172 [[480, 154, 799, 532], [0, 36, 306, 532], [231, 215, 426, 532], [482, 242, 586, 517]]
Chk 14173 [[0, 55, 308, 317], [200, 44, 478, 250]]
Chk 14174 [[272, 72, 380, 212], [174, 73, 276, 199], [11, 34, 174, 213], [387, 1, 549, 282]]
Chk 14176 [[37, 121, 386, 528], [465, 58, 791, 595]]
Chk 14177 [[0, 221, 218, 676], [230, 206, 526, 676], [399, 194, 681, 676]]
Chk 14178 [[178, 145, 373, 599], [411, 123, 721, 599]]
Chk 14179 [[60, 51, 291, 665], [457, 113, 741, 722]]
Chk 14180 [[16, 26, 260, 533], [296, 61, 782, 521]]
Chk 14181 [[64, 12, 269, 311], [233, 131, 505, 420]]
Chk 14182 [[38, 126, 174, 298], [262, 107, 442, 299], [240, 14, 395, 229], [419, 168, 480, 243], [0, 53, 87, 216]]
Chk 14183 [[31, 6, 233, 361], [230, 97, 422, 306]]
Chk 14186 [[0, 0, 273, 333], [146, 0, 459, 333], [314, 22, 500, 333]]
Chk 14187 [[259, 111, 357, 458], [87, 102, 240, 487], [469, 110, 557, 245], [3, 342, 58, 526]]
Chk 14188 [[412, 51, 737, 439], [181, 73, 379, 307], [23, 39, 181, 382], [74, 69, 351, 418]]
Chk 14189 [[0, 146, 120, 333], [48, 167, 187, 333], [104, 97, 202, 318], [166, 148, 294, 286], [298, 132, 384, 284], [347, 152, 500, 333]]
Chk 14190 [[3, 199, 302, 541], [311, 88, 757, 652], [543, 150, 799, 676]]
Chk 14193 [[23, 189, 263, 569], [285, 168, 475, 312], [518, 184, 783, 571]]
Chk 14194 [[103, 7, 307, 588], [318, 97, 500, 574], [494, 86, 654, 588], [708, 126, 799, 356]]
Chk 14195 [[214, 353, 525, 795], [23, 14, 366, 782], [481, 390, 599, 785], [457, 379, 556, 516]]
Chk 14196 [[0, 123, 306, 522], [435, 191, 799, 532], [352, 197, 572, 485]]
Chk 14198 [[306, 127, 480, 480], [59, 130, 264, 503]]
Chk 14200 [[190, 35, 438, 527], [24, 113, 339, 532], [339, 127, 742, 529]]
Chk 14201 [[352, 17, 776, 506], [15, 2, 365, 552]]
Chk 14202 [[54, 111, 388, 529], [374, 87, 750, 529], [250, 0, 322, 154], [580, 0, 643, 194], [365, 0, 428, 194]]
Chk 14204 [[0, 58, 107, 332], [156, 18, 249, 141], [297, 19, 386, 187], [358, 56, 493, 278], [478, 49, 536, 148], [640, 15, 726, 280], [0, 121, 420, 726], [353, 115, 726, 726]]
Chk 14205 [[72, 131, 114, 187], [137, 59, 222, 366], [349, 105, 390, 226], [431, 87, 494, 354]]
Chk 14206 [[0, 134, 511, 535], [0, 96, 504, 541]]
Chk 14207 [[273, 89, 484, 532], [489, 78, 690, 532]]
Chk 14208 [[2, 22, 164, 370], [283, 68, 462, 374], [140, 133, 314, 364], [237, 148, 310, 267]]
Chk 14210 [[73, 15, 322, 624], [255, 101, 463, 564], [397, 57, 640, 598]]
Chk 14211 [[117, 290, 382, 639], [407, 195, 746, 636]]
Chk 14212 [[196, 205, 438, 714], [331, 170, 573, 716]]
Chk 14213 [[453, 20, 633, 442], [48, 57, 179, 579], [611, 81, 734, 543]]
Chk 14214 [[0, 14, 539, 600], [424, 232, 686, 600]]
Chk 14215 [[24, 157, 131, 551], [95, 168, 203, 536], [202, 207, 398, 571], [428, 138, 644, 571], [701, 225, 770, 286]]
Chk 14216 [[522, 157, 750, 599], [276, 154, 567, 410], [12, 200, 224, 587]]
Chk 14218 [[270, 53, 409, 323], [96, 67, 266, 319]]
Chk 14219 [[2, 159, 139, 531], [118, 124, 360, 531], [324, 157, 678, 527], [339, 176, 487, 502]]
Chk 14220 [[361, 7, 799, 799], [6, 95, 398, 769]]
Chk 14222 [[0, 254, 321, 567], [11, 116, 438, 600], [442, 94, 736, 592], [647, 166, 800, 597]]
Chk 14223 [[99, 54, 219, 260], [124, 26, 251, 232]]
Chk 14224 [[123, 103, 507, 420], [474, 100, 751, 461]]
Chk 14225 [[10, 120, 412, 533], [240, 67, 768, 533]]
Chk 14226 [[143, 119, 372, 656], [49, 296, 225, 718]]
Chk 14227 [[0, 92, 232, 781], [300, 209, 412, 345]]
Chk 14228 [[98, 169, 621, 599], [586, 171, 799, 599]]
Chk 14229 [[547, 229, 800, 471], [333, 34, 506, 503], [137, 9, 311, 502]]
Chk 14230 [[166, 200, 493, 512], [512, 130, 765, 457]]
Chk 14231 [[0, 81, 304, 302], [262, 37, 476, 312]]
Chk 14232 [[271, 11, 756, 638], [60, 44, 405, 638]]
Chk 14233 [[181, 216, 469, 784], [13, 229, 359, 783]]
Chk 14234 [[0, 154, 256, 730], [257, 133, 559, 730], [453, 203, 595, 730], [575, 180, 800, 699]]
Chk 14236 [[8, 3, 319, 516], [387, 35, 799, 500], [122, 8, 600, 446]]
Chk 14238 [[0, 70, 201, 388], [427, 0, 499, 383]]
Chk 14239 [[16, 35, 243, 289], [606, 31, 788, 284]]
Chk 14240 [[137, 145, 506, 799], [0, 68, 90, 730], [15, 107, 339, 739]]
Chk 14241 [[342, 212, 720, 586], [78, 192, 349, 586]]
Chk 14242 [[201, 120, 537, 522], [3, 123, 313, 532]]
Chk 14243 [[189, 33, 776, 558], [69, 41, 392, 570]]
Chk 14244 [[0, 10, 406, 596], [345, 61, 795, 598]]
Chk 14245 [[367, 343, 476, 499], [659, 404, 782, 574], [174, 248, 238, 455], [593, 315, 659, 478]]
Chk 14246 [[47, 170, 351, 791], [266, 129, 393, 690]]
Chk 14247 [[214, 0, 496, 331], [72, 70, 449, 330]]
Chk 14248 [[291, 24, 567, 398], [23, 90, 394, 398]]
Chk 14249 [[122, 163, 296, 406], [427, 214, 629, 458]]
Chk 14250 [[0, 34, 243, 375], [224, 75, 500, 374]]
Chk 14251 [[17, 50, 220, 344], [158, 36, 496, 354], [188, 56, 316, 337]]
Chk 14252 [[122, 158, 502, 511], [0, 183, 314, 549]]
Chk 14253 [[0, 48, 308, 399], [309, 0, 599, 392]]
Chk 14254 [[56, 31, 322, 393], [298, 36, 533, 397]]
Chk 14255 [[0, 0, 365, 496], [12, 174, 391, 500]]
Chk 14256 [[18, 25, 383, 399], [420, 110, 713, 399]]
Chk 14257 [[601, 121, 749, 532], [309, 70, 489, 270]]
Chk 14258 [[613, 200, 788, 529], [368, 221, 543, 437], [188, 170, 391, 480], [4, 163, 263, 524], [72, 214, 551, 514]]
Chk 14259 [[133, 186, 463, 444], [62, 317, 487, 740]]
Chk 14260 [[222, 251, 310, 450], [548, 193, 686, 599]]
Chk 14261 [[85, 139, 425, 534], [372, 69, 768, 534], [722, 156, 798, 526]]
Chk 14262 [[129, 135, 292, 447], [312, 107, 486, 440], [330, 257, 544, 515]]
Chk 14263 [[161, 40, 257, 273], [280, 124, 343, 191], [7, 169, 215, 360]]
Chk 14265 [[1, 248, 313, 599], [182, 111, 391, 561], [523, 251, 764, 549]]
Chk 14266 [[3, 192, 366, 800], [261, 94, 531, 797]]
Chk 14267 [[318, 94, 471, 345], [38, 62, 368, 345], [111, 22, 213, 237]]
Chk 14268 [[0, 10, 444, 532], [367, 16, 799, 532]]
Chk 14269 [[3, 50, 392, 453], [186, 115, 484, 454]]
Chk 14270 [[153, 166, 437, 526], [358, 97, 617, 531]]
Chk 14271 [[291, 176, 516, 570], [60, 151, 488, 584], [456, 178, 694, 577]]
Chk 14272 [[209, 405, 355, 799], [15, 352, 246, 790]]
Chk 14273 [[274, 89, 524, 545], [24, 64, 332, 587], [567, 71, 740, 431]]
Chk 14274 [[255, 69, 469, 532], [68, 148, 174, 441], [472, 35, 704, 532], [3, 140, 72, 409], [681, 26, 792, 512], [418, 104, 509, 406], [120, 145, 195, 418]]
Chk 14275 [[41, 21, 324, 495], [32, 128, 305, 483]]
Chk 14276 [[172, 65, 270, 294], [132, 64, 225, 299]]
Chk 14277 [[105, 130, 397, 367], [461, 212, 765, 368], [457, 29, 580, 102], [578, 32, 663, 106], [404, 12, 463, 95], [135, 0, 230, 112], [14, 7, 110, 92]]
Chk 14278 [[80, 269, 387, 609], [572, 266, 800, 511], [437, 324, 800, 609]]
Chk 14279 [[6, 21, 216, 345], [169, 75, 361, 336], [328, 79, 499, 352]]
Chk 14280 [[257, 154, 483, 471], [409, 64, 663, 520]]
Chk 14281 [[5, 7, 580, 600], [361, 54, 671, 442], [363, 1, 619, 254]]
Chk 14282 [[46, 83, 507, 599], [388, 114, 799, 599]]
Chk 14283 [[467, 412, 615, 532], [347, 205, 686, 529], [401, 103, 537, 234], [225, 44, 422, 527], [77, 114, 233, 532]]
Chk 14286 [[12, 226, 146, 531], [173, 242, 335, 520]]
Chk 14287 [[93, 102, 390, 461], [397, 46, 669, 446], [49, 172, 94, 226], [2, 166, 46, 219], [73, 173, 117, 226]]
Chk 14288 [[0, 0, 98, 187], [156, 1, 253, 230], [228, 0, 349, 225], [200, 274, 398, 505], [440, 112, 730, 515], [696, 2, 800, 528]]
Chk 14289 [[191, 157, 483, 618], [241, 72, 702, 640]]
Chk 14290 [[155, 192, 357, 525], [312, 201, 525, 533], [525, 256, 577, 396], [594, 281, 638, 351], [497, 246, 538, 393]]
Chk 14291 [[29, 51, 397, 448], [386, 242, 686, 600]]
Chk 14292 [[5, 106, 271, 497], [269, 91, 692, 499], [685, 38, 786, 177]]
Chk 14293 [[323, 21, 799, 599], [27, 41, 458, 599]]
Chk 14294 [[376, 103, 551, 432], [246, 104, 408, 440]]
Chk 14295 [[293, 16, 799, 527], [0, 70, 381, 529]]
Chk 14296 [[532, 43, 688, 525], [277, 0, 583, 479], [744, 0, 799, 173]]
Chk 14297 [[108, 67, 342, 575], [374, 4, 681, 600], [635, 75, 800, 600], [76, 154, 165, 416], [78, 410, 337, 600]]
Chk 14298 [[76, 131, 418, 594], [343, 18, 800, 600]]
Chk 14299 [[417, 25, 616, 378], [241, 47, 451, 373], [28, 0, 264, 385]]
Chk 14301 [[6, 139, 69, 229], [230, 111, 326, 226], [367, 64, 492, 247], [127, 125, 212, 214]]

Chk 14302 [[30, 247, 335, 767], [227, 169, 501, 799], [89, 195, 153, 275], [236, 190, 305, 276], [177, 178, 222, 254], [333, 0, 386, 96], [428, 225, 532, 454]]
Chk 14303 [[281, 82, 799, 523], [7, 50, 357, 532]]
Chk 14304 [[132, 96, 623, 787], [1, 161, 389, 774]]
Chk 14307 [[413, 41, 580, 505], [560, 55, 718, 527]]
Chk 14309 [[354, 51, 439, 270], [443, 57, 603, 294], [539, 144, 668, 376], [249, 155, 387, 314], [99, 145, 148, 304], [134, 137, 229, 336]]
Chk 14310 [[22, 60, 288, 333], [262, 8, 480, 332]]
Chk 14312 [[4, 133, 119, 312], [178, 128, 330, 287], [285, 27, 466, 301]]
Chk 14315 [[83, 128, 305, 351], [297, 0, 473, 314], [448, 118, 639, 342], [0, 85, 113, 359]]
Chk 14316 [[9, 122, 150, 376], [235, 0, 399, 383], [339, 116, 537, 408]]
Chk 14318 [[254, 80, 626, 599], [114, 156, 451, 588]]
Chk 14319 [[0, 169, 141, 530], [124, 164, 251, 368], [147, 45, 528, 530], [503, 159, 800, 530]]
Chk 14320 [[215, 74, 444, 438], [78, 40, 311, 431]]
Chk 14321 [[98, 29, 352, 501], [471, 27, 768, 495]]
Chk 14322 [[261, 175, 330, 312], [347, 192, 392, 317]]
Chk 14323 [[70, 335, 609, 516], [312, 208, 513, 422]]
Chk 14324 [[272, 153, 475, 499], [471, 212, 734, 534], [585, 382, 797, 580], [33, 300, 492, 539], [356, 362, 795, 539]]
Chk 14325 [[0, 284, 409, 795], [249, 46, 623, 640]]
Chk 14326 [[0, 21, 439, 533], [461, 121, 775, 530]]
Chk 14327 [[141, 146, 317, 421], [426, 110, 592, 429]]
Chk 14328 [[146, 106, 360, 396], [7, 113, 195, 423]]
Chk 14329 [[62, 88, 354, 476], [393, 45, 668, 443]]
Chk 14331 [[556, 171, 643, 296], [487, 28, 800, 599], [406, 118, 556, 297], [312, 16, 433, 284], [0, 73, 439, 600]]
Chk 14332 [[0, 91, 180, 512], [92, 135, 192, 235], [10, 204, 418, 530], [325, 82, 800, 530], [714, 59, 800, 276], [564, 140, 626, 234]]
Chk 14334 [[224, 206, 330, 532], [75, 86, 219, 518], [338, 6, 432, 230], [463, 7, 699, 292], [613, 12, 670, 140], [756, 6, 799, 112], [363, 199, 417, 260]]
Chk 14336 [[366, 30, 642, 799], [58, 363, 218, 700], [373, 370, 424, 511]]
Chk 14337 [[0, 115, 163, 441], [229, 182, 354, 434], [467, 55, 788, 449], [340, 178, 470, 445], [438, 132, 636, 445]]
Chk 14338 [[366, 66, 598, 532], [188, 86, 417, 532]]
Chk 14340 [[2, 113, 303, 552], [156, 153, 262, 375], [362, 150, 430, 354], [304, 14, 647, 552], [616, 0, 800, 547]]
Chk 14341 [[322, 99, 556, 596], [629, 220, 684, 388], [731, 222, 782, 360], [1, 23, 246, 580], [231, 160, 378, 529], [216, 192, 272, 357], [591, 223, 659, 381], [742, 209, 796, 442]]
Chk 14342 [[276, 530, 350, 678], [193, 513, 275, 660]]
Chk 14343 [[0, 107, 388, 592], [313, 234, 525, 467], [569, 203, 750, 544]]
Chk 14344 [[95, 19, 440, 370], [8, 20, 225, 365]]
Chk 14345 [[361, 68, 603, 396], [166, 80, 474, 521]]
Chk 14347 [[354, 178, 566, 743], [115, 26, 421, 702]]
Chk 14348 [[0, 66, 221, 331], [237, 12, 498, 333], [291, 146, 500, 333]]
Chk 14349 [[323, 263, 498, 724], [188, 316, 402, 771]]
Chk 14350 [[3, 164, 243, 799], [272, 206, 531, 799], [459, 231, 510, 351]]
Chk 14351 [[355, 0, 493, 533], [215, 10, 395, 533]]
Chk 14352 [[101, 44, 279, 613], [238, 100, 411, 580]]
Chk 14353 [[340, 19, 523, 599], [6, 409, 300, 797], [89, 194, 493, 781], [161, 57, 397, 541]]
Chk 14354 [[108, 210, 191, 472], [43, 236, 124, 477]]
Chk 14356 [[78, 39, 296, 535], [229, 50, 460, 529]]
Chk 14357 [[86, 164, 282, 476], [456, 90, 757, 498], [309, 166, 503, 427]]
Chk 14361 [[377, 151, 645, 530], [274, 0, 799, 533]]
Chk 14362 [[48, 182, 400, 786], [110, 53, 210, 265], [284, 89, 479, 799], [36, 62, 115, 315], [200, 83, 280, 177], [126, 169, 326, 517], [472, 129, 532, 313], [268, 79, 332, 198]]
Chk 14363 [[479, 46, 799, 519], [1, 43, 515, 469], [237, 38, 469, 384]]
Chk 14365 [[390, 132, 549, 329], [202, 156, 384, 331], [0, 107, 147, 400], [576, 83, 799, 527], [502, 91, 686, 362]]
Chk 14366 [[399, 65, 799, 525], [21, 49, 379, 532]]
Chk 14368 [[31, 219, 354, 686], [324, 240, 675, 704]]
Chk 14369 [[305, 137, 637, 486], [38, 143, 376, 495], [690, 167, 799, 456]]
Chk 14370 [[520, 45, 787, 462], [21, 46, 214, 259], [92, 63, 334, 499]]
Chk 14372 [[399, 210, 550, 447], [202, 239, 269, 441], [124, 217, 191, 442]]
Chk 14373 [[23, 49, 411, 529], [472, 124, 752, 538], [214, 95, 571, 534]]
Chk 14374 [[0, 103, 323, 524], [486, 44, 792, 533]]
Chk 14375 [[3, 25, 142, 332], [260, 36, 457, 332], [26, 36, 308, 332]]
Chk 14376 [[32, 15, 159, 374], [134, 54, 265, 374], [240, 41, 363, 374], [337, 53, 488, 374]]
Chk 14377 [[45, 241, 337, 597], [244, 148, 491, 600], [553, 108, 789, 600]]
Chk 14378 [[263, 3, 795, 626], [89, 48, 503, 626], [0, 492, 62, 621]]
Chk 14379 [[5, 75, 469, 483], [277, 95, 457, 533]]
Chk 14380 [[34, 50, 358, 799], [224, 117, 502, 799]]
Chk 14381 [[50, 244, 365, 587], [349, 281, 574, 596]]
Chk 14382 [[504, 85, 800, 532], [70, 217, 464, 532]]
Chk 14383 [[403, 212, 688, 585], [0, 3, 549, 599]]
Chk 14385 [[44, 54, 407, 394], [390, 50, 695, 444]]
Chk 14386 [[486, 23, 717, 584], [332, 53, 489, 579], [65, 36, 374, 594], [57, 171, 113, 303], [388, 51, 460, 146], [296, 133, 357, 360]]
Chk 14387 [[115, 168, 274, 500], [51, 104, 166, 500]]
Chk 14388 [[283, 256, 414, 506], [189, 37, 432, 520], [582, 184, 799, 514]]
Chk 14389 [[54, 162, 321, 800], [263, 97, 485, 800]]
Chk 14390 [[232, 199, 463, 485], [312, 129, 547, 418]]
Chk 14391 [[468, 122, 681, 468], [23, 89, 426, 509], [307, 90, 531, 481]]
Chk 14392 [[5, 69, 301, 327], [170, 124, 469, 293]]
Chk 14395 [[481, 72, 717, 492], [154, 89, 498, 531]]
Chk 14397 [[276, 122, 426, 366], [263, 215, 714, 495]]
Chk 14398 [[136, 41, 414, 439], [524, 184, 637, 397], [397, 162, 527, 397]]
Chk 14400 [[7, 14, 185, 484], [165, 48, 284, 487]]
Chk 14402 [[19, 0, 305, 653], [397, 271, 710, 600]]
Chk 14403 [[0, 99, 98, 322], [259, 139, 357, 258], [315, 48, 469, 249]]
Chk 14404 [[0, 105, 275, 453], [286, 79, 617, 447], [479, 135, 800, 506]]
Chk 14405 [[404, 152, 534, 582], [621, 199, 762, 584], [527, 219, 631, 557]]
Chk 14406 [[257, 17, 800, 533], [21, 281, 288, 533]]
Chk 14407 [[0, 34, 299, 377], [132, 107, 236, 228], [533, 107, 637, 311], [582, 65, 800, 395]]
Chk 14408 [[605, 135, 799, 420], [167, 137, 489, 426]]
Chk 14409 [[366, 197, 556, 564], [133, 219, 337, 527]]
Chk 14410 [[346, 297, 595, 653], [619, 182, 742, 631], [728, 201, 800, 580]]
Chk 14411 [[165, 31, 708, 526], [523, 22, 747, 493]]
Chk 14412 [[193, 165, 267, 339], [260, 145, 336, 349]]
Chk 14413 [[248, 155, 561, 532], [266, 68, 559, 526]]
Chk 14414 [[73, 0, 460, 564], [445, 36, 709, 556]]
Chk 14415 [[141, 101, 229, 332], [260, 82, 356, 332]]
Chk 14416 [[447, 110, 726, 599], [241, 244, 476, 599], [679, 169, 761, 416]]
Chk 14417 [[506, 133, 628, 457], [433, 145, 580, 481]]
Chk 14418 [[128, 104, 278, 258], [3, 101, 145, 260], [332, 95, 497, 347], [311, 94, 401, 296]]
Chk 14419 [[126, 107, 251, 631], [194, 77, 361, 622], [275, 79, 367, 312]]
Chk 14420 [[303, 137, 477, 367], [3, 100, 155, 358], [143, 116, 278, 326], [42, 8, 196, 293]]
Chk 14421 [[14, 59, 249, 531], [334, 233, 438, 461], [661, 342, 709, 457], [755, 327, 796, 441], [445, 231, 639, 506]]
Chk 14422 [[474, 64, 799, 493], [1, 0, 287, 488]]
Chk 14424 [[34, 71, 141, 406], [169, 111, 281, 468]]
Chk 14425 [[292, 77, 764, 532], [0, 67, 379, 523]]
Chk 14426 [[220, 51, 439, 642], [0, 22, 210, 751], [393, 113, 592, 779]]
Chk 14428 [[170, 152, 300, 317], [30, 160, 195, 315]]
Chk 14429 [[249, 30, 483, 373], [6, 33, 237, 370]]
Chk 14430 [[236, 226, 339, 425], [459, 262, 568, 513]]
Chk 14432 [[113, 136, 344, 459], [151, 351, 566, 524]]
Chk 14433 [[222, 202, 431, 454], [463, 188, 707, 404], [672, 188, 799, 529], [26, 184, 261, 413]]
Chk 14434 [[1, 133, 338, 531], [352, 97, 767, 536], [253, 134, 505, 531]]
Chk 14435 [[53, 57, 411, 545], [566, 28, 799, 599]]
Chk 14436 [[0, 174, 244, 527], [474, 68, 799, 532], [165, 88, 321, 526], [339, 9, 603, 532], [752, 76, 799, 237], [495, 0, 569, 142], [388, 45, 572, 243]]
Chk 14437 [[56, 160, 416, 783], [49, 228, 402, 800]]
Chk 14438 [[94, 213, 312, 799], [303, 118, 595, 799]]
Chk 14440 [[244, 119, 600, 800], [15, 250, 339, 800], [28, 468, 245, 727]]
Chk 14441 [[352, 45, 499, 347], [4, 53, 172, 374]]
Chk 14442 [[78, 95, 367, 728], [367, 291, 531, 712]]
Chk 14443 [[99, 36, 748, 599], [472, 108, 799, 574]]
Chk 14444 [[12, 108, 156, 333], [131, 37, 303, 245], [270, 89, 414, 248], [315, 0, 500, 332]]
Chk 14445 [[81, 0, 246, 343], [306, 148, 512, 355]]
Chk 14446 [[18, 49, 180, 351], [151, 128, 200, 198], [479, 102, 534, 154], [246, 202, 450, 361], [197, 71, 266, 285], [332, 152, 529, 345], [22, 47, 92, 200]]
Chk 14447 [[227, 173, 391, 514], [76, 58, 215, 434], [4, 192, 152, 477]]
Chk 14448 [[35, 201, 180, 453], [155, 67, 439, 415], [356, 188, 536, 459]]
Chk 14449 [[169, 0, 361, 492], [12, 193, 203, 484]]
Chk 14451 [[261, 107, 344, 211], [47, 0, 193, 207], [374, 81, 542, 271]]
Chk 14452 [[0, 63, 167, 281], [199, 96, 348, 281]]
Chk 14453 [[251, 251, 418, 721], [91, 229, 306, 751]]
Chk 14454 [[0, 0, 81, 497], [52, 23, 375, 500]]

Chk 14456 [[15, 82, 123, 360], [124, 120, 215, 347], [15, 58, 577, 512], [405, 109, 788, 528]]
Chk 14457 [[276, 79, 742, 614], [236, 119, 402, 590], [63, 201, 243, 520]]
Chk 14460 [[250, 151, 487, 530], [304, 110, 503, 531], [203, 4, 395, 482]]
Chk 14461 [[125, 151, 421, 753], [0, 392, 103, 720], [431, 336, 529, 783]]
Chk 14462 [[143, 39, 435, 481], [3, 93, 129, 340], [527, 209, 769, 483], [642, 27, 796, 479]]
Chk 14463 [[5, 64, 236, 624], [149, 102, 363, 762]]
Chk 14464 [[0, 190, 140, 800], [97, 217, 248, 779], [273, 272, 374, 625], [356, 300, 433, 640]]
Chk 14465 [[34, 64, 536, 512], [344, 171, 743, 514]]
Chk 14466 [[19, 6, 672, 713], [300, 162, 772, 709]]
Chk 14467 [[0, 51, 216, 332], [58, 40, 182, 301], [218, 51, 297, 209], [312, 68, 380, 148], [373, 46, 481, 326]]
Chk 14468 [[25, 22, 195, 218], [150, 118, 445, 464], [523, 0, 648, 135], [376, 95, 756, 498], [711, 3, 792, 146]]
Chk 14469 [[269, 250, 440, 574], [362, 286, 532, 576]]
Chk 14470 [[9, 69, 183, 328], [303, 42, 478, 331]]
Chk 14471 [[453, 147, 627, 475], [568, 186, 609, 252], [233, 166, 358, 369], [5, 132, 179, 306]]
Chk 14472 [[150, 26, 550, 799], [23, 149, 318, 799]]
Chk 14473 [[308, 132, 496, 363], [5, 133, 221, 510], [576, 165, 797, 388]]
Chk 14475 [[186, 118, 369, 333], [330, 84, 391, 154]]
Chk 14476 [[452, 201, 555, 449], [560, 199, 687, 443], [69, 203, 158, 370]]
Chk 14477 [[381, 70, 644, 571], [438, 167, 691, 571]]
Chk 14479 [[282, 104, 477, 599], [416, 203, 663, 591], [63, 37, 142, 134], [575, 105, 619, 177], [417, 71, 654, 413]]
Chk 14481 [[34, 135, 414, 752], [322, 15, 531, 393], [409, 117, 714, 739]]
Chk 14482 [[481, 110, 769, 533], [98, 227, 337, 532], [0, 23, 588, 533]]
Chk 14484 [[292, 71, 473, 574], [505, 122, 662, 591], [48, 132, 282, 559]]
Chk 14485 [[395, 208, 587, 743], [286, 276, 376, 524], [490, 281, 619, 726]]
Chk 14487 [[12, 86, 72, 273], [107, 136, 193, 348], [395, 222, 517, 436], [239, 202, 451, 770], [103, 144, 314, 789]]
Chk 14488 [[128, 73, 345, 485], [278, 42, 419, 484], [341, 107, 494, 492], [474, 32, 654, 498]]
Chk 14489 [[517, 95, 758, 512], [21, 118, 265, 364]]
Chk 14490 [[121, 84, 511, 600], [413, 129, 800, 600]]
Chk 14491 [[335, 88, 499, 332], [66, 70, 284, 332]]
Chk 14492 [[139, 131, 376, 533], [390, 144, 616, 531]]
Chk 14493 [[49, 28, 718, 532], [327, 216, 799, 530]]
Chk 14494 [[508, 68, 712, 522], [76, 84, 233, 531], [291, 102, 468, 494], [0, 317, 99, 531], [0, 233, 60, 399]]
Chk 14496 [[260, 125, 357, 489], [356, 143, 440, 476], [432, 131, 511, 498]]
Chk 14497 [[75, 138, 448, 529], [348, 138, 671, 527]]
Chk 14498 [[96, 102, 484, 550], [473, 103, 694, 511]]
Chk 14499 [[97, 277, 219, 468], [187, 141, 294, 482], [362, 201, 603, 532], [528, 200, 741, 515]]
Chk 14500 [[475, 183, 800, 660], [0, 24, 233, 660]]
Chk 14501 [[23, 26, 255, 545], [347, 106, 633, 545], [208, 90, 394, 524]]
Chk 14503 [[75, 171, 134, 313], [128, 164, 202, 308], [238, 170, 404, 440], [387, 0, 794, 533]]
Chk 14504 [[308, 130, 591, 522], [19, 71, 282, 522], [584, 46, 787, 522], [610, 347, 655, 514]]
Chk 14505 [[30, 93, 341, 365], [238, 39, 355, 354]]
Chk 14506 [[57, 25, 501, 639], [520, 176, 766, 639], [342, 53, 689, 623]]
Chk 14507 [[0, 121, 113, 490], [133, 55, 353, 572], [406, 75, 637, 551], [639, 108, 800, 561]]
Chk 14508 [[108, 98, 331, 375], [214, 16, 384, 375]]
Chk 14509 [[4, 36, 229, 497], [137, 62, 364, 532], [304, 176, 470, 532], [475, 42, 660, 534]]
Chk 14510 [[543, 153, 661, 401], [167, 127, 284, 418], [250, 150, 346, 414], [104, 248, 149, 311]]
Chk 14511 [[14, 167, 283, 412], [257, 133, 577, 433], [527, 110, 766, 414]]
Chk 14512 [[165, 315, 385, 599], [337, 174, 590, 583]]
Chk 14513 [[319, 370, 489, 698], [193, 40, 373, 646]]
Chk 14514 [[15, 91, 380, 754], [289, 63, 635, 623]]
Chk 14515 [[418, 178, 636, 503], [455, 202, 781, 501]]
Chk 14516 [[172, 42, 349, 279], [7, 44, 200, 277], [309, 16, 457, 268]]
Chk 14517 [[312, 255, 383, 396], [450, 211, 524, 409], [168, 256, 249, 389], [265, 290, 315, 395]]
Chk 14518 [[105, 59, 592, 550], [433, 207, 748, 579]]
Chk 14519 [[141, 119, 447, 667], [0, 156, 475, 792]]
Chk 14520 [[124, 8, 563, 725], [433, 103, 720, 697]]
Chk 14521 [[412, 306, 603, 459], [467, 293, 730, 513], [313, 168, 407, 415], [402, 210, 450, 393]]
Chk 14522 [[170, 114, 381, 519], [452, 170, 587, 527]]
Chk 14523 [[106, 62, 747, 532], [736, 171, 788, 291], [96, 50, 393, 490], [626, 4, 689, 135]]
Chk 14524 [[226, 46, 457, 609], [402, 133, 659, 609]]
Chk 14526 [[45, 22, 269, 324], [203, 42, 411, 325]]
Chk 14527 [[0, 113, 152, 531], [465, 50, 780, 531], [199, 204, 243, 316]]
Chk 14528 [[38, 65, 165, 291], [255, 54, 390, 299], [101, 69, 272, 299]]
Chk 14530 [[325, 212, 417, 381], [431, 155, 488, 390]]
Chk 14531 [[137, 61, 354, 535], [452, 50, 697, 466]]
Chk 14532 [[0, 18, 112, 323], [101, 41, 227, 274], [230, 138, 376, 288], [327, 22, 491, 356], [58, 223, 190, 361]]
Chk 14533 [[135, 94, 376, 480], [272, 59, 594, 469]]
Chk 14534 [[324, 34, 745, 645], [59, 70, 308, 632], [58, 134, 126, 454], [342, 138, 405, 293], [0, 139, 43, 250], [688, 158, 758, 344]]
Chk 14536 [[136, 59, 291, 679], [270, 107, 428, 632]]
Chk 14537 [[487, 197, 764, 594], [311, 228, 495, 486], [74, 240, 311, 514]]
Chk 14538 [[84, 77, 386, 723], [269, 17, 506, 723]]
Chk 14539 [[33, 227, 322, 766], [332, 139, 721, 781]]
Chk 14540 [[66, 196, 344, 800], [297, 135, 560, 794], [250, 109, 398, 314]]
Chk 14541 [[246, 0, 498, 755], [15, 23, 234, 769]]
Chk 14542 [[261, 37, 448, 529], [67, 15, 356, 529]]
Chk 14543 [[12, 379, 217, 788], [169, 295, 446, 738]]
Chk 14544 [[48, 103, 437, 600], [138, 162, 669, 599]]
Chk 14545 [[0, 9, 50, 288], [50, 14, 235, 285], [152, 53, 214, 213], [214, 56, 306, 288]]
Chk 14546 [[74, 250, 588, 800], [36, 30, 597, 800]]
Chk 14547 [[371, 108, 539, 597], [197, 125, 381, 584], [88, 182, 131, 297], [0, 192, 51, 382], [735, 169, 799, 301]]
Chk 14548 [[156, 64, 438, 529], [523, 144, 716, 532], [316, 68, 568, 532]]
Chk 14549 [[91, 119, 285, 355], [407, 68, 800, 533]]
Chk 14551 [[133, 252, 294, 663], [217, 210, 363, 620]]
Chk 14552 [[68, 73, 442, 334], [202, 62, 405, 289]]
Chk 14553 [[395, 64, 644, 462], [12, 69, 391, 482]]
Chk 14554 [[111, 30, 367, 361], [271, 42, 422, 390]]
Chk 14555 [[72, 2, 249, 242], [35, 4, 399, 333]]
Chk 14556 [[144, 144, 210, 329], [197, 121, 302, 325]]
Chk 14557 [[109, 42, 340, 333], [286, 17, 492, 333]]
Chk 14558 [[72, 46, 528, 532], [334, 64, 720, 532]]
Chk 14559 [[15, 53, 207, 417], [124, 41, 270, 400]]
Chk 14560 [[143, 42, 307, 333], [159, 1, 413, 333]]
Chk 14561 [[242, 216, 415, 796], [112, 216, 277, 690]]
Chk 14562 [[24, 48, 351, 299], [226, 36, 390, 299], [34, 39, 166, 299]]
Chk 14563 [[507, 405, 646, 597], [242, 199, 405, 621], [167, 160, 324, 621]]
Chk 14564 [[288, 58, 750, 691], [321, 32, 623, 632]]
Chk 14565 [[0, 103, 302, 375], [239, 115, 381, 375]]
Chk 14566 [[140, 236, 237, 336], [306, 112, 485, 500], [17, 86, 221, 500]]
Chk 14567 [[293, 70, 529, 799], [144, 127, 315, 701]]
Chk 14568 [[226, 150, 444, 486], [339, 142, 626, 480]]
Chk 14569 [[314, 49, 528, 688], [126, 110, 366, 710], [49, 272, 94, 361], [174, 64, 230, 123]]
Chk 14570 [[445, 177, 786, 555], [19, 153, 330, 572], [241, 160, 594, 587]]
Chk 14572 [[329, 74, 713, 534], [237, 135, 462, 530], [85, 63, 338, 534], [725, 205, 788, 344], [640, 220, 706, 330], [582, 189, 671, 367]]
Chk 14575 [[208, 60, 455, 380], [23, 43, 180, 373]]
Chk 14576 [[181, 156, 351, 532], [684, 104, 762, 293], [307, 108, 393, 253], [94, 78, 163, 228], [397, 120, 633, 529], [401, 107, 449, 260], [44, 89, 87, 170]]
Chk 14577 [[328, 194, 462, 379], [565, 130, 717, 426], [53, 160, 254, 441]]
Chk 14578 [[404, 294, 735, 680], [172, 324, 507, 680]]
Chk 14579 [[0, 82, 203, 799], [160, 211, 369, 745], [577, 208, 789, 764], [203, 228, 664, 799]]
Chk 14580 [[118, 242, 265, 763], [168, 261, 360, 769]]
Chk 14581 [[101, 125, 255, 457], [127, 179, 566, 471]]
Chk 14582 [[101, 228, 179, 359], [144, 198, 260, 429], [225, 201, 420, 448], [462, 161, 637, 450]]
Chk 14583 [[376, 83, 790, 533], [84, 116, 504, 533]]
Chk 14584 [[168, 540, 224, 686], [80, 426, 184, 696]]
Chk 14585 [[14, 89, 632, 799], [10, 184, 374, 794]]
Chk 14586 [[109, 103, 588, 446], [109, 117, 448, 421]]
Chk 14587 [[107, 167, 432, 678], [368, 164, 740, 676]]
Chk 14589 [[418, 0, 789, 738], [86, 35, 440, 730], [77, 99, 276, 584]]
Chk 14590 [[244, 384, 375, 792], [70, 357, 208, 778], [389, 393, 440, 608], [427, 404, 486, 582], [470, 412, 532, 590], [194, 414, 257, 713]]
Chk 14592 [[42, 99, 126, 317], [206, 125, 249, 239], [183, 90, 465, 450], [435, 104, 614, 450], [637, 84, 738, 325], [659, 90, 799, 355]]
Chk 14593 [[35, 356, 448, 798], [222, 111, 448, 739], [36, 90, 78, 156]]

Chk 14595 [[32, 175, 238, 529], [354, 175, 714, 525], [155, 134, 412, 529]]
Chk 14596 [[272, 125, 535, 627], [24, 36, 370, 626], [447, 40, 513, 215]]
Chk 14597 [[146, 152, 333, 530], [279, 60, 501, 531]]
Chk 14598 [[43, 34, 468, 532], [474, 156, 773, 531]]
Chk 14599 [[0, 53, 296, 500], [61, 126, 333, 500]]
Chk 14600 [[0, 253, 135, 438], [218, 300, 332, 483], [115, 255, 249, 443]]
Chk 14601 [[0, 113, 281, 499], [259, 155, 741, 453], [535, 141, 785, 486]]
Chk 14602 [[393, 49, 800, 586], [26, 15, 531, 586]]
Chk 14603 [[302, 107, 461, 411], [632, 103, 776, 398], [157, 290, 246, 452]]
Chk 14605 [[8, 250, 183, 751], [158, 217, 361, 721]]
Chk 14606 [[114, 49, 472, 565], [284, 39, 480, 564], [381, 74, 551, 569], [450, 50, 767, 564]]
Chk 14607 [[0, 81, 275, 600], [123, 163, 348, 340], [373, 191, 681, 412], [626, 204, 710, 352]]
Chk 14610 [[295, 345, 489, 565], [136, 351, 266, 561], [482, 368, 537, 562], [3, 369, 117, 546], [747, 380, 793, 521], [697, 381, 752, 521], [18, 167, 62, 289], [662, 388, 727, 543]]
Chk 14611 [[0, 130, 133, 375], [206, 133, 363, 285], [294, 97, 500, 374]]
Chk 14612 [[0, 249, 508, 800], [0, 54, 542, 800]]
Chk 14613 [[459, 160, 748, 585], [0, 25, 346, 599]]
Chk 14614 [[2, 116, 326, 378], [124, 36, 776, 450]]
Chk 14615 [[123, 72, 392, 530], [383, 205, 637, 530]]
Chk 14617 [[91, 43, 429, 751], [336, 59, 497, 712]]
Chk 14618 [[36, 19, 273, 560], [343, 58, 544, 472]]
Chk 14619 [[90, 48, 322, 532], [314, 127, 459, 522], [407, 96, 755, 533]]
Chk 14620 [[647, 123, 763, 515], [123, 97, 269, 261], [247, 129, 394, 295]]
Chk 14621 [[5, 153, 354, 531], [329, 192, 711, 531]]
Chk 14622 [[122, 57, 344, 338], [311, 49, 535, 347]]
Chk 14623 [[323, 141, 630, 589], [553, 117, 780, 609]]
Chk 14624 [[192, 88, 482, 531], [385, 111, 578, 531]]
Chk 14625 [[255, 100, 462, 800], [197, 86, 359, 787]]
Chk 14626 [[246, 291, 511, 743], [122, 276, 324, 756], [1, 62, 71, 365], [366, 25, 494, 353], [525, 60, 600, 377], [258, 50, 370, 371], [110, 70, 258, 358]]
Chk 14627 [[0, 57, 546, 800], [198, 65, 800, 800]]
Chk 14628 [[17, 1, 161, 377], [54, 108, 374, 531], [348, 0, 745, 527], [482, 164, 772, 497]]
Chk 14629 [[0, 286, 517, 460], [0, 352, 502, 532]]
Chk 14630 [[91, 54, 345, 762], [84, 11, 413, 792], [0, 119, 92, 538]]
Chk 14631 [[12, 0, 389, 534], [415, 7, 796, 534]]
Chk 14632 [[276, 300, 599, 799], [4, 0, 367, 798]]
Chk 14633 [[142, 68, 587, 533], [461, 36, 799, 533]]
Chk 14634 [[137, 147, 420, 548], [290, 139, 445, 518], [332, 0, 410, 150]]
Chk 14635 [[300, 93, 474, 327], [461, 59, 648, 302]]
Chk 14636 [[207, 160, 387, 721], [219, 194, 331, 472]]
Chk 14637 [[220, 178, 388, 594], [427, 192, 578, 417], [11, 226, 242, 593], [524, 217, 784, 568], [414, 59, 533, 315]]
Chk 14638 [[454, 55, 618, 507], [58, 1, 246, 511], [622, 34, 771, 479], [184, 10, 331, 515]]
Chk 14639 [[213, 304, 361, 775], [65, 278, 291, 787]]
Chk 14642 [[0, 42, 184, 800], [154, 81, 534, 800], [180, 0, 600, 800], [438, 44, 510, 126], [486, 90, 600, 683]]
Chk 14644 [[322, 207, 451, 466], [438, 191, 559, 466], [210, 210, 347, 466], [406, 193, 455, 298]]
Chk 14645 [[399, 128, 800, 514], [437, 103, 602, 379], [127, 119, 282, 352], [0, 121, 327, 521], [0, 259, 214, 600]]
Chk 14647 [[76, 121, 426, 562], [510, 224, 561, 314], [586, 235, 628, 326], [490, 77, 623, 280], [673, 138, 720, 234]]
Chk 14648 [[410, 140, 785, 529], [98, 137, 292, 425]]
Chk 14649 [[314, 91, 408, 271], [638, 113, 773, 284]]
Chk 14650 [[255, 70, 492, 798], [46, 142, 322, 799]]
Chk 14651 [[351, 122, 796, 525], [315, 15, 688, 523], [5, 40, 396, 528]]
Chk 14652 [[65, 61, 375, 249], [0, 0, 290, 247]]
Chk 14653 [[82, 80, 321, 457], [56, 31, 284, 500]]
Chk 14654 [[40, 94, 200, 500], [38, 93, 304, 500]]
Chk 14655 [[19, 0, 272, 334], [192, 10, 411, 334]]
Chk 14656 [[167, 95, 537, 506], [345, 0, 784, 494]]
Chk 14657 [[123, 53, 717, 545], [393, 139, 681, 537]]
Chk 14658 [[0, 0, 463, 237], [19, 0, 500, 400]]
Chk 14659 [[14, 62, 285, 498], [0, 58, 349, 500]]
Chk 14660 [[5, 67, 362, 532], [268, 101, 543, 532]]
Chk 14661 [[94, 0, 315, 333], [198, 0, 500, 324]]
Chk 14662 [[85, 136, 368, 513], [355, 127, 660, 513], [535, 149, 734, 495]]
Chk 14664 [[107, 116, 366, 599], [531, 83, 778, 598]]
Chk 14665 [[0, 44, 185, 532], [110, 39, 336, 314], [263, 140, 734, 534], [617, 25, 771, 454]]
Chk 14667 [[445, 144, 599, 348], [67, 157, 337, 767], [9, 103, 138, 525], [161, 181, 356, 534]]
Chk 14668 [[175, 176, 407, 528], [347, 116, 637, 534]]
Chk 14669 [[0, 75, 49, 224], [33, 69, 77, 215], [73, 58, 122, 209], [329, 21, 499, 281], [241, 80, 289, 147], [293, 84, 345, 146], [199, 83, 243, 137], [131, 98, 188, 171]]
Chk 14670 [[229, 95, 489, 532], [338, 83, 505, 408], [242, 4, 287, 112]]
Chk 14671 [[19, 153, 81, 346], [72, 124, 172, 446], [143, 111, 238, 497], [201, 136, 265, 375], [248, 153, 293, 363], [298, 137, 365, 423]]
Chk 14672 [[0, 60, 195, 365], [191, 144, 318, 309], [309, 83, 409, 319], [355, 19, 500, 374]]
Chk 14673 [[86, 52, 394, 585], [214, 283, 462, 592], [398, 123, 742, 591]]
Chk 14674 [[404, 26, 599, 504], [149, 32, 461, 450]]
Chk 14675 [[28, 23, 231, 252], [249, 0, 411, 223], [252, 69, 500, 375]]
Chk 14676 [[97, 33, 430, 531], [362, 49, 661, 516]]
Chk 14677 [[135, 96, 399, 535], [325, 35, 692, 535]]
Chk 14678 [[234, 119, 425, 682], [121, 58, 301, 651]]
Chk 14679 [[176, 9, 274, 310], [6, 24, 83, 266], [506, 78, 791, 562], [103, 51, 162, 218], [275, 78, 341, 302], [286, 84, 666, 562]]
Chk 14680 [[447, 126, 682, 600], [121, 73, 375, 600]]
Chk 14682 [[224, 74, 383, 499], [171, 210, 250, 419], [599, 206, 749, 439]]
Chk 14683 [[478, 171, 698, 422], [42, 115, 323, 524]]
Chk 14684 [[552, 26, 799, 532], [90, 79, 332, 532]]
Chk 14685 [[301, 204, 506, 471], [353, 217, 719, 486]]
Chk 14687 [[2, 62, 175, 375], [147, 133, 387, 375], [308, 17, 500, 375], [276, 144, 355, 269], [75, 138, 160, 251]]
Chk 14688 [[166, 284, 345, 570], [322, 212, 659, 592]]
Chk 14689 [[41, 159, 340, 599], [257, 210, 427, 599]]
Chk 14690 [[42, 85, 518, 509], [344, 133, 630, 533]]
Chk 14692 [[279, 108, 409, 374], [43, 87, 219, 374]]
Chk 14693 [[400, 100, 580, 582], [147, 121, 213, 364], [215, 128, 277, 378], [233, 175, 414, 579], [69, 121, 134, 330], [363, 136, 421, 241], [588, 128, 657, 338]]
Chk 14694 [[482, 288, 632, 599], [13, 196, 273, 599], [220, 186, 410, 599]]
Chk 14695 [[0, 49, 268, 499], [455, 33, 789, 527]]
Chk 14696 [[614, 60, 725, 311], [114, 82, 323, 517], [404, 89, 587, 467], [352, 97, 462, 263], [504, 72, 610, 372]]
Chk 14697 [[224, 280, 467, 800], [261, 361, 477, 800]]
Chk 14698 [[473, 220, 573, 492], [546, 233, 696, 521]]
Chk 14699 [[13, 84, 109, 229], [236, 29, 348, 174], [276, 94, 424, 351], [385, 35, 495, 173], [429, 122, 490, 238], [369, 0, 800, 524], [0, 131, 411, 533]]
Chk 14700 [[0, 138, 225, 799], [261, 178, 518, 793]]
Chk 14701 [[98, 129, 412, 586], [422, 181, 769, 596], [267, 190, 585, 588], [647, 69, 689, 137], [2, 42, 55, 142], [205, 0, 265, 91]]
Chk 14702 [[5, 42, 366, 531], [428, 87, 799, 520]]
Chk 14705 [[81, 114, 448, 749], [357, 116, 617, 738], [226, 11, 471, 667]]
Chk 14706 [[5, 13, 369, 582], [390, 303, 702, 594], [286, 292, 459, 581], [0, 251, 156, 599]]
Chk 14707 [[253, 177, 368, 331], [370, 160, 484, 391]]
Chk 14708 [[175, 56, 499, 332], [7, 42, 321, 330]]
Chk 14709 [[188, 78, 270, 394], [28, 54, 131, 447]]
Chk 14710 [[28, 92, 400, 775], [251, 89, 510, 734], [424, 168, 520, 632]]
Chk 14711 [[206, 77, 334, 485], [24, 51, 155, 485], [327, 23, 485, 249]]
Chk 14712 [[366, 0, 786, 533], [10, 45, 417, 533], [312, 158, 466, 513]]
Chk 14713 [[158, 114, 222, 192], [101, 94, 169, 199]]
Chk 14714 [[2, 165, 448, 799], [382, 111, 791, 796]]
Chk 14715 [[210, 369, 442, 771], [341, 369, 576, 755]]
Chk 14716 [[171, 154, 419, 578], [387, 95, 644, 599]]
Chk 14717 [[39, 115, 237, 718], [157, 208, 337, 719], [300, 157, 494, 717]]
Chk 14719 [[463, 39, 758, 370], [148, 161, 582, 491]]
Chk 14720 [[650, 251, 740, 509], [596, 224, 670, 504]]
Chk 14721 [[237, 115, 441, 374], [306, 79, 447, 374]]
Chk 14722 [[17, 44, 309, 576], [393, 39, 720, 565]]
Chk 14723 [[0, 119, 387, 495], [407, 133, 673, 445]]
Chk 14724 [[367, 226, 443, 481], [262, 248, 383, 483], [29, 164, 382, 520], [610, 66, 799, 530]]
Chk 14725 [[153, 168, 384, 388], [188, 151, 582, 533], [218, 74, 800, 533]]

Chk 14727 [[123, 144, 276, 590], [414, 36, 641, 593], [271, 57, 465, 591], [42, 233, 86, 372], [97, 253, 144, 359]]
Chk 14728 [[44, 280, 350, 608], [271, 144, 673, 608], [0, 385, 47, 560], [476, 222, 683, 604]]
Chk 14729 [[444, 145, 710, 519], [14, 207, 179, 435], [160, 215, 314, 405], [315, 242, 474, 431]]
Chk 14730 [[130, 272, 695, 494], [258, 101, 656, 366]]
Chk 14732 [[10, 142, 298, 496], [354, 66, 534, 490]]
Chk 14733 [[173, 5, 399, 499], [0, 151, 202, 488]]
Chk 14734 [[0, 39, 185, 371], [272, 43, 480, 375]]
Chk 14735 [[134, 113, 257, 434], [287, 105, 385, 361], [407, 161, 552, 506]]
Chk 14736 [[258, 106, 367, 272], [90, 130, 235, 439]]
Chk 14737 [[222, 126, 305, 332], [306, 20, 449, 332], [134, 0, 266, 332], [14, 3, 139, 323], [152, 101, 439, 329], [0, 0, 56, 112]]
Chk 14738 [[71, 84, 260, 530], [530, 33, 741, 524]]
Chk 14739 [[79, 91, 328, 778], [242, 134, 489, 800]]
Chk 14740 [[298, 100, 472, 632], [196, 150, 358, 615]]
Chk 14742 [[7, 89, 322, 585], [315, 58, 688, 599]]
Chk 14743 [[79, 252, 296, 474], [0, 19, 280, 476]]
Chk 14744 [[275, 89, 603, 511], [607, 107, 799, 433], [7, 142, 343, 579]]
Chk 14745 [[330, 53, 499, 317], [55, 64, 255, 345]]
Chk 14747 [[87, 110, 537, 730], [456, 274, 662, 728]]
Chk 14748 [[184, 322, 361, 799], [0, 388, 191, 787], [3, 432, 91, 711]]
Chk 14749 [[0, 23, 371, 599], [566, 224, 746, 460], [263, 94, 657, 563], [758, 338, 799, 422]]
Chk 14751 [[115, 257, 513, 797], [63, 55, 534, 800]]
Chk 14752 [[81, 165, 330, 530], [298, 160, 496, 412], [546, 144, 740, 372], [605, 224, 718, 380]]
Chk 14753 [[276, 120, 474, 530], [167, 11, 414, 521], [406, 20, 659, 530]]
Chk 14754 [[108, 81, 390, 457], [380, 105, 592, 553], [448, 134, 731, 589]]
Chk 14755 [[110, 143, 365, 637], [358, 158, 565, 390]]
Chk 14756 [[234, 79, 448, 531], [401, 57, 541, 531]]
Chk 14757 [[0, 207, 280, 800], [141, 112, 354, 750], [226, 204, 529, 800]]
Chk 14759 [[439, 166, 555, 396], [361, 178, 461, 460], [240, 160, 335, 389], [0, 108, 331, 517]]
Chk 14760 [[87, 321, 436, 798], [151, 72, 441, 622], [5, 70, 124, 354], [402, 96, 447, 195]]
Chk 14761 [[203, 185, 444, 772], [32, 189, 235, 778], [55, 203, 97, 260]]
Chk 14762 [[209, 32, 416, 274], [0, 33, 184, 332]]
Chk 14763 [[252, 182, 376, 510], [331, 154, 519, 531], [37, 206, 127, 500], [70, 176, 337, 531], [469, 161, 691, 531], [694, 185, 799, 511], [41, 184, 118, 321]]
Chk 14764 [[189, 7, 499, 211], [389, 43, 442, 118]]
Chk 14765 [[162, 56, 799, 573], [34, 126, 466, 585]]
Chk 14766 [[29, 113, 285, 427], [242, 88, 507, 432], [537, 81, 770, 436]]
Chk 14767 [[179, 161, 226, 274], [261, 203, 373, 373], [14, 176, 197, 365]]
Chk 14768 [[183, 142, 356, 449], [342, 125, 485, 450], [638, 202, 735, 410]]
Chk 14769 [[0, 71, 89, 458], [75, 108, 207, 385], [121, 126, 379, 776], [305, 141, 535, 749], [309, 94, 397, 224], [414, 72, 484, 146]]
Chk 14770 [[110, 129, 284, 429], [332, 29, 678, 499]]
Chk 14771 [[184, 182, 408, 506], [100, 54, 382, 534], [441, 135, 659, 530], [355, 41, 725, 534]]
Chk 14772 [[5, 183, 311, 790], [227, 147, 494, 789], [0, 223, 110, 748]]
Chk 14775 [[333, 111, 565, 526], [83, 76, 408, 524]]
Chk 14776 [[318, 238, 525, 686], [143, 211, 427, 746]]
Chk 14777 [[160, 55, 378, 532], [364, 15, 623, 532]]
Chk 14778 [[257, 169, 422, 505], [335, 339, 458, 512]]
Chk 14780 [[120, 227, 270, 721], [248, 249, 400, 725]]
Chk 14781 [[136, 76, 471, 587], [390, 106, 638, 511]]
Chk 14782 [[15, 106, 409, 463], [460, 48, 798, 475]]
Chk 14783 [[11, 42, 298, 486], [273, 85, 550, 459], [581, 142, 800, 493]]
Chk 14786 [[50, 162, 177, 297], [266, 91, 422, 374], [235, 72, 345, 278]]
Chk 14787 [[207, 337, 434, 691], [345, 202, 666, 691]]
Chk 14789 [[164, 101, 315, 462], [361, 105, 530, 565], [103, 275, 187, 460], [552, 154, 641, 422]]
Chk 14790 [[309, 160, 396, 337], [299, 169, 519, 520], [481, 102, 614, 484]]
Chk 14791 [[374, 239, 588, 529], [490, 226, 784, 522], [439, 131, 511, 250]]
Chk 14792 [[188, 113, 350, 599], [527, 94, 682, 557], [99, 120, 243, 599]]
Chk 14793 [[0, 155, 280, 564], [580, 177, 775, 383]]
Chk 14794 [[187, 147, 471, 800], [42, 116, 376, 800]]
Chk 14795 [[35, 226, 371, 800], [245, 108, 530, 800]]
Chk 14796 [[65, 144, 372, 536], [242, 107, 374, 527]]
Chk 14798 [[224, 4, 340, 239], [314, 10, 604, 538]]
Chk 14799 [[209, 48, 495, 596], [369, 49, 651, 592]]
Chk 14800 [[46, 25, 116, 244], [169, 97, 399, 750], [337, 50, 579, 712]]
Chk 14801 [[0, 10, 620, 506], [23, 0, 261, 473]]
Chk 14802 [[430, 38, 799, 529], [54, 56, 385, 532]]
Chk 14803 [[243, 118, 387, 499], [130, 116, 265, 499]]
Chk 14804 [[273, 361, 323, 564], [210, 353, 268, 584], [352, 366, 395, 444]]
Chk 14806 [[58, 94, 284, 284], [204, 90, 345, 276]]
Chk 14807 [[120, 166, 259, 505], [109, 188, 204, 509]]
Chk 14808 [[176, 187, 511, 566], [77, 210, 413, 575]]
Chk 14809 [[313, 197, 456, 425], [87, 134, 268, 487], [603, 220, 739, 438]]
Chk 14810 [[231, 243, 326, 485], [317, 215, 486, 522], [404, 28, 624, 494]]
Chk 14811 [[330, 120, 632, 598], [167, 197, 356, 521]]
Chk 14812 [[432, 29, 751, 460], [45, 259, 260, 519], [340, 160, 487, 304], [138, 143, 332, 358], [305, 148, 670, 321]]
Chk 14813 [[291, 345, 503, 635], [69, 392, 312, 676]]
Chk 14814 [[140, 89, 598, 531], [405, 95, 752, 518]]
Chk 14815 [[237, 14, 799, 533], [21, 8, 536, 512]]
Chk 14816 [[85, 71, 384, 531], [389, 58, 697, 531], [310, 135, 456, 450]]
Chk 14817 [[54, 256, 405, 799], [245, 163, 447, 799]]
Chk 14819 [[93, 108, 294, 415], [309, 18, 519, 526], [477, 7, 740, 523], [56, 39, 226, 340]]
Chk 14820 [[80, 36, 463, 330], [7, 1, 268, 324]]
Chk 14821 [[17, 69, 203, 308], [145, 75, 279, 295], [271, 129, 373, 261], [335, 90, 452, 290]]
Chk 14822 [[3, 136, 350, 599], [549, 50, 799, 599], [228, 244, 394, 599]]
Chk 14823 [[138, 158, 290, 493], [284, 177, 447, 496]]
Chk 14824 [[16, 68, 269, 800], [133, 66, 420, 726]]
Chk 14825 [[0, 77, 725, 639], [226, 201, 739, 500]]
Chk 14826 [[52, 511, 303, 773], [337, 499, 518, 790], [177, 348, 312, 770]]
Chk 14827 [[219, 133, 446, 780], [2, 93, 164, 799], [189, 136, 406, 429]]
Chk 14828 [[138, 93, 382, 512], [294, 83, 605, 490]]
Chk 14829 [[184, 5, 497, 284], [430, 18, 677, 284]]
Chk 14830 [[297, 12, 774, 522], [14, 155, 479, 525]]
Chk 14832 [[329, 41, 499, 371], [0, 89, 113, 226], [109, 115, 246, 237]]
Chk 14833 [[412, 63, 724, 519], [162, 102, 344, 507], [389, 207, 454, 354], [616, 44, 753, 518]]
Chk 14835 [[53, 141, 470, 587], [445, 103, 696, 584]]
Chk 14837 [[148, 119, 323, 500], [164, 176, 288, 500], [14, 124, 212, 500]]
Chk 14838 [[49, 36, 448, 530], [506, 49, 798, 508], [260, 15, 521, 462]]
Chk 14839 [[457, 170, 549, 486], [313, 197, 396, 502], [169, 154, 281, 527]]
Chk 14840 [[9, 52, 71, 312], [92, 134, 251, 480], [173, 113, 300, 464], [98, 8, 155, 182], [271, 67, 330, 332]]
Chk 14841 [[230, 99, 513, 799], [27, 108, 394, 799], [126, 60, 431, 476]]
Chk 14842 [[252, 3, 459, 463], [362, 28, 706, 396], [262, 174, 679, 533]]
Chk 14843 [[466, 81, 636, 571], [193, 130, 351, 585], [423, 75, 496, 294]]
Chk 14844 [[545, 207, 629, 393], [585, 78, 756, 393]]
Chk 14845 [[236, 449, 277, 584], [192, 453, 237, 585]]
Chk 14847 [[0, 134, 65, 374], [212, 86, 305, 359], [343, 179, 423, 369], [143, 96, 233, 359], [377, 33, 436, 142], [14, 66, 74, 174]]
Chk 14848 [[346, 139, 643, 632], [385, 457, 573, 645]]
Chk 14850 [[398, 135, 764, 535], [43, 169, 391, 531]]
Chk 14851 [[331, 173, 762, 532], [0, 3, 137, 319], [220, 13, 527, 397]]
Chk 14852 [[0, 301, 385, 796], [192, 40, 531, 720]]
Chk 14853 [[13, 54, 270, 527], [198, 163, 371, 518], [335, 112, 506, 519], [486, 22, 781, 519]]
Chk 14854 [[465, 60, 787, 517], [346, 102, 551, 507]]
Chk 14855 [[2, 123, 278, 799], [224, 25, 517, 799]]
Chk 14857 [[343, 38, 523, 454], [177, 156, 290, 474], [15, 249, 105, 466]]
Chk 14858 [[341, 90, 765, 527], [324, 106, 524, 497]]
Chk 14859 [[605, 156, 713, 540], [651, 143, 797, 662], [521, 142, 633, 669], [366, 96, 590, 699], [102, 113, 354, 700]]
Chk 14860 [[253, 60, 334, 388], [164, 54, 262, 424], [0, 63, 218, 500]]
Chk 14861 [[126, 139, 393, 475], [487, 150, 585, 306], [378, 157, 494, 321]]
Chk 14862 [[131, 20, 788, 629], [21, 58, 447, 642]]
Chk 14863 [[463, 89, 753, 428], [82, 80, 351, 576], [0, 89, 202, 590]]
Chk 14865 [[168, 4, 361, 475], [513, 41, 676, 465], [350, 202, 481, 496], [735, 247, 784, 376]]
Chk 14866 [[118, 268, 284, 766], [258, 140, 436, 519], [18, 49, 474, 760]]

Chk 14867 [[359, 160, 436, 454], [378, 186, 479, 447]]
Chk 14868 [[49, 115, 146, 368], [84, 62, 194, 322], [172, 62, 359, 339], [330, 46, 494, 309]]
Chk 14869 [[0, 9, 108, 240], [0, 0, 350, 533], [274, 71, 470, 504], [459, 39, 800, 533]]
Chk 14870 [[107, 159, 275, 640], [164, 240, 489, 681]]
Chk 14871 [[60, 193, 179, 526], [431, 208, 519, 457], [497, 197, 553, 443]]
Chk 14872 [[476, 77, 644, 310], [401, 79, 570, 302]]
Chk 14873 [[79, 253, 302, 615], [285, 259, 516, 611], [26, 313, 71, 394]]
Chk 14874 [[194, 123, 497, 524], [504, 118, 724, 401]]
Chk 14875 [[29, 31, 224, 732], [230, 109, 571, 787]]
Chk 14876 [[60, 5, 415, 800], [0, 0, 390, 800]]
Chk 14877 [[414, 77, 694, 530], [205, 64, 414, 525]]
Chk 14878 [[361, 50, 714, 577], [135, 39, 495, 566]]
Chk 14880 [[102, 183, 470, 529], [85, 97, 486, 597]]
Chk 14881 [[336, 33, 507, 517], [526, 0, 685, 532], [195, 153, 331, 528]]
Chk 14884 [[339, 97, 700, 533], [61, 115, 433, 533], [338, 223, 388, 307]]
Chk 14886 [[173, 149, 458, 731], [0, 151, 275, 798]]
Chk 14887 [[206, 17, 341, 234], [528, 155, 683, 407], [352, 178, 516, 418], [251, 198, 448, 467], [83, 221, 395, 598]]
Chk 14888 [[3, 28, 307, 719], [227, 83, 500, 789]]
Chk 14889 [[80, 259, 326, 798], [245, 248, 534, 799]]
Chk 14891 [[17, 114, 448, 533], [330, 11, 788, 514]]
Chk 14892 [[11, 179, 403, 532], [428, 189, 787, 532]]
Chk 14893 [[71, 395, 171, 800], [298, 245, 446, 800]]
Chk 14894 [[578, 93, 799, 532], [30, 1, 231, 532], [406, 62, 587, 532], [2, 278, 94, 532]]
Chk 14895 [[192, 396, 282, 474], [292, 396, 366, 478]]
Chk 14896 [[383, 263, 504, 557], [255, 79, 396, 408]]
Chk 14897 [[0, 72, 224, 530], [261, 90, 535, 530], [495, 39, 800, 525]]
Chk 14898 [[23, 169, 153, 263], [150, 98, 282, 234], [206, 100, 381, 295]]
Chk 14900 [[83, 100, 269, 276], [181, 115, 305, 280]]
Chk 14901 [[1, 47, 241, 799], [199, 0, 549, 799]]
Chk 14902 [[52, 40, 153, 240], [337, 42, 442, 236]]
Chk 14903 [[80, 118, 393, 531], [483, 122, 666, 524], [332, 72, 596, 508], [663, 48, 730, 175]]
Chk 14904 [[46, 484, 206, 587], [165, 118, 402, 584], [423, 73, 703, 595], [641, 364, 800, 591]]
Chk 14905 [[193, 95, 454, 523], [335, 119, 537, 473]]
Chk 14906 [[12, 97, 259, 449], [319, 56, 508, 393], [612, 49, 799, 447], [323, 311, 415, 442]]
Chk 14907 [[335, 181, 556, 502], [212, 19, 450, 320]]
Chk 14908 [[248, 106, 353, 293], [83, 105, 238, 277], [222, 86, 263, 191]]
Chk 14909 [[323, 99, 581, 524], [102, 98, 373, 531]]
Chk 14910 [[247, 291, 382, 594], [247, 392, 318, 573]]
Chk 14911 [[22, 66, 185, 452], [149, 82, 498, 431], [534, 75, 768, 442]]
Chk 14912 [[7, 160, 368, 530], [364, 127, 635, 481]]
Chk 14913 [[92, 109, 254, 532], [542, 90, 648, 529]]
Chk 14915 [[133, 48, 484, 431], [298, 72, 619, 445], [547, 36, 588, 146], [395, 22, 466, 171], [587, 47, 751, 380], [564, 1, 613, 60], [667, 42, 746, 129]]
Chk 14916 [[2, 65, 186, 429], [163, 43, 289, 428]]
Chk 14917 [[92, 49, 523, 508], [299, 100, 696, 518]]
Chk 14918 [[154, 151, 474, 482], [398, 123, 778, 588], [34, 213, 107, 322], [115, 148, 251, 327]]
Chk 14919 [[190, 1, 646, 530], [399, 278, 707, 533]]
Chk 14920 [[457, 144, 636, 532], [598, 112, 768, 520], [719, 112, 783, 271]]
Chk 14921 [[429, 138, 647, 521], [83, 110, 283, 505]]
Chk 14922 [[257, 76, 376, 606], [332, 338, 446, 642]]
Chk 14923 [[495, 52, 793, 532], [29, 66, 453, 531], [0, 3, 109, 123]]
Chk 14924 [[445, 72, 664, 413], [131, 169, 308, 423]]
Chk 14925 [[465, 219, 704, 607], [107, 66, 571, 719]]
Chk 14926 [[5, 34, 311, 799], [295, 66, 530, 780]]
Chk 14927 [[159, 32, 382, 527], [315, 46, 560, 531]]
Chk 14928 [[0, 309, 343, 600], [233, 88, 618, 600], [543, 216, 800, 600]]
Chk 14929 [[27, 124, 374, 588], [119, 117, 674, 592]]
Chk 14930 [[60, 77, 426, 747], [138, 353, 517, 784]]
Chk 14931 [[233, 135, 517, 426], [233, 315, 464, 706]]
Chk 14932 [[89, 111, 456, 531], [347, 122, 674, 529]]
Chk 14933 [[60, 140, 240, 717], [86, 180, 325, 702]]
Chk 14936 [[2, 13, 323, 559], [433, 50, 752, 584]]
Chk 14937 [[73, 266, 114, 375], [177, 248, 233, 369]]
Chk 14939 [[244, 105, 423, 532], [392, 126, 614, 532], [674, 112, 800, 532], [634, 142, 727, 521], [592, 169, 652, 333], [563, 152, 610, 370]]
Chk 14940 [[361, 221, 707, 453], [93, 0, 332, 433]]
Chk 14941 [[282, 203, 513, 798], [151, 84, 326, 799]]
Chk 14942 [[316, 149, 603, 534], [292, 52, 697, 530]]
Chk 14943 [[158, 170, 396, 435], [317, 154, 474, 415]]
Chk 14944 [[87, 54, 255, 329], [68, 34, 178, 332]]
Chk 14945 [[63, 10, 334, 313], [47, 45, 471, 313]]
Chk 14946 [[173, 66, 325, 257], [202, 111, 295, 365]]
Chk 14947 [[18, 169, 599, 473], [363, 67, 598, 443]]
Chk 14948 [[92, 35, 341, 332], [162, 96, 494, 326]]
Chk 14949 [[179, 43, 436, 312], [126, 31, 379, 313]]
Chk 14950 [[72, 82, 352, 333], [251, 42, 500, 333]]
Chk 14951 [[0, 83, 189, 549], [219, 0, 511, 485]]
Chk 14952 [[0, 22, 257, 333], [5, 96, 407, 333]]
Chk 14953 [[0, 91, 336, 600], [165, 120, 356, 350], [550, 122, 798, 409]]
Chk 14954 [[19, 38, 220, 274], [326, 7, 438, 225], [149, 7, 500, 375]]
Chk 14955 [[2, 87, 273, 472], [209, 15, 496, 474], [403, 15, 711, 479]]
Chk 14956 [[408, 67, 792, 531], [222, 98, 484, 531]]
Chk 14957 [[0, 117, 501, 531], [197, 221, 565, 531], [483, 133, 800, 531]]
Chk 14958 [[78, 78, 242, 333], [275, 28, 449, 333], [250, 76, 319, 156]]
Chk 14959 [[24, 23, 610, 513], [247, 213, 798, 520]]
Chk 14960 [[142, 130, 471, 484], [236, 68, 749, 532]]
Chk 14961 [[0, 124, 701, 521], [450, 152, 799, 519]]
Chk 14965 [[12, 59, 623, 518], [301, 238, 731, 520]]
Chk 14967 [[222, 80, 534, 797], [45, 307, 219, 799]]
Chk 14968 [[331, 231, 399, 421], [240, 140, 319, 465]]
Chk 14970 [[52, 130, 163, 480], [121, 130, 214, 431], [215, 132, 324, 480]]
Chk 14971 [[216, 103, 499, 330], [27, 53, 288, 332], [206, 132, 322, 301]]
Chk 14972 [[92, 346, 229, 739], [341, 374, 523, 759], [202, 367, 353, 617]]
Chk 14973 [[201, 107, 403, 403], [348, 24, 593, 392]]
Chk 14974 [[535, 90, 799, 597], [255, 191, 654, 590], [4, 116, 291, 576]]
Chk 14975 [[40, 201, 232, 395], [196, 169, 486, 506], [443, 148, 774, 596]]
Chk 14977 [[0, 37, 135, 375], [168, 97, 257, 375], [389, 88, 489, 375], [284, 209, 375, 323]]
Chk 14978 [[43, 75, 337, 499], [211, 85, 354, 464]]
Chk 14979 [[37, 235, 304, 587], [522, 189, 775, 599], [336, 4, 624, 561], [494, 308, 612, 564], [27, 351, 84, 439]]
Chk 14980 [[301, 121, 458, 608], [178, 139, 305, 611], [87, 177, 194, 398], [195, 166, 305, 339]]
Chk 14981 [[2, 164, 177, 533], [148, 80, 453, 533], [380, 127, 630, 533], [505, 132, 659, 484]]
Chk 14982 [[229, 46, 423, 532], [393, 48, 556, 509], [408, 2, 534, 224], [260, 18, 332, 128]]
Chk 14983 [[7, 139, 206, 687], [143, 63, 503, 799]]
Chk 14986 [[274, 104, 395, 349], [123, 24, 335, 369], [381, 121, 453, 273]]
Chk 14987 [[154, 195, 366, 526], [437, 223, 606, 529], [309, 87, 487, 530]]
Chk 14988 [[245, 191, 427, 789], [130, 192, 314, 798], [81, 335, 139, 545], [4, 321, 55, 463]]
Chk 14989 [[37, 21, 419, 632], [332, 4, 788, 601]]
Chk 14990 [[11, 403, 289, 745], [148, 387, 470, 742]]
Chk 14992 [[21, 136, 444, 599], [368, 205, 706, 599], [551, 225, 780, 537]]
Chk 14993 [[391, 146, 712, 530], [223, 118, 421, 531]]
Chk 14994 [[392, 214, 515, 402], [230, 210, 361, 459]]
Chk 14995 [[118, 20, 338, 340], [0, 137, 237, 353]]
Chk 14996 [[397, 139, 560, 535], [697, 11, 799, 595], [129, 61, 459, 514]]
Chk 14997 [[0, 48, 349, 582], [467, 64, 792, 556]]
Chk 14998 [[19, 45, 150, 497], [110, 15, 273, 500], [266, 36, 318, 500]]
Chk 14999 [[81, 60, 378, 799], [399, 104, 691, 782], [601, 166, 678, 330]]
Chk 15000 [[655, 39, 793, 436], [535, 83, 613, 246], [97, 4, 533, 441], [296, 170, 589, 447], [57, 240, 105, 317], [19, 184, 60, 239]]
Chk 15001 [[537, 321, 642, 448], [690, 309, 765, 443]]
Chk 15002 [[431, 168, 780, 533], [19, 0, 800, 506]]
Chk 15003 [[0, 97, 262, 333], [119, 6, 282, 329], [280, 38, 490, 333]]
Chk 15004 [[92, 183, 191, 500], [153, 177, 262, 500]]
Chk 15005 [[361, 109, 503, 408], [458, 183, 751, 423]]
Chk 15006 [[0, 308, 305, 801], [7, 98, 510, 801]]
Chk 15007 [[433, 86, 775, 451], [368, 72, 515, 438], [134, 77, 330, 382], [513, 157, 568, 267]]
Chk 15008 [[121, 180, 181, 300], [118, 42, 430, 471], [390, 217, 710, 516], [595, 189, 734, 400]]
Chk 15009 [[257, 206, 466, 599], [426, 172, 603, 599]]
Chk 15010 [[0, 130, 282, 533], [156, 115, 328, 410], [345, 98, 531, 379], [612, 36, 731, 171], [521, 113, 728, 424], [720, 110, 800, 401]]
Chk 15011 [[440, 141, 683, 397], [27, 159, 272, 349]]
Chk 15012 [[29, 273, 176, 772], [168, 203, 346, 779]]
Chk 15013 [[6, 117, 150, 360], [108, 47, 270, 221], [123, 106, 316, 369], [273, 40, 500, 367]]
Chk 15014 [[300, 7, 568, 349], [79, 3, 332, 349]]

Chk 15015 [[278, 8, 451, 282], [0, 100, 389, 371]]
Chk 15016 [[299, 72, 615, 532], [119, 89, 372, 524], [5, 347, 83, 517]]
Chk 15017 [[0, 114, 226, 513], [225, 141, 509, 430]]
Chk 15018 [[0, 0, 244, 333], [209, 5, 500, 320]]
Chk 15019 [[309, 17, 387, 184], [478, 82, 766, 398], [35, 176, 333, 481]]
Chk 15020 [[40, 0, 277, 710], [252, 43, 437, 700], [428, 103, 482, 218], [391, 99, 435, 181]]
Chk 15021 [[425, 202, 796, 724], [19, 52, 379, 724], [211, 10, 610, 724]]
Chk 15022 [[0, 35, 319, 449], [489, 126, 791, 415]]
Chk 15023 [[0, 165, 271, 526], [340, 201, 520, 509], [473, 182, 800, 529]]
Chk 15024 [[12, 53, 82, 170], [42, 40, 235, 800], [262, 53, 475, 776]]
Chk 15026 [[395, 206, 490, 443], [257, 36, 420, 466]]
Chk 15027 [[2, 15, 534, 595], [401, 164, 800, 600], [537, 203, 800, 507]]
Chk 15028 [[37, 98, 300, 499], [190, 20, 471, 499]]
Chk 15029 [[360, 41, 799, 622], [0, 302, 340, 566]]
Chk 15030 [[66, 122, 200, 639], [182, 113, 323, 652], [354, 128, 398, 232]]
Chk 15031 [[197, 65, 340, 362], [56, 97, 205, 374], [365, 45, 499, 361]]
Chk 15032 [[76, 56, 182, 343], [442, 46, 537, 311]]
Chk 15033 [[27, 176, 73, 316], [101, 200, 156, 313], [411, 11, 570, 505], [574, 135, 776, 513], [710, 160, 757, 240]]
Chk 15034 [[345, 133, 621, 557], [33, 199, 350, 527]]
Chk 15036 [[229, 303, 364, 681], [289, 285, 424, 668]]
Chk 15037 [[382, 141, 791, 433], [196, 117, 419, 396], [639, 142, 799, 458]]
Chk 15038 [[162, 100, 250, 269], [0, 63, 239, 532], [261, 100, 388, 368], [237, 65, 589, 532], [527, 25, 800, 532], [0, 96, 69, 213]]
Chk 15039 [[415, 205, 629, 490], [270, 172, 405, 508], [576, 184, 699, 400]]
Chk 15040 [[23, 90, 175, 490], [158, 91, 332, 465], [307, 243, 375, 500]]
Chk 15041 [[138, 74, 483, 479], [50, 126, 245, 493]]
Chk 15042 [[155, 152, 456, 545], [410, 80, 717, 552]]
Chk 15043 [[169, 122, 596, 799], [19, 219, 329, 799]]
Chk 15046 [[609, 26, 784, 533], [208, 137, 381, 531]]
Chk 15047 [[5, 3, 585, 533], [378, 0, 799, 533]]
Chk 15048 [[154, 178, 440, 592], [518, 122, 667, 586]]
Chk 15049 [[106, 148, 363, 453], [331, 143, 671, 528]]
Chk 15050 [[50, 25, 301, 614], [486, 69, 766, 614], [301, 97, 579, 614], [696, 196, 772, 367]]
Chk 15051 [[0, 57, 253, 375], [347, 206, 478, 375], [326, 123, 498, 366]]
Chk 15052 [[18, 93, 288, 417], [195, 0, 503, 419]]
Chk 15054 [[3, 0, 451, 734], [305, 255, 658, 729]]
Chk 15055 [[99, 4, 514, 518], [394, 230, 653, 517], [55, 157, 122, 289], [700, 4, 794, 527]]
Chk 15056 [[234, 24, 497, 368], [102, 83, 406, 363]]
Chk 15057 [[102, 22, 478, 333], [0, 172, 404, 333]]
Chk 15058 [[59, 29, 241, 324], [88, 15, 471, 324]]
Chk 15059 [[80, 249, 305, 527], [468, 46, 782, 494], [346, 85, 642, 518]]
Chk 15060 [[0, 0, 500, 229], [0, 153, 450, 402]]
Chk 15061 [[30, 0, 314, 383], [224, 9, 489, 383]]
Chk 15062 [[196, 264, 331, 535], [59, 240, 219, 528]]
Chk 15063 [[0, 138, 646, 420], [195, 288, 619, 422]]
Chk 15065 [[304, 149, 391, 383], [184, 206, 309, 430], [12, 263, 134, 552], [548, 46, 595, 152], [555, 155, 599, 351], [326, 26, 379, 191], [0, 25, 42, 208], [37, 30, 90, 121]]
Chk 15066 [[0, 0, 350, 600], [495, 10, 800, 600], [484, 294, 555, 553], [399, 288, 487, 553]]
Chk 15067 [[468, 57, 655, 441], [297, 89, 459, 448], [58, 126, 270, 435], [733, 269, 799, 392]]
Chk 15068 [[280, 145, 512, 484], [405, 144, 795, 530], [217, 162, 298, 291], [300, 136, 350, 242]]
Chk 15069 [[158, 96, 411, 529], [436, 107, 620, 384]]
Chk 15070 [[85, 46, 494, 800], [91, 291, 556, 800]]
Chk 15071 [[23, 0, 304, 799], [263, 88, 567, 784]]
Chk 15072 [[60, 224, 498, 775], [379, 0, 799, 680]]
Chk 15073 [[155, 43, 397, 569], [175, 83, 429, 574], [378, 46, 497, 517], [457, 102, 537, 525]]
Chk 15074 [[131, 136, 344, 513], [358, 171, 506, 450], [330, 63, 800, 543]]
Chk 15075 [[5, 112, 336, 535], [240, 108, 419, 528], [472, 106, 689, 534], [632, 102, 794, 535]]
Chk 15076 [[0, 123, 264, 600], [203, 171, 409, 600], [362, 203, 447, 335], [371, 70, 611, 600], [469, 32, 800, 600]]
Chk 15077 [[0, 31, 341, 532], [604, 34, 800, 305]]
Chk 15078 [[171, 142, 435, 504], [380, 137, 636, 533], [366, 161, 797, 530]]
Chk 15079 [[229, 24, 442, 509], [469, 81, 619, 414]]
Chk 15080 [[1, 13, 390, 445], [204, 149, 598, 439]]
Chk 15082 [[310, 102, 478, 490], [84, 38, 348, 348]]
Chk 15083 [[201, 274, 363, 528], [55, 162, 245, 528]]
Chk 15084 [[93, 196, 203, 340], [412, 69, 775, 525], [236, 199, 461, 483], [315, 130, 400, 351], [444, 144, 571, 454]]
Chk 15085 [[16, 132, 400, 599], [505, 138, 795, 565]]
Chk 15087 [[576, 0, 684, 130], [199, 363, 397, 597], [30, 11, 110, 109], [310, 43, 398, 118], [519, 96, 627, 423], [445, 72, 543, 404]]
Chk 15088 [[12, 181, 149, 659], [378, 137, 510, 616]]
Chk 15089 [[38, 164, 221, 450], [244, 126, 313, 380], [175, 203, 237, 317], [337, 186, 504, 431], [491, 183, 554, 392], [500, 157, 778, 475]]
Chk 15090 [[415, 216, 583, 478], [583, 210, 716, 501], [159, 132, 454, 477], [732, 20, 784, 85]]
Chk 15091 [[6, 212, 428, 532], [477, 248, 707, 532]]
Chk 15093 [[6, 66, 383, 523], [327, 126, 723, 525]]
Chk 15094 [[5, 106, 392, 753], [306, 21, 532, 746]]
Chk 15095 [[203, 201, 429, 597], [426, 226, 600, 599], [59, 415, 205, 599]]
Chk 15096 [[11, 173, 227, 791], [275, 72, 582, 788], [250, 83, 401, 664], [509, 144, 588, 632]]
Chk 15097 [[241, 66, 410, 435], [101, 74, 285, 433]]
Chk 15098 [[20, 122, 204, 370], [171, 109, 315, 367], [206, 126, 445, 374]]
Chk 15099 [[597, 47, 799, 530], [22, 56, 292, 530], [210, 69, 445, 514]]
Chk 15100 [[545, 12, 711, 339], [392, 19, 622, 350]]
Chk 15101 [[214, 79, 503, 456], [143, 78, 285, 363], [12, 69, 96, 200], [152, 53, 204, 127], [391, 74, 438, 135], [375, 57, 419, 117], [543, 55, 662, 360], [672, 58, 800, 366]]
Chk 15102 [[0, 113, 144, 364], [216, 32, 428, 406], [275, 332, 569, 555], [286, 483, 529, 798], [198, 651, 374, 800]]
Chk 15103 [[110, 89, 319, 404], [306, 175, 467, 399], [468, 173, 600, 363], [460, 157, 785, 450]]
Chk 15104 [[226, 30, 449, 329], [80, 49, 256, 328]]
Chk 15105 [[23, 146, 299, 799], [218, 449, 431, 799], [242, 47, 519, 799]]
Chk 15106 [[19, 11, 153, 226], [209, 41, 288, 226], [329, 103, 490, 222]]
Chk 15107 [[393, 78, 634, 461], [156, 59, 413, 466]]
Chk 15108 [[165, 238, 509, 673], [3, 77, 583, 780]]
Chk 15109 [[140, 11, 407, 531], [314, 20, 643, 531]]
Chk 15110 [[685, 98, 753, 352], [606, 131, 658, 372]]
Chk 15111 [[76, 109, 661, 577], [281, 154, 477, 434]]
Chk 15112 [[313, 69, 706, 691], [118, 42, 375, 690]]
Chk 15113 [[0, 78, 251, 499], [161, 132, 374, 499]]
Chk 15114 [[60, 36, 274, 498], [306, 51, 511, 496], [531, 35, 800, 478]]
Chk 15115 [[130, 119, 598, 471], [206, 127, 449, 600]]
Chk 15116 [[174, 0, 381, 531], [269, 15, 507, 533]]
Chk 15117 [[255, 127, 387, 412], [361, 107, 519, 450]]
Chk 15118 [[31, 77, 379, 799], [334, 105, 616, 799]]
Chk 15119 [[211, 147, 413, 718], [110, 146, 328, 719]]
Chk 15120 [[122, 208, 354, 593], [500, 154, 680, 600]]
Chk 15121 [[0, 64, 275, 599], [332, 215, 608, 592], [628, 81, 800, 600]]
Chk 15122 [[293, 25, 358, 198], [378, 62, 499, 374], [24, 46, 282, 351], [144, 54, 220, 244]]
Chk 15125 [[0, 42, 175, 441], [517, 20, 798, 600]]
Chk 15126 [[406, 135, 617, 382], [719, 168, 797, 252], [206, 183, 249, 268], [26, 200, 195, 518], [589, 174, 641, 237]]
Chk 15127 [[345, 57, 561, 532], [597, 45, 799, 495], [61, 29, 292, 532]]
Chk 15128 [[8, 111, 196, 399], [81, 245, 233, 789], [226, 183, 425, 782]]
Chk 15129 [[283, 230, 406, 521], [456, 241, 612, 438], [44, 229, 188, 456]]
Chk 15130 [[15, 0, 365, 528], [478, 95, 730, 417]]
Chk 15131 [[509, 130, 686, 572], [358, 250, 502, 573]]
Chk 15132 [[91, 182, 405, 525], [357, 45, 611, 528]]
Chk 15133 [[88, 506, 278, 795], [202, 439, 313, 681], [278, 499, 391, 765]]
Chk 15135 [[414, 70, 799, 560], [30, 95, 301, 521]]
Chk 15137 [[30, 119, 470, 698], [73, 102, 454, 741], [419, 355, 732, 800]]
Chk 15138 [[217, 76, 665, 478], [42, 93, 388, 478]]
Chk 15139 [[359, 133, 799, 532], [14, 119, 240, 532]]
Chk 15141 [[59, 156, 499, 528], [498, 145, 787, 498]]
Chk 15142 [[135, 238, 279, 743], [260, 247, 421, 754], [392, 248, 444, 371]]
Chk 15143 [[63, 60, 479, 529], [372, 118, 748, 529]]
Chk 15144 [[155, 160, 368, 386], [354, 255, 563, 426], [556, 214, 698, 423]]
Chk 15145 [[29, 81, 163, 458], [184, 95, 283, 227], [247, 83, 385, 276]]
Chk 15147 [[42, 194, 569, 800], [36, 170, 561, 787]]
Chk 15148 [[462, 199, 529, 363], [661, 183, 728, 362], [191, 169, 328, 534]]
Chk 15149 [[541, 60, 664, 402], [3, 57, 57, 304], [37, 41, 180, 442], [633, 57, 755, 462]]
Chk 15150 [[54, 90, 282, 618], [319, 318, 432, 539], [211, 202, 331, 529]]
Chk 15151 [[261, 102, 363, 322], [148, 119, 283, 373]]
Chk 15152 [[3, 14, 273, 331], [156, 58, 492, 330]]

Chk 15153 [[141, 30, 789, 529], [19, 63, 434, 449]]
Chk 15154 [[522, 0, 800, 532], [449, 130, 693, 527], [19, 102, 443, 532]]
Chk 15155 [[0, 60, 316, 532], [208, 108, 749, 532]]
Chk 15156 [[92, 190, 400, 469], [119, 111, 716, 459]]
Chk 15157 [[59, 95, 343, 397], [411, 68, 675, 421]]
Chk 15158 [[279, 26, 799, 526], [53, 6, 501, 528]]
Chk 15159 [[288, 105, 398, 332], [157, 198, 240, 332], [383, 104, 428, 264], [204, 78, 309, 332], [66, 236, 153, 332]]
Chk 15160 [[215, 110, 507, 599], [363, 85, 593, 595]]
Chk 15161 [[208, 197, 570, 773], [163, 286, 365, 732]]
Chk 15162 [[308, 52, 379, 288], [184, 112, 226, 220]]
Chk 15163 [[6, 48, 397, 528], [374, 112, 732, 528]]
Chk 15164 [[384, 198, 717, 590], [73, 237, 323, 592]]
Chk 15165 [[36, 61, 239, 605], [204, 148, 331, 309], [278, 107, 473, 532], [457, 44, 772, 595]]
Chk 15168 [[153, 69, 566, 649], [509, 125, 738, 588]]
Chk 15169 [[226, 30, 652, 599], [8, 229, 341, 599]]
Chk 15171 [[17, 48, 254, 317], [315, 75, 499, 304]]
Chk 15172 [[166, 164, 466, 482], [485, 200, 758, 499]]
Chk 15173 [[387, 110, 567, 514], [27, 154, 255, 364], [400, 252, 705, 531]]
Chk 15175 [[79, 206, 264, 491], [222, 185, 519, 534], [453, 129, 779, 534]]
Chk 15176 [[384, 0, 787, 533], [208, 105, 463, 529]]
Chk 15177 [[31, 18, 273, 464], [241, 45, 472, 470]]
Chk 15178 [[28, 188, 354, 800], [280, 175, 499, 800]]
Chk 15179 [[107, 135, 435, 479], [366, 77, 689, 452]]
Chk 15182 [[303, 107, 431, 515], [656, 87, 786, 498]]
Chk 15183 [[37, 45, 437, 793], [69, 7, 479, 795]]
Chk 15185 [[314, 137, 682, 532], [349, 15, 744, 532], [9, 50, 435, 532]]
Chk 15186 [[98, 7, 206, 179], [142, 180, 389, 421], [376, 104, 565, 515]]
Chk 15187 [[530, 405, 732, 638], [192, 289, 372, 617]]
Chk 15188 [[89, 243, 326, 514], [103, 212, 461, 600], [415, 289, 648, 595], [293, 137, 725, 600]]
Chk 15189 [[23, 154, 293, 467], [184, 199, 361, 436], [391, 115, 604, 314], [577, 97, 762, 274]]
Chk 15190 [[185, 106, 338, 365], [415, 170, 473, 349], [283, 71, 354, 369], [100, 173, 143, 276]]
Chk 15191 [[300, 236, 470, 530], [507, 148, 773, 472], [642, 146, 799, 316]]
Chk 15192 [[252, 183, 521, 528], [434, 190, 701, 534]]
Chk 15193 [[94, 128, 207, 395], [37, 108, 151, 385], [363, 179, 427, 376], [441, 52, 570, 415], [666, 170, 719, 288], [752, 170, 795, 266], [600, 148, 662, 302]]
Chk 15194 [[59, 93, 434, 533], [532, 208, 712, 528]]
Chk 15195 [[379, 63, 799, 505], [2, 46, 353, 531]]
Chk 15196 [[3, 166, 156, 561], [396, 135, 715, 599], [143, 172, 392, 594], [308, 203, 444, 553]]
Chk 15197 [[260, 9, 792, 533], [0, 0, 521, 533]]
Chk 15198 [[4, 19, 306, 532], [397, 49, 643, 328]]
Chk 15199 [[37, 59, 428, 564], [270, 39, 578, 527], [371, 52, 699, 571]]
Chk 15200 [[15, 108, 179, 470], [447, 106, 759, 468]]
Chk 15201 [[112, 114, 362, 787], [309, 10, 491, 727], [358, 49, 534, 798], [236, 107, 300, 187]]
Chk 15202 [[311, 275, 375, 414], [407, 221, 481, 409], [134, 239, 230, 530]]
Chk 15204 [[163, 65, 449, 519], [265, 116, 370, 424], [335, 93, 455, 394], [424, 139, 600, 518]]
Chk 15207 [[154, 115, 447, 601], [308, 94, 669, 606]]
Chk 15208 [[0, 26, 401, 411], [371, 4, 511, 204], [610, 1, 772, 81], [401, 14, 800, 424], [69, 1, 163, 111]]
Chk 15209 [[202, 466, 286, 681], [158, 336, 327, 674]]
Chk 15210 [[74, 103, 378, 524], [410, 73, 679, 525]]
Chk 15211 [[432, 116, 611, 473], [244, 172, 440, 455]]
Chk 15212 [[321, 131, 668, 532], [624, 147, 739, 505], [279, 126, 464, 476], [116, 206, 367, 510]]
Chk 15213 [[12, 60, 422, 532], [380, 112, 761, 527], [205, 151, 510, 529], [0, 172, 64, 383], [729, 182, 788, 495], [686, 192, 771, 292], [387, 134, 443, 217]]
Chk 15214 [[109, 235, 406, 524], [329, 130, 750, 522]]
Chk 15215 [[322, 40, 401, 329], [483, 47, 592, 325], [219, 158, 309, 339], [181, 77, 330, 393]]
Chk 15216 [[83, 195, 343, 563], [245, 162, 559, 800], [111, 248, 165, 341], [319, 281, 378, 353]]
Chk 15217 [[0, 203, 73, 327], [8, 197, 163, 374], [258, 189, 500, 375], [373, 190, 431, 271], [231, 186, 321, 268], [142, 191, 210, 263]]
Chk 15218 [[404, 4, 570, 532], [481, 0, 671, 532]]
Chk 15219 [[42, 312, 278, 646], [160, 211, 346, 495], [261, 82, 493, 482]]
Chk 15220 [[414, 470, 511, 731], [297, 479, 417, 744]]
Chk 15221 [[82, 76, 374, 499], [0, 60, 227, 499]]
Chk 15222 [[143, 90, 560, 571], [307, 68, 800, 571]]
Chk 15223 [[389, 126, 537, 435], [5, 167, 270, 513], [428, 140, 671, 477], [630, 212, 789, 478]]
Chk 15225 [[278, 371, 402, 794], [62, 341, 413, 797]]
Chk 15227 [[223, 130, 492, 335], [3, 98, 271, 331], [169, 112, 330, 335]]
Chk 15228 [[386, 113, 481, 279], [261, 170, 529, 472], [464, 189, 719, 595]]
Chk 15229 [[163, 57, 382, 467], [167, 155, 568, 531]]
Chk 15230 [[65, 194, 300, 588], [447, 160, 793, 556]]
Chk 15232 [[75, 19, 435, 506], [396, 95, 738, 531]]
Chk 15233 [[0, 77, 529, 530], [297, 67, 796, 530]]
Chk 15235 [[379, 83, 692, 531], [187, 201, 375, 531], [53, 205, 303, 531]]
Chk 15236 [[0, 57, 331, 425], [38, 172, 455, 581], [337, 251, 659, 585]]
Chk 15237 [[426, 92, 785, 775], [1, 168, 138, 703]]
Chk 15238 [[47, 47, 329, 652], [368, 238, 535, 663], [436, 19, 643, 600]]
Chk 15239 [[582, 123, 740, 666], [457, 46, 702, 677]]
Chk 15240 [[216, 70, 316, 263], [336, 76, 498, 374], [9, 88, 102, 252]]
Chk 15241 [[530, 87, 779, 411], [0, 32, 260, 532], [123, 80, 433, 521]]
Chk 15242 [[526, 14, 662, 289], [355, 50, 519, 364], [60, 0, 119, 121]]
Chk 15243 [[125, 191, 385, 534], [442, 33, 653, 263]]
Chk 15244 [[389, 139, 662, 599], [19, 215, 391, 599], [189, 173, 550, 599]]
Chk 15245 [[144, 41, 245, 371], [209, 41, 327, 375]]
Chk 15246 [[636, 327, 781, 526], [377, 81, 649, 530]]
Chk 15247 [[179, 262, 344, 659], [206, 477, 315, 639]]
Chk 15249 [[12, 195, 216, 428], [150, 280, 215, 379], [256, 254, 416, 393], [421, 246, 637, 408], [631, 176, 800, 458]]
Chk 15250 [[0, 46, 343, 527], [319, 23, 745, 521]]
Chk 15251 [[0, 78, 431, 600], [361, 100, 763, 600]]
Chk 15252 [[325, 164, 643, 600], [0, 59, 332, 600], [427, 169, 500, 299]]
Chk 15254 [[151, 135, 323, 532], [302, 28, 762, 532], [4, 217, 97, 328], [200, 162, 535, 532]]
Chk 15255 [[221, 134, 361, 596], [347, 127, 484, 596], [474, 138, 647, 595]]
Chk 15256 [[0, 78, 287, 534], [466, 58, 618, 355], [363, 129, 733, 534]]
Chk 15257 [[73, 276, 401, 799], [333, 182, 799, 799], [346, 374, 598, 799]]
Chk 15258 [[246, 192, 377, 417], [343, 225, 509, 438], [412, 174, 536, 331]]
Chk 15259 [[362, 74, 771, 531], [22, 116, 590, 531]]
Chk 15262 [[238, 95, 590, 560], [62, 28, 403, 496]]
Chk 15266 [[136, 166, 564, 794], [1, 102, 292, 649]]
Chk 15267 [[54, 4, 277, 278], [247, 4, 493, 280]]
Chk 15270 [[12, 99, 260, 395], [229, 108, 482, 400], [185, 11, 286, 121], [284, 30, 381, 170]]
Chk 15271 [[319, 109, 775, 420], [59, 57, 358, 318]]
Chk 15272 [[98, 175, 184, 440], [594, 158, 706, 463], [294, 238, 423, 382], [495, 250, 578, 348]]
Chk 15273 [[161, 39, 419, 330], [32, 0, 288, 329], [389, 152, 492, 326]]
Chk 15274 [[385, 127, 491, 447], [206, 89, 458, 763], [48, 5, 282, 785]]
Chk 15275 [[49, 49, 384, 495], [621, 3, 797, 485]]
Chk 15276 [[254, 115, 800, 600], [361, 192, 510, 352]]
Chk 15277 [[0, 0, 532, 600], [438, 138, 699, 476]]
Chk 15278 [[283, 131, 799, 532], [0, 200, 345, 532]]
Chk 15280 [[444, 178, 796, 520], [261, 147, 476, 376], [4, 167, 249, 501]]
Chk 15281 [[333, 116, 661, 413], [113, 157, 284, 509]]
Chk 15282 [[77, 434, 143, 521], [82, 504, 159, 644]]
Chk 15283 [[176, 135, 408, 477], [426, 50, 672, 478]]
Chk 15284 [[67, 65, 192, 142], [120, 110, 474, 240]]
Chk 15285 [[264, 110, 583, 591], [400, 129, 755, 578]]
Chk 15286 [[58, 67, 208, 431], [132, 57, 277, 449]]
Chk 15287 [[0, 13, 383, 531], [449, 122, 778, 521]]
Chk 15288 [[298, 100, 431, 323], [42, 25, 201, 325], [164, 53, 329, 322]]
Chk 15290 [[113, 122, 342, 549], [507, 55, 735, 522]]
Chk 15291 [[157, 387, 295, 726], [226, 126, 446, 713]]
Chk 15294 [[0, 87, 401, 532], [445, 170, 741, 468]]
Chk 15295 [[211, 123, 573, 764], [11, 132, 316, 781], [396, 150, 539, 461]]
Chk 15296 [[19, 56, 533, 649], [49, 300, 593, 800]]
Chk 15297 [[54, 45, 362, 534], [315, 160, 641, 534]]
Chk 15298 [[121, 78, 524, 531], [314, 9, 739, 531]]
Chk 15299 [[224, 235, 392, 529], [399, 243, 590, 532], [737, 281, 787, 388], [107, 183, 199, 531], [591, 281, 635, 370], [16, 291, 84, 486], [192, 275, 235, 368]]
Chk 15300 [[129, 255, 366, 721], [182, 297, 373, 797]]

Chk 15303 [[29, 74, 90, 297], [159, 59, 222, 296], [353, 175, 561, 421], [691, 118, 741, 270], [544, 104, 601, 183], [110, 82, 157, 257], [436, 193, 597, 374], [307, 111, 368, 214], [626, 55, 686, 281]]
Chk 15304 [[88, 22, 446, 499], [227, 165, 404, 480]]
Chk 15305 [[148, 214, 419, 757], [141, 19, 442, 799]]
Chk 15306 [[90, 331, 520, 586], [408, 98, 595, 592], [353, 33, 527, 305]]
Chk 15308 [[224, 104, 546, 534], [499, 270, 799, 534]]
Chk 15309 [[273, 94, 546, 799], [519, 272, 597, 387], [113, 154, 331, 694], [39, 221, 93, 360], [0, 185, 44, 334], [51, 210, 140, 375]]
Chk 15310 [[251, 280, 419, 518], [61, 147, 253, 524], [325, 29, 743, 524], [0, 174, 72, 518], [8, 1, 116, 322], [679, 159, 798, 524], [259, 36, 472, 524]]
Chk 15311 [[408, 44, 793, 507], [6, 106, 388, 516], [137, 28, 671, 516]]
Chk 15312 [[0, 163, 42, 301], [65, 44, 210, 383], [20, 76, 332, 493]]
Chk 15313 [[364, 4, 765, 633], [205, 7, 472, 633]]
Chk 15314 [[0, 152, 175, 490], [295, 84, 374, 236]]
Chk 15316 [[155, 141, 366, 368], [555, 140, 746, 490]]
Chk 15319 [[133, 121, 301, 579], [380, 229, 512, 468]]
Chk 15322 [[353, 28, 699, 576], [114, 109, 428, 566]]
Chk 15323 [[0, 55, 283, 533], [145, 58, 494, 533], [210, 57, 387, 308], [482, 44, 792, 522]]
Chk 15324 [[108, 73, 321, 495], [15, 49, 239, 427]]
Chk 15325 [[620, 78, 799, 582], [473, 126, 626, 481], [161, 153, 365, 587], [259, 177, 357, 355]]
Chk 15326 [[0, 1, 240, 334], [92, 0, 500, 334], [336, 17, 454, 137]]
Chk 15329 [[580, 50, 764, 471], [397, 130, 509, 434], [312, 150, 354, 293], [350, 259, 439, 427], [367, 140, 411, 305]]
Chk 15330 [[163, 83, 220, 146], [219, 84, 362, 293], [0, 40, 243, 375]]
Chk 15331 [[412, 187, 591, 530], [231, 243, 386, 512]]
Chk 15333 [[389, 253, 612, 506], [60, 241, 198, 403], [155, 253, 388, 540]]
Chk 15334 [[71, 128, 320, 392], [371, 117, 587, 393]]
Chk 15335 [[390, 61, 799, 534], [1, 264, 235, 534], [103, 64, 476, 534], [333, 6, 487, 471]]
Chk 15337 [[398, 139, 702, 540], [104, 152, 411, 591], [250, 137, 382, 451], [430, 129, 518, 294], [585, 72, 627, 167]]
Chk 15338 [[278, 91, 423, 377], [385, 110, 623, 492], [6, 5, 72, 117], [7, 16, 171, 144]]
Chk 15339 [[0, 253, 112, 524], [266, 185, 534, 534], [433, 207, 509, 524], [471, 154, 647, 526]]
Chk 15340 [[278, 152, 475, 533], [699, 303, 799, 533], [529, 135, 689, 354]]
Chk 15341 [[10, 107, 453, 609], [311, 72, 777, 609]]
Chk 15343 [[81, 78, 297, 491], [323, 120, 517, 520]]
Chk 15344 [[53, 59, 458, 520], [122, 29, 521, 469]]
Chk 15346 [[109, 190, 355, 436], [414, 217, 712, 514]]
Chk 15347 [[221, 207, 489, 786], [58, 157, 291, 800], [5, 237, 56, 303], [404, 243, 459, 380]]
Chk 15348 [[111, 83, 252, 500], [216, 141, 343, 500]]
Chk 15349 [[258, 64, 448, 533], [471, 47, 697, 533], [0, 38, 145, 511], [80, 12, 322, 533], [688, 55, 799, 516], [475, 106, 554, 259], [492, 109, 549, 182]]
Chk 15350 [[78, 60, 378, 331], [235, 8, 442, 328]]
Chk 15351 [[6, 39, 309, 282], [309, 12, 497, 298]]
Chk 15352 [[0, 0, 464, 597], [645, 194, 799, 549], [398, 54, 714, 570]]
Chk 15353 [[140, 9, 500, 324], [50, 183, 493, 335]]
Chk 15354 [[182, 47, 457, 332], [160, 77, 332, 332]]
Chk 15355 [[41, 0, 356, 333], [128, 4, 500, 333]]
Chk 15356 [[39, 35, 346, 396], [287, 4, 587, 399]]
Chk 15357 [[122, 132, 507, 778], [21, 126, 318, 774]]
Chk 15358 [[0, 100, 379, 285], [0, 134, 442, 322]]
Chk 15360 [[72, 82, 283, 479], [0, 47, 310, 494]]
Chk 15362 [[423, 85, 716, 533], [39, 142, 292, 533], [266, 103, 485, 533]]
Chk 15363 [[217, 89, 344, 355], [269, 120, 401, 373]]
Chk 15364 [[196, 63, 395, 303], [344, 80, 499, 326], [0, 96, 230, 321]]
Chk 15365 [[31, 125, 212, 500], [191, 66, 320, 499]]
Chk 15366 [[203, 113, 719, 793], [0, 104, 354, 792]]
Chk 15367 [[0, 0, 209, 373], [129, 162, 182, 295], [196, 149, 281, 322], [281, 113, 411, 374], [321, 73, 495, 374]]
Chk 15368 [[594, 81, 799, 534], [375, 71, 601, 534], [213, 44, 396, 534], [0, 57, 226, 534]]
Chk 15369 [[453, 202, 573, 508], [284, 148, 420, 554], [30, 246, 223, 535]]
Chk 15370 [[5, 448, 331, 767], [276, 391, 524, 768]]
Chk 15371 [[342, 57, 769, 618], [76, 266, 399, 602], [82, 101, 277, 354]]
Chk 15372 [[41, 137, 192, 612], [243, 281, 519, 711]]
Chk 15373 [[143, 25, 338, 497], [42, 13, 205, 499]]
Chk 15374 [[99, 58, 544, 600], [358, 28, 651, 582]]
Chk 15375 [[0, 202, 127, 800], [235, 161, 487, 494], [85, 84, 548, 800]]
Chk 15376 [[0, 0, 311, 576], [475, 74, 798, 584], [418, 58, 790, 584], [146, 232, 531, 584]]
Chk 15377 [[164, 202, 314, 527], [329, 183, 508, 410], [567, 380, 701, 529]]
Chk 15378 [[416, 7, 658, 567], [281, 46, 478, 517]]
Chk 15379 [[0, 0, 285, 499], [155, 122, 308, 403], [228, 61, 443, 428]]
Chk 15380 [[0, 61, 321, 384], [182, 171, 256, 256], [238, 60, 500, 389], [410, 59, 472, 211]]
Chk 15381 [[35, 167, 322, 525], [301, 125, 800, 531], [420, 172, 500, 338]]
Chk 15382 [[133, 344, 244, 599], [514, 384, 594, 603], [220, 369, 328, 583]]
Chk 15383 [[454, 18, 796, 581], [140, 5, 408, 412]]
Chk 15384 [[461, 229, 783, 595], [0, 268, 256, 592]]
Chk 15386 [[119, 126, 343, 534], [354, 165, 570, 531], [732, 227, 800, 525]]
Chk 15387 [[127, 253, 334, 795], [236, 313, 365, 781]]
Chk 15388 [[472, 196, 676, 409], [6, 173, 140, 414], [268, 202, 478, 431]]
Chk 15389 [[232, 82, 548, 533], [376, 35, 705, 526]]
Chk 15390 [[361, 69, 719, 508], [185, 167, 422, 498]]
Chk 15391 [[314, 51, 669, 475], [26, 24, 550, 477]]
Chk 15394 [[147, 78, 347, 390], [341, 170, 555, 533]]
Chk 15395 [[485, 218, 593, 439], [376, 231, 507, 475]]
Chk 15397 [[371, 177, 481, 422], [403, 169, 556, 445]]
Chk 15398 [[204, 125, 315, 305], [304, 122, 463, 333], [26, 21, 136, 271], [115, 131, 211, 317]]
Chk 15399 [[269, 206, 548, 599], [524, 258, 786, 599], [23, 234, 330, 588]]
Chk 15401 [[418, 15, 791, 599], [15, 88, 432, 583], [0, 148, 50, 386], [360, 172, 401, 273], [747, 162, 799, 304]]
Chk 15402 [[195, 22, 464, 528], [456, 176, 746, 506], [420, 131, 629, 396]]
Chk 15403 [[143, 194, 482, 526], [417, 99, 665, 516]]
Chk 15404 [[398, 0, 799, 599], [201, 19, 494, 599]]
Chk 15405 [[213, 127, 263, 278], [280, 104, 335, 272], [142, 126, 206, 306]]
Chk 15406 [[165, 130, 556, 510], [389, 133, 604, 373], [468, 155, 626, 363]]
Chk 15407 [[335, 244, 622, 547], [206, 37, 486, 520]]
Chk 15408 [[153, 107, 406, 528], [354, 116, 669, 532]]
Chk 15409 [[503, 268, 703, 586], [192, 254, 568, 593], [58, 227, 245, 599], [703, 261, 799, 587], [1, 229, 77, 355], [3, 229, 83, 592]]
Chk 15410 [[41, 74, 205, 332], [225, 18, 373, 332], [363, 0, 492, 319], [151, 94, 204, 173]]
Chk 15411 [[317, 87, 500, 557], [551, 74, 754, 588], [43, 91, 335, 585], [0, 136, 45, 244], [480, 138, 546, 364], [34, 156, 86, 241]]
Chk 15412 [[392, 81, 696, 492], [132, 224, 434, 495], [723, 279, 799, 506], [651, 228, 720, 495], [741, 291, 798, 374]]
Chk 15413 [[95, 214, 245, 370], [288, 142, 399, 365], [43, 22, 137, 233], [348, 134, 477, 351], [16, 164, 85, 234]]
Chk 15415 [[447, 262, 633, 544], [244, 220, 451, 510]]
Chk 15416 [[114, 100, 481, 496], [487, 54, 800, 482]]
Chk 15418 [[5, 0, 353, 783], [287, 198, 519, 785]]
Chk 15419 [[57, 69, 455, 533], [210, 95, 462, 472]]
Chk 15420 [[115, 115, 310, 559], [231, 211, 397, 579], [314, 121, 620, 600]]
Chk 15421 [[0, 107, 375, 800], [309, 107, 639, 800]]
Chk 15423 [[118, 23, 363, 546], [430, 42, 766, 565]]
Chk 15424 [[389, 109, 756, 639], [190, 90, 472, 639]]
Chk 15425 [[0, 25, 264, 331], [183, 7, 500, 327]]
Chk 15426 [[97, 127, 189, 271], [183, 143, 298, 468]]
Chk 15427 [[396, 62, 633, 601], [106, 60, 336, 434]]
Chk 15429 [[334, 74, 524, 325], [272, 96, 432, 337], [47, 2, 219, 334]]
Chk 15430 [[194, 54, 537, 531], [401, 41, 781, 531]]
Chk 15432 [[335, 213, 588, 502], [518, 175, 778, 521], [53, 6, 338, 496]]
Chk 15433 [[74, 131, 450, 610], [404, 53, 761, 566]]
Chk 15434 [[257, 188, 325, 390], [241, 199, 523, 791], [48, 258, 264, 799]]
Chk 15435 [[73, 74, 288, 795], [263, 81, 451, 752], [191, 70, 376, 628], [321, 62, 372, 135]]
Chk 15436 [[8, 150, 354, 535], [445, 170, 788, 537], [322, 462, 381, 537]]
Chk 15437 [[248, 127, 462, 398], [605, 217, 715, 431], [403, 252, 633, 433], [709, 35, 772, 101]]
Chk 15438 [[250, 62, 386, 333], [305, 56, 491, 332]]
Chk 15439 [[354, 17, 502, 428], [527, 177, 678, 500]]
Chk 15441 [[0, 80, 142, 285], [334, 77, 480, 271], [181, 75, 370, 278]]
Chk 15442 [[551, 60, 730, 532], [177, 93, 385, 532], [359, 92, 498, 431]]
Chk 15443 [[0, 107, 371, 503], [289, 33, 671, 515]]
Chk 15444 [[71, 55, 250, 333], [274, 62, 485, 333]]

Chk 15445 [[248, 82, 409, 486], [59, 136, 158, 523], [397, 63, 529, 571]]
Chk 15446 [[0, 11, 313, 532], [330, 54, 794, 523]]
Chk 15447 [[303, 122, 589, 406], [542, 98, 799, 501], [18, 101, 334, 344]]
Chk 15448 [[273, 28, 645, 610], [103, 256, 502, 625]]
Chk 15449 [[45, 74, 358, 599], [443, 4, 766, 599]]
Chk 15450 [[203, 2, 662, 648], [442, 45, 669, 580], [173, 62, 481, 492]]
Chk 15451 [[105, 48, 338, 570], [379, 82, 621, 562]]
Chk 15453 [[174, 28, 291, 333], [229, 9, 303, 330], [441, 116, 493, 229]]
Chk 15454 [[191, 54, 398, 600], [261, 92, 800, 600]]
Chk 15455 [[0, 72, 346, 373], [196, 51, 481, 368], [380, 43, 495, 366], [198, 74, 333, 330]]
Chk 15456 [[106, 184, 422, 600], [275, 190, 501, 600]]
Chk 15457 [[140, 44, 284, 272], [27, 68, 152, 332]]
Chk 15458 [[15, 105, 377, 680], [326, 94, 552, 650], [456, 119, 727, 679], [723, 125, 784, 347], [0, 242, 42, 397], [3, 104, 46, 319], [134, 93, 181, 165]]
Chk 15459 [[180, 30, 548, 522], [449, 144, 783, 532]]
Chk 15460 [[3, 58, 319, 556], [184, 138, 522, 551]]
Chk 15461 [[2, 90, 312, 595], [386, 114, 631, 599], [234, 113, 403, 600]]
Chk 15462 [[122, 0, 799, 520], [0, 18, 442, 532]]
Chk 15463 [[246, 175, 375, 500], [66, 137, 271, 500], [39, 43, 275, 466], [234, 62, 322, 275], [62, 74, 107, 220], [0, 72, 47, 141]]
Chk 15464 [[176, 50, 419, 334], [278, 0, 493, 334]]
Chk 15465 [[7, 0, 284, 331], [234, 125, 497, 331]]
Chk 15466 [[336, 75, 477, 537], [221, 80, 354, 536]]
Chk 15467 [[158, 0, 500, 539], [0, 44, 312, 549]]
Chk 15468 [[137, 171, 368, 408], [19, 2, 237, 411]]
Chk 15469 [[113, 22, 391, 347], [203, 115, 381, 319]]
Chk 15470 [[12, 72, 365, 785], [195, 220, 535, 791]]
Chk 15471 [[6, 55, 208, 333], [241, 42, 431, 336]]
Chk 15472 [[453, 189, 588, 453], [319, 217, 544, 494]]
Chk 15473 [[0, 10, 535, 594], [456, 103, 691, 508]]
Chk 15474 [[0, 138, 187, 522], [563, 234, 789, 522], [70, 167, 645, 522]]
Chk 15475 [[192, 44, 430, 451], [24, 204, 231, 584], [20, 112, 136, 242], [745, 232, 799, 326], [472, 207, 620, 437], [493, 267, 799, 583]]
Chk 15476 [[531, 98, 676, 467], [338, 111, 505, 473]]
Chk 15477 [[4, 112, 366, 725], [3, 168, 58, 391], [259, 184, 382, 339], [342, 79, 728, 692], [391, 141, 447, 228]]
Chk 15478 [[61, 80, 160, 393], [116, 74, 206, 399]]
Chk 15479 [[6, 107, 184, 346], [180, 99, 347, 318], [22, 37, 67, 99], [365, 108, 499, 322]]
Chk 15481 [[328, 186, 524, 529], [484, 176, 761, 528], [137, 203, 331, 483]]
Chk 15482 [[0, 23, 190, 355], [337, 69, 499, 248]]
Chk 15483 [[509, 188, 719, 453], [306, 165, 471, 459], [113, 193, 277, 541]]
Chk 15484 [[74, 97, 508, 597], [379, 179, 568, 592]]
Chk 15485 [[292, 193, 517, 529], [504, 177, 594, 427], [567, 115, 790, 529], [35, 55, 310, 505]]
Chk 15486 [[176, 141, 538, 534], [0, 142, 219, 528]]
Chk 15487 [[148, 66, 378, 526], [298, 91, 499, 532]]
Chk 15488 [[211, 186, 366, 571], [362, 206, 477, 555], [464, 199, 613, 587]]
Chk 15489 [[195, 217, 395, 620], [103, 232, 245, 600]]
Chk 15490 [[145, 5, 351, 501], [564, 73, 773, 501]]
Chk 15491 [[62, 149, 338, 545], [225, 118, 506, 537]]
Chk 15492 [[146, 92, 427, 523], [374, 33, 680, 563]]
Chk 15493 [[233, 126, 660, 510], [20, 128, 271, 515]]
Chk 15494 [[284, 86, 467, 332], [51, 114, 264, 332]]
Chk 15495 [[448, 17, 763, 607], [70, 104, 365, 611], [266, 39, 550, 611]]
Chk 15496 [[39, 297, 314, 609], [350, 130, 617, 475]]
Chk 15497 [[475, 125, 594, 528], [352, 116, 478, 511], [74, 89, 215, 532]]
Chk 15498 [[155, 121, 259, 430], [93, 148, 194, 430]]
Chk 15499 [[217, 169, 339, 476], [309, 200, 453, 488]]
Chk 15501 [[190, 64, 425, 745], [15, 32, 220, 661]]
Chk 15502 [[141, 136, 352, 575], [393, 139, 484, 543], [311, 154, 409, 546]]
Chk 15503 [[287, 125, 636, 409], [126, 96, 424, 428]]
Chk 15504 [[52, 80, 240, 599], [365, 53, 760, 585]]
Chk 15507 [[188, 171, 434, 534], [68, 224, 213, 534]]
Chk 15508 [[381, 155, 563, 528], [556, 108, 787, 525], [8, 23, 297, 509], [721, 189, 795, 434], [512, 68, 625, 530]]
Chk 15509 [[401, 112, 799, 533], [224, 145, 612, 533]]
Chk 15510 [[113, 80, 330, 429], [446, 62, 535, 146], [601, 33, 738, 249], [443, 93, 685, 361]]
Chk 15511 [[443, 134, 646, 508], [151, 183, 375, 521]]
Chk 15512 [[614, 191, 736, 491], [201, 150, 339, 478], [34, 144, 161, 510], [505, 184, 647, 571]]
Chk 15513 [[64, 128, 385, 513], [421, 115, 670, 508], [346, 272, 571, 529]]
Chk 15515 [[272, 152, 711, 599], [113, 164, 500, 599]]
Chk 15516 [[72, 295, 274, 599], [42, 189, 126, 383], [95, 149, 314, 439], [14, 197, 59, 340]]
Chk 15517 [[51, 131, 170, 441], [165, 125, 255, 435], [230, 105, 292, 366], [172, 81, 255, 180]]
Chk 15518 [[19, 95, 437, 531], [342, 72, 629, 531]]
Chk 15519 [[205, 49, 330, 327], [310, 88, 412, 331], [55, 206, 107, 333]]
Chk 15520 [[24, 113, 609, 527], [568, 13, 799, 517], [0, 47, 178, 530]]
Chk 15522 [[43, 125, 249, 306], [185, 0, 382, 311], [356, 142, 489, 266]]
Chk 15524 [[251, 74, 373, 424], [461, 96, 701, 436]]
Chk 15525 [[399, 67, 610, 342], [43, 107, 225, 523], [600, 197, 717, 333]]
Chk 15526 [[187, 93, 407, 527], [4, 111, 263, 531], [431, 1, 799, 532]]
Chk 15527 [[141, 0, 540, 449], [354, 2, 799, 449]]
Chk 15528 [[108, 292, 262, 799], [224, 302, 358, 794]]
Chk 15529 [[7, 101, 608, 517], [214, 23, 572, 456]]
Chk 15531 [[0, 0, 270, 147], [0, 70, 197, 232]]
Chk 15532 [[243, 20, 464, 374], [482, 149, 574, 297], [647, 224, 699, 306], [589, 218, 650, 306], [5, 179, 66, 292], [47, 185, 89, 268], [78, 150, 131, 209]]
Chk 15533 [[203, 52, 368, 334], [311, 31, 423, 334], [400, 94, 483, 326], [169, 151, 210, 221]]
Chk 15534 [[349, 148, 617, 713], [161, 152, 425, 688]]
Chk 15535 [[106, 225, 223, 514], [535, 237, 698, 539]]
Chk 15536 [[58, 203, 247, 518], [313, 236, 507, 461], [196, 173, 509, 458]]
Chk 15537 [[29, 51, 360, 490], [387, 123, 645, 403]]
Chk 15539 [[143, 127, 414, 434], [400, 154, 657, 459], [313, 72, 465, 344], [516, 170, 625, 324], [674, 84, 767, 292], [640, 181, 707, 286]]
Chk 15540 [[61, 45, 150, 325], [262, 54, 446, 332]]
Chk 15541 [[141, 108, 334, 566], [248, 64, 541, 550]]
Chk 15542 [[89, 63, 336, 375], [1, 85, 376, 360]]
Chk 15543 [[0, 46, 306, 500], [73, 191, 395, 464], [221, 0, 500, 500]]
Chk 15545 [[399, 77, 725, 517], [223, 153, 444, 519]]
Chk 15547 [[111, 118, 229, 418], [101, 162, 168, 351]]
Chk 15548 [[433, 128, 791, 599], [2, 117, 266, 555], [166, 138, 372, 599], [428, 262, 496, 495], [383, 224, 433, 320]]
Chk 15549 [[140, 112, 512, 558], [459, 250, 677, 558]]
Chk 15550 [[111, 197, 236, 530], [341, 153, 475, 290]]
Chk 15552 [[6, 15, 269, 374], [130, 60, 467, 375]]
Chk 15553 [[508, 100, 788, 437], [10, 114, 219, 521]]
Chk 15554 [[207, 104, 400, 283], [451, 71, 671, 302]]
Chk 15555 [[77, 104, 437, 599], [414, 62, 743, 599]]
Chk 15556 [[276, 37, 442, 361], [175, 93, 282, 313]]
Chk 15557 [[360, 129, 535, 449], [563, 162, 730, 449], [1, 107, 199, 449], [138, 99, 354, 443]]
Chk 15558 [[105, 133, 452, 535], [429, 52, 800, 535], [10, 215, 170, 535]]
Chk 15559 [[73, 37, 349, 507], [377, 14, 758, 506]]
Chk 15560 [[2, 96, 478, 585], [468, 50, 763, 584]]
Chk 15561 [[252, 73, 503, 765], [63, 72, 280, 783]]
Chk 15562 [[14, 0, 157, 543], [275, 131, 388, 445], [382, 94, 614, 551], [0, 100, 106, 551]]
Chk 15563 [[461, 157, 793, 571], [86, 163, 344, 412]]
Chk 15564 [[21, 62, 396, 533], [312, 19, 783, 533]]
Chk 15565 [[116, 290, 572, 799], [0, 0, 302, 799]]
Chk 15566 [[50, 88, 364, 530], [603, 106, 788, 530]]
Chk 15567 [[265, 9, 459, 319], [0, 36, 239, 333]]
Chk 15568 [[18, 51, 195, 405], [159, 39, 500, 405]]
Chk 15569 [[62, 0, 259, 259], [176, 152, 463, 338], [365, 17, 499, 336]]
Chk 15570 [[2, 237, 203, 563], [39, 232, 457, 588], [298, 204, 577, 538]]
Chk 15571 [[509, 156, 800, 597], [0, 157, 568, 600], [3, 88, 289, 432]]
Chk 15572 [[81, 16, 242, 299], [237, 0, 500, 329]]
Chk 15573 [[12, 32, 144, 214], [185, 18, 386, 274]]
Chk 15574 [[0, 2, 267, 300], [266, 0, 478, 300]]
Chk 15575 [[284, 133, 396, 364], [172, 169, 289, 364], [230, 124, 325, 218]]
Chk 15576 [[417, 105, 800, 531], [98, 242, 800, 531]]
Chk 15577 [[308, 142, 526, 483], [69, 106, 308, 744], [106, 132, 461, 543]]
Chk 15578 [[88, 106, 288, 520], [170, 148, 359, 531]]
Chk 15579 [[310, 118, 445, 374], [93, 130, 196, 374], [163, 154, 246, 374]]
Chk 15581 [[1, 67, 100, 480], [187, 25, 350, 473], [281, 202, 331, 294]]
Chk 15582 [[34, 300, 239, 677], [232, 308, 432, 681], [576, 329, 788, 680], [412, 174, 595, 499], [359, 27, 654, 502]]
Chk 15583 [[313, 56, 659, 517], [53, 75, 437, 521]]
Chk 15584 [[96, 19, 322, 800], [201, 255, 417, 800], [304, 163, 382, 250], [375, 178, 506, 472]]
Chk 15585 [[323, 183, 638, 535], [469, 64, 751, 532]]
Chk 15586 [[114, 105, 306, 374], [227, 156, 390, 374]]
Chk 15587 [[104, 116, 285, 599], [390, 287, 772, 599]]

Chk 15588 [[384, 92, 721, 641], [60, 49, 401, 640], [358, 242, 409, 392], [294, 214, 353, 349]]
Chk 15589 [[569, 188, 787, 532], [8, 135, 185, 532], [230, 70, 549, 521], [130, 136, 293, 519], [284, 50, 433, 363]]
Chk 15590 [[706, 196, 790, 408], [238, 86, 434, 527], [553, 171, 692, 520], [512, 165, 586, 386], [339, 189, 549, 496], [584, 115, 646, 217]]
Chk 15591 [[29, 35, 191, 295], [303, 124, 370, 247], [189, 140, 267, 223]]
Chk 15592 [[314, 10, 403, 241], [412, 94, 470, 156], [0, 139, 163, 335], [174, 115, 347, 278]]
Chk 15593 [[4, 0, 111, 170], [89, 110, 262, 333], [108, 269, 324, 481], [190, 488, 448, 723], [260, 580, 582, 800]]
Chk 15594 [[146, 16, 320, 460], [306, 66, 516, 400], [579, 17, 746, 360]]
Chk 15595 [[8, 79, 329, 578], [499, 67, 799, 596], [338, 100, 636, 538], [244, 141, 391, 487]]
Chk 15596 [[54, 110, 301, 428], [382, 119, 570, 406], [534, 95, 786, 449], [704, 72, 800, 188], [465, 53, 575, 162]]
Chk 15597 [[563, 53, 775, 272], [3, 8, 399, 532], [377, 50, 625, 388]]
Chk 15598 [[384, 133, 714, 523], [0, 58, 230, 532]]
Chk 15599 [[103, 41, 417, 633], [364, 116, 684, 631]]
Chk 15600 [[0, 52, 358, 566], [123, 149, 261, 371], [274, 20, 468, 375], [460, 125, 774, 503]]
Chk 15601 [[12, 48, 318, 800], [216, 60, 487, 800], [407, 75, 600, 789], [354, 74, 419, 194]]
Chk 15602 [[238, 289, 348, 554], [162, 293, 236, 494]]
Chk 15603 [[374, 60, 542, 568], [303, 120, 483, 595]]
Chk 15605 [[371, 130, 542, 535], [305, 79, 514, 535]]
Chk 15606 [[528, 138, 681, 449], [429, 77, 633, 440]]
Chk 15607 [[104, 243, 396, 800], [293, 285, 656, 800]]
Chk 15608 [[64, 137, 184, 479], [662, 145, 786, 485], [238, 144, 351, 520], [342, 110, 439, 480]]
Chk 15609 [[181, 1, 397, 296], [575, 46, 764, 250], [0, 55, 201, 444]]
Chk 15610 [[225, 96, 583, 796], [365, 103, 586, 404], [35, 92, 241, 621]]
Chk 15611 [[147, 99, 337, 452], [409, 70, 619, 453]]
Chk 15612 [[158, 379, 342, 509], [347, 251, 446, 564], [551, 415, 689, 564], [448, 257, 557, 501], [282, 45, 459, 477]]
Chk 15613 [[438, 52, 799, 503], [321, 167, 540, 502], [39, 102, 351, 508], [538, 184, 604, 277], [482, 171, 563, 323]]
Chk 15614 [[52, 197, 315, 694], [156, 172, 465, 773]]
Chk 15615 [[6, 158, 272, 616], [377, 84, 639, 622]]
Chk 15616 [[436, 208, 538, 533], [495, 200, 621, 533]]
Chk 15617 [[461, 219, 615, 532], [139, 85, 370, 489]]
Chk 15618 [[0, 217, 357, 600], [4, 69, 337, 600], [320, 217, 570, 600], [314, 93, 698, 600]]
Chk 15620 [[246, 31, 799, 531], [71, 0, 488, 510]]
Chk 15621 [[39, 31, 230, 441], [197, 44, 377, 416]]
Chk 15622 [[129, 46, 586, 594], [534, 1, 784, 264]]
Chk 15623 [[86, 42, 477, 583], [342, 72, 764, 582]]
Chk 15624 [[140, 18, 419, 534], [336, 96, 633, 534]]
Chk 15625 [[31, 114, 286, 509], [387, 183, 530, 519], [235, 126, 444, 529], [703, 247, 793, 358], [536, 242, 755, 515]]
Chk 15626 [[2, 61, 129, 530], [218, 8, 462, 496], [391, 42, 480, 190], [272, 160, 454, 519], [563, 65, 697, 505], [708, 20, 800, 525]]
Chk 15627 [[70, 106, 713, 592], [388, 176, 795, 572]]
Chk 15628 [[86, 20, 476, 573], [128, 167, 454, 477], [419, 141, 606, 542], [550, 167, 777, 545]]
Chk 15629 [[24, 79, 292, 544], [169, 197, 539, 800]]
Chk 15630 [[9, 19, 423, 574], [463, 80, 756, 465]]
Chk 15631 [[94, 136, 535, 538], [362, 24, 684, 538], [409, 4, 592, 312]]
Chk 15632 [[110, 122, 218, 408], [228, 56, 345, 464]]
Chk 15633 [[0, 2, 414, 621], [161, 298, 460, 605], [400, 21, 639, 591]]
Chk 15635 [[54, 80, 323, 450], [229, 56, 425, 443], [360, 96, 407, 174], [476, 112, 590, 240], [475, 175, 579, 271], [494, 72, 779, 443]]
Chk 15636 [[193, 55, 533, 790], [21, 148, 324, 799]]
Chk 15637 [[26, 5, 143, 252], [147, 16, 308, 526], [277, 49, 401, 500], [461, 24, 650, 528]]
Chk 15638 [[0, 2, 298, 528], [255, 94, 542, 520]]
Chk 15640 [[32, 152, 337, 593], [226, 266, 466, 593], [229, 33, 740, 593]]
Chk 15641 [[32, 163, 458, 619], [247, 107, 482, 619], [432, 78, 794, 607]]
Chk 15642 [[126, 80, 248, 486], [23, 80, 122, 445]]
Chk 15643 [[395, 204, 522, 475], [58, 212, 168, 549]]
Chk 15644 [[541, 140, 722, 529], [85, 115, 292, 518], [376, 66, 570, 529], [219, 27, 447, 529]]
Chk 15645 [[370, 226, 471, 533], [317, 211, 414, 534]]
Chk 15646 [[205, 88, 324, 369], [565, 216, 642, 409]]
Chk 15647 [[0, 55, 322, 202], [68, 129, 470, 333]]
Chk 15648 [[49, 112, 320, 533], [305, 111, 708, 533], [733, 231, 776, 294]]
Chk 15650 [[184, 103, 432, 534], [456, 107, 799, 534]]
Chk 15651 [[440, 213, 799, 599], [32, 210, 309, 599]]
Chk 15652 [[198, 184, 313, 628], [260, 146, 469, 582]]
Chk 15653 [[0, 69, 427, 511], [388, 103, 791, 432]]
Chk 15654 [[195, 296, 459, 599], [254, 44, 627, 599], [447, 96, 622, 484]]
Chk 15655 [[27, 158, 118, 334], [196, 291, 326, 726], [68, 264, 217, 675]]
Chk 15656 [[495, 0, 735, 522], [448, 83, 562, 492]]
Chk 15657 [[72, 62, 378, 539], [437, 212, 538, 365], [475, 25, 800, 539]]
Chk 15658 [[229, 95, 526, 507], [246, 20, 289, 131], [560, 74, 781, 505], [20, 92, 377, 507], [709, 52, 798, 452], [488, 99, 597, 238], [418, 117, 567, 501], [1, 50, 159, 271]]
Chk 15659 [[195, 168, 639, 584], [452, 128, 725, 575]]
Chk 15660 [[0, 13, 166, 375], [222, 40, 371, 375], [305, 108, 466, 375]]
Chk 15661 [[42, 213, 330, 529], [444, 5, 799, 530], [225, 198, 563, 527], [147, 8, 204, 73]]
Chk 15662 [[402, 244, 564, 380], [563, 144, 675, 522], [121, 238, 213, 343]]
Chk 15664 [[49, 309, 405, 800], [283, 269, 533, 800], [201, 211, 368, 476], [0, 199, 199, 692]]
Chk 15665 [[308, 238, 702, 600], [172, 103, 794, 600]]
Chk 15666 [[140, 35, 223, 195], [249, 40, 418, 486], [345, 86, 499, 486]]
Chk 15667 [[276, 127, 799, 592], [22, 129, 555, 599]]
Chk 15668 [[49, 376, 128, 676], [119, 367, 279, 800], [233, 376, 356, 800]]
Chk 15669 [[21, 122, 369, 595], [556, 100, 799, 599]]
Chk 15670 [[260, 89, 493, 374], [4, 89, 288, 374]]
Chk 15671 [[316, 46, 772, 565], [37, 97, 481, 586]]
Chk 15672 [[18, 135, 244, 531], [140, 163, 565, 531], [693, 440, 745, 494]]
Chk 15674 [[170, 115, 384, 699], [33, 141, 240, 621], [424, 116, 468, 174], [27, 114, 84, 274]]
Chk 15675 [[27, 41, 217, 592], [127, 86, 387, 596], [386, 80, 530, 333], [367, 103, 694, 596]]
Chk 15676 [[498, 20, 740, 532], [257, 37, 439, 531], [366, 104, 557, 533], [46, 122, 263, 525], [65, 46, 261, 478]]
Chk 15677 [[343, 165, 466, 533], [155, 155, 289, 530], [625, 162, 796, 533], [444, 276, 489, 356]]
Chk 15679 [[302, 185, 656, 719], [208, 280, 428, 718]]
Chk 15680 [[311, 511, 415, 740], [26, 521, 120, 685], [460, 513, 599, 731], [117, 513, 235, 729]]
Chk 15681 [[489, 88, 660, 379], [561, 79, 709, 357]]
Chk 15682 [[491, 150, 675, 512], [348, 131, 562, 507]]
Chk 15683 [[151, 166, 304, 322], [459, 130, 677, 600]]
Chk 15684 [[23, 71, 400, 644], [315, 97, 716, 644]]
Chk 15685 [[248, 7, 563, 800], [0, 74, 412, 800]]
Chk 15686 [[466, 489, 756, 716], [580, 464, 721, 662]]
Chk 15687 [[31, 174, 311, 444], [459, 39, 788, 463]]
Chk 15688 [[56, 54, 514, 509], [269, 87, 673, 525]]
Chk 15689 [[52, 57, 317, 369], [290, 0, 499, 373]]
Chk 15691 [[0, 27, 68, 352], [67, 72, 214, 410], [311, 64, 374, 499], [174, 47, 343, 489]]
Chk 15692 [[292, 65, 448, 305], [99, 44, 254, 360]]
Chk 15693 [[84, 10, 222, 237], [257, 21, 452, 333]]
Chk 15694 [[39, 104, 201, 310], [190, 100, 307, 271], [326, 124, 438, 252]]
Chk 15695 [[32, 80, 91, 193], [139, 71, 199, 215], [56, 14, 365, 348]]
Chk 15696 [[106, 22, 333, 400], [53, 172, 287, 466]]
Chk 15697 [[14, 84, 274, 498], [117, 139, 215, 470], [123, 127, 339, 499]]
Chk 15698 [[173, 113, 331, 448], [436, 228, 621, 442], [612, 221, 760, 458]]
Chk 15699 [[88, 229, 301, 333], [223, 41, 375, 332], [389, 144, 450, 273]]
Chk 15700 [[7, 21, 268, 301], [226, 16, 500, 375]]
Chk 15701 [[0, 87, 228, 500], [130, 16, 343, 500]]
Chk 15703 [[540, 151, 633, 461], [434, 164, 550, 480], [78, 171, 235, 526], [221, 143, 350, 344]]
Chk 15705 [[474, 94, 712, 473], [149, 94, 399, 425], [0, 26, 143, 376], [114, 11, 225, 165], [344, 21, 438, 263], [425, 1, 471, 137], [491, 4, 546, 93]]
Chk 15706 [[0, 39, 82, 285], [174, 111, 636, 515], [136, 187, 417, 512]]
Chk 15708 [[29, 72, 420, 787], [314, 89, 525, 701]]
Chk 15709 [[118, 525, 309, 797], [221, 20, 442, 686], [86, 18, 308, 656]]
Chk 15710 [[47, 54, 170, 242], [77, 176, 417, 368], [277, 82, 491, 310]]
Chk 15712 [[464, 219, 581, 429], [196, 199, 361, 512]]
Chk 15713 [[249, 110, 483, 526], [400, 128, 705, 534]]
Chk 15714 [[0, 67, 185, 326], [209, 162, 349, 332], [247, 108, 483, 333]]

Chk 15715 [[432, 40, 800, 589], [356, 212, 589, 452], [172, 218, 429, 433]]
Chk 15716 [[229, 107, 467, 529], [404, 84, 669, 533]]
Chk 15717 [[101, 5, 446, 515], [457, 34, 728, 525], [218, 49, 285, 348]]
Chk 15718 [[0, 64, 160, 533], [583, 121, 770, 533], [110, 131, 350, 533], [397, 54, 655, 533], [0, 52, 46, 136], [99, 47, 143, 127], [57, 45, 102, 112]]
Chk 15719 [[484, 40, 800, 532], [204, 197, 587, 532], [54, 123, 272, 531], [370, 277, 414, 394]]
Chk 15720 [[0, 33, 364, 599], [498, 81, 799, 513]]
Chk 15721 [[0, 68, 114, 572], [525, 76, 740, 576], [64, 76, 398, 576]]
Chk 15722 [[281, 146, 520, 484], [29, 110, 485, 528], [499, 137, 763, 463]]
Chk 15724 [[400, 124, 797, 527], [34, 53, 490, 535]]
Chk 15725 [[103, 273, 456, 530], [303, 245, 507, 530]]
Chk 15726 [[141, 131, 367, 372], [256, 70, 389, 374]]
Chk 15727 [[188, 58, 301, 325], [329, 46, 449, 327]]
Chk 15728 [[501, 103, 793, 568], [19, 80, 371, 580]]
Chk 15729 [[299, 23, 473, 188], [52, 41, 391, 332], [1, 23, 224, 254]]
Chk 15730 [[95, 52, 422, 644], [386, 117, 646, 618], [718, 1, 799, 175]]
Chk 15731 [[189, 102, 652, 534], [367, 28, 755, 533]]
Chk 15732 [[111, 157, 480, 612], [674, 129, 780, 401], [96, 127, 262, 624]]
Chk 15733 [[6, 236, 117, 493], [56, 93, 163, 501], [245, 28, 416, 526], [401, 87, 560, 524]]
Chk 15734 [[0, 11, 335, 800], [233, 19, 488, 795]]
Chk 15735 [[426, 70, 733, 536], [42, 27, 505, 518]]
Chk 15736 [[14, 130, 352, 524], [381, 158, 781, 533], [359, 219, 435, 355]]
Chk 15737 [[24, 221, 133, 529], [99, 87, 319, 641], [253, 185, 372, 424], [502, 179, 601, 496]]
Chk 15738 [[443, 376, 523, 603], [499, 221, 619, 610]]
Chk 15739 [[122, 65, 202, 191], [220, 63, 284, 157], [282, 48, 384, 230], [241, 35, 478, 330]]
Chk 15740 [[200, 95, 499, 499], [0, 70, 263, 499]]
Chk 15741 [[213, 0, 799, 705], [8, 13, 498, 730]]
Chk 15743 [[316, 151, 389, 306], [347, 164, 455, 405], [608, 68, 790, 528]]
Chk 15745 [[50, 133, 125, 460], [111, 103, 194, 487]]
Chk 15746 [[193, 43, 345, 477], [320, 48, 451, 496]]
Chk 15747 [[339, 151, 465, 434], [156, 152, 297, 439]]
Chk 15748 [[571, 93, 738, 429], [434, 114, 600, 414], [103, 22, 421, 490]]
Chk 15749 [[175, 173, 345, 489], [377, 277, 524, 515], [582, 170, 792, 517]]
Chk 15750 [[381, 99, 787, 569], [139, 167, 410, 491]]
Chk 15751 [[71, 102, 228, 524], [210, 91, 395, 518], [312, 66, 557, 530], [498, 109, 674, 527]]
Chk 15752 [[434, 227, 675, 573], [12, 53, 239, 599], [195, 295, 430, 528]]
Chk 15753 [[124, 18, 711, 532], [21, 118, 357, 532]]
Chk 15754 [[290, 228, 595, 599], [586, 146, 771, 599], [0, 170, 188, 599]]
Chk 15755 [[183, 155, 365, 505], [413, 103, 754, 476]]
Chk 15756 [[417, 43, 799, 599], [0, 65, 367, 599]]
Chk 15757 [[93, 11, 442, 481], [374, 0, 778, 416], [0, 63, 140, 492]]
Chk 15758 [[10, 88, 162, 295], [149, 71, 382, 267]]
Chk 15759 [[49, 235, 241, 658], [150, 47, 400, 420], [323, 228, 461, 607]]
Chk 15760 [[446, 0, 766, 392], [116, 55, 527, 399]]
Chk 15761 [[207, 59, 517, 365], [214, 46, 348, 346]]
Chk 15762 [[20, 57, 470, 523], [358, 124, 781, 517]]
Chk 15763 [[5, 25, 270, 399], [182, 30, 465, 399]]
Chk 15764 [[0, 66, 380, 777], [346, 260, 637, 695]]
Chk 15765 [[34, 121, 262, 500], [134, 0, 306, 499]]
Chk 15766 [[383, 56, 770, 553], [31, 116, 561, 570]]
Chk 15767 [[180, 108, 527, 558], [1, 291, 378, 578]]
Chk 15768 [[366, 7, 499, 296], [9, 53, 270, 360], [120, 0, 309, 271]]
Chk 15769 [[2, 99, 276, 526], [435, 139, 693, 472], [378, 127, 578, 424]]
Chk 15770 [[264, 292, 440, 532], [394, 300, 619, 532]]
Chk 15771 [[208, 547, 531, 743], [5, 364, 399, 796]]
Chk 15774 [[470, 33, 726, 532], [156, 113, 289, 532], [375, 111, 538, 532], [252, 120, 363, 532]]
Chk 15775 [[13, 0, 269, 535], [245, 233, 362, 532], [375, 216, 605, 532]]
Chk 15776 [[470, 156, 642, 598], [247, 201, 405, 599]]
Chk 15777 [[50, 5, 347, 599], [445, 110, 688, 525]]
Chk 15778 [[0, 42, 206, 329], [290, 7, 498, 332], [154, 39, 321, 327]]
Chk 15779 [[0, 65, 274, 598], [421, 105, 729, 590], [492, 274, 757, 600]]
Chk 15781 [[274, 157, 380, 368], [100, 174, 151, 369], [159, 195, 220, 343]]
Chk 15782 [[99, 144, 459, 453], [369, 45, 800, 529]]
Chk 15783 [[158, 416, 257, 699], [327, 245, 469, 717]]
Chk 15784 [[471, 61, 592, 402], [187, 113, 384, 368], [4, 33, 62, 128], [383, 106, 477, 453]]
Chk 15785 [[238, 249, 298, 511], [372, 264, 447, 515]]
Chk 15787 [[112, 102, 178, 223], [87, 6, 177, 153]]
Chk 15791 [[136, 44, 360, 469], [521, 160, 639, 471]]
Chk 15793 [[117, 139, 261, 432], [344, 160, 482, 429], [252, 152, 365, 436], [94, 154, 195, 400]]
Chk 15794 [[119, 109, 214, 300], [556, 145, 616, 262], [168, 86, 260, 317]]
Chk 15795 [[211, 227, 365, 594], [90, 266, 189, 545]]
Chk 15796 [[213, 178, 284, 301], [47, 213, 170, 392]]
Chk 15799 [[191, 155, 268, 332], [41, 166, 118, 331]]
Chk 15800 [[196, 123, 334, 432], [66, 108, 219, 362], [0, 127, 55, 355], [406, 93, 479, 277]]
Chk 15805 [[298, 85, 425, 382], [513, 66, 588, 321], [0, 174, 190, 377], [576, 73, 639, 307]]
Chk 15806 [[4, 43, 331, 565], [380, 123, 660, 569], [680, 165, 988, 567]]
Chk 15807 [[444, 212, 562, 535], [231, 272, 355, 537]]
Chk 15808 [[161, 422, 275, 833], [430, 395, 504, 851]]
Chk 15809 [[164, 253, 272, 612], [238, 269, 360, 617], [95, 260, 182, 621]]
Chk 15810 [[744, 110, 830, 269], [229, 296, 506, 626]]
Chk 15813 [[258, 153, 396, 630], [48, 162, 205, 616]]
Chk 15815 [[131, 333, 625, 1020], [4, 157, 276, 1020]]
Chk 15816 [[363, 115, 639, 473], [1, 95, 213, 460]]
Chk 15817 [[399, 253, 633, 538], [212, 161, 323, 428], [709, 82, 811, 229], [758, 248, 888, 489]]
Chk 15818 [[351, 107, 503, 334], [415, 121, 639, 479], [43, 119, 409, 479]]
Chk 15819 [[300, 53, 393, 349], [443, 45, 526, 343], [110, 28, 220, 415]]
Chk 15821 [[185, 455, 294, 652], [2, 516, 92, 676], [289, 318, 411, 446]]
Chk 15822 [[404, 77, 616, 445], [188, 290, 379, 711]]
Chk 15823 [[169, 244, 248, 408], [255, 148, 354, 323], [254, 257, 368, 384]]
Chk 15824 [[108, 90, 248, 428], [216, 97, 334, 422], [310, 124, 423, 388], [392, 102, 543, 411]]
Chk 15825 [[419, 72, 558, 330], [60, 208, 192, 478]]
Chk 15826 [[171, 161, 539, 766], [472, 46, 1014, 764]]
Chk 15828 [[600, 173, 832, 554], [432, 56, 710, 493]]
Chk 15830 [[19, 0, 255, 423], [324, 3, 574, 202]]
Chk 15831 [[539, 234, 591, 424], [585, 168, 637, 435], [240, 79, 383, 219], [153, 111, 215, 221], [7, 165, 72, 312]]

error: OpenCV(4.7.0) /Users/runner/miniforge3/conda-bld/libopencv_1675730072788/work/modules/imgproc/src/resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

In [ ]:
df_ne_an.to_csv('dataset/annotations1.csv',index=False)
df_ne_an

In [ ]:
# img = cv2.imread("dataset/image/00000.jpg")

# cv2.imshow('sample image',img)

# cv2.imwrite(, img)

In [ ]:
# import cv2
# import matplotlib.pyplot as plt

# image = cv2.imread('dataset/image/00001.jpg')
# indx = [[539, 234, 591, 424], [585, 168, 637, 435], [240, 79, 383, 219], [153, 111, 215, 221], [7, 165, 72, 312]]
# indx = indx[1]

# height, width, channels = image.shape
# start_point = (indx[0],indx[1])
# end_point = (indx[2], indx[3])
# color = (0,0,255)
# thickness = 5

# image = cv2.rectangle(image, start_point, end_point, color, thickness)
# # cv2.imshow('Rectangle',image)

# image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
# plt.imshow(image)
# plt.show()